open Database
open BayesianBody_008
let db = db 
|> Map.add "pickled" { in_spam=0; in_ham=3}
|> Map.add "pickles" { in_spam=0; in_ham=3}
|> Map.add "pickmarkseen" { in_spam=0; in_ham=4}
|> Map.add "picks" { in_spam=1; in_ham=8}
|> Map.add "pics" { in_spam=8; in_ham=6}
|> Map.add "pictograms" { in_spam=0; in_ham=3}
|> Map.add "picture" { in_spam=9; in_ham=34}
|> Map.add "pictures" { in_spam=1; in_ham=19}
|> Map.add "pid" { in_spam=1; in_ham=3}
|> Map.add "pie" { in_spam=5; in_ham=3}
|> Map.add "piece" { in_spam=3; in_ham=31}
|> Map.add "pieces" { in_spam=4; in_ham=4}
|> Map.add "pig" { in_spam=0; in_ham=5}
|> Map.add "piggy" { in_spam=0; in_ham=3}
|> Map.add "piles" { in_spam=2; in_ham=4}
|> Map.add "pill" { in_spam=4; in_ham=2}
|> Map.add "pillow" { in_spam=0; in_ham=4}
|> Map.add "pills" { in_spam=2; in_ham=5}
|> Map.add "pilot" { in_spam=1; in_ham=2}
|> Map.add "pilots" { in_spam=1; in_ham=3}
|> Map.add "pine" { in_spam=0; in_ham=5}
|> Map.add "ping" { in_spam=0; in_ham=4}
|> Map.add "pingback" { in_spam=0; in_ham=3}
|> Map.add "pinnacle" { in_spam=0; in_ham=3}
|> Map.add "pinpoint" { in_spam=0; in_ham=3}
|> Map.add "pioneer" { in_spam=0; in_ham=6}
|> Map.add "pioneered" { in_spam=0; in_ham=8}
|> Map.add "pioneering" { in_spam=0; in_ham=24}
|> Map.add "pioneers" { in_spam=0; in_ham=7}
|> Map.add "pipe" { in_spam=2; in_ham=8}
|> Map.add "pipeline" { in_spam=0; in_ham=5}
|> Map.add "pipermail" { in_spam=0; in_ham=7}
|> Map.add "piping" { in_spam=0; in_ham=3}
|> Map.add "piracy" { in_spam=1; in_ham=9}
|> Map.add "pirate" { in_spam=0; in_ham=3}
|> Map.add "pirated" { in_spam=0; in_ham=3}
|> Map.add "pirates" { in_spam=0; in_ham=6}
|> Map.add "pissed" { in_spam=0; in_ham=6}
|> Map.add "pit" { in_spam=0; in_ham=3}
|> Map.add "pitch" { in_spam=1; in_ham=3}
|> Map.add "pitching" { in_spam=0; in_ham=4}
|> Map.add "pitfalls" { in_spam=0; in_ham=14}
|> Map.add "pitt" { in_spam=1; in_ham=4}
|> Map.add "pittsburg" { in_spam=0; in_ham=4}
|> Map.add "pittstate" { in_spam=0; in_ham=4}
|> Map.add "pity" { in_spam=0; in_ham=7}
|> Map.add "pixel" { in_spam=1; in_ham=2}
|> Map.add "pkglist" { in_spam=0; in_ham=5}
|> Map.add "pki" { in_spam=0; in_ham=4}
|> Map.add "place" { in_spam=35; in_ham=146}
|> Map.add "placed" { in_spam=11; in_ham=17}
|> Map.add "placement" { in_spam=1; in_ham=3}
|> Map.add "places" { in_spam=13; in_ham=50}
|> Map.add "placing" { in_spam=8; in_ham=3}
|> Map.add "plagued" { in_spam=1; in_ham=6}
|> Map.add "plain" { in_spam=10; in_ham=33}
|> Map.add "plain'" { in_spam=0; in_ham=4}
|> Map.add "plainly" { in_spam=0; in_ham=4}
|> Map.add "plaintext" { in_spam=0; in_ham=3}
|> Map.add "plan" { in_spam=43; in_ham=51}
|> Map.add "plane" { in_spam=0; in_ham=6}
|> Map.add "planes" { in_spam=0; in_ham=5}
|> Map.add "planet" { in_spam=2; in_ham=17}
|> Map.add "planets" { in_spam=0; in_ham=5}
|> Map.add "planned" { in_spam=1; in_ham=13}
|> Map.add "planning" { in_spam=8; in_ham=28}
|> Map.add "plans" { in_spam=12; in_ham=32}
|> Map.add "plant" { in_spam=1; in_ham=8}
|> Map.add "planta" { in_spam=0; in_ham=42}
|> Map.add "plants" { in_spam=0; in_ham=4}
|> Map.add "plaque" { in_spam=0; in_ham=3}
|> Map.add "plasma" { in_spam=0; in_ham=3}
|> Map.add "plastic" { in_spam=0; in_ham=3}
|> Map.add "plate" { in_spam=1; in_ham=3}
|> Map.add "plates" { in_spam=2; in_ham=2}
|> Map.add "platform" { in_spam=1; in_ham=81}
|> Map.add "platforms" { in_spam=0; in_ham=14}
|> Map.add "platinum" { in_spam=6; in_ham=0}
|> Map.add "plausible" { in_spam=0; in_ham=10}
|> Map.add "play" { in_spam=14; in_ham=74}
|> Map.add "playback" { in_spam=1; in_ham=9}
|> Map.add "played" { in_spam=4; in_ham=21}
|> Map.add "player" { in_spam=2; in_ham=20}
|> Map.add "players" { in_spam=4; in_ham=16}
|> Map.add "playing" { in_spam=14; in_ham=46}
|> Map.add "playlist" { in_spam=0; in_ham=3}
|> Map.add "plays" { in_spam=2; in_ham=8}
|> Map.add "plaza" { in_spam=0; in_ham=4}
|> Map.add "plc" { in_spam=1; in_ham=3}
|> Map.add "please" { in_spam=266; in_ham=150}
|> Map.add "pleased" { in_spam=3; in_ham=8}
|> Map.add "pleasure" { in_spam=5; in_ham=4}
|> Map.add "pledge" { in_spam=5; in_ham=2}
|> Map.add "plenty" { in_spam=5; in_ham=21}
|> Map.add "plot" { in_spam=3; in_ham=5}
|> Map.add "plucker" { in_spam=0; in_ham=3}
|> Map.add "plug" { in_spam=2; in_ham=9}
|> Map.add "plugged" { in_spam=0; in_ham=5}
|> Map.add "plugin" { in_spam=0; in_ham=17}
|> Map.add "plugins" { in_spam=0; in_ham=18}
|> Map.add "plus" { in_spam=29; in_ham=29}
|> Map.add "pluto" { in_spam=0; in_ham=5}
|> Map.add "plutocracy" { in_spam=0; in_ham=3}
|> Map.add "png" { in_spam=0; in_ham=3}
|> Map.add "pnni" { in_spam=0; in_ham=6}
|> Map.add "pobox" { in_spam=0; in_ham=23}
|> Map.add "pocket" { in_spam=12; in_ham=4}
|> Map.add "pockets" { in_spam=4; in_ham=4}
|> Map.add "pod" { in_spam=1; in_ham=2}
|> Map.add "podium" { in_spam=0; in_ham=5}
|> Map.add "pofrweul" { in_spam=0; in_ham=3}
|> Map.add "point" { in_spam=23; in_ham=192}
|> Map.add "pointed" { in_spam=0; in_ham=16}
|> Map.add "pointer" { in_spam=0; in_ham=7}
|> Map.add "pointers" { in_spam=0; in_ham=7}
|> Map.add "pointing" { in_spam=0; in_ham=21}
|> Map.add "points" { in_spam=8; in_ham=56}
|> Map.add "poised" { in_spam=0; in_ham=3}
|> Map.add "poison" { in_spam=0; in_ham=4}
|> Map.add "poke" { in_spam=0; in_ham=4}
|> Map.add "poked" { in_spam=0; in_ham=5}
|> Map.add "poker" { in_spam=4; in_ham=3}
|> Map.add "poking" { in_spam=0; in_ham=3}
|> Map.add "police" { in_spam=4; in_ham=37}
|> Map.add "policeman" { in_spam=0; in_ham=3}
|> Map.add "policies" { in_spam=9; in_ham=16}
|> Map.add "policing" { in_spam=0; in_ham=3}
|> Map.add "policy" { in_spam=22; in_ham=36}
|> Map.add "polite" { in_spam=0; in_ham=6}
|> Map.add "political" { in_spam=13; in_ham=64}
|> Map.add "politically" { in_spam=0; in_ham=8}
|> Map.add "politician" { in_spam=0; in_ham=9}
|> Map.add "politicians" { in_spam=0; in_ham=14}
|> Map.add "politics" { in_spam=2; in_ham=54}
|> Map.add "poll" { in_spam=0; in_ham=11}
|> Map.add "polls" { in_spam=0; in_ham=5}
|> Map.add "polluted" { in_spam=0; in_ham=3}
|> Map.add "polygons" { in_spam=0; in_ham=3}
|> Map.add "ponce" { in_spam=0; in_ham=8}
|> Map.add "pool" { in_spam=2; in_ham=4}
|> Map.add "poor" { in_spam=8; in_ham=30}
|> Map.add "poorest" { in_spam=0; in_ham=3}
|> Map.add "poorly" { in_spam=0; in_ham=7}
|> Map.add "pop" { in_spam=7; in_ham=33}
|> Map.add "pope" { in_spam=0; in_ham=6}
|> Map.add "pops" { in_spam=0; in_ham=5}
|> Map.add "popular" { in_spam=13; in_ham=37}
|> Map.add "popularity" { in_spam=7; in_ham=4}
|> Map.add "population" { in_spam=7; in_ham=44}
|> Map.add "populations" { in_spam=1; in_ham=7}
|> Map.add "popup" { in_spam=0; in_ham=5}
|> Map.add "porn" { in_spam=9; in_ham=6}
|> Map.add "porous" { in_spam=1; in_ham=2}
|> Map.add "port" { in_spam=0; in_ham=24}
|> Map.add "portable" { in_spam=3; in_ham=9}
|> Map.add "portal" { in_spam=1; in_ham=2}
|> Map.add "ported" { in_spam=0; in_ham=9}
|> Map.add "porters" { in_spam=0; in_ham=16}
|> Map.add "portfolio" { in_spam=7; in_ham=9}
|> Map.add "portigal" { in_spam=0; in_ham=4}
|> Map.add "porting" { in_spam=0; in_ham=6}
|> Map.add "portion" { in_spam=6; in_ham=8}
|> Map.add "portions" { in_spam=0; in_ham=15}
|> Map.add "portland" { in_spam=0; in_ham=4}
|> Map.add "ports" { in_spam=0; in_ham=16}
|> Map.add "pos" { in_spam=0; in_ham=7}
|> Map.add "pose" { in_spam=0; in_ham=7}
|> Map.add "posed" { in_spam=1; in_ham=4}
|> Map.add "poses" { in_spam=0; in_ham=3}
|> Map.add "posit" { in_spam=0; in_ham=3}
|> Map.add "position" { in_spam=31; in_ham=25}
|> Map.add "positioned" { in_spam=0; in_ham=6}
|> Map.add "positioning" { in_spam=0; in_ham=8}
|> Map.add "positions" { in_spam=1; in_ham=15}
|> Map.add "positive" { in_spam=3; in_ham=28}
|> Map.add "positives" { in_spam=0; in_ham=22}
|> Map.add "posix" { in_spam=0; in_ham=5}
|> Map.add "possess" { in_spam=1; in_ham=3}
|> Map.add "possesses" { in_spam=0; in_ham=4}
|> Map.add "possession" { in_spam=5; in_ham=4}
|> Map.add "possibility" { in_spam=1; in_ham=18}
|> Map.add "possible" { in_spam=33; in_ham=133}
|> Map.add "possibly" { in_spam=2; in_ham=29}
|> Map.add "post" { in_spam=63; in_ham=90}
|> Map.add "post-bubble" { in_spam=0; in_ham=6}
|> Map.add "post-gazette" { in_spam=0; in_ham=3}
|> Map.add "postage" { in_spam=10; in_ham=2}
|> Map.add "postal" { in_spam=13; in_ham=1}
|> Map.add "postcard" { in_spam=1; in_ham=2}
|> Map.add "posted" { in_spam=2; in_ham=100}
|> Map.add "poster" { in_spam=0; in_ham=6}
|> Map.add "postfix" { in_spam=0; in_ham=5}
|> Map.add "postgresql" { in_spam=1; in_ham=8}
|> Map.add "posting" { in_spam=1; in_ham=23}
|> Map.add "postings" { in_spam=1; in_ham=5}
|> Map.add "postman" { in_spam=3; in_ham=1}
|> Map.add "postmasters" { in_spam=0; in_ham=3}
|> Map.add "posts" { in_spam=1; in_ham=14}
|> Map.add "posture" { in_spam=0; in_ham=3}
|> Map.add "potatoes" { in_spam=3; in_ham=1}
|> Map.add "potent" { in_spam=2; in_ham=5}
|> Map.add "potential" { in_spam=19; in_ham=40}
|> Map.add "potentially" { in_spam=2; in_ham=17}
|> Map.add "pouches" { in_spam=8; in_ham=0}
|> Map.add "pound" { in_spam=2; in_ham=7}
|> Map.add "pounds" { in_spam=10; in_ham=1}
|> Map.add "pour" { in_spam=2; in_ham=2}
|> Map.add "poverty" { in_spam=2; in_ham=23}
|> Map.add "powell" { in_spam=0; in_ham=5}
|> Map.add "powell's" { in_spam=0; in_ham=4}
|> Map.add "power" { in_spam=15; in_ham=60}
|> Map.add "powerbook" { in_spam=0; in_ham=5}
|> Map.add "powered" { in_spam=2; in_ham=6}
|> Map.add "powerful" { in_spam=17; in_ham=28}
|> Map.add "powerhouse" { in_spam=2; in_ham=8}
|> Map.add "powerpoint" { in_spam=3; in_ham=4}
|> Map.add "powers" { in_spam=2; in_ham=27}
|> Map.add "ppl" { in_spam=1; in_ham=2}
|> Map.add "ppp" { in_spam=0; in_ham=4}
|> Map.add "pppoe" { in_spam=0; in_ham=4}
|> Map.add "practical" { in_spam=7; in_ham=16}
|> Map.add "practically" { in_spam=3; in_ham=15}
|> Map.add "practice" { in_spam=2; in_ham=42}
|> Map.add "practiced" { in_spam=0; in_ham=3}
|> Map.add "practices" { in_spam=8; in_ham=15}
|> Map.add "praeterea" { in_spam=0; in_ham=4}
|> Map.add "pragmatic" { in_spam=1; in_ham=2}
|> Map.add "prairie" { in_spam=1; in_ham=2}
|> Map.add "praise" { in_spam=0; in_ham=3}
|> Map.add "prakash" { in_spam=0; in_ham=8}
|> Map.add "pravda" { in_spam=0; in_ham=3}
|> Map.add "pray" { in_spam=1; in_ham=3}
|> Map.add "prayer" { in_spam=0; in_ham=3}
|> Map.add "pre" { in_spam=3; in_ham=8}
|> Map.add "pre-forms" { in_spam=0; in_ham=3}
|> Map.add "pre-recorded" { in_spam=4; in_ham=2}
|> Map.add "preaty" { in_spam=0; in_ham=4}
|> Map.add "precedence" { in_spam=0; in_ham=6}
|> Map.add "precedents" { in_spam=1; in_ham=3}
|> Map.add "preceding" { in_spam=1; in_ham=2}
|> Map.add "precious" { in_spam=3; in_ham=1}
|> Map.add "precise" { in_spam=0; in_ham=5}
|> Map.add "precisely" { in_spam=2; in_ham=13}
|> Map.add "precision" { in_spam=0; in_ham=3}
|> Map.add "preclude" { in_spam=0; in_ham=3}
|> Map.add "predecessors" { in_spam=1; in_ham=2}
|> Map.add "predict" { in_spam=6; in_ham=6}
|> Map.add "predictable" { in_spam=0; in_ham=5}
|> Map.add "predicted" { in_spam=0; in_ham=7}
|> Map.add "predicting" { in_spam=0; in_ham=45}
|> Map.add "prefer" { in_spam=5; in_ham=33}
|> Map.add "preferably" { in_spam=0; in_ham=4}
|> Map.add "preference" { in_spam=1; in_ham=6}
|> Map.add "preferences" { in_spam=0; in_ham=85}
|> Map.add "preferrably" { in_spam=0; in_ham=3}
|> Map.add "preferred" { in_spam=4; in_ham=12}
|> Map.add "preferring" { in_spam=0; in_ham=4}
|> Map.add "prefix" { in_spam=1; in_ham=7}
|> Map.add "prefixes" { in_spam=0; in_ham=3}
|> Map.add "prefs" { in_spam=0; in_ham=10}
|> Map.add "pregnancy" { in_spam=1; in_ham=2}
|> Map.add "pregnant" { in_spam=0; in_ham=3}
|> Map.add "preloading" { in_spam=0; in_ham=3}
|> Map.add "premeditated" { in_spam=0; in_ham=3}
|> Map.add "premier" { in_spam=4; in_ham=1}
|> Map.add "premiere" { in_spam=0; in_ham=3}
|> Map.add "premise" { in_spam=0; in_ham=7}
|> Map.add "premises" { in_spam=1; in_ham=3}
|> Map.add "premium" { in_spam=13; in_ham=3}
|> Map.add "prep" { in_spam=1; in_ham=6}
|> Map.add "preparation" { in_spam=4; in_ham=2}
|> Map.add "prepare" { in_spam=6; in_ham=7}
|> Map.add "prepared" { in_spam=2; in_ham=22}
|> Map.add "preparing" { in_spam=2; in_ham=16}
|> Map.add "prereq" { in_spam=0; in_ham=4}
|> Map.add "preschool" { in_spam=3; in_ham=1}
|> Map.add "prescription" { in_spam=9; in_ham=1}
|> Map.add "presence" { in_spam=1; in_ham=16}
|> Map.add "present" { in_spam=19; in_ham=28}
|> Map.add "presentation" { in_spam=6; in_ham=3}
|> Map.add "presented" { in_spam=12; in_ham=7}
|> Map.add "presently" { in_spam=11; in_ham=1}
|> Map.add "presents" { in_spam=1; in_ham=5}
|> Map.add "preserve" { in_spam=2; in_ham=10}
|> Map.add "preserved" { in_spam=0; in_ham=6}
|> Map.add "preserving" { in_spam=0; in_ham=5}
|> Map.add "presidency" { in_spam=2; in_ham=3}
|> Map.add "president" { in_spam=23; in_ham=49}
|> Map.add "president's" { in_spam=2; in_ham=6}
|> Map.add "presidential" { in_spam=0; in_ham=8}
|> Map.add "presort" { in_spam=0; in_ham=3}
|> Map.add "presorting" { in_spam=0; in_ham=3}
|> Map.add "press" { in_spam=9; in_ham=53}
|> Map.add "pressed" { in_spam=1; in_ham=2}
|> Map.add "presses" { in_spam=1; in_ham=3}
|> Map.add "pressing" { in_spam=1; in_ham=4}
|> Map.add "pressure" { in_spam=1; in_ham=13}
|> Map.add "pressurized" { in_spam=0; in_ham=4}
|> Map.add "presumably" { in_spam=0; in_ham=21}
|> Map.add "presume" { in_spam=0; in_ham=11}
|> Map.add "presumed" { in_spam=1; in_ham=3}
|> Map.add "presumption" { in_spam=0; in_ham=3}
|> Map.add "pretend" { in_spam=2; in_ham=2}
|> Map.add "pretending" { in_spam=0; in_ham=3}
|> Map.add "pretext" { in_spam=0; in_ham=3}
|> Map.add "pretty" { in_spam=9; in_ham=114}
|> Map.add "prev" { in_spam=0; in_ham=4}
|> Map.add "prevalence" { in_spam=0; in_ham=4}
|> Map.add "prevent" { in_spam=7; in_ham=22}
|> Map.add "prevented" { in_spam=0; in_ham=5}
|> Map.add "preventing" { in_spam=0; in_ham=8}
|> Map.add "prevention" { in_spam=0; in_ham=3}
|> Map.add "prevents" { in_spam=0; in_ham=9}
|> Map.add "previous" { in_spam=6; in_ham=35}
|> Map.add "previously" { in_spam=14; in_ham=40}
|> Map.add "prey" { in_spam=15; in_ham=4}
|> Map.add "price" { in_spam=66; in_ham=32}
|> Map.add "price-fixing" { in_spam=0; in_ham=3}
|> Map.add "priced" { in_spam=4; in_ham=9}
|> Map.add "prices" { in_spam=33; in_ham=15}
|> Map.add "pricing" { in_spam=10; in_ham=5}
|> Map.add "prid" { in_spam=0; in_ham=3}
|> Map.add "primarily" { in_spam=2; in_ham=16}
|> Map.add "primary" { in_spam=14; in_ham=27}
|> Map.add "prime" { in_spam=1; in_ham=8}
|> Map.add "primitive" { in_spam=0; in_ham=6}
|> Map.add "prince" { in_spam=4; in_ham=5}
|> Map.add "princeton" { in_spam=0; in_ham=4}
|> Map.add "principal" { in_spam=4; in_ham=3}
|> Map.add "principle" { in_spam=1; in_ham=11}
|> Map.add "principles" { in_spam=4; in_ham=7}
|> Map.add "pringles" { in_spam=0; in_ham=4}
|> Map.add "print" { in_spam=15; in_ham=43}
|> Map.add "printed" { in_spam=3; in_ham=9}
|> Map.add "printer" { in_spam=5; in_ham=10}
|> Map.add "printers" { in_spam=1; in_ham=2}
|> Map.add "printf" { in_spam=0; in_ham=5}
|> Map.add "printing" { in_spam=5; in_ham=12}
|> Map.add "prints" { in_spam=0; in_ham=6}
|> Map.add "prior" { in_spam=4; in_ham=28}
|> Map.add "priority" { in_spam=3; in_ham=16}
|> Map.add "prison" { in_spam=2; in_ham=6}
|> Map.add "priv" { in_spam=0; in_ham=3}
|> Map.add "privacy" { in_spam=15; in_ham=13}
|> Map.add "private" { in_spam=54; in_ham=40}
|> Map.add "privately" { in_spam=1; in_ham=11}
|> Map.add "privilege" { in_spam=3; in_ham=6}
|> Map.add "privileged" { in_spam=0; in_ham=9}
|> Map.add "privileges" { in_spam=0; in_ham=8}
|> Map.add "prize" { in_spam=2; in_ham=12}
|> Map.add "prizemama" { in_spam=10; in_ham=0}
|> Map.add "prizes" { in_spam=2; in_ham=3}
|> Map.add "pro" { in_spam=9; in_ham=7}
|> Map.add "proactive" { in_spam=0; in_ham=5}
|> Map.add "prob" { in_spam=0; in_ham=8}
|> Map.add "probability" { in_spam=0; in_ham=12}
|> Map.add "probably" { in_spam=15; in_ham=224}
|> Map.add "probe" { in_spam=0; in_ham=5}
|> Map.add "problem" { in_spam=20; in_ham=281}
|> Map.add "problematic" { in_spam=0; in_ham=7}
|> Map.add "problems" { in_spam=24; in_ham=144}
|> Map.add "proc" { in_spam=0; in_ham=15}
|> Map.add "procedure" { in_spam=0; in_ham=22}
|> Map.add "procedures" { in_spam=8; in_ham=4}
|> Map.add "proceed" { in_spam=7; in_ham=8}
|> Map.add "proceeding" { in_spam=0; in_ham=4}
|> Map.add "proceedings" { in_spam=0; in_ham=3}
|> Map.add "process" { in_spam=23; in_ham=79}
|> Map.add "processed" { in_spam=7; in_ham=5}
|> Map.add "processes" { in_spam=2; in_ham=34}
|> Map.add "processing" { in_spam=11; in_ham=36}
|> Map.add "procession" { in_spam=0; in_ham=4}
|> Map.add "processor" { in_spam=1; in_ham=7}
|> Map.add "processors" { in_spam=0; in_ham=6}
|> Map.add "proclaimed" { in_spam=1; in_ham=5}
|> Map.add "procmail" { in_spam=0; in_ham=50}
|> Map.add "procmailrc" { in_spam=0; in_ham=17}
|> Map.add "procurement" { in_spam=4; in_ham=3}
|> Map.add "produce" { in_spam=5; in_ham=25}
|> Map.add "produced" { in_spam=2; in_ham=28}
|> Map.add "producer" { in_spam=4; in_ham=3}
|> Map.add "producers" { in_spam=2; in_ham=8}
|> Map.add "produces" { in_spam=0; in_ham=5}
|> Map.add "producing" { in_spam=1; in_ham=9}
|> Map.add "product" { in_spam=41; in_ham=61}
|> Map.add "production" { in_spam=1; in_ham=22}
|> Map.add "productive" { in_spam=0; in_ham=14}
|> Map.add "productivity" { in_spam=0; in_ham=5}
|> Map.add "products" { in_spam=61; in_ham=32}
|> Map.add "prof" { in_spam=2; in_ham=5}
|> Map.add "profession" { in_spam=1; in_ham=2}
|> Map.add "professional" { in_spam=65; in_ham=23}
|> Map.add "professor" { in_spam=2; in_ham=9}
|> Map.add "profile" { in_spam=4; in_ham=16}
|> Map.add "profiled" { in_spam=5; in_ham=1}
|> Map.add "profiler" { in_spam=0; in_ham=3}
|> Map.add "profiling" { in_spam=0; in_ham=4}
|> Map.add "profit" { in_spam=15; in_ham=12}
|> Map.add "profitable" { in_spam=28; in_ham=4}
|> Map.add "profits" { in_spam=17; in_ham=5}
|> Map.add "profound" { in_spam=1; in_ham=6}
|> Map.add "progid" { in_spam=31; in_ham=0}
|> Map.add "program" { in_spam=50; in_ham=71}
|> Map.add "program's" { in_spam=0; in_ham=4}
|> Map.add "programme" { in_spam=3; in_ham=11}
|> Map.add "programmed" { in_spam=0; in_ham=6}
|> Map.add "programmer" { in_spam=0; in_ham=18}
|> Map.add "programmers" { in_spam=4; in_ham=8}
|> Map.add "programming" { in_spam=3; in_ham=35}
|> Map.add "programs" { in_spam=34; in_ham=33}
|> Map.add "progress" { in_spam=9; in_ham=31}
|> Map.add "prohibited" { in_spam=8; in_ham=6}
|> Map.add "prohibiting" { in_spam=8; in_ham=1}
|> Map.add "project" { in_spam=10; in_ham=79}
|> Map.add "projection" { in_spam=4; in_ham=1}
|> Map.add "projects" { in_spam=8; in_ham=30}
|> Map.add "proliferate" { in_spam=1; in_ham=7}
|> Map.add "prominent" { in_spam=2; in_ham=4}
|> Map.add "promiscuity" { in_spam=0; in_ham=13}
|> Map.add "promiscuous" { in_spam=0; in_ham=18}
|> Map.add "promise" { in_spam=16; in_ham=27}
|> Map.add "promised" { in_spam=7; in_ham=14}
|> Map.add "promises" { in_spam=1; in_ham=14}
|> Map.add "promising" { in_spam=0; in_ham=12}
|> Map.add "promo" { in_spam=1; in_ham=2}
|> Map.add "promote" { in_spam=10; in_ham=10}
|> Map.add "promoting" { in_spam=1; in_ham=10}
|> Map.add "promotion" { in_spam=23; in_ham=3}
|> Map.add "promotional" { in_spam=6; in_ham=1}
|> Map.add "promotions" { in_spam=6; in_ham=1}
|> Map.add "prompt" { in_spam=20; in_ham=10}
|> Map.add "prompted" { in_spam=0; in_ham=3}
|> Map.add "promptly" { in_spam=4; in_ham=2}
|> Map.add "pronounced" { in_spam=0; in_ham=3}
|> Map.add "proof" { in_spam=4; in_ham=16}
|> Map.add "propagate" { in_spam=1; in_ham=3}
|> Map.add "propagation" { in_spam=0; in_ham=3}
|> Map.add "proper" { in_spam=12; in_ham=24}
|> Map.add "properly" { in_spam=3; in_ham=10}
|> Map.add "properties" { in_spam=10; in_ham=5}
|> Map.add "property" { in_spam=5; in_ham=29}
|> Map.add "proponent" { in_spam=0; in_ham=3}
|> Map.add "proportion" { in_spam=0; in_ham=5}
|> Map.add "proportional" { in_spam=0; in_ham=3}
|> Map.add "proposal" { in_spam=19; in_ham=5}
|> Map.add "proposals" { in_spam=3; in_ham=4}
|> Map.add "propose" { in_spam=4; in_ham=10}
|> Map.add "proposed" { in_spam=12; in_ham=25}
|> Map.add "proposition" { in_spam=3; in_ham=4}
|> Map.add "proprietary" { in_spam=2; in_ham=20}
|> Map.add "prosecute" { in_spam=0; in_ham=7}
|> Map.add "prosecuted" { in_spam=0; in_ham=3}
|> Map.add "prosecution" { in_spam=0; in_ham=4}
|> Map.add "prospect" { in_spam=2; in_ham=5}
|> Map.add "prospective" { in_spam=4; in_ham=1}
|> Map.add "prospects" { in_spam=7; in_ham=2}
|> Map.add "prosper" { in_spam=0; in_ham=3}
|> Map.add "prosperous" { in_spam=0; in_ham=7}
|> Map.add "prostitute" { in_spam=0; in_ham=9}
|> Map.add "prostitute'" { in_spam=0; in_ham=3}
|> Map.add "prostitution" { in_spam=0; in_ham=3}
|> Map.add "protecion" { in_spam=5; in_ham=0}
|> Map.add "protect" { in_spam=31; in_ham=37}
|> Map.add "protected" { in_spam=3; in_ham=19}
|> Map.add "protecting" { in_spam=3; in_ham=10}
|> Map.add "protection" { in_spam=16; in_ham=28}
|> Map.add "protective" { in_spam=4; in_ham=2}
|> Map.add "protector" { in_spam=2; in_ham=3}
|> Map.add "protects" { in_spam=0; in_ham=5}
|> Map.add "proteon" { in_spam=0; in_ham=6}
|> Map.add "protest" { in_spam=1; in_ham=9}
|> Map.add "protestant" { in_spam=0; in_ham=3}
|> Map.add "protested" { in_spam=0; in_ham=5}
|> Map.add "protesters" { in_spam=0; in_ham=4}
|> Map.add "protesting" { in_spam=1; in_ham=10}
|> Map.add "protestors" { in_spam=0; in_ham=5}
|> Map.add "protests" { in_spam=1; in_ham=10}
|> Map.add "protocol" { in_spam=2; in_ham=17}
|> Map.add "protocols" { in_spam=0; in_ham=8}
|> Map.add "prototype" { in_spam=0; in_ham=8}
|> Map.add "prototypes" { in_spam=0; in_ham=3}
|> Map.add "proud" { in_spam=1; in_ham=5}
|> Map.add "prove" { in_spam=1; in_ham=9}
|> Map.add "proved" { in_spam=8; in_ham=3}
|> Map.add "proven" { in_spam=23; in_ham=23}
|> Map.add "provide" { in_spam=50; in_ham=86}
|> Map.add "provided" { in_spam=16; in_ham=58}
|> Map.add "provider" { in_spam=2; in_ham=16}
|> Map.add "providers" { in_spam=3; in_ham=8}
|> Map.add "provides" { in_spam=8; in_ham=40}
|> Map.add "providing" { in_spam=11; in_ham=25}
|> Map.add "province" { in_spam=1; in_ham=13}
|> Map.add "provincial" { in_spam=0; in_ham=5}
|> Map.add "proving" { in_spam=0; in_ham=7}
|> Map.add "provisions" { in_spam=1; in_ham=6}
|> Map.add "provocative" { in_spam=0; in_ham=7}
|> Map.add "provoking" { in_spam=0; in_ham=6}
|> Map.add "proxy" { in_spam=0; in_ham=14}
|> Map.add "prseocsing" { in_spam=0; in_ham=3}
|> Map.add "prsooscers" { in_spam=0; in_ham=3}
|> Map.add "pst" { in_spam=1; in_ham=2}
|> Map.add "psu" { in_spam=0; in_ham=3}
|> Map.add "psyche" { in_spam=0; in_ham=13}
|> Map.add "psychologist" { in_spam=0; in_ham=5}
|> Map.add "pto" { in_spam=0; in_ham=3}
|> Map.add "ptrmismatch" { in_spam=0; in_ham=3}
|> Map.add "ptts" { in_spam=0; in_ham=3}
|> Map.add "pub" { in_spam=1; in_ham=28}
|> Map.add "pubiltacion" { in_spam=0; in_ham=3}
|> Map.add "public" { in_spam=57; in_ham=106}
|> Map.add "public's" { in_spam=0; in_ham=5}
|> Map.add "publication" { in_spam=9; in_ham=16}
|> Map.add "publications" { in_spam=4; in_ham=6}
|> Map.add "publicity" { in_spam=0; in_ham=4}
|> Map.add "publicly" { in_spam=2; in_ham=6}
|> Map.add "publish" { in_spam=12; in_ham=10}
|> Map.add "published" { in_spam=8; in_ham=32}
|> Map.add "publisher" { in_spam=6; in_ham=8}
|> Map.add "publishers" { in_spam=1; in_ham=7}
|> Map.add "publishes" { in_spam=1; in_ham=2}
|> Map.add "publishing" { in_spam=7; in_ham=11}
|> Map.add "pubs" { in_spam=0; in_ham=4}
|> Map.add "puc" { in_spam=0; in_ham=3}
|> Map.add "pudge" { in_spam=0; in_ham=56}
|> Map.add "puglisi" { in_spam=0; in_ham=8}
|> Map.add "pull" { in_spam=2; in_ham=28}
|> Map.add "pulled" { in_spam=0; in_ham=15}
|> Map.add "pulling" { in_spam=4; in_ham=14}
|> Map.add "pump" { in_spam=2; in_ham=7}
|> Map.add "pun" { in_spam=1; in_ham=2}
|> Map.add "punch" { in_spam=1; in_ham=3}
|> Map.add "punching" { in_spam=0; in_ham=10}
|> Map.add "punctuation" { in_spam=0; in_ham=3}
|> Map.add "punks" { in_spam=0; in_ham=4}
|> Map.add "puppy" { in_spam=0; in_ham=5}
|> Map.add "purchase" { in_spam=47; in_ham=12}
|> Map.add "purchased" { in_spam=11; in_ham=10}
|> Map.add "purchases" { in_spam=1; in_ham=3}
|> Map.add "purchasing" { in_spam=5; in_ham=0}
|> Map.add "pure" { in_spam=1; in_ham=12}
|> Map.add "purely" { in_spam=0; in_ham=8}
|> Map.add "purging" { in_spam=0; in_ham=4}
|> Map.add "purple" { in_spam=3; in_ham=2}
|> Map.add "purpose" { in_spam=14; in_ham=34}
|> Map.add "purposes" { in_spam=11; in_ham=11}
|> Map.add "pursue" { in_spam=2; in_ham=10}
|> Map.add "pursued" { in_spam=0; in_ham=6}
|> Map.add "pursuing" { in_spam=0; in_ham=5}
|> Map.add "pursuit" { in_spam=1; in_ham=6}
|> Map.add "push" { in_spam=1; in_ham=11}
|> Map.add "pushed" { in_spam=0; in_ham=12}
|> Map.add "pushing" { in_spam=1; in_ham=9}
|> Map.add "put" { in_spam=48; in_ham=180}
|> Map.add "puts" { in_spam=0; in_ham=18}
|> Map.add "putting" { in_spam=5; in_ham=34}
|> Map.add "putty" { in_spam=0; in_ham=4}
|> Map.add "puzzled" { in_spam=0; in_ham=4}
|> Map.add "pyramid" { in_spam=0; in_ham=4}
|> Map.add "pystytt" { in_spam=0; in_ham=4}
|> Map.add "python" { in_spam=0; in_ham=67}
|> Map.add "python'" { in_spam=0; in_ham=3}
|> Map.add "python-list" { in_spam=0; in_ham=3}
|> Map.add "pyzor" { in_spam=0; in_ham=5}
|> Map.add "qaeda" { in_spam=0; in_ham=4}
|> Map.add "qed" { in_spam=0; in_ham=3}
|> Map.add "qmail" { in_spam=0; in_ham=10}
|> Map.add "qrpzmc" { in_spam=0; in_ham=6}
|> Map.add "quadruple" { in_spam=0; in_ham=6}
|> Map.add "quaffapint" { in_spam=0; in_ham=3}
|> Map.add "qualified" { in_spam=13; in_ham=0}
|> Map.add "qualify" { in_spam=15; in_ham=9}
|> Map.add "qualifying" { in_spam=3; in_ham=1}
|> Map.add "quality" { in_spam=34; in_ham=42}
|> Map.add "qualms" { in_spam=0; in_ham=3}
|> Map.add "quantities" { in_spam=3; in_ham=3}
|> Map.add "quantum" { in_spam=1; in_ham=2}
|> Map.add "quarry" { in_spam=0; in_ham=3}
|> Map.add "quarter" { in_spam=4; in_ham=12}
|> Map.add "que" { in_spam=2; in_ham=5}
|> Map.add "queen" { in_spam=0; in_ham=4}
|> Map.add "queens" { in_spam=0; in_ham=4}
|> Map.add "queensland" { in_spam=1; in_ham=3}
|> Map.add "queried" { in_spam=0; in_ham=3}
|> Map.add "queries" { in_spam=1; in_ham=6}
|> Map.add "query" { in_spam=2; in_ham=12}
|> Map.add "quest" { in_spam=1; in_ham=2}
|> Map.add "question" { in_spam=17; in_ham=101}
|> Map.add "questionable" { in_spam=4; in_ham=6}
|> Map.add "questions" { in_spam=35; in_ham=43}
|> Map.add "queue" { in_spam=0; in_ham=5}
|> Map.add "qui" { in_spam=2; in_ham=4}
|> Map.add "quick" { in_spam=37; in_ham=38}
|> Map.add "quicker" { in_spam=0; in_ham=5}
|> Map.add "quickest" { in_spam=3; in_ham=2}
|> Map.add "quickly" { in_spam=13; in_ham=48}
|> Map.add "quicktime" { in_spam=0; in_ham=8}
|> Map.add "quicktopic" { in_spam=0; in_ham=111}
|> Map.add "quiet" { in_spam=1; in_ham=10}
|> Map.add "quietly" { in_spam=1; in_ham=3}
|> Map.add "quinlan" { in_spam=0; in_ham=10}
|> Map.add "quinn" { in_spam=0; in_ham=3}
|> Map.add "quirks" { in_spam=0; in_ham=3}
|> Map.add "quit" { in_spam=4; in_ham=6}
|> Map.add "quite" { in_spam=7; in_ham=129}
|> Map.add "quiz" { in_spam=0; in_ham=9}
|> Map.add "quizzes" { in_spam=0; in_ham=4}
|> Map.add "quo" { in_spam=0; in_ham=3}
|> Map.add "quot" { in_spam=19; in_ham=3}
|> Map.add "quote" { in_spam=20; in_ham=23}
|> Map.add "quoted" { in_spam=0; in_ham=19}
|> Map.add "quotes" { in_spam=17; in_ham=27}
|> Map.add "quoting" { in_spam=1; in_ham=15}
|> Map.add "qves" { in_spam=10; in_ham=0}
|> Map.add "race" { in_spam=1; in_ham=10}
|> Map.add "rachel" { in_spam=0; in_ham=3}
|> Map.add "racial" { in_spam=0; in_ham=3}
|> Map.add "racist" { in_spam=0; in_ham=3}
|> Map.add "rack" { in_spam=0; in_ham=3}
|> Map.add "rackspace" { in_spam=0; in_ham=3}
|> Map.add "radar" { in_spam=2; in_ham=3}
|> Map.add "radiation" { in_spam=2; in_ham=3}
|> Map.add "radical" { in_spam=0; in_ham=5}
|> Map.add "radicalism" { in_spam=0; in_ham=3}
|> Map.add "radio" { in_spam=5; in_ham=52}
|> Map.add "rael" { in_spam=0; in_ham=5}
|> Map.add "rafael" { in_spam=0; in_ham=17}
|> Map.add "rags" { in_spam=0; in_ham=5}
|> Map.add "rah" { in_spam=0; in_ham=50}
|> Map.add "raid" { in_spam=0; in_ham=12}
|> Map.add "railroads" { in_spam=0; in_ham=3}
|> Map.add "rain" { in_spam=0; in_ham=7}
|> Map.add "raise" { in_spam=1; in_ham=17}
|> Map.add "raised" { in_spam=2; in_ham=21}
|> Map.add "raises" { in_spam=0; in_ham=7}
|> Map.add "raising" { in_spam=3; in_ham=6}
|> Map.add "raistrick" { in_spam=0; in_ham=3}
|> Map.add "raj" { in_spam=0; in_ham=3}
|> Map.add "rajs" { in_spam=0; in_ham=3}
|> Map.add "rake" { in_spam=3; in_ham=1}
|> Map.add "raleigh" { in_spam=0; in_ham=3}
|> Map.add "rallied" { in_spam=5; in_ham=0}
|> Map.add "rallies" { in_spam=0; in_ham=8}
|> Map.add "ram" { in_spam=2; in_ham=11}
|> Map.add "ramblings" { in_spam=0; in_ham=3}
|> Map.add "rambus" { in_spam=0; in_ham=4}
|> Map.add "ramdinose" { in_spam=0; in_ham=3}
|> Map.add "rampant" { in_spam=2; in_ham=5}
|> Map.add "ran" { in_spam=1; in_ham=39}
|> Map.add "rancho" { in_spam=3; in_ham=1}
|> Map.add "random" { in_spam=4; in_ham=29}
|> Map.add "randomising" { in_spam=0; in_ham=3}
|> Map.add "randomly" { in_spam=0; in_ham=29}
|> Map.add "randy" { in_spam=0; in_ham=5}
|> Map.add "range" { in_spam=3; in_ham=31}
|> Map.add "ranges" { in_spam=0; in_ham=6}
|> Map.add "ranging" { in_spam=3; in_ham=3}
|> Map.add "rank" { in_spam=0; in_ham=6}
|> Map.add "ranking" { in_spam=1; in_ham=8}
|> Map.add "rant" { in_spam=0; in_ham=4}
|> Map.add "ranting" { in_spam=0; in_ham=4}
|> Map.add "rants" { in_spam=2; in_ham=6}
|> Map.add "rap" { in_spam=1; in_ham=4}
|> Map.add "raph" { in_spam=0; in_ham=3}
|> Map.add "rapid" { in_spam=4; in_ham=14}
|> Map.add "rapidly" { in_spam=8; in_ham=18}
|> Map.add "rare" { in_spam=1; in_ham=23}
|> Map.add "rarely" { in_spam=2; in_ham=8}
|> Map.add "rat" { in_spam=1; in_ham=3}
|> Map.add "rat's" { in_spam=0; in_ham=4}
|> Map.add "rate" { in_spam=43; in_ham=56}
|> Map.add "rated" { in_spam=11; in_ham=7}
|> Map.add "rates" { in_spam=37; in_ham=41}
|> Map.add "rather" { in_spam=8; in_ham=132}
|> Map.add "ratified" { in_spam=1; in_ham=2}
|> Map.add "rating" { in_spam=2; in_ham=4}
|> Map.add "ratings" { in_spam=1; in_ham=5}
|> Map.add "ratio" { in_spam=2; in_ham=12}
|> Map.add "rational" { in_spam=0; in_ham=3}
|> Map.add "rats" { in_spam=0; in_ham=7}
|> Map.add "raw" { in_spam=3; in_ham=25}
|> Map.add "rawhide" { in_spam=0; in_ham=4}
|> Map.add "ray" { in_spam=1; in_ham=9}
|> Map.add "raymond" { in_spam=0; in_ham=3}
|> Map.add "razor" { in_spam=0; in_ham=82}
|> Map.add "razor-admin" { in_spam=0; in_ham=6}
|> Map.add "razor-agent" { in_spam=0; in_ham=14}
|> Map.add "razor-agents" { in_spam=0; in_ham=7}
|> Map.add "razor-check" { in_spam=0; in_ham=12}
|> Map.add "razor-report" { in_spam=0; in_ham=3}
|> Map.add "razor-users" { in_spam=0; in_ham=78}
|> Map.add "razored" { in_spam=0; in_ham=3}
|> Map.add "rbl" { in_spam=1; in_ham=5}
|> Map.add "rbls" { in_spam=0; in_ham=3}
|> Map.add "rbrace" { in_spam=0; in_ham=3}
|> Map.add "rbs" { in_spam=0; in_ham=4}
|> Map.add "rcs" { in_spam=0; in_ham=16}
|> Map.add "rcvstore" { in_spam=0; in_ham=6}
|> Map.add "rdbms" { in_spam=0; in_ham=7}
|> Map.add "rdf" { in_spam=0; in_ham=13}
|> Map.add "re-education" { in_spam=0; in_ham=3}
|> Map.add "re-enter" { in_spam=0; in_ham=3}
|> Map.add "re-entering" { in_spam=7; in_ham=0}
|> Map.add "re-run" { in_spam=0; in_ham=3}
|> Map.add "re-scan" { in_spam=0; in_ham=5}
|> Map.add "re-seating" { in_spam=0; in_ham=3}
|> Map.add "reach" { in_spam=27; in_ham=47}
|> Map.add "reached" { in_spam=9; in_ham=11}
|> Map.add "reaches" { in_spam=0; in_ham=3}
|> Map.add "reaching" { in_spam=0; in_ham=7}
|> Map.add "react" { in_spam=0; in_ham=6}
|> Map.add "reaction" { in_spam=1; in_ham=4}
|> Map.add "read" { in_spam=32; in_ham=167}
|> Map.add "read-only" { in_spam=0; in_ham=4}
|> Map.add "reader" { in_spam=1; in_ham=15}
|> Map.add "readers" { in_spam=2; in_ham=9}
|> Map.add "readily" { in_spam=0; in_ham=5}
|> Map.add "reading" { in_spam=19; in_ham=79}
|> Map.add "readings" { in_spam=0; in_ham=3}
|> Map.add "readme" { in_spam=0; in_ham=17}
|> Map.add "reads" { in_spam=0; in_ham=13}
|> Map.add "ready" { in_spam=34; in_ham=30}
|> Map.add "real" { in_spam=33; in_ham=154}
|> Map.add "real-time" { in_spam=6; in_ham=64}
|> Map.add "real-world" { in_spam=0; in_ham=3}
|> Map.add "realistic" { in_spam=0; in_ham=7}
|> Map.add "realities" { in_spam=1; in_ham=3}
|> Map.add "reality" { in_spam=4; in_ham=25}
|> Map.add "realization" { in_spam=0; in_ham=3}
|> Map.add "realize" { in_spam=7; in_ham=27}
|> Map.add "realized" { in_spam=1; in_ham=8}
|> Map.add "realizing" { in_spam=1; in_ham=5}
|> Map.add "really" { in_spam=22; in_ham=330}
|> Map.add "realm" { in_spam=0; in_ham=3}
|> Map.add "realtime" { in_spam=0; in_ham=4}
|> Map.add "reaps" { in_spam=8; in_ham=0}
|> Map.add "rear" { in_spam=1; in_ham=9}
|> Map.add "reason" { in_spam=25; in_ham=117}
|> Map.add "reasonable" { in_spam=2; in_ham=21}
|> Map.add "reasonably" { in_spam=0; in_ham=13}
|> Map.add "reasoning" { in_spam=1; in_ham=5}
|> Map.add "reasons" { in_spam=12; in_ham=60}
|> Map.add "reassembles" { in_spam=0; in_ham=3}
|> Map.add "rebel" { in_spam=3; in_ham=1}
|> Map.add "rebels" { in_spam=2; in_ham=2}
|> Map.add "reboot" { in_spam=0; in_ham=14}
|> Map.add "rebooted" { in_spam=0; in_ham=4}
|> Map.add "rebranding" { in_spam=0; in_ham=3}
|> Map.add "rebuild" { in_spam=0; in_ham=43}
|> Map.add "rebuilding" { in_spam=0; in_ham=12}
|> Map.add "rebuilt" { in_spam=0; in_ham=13}
|> Map.add "rebuttal" { in_spam=0; in_ham=3}
|> Map.add "recall" { in_spam=0; in_ham=30}
|> Map.add "recalled" { in_spam=0; in_ham=5}
|> Map.add "recalls" { in_spam=0; in_ham=4}
|> Map.add "recapture" { in_spam=0; in_ham=3}
|> Map.add "receding" { in_spam=0; in_ham=5}
|> Map.add "receipt" { in_spam=8; in_ham=1}
|> Map.add "receive" { in_spam=147; in_ham=47}
|> Map.add "received" { in_spam=60; in_ham=125}
|> Map.add "received'" { in_spam=0; in_ham=3}
|> Map.add "receiver" { in_spam=3; in_ham=1}
|> Map.add "receivers" { in_spam=1; in_ham=2}
|> Map.add "receives" { in_spam=7; in_ham=7}
|> Map.add "receiving" { in_spam=66; in_ham=96}
|> Map.add "recent" { in_spam=11; in_ham=81}
|> Map.add "recently" { in_spam=24; in_ham=64}
|> Map.add "reception" { in_spam=1; in_ham=2}
|> Map.add "recession" { in_spam=6; in_ham=2}
|> Map.add "recharging" { in_spam=0; in_ham=4}
|> Map.add "recieve" { in_spam=5; in_ham=2}
|> Map.add "recipe" { in_spam=0; in_ham=12}
|> Map.add "recipient" { in_spam=5; in_ham=21}
|> Map.add "recipients" { in_spam=6; in_ham=18}
|> Map.add "reciprocal" { in_spam=1; in_ham=3}
|> Map.add "reckon" { in_spam=0; in_ham=9}
|> Map.add "recognition" { in_spam=3; in_ham=6}
|> Map.add "recognize" { in_spam=1; in_ham=17}
|> Map.add "recognized" { in_spam=2; in_ham=7}
|> Map.add "recollection" { in_spam=0; in_ham=4}
|> Map.add "recommend" { in_spam=6; in_ham=26}
|> Map.add "recommended" { in_spam=2; in_ham=17}
|> Map.add "recommending" { in_spam=0; in_ham=3}
|> Map.add "recommends" { in_spam=0; in_ham=5}
|> Map.add "recompile" { in_spam=0; in_ham=15}
|> Map.add "recompiled" { in_spam=0; in_ham=7}
|> Map.add "recompiling" { in_spam=0; in_ham=8}
|> Map.add "reconfigure" { in_spam=0; in_ham=7}
|> Map.add "reconnect" { in_spam=1; in_ham=3}
|> Map.add "reconnection" { in_spam=0; in_ham=3}
|> Map.add "record" { in_spam=7; in_ham=60}
|> Map.add "recorded" { in_spam=2; in_ham=16}
|> Map.add "recorder" { in_spam=1; in_ham=3}
|> Map.add "recording" { in_spam=2; in_ham=8}
|> Map.add "recordings" { in_spam=0; in_ham=3}
|> Map.add "records" { in_spam=3; in_ham=18}
|> Map.add "recover" { in_spam=1; in_ham=8}
|> Map.add "recovered" { in_spam=0; in_ham=3}
|> Map.add "recovering" { in_spam=0; in_ham=4}
|> Map.add "recovery" { in_spam=0; in_ham=8}
|> Map.add "recreate" { in_spam=0; in_ham=6}
|> Map.add "recreation" { in_spam=1; in_ham=2}
|> Map.add "recreational" { in_spam=1; in_ham=2}
|> Map.add "recreations" { in_spam=0; in_ham=4}
|> Map.add "recruiting" { in_spam=3; in_ham=1}
|> Map.add "rect" { in_spam=3; in_ham=1}
|> Map.add "recurring" { in_spam=2; in_ham=4}
|> Map.add "recurse" { in_spam=0; in_ham=6}
|> Map.add "recycled" { in_spam=0; in_ham=3}
|> Map.add "red" { in_spam=25; in_ham=127}
|> Map.add "redefining" { in_spam=0; in_ham=3}
|> Map.add "redesign" { in_spam=3; in_ham=2}
|> Map.add "redesigned" { in_spam=3; in_ham=1}
|> Map.add "redhat" { in_spam=0; in_ham=209}
|> Map.add "redhat's" { in_spam=0; in_ham=3}
|> Map.add "redhat-" { in_spam=0; in_ham=4}
|> Map.add "redirect" { in_spam=5; in_ham=1}
|> Map.add "redirects" { in_spam=0; in_ham=4}
|> Map.add "redo" { in_spam=0; in_ham=4}
|> Map.add "reduce" { in_spam=2; in_ham=25}
|> Map.add "reduced" { in_spam=2; in_ham=8}
|> Map.add "reduces" { in_spam=1; in_ham=6}
|> Map.add "reducing" { in_spam=1; in_ham=10}
|> Map.add "reduction" { in_spam=7; in_ham=6}
|> Map.add "reductions" { in_spam=0; in_ham=6}
|> Map.add "reeling" { in_spam=0; in_ham=3}
|> Map.add "rees" { in_spam=0; in_ham=5}
|> Map.add "ref" { in_spam=3; in_ham=3}
|> Map.add "refactoring" { in_spam=0; in_ham=3}
|> Map.add "refcode" { in_spam=2; in_ham=106}
|> Map.add "refer" { in_spam=4; in_ham=6}
|> Map.add "reference" { in_spam=13; in_ham=44}
|> Map.add "referenced" { in_spam=1; in_ham=5}
|> Map.add "references" { in_spam=6; in_ham=7}
|> Map.add "refering" { in_spam=0; in_ham=4}
|> Map.add "referral" { in_spam=3; in_ham=1}
|> Map.add "referring" { in_spam=3; in_ham=11}
|> Map.add "refers" { in_spam=2; in_ham=2}
|> Map.add "refinance" { in_spam=14; in_ham=0}
|> Map.add "refinancing" { in_spam=12; in_ham=0}
|> Map.add "refined" { in_spam=1; in_ham=3}
|> Map.add "refining" { in_spam=5; in_ham=1}
|> Map.add "reflect" { in_spam=1; in_ham=8}
|> Map.add "reflects" { in_spam=0; in_ham=6}
|> Map.add "reflexively" { in_spam=0; in_ham=3}
|> Map.add "reform" { in_spam=5; in_ham=7}
|> Map.add "reforming" { in_spam=0; in_ham=4}
|> Map.add "reforms" { in_spam=0; in_ham=5}
|> Map.add "refresh" { in_spam=0; in_ham=3}
|> Map.add "refreshing" { in_spam=3; in_ham=1}
|> Map.add "refueled" { in_spam=0; in_ham=4}
|> Map.add "refuge" { in_spam=1; in_ham=5}
|> Map.add "refund" { in_spam=5; in_ham=6}
|> Map.add "refused" { in_spam=2; in_ham=7}
|> Map.add "refutations" { in_spam=0; in_ham=3}
|> Map.add "reg" { in_spam=6; in_ham=12}
|> Map.add "regain" { in_spam=1; in_ham=2}
|> Map.add "regard" { in_spam=4; in_ham=16}
|> Map.add "regarded" { in_spam=1; in_ham=2}
|> Map.add "regarding" { in_spam=15; in_ham=9}
|> Map.add "regardless" { in_spam=4; in_ham=15}
|> Map.add "regards" { in_spam=29; in_ham=77}
|> Map.add "regexp" { in_spam=0; in_ham=4}
|> Map.add "regime" { in_spam=3; in_ham=12}
|> Map.add "regimes" { in_spam=0; in_ham=5}
|> Map.add "region" { in_spam=3; in_ham=21}
|> Map.add "regional" { in_spam=1; in_ham=14}
|> Map.add "regions" { in_spam=1; in_ham=10}
|> Map.add "register" { in_spam=13; in_ham=15}
|> Map.add "registered" { in_spam=37; in_ham=12}
|> Map.add "registering" { in_spam=2; in_ham=7}
|> Map.add "registration" { in_spam=9; in_ham=6}
|> Map.add "registry" { in_spam=0; in_ham=9}
|> Map.add "regnicoiton" { in_spam=0; in_ham=3}
|> Map.add "regret" { in_spam=5; in_ham=4}
|> Map.add "regrets" { in_spam=0; in_ham=4}
|> Map.add "regular" { in_spam=13; in_ham=31}
|> Map.add "regularly" { in_spam=2; in_ham=12}
|> Map.add "regulate" { in_spam=0; in_ham=3}
|> Map.add "regulated" { in_spam=1; in_ham=7}
|> Map.add "regulates" { in_spam=0; in_ham=3}
|> Map.add "regulation" { in_spam=0; in_ham=19}
|> Map.add "regulations" { in_spam=6; in_ham=14}
|> Map.add "regulator" { in_spam=0; in_ham=3}
|> Map.add "regulators" { in_spam=0; in_ham=5}
|> Map.add "regulatory" { in_spam=2; in_ham=11}
|> Map.add "reibadailty" { in_spam=0; in_ham=3}
|> Map.add "reign" { in_spam=0; in_ham=6}
|> Map.add "reinforce" { in_spam=0; in_ham=3}
|> Map.add "reinforced" { in_spam=1; in_ham=2}
|> Map.add "reingold" { in_spam=0; in_ham=5}
|> Map.add "reinstall" { in_spam=0; in_ham=13}
|> Map.add "reject" { in_spam=0; in_ham=12}
|> Map.add "rejected" { in_spam=2; in_ham=13}
|> Map.add "rejecting" { in_spam=0; in_ham=4}
|> Map.add "rel" { in_spam=3; in_ham=1}
|> Map.add "relate" { in_spam=1; in_ham=4}
|> Map.add "related" { in_spam=13; in_ham=40}
|> Map.add "relating" { in_spam=4; in_ham=5}
|> Map.add "relations" { in_spam=3; in_ham=5}
|> Map.add "relationship" { in_spam=7; in_ham=27}
|> Map.add "relative" { in_spam=4; in_ham=18}
|> Map.add "relatively" { in_spam=6; in_ham=21}
|> Map.add "relatives" { in_spam=6; in_ham=4}
|> Map.add "relax" { in_spam=7; in_ham=3}
|> Map.add "relaxation" { in_spam=1; in_ham=2}
|> Map.add "relaxed" { in_spam=0; in_ham=9}
|> Map.add "relaxing" { in_spam=1; in_ham=2}
|> Map.add "relay" { in_spam=1; in_ham=9}
|> Map.add "relayed" { in_spam=0; in_ham=3}
|> Map.add "relays" { in_spam=0; in_ham=4}
|> Map.add "release" { in_spam=10; in_ham=127}
|> Map.add "released" { in_spam=3; in_ham=46}
|> Map.add "releases" { in_spam=3; in_ham=37}
|> Map.add "releasing" { in_spam=0; in_ham=6}
|> Map.add "relevance" { in_spam=0; in_ham=5}
|> Map.add "relevant" { in_spam=12; in_ham=29}
|> Map.add "reliability" { in_spam=0; in_ham=7}
|> Map.add "reliable" { in_spam=8; in_ham=13}
|> Map.add "reliably" { in_spam=1; in_ham=2}
|> Map.add "reliance" { in_spam=0; in_ham=4}
|> Map.add "relief" { in_spam=1; in_ham=9}
|> Map.add "relies" { in_spam=0; in_ham=7}
|> Map.add "relieving" { in_spam=0; in_ham=4}
|> Map.add "religion" { in_spam=2; in_ham=17}
|> Map.add "religions" { in_spam=0; in_ham=7}
|> Map.add "religiosity" { in_spam=0; in_ham=5}
|> Map.add "religious" { in_spam=1; in_ham=23}
|> Map.add "reluctant" { in_spam=0; in_ham=3}
|> Map.add "rely" { in_spam=5; in_ham=18}
|> Map.add "relying" { in_spam=0; in_ham=4}
|> Map.add "remain" { in_spam=7; in_ham=30}
|> Map.add "remained" { in_spam=3; in_ham=5}
|> Map.add "remaining" { in_spam=2; in_ham=11}
|> Map.add "remains" { in_spam=6; in_ham=33}
|> Map.add "remarkable" { in_spam=4; in_ham=5}
|> Map.add "remarkably" { in_spam=1; in_ham=2}
|> Map.add "remarks" { in_spam=0; in_ham=5}
|> Map.add "remeber" { in_spam=0; in_ham=3}
|> Map.add "remedies" { in_spam=0; in_ham=4}
|> Map.add "remember" { in_spam=19; in_ham=76}
|> Map.add "remembering" { in_spam=0; in_ham=7}
|> Map.add "remembrance" { in_spam=1; in_ham=9}
|> Map.add "remind" { in_spam=1; in_ham=3}
|> Map.add "reminder" { in_spam=2; in_ham=6}
|> Map.add "reminders" { in_spam=0; in_ham=4}
|> Map.add "reminds" { in_spam=0; in_ham=6}
|> Map.add "remnants" { in_spam=0; in_ham=3}
|> Map.add "remodeling" { in_spam=0; in_ham=5}
|> Map.add "remote" { in_spam=9; in_ham=27}
|> Map.add "remotely" { in_spam=0; in_ham=7}
|> Map.add "removal" { in_spam=58; in_ham=4}
|> Map.add "removal'" { in_spam=6; in_ham=0}
|> Map.add "remove" { in_spam=167; in_ham=71}
|> Map.add "remove'" { in_spam=5; in_ham=1}
|> Map.add "removed" { in_spam=131; in_ham=69}
|> Map.add "removeme" { in_spam=9; in_ham=0}
|> Map.add "removes" { in_spam=6; in_ham=4}
|> Map.add "removing" { in_spam=3; in_ham=17}
|> Map.add "renamed" { in_spam=0; in_ham=6}
|> Map.add "render" { in_spam=1; in_ham=8}
|> Map.add "rendered" { in_spam=0; in_ham=4}
|> Map.add "rendering" { in_spam=1; in_ham=6}
|> Map.add "renew" { in_spam=0; in_ham=4}
|> Map.add "renewable" { in_spam=0; in_ham=4}
|> Map.add "renewal" { in_spam=3; in_ham=4}
|> Map.add "rennie" { in_spam=0; in_ham=4}
|> Map.add "renovate" { in_spam=0; in_ham=4}
|> Map.add "rent" { in_spam=4; in_ham=8}
|> Map.add "rental" { in_spam=10; in_ham=2}
|> Map.add "renting" { in_spam=0; in_ham=3}
|> Map.add "rep" { in_spam=3; in_ham=2}
|> Map.add "repackage" { in_spam=0; in_ham=5}
|> Map.add "repackaged" { in_spam=0; in_ham=7}
|> Map.add "repair" { in_spam=16; in_ham=6}
|> Map.add "repairs" { in_spam=5; in_ham=3}
|> Map.add "repeat" { in_spam=4; in_ham=6}
|> Map.add "repeated" { in_spam=1; in_ham=3}
|> Map.add "repeatedly" { in_spam=1; in_ham=9}
|> Map.add "replace" { in_spam=4; in_ham=26}
|> Map.add "replaced" { in_spam=1; in_ham=13}
|> Map.add "replacement" { in_spam=2; in_ham=11}
|> Map.add "replacements" { in_spam=2; in_ham=6}
|> Map.add "replaces" { in_spam=0; in_ham=3}
|> Map.add "replacing" { in_spam=3; in_ham=5}
|> Map.add "replcomps" { in_spam=0; in_ham=4}
|> Map.add "replete" { in_spam=1; in_ham=2}
|> Map.add "replicate" { in_spam=2; in_ham=2}
|> Map.add "replied" { in_spam=0; in_ham=12}
|> Map.add "replies" { in_spam=1; in_ham=4}
|> Map.add "reply" { in_spam=98; in_ham=19}
|> Map.add "reply-to" { in_spam=1; in_ham=9}
|> Map.add "replying" { in_spam=4; in_ham=8}
|> Map.add "report" { in_spam=34; in_ham=61}
|> Map.add "reported" { in_spam=7; in_ham=47}
|> Map.add "reportedby" { in_spam=0; in_ham=3}
|> Map.add "reporter" { in_spam=1; in_ham=8}
|> Map.add "reporters" { in_spam=1; in_ham=4}
|> Map.add "reporting" { in_spam=3; in_ham=21}
|> Map.add "reports" { in_spam=14; in_ham=44}
|> Map.add "repositories" { in_spam=0; in_ham=4}

