open Database
let db = Map.empty 
|> Map.add "2.14" { in_spam=0; in_ham=13}
|> Map.add "2.40" { in_spam=0; in_ham=19}
|> Map.add "2.41" { in_spam=0; in_ham=17}
|> Map.add "2002" { in_spam=13; in_ham=64}
|> Map.add "8.0" { in_spam=0; in_ham=22}
|> Map.add "ADV" { in_spam=18; in_ham=0}
|> Map.add "ALSA" { in_spam=0; in_ham=32}
|> Map.add "ARRRGHHH" { in_spam=0; in_ham=9}
|> Map.add "CVS" { in_spam=0; in_ham=39}
|> Map.add "DMA" { in_spam=0; in_ham=17}
|> Map.add "DVD" { in_spam=2; in_ham=25}
|> Map.add "GPG" { in_spam=0; in_ham=9}
|> Map.add "ILUG" { in_spam=32; in_ham=92}
|> Map.add "RSS" { in_spam=0; in_ham=10}
|> Map.add "SACVS" { in_spam=0; in_ham=18}
|> Map.add "YOUR" { in_spam=13; in_ham=3}
|> Map.add "about" { in_spam=4; in_ham=20}
|> Map.add "absurdities" { in_spam=0; in_ham=9}
|> Map.add "activebuddy" { in_spam=0; in_ham=11}
|> Map.add "adv" { in_spam=20; in_ham=0}
|> Map.add "after" { in_spam=0; in_ham=10}
|> Map.add "again" { in_spam=2; in_ham=8}
|> Map.add "all" { in_spam=3; in_ham=19}
|> Map.add "almost" { in_spam=0; in_ham=25}
|> Map.add "alsa" { in_spam=0; in_ham=34}
|> Map.add "alsa-driver" { in_spam=0; in_ham=12}
|> Map.add "amendment" { in_spam=0; in_ham=20}
|> Map.add "and" { in_spam=24; in_ham=116}
|> Map.add "announces" { in_spam=0; in_ham=13}
|> Map.add "anolther" { in_spam=0; in_ham=12}
|> Map.add "another" { in_spam=0; in_ham=8}
|> Map.add "apple" { in_spam=0; in_ham=10}
|> Map.add "approach" { in_spam=1; in_ham=7}
|> Map.add "apt" { in_spam=0; in_ham=57}
|> Map.add "apt-get" { in_spam=0; in_ham=13}
|> Map.add "are" { in_spam=11; in_ham=27}
|> Map.add "arrrghhh" { in_spam=0; in_ham=9}
|> Map.add "article" { in_spam=0; in_ham=9}
|> Map.add "attacks" { in_spam=0; in_ham=11}
|> Map.add "automated" { in_spam=0; in_ham=14}
|> Map.add "available" { in_spam=5; in_ham=7}
|> Map.add "back" { in_spam=3; in_ham=10}
|> Map.add "bad" { in_spam=0; in_ham=22}
|> Map.add "bank" { in_spam=5; in_ham=6}
|> Map.add "base" { in_spam=2; in_ham=12}
|> Map.add "behaviours" { in_spam=0; in_ham=17}
|> Map.add "best" { in_spam=19; in_ham=3}
|> Map.add "big" { in_spam=8; in_ham=29}
|> Map.add "bliss" { in_spam=0; in_ham=55}
|> Map.add "boycotting" { in_spam=0; in_ham=8}
|> Map.add "bucks" { in_spam=1; in_ham=12}
|> Map.add "bug" { in_spam=0; in_ham=43}
|> Map.add "build" { in_spam=1; in_ham=10}
|> Map.add "bush" { in_spam=0; in_ham=9}
|> Map.add "business" { in_spam=7; in_ham=7}
|> Map.add "but" { in_spam=0; in_ham=10}
|> Map.add "buy" { in_spam=3; in_ham=6}
|> Map.add "can" { in_spam=4; in_ham=15}
|> Map.add "can't" { in_spam=0; in_ham=12}
|> Map.add "canadians" { in_spam=0; in_ham=8}
|> Map.add "car" { in_spam=0; in_ham=8}
|> Map.add "case" { in_spam=2; in_ham=14}
|> Map.add "change" { in_spam=0; in_ham=16}
|> Map.add "click" { in_spam=1; in_ham=17}
|> Map.add "cluetrain" { in_spam=0; in_ham=9}
|> Map.add "com" { in_spam=8; in_ham=24}
|> Map.add "compile" { in_spam=0; in_ham=9}
|> Map.add "complete" { in_spam=3; in_ham=9}
|> Map.add "computer" { in_spam=10; in_ham=5}
|> Map.add "current" { in_spam=0; in_ham=12}
|> Map.add "curse" { in_spam=0; in_ham=9}
|> Map.add "cvs" { in_spam=0; in_ham=42}
|> Map.add "datapower" { in_spam=0; in_ham=13}
|> Map.add "date" { in_spam=0; in_ham=8}
|> Map.add "day" { in_spam=3; in_ham=11}
|> Map.add "dell" { in_spam=0; in_ham=9}
|> Map.add "delta" { in_spam=0; in_ham=11}
|> Map.add "deployment" { in_spam=0; in_ham=28}
|> Map.add "digital" { in_spam=1; in_ham=16}
|> Map.add "dma" { in_spam=0; in_ham=17}
|> Map.add "doesnt" { in_spam=0; in_ham=9}
|> Map.add "don't" { in_spam=5; in_ham=5}
|> Map.add "drive" { in_spam=0; in_ham=17}
|> Map.add "dvd" { in_spam=2; in_ham=27}
|> Map.add "dylsexics" { in_spam=0; in_ham=8}
|> Map.add "easy" { in_spam=2; in_ham=26}
|> Map.add "ebusiness" { in_spam=0; in_ham=9}
|> Map.add "electric" { in_spam=0; in_ham=8}
|> Map.add "email" { in_spam=5; in_ham=13}
|> Map.add "empire" { in_spam=0; in_ham=26}
|> Map.add "error" { in_spam=1; in_ham=12}
|> Map.add "errors" { in_spam=0; in_ham=8}
|> Map.add "exmh" { in_spam=0; in_ham=26}
|> Map.add "false" { in_spam=0; in_ham=20}
|> Map.add "file" { in_spam=0; in_ham=17}
|> Map.add "finally" { in_spam=0; in_ham=11}
|> Map.add "find" { in_spam=5; in_ham=14}
|> Map.add "first" { in_spam=2; in_ham=25}
|> Map.add "focus" { in_spam=1; in_ham=17}
|> Map.add "for" { in_spam=49; in_ham=296}
|> Map.add "free" { in_spam=30; in_ham=11}
|> Map.add "friends" { in_spam=0; in_ham=13}
|> Map.add "from" { in_spam=10; in_ham=68}
|> Map.add "funny" { in_spam=0; in_ham=8}
|> Map.add "fwd" { in_spam=4; in_ham=30}
|> Map.add "get" { in_spam=19; in_ham=13}
|> Map.add "gets" { in_spam=2; in_ham=19}
|> Map.add "getting" { in_spam=0; in_ham=11}
|> Map.add "global" { in_spam=0; in_ham=27}
|> Map.add "god" { in_spam=0; in_ham=16}
|> Map.add "going" { in_spam=0; in_ham=8}
|> Map.add "good" { in_spam=0; in_ham=15}
|> Map.add "goodbye" { in_spam=0; in_ham=26}
|> Map.add "google" { in_spam=0; in_ham=17}
|> Map.add "gov" { in_spam=0; in_ham=14}
|> Map.add "government" { in_spam=1; in_ham=12}
|> Map.add "gpg" { in_spam=0; in_ham=9}
|> Map.add "habeus" { in_spam=0; in_ham=20}
|> Map.add "had" { in_spam=0; in_ham=9}
|> Map.add "hanson's" { in_spam=0; in_ham=21}
|> Map.add "has" { in_spam=2; in_ham=25}
|> Map.add "hat" { in_spam=0; in_ham=10}
|> Map.add "have" { in_spam=7; in_ham=8}
|> Map.add "headlines" { in_spam=0; in_ham=28}
|> Map.add "help" { in_spam=5; in_ham=13}
|> Map.add "here" { in_spam=12; in_ham=5}
|> Map.add "high" { in_spam=1; in_ham=14}
|> Map.add "his" { in_spam=1; in_ham=21}
|> Map.add "histograms" { in_spam=0; in_ham=8}
|> Map.add "home" { in_spam=15; in_ham=8}
|> Map.add "hottest" { in_spam=1; in_ham=12}
|> Map.add "how" { in_spam=4; in_ham=19}
|> Map.add "http" { in_spam=1; in_ham=14}
|> Map.add "i'm" { in_spam=1; in_ham=9}
|> Map.add "i've" { in_spam=0; in_ham=8}
|> Map.add "ilug" { in_spam=34; in_ham=92}
|> Map.add "image" { in_spam=1; in_ham=22}
|> Map.add "india's" { in_spam=0; in_ham=10}
|> Map.add "information" { in_spam=6; in_ham=5}
|> Map.add "insert" { in_spam=0; in_ham=9}
|> Map.add "install" { in_spam=0; in_ham=9}
|> Map.add "interesting" { in_spam=0; in_ham=9}
|> Map.add "internet" { in_spam=7; in_ham=12}
|> Map.add "into" { in_spam=0; in_ham=10}
|> Map.add "iraq" { in_spam=1; in_ham=7}
|> Map.add "it's" { in_spam=0; in_ham=8}
|> Map.add "java" { in_spam=0; in_ham=35}
|> Map.add "jump" { in_spam=0; in_ham=9}
|> Map.add "just" { in_spam=4; in_ham=10}
|> Map.add "kernel" { in_spam=0; in_ham=8}
|> Map.add "key" { in_spam=0; in_ham=16}
|> Map.add "kiddies" { in_spam=0; in_ham=35}
|> Map.add "laptop" { in_spam=1; in_ham=8}
|> Map.add "last" { in_spam=3; in_ham=8}
|> Map.add "left" { in_spam=0; in_ham=10}
|> Map.add "liberal" { in_spam=0; in_ham=9}
|> Map.add "life" { in_spam=10; in_ham=10}
|> Map.add "like" { in_spam=1; in_ham=9}
|> Map.add "linux" { in_spam=0; in_ham=18}
|> Map.add "log" { in_spam=0; in_ham=8}
|> Map.add "looking" { in_spam=2; in_ham=7}
|> Map.add "low" { in_spam=13; in_ham=14}
|> Map.add "mac" { in_spam=0; in_ham=8}
|> Map.add "made" { in_spam=0; in_ham=26}
|> Map.add "mail" { in_spam=0; in_ham=18}
|> Map.add "make" { in_spam=9; in_ham=3}
|> Map.add "man" { in_spam=1; in_ham=24}
|> Map.add "management" { in_spam=1; in_ham=7}
|> Map.add "mark" { in_spam=0; in_ham=8}
|> Map.add "may" { in_spam=2; in_ham=7}
|> Map.add "meet" { in_spam=1; in_ham=13}
|> Map.add "meetings" { in_spam=0; in_ham=12}
|> Map.add "message" { in_spam=1; in_ham=40}
|> Map.add "moment" { in_spam=1; in_ham=20}
|> Map.add "money" { in_spam=16; in_ham=0}
|> Map.add "more" { in_spam=3; in_ham=13}
|> Map.add "mplayer" { in_spam=0; in_ham=15}
|> Map.add "name" { in_spam=1; in_ham=15}
|> Map.add "national" { in_spam=0; in_ham=22}
|> Map.add "negative" { in_spam=0; in_ham=13}
|> Map.add "net" { in_spam=2; in_ham=27}
|> Map.add "new" { in_spam=13; in_ham=103}
|> Map.add "newbie" { in_spam=0; in_ham=8}
|> Map.add "news" { in_spam=5; in_ham=17}
|> Map.add "next" { in_spam=1; in_ham=7}
|> Map.add "nixia" { in_spam=0; in_ham=10}
|> Map.add "nobel" { in_spam=0; in_ham=11}
|> Map.add "not" { in_spam=3; in_ham=35}
|> Map.add "now" { in_spam=12; in_ham=14}
|> Map.add "null" { in_spam=0; in_ham=20}
|> Map.add "one" { in_spam=10; in_ham=9}
|> Map.add "online" { in_spam=9; in_ham=8}
|> Map.add "other" { in_spam=3; in_ham=9}
|> Map.add "ouch" { in_spam=0; in_ham=71}
|> Map.add "our" { in_spam=0; in_ham=23}
|> Map.add "out" { in_spam=3; in_ham=17}
|> Map.add "over" { in_spam=3; in_ham=9}
|> Map.add "own" { in_spam=3; in_ham=9}
|> Map.add "package" { in_spam=1; in_ham=15}
|> Map.add "packages" { in_spam=0; in_ham=12}
|> Map.add "palestinians" { in_spam=0; in_ham=10}
|> Map.add "patch" { in_spam=1; in_ham=12}
|> Map.add "patent" { in_spam=0; in_ham=8}
|> Map.add "perl" { in_spam=0; in_ham=60}
|> Map.add "personals" { in_spam=0; in_ham=11}
|> Map.add "pirates" { in_spam=0; in_ham=15}
|> Map.add "place" { in_spam=1; in_ham=13}
|> Map.add "play" { in_spam=4; in_ham=8}
|> Map.add "player" { in_spam=0; in_ham=8}
|> Map.add "please" { in_spam=7; in_ham=11}
|> Map.add "problem" { in_spam=0; in_ham=45}
|> Map.add "problems" { in_spam=1; in_ham=23}
|> Map.add "question" { in_spam=0; in_ham=13}
|> Map.add "radio" { in_spam=0; in_ham=8}
|> Map.add "rate" { in_spam=3; in_ham=14}
|> Map.add "rates" { in_spam=18; in_ham=0}
|> Map.add "razor" { in_spam=0; in_ham=52}
|> Map.add "razor-users" { in_spam=0; in_ham=89}
|> Map.add "read" { in_spam=1; in_ham=7}
|> Map.add "ready" { in_spam=2; in_ham=8}
|> Map.add "real" { in_spam=2; in_ham=7}
|> Map.add "recommended" { in_spam=0; in_ham=13}
|> Map.add "recovery" { in_spam=0; in_ham=11}
|> Map.add "red" { in_spam=0; in_ham=10}
|> Map.add "redhat" { in_spam=0; in_ham=12}
|> Map.add "related" { in_spam=0; in_ham=12}
|> Map.add "release" { in_spam=1; in_ham=20}
|> Map.add "released" { in_spam=0; in_ham=8}
|> Map.add "report" { in_spam=1; in_ham=20}
|> Map.add "results" { in_spam=1; in_ham=9}
|> Map.add "review" { in_spam=0; in_ham=25}
|> Map.add "roman" { in_spam=0; in_ham=27}
|> Map.add "rpm" { in_spam=0; in_ham=14}
|> Map.add "rss" { in_spam=0; in_ham=10}
|> Map.add "rules" { in_spam=0; in_ham=8}
|> Map.add "sacvs" { in_spam=0; in_ham=18}
|> Map.add "sadev" { in_spam=0; in_ham=73}
|> Map.add "satalk" { in_spam=1; in_ham=138}
|> Map.add "save" { in_spam=7; in_ham=5}
|> Map.add "scoop" { in_spam=3; in_ham=9}
|> Map.add "secure" { in_spam=0; in_ham=19}
|> Map.add "sed" { in_spam=0; in_ham=26}
|> Map.add "selling" { in_spam=0; in_ham=54}
|> Map.add "sept" { in_spam=0; in_ham=21}
|> Map.add "sequence" { in_spam=0; in_ham=12}
|> Map.add "sequences" { in_spam=0; in_ham=26}
|> Map.add "servants" { in_spam=0; in_ham=10}
|> Map.add "sets" { in_spam=0; in_ham=30}
|> Map.add "signature" { in_spam=0; in_ham=9}
|> Map.add "silence" { in_spam=0; in_ham=20}
|> Map.add "site" { in_spam=2; in_ham=9}
|> Map.add "slaughter" { in_spam=0; in_ham=15}
|> Map.add "socialism" { in_spam=0; in_ham=9}
|> Map.add "software" { in_spam=7; in_ham=13}
|> Map.add "sofware" { in_spam=0; in_ham=14}
|> Map.add "some" { in_spam=0; in_ham=10}
|> Map.add "something" { in_spam=1; in_ham=12}
|> Map.add "sorting" { in_spam=0; in_ham=23}
|> Map.add "spam" { in_spam=2; in_ham=48}
|> Map.add "spamassassin" { in_spam=0; in_ham=57}
|> Map.add "spambayes" { in_spam=0; in_ham=143}
|> Map.add "spec" { in_spam=0; in_ham=10}
|> Map.add "speed" { in_spam=1; in_ham=10}
|> Map.add "src" { in_spam=0; in_ham=10}
|> Map.add "states" { in_spam=0; in_ham=26}
|> Map.add "station" { in_spam=0; in_ham=11}
|> Map.add "status" { in_spam=3; in_ham=7}
|> Map.add "still" { in_spam=1; in_ham=11}
|> Map.add "stories" { in_spam=0; in_ham=29}
|> Map.add "subject" { in_spam=468; in_ham=2537}
|> Map.add "sun" { in_spam=0; in_ham=10}
|> Map.add "support" { in_spam=3; in_ham=6}
|> Map.add "system" { in_spam=1; in_ham=17}
|> Map.add "test" { in_spam=0; in_ham=38}
|> Map.add "testing" { in_spam=1; in_ham=21}
|> Map.add "that" { in_spam=0; in_ham=23}
|> Map.add "the" { in_spam=53; in_ham=371}
|> Map.add "there" { in_spam=0; in_ham=10}
|> Map.add "this" { in_spam=9; in_ham=21}
|> Map.add "time" { in_spam=8; in_ham=7}
|> Map.add "tip" { in_spam=0; in_ham=12}
|> Map.add "toddlers" { in_spam=0; in_ham=8}
|> Map.add "too" { in_spam=3; in_ham=11}
|> Map.add "tough" { in_spam=0; in_ham=15}
|> Map.add "traceback" { in_spam=0; in_ham=19}
|> Map.add "training" { in_spam=0; in_ham=8}
|> Map.add "united" { in_spam=0; in_ham=26}
|> Map.add "untie" { in_spam=0; in_ham=8}
|> Map.add "updates" { in_spam=0; in_ham=8}
|> Map.add "upgrade" { in_spam=0; in_ham=18}
|> Map.add "use" { in_spam=2; in_ham=88}
|> Map.add "users" { in_spam=0; in_ham=18}
|> Map.add "using" { in_spam=0; in_ham=8}
|> Map.add "viewing" { in_spam=0; in_ham=14}
|> Map.add "void" { in_spam=0; in_ham=11}
|> Map.add "warming" { in_spam=0; in_ham=25}
|> Map.add "was" { in_spam=1; in_ham=108}
|> Map.add "web" { in_spam=2; in_ham=11}
|> Map.add "webforms" { in_spam=0; in_ham=9}
|> Map.add "wedded" { in_spam=0; in_ham=54}
|> Map.add "what" { in_spam=7; in_ham=4}
|> Map.add "whoa" { in_spam=0; in_ham=11}
|> Map.add "why" { in_spam=2; in_ham=25}
|> Map.add "wifi" { in_spam=0; in_ham=11}
|> Map.add "will" { in_spam=9; in_ham=5}
|> Map.add "win" { in_spam=2; in_ham=7}
|> Map.add "window" { in_spam=0; in_ham=34}
|> Map.add "with" { in_spam=17; in_ham=115}
|> Map.add "women" { in_spam=0; in_ham=13}
|> Map.add "work" { in_spam=6; in_ham=7}
|> Map.add "working" { in_spam=3; in_ham=22}
|> Map.add "world" { in_spam=1; in_ham=10}
|> Map.add "wrold" { in_spam=0; in_ham=8}
|> Map.add "xine" { in_spam=0; in_ham=12}
|> Map.add "yahoo" { in_spam=0; in_ham=12}
|> Map.add "year" { in_spam=11; in_ham=2}
|> Map.add "you" { in_spam=46; in_ham=25}
|> Map.add "your" { in_spam=70; in_ham=15}
|> Map.add "zzzzteana" { in_spam=0; in_ham=87}

