open Database
open BayesianBody_000
let db = db 
|> Map.add "CORNER" { in_spam=7; in_ham=0}
|> Map.add "COST" { in_spam=11; in_ham=0}
|> Map.add "COVERAGE" { in_spam=3; in_ham=1}
|> Map.add "CPAN" { in_spam=0; in_ham=7}
|> Map.add "CPU" { in_spam=5; in_ham=8}
|> Map.add "CRTC" { in_spam=0; in_ham=3}
|> Map.add "CSS" { in_spam=0; in_ham=7}
|> Map.add "CTO" { in_spam=0; in_ham=14}
|> Map.add "CURRENCY" { in_spam=6; in_ham=0}
|> Map.add "CURRENTLY" { in_spam=10; in_ham=0}
|> Map.add "CVS" { in_spam=0; in_ham=48}
|> Map.add "DALSA" { in_spam=0; in_ham=3}
|> Map.add "DATA" { in_spam=6; in_ham=5}
|> Map.add "DATAPOWER" { in_spam=0; in_ham=10}
|> Map.add "DATE" { in_spam=1; in_ham=4}
|> Map.add "DAY" { in_spam=5; in_ham=1}
|> Map.add "DAYS" { in_spam=5; in_ham=0}
|> Map.add "DBQE" { in_spam=0; in_ham=80}
|> Map.add "DCC" { in_spam=0; in_ham=8}
|> Map.add "DEAR" { in_spam=7; in_ham=0}
|> Map.add "DEBUG" { in_spam=0; in_ham=3}
|> Map.add "DEMOCRATIC" { in_spam=5; in_ham=0}
|> Map.add "DEXPORT" { in_spam=0; in_ham=3}
|> Map.add "DGXT" { in_spam=0; in_ham=6}
|> Map.add "DIAGNOSE" { in_spam=5; in_ham=0}
|> Map.add "DIGITAL" { in_spam=5; in_ham=0}
|> Map.add "DIRECT" { in_spam=6; in_ham=1}
|> Map.add "DISPLAY" { in_spam=1; in_ham=7}
|> Map.add "DIV" { in_spam=30; in_ham=5}
|> Map.add "DLINUX" { in_spam=0; in_ham=3}
|> Map.add "DMA" { in_spam=0; in_ham=13}
|> Map.add "DMCA" { in_spam=0; in_ham=9}
|> Map.add "DMODULE" { in_spam=0; in_ham=3}
|> Map.add "DNA" { in_spam=0; in_ham=4}
|> Map.add "DNFO" { in_spam=0; in_ham=3}
|> Map.add "DNS" { in_spam=1; in_ham=21}
|> Map.add "DNSBL" { in_spam=0; in_ham=3}
|> Map.add "DOCTYPE" { in_spam=36; in_ham=5}
|> Map.add "DOES" { in_spam=3; in_ham=3}
|> Map.add "DOLLARS" { in_spam=10; in_ham=0}
|> Map.add "DOS" { in_spam=2; in_ham=3}
|> Map.add "DREAMS" { in_spam=7; in_ham=0}
|> Map.add "DROPPRIVS" { in_spam=0; in_ham=5}
|> Map.add "DRS" { in_spam=0; in_ham=4}
|> Map.add "DSA" { in_spam=0; in_ham=13}
|> Map.add "DSL" { in_spam=0; in_ham=5}
|> Map.add "DTD" { in_spam=36; in_ham=7}
|> Map.add "DUE" { in_spam=10; in_ham=0}
|> Map.add "DVD" { in_spam=6; in_ham=24}
|> Map.add "EACH" { in_spam=8; in_ham=0}
|> Map.add "EASY" { in_spam=12; in_ham=0}
|> Map.add "EBEDCB" { in_spam=5; in_ham=0}
|> Map.add "EDT" { in_spam=0; in_ham=19}
|> Map.add "EDU" { in_spam=3; in_ham=1}
|> Map.add "EFF" { in_spam=0; in_ham=5}
|> Map.add "EFFECTIVE" { in_spam=4; in_ham=1}
|> Map.add "EFFORT" { in_spam=9; in_ham=0}
|> Map.add "EIDE" { in_spam=0; in_ham=3}
|> Map.add "EITHER" { in_spam=2; in_ham=5}
|> Map.add "EMAIL" { in_spam=20; in_ham=2}
|> Map.add "END" { in_spam=4; in_ham=99}
|> Map.add "ENVELOPE" { in_spam=7; in_ham=0}
|> Map.add "EPIC" { in_spam=0; in_ham=3}
|> Map.add "EST" { in_spam=2; in_ham=2}
|> Map.add "EVENT" { in_spam=1; in_ham=3}
|> Map.add "EVER" { in_spam=17; in_ham=1}
|> Map.add "EVERY" { in_spam=6; in_ham=0}
|> Map.add "EVERYTHING" { in_spam=6; in_ham=0}
|> Map.add "EXACTLY" { in_spam=9; in_ham=0}
|> Map.add "EXCESS" { in_spam=5; in_ham=0}
|> Map.add "EXCLUSIVE" { in_spam=5; in_ham=0}
|> Map.add "EXMH" { in_spam=0; in_ham=8}
|> Map.add "EXPERTS" { in_spam=5; in_ham=0}
|> Map.add "EXPIRATION" { in_spam=5; in_ham=0}
|> Map.add "EXPORT" { in_spam=0; in_ham=3}
|> Map.add "FACE" { in_spam=8; in_ham=1}
|> Map.add "FACT" { in_spam=3; in_ham=1}
|> Map.add "FAMILY" { in_spam=5; in_ham=1}
|> Map.add "FAQ" { in_spam=6; in_ham=6}
|> Map.add "FAST" { in_spam=4; in_ham=1}
|> Map.add "FASTEST" { in_spam=7; in_ham=0}
|> Map.add "FAX" { in_spam=15; in_ham=2}
|> Map.add "FBI" { in_spam=1; in_ham=12}
|> Map.add "FCC" { in_spam=0; in_ham=7}
|> Map.add "FDDI" { in_spam=0; in_ham=6}
|> Map.add "FEDERAL" { in_spam=5; in_ham=0}
|> Map.add "FFFF" { in_spam=29; in_ham=1}
|> Map.add "FFFFAE" { in_spam=5; in_ham=0}
|> Map.add "FFFFCC" { in_spam=13; in_ham=1}
|> Map.add "FFFFFF" { in_spam=98; in_ham=1}
|> Map.add "FIGURE" { in_spam=9; in_ham=0}
|> Map.add "FILE" { in_spam=5; in_ham=2}
|> Map.add "FINANCIAL" { in_spam=8; in_ham=0}
|> Map.add "FIXED" { in_spam=2; in_ham=4}
|> Map.add "FMI" { in_spam=0; in_ham=3}
|> Map.add "FOAF" { in_spam=0; in_ham=8}
|> Map.add "FOLLOW" { in_spam=7; in_ham=0}
|> Map.add "FOLLOWING" { in_spam=9; in_ham=0}
|> Map.add "FONT" { in_spam=84; in_ham=7}
|> Map.add "FOR" { in_spam=55; in_ham=7}
|> Map.add "FORM" { in_spam=23; in_ham=0}
|> Map.add "FREE" { in_spam=149; in_ham=110}
|> Map.add "FREEDOM" { in_spam=6; in_ham=0}
|> Map.add "FRIEND" { in_spam=9; in_ham=0}
|> Map.add "FROM" { in_spam=29; in_ham=4}
|> Map.add "FTAM" { in_spam=0; in_ham=6}
|> Map.add "FTC" { in_spam=0; in_ham=4}
|> Map.add "FTP" { in_spam=2; in_ham=6}
|> Map.add "FULL" { in_spam=5; in_ham=0}
|> Map.add "FUTURE" { in_spam=9; in_ham=0}
|> Map.add "FWIW" { in_spam=0; in_ham=5}
|> Map.add "FYI" { in_spam=0; in_ham=6}
|> Map.add "GAB" { in_spam=0; in_ham=3}
|> Map.add "GCC" { in_spam=0; in_ham=4}
|> Map.add "GDC" { in_spam=0; in_ham=4}
|> Map.add "GEN" { in_spam=3; in_ham=4}
|> Map.add "GENERATE" { in_spam=8; in_ham=0}
|> Map.add "GENERATOR" { in_spam=63; in_ham=5}
|> Map.add "GEORGE" { in_spam=3; in_ham=1}
|> Map.add "GET" { in_spam=28; in_ham=0}
|> Map.add "GIF" { in_spam=1; in_ham=2}
|> Map.add "GMT" { in_spam=0; in_ham=57}
|> Map.add "GNOME" { in_spam=0; in_ham=3}
|> Map.add "GNU" { in_spam=0; in_ham=89}
|> Map.add "GOOD" { in_spam=4; in_ham=1}
|> Map.add "GPG" { in_spam=1; in_ham=11}
|> Map.add "GPL" { in_spam=0; in_ham=10}
|> Map.add "GPRS" { in_spam=0; in_ham=5}
|> Map.add "GREAT" { in_spam=4; in_ham=1}
|> Map.add "GROWING" { in_spam=5; in_ham=0}
|> Map.add "GSM" { in_spam=0; in_ham=4}
|> Map.add "GUARANTEE" { in_spam=5; in_ham=0}
|> Map.add "GUARANTEED" { in_spam=20; in_ham=0}
|> Map.add "GUI" { in_spam=0; in_ham=4}
|> Map.add "GUIDELINES" { in_spam=6; in_ham=0}
|> Map.add "HAA" { in_spam=0; in_ham=11}
|> Map.add "HARD" { in_spam=4; in_ham=1}
|> Map.add "HAS" { in_spam=11; in_ham=0}
|> Map.add "HAVE" { in_spam=15; in_ham=3}
|> Map.add "HBS" { in_spam=3; in_ham=1}
|> Map.add "HDI" { in_spam=0; in_ham=3}
|> Map.add "HEAD" { in_spam=60; in_ham=8}
|> Map.add "HEIGHT" { in_spam=14; in_ham=0}
|> Map.add "HELPS" { in_spam=5; in_ham=0}
|> Map.add "HERE" { in_spam=79; in_ham=0}
|> Map.add "HIL" { in_spam=0; in_ham=5}
|> Map.add "HITOFF" { in_spam=0; in_ham=3}
|> Map.add "HIV" { in_spam=1; in_ham=6}
|> Map.add "HOME" { in_spam=8; in_ham=3}
|> Map.add "HONORED" { in_spam=5; in_ham=0}
|> Map.add "HOT" { in_spam=6; in_ham=0}
|> Map.add "HOW" { in_spam=14; in_ham=6}
|> Map.add "HREF" { in_spam=20; in_ham=2}
|> Map.add "HTH" { in_spam=0; in_ham=5}
|> Map.add "HTML" { in_spam=90; in_ham=52}
|> Map.add "HTTP" { in_spam=0; in_ham=11}
|> Map.add "HUGE" { in_spam=5; in_ham=2}
|> Map.add "HUNDREDS" { in_spam=6; in_ham=0}
|> Map.add "IAA" { in_spam=2; in_ham=2}
|> Map.add "IBM" { in_spam=1; in_ham=12}
|> Map.add "ICANN" { in_spam=6; in_ham=0}
|> Map.add "ICQ" { in_spam=0; in_ham=22}
|> Map.add "IDE" { in_spam=0; in_ham=8}
|> Map.add "IEEE" { in_spam=0; in_ham=10}
|> Map.add "IETF" { in_spam=0; in_ham=6}
|> Map.add "III" { in_spam=9; in_ham=53}
|> Map.add "IIRC" { in_spam=0; in_ham=12}
|> Map.add "IIS" { in_spam=0; in_ham=3}
|> Map.add "IIU" { in_spam=0; in_ham=3}
|> Map.add "ILUG" { in_spam=0; in_ham=11}
|> Map.add "IMAP" { in_spam=0; in_ham=8}
|> Map.add "IMF" { in_spam=2; in_ham=4}
|> Map.add "IMG" { in_spam=52; in_ham=52}
|> Map.add "IMHO" { in_spam=0; in_ham=16}
|> Map.add "IMO" { in_spam=0; in_ham=13}
|> Map.add "IMPORTANT" { in_spam=13; in_ham=1}
|> Map.add "IMPRESSIVE" { in_spam=5; in_ham=0}
|> Map.add "INCLUDING" { in_spam=5; in_ham=1}
|> Map.add "INCOME" { in_spam=13; in_ham=0}
|> Map.add "INCREASE" { in_spam=12; in_ham=0}
|> Map.add "INDUSTRY" { in_spam=5; in_ham=0}
|> Map.add "INFO" { in_spam=13; in_ham=4}
|> Map.add "INFORMATION" { in_spam=13; in_ham=1}
|> Map.add "INPUT" { in_spam=16; in_ham=0}
|> Map.add "INSTANT" { in_spam=10; in_ham=0}
|> Map.add "INSTRUCTED" { in_spam=8; in_ham=0}
|> Map.add "INSTRUCTION" { in_spam=5; in_ham=0}
|> Map.add "INSTRUCTIONS" { in_spam=6; in_ham=0}
|> Map.add "INTEREST" { in_spam=8; in_ham=0}
|> Map.add "INTERNET" { in_spam=14; in_ham=1}
|> Map.add "INTO" { in_spam=11; in_ham=0}
|> Map.add "INVALID" { in_spam=0; in_ham=4}
|> Map.add "INVEST" { in_spam=7; in_ham=0}
|> Map.add "INVESTMENT" { in_spam=7; in_ham=0}
|> Map.add "IPO" { in_spam=0; in_ham=6}
|> Map.add "IRA" { in_spam=0; in_ham=5}
|> Map.add "IRC" { in_spam=0; in_ham=5}
|> Map.add "IRS" { in_spam=1; in_ham=5}
|> Map.add "IRTF" { in_spam=0; in_ham=6}
|> Map.add "ISDN" { in_spam=1; in_ham=2}
|> Map.add "ISO" { in_spam=0; in_ham=8}
|> Map.add "ISP" { in_spam=3; in_ham=14}
|> Map.add "ITS" { in_spam=6; in_ham=1}
|> Map.add "IVR" { in_spam=0; in_ham=3}
|> Map.add "JACK" { in_spam=0; in_ham=4}
|> Map.add "JDK" { in_spam=1; in_ham=3}
|> Map.add "JID" { in_spam=0; in_ham=9}
|> Map.add "JIT" { in_spam=0; in_ham=6}
|> Map.add "JUST" { in_spam=16; in_ham=3}
|> Map.add "KABILA" { in_spam=5; in_ham=0}
|> Map.add "KCET" { in_spam=0; in_ham=3}
|> Map.add "KDE" { in_spam=0; in_ham=8}
|> Map.add "KEEP" { in_spam=14; in_ham=0}
|> Map.add "KERNEL" { in_spam=0; in_ham=7}
|> Map.add "KFJC" { in_spam=0; in_ham=4}
|> Map.add "KNOW" { in_spam=10; in_ham=2}
|> Map.add "LAN" { in_spam=1; in_ham=11}
|> Map.add "LAURENT" { in_spam=5; in_ham=0}
|> Map.add "LCD" { in_spam=0; in_ham=6}
|> Map.add "LED" { in_spam=0; in_ham=4}
|> Map.add "LEFT" { in_spam=12; in_ham=1}
|> Map.add "LEGALLY" { in_spam=11; in_ham=0}
|> Map.add "LEMANN" { in_spam=0; in_ham=3}
|> Map.add "LESS" { in_spam=9; in_ham=0}
|> Map.add "LIE" { in_spam=7; in_ham=0}
|> Map.add "LIFE" { in_spam=5; in_ham=1}
|> Map.add "LIH" { in_spam=0; in_ham=7}
|> Map.add "LIKE" { in_spam=10; in_ham=4}
|> Map.add "LIMIT" { in_spam=9; in_ham=0}
|> Map.add "LIMITED" { in_spam=7; in_ham=1}
|> Map.add "LINKS" { in_spam=1; in_ham=3}
|> Map.add "LINUX" { in_spam=0; in_ham=5}
|> Map.add "LIST" { in_spam=18; in_ham=0}
|> Map.add "LITTLE" { in_spam=8; in_ham=0}
|> Map.add "LLC" { in_spam=5; in_ham=8}
|> Map.add "LOCAL" { in_spam=3; in_ham=1}
|> Map.add "LOL" { in_spam=0; in_ham=10}
|> Map.add "LOST" { in_spam=1; in_ham=11}
|> Map.add "LOT" { in_spam=7; in_ham=2}
|> Map.add "LOW" { in_spam=21; in_ham=0}
|> Map.add "LUCK" { in_spam=1; in_ham=2}
|> Map.add "MACHINE" { in_spam=6; in_ham=0}
|> Map.add "MAIL" { in_spam=2; in_ham=2}
|> Map.add "MAILED" { in_spam=7; in_ham=0}
|> Map.add "MAJOR" { in_spam=5; in_ham=0}
|> Map.add "MAKE" { in_spam=14; in_ham=0}
|> Map.add "MAKES" { in_spam=5; in_ham=0}
|> Map.add "MAKING" { in_spam=9; in_ham=0}
|> Map.add "MANY" { in_spam=1; in_ham=4}
|> Map.add "MARKETING" { in_spam=7; in_ham=0}
|> Map.add "MARLA" { in_spam=0; in_ham=4}
|> Map.add "MARRIAGE" { in_spam=0; in_ham=3}
|> Map.add "MATTER" { in_spam=7; in_ham=0}
|> Map.add "MAX" { in_spam=0; in_ham=4}
|> Map.add "MAY" { in_spam=5; in_ham=1}
|> Map.add "MBA" { in_spam=1; in_ham=4}
|> Map.add "MDT" { in_spam=0; in_ham=10}
|> Map.add "META" { in_spam=45; in_ham=5}
|> Map.add "METHOD" { in_spam=11; in_ham=0}
|> Map.add "MIAMI" { in_spam=0; in_ham=3}
|> Map.add "MIDI" { in_spam=0; in_ham=4}
|> Map.add "MILLION" { in_spam=8; in_ham=0}
|> Map.add "MIME" { in_spam=1; in_ham=18}
|> Map.add "MINCOUNT" { in_spam=0; in_ham=4}
|> Map.add "MISTAKES" { in_spam=5; in_ham=0}
|> Map.add "MIT" { in_spam=0; in_ham=10}
|> Map.add "MLM" { in_spam=12; in_ham=0}
|> Map.add "MMS" { in_spam=0; in_ham=3}
|> Map.add "MODULE" { in_spam=0; in_ham=3}
|> Map.add "MONEY" { in_spam=29; in_ham=0}
|> Map.add "MORE" { in_spam=30; in_ham=3}
|> Map.add "MOST" { in_spam=6; in_ham=0}
|> Map.add "MPH" { in_spam=0; in_ham=4}
|> Map.add "MSHTML" { in_spam=24; in_ham=4}
|> Map.add "MSIE" { in_spam=0; in_ham=5}
|> Map.add "MSM" { in_spam=0; in_ham=3}
|> Map.add "MSN" { in_spam=0; in_ham=32}
|> Map.add "MSNBC" { in_spam=0; in_ham=3}
|> Map.add "MTA" { in_spam=0; in_ham=15}
|> Map.add "MUA" { in_spam=0; in_ham=4}
|> Map.add "MUST" { in_spam=13; in_ham=5}
|> Map.add "NAME" { in_spam=40; in_ham=7}
|> Map.add "NASA" { in_spam=1; in_ham=9}
|> Map.add "NASDAQ" { in_spam=0; in_ham=6}
|> Map.add "NAT" { in_spam=0; in_ham=4}
|> Map.add "NATO" { in_spam=1; in_ham=5}
|> Map.add "NBC" { in_spam=6; in_ham=0}
|> Map.add "NEED" { in_spam=6; in_ham=3}
|> Map.add "NET" { in_spam=7; in_ham=12}
|> Map.add "NETNOTEINC" { in_spam=15; in_ham=0}
|> Map.add "NEVER" { in_spam=23; in_ham=1}
|> Map.add "NEW" { in_spam=18; in_ham=20}
|> Map.add "NEWS" { in_spam=10; in_ham=2}
|> Map.add "NEXT" { in_spam=5; in_ham=1}
|> Map.add "NFL" { in_spam=0; in_ham=3}
|> Map.add "NFS" { in_spam=0; in_ham=3}
|> Map.add "NICHOLAS" { in_spam=0; in_ham=3}
|> Map.add "NIGERIA" { in_spam=7; in_ham=0}
|> Map.add "NMH" { in_spam=0; in_ham=3}
|> Map.add "NOKEY" { in_spam=0; in_ham=3}
|> Map.add "NONSPAM" { in_spam=0; in_ham=5}
|> Map.add "NOT" { in_spam=93; in_ham=35}
|> Map.add "NOTE" { in_spam=18; in_ham=2}
|> Map.add "NOTHING" { in_spam=7; in_ham=2}
|> Map.add "NOTICE" { in_spam=4; in_ham=2}
|> Map.add "NOW" { in_spam=84; in_ham=2}
|> Map.add "NPR" { in_spam=0; in_ham=4}
|> Map.add "NTK" { in_spam=1; in_ham=2}
|> Map.add "NUMBER" { in_spam=11; in_ham=0}
|> Map.add "NUMBERS" { in_spam=7; in_ham=0}
|> Map.add "NVIDIA" { in_spam=0; in_ham=3}
|> Map.add "OBB" { in_spam=0; in_ham=5}
|> Map.add "ODBC" { in_spam=1; in_ham=2}
|> Map.add "OFF" { in_spam=4; in_ham=1}
|> Map.add "OFFER" { in_spam=12; in_ham=1}
|> Map.add "ONCE" { in_spam=6; in_ham=0}
|> Map.add "ONE" { in_spam=13; in_ham=1}
|> Map.add "ONLINE" { in_spam=7; in_ham=0}
|> Map.add "ONLY" { in_spam=28; in_ham=1}
|> Map.add "OPML" { in_spam=0; in_ham=3}
|> Map.add "ORBT" { in_spam=5; in_ham=0}
|> Map.add "ORDER" { in_spam=32; in_ham=1}
|> Map.add "ORDERING" { in_spam=9; in_ham=0}
|> Map.add "ORDERS" { in_spam=9; in_ham=0}
|> Map.add "ORG" { in_spam=3; in_ham=2}
|> Map.add "ORIGINATOR" { in_spam=8; in_ham=0}
|> Map.add "ORKPLACE" { in_spam=0; in_ham=5}
|> Map.add "OSCON" { in_spam=0; in_ham=4}
|> Map.add "OSDN" { in_spam=2; in_ham=106}
|> Map.add "OSI" { in_spam=0; in_ham=8}
|> Map.add "OSS" { in_spam=1; in_ham=17}
|> Map.add "OTC" { in_spam=5; in_ham=0}
|> Map.add "OTCBB" { in_spam=6; in_ham=0}
|> Map.add "OTHER" { in_spam=13; in_ham=2}
|> Map.add "OTHERS" { in_spam=5; in_ham=1}
|> Map.add "OTOH" { in_spam=0; in_ham=11}
|> Map.add "OUR" { in_spam=11; in_ham=1}
|> Map.add "OUT" { in_spam=22; in_ham=1}
|> Map.add "OVER" { in_spam=7; in_ham=0}
|> Map.add "OVERALL" { in_spam=0; in_ham=5}
|> Map.add "PAPER" { in_spam=7; in_ham=0}
|> Map.add "PBS" { in_spam=0; in_ham=5}
|> Map.add "PCI" { in_spam=0; in_ham=4}
|> Map.add "PCM" { in_spam=0; in_ham=4}
|> Map.add "PDA" { in_spam=0; in_ham=4}
|> Map.add "PDF" { in_spam=0; in_ham=5}
|> Map.add "PDIF" { in_spam=0; in_ham=3}
|> Map.add "PDT" { in_spam=0; in_ham=14}
|> Map.add "PENCIL" { in_spam=7; in_ham=0}
|> Map.add "PEOPLE" { in_spam=12; in_ham=0}
|> Map.add "PER" { in_spam=5; in_ham=0}
|> Map.add "PGP" { in_spam=0; in_ham=110}
|> Map.add "PHONE" { in_spam=12; in_ham=0}
|> Map.add "PHP" { in_spam=2; in_ham=4}
|> Map.add "PITFALLS" { in_spam=0; in_ham=3}
|> Map.add "PKI" { in_spam=0; in_ham=4}
|> Map.add "PLACE" { in_spam=9; in_ham=0}
|> Map.add "PLACING" { in_spam=8; in_ham=0}
|> Map.add "PLEASE" { in_spam=20; in_ham=2}
|> Map.add "PLUS" { in_spam=6; in_ham=0}
|> Map.add "PNNI" { in_spam=0; in_ham=6}
|> Map.add "POLICY" { in_spam=4; in_ham=2}
|> Map.add "POP" { in_spam=4; in_ham=12}
|> Map.add "POPULARITY" { in_spam=7; in_ham=0}
|> Map.add "POSIX" { in_spam=0; in_ham=3}
|> Map.add "POSSIBLE" { in_spam=6; in_ham=0}
|> Map.add "POST" { in_spam=2; in_ham=2}
|> Map.add "PREVENT" { in_spam=7; in_ham=0}
|> Map.add "PRIMARY" { in_spam=0; in_ham=4}
|> Map.add "PRINT" { in_spam=9; in_ham=1}
|> Map.add "PROBLEM" { in_spam=5; in_ham=0}
|> Map.add "PROCESS" { in_spam=8; in_ham=0}
|> Map.add "PROGRAM" { in_spam=9; in_ham=0}
|> Map.add "PROGRESS" { in_spam=7; in_ham=0}
|> Map.add "PROTECION" { in_spam=5; in_ham=0}
|> Map.add "PSU" { in_spam=0; in_ham=3}
|> Map.add "PTO" { in_spam=0; in_ham=3}
|> Map.add "PUBLIC" { in_spam=37; in_ham=6}
|> Map.add "PUC" { in_spam=0; in_ham=3}
|> Map.add "PURPOSE" { in_spam=3; in_ham=1}
|> Map.add "QED" { in_spam=0; in_ham=3}
|> Map.add "QUESTIONS" { in_spam=9; in_ham=0}
|> Map.add "RAH" { in_spam=0; in_ham=24}
|> Map.add "RAID" { in_spam=0; in_ham=7}
|> Map.add "RAM" { in_spam=1; in_ham=8}
|> Map.add "RANK" { in_spam=0; in_ham=3}
|> Map.add "RAPIDLY" { in_spam=5; in_ham=0}
|> Map.add "RATES" { in_spam=6; in_ham=0}
|> Map.add "RATS" { in_spam=0; in_ham=4}
|> Map.add "RAW" { in_spam=2; in_ham=2}
|> Map.add "RBL" { in_spam=0; in_ham=5}
|> Map.add "RBS" { in_spam=0; in_ham=4}
|> Map.add "RCS" { in_spam=0; in_ham=15}
|> Map.add "RDBMS" { in_spam=0; in_ham=6}
|> Map.add "RDF" { in_spam=0; in_ham=12}
|> Map.add "READ" { in_spam=9; in_ham=3}
|> Map.add "README" { in_spam=0; in_ham=17}
|> Map.add "REALLY" { in_spam=2; in_ham=4}
|> Map.add "REASONS" { in_spam=6; in_ham=0}
|> Map.add "RECEIVE" { in_spam=9; in_ham=0}
|> Map.add "RECENT" { in_spam=7; in_ham=0}
|> Map.add "REFERENCE" { in_spam=8; in_ham=0}
|> Map.add "RELAX" { in_spam=7; in_ham=0}
|> Map.add "REMEMBER" { in_spam=9; in_ham=0}
|> Map.add "REMOVE" { in_spam=41; in_ham=1}
|> Map.add "REPLY" { in_spam=36; in_ham=0}
|> Map.add "REPORT" { in_spam=9; in_ham=0}
|> Map.add "REPORTS" { in_spam=9; in_ham=0}
|> Map.add "REPUBLIC" { in_spam=5; in_ham=0}
|> Map.add "REQUEST" { in_spam=4; in_ham=1}
|> Map.add "RESOLVED" { in_spam=0; in_ham=7}
|> Map.add "RESPECT" { in_spam=7; in_ham=0}
|> Map.add "RESPONSES" { in_spam=7; in_ham=0}
|> Map.add "RETURN" { in_spam=8; in_ham=0}
|> Map.add "RFC" { in_spam=0; in_ham=10}
|> Map.add "RIAA" { in_spam=0; in_ham=9}
|> Map.add "RIGHT" { in_spam=9; in_ham=0}
|> Map.add "RISK" { in_spam=12; in_ham=0}
|> Map.add "ROAD" { in_spam=7; in_ham=0}
|> Map.add "RPM" { in_spam=0; in_ham=46}
|> Map.add "RPMS" { in_spam=0; in_ham=11}
|> Map.add "RSA" { in_spam=0; in_ham=5}
|> Map.add "RSS" { in_spam=0; in_ham=19}
|> Map.add "SAME" { in_spam=1; in_ham=2}
|> Map.add "SAN" { in_spam=3; in_ham=2}
|> Map.add "SAVE" { in_spam=7; in_ham=1}
|> Map.add "SBC" { in_spam=0; in_ham=5}
|> Map.add "SCO" { in_spam=1; in_ham=5}
|> Map.add "SCORE" { in_spam=0; in_ham=4}
|> Map.add "SCSI" { in_spam=0; in_ham=6}
|> Map.add "SDL" { in_spam=0; in_ham=3}
|> Map.add "SEARCH" { in_spam=7; in_ham=0}
|> Map.add "SEC" { in_spam=0; in_ham=8}
|> Map.add "SECPROG" { in_spam=0; in_ham=4}
|> Map.add "SECTION" { in_spam=5; in_ham=2}
|> Map.add "SEE" { in_spam=7; in_ham=1}
|> Map.add "SEEN" { in_spam=5; in_ham=0}
|> Map.add "SELL" { in_spam=5; in_ham=0}
|> Map.add "SEND" { in_spam=14; in_ham=1}
|> Map.add "SENDING" { in_spam=9; in_ham=0}
|> Map.add "SERVICE" { in_spam=6; in_ham=0}
|> Map.add "SERVICES" { in_spam=4; in_ham=1}
|> Map.add "SEX" { in_spam=4; in_ham=1}
|> Map.add "SGO" { in_spam=14; in_ham=0}
|> Map.add "SHA" { in_spam=0; in_ham=22}
|> Map.add "SHIPPING" { in_spam=9; in_ham=0}
|> Map.add "SHOULD" { in_spam=4; in_ham=1}
|> Map.add "SIGNED" { in_spam=1; in_ham=24}
|> Map.add "SIMPLE" { in_spam=8; in_ham=0}
|> Map.add "SITES" { in_spam=5; in_ham=0}
|> Map.add "SIX" { in_spam=6; in_ham=1}
|> Map.add "SIZE" { in_spam=17; in_ham=1}
|> Map.add "SMP" { in_spam=0; in_ham=4}
|> Map.add "SMS" { in_spam=1; in_ham=4}
|> Map.add "SMTP" { in_spam=0; in_ham=16}
|> Map.add "SND" { in_spam=0; in_ham=4}
|> Map.add "SNMP" { in_spam=0; in_ham=6}
|> Map.add "SOAP" { in_spam=0; in_ham=11}
|> Map.add "SOFTBANK" { in_spam=0; in_ham=6}
|> Map.add "SOFTWARE" { in_spam=8; in_ham=1}
|> Map.add "SOLD" { in_spam=5; in_ham=0}
|> Map.add "SPAM" { in_spam=9; in_ham=19}
|> Map.add "SPAMPROB" { in_spam=0; in_ham=6}
|> Map.add "SPAN" { in_spam=11; in_ham=0}
|> Map.add "SPECIAL" { in_spam=9; in_ham=2}
|> Map.add "SQL" { in_spam=1; in_ham=6}
|> Map.add "SRC" { in_spam=16; in_ham=1}
|> Map.add "SRPM" { in_spam=0; in_ham=5}
|> Map.add "SSH" { in_spam=0; in_ham=8}
|> Map.add "SSL" { in_spam=2; in_ham=10}
|> Map.add "START" { in_spam=10; in_ham=0}
|> Map.add "STARTED" { in_spam=6; in_ham=0}
|> Map.add "STATE" { in_spam=14; in_ham=0}
|> Map.add "STDIN" { in_spam=0; in_ham=12}
|> Map.add "STDOUT" { in_spam=0; in_ham=3}
|> Map.add "STILL" { in_spam=7; in_ham=2}
|> Map.add "STRONG" { in_spam=15; in_ham=1}
|> Map.add "STYLE" { in_spam=22; in_ham=5}
|> Map.add "SUBJECT" { in_spam=4; in_ham=3}
|> Map.add "SUCCESS" { in_spam=10; in_ham=0}
|> Map.add "SUCH" { in_spam=3; in_ham=1}
|> Map.add "SUM" { in_spam=3; in_ham=1}
|> Map.add "SUMMARY" { in_spam=1; in_ham=2}
|> Map.add "SURE" { in_spam=7; in_ham=0}
|> Map.add "SURPRISINGLY" { in_spam=0; in_ham=3}
|> Map.add "SUV" { in_spam=6; in_ham=1}
|> Map.add "SYMBOL" { in_spam=0; in_ham=3}
|> Map.add "SYMTAB" { in_spam=0; in_ham=3}
|> Map.add "SYSTEM" { in_spam=6; in_ham=1}
|> Map.add "TABLE" { in_spam=66; in_ham=1}
|> Map.add "TARGET" { in_spam=3; in_ham=4}
|> Map.add "TBODY" { in_spam=45; in_ham=0}
|> Map.add "TECHNOLOGY" { in_spam=0; in_ham=11}
|> Map.add "TEL" { in_spam=5; in_ham=0}
|> Map.add "TESTIMONIALS" { in_spam=7; in_ham=0}
|> Map.add "TEXT" { in_spam=5; in_ham=2}
|> Map.add "THAN" { in_spam=14; in_ham=1}
|> Map.add "THANKS" { in_spam=8; in_ham=0}
|> Map.add "THAT" { in_spam=18; in_ham=12}
|> Map.add "THE" { in_spam=49; in_ham=20}
|> Map.add "THEN" { in_spam=7; in_ham=0}
|> Map.add "THESE" { in_spam=9; in_ham=0}
|> Map.add "THEY" { in_spam=0; in_ham=6}
|> Map.add "THIS" { in_spam=34; in_ham=5}
|> Map.add "THOUSANDS" { in_spam=5; in_ham=0}
|> Map.add "TIA" { in_spam=0; in_ham=4}
|> Map.add "TIME" { in_spam=13; in_ham=0}
|> Map.add "TIMES" { in_spam=7; in_ham=2}
|> Map.add "TITLE" { in_spam=46; in_ham=1}
|> Map.add "TMDA" { in_spam=0; in_ham=20}
|> Map.add "TODAY" { in_spam=22; in_ham=0}
|> Map.add "TODO" { in_spam=0; in_ham=4}
|> Map.add "TONY" { in_spam=0; in_ham=5}
|> Map.add "TOOLS" { in_spam=6; in_ham=0}
|> Map.add "TOP" { in_spam=13; in_ham=0}
|> Map.add "TOPDIR" { in_spam=0; in_ham=3}
|> Map.add "TOTAL" { in_spam=10; in_ham=0}
|> Map.add "TRACK" { in_spam=8; in_ham=0}
|> Map.add "TRUE" { in_spam=8; in_ham=0}
|> Map.add "TRUST" { in_spam=6; in_ham=0}
|> Map.add "TRY" { in_spam=5; in_ham=1}
|> Map.add "TURNS" { in_spam=5; in_ham=0}
|> Map.add "TWO" { in_spam=5; in_ham=0}
|> Map.add "TYPE" { in_spam=14; in_ham=0}
|> Map.add "UCI" { in_spam=0; in_ham=3}
|> Map.add "UEFAS" { in_spam=5; in_ham=0}
|> Map.add "UNBEATABLE" { in_spam=5; in_ham=0}
|> Map.add "UNITED" { in_spam=5; in_ham=0}
|> Map.add "UNIX" { in_spam=0; in_ham=14}
|> Map.add "UNKNOWN" { in_spam=0; in_ham=5}
|> Map.add "URGENT" { in_spam=3; in_ham=1}
|> Map.add "URL" { in_spam=13; in_ham=665}
|> Map.add "USA" { in_spam=17; in_ham=56}
|> Map.add "USAF" { in_spam=1; in_ham=2}
|> Map.add "USB" { in_spam=1; in_ham=8}
|> Map.add "USD" { in_spam=10; in_ham=2}
|> Map.add "USE" { in_spam=8; in_ham=1}
|> Map.add "USERLAND" { in_spam=0; in_ham=3}
|> Map.add "VALIGN" { in_spam=5; in_ham=0}
|> Map.add "VALUABLE" { in_spam=5; in_ham=0}
|> Map.add "VALUE" { in_spam=5; in_ham=0}
|> Map.add "VCR" { in_spam=2; in_ham=2}
|> Map.add "VERSION" { in_spam=3; in_ham=4}
|> Map.add "VERY" { in_spam=6; in_ham=5}
|> Map.add "VHP" { in_spam=0; in_ham=3}
|> Map.add "VIAGRA" { in_spam=6; in_ham=0}
|> Map.add "VIII" { in_spam=0; in_ham=3}
|> Map.add "VISIT" { in_spam=5; in_ham=0}
|> Map.add "VMS" { in_spam=0; in_ham=3}
|> Map.add "VNC" { in_spam=0; in_ham=4}
|> Map.add "WAIT" { in_spam=5; in_ham=0}
|> Map.add "WAN" { in_spam=0; in_ham=6}
|> Map.add "WANT" { in_spam=16; in_ham=6}
|> Map.add "WAS" { in_spam=7; in_ham=2}
|> Map.add "WASHINGTON" { in_spam=0; in_ham=3}
|> Map.add "WAY" { in_spam=8; in_ham=2}
|> Map.add "WEB" { in_spam=6; in_ham=0}
|> Map.add "WEBSITE" { in_spam=7; in_ham=0}
|> Map.add "WHAT" { in_spam=9; in_ham=0}
|> Map.add "WHEN" { in_spam=6; in_ham=0}
|> Map.add "WHERE" { in_spam=6; in_ham=0}
|> Map.add "WHOLE" { in_spam=8; in_ham=0}
|> Map.add "WHOLESALE" { in_spam=5; in_ham=0}
|> Map.add "WHY" { in_spam=7; in_ham=3}
|> Map.add "WIDTH" { in_spam=25; in_ham=0}
|> Map.add "WILL" { in_spam=28; in_ham=1}
|> Map.add "WITH" { in_spam=21; in_ham=1}
|> Map.add "WITHIN" { in_spam=10; in_ham=0}
|> Map.add "WONTFIX" { in_spam=0; in_ham=4}
|> Map.add "WORK" { in_spam=7; in_ham=0}
|> Map.add "WORKING" { in_spam=9; in_ham=0}
|> Map.add "WORKS" { in_spam=4; in_ham=1}
|> Map.add "WORLD" { in_spam=2; in_ham=3}
|> Map.add "WORST" { in_spam=7; in_ham=1}
|> Map.add "WORTH" { in_spam=8; in_ham=1}
|> Map.add "WRT" { in_spam=0; in_ham=7}
|> Map.add "WTF" { in_spam=0; in_ham=9}
|> Map.add "WTO" { in_spam=0; in_ham=4}
|> Map.add "WWII" { in_spam=0; in_ham=3}
|> Map.add "XHTML" { in_spam=0; in_ham=5}
|> Map.add "XML" { in_spam=0; in_ham=33}
|> Map.add "XMMS" { in_spam=0; in_ham=8}
|> Map.add "XPE" { in_spam=0; in_ham=6}
|> Map.add "XPS" { in_spam=0; in_ham=4}
|> Map.add "XSL" { in_spam=0; in_ham=6}
|> Map.add "XXX" { in_spam=10; in_ham=3}
|> Map.add "YAPC" { in_spam=0; in_ham=7}
|> Map.add "YBB" { in_spam=0; in_ham=51}
|> Map.add "YEAR" { in_spam=6; in_ham=0}
|> Map.add "YES" { in_spam=5; in_ham=0}
|> Map.add "YOU" { in_spam=76; in_ham=1}
|> Map.add "YOUR" { in_spam=54; in_ham=0}
|> Map.add "YOURS" { in_spam=17; in_ham=0}
|> Map.add "ZTVN" { in_spam=0; in_ham=4}
|> Map.add "a-fa-f" { in_spam=0; in_ham=3}
|> Map.add "a-level" { in_spam=0; in_ham=3}
|> Map.add "aalib" { in_spam=0; in_ham=7}
|> Map.add "aap" { in_spam=0; in_ham=5}
|> Map.add "aaron" { in_spam=0; in_ham=9}
|> Map.add "aaronsw" { in_spam=0; in_ham=20}
|> Map.add "aaxine" { in_spam=0; in_ham=6}
|> Map.add "abacha" { in_spam=5; in_ham=0}
|> Map.add "abandon" { in_spam=2; in_ham=3}
|> Map.add "abandoned" { in_spam=3; in_ham=9}
|> Map.add "abc" { in_spam=2; in_ham=3}
|> Map.add "abcnews" { in_spam=0; in_ham=3}
|> Map.add "abidjan" { in_spam=7; in_ham=0}
|> Map.add "abilities" { in_spam=0; in_ham=4}
|> Map.add "ability" { in_spam=13; in_ham=71}
|> Map.add "abiword" { in_spam=0; in_ham=4}
|> Map.add "able" { in_spam=20; in_ham=119}
|> Map.add "aboard" { in_spam=0; in_ham=5}
|> Map.add "abolition" { in_spam=0; in_ham=4}
|> Map.add "aborted" { in_spam=0; in_ham=5}
|> Map.add "about" { in_spam=121; in_ham=670}
|> Map.add "above" { in_spam=53; in_ham=73}
|> Map.add "abraham" { in_spam=0; in_ham=3}
|> Map.add "abroad" { in_spam=4; in_ham=6}
|> Map.add "absence" { in_spam=2; in_ham=8}
|> Map.add "absense" { in_spam=0; in_ham=4}
|> Map.add "absent" { in_spam=0; in_ham=4}
|> Map.add "absolute" { in_spam=6; in_ham=18}
|> Map.add "absolutely" { in_spam=43; in_ham=33}
|> Map.add "absorbed" { in_spam=0; in_ham=4}
|> Map.add "abstract" { in_spam=2; in_ham=6}
|> Map.add "abstraction" { in_spam=0; in_ham=6}
|> Map.add "absurd" { in_spam=0; in_ham=3}
|> Map.add "abu" { in_spam=1; in_ham=2}
|> Map.add "abundant" { in_spam=1; in_ham=2}
|> Map.add "abuse" { in_spam=14; in_ham=8}
|> Map.add "abused" { in_spam=1; in_ham=3}
|> Map.add "abusers" { in_spam=1; in_ham=2}
|> Map.add "academic" { in_spam=3; in_ham=7}
|> Map.add "academy" { in_spam=0; in_ham=3}
|> Map.add "accelerate" { in_spam=0; in_ham=8}
|> Map.add "accelerating" { in_spam=0; in_ham=4}
|> Map.add "acceleration" { in_spam=0; in_ham=9}
|> Map.add "accelerator" { in_spam=0; in_ham=6}
|> Map.add "accelerators" { in_spam=0; in_ham=7}
|> Map.add "accept" { in_spam=29; in_ham=41}
|> Map.add "acceptable" { in_spam=2; in_ham=12}
|> Map.add "acceptance" { in_spam=5; in_ham=7}
|> Map.add "accepted" { in_spam=24; in_ham=12}
|> Map.add "accepting" { in_spam=2; in_ham=9}
|> Map.add "access" { in_spam=54; in_ham=89}
|> Map.add "accessed" { in_spam=0; in_ham=3}
|> Map.add "accessible" { in_spam=7; in_ham=8}
|> Map.add "accessories" { in_spam=4; in_ham=1}
|> Map.add "accident" { in_spam=2; in_ham=11}
|> Map.add "accidentally" { in_spam=0; in_ham=5}
|> Map.add "accommodate" { in_spam=1; in_ham=2}
|> Map.add "accompanying" { in_spam=2; in_ham=2}
|> Map.add "accomplish" { in_spam=1; in_ham=11}
|> Map.add "accomplished" { in_spam=1; in_ham=7}
|> Map.add "accordance" { in_spam=1; in_ham=2}
|> Map.add "according" { in_spam=14; in_ham=65}
|> Map.add "accordingly" { in_spam=1; in_ham=8}
|> Map.add "account" { in_spam=40; in_ham=35}
|> Map.add "accountant" { in_spam=8; in_ham=0}
|> Map.add "accounting" { in_spam=1; in_ham=11}
|> Map.add "accounts" { in_spam=16; in_ham=23}
|> Map.add "accrue" { in_spam=0; in_ham=3}
|> Map.add "accrued" { in_spam=3; in_ham=1}
|> Map.add "accumulation" { in_spam=1; in_ham=3}
|> Map.add "accuracy" { in_spam=1; in_ham=7}
|> Map.add "accurate" { in_spam=2; in_ham=21}
|> Map.add "accurately" { in_spam=7; in_ham=6}
|> Map.add "accused" { in_spam=0; in_ham=10}
|> Map.add "accustomed" { in_spam=0; in_ham=3}
|> Map.add "achieve" { in_spam=8; in_ham=14}
|> Map.add "achieved" { in_spam=4; in_ham=4}
|> Map.add "achievement" { in_spam=0; in_ham=16}
|> Map.add "achieving" { in_spam=4; in_ham=3}
|> Map.add "acknowledge" { in_spam=7; in_ham=2}
|> Map.add "acknowledged" { in_spam=2; in_ham=2}
|> Map.add "acm" { in_spam=0; in_ham=8}
|> Map.add "acpi" { in_spam=0; in_ham=25}
|> Map.add "acquainted" { in_spam=1; in_ham=6}
|> Map.add "acquire" { in_spam=10; in_ham=10}
|> Map.add "acquired" { in_spam=0; in_ham=23}
|> Map.add "acquiring" { in_spam=0; in_ham=6}
|> Map.add "acquisition" { in_spam=7; in_ham=7}
|> Map.add "acronymchile" { in_spam=0; in_ham=3}
|> Map.add "across" { in_spam=8; in_ham=72}
|> Map.add "act" { in_spam=32; in_ham=45}
|> Map.add "acted" { in_spam=0; in_ham=4}
|> Map.add "acting" { in_spam=5; in_ham=11}
|> Map.add "action" { in_spam=65; in_ham=45}
|> Map.add "actions" { in_spam=3; in_ham=21}
|> Map.add "activated" { in_spam=0; in_ham=4}
|> Map.add "active" { in_spam=12; in_ham=21}
|> Map.add "actively" { in_spam=4; in_ham=15}
|> Map.add "activist" { in_spam=0; in_ham=7}
|> Map.add "activists" { in_spam=0; in_ham=12}
|> Map.add "activities" { in_spam=10; in_ham=19}
|> Map.add "activity" { in_spam=7; in_ham=15}
|> Map.add "acts" { in_spam=6; in_ham=16}
|> Map.add "actual" { in_spam=6; in_ham=50}
|> Map.add "actually" { in_spam=28; in_ham=206}
|> Map.add "actualy" { in_spam=0; in_ham=4}
|> Map.add "acuitive" { in_spam=0; in_ham=6}
|> Map.add "ad-hoc" { in_spam=0; in_ham=3}
|> Map.add "adam" { in_spam=0; in_ham=66}
|> Map.add "adam-fantasy" { in_spam=0; in_ham=6}
|> Map.add "adamson" { in_spam=0; in_ham=3}
|> Map.add "adapt" { in_spam=5; in_ham=8}
|> Map.add "adapted" { in_spam=0; in_ham=3}
|> Map.add "adapting" { in_spam=0; in_ham=3}
|> Map.add "adclick" { in_spam=13; in_ham=0}
|> Map.add "add" { in_spam=21; in_ham=167}
|> Map.add "added" { in_spam=15; in_ham=94}
|> Map.add "addicted" { in_spam=0; in_ham=3}
|> Map.add "addiction" { in_spam=0; in_ham=7}
|> Map.add "addictive" { in_spam=0; in_ham=5}
|> Map.add "addicts" { in_spam=0; in_ham=3}
|> Map.add "adding" { in_spam=1; in_ham=56}
|> Map.add "addition" { in_spam=8; in_ham=27}
|> Map.add "additional" { in_spam=16; in_ham=47}
|> Map.add "additionally" { in_spam=1; in_ham=7}
|> Map.add "additions" { in_spam=0; in_ham=6}
|> Map.add "addr" { in_spam=5; in_ham=10}
|> Map.add "address" { in_spam=117; in_ham=88}
|> Map.add "addressed" { in_spam=1; in_ham=8}
|> Map.add "addresses" { in_spam=36; in_ham=51}
|> Map.add "addressing" { in_spam=0; in_ham=11}
|> Map.add "adds" { in_spam=0; in_ham=23}
|> Map.add "adelphia" { in_spam=0; in_ham=3}
|> Map.add "adequate" { in_spam=1; in_ham=6}
|> Map.add "adinfo" { in_spam=0; in_ham=4}
|> Map.add "adjust" { in_spam=0; in_ham=7}
|> Map.add "adjusting" { in_spam=0; in_ham=3}
|> Map.add "adjustment" { in_spam=1; in_ham=2}
|> Map.add "admanmail" { in_spam=15; in_ham=0}
|> Map.add "admin" { in_spam=0; in_ham=10}
|> Map.add "administer" { in_spam=1; in_ham=5}
|> Map.add "admission" { in_spam=0; in_ham=4}
|> Map.add "admissions" { in_spam=0; in_ham=4}
|> Map.add "admit" { in_spam=0; in_ham=16}
|> Map.add "admits" { in_spam=0; in_ham=8}
|> Map.add "admitted" { in_spam=0; in_ham=7}
|> Map.add "adobe" { in_spam=1; in_ham=2}
|> Map.add "adopt" { in_spam=0; in_ham=11}
|> Map.add "adopted" { in_spam=1; in_ham=4}
|> Map.add "adopting" { in_spam=0; in_ham=13}
|> Map.add "adoption" { in_spam=1; in_ham=11}
|> Map.add "ads" { in_spam=20; in_ham=13}
|> Map.add "adsl" { in_spam=1; in_ham=3}
|> Map.add "adult" { in_spam=15; in_ham=5}
|> Map.add "adults" { in_spam=5; in_ham=2}
|> Map.add "advance" { in_spam=5; in_ham=18}
|> Map.add "advanced" { in_spam=8; in_ham=34}
|> Map.add "advancement" { in_spam=0; in_ham=3}
|> Map.add "advances" { in_spam=1; in_ham=3}
|> Map.add "advancing" { in_spam=0; in_ham=4}
|> Map.add "advantage" { in_spam=17; in_ham=48}
|> Map.add "advantages" { in_spam=1; in_ham=8}
|> Map.add "advent" { in_spam=2; in_ham=2}
|> Map.add "adventure" { in_spam=1; in_ham=3}
|> Map.add "adversary" { in_spam=0; in_ham=3}
|> Map.add "adverse" { in_spam=1; in_ham=6}
|> Map.add "adversity" { in_spam=1; in_ham=2}
|> Map.add "advertise" { in_spam=13; in_ham=6}
|> Map.add "advertised" { in_spam=4; in_ham=6}
|> Map.add "advertisers" { in_spam=10; in_ham=1}
|> Map.add "advertising" { in_spam=33; in_ham=18}
|> Map.add "advice" { in_spam=19; in_ham=11}
|> Map.add "advise" { in_spam=2; in_ham=11}
|> Map.add "advised" { in_spam=8; in_ham=4}
|> Map.add "advisement" { in_spam=5; in_ham=0}
|> Map.add "adviser" { in_spam=4; in_ham=1}
|> Map.add "advises" { in_spam=1; in_ham=2}
|> Map.add "advisor" { in_spam=5; in_ham=1}
|> Map.add "advisors" { in_spam=0; in_ham=8}
|> Map.add "advisory" { in_spam=5; in_ham=4}
|> Map.add "advocacy" { in_spam=0; in_ham=3}
|> Map.add "advocate" { in_spam=4; in_ham=5}
|> Map.add "advocates" { in_spam=0; in_ham=3}
|> Map.add "advocating" { in_spam=1; in_ham=2}
|> Map.add "advogato" { in_spam=0; in_ham=4}
|> Map.add "aerial" { in_spam=0; in_ham=4}
|> Map.add "aeriksson" { in_spam=0; in_ham=15}
|> Map.add "aesthetics" { in_spam=0; in_ham=4}
|> Map.add "afaik" { in_spam=0; in_ham=7}
|> Map.add "affair" { in_spam=0; in_ham=8}
|> Map.add "affairs" { in_spam=2; in_ham=5}
|> Map.add "affect" { in_spam=0; in_ham=7}
|> Map.add "affected" { in_spam=2; in_ham=8}
|> Map.add "affecting" { in_spam=1; in_ham=3}
|> Map.add "affects" { in_spam=0; in_ham=10}
|> Map.add "affero" { in_spam=0; in_ham=6}
|> Map.add "affiliate" { in_spam=25; in_ham=4}
|> Map.add "affiliated" { in_spam=12; in_ham=6}
|> Map.add "affiliates" { in_spam=14; in_ham=1}
|> Map.add "affluent" { in_spam=1; in_ham=3}
|> Map.add "afford" { in_spam=2; in_ham=13}
|> Map.add "affordable" { in_spam=11; in_ham=1}
|> Map.add "afft" { in_spam=10; in_ham=0}
|> Map.add "afghan" { in_spam=0; in_ham=3}
|> Map.add "afghanistan" { in_spam=1; in_ham=11}
|> Map.add "afraid" { in_spam=3; in_ham=22}
|> Map.add "africa" { in_spam=15; in_ham=12}
|> Map.add "african" { in_spam=7; in_ham=7}
|> Map.add "aftcfeed" { in_spam=0; in_ham=3}
|> Map.add "after" { in_spam=61; in_ham=310}
|> Map.add "afterall" { in_spam=0; in_ham=3}
|> Map.add "afternoon" { in_spam=1; in_ham=14}
|> Map.add "afterwards" { in_spam=0; in_ham=9}
|> Map.add "again" { in_spam=58; in_ham=202}
|> Map.add "against" { in_spam=37; in_ham=126}
|> Map.add "age" { in_spam=28; in_ham=33}
|> Map.add "aged" { in_spam=0; in_ham=5}
|> Map.add "ageist" { in_spam=0; in_ham=3}
|> Map.add "agencies" { in_spam=8; in_ham=12}
|> Map.add "agency" { in_spam=5; in_ham=21}
|> Map.add "agenda" { in_spam=2; in_ham=11}
|> Map.add "agendas" { in_spam=1; in_ham=2}
|> Map.add "agent" { in_spam=14; in_ham=36}
|> Map.add "agents" { in_spam=12; in_ham=21}
|> Map.add "ages" { in_spam=4; in_ham=6}
|> Map.add "aggregator" { in_spam=0; in_ham=9}
|> Map.add "aggregators" { in_spam=0; in_ham=3}
|> Map.add "aggression" { in_spam=1; in_ham=2}
|> Map.add "aggressive" { in_spam=1; in_ham=18}
|> Map.add "aggressively" { in_spam=0; in_ham=3}
|> Map.add "agile" { in_spam=0; in_ham=21}
|> Map.add "aging" { in_spam=8; in_ham=1}
|> Map.add "ago" { in_spam=7; in_ham=121}
|> Map.add "agree" { in_spam=4; in_ham=66}
|> Map.add "agreeable" { in_spam=0; in_ham=39}
|> Map.add "agreed" { in_spam=12; in_ham=26}
|> Map.add "agreement" { in_spam=9; in_ham=13}
|> Map.add "agreements" { in_spam=1; in_ham=5}
|> Map.add "agricultural" { in_spam=1; in_ham=4}
|> Map.add "aha" { in_spam=1; in_ham=3}
|> Map.add "ahead" { in_spam=4; in_ham=20}
|> Map.add "ahem" { in_spam=0; in_ham=8}
|> Map.add "aherne" { in_spam=0; in_ham=3}
|> Map.add "ahh" { in_spam=0; in_ham=8}
|> Map.add "ahm" { in_spam=0; in_ham=4}
|> Map.add "ahoo" { in_spam=0; in_ham=3}
|> Map.add "aid" { in_spam=11; in_ham=27}
|> Map.add "aides" { in_spam=1; in_ham=3}
|> Map.add "aiding" { in_spam=0; in_ham=4}
|> Map.add "aids" { in_spam=0; in_ham=13}
|> Map.add "aidsphobic" { in_spam=0; in_ham=6}
|> Map.add "aim" { in_spam=2; in_ham=14}
|> Map.add "aimed" { in_spam=0; in_ham=7}
|> Map.add "aims" { in_spam=0; in_ham=5}
|> Map.add "ain't" { in_spam=3; in_ham=6}
|> Map.add "aint" { in_spam=0; in_ham=4}
|> Map.add "aio" { in_spam=0; in_ham=4}
|> Map.add "air" { in_spam=17; in_ham=34}
|> Map.add "airbus" { in_spam=1; in_ham=3}
|> Map.add "aircraft" { in_spam=2; in_ham=10}
|> Map.add "airflow" { in_spam=0; in_ham=3}
|> Map.add "airline" { in_spam=5; in_ham=7}
|> Map.add "airlines" { in_spam=0; in_ham=4}
|> Map.add "airport" { in_spam=2; in_ham=6}
|> Map.add "airways" { in_spam=1; in_ham=2}
|> Map.add "aisle" { in_spam=0; in_ham=3}
|> Map.add "aix" { in_spam=0; in_ham=4}
|> Map.add "ajatellut" { in_spam=0; in_ham=4}
|> Map.add "ajatuksia" { in_spam=0; in_ham=4}
|> Map.add "aka" { in_spam=1; in_ham=6}
|> Map.add "akam" { in_spam=0; in_ham=6}
|> Map.add "akamai" { in_spam=1; in_ham=9}
|> Map.add "akamai's" { in_spam=0; in_ham=6}
|> Map.add "akd" { in_spam=0; in_ham=4}
|> Map.add "aks" { in_spam=0; in_ham=3}
|> Map.add "alabama" { in_spam=4; in_ham=6}
|> Map.add "alan" { in_spam=0; in_ham=26}
|> Map.add "alarm" { in_spam=1; in_ham=8}
|> Map.add "alas" { in_spam=0; in_ham=3}
|> Map.add "alaska" { in_spam=4; in_ham=4}
|> Map.add "alastair" { in_spam=0; in_ham=4}
|> Map.add "alb" { in_spam=0; in_ham=8}
|> Map.add "albania" { in_spam=2; in_ham=2}
|> Map.add "albeit" { in_spam=0; in_ham=5}
|> Map.add "alberta" { in_spam=8; in_ham=2}
|> Map.add "album" { in_spam=7; in_ham=7}
|> Map.add "albums" { in_spam=4; in_ham=3}
|> Map.add "alcanet" { in_spam=0; in_ham=3}
|> Map.add "alcohol" { in_spam=2; in_ham=3}
|> Map.add "alcoholics" { in_spam=0; in_ham=3}
|> Map.add "alcoholism" { in_spam=0; in_ham=4}
|> Map.add "alert" { in_spam=6; in_ham=4}
|> Map.add "alex" { in_spam=1; in_ham=4}
|> Map.add "algorithm" { in_spam=0; in_ham=14}
|> Map.add "algorithms" { in_spam=4; in_ham=5}
|> Map.add "alias" { in_spam=0; in_ham=6}
|> Map.add "aliens" { in_spam=0; in_ham=3}
|> Map.add "align" { in_spam=172; in_ham=5}
|> Map.add "aligned" { in_spam=0; in_ham=3}
|> Map.add "alike" { in_spam=0; in_ham=7}
|> Map.add "alink" { in_spam=13; in_ham=0}
|> Map.add "alinoe" { in_spam=0; in_ham=5}
|> Map.add "alive" { in_spam=0; in_ham=12}
|> Map.add "all" { in_spam=228; in_ham=870}
|> Map.add "all-courses" { in_spam=0; in_ham=3}
|> Map.add "allegations" { in_spam=1; in_ham=2}
|> Map.add "alleged" { in_spam=1; in_ham=3}
|> Map.add "allegedly" { in_spam=1; in_ham=4}
|> Map.add "allen" { in_spam=0; in_ham=9}
|> Map.add "alleviate" { in_spam=0; in_ham=3}
|> Map.add "alleviated" { in_spam=0; in_ham=3}
|> Map.add "alley" { in_spam=1; in_ham=3}
|> Map.add "alleyways" { in_spam=0; in_ham=3}
|> Map.add "alliance" { in_spam=3; in_ham=12}
|> Map.add "alliances" { in_spam=0; in_ham=3}
|> Map.add "allies" { in_spam=2; in_ham=6}
|> Map.add "allocation" { in_spam=2; in_ham=5}
|> Map.add "allow" { in_spam=50; in_ham=71}
|> Map.add "allowed" { in_spam=4; in_ham=40}
|> Map.add "allowing" { in_spam=2; in_ham=14}
|> Map.add "allows" { in_spam=8; in_ham=42}
|> Map.add "allude" { in_spam=0; in_ham=4}
|> Map.add "almighty" { in_spam=1; in_ham=2}
|> Map.add "almost" { in_spam=19; in_ham=102}
|> Map.add "alone" { in_spam=15; in_ham=27}
|> Map.add "along" { in_spam=21; in_ham=71}
|> Map.add "alongside" { in_spam=0; in_ham=3}
|> Map.add "alot" { in_spam=1; in_ham=6}
|> Map.add "alpha" { in_spam=0; in_ham=3}
|> Map.add "already" { in_spam=28; in_ham=154}
|> Map.add "alsa" { in_spam=0; in_ham=44}
|> Map.add "alsa's" { in_spam=0; in_ham=3}
|> Map.add "alsa-driver" { in_spam=0; in_ham=18}
|> Map.add "alsa-driver-" { in_spam=0; in_ham=4}
|> Map.add "alsa-kernel" { in_spam=0; in_ham=14}
|> Map.add "alsa-lib" { in_spam=0; in_ham=5}
|> Map.add "alsa-libs" { in_spam=0; in_ham=3}
|> Map.add "alsa-utils" { in_spam=0; in_ham=3}
|> Map.add "alsa-xmms" { in_spam=0; in_ham=4}
|> Map.add "alsactl" { in_spam=0; in_ham=6}
|> Map.add "alsamixer" { in_spam=0; in_ham=12}
|> Map.add "alsaplaer" { in_spam=0; in_ham=3}
|> Map.add "alsaplayer" { in_spam=0; in_ham=10}
|> Map.add "alsaplayer-" { in_spam=0; in_ham=3}
|> Map.add "alsasound" { in_spam=0; in_ham=7}
|> Map.add "also" { in_spam=102; in_ham=425}
|> Map.add "alt" { in_spam=61; in_ham=9}
|> Map.add "alter" { in_spam=10; in_ham=9}
|> Map.add "altered" { in_spam=0; in_ham=3}
|> Map.add "alternate" { in_spam=2; in_ham=15}
|> Map.add "alternative" { in_spam=12; in_ham=45}
|> Map.add "alternatives" { in_spam=1; in_ham=10}
|> Map.add "although" { in_spam=13; in_ham=102}
|> Map.add "altitude" { in_spam=0; in_ham=8}
|> Map.add "altogether" { in_spam=0; in_ham=4}
|> Map.add "alum" { in_spam=0; in_ham=3}
|> Map.add "alumni" { in_spam=0; in_ham=10}
|> Map.add "alvie" { in_spam=0; in_ham=6}
|> Map.add "always" { in_spam=33; in_ham=140}
|> Map.add "amateur" { in_spam=5; in_ham=2}
|> Map.add "amavisd" { in_spam=0; in_ham=4}
|> Map.add "amazed" { in_spam=6; in_ham=3}
|> Map.add "amazing" { in_spam=9; in_ham=16}
|> Map.add "amazingly" { in_spam=3; in_ham=8}
|> Map.add "amazon" { in_spam=2; in_ham=12}
|> Map.add "ambiguous" { in_spam=0; in_ham=5}
|> Map.add "ambitious" { in_spam=2; in_ham=9}
|> Map.add "amen" { in_spam=0; in_ham=6}
|> Map.add "amended" { in_spam=3; in_ham=3}
|> Map.add "amendment" { in_spam=0; in_ham=23}
|> Map.add "america" { in_spam=12; in_ham=46}
|> Map.add "america's" { in_spam=2; in_ham=12}
|> Map.add "american" { in_spam=18; in_ham=78}
|> Map.add "americans" { in_spam=3; in_ham=36}
|> Map.add "americas" { in_spam=0; in_ham=3}
|> Map.add "amid" { in_spam=1; in_ham=3}
|> Map.add "among" { in_spam=6; in_ham=39}
|> Map.add "amongst" { in_spam=0; in_ham=14}
|> Map.add "amount" { in_spam=30; in_ham=49}
|> Map.add "amounts" { in_spam=9; in_ham=15}
|> Map.add "amp" { in_spam=48; in_ham=2}
|> Map.add "amphetadesk" { in_spam=0; in_ham=4}
|> Map.add "amun" { in_spam=0; in_ham=3}
|> Map.add "amusing" { in_spam=0; in_ham=14}
|> Map.add "analog" { in_spam=0; in_ham=13}
|> Map.add "analogous" { in_spam=0; in_ham=7}
|> Map.add "analogy" { in_spam=1; in_ham=6}
|> Map.add "analyses" { in_spam=2; in_ham=3}
|> Map.add "analysis" { in_spam=1; in_ham=28}
|> Map.add "analyst" { in_spam=6; in_ham=20}
|> Map.add "analysts" { in_spam=1; in_ham=2}
|> Map.add "analyzing" { in_spam=0; in_ham=7}
|> Map.add "ananova" { in_spam=0; in_ham=7}
|> Map.add "anarchist" { in_spam=0; in_ham=4}
|> Map.add "anathema" { in_spam=0; in_ham=5}
|> Map.add "ancestral" { in_spam=1; in_ham=2}
|> Map.add "anchors" { in_spam=0; in_ham=4}
|> Map.add "ancient" { in_spam=0; in_ham=11}
|> Map.add "and" { in_spam=372; in_ham=1865}
|> Map.add "andean" { in_spam=0; in_ham=3}
|> Map.add "anders" { in_spam=0; in_ham=21}
|> Map.add "anderson" { in_spam=4; in_ham=8}
|> Map.add "andes" { in_spam=0; in_ham=3}
|> Map.add "andrew" { in_spam=0; in_ham=14}
|> Map.add "andrey" { in_spam=0; in_ham=3}
|> Map.add "andy" { in_spam=1; in_ham=3}

