open Database
open BayesianBody_003
let db = db 
|> Map.add "proxy" { in_spam=0; in_ham=14}
|> Map.add "psyche" { in_spam=0; in_ham=13}
|> Map.add "pub" { in_spam=1; in_ham=28}
|> Map.add "public" { in_spam=61; in_ham=106}
|> Map.add "publication" { in_spam=9; in_ham=16}
|> Map.add "publications" { in_spam=4; in_ham=6}
|> Map.add "publish" { in_spam=13; in_ham=11}
|> Map.add "published" { in_spam=8; in_ham=32}
|> Map.add "publisher" { in_spam=6; in_ham=9}
|> Map.add "publishers" { in_spam=1; in_ham=7}
|> Map.add "publishing" { in_spam=7; in_ham=11}
|> Map.add "pudge" { in_spam=0; in_ham=56}
|> Map.add "puglisi" { in_spam=0; in_ham=8}
|> Map.add "pull" { in_spam=2; in_ham=28}
|> Map.add "pulled" { in_spam=0; in_ham=15}
|> Map.add "pulling" { in_spam=4; in_ham=14}
|> Map.add "pump" { in_spam=4; in_ham=7}
|> Map.add "punching" { in_spam=0; in_ham=10}
|> Map.add "purchase" { in_spam=50; in_ham=13}
|> Map.add "purchased" { in_spam=12; in_ham=10}
|> Map.add "pure" { in_spam=1; in_ham=12}
|> Map.add "purely" { in_spam=0; in_ham=8}
|> Map.add "purpose" { in_spam=15; in_ham=35}
|> Map.add "purposes" { in_spam=12; in_ham=11}
|> Map.add "pursue" { in_spam=2; in_ham=10}
|> Map.add "push" { in_spam=1; in_ham=11}
|> Map.add "pushed" { in_spam=0; in_ham=12}
|> Map.add "pushing" { in_spam=1; in_ham=9}
|> Map.add "put" { in_spam=48; in_ham=182}
|> Map.add "puts" { in_spam=0; in_ham=18}
|> Map.add "putting" { in_spam=5; in_ham=34}
|> Map.add "python" { in_spam=0; in_ham=67}
|> Map.add "qmail" { in_spam=0; in_ham=10}
|> Map.add "qualified" { in_spam=15; in_ham=0}
|> Map.add "qualify" { in_spam=16; in_ham=9}
|> Map.add "quality" { in_spam=35; in_ham=42}
|> Map.add "quarter" { in_spam=4; in_ham=12}
|> Map.add "query" { in_spam=3; in_ham=12}
|> Map.add "question" { in_spam=18; in_ham=104}
|> Map.add "questionable" { in_spam=4; in_ham=6}
|> Map.add "questions" { in_spam=38; in_ham=44}
|> Map.add "quick" { in_spam=37; in_ham=38}
|> Map.add "quickly" { in_spam=15; in_ham=49}
|> Map.add "quicktime" { in_spam=0; in_ham=8}
|> Map.add "quicktopic" { in_spam=0; in_ham=111}
|> Map.add "quiet" { in_spam=1; in_ham=10}
|> Map.add "quinlan" { in_spam=0; in_ham=10}
|> Map.add "quit" { in_spam=4; in_ham=6}
|> Map.add "quite" { in_spam=7; in_ham=129}
|> Map.add "quiz" { in_spam=0; in_ham=9}
|> Map.add "quot" { in_spam=19; in_ham=3}
|> Map.add "quote" { in_spam=20; in_ham=23}
|> Map.add "quoted" { in_spam=0; in_ham=20}
|> Map.add "quotes" { in_spam=20; in_ham=27}
|> Map.add "quoting" { in_spam=1; in_ham=15}
|> Map.add "race" { in_spam=1; in_ham=11}
|> Map.add "radio" { in_spam=5; in_ham=52}
|> Map.add "rafael" { in_spam=0; in_ham=17}
|> Map.add "rah" { in_spam=0; in_ham=50}
|> Map.add "raid" { in_spam=0; in_ham=12}
|> Map.add "raise" { in_spam=1; in_ham=17}
|> Map.add "raised" { in_spam=2; in_ham=21}
|> Map.add "raises" { in_spam=0; in_ham=8}
|> Map.add "raising" { in_spam=3; in_ham=6}
|> Map.add "rallies" { in_spam=0; in_ham=8}
|> Map.add "ram" { in_spam=2; in_ham=11}
|> Map.add "ran" { in_spam=1; in_ham=39}
|> Map.add "random" { in_spam=4; in_ham=29}
|> Map.add "randomly" { in_spam=0; in_ham=29}
|> Map.add "range" { in_spam=5; in_ham=31}
|> Map.add "ranking" { in_spam=1; in_ham=8}
|> Map.add "rapid" { in_spam=4; in_ham=14}
|> Map.add "rapidly" { in_spam=8; in_ham=18}
|> Map.add "rare" { in_spam=1; in_ham=23}
|> Map.add "rarely" { in_spam=2; in_ham=8}
|> Map.add "rate" { in_spam=47; in_ham=56}
|> Map.add "rated" { in_spam=15; in_ham=7}
|> Map.add "rates" { in_spam=41; in_ham=41}
|> Map.add "rather" { in_spam=8; in_ham=133}
|> Map.add "ratio" { in_spam=2; in_ham=12}
|> Map.add "raw" { in_spam=3; in_ham=25}
|> Map.add "ray" { in_spam=1; in_ham=10}
|> Map.add "razor" { in_spam=0; in_ham=84}
|> Map.add "razor-agent" { in_spam=0; in_ham=15}
|> Map.add "razor-check" { in_spam=0; in_ham=12}
|> Map.add "razor-users" { in_spam=0; in_ham=78}
|> Map.add "rcs" { in_spam=0; in_ham=16}
|> Map.add "rdf" { in_spam=0; in_ham=13}
|> Map.add "reach" { in_spam=28; in_ham=48}
|> Map.add "reached" { in_spam=10; in_ham=11}
|> Map.add "read" { in_spam=32; in_ham=168}
|> Map.add "reader" { in_spam=1; in_ham=15}
|> Map.add "readers" { in_spam=2; in_ham=10}
|> Map.add "reading" { in_spam=19; in_ham=79}
|> Map.add "readme" { in_spam=0; in_ham=17}
|> Map.add "reads" { in_spam=0; in_ham=13}
|> Map.add "ready" { in_spam=36; in_ham=30}
|> Map.add "real" { in_spam=34; in_ham=154}
|> Map.add "real-time" { in_spam=6; in_ham=64}
|> Map.add "reality" { in_spam=4; in_ham=25}
|> Map.add "realize" { in_spam=7; in_ham=28}
|> Map.add "realized" { in_spam=1; in_ham=8}
|> Map.add "really" { in_spam=23; in_ham=331}
|> Map.add "rear" { in_spam=1; in_ham=9}
|> Map.add "reason" { in_spam=26; in_ham=117}
|> Map.add "reasonable" { in_spam=2; in_ham=21}
|> Map.add "reasonably" { in_spam=0; in_ham=13}
|> Map.add "reasons" { in_spam=13; in_ham=60}
|> Map.add "reboot" { in_spam=0; in_ham=14}
|> Map.add "rebuild" { in_spam=0; in_ham=43}
|> Map.add "rebuilding" { in_spam=0; in_ham=12}
|> Map.add "rebuilt" { in_spam=0; in_ham=13}
|> Map.add "recall" { in_spam=0; in_ham=30}
|> Map.add "receive" { in_spam=183; in_ham=48}
|> Map.add "received" { in_spam=63; in_ham=126}
|> Map.add "receives" { in_spam=7; in_ham=7}
|> Map.add "receiving" { in_spam=69; in_ham=96}
|> Map.add "recent" { in_spam=11; in_ham=81}
|> Map.add "recently" { in_spam=25; in_ham=64}
|> Map.add "recipe" { in_spam=0; in_ham=13}
|> Map.add "recipient" { in_spam=5; in_ham=21}
|> Map.add "recipients" { in_spam=6; in_ham=18}
|> Map.add "reckon" { in_spam=0; in_ham=9}
|> Map.add "recognition" { in_spam=3; in_ham=6}
|> Map.add "recognize" { in_spam=1; in_ham=17}
|> Map.add "recognized" { in_spam=2; in_ham=7}
|> Map.add "recommend" { in_spam=6; in_ham=26}
|> Map.add "recommended" { in_spam=2; in_ham=17}
|> Map.add "recompile" { in_spam=0; in_ham=15}
|> Map.add "recompiling" { in_spam=0; in_ham=8}
|> Map.add "record" { in_spam=10; in_ham=60}
|> Map.add "recorded" { in_spam=2; in_ham=16}
|> Map.add "recording" { in_spam=2; in_ham=8}
|> Map.add "records" { in_spam=3; in_ham=18}
|> Map.add "recover" { in_spam=1; in_ham=8}
|> Map.add "recovery" { in_spam=0; in_ham=9}
|> Map.add "red" { in_spam=25; in_ham=127}
|> Map.add "redhat" { in_spam=0; in_ham=210}
|> Map.add "reduce" { in_spam=3; in_ham=25}
|> Map.add "reduced" { in_spam=2; in_ham=8}
|> Map.add "reducing" { in_spam=1; in_ham=10}
|> Map.add "reduction" { in_spam=8; in_ham=6}
|> Map.add "refcode" { in_spam=2; in_ham=106}
|> Map.add "refer" { in_spam=5; in_ham=6}
|> Map.add "reference" { in_spam=13; in_ham=44}
|> Map.add "references" { in_spam=6; in_ham=7}
|> Map.add "referring" { in_spam=5; in_ham=11}
|> Map.add "reflect" { in_spam=1; in_ham=8}
|> Map.add "reform" { in_spam=5; in_ham=7}
|> Map.add "refund" { in_spam=5; in_ham=6}
|> Map.add "refused" { in_spam=2; in_ham=7}
|> Map.add "reg" { in_spam=6; in_ham=12}
|> Map.add "regard" { in_spam=4; in_ham=16}
|> Map.add "regarding" { in_spam=15; in_ham=9}
|> Map.add "regardless" { in_spam=5; in_ham=15}
|> Map.add "regards" { in_spam=31; in_ham=78}
|> Map.add "regime" { in_spam=4; in_ham=12}
|> Map.add "region" { in_spam=3; in_ham=21}
|> Map.add "regional" { in_spam=1; in_ham=14}
|> Map.add "regions" { in_spam=1; in_ham=10}
|> Map.add "register" { in_spam=13; in_ham=16}
|> Map.add "registered" { in_spam=40; in_ham=12}
|> Map.add "registering" { in_spam=2; in_ham=7}
|> Map.add "registration" { in_spam=9; in_ham=6}
|> Map.add "registry" { in_spam=0; in_ham=9}
|> Map.add "regular" { in_spam=14; in_ham=31}
|> Map.add "regularly" { in_spam=2; in_ham=12}
|> Map.add "regulated" { in_spam=1; in_ham=7}
|> Map.add "regulation" { in_spam=0; in_ham=19}
|> Map.add "regulations" { in_spam=6; in_ham=14}
|> Map.add "regulatory" { in_spam=2; in_ham=11}
|> Map.add "reinstall" { in_spam=0; in_ham=13}
|> Map.add "reject" { in_spam=0; in_ham=12}
|> Map.add "rejected" { in_spam=2; in_ham=13}
|> Map.add "related" { in_spam=14; in_ham=40}
|> Map.add "relationship" { in_spam=7; in_ham=27}
|> Map.add "relative" { in_spam=4; in_ham=18}
|> Map.add "relatively" { in_spam=6; in_ham=21}
|> Map.add "relaxed" { in_spam=0; in_ham=9}
|> Map.add "relay" { in_spam=1; in_ham=9}
|> Map.add "release" { in_spam=10; in_ham=128}
|> Map.add "released" { in_spam=3; in_ham=46}
|> Map.add "releases" { in_spam=3; in_ham=37}
|> Map.add "relevant" { in_spam=12; in_ham=29}
|> Map.add "reliable" { in_spam=8; in_ham=13}
|> Map.add "relief" { in_spam=1; in_ham=9}
|> Map.add "religion" { in_spam=2; in_ham=18}
|> Map.add "religions" { in_spam=0; in_ham=8}
|> Map.add "religious" { in_spam=1; in_ham=24}
|> Map.add "rely" { in_spam=5; in_ham=18}
|> Map.add "remain" { in_spam=9; in_ham=31}
|> Map.add "remaining" { in_spam=2; in_ham=11}
|> Map.add "remains" { in_spam=8; in_ham=33}
|> Map.add "remember" { in_spam=19; in_ham=76}
|> Map.add "remembrance" { in_spam=1; in_ham=9}
|> Map.add "remote" { in_spam=9; in_ham=27}
|> Map.add "removal" { in_spam=58; in_ham=4}
|> Map.add "remove" { in_spam=168; in_ham=72}
|> Map.add "removed" { in_spam=162; in_ham=69}
|> Map.add "removing" { in_spam=3; in_ham=17}
|> Map.add "render" { in_spam=1; in_ham=8}
|> Map.add "rent" { in_spam=4; in_ham=8}
|> Map.add "repair" { in_spam=17; in_ham=6}
|> Map.add "repeat" { in_spam=4; in_ham=6}
|> Map.add "repeatedly" { in_spam=1; in_ham=9}
|> Map.add "replace" { in_spam=4; in_ham=26}
|> Map.add "replaced" { in_spam=1; in_ham=13}
|> Map.add "replacement" { in_spam=4; in_ham=11}
|> Map.add "replied" { in_spam=0; in_ham=12}
|> Map.add "reply" { in_spam=128; in_ham=19}
|> Map.add "reply-to" { in_spam=1; in_ham=9}
|> Map.add "replying" { in_spam=6; in_ham=8}
|> Map.add "report" { in_spam=35; in_ham=62}
|> Map.add "reported" { in_spam=7; in_ham=48}
|> Map.add "reporter" { in_spam=1; in_ham=8}
|> Map.add "reporting" { in_spam=3; in_ham=22}
|> Map.add "reports" { in_spam=14; in_ham=44}
|> Map.add "repository" { in_spam=0; in_ham=36}
|> Map.add "represent" { in_spam=7; in_ham=9}
|> Map.add "reproduce" { in_spam=0; in_ham=15}
|> Map.add "republic" { in_spam=16; in_ham=12}
|> Map.add "republican" { in_spam=0; in_ham=23}
|> Map.add "reputation" { in_spam=2; in_ham=11}
|> Map.add "request" { in_spam=43; in_ham=16}
|> Map.add "requested" { in_spam=7; in_ham=5}
|> Map.add "requesting" { in_spam=21; in_ham=1}
|> Map.add "requests" { in_spam=23; in_ham=15}
|> Map.add "require" { in_spam=13; in_ham=52}
|> Map.add "required" { in_spam=68; in_ham=42}
|> Map.add "requirement" { in_spam=6; in_ham=16}
|> Map.add "requirements" { in_spam=14; in_ham=18}
|> Map.add "requires" { in_spam=11; in_ham=59}
|> Map.add "requiring" { in_spam=0; in_ham=16}
|> Map.add "rescue" { in_spam=0; in_ham=8}
|> Map.add "research" { in_spam=19; in_ham=63}
|> Map.add "researchers" { in_spam=0; in_ham=16}
|> Map.add "reserve" { in_spam=5; in_ham=7}
|> Map.add "reserved" { in_spam=13; in_ham=64}
|> Map.add "reservoir" { in_spam=0; in_ham=11}
|> Map.add "reset" { in_spam=3; in_ham=10}
|> Map.add "residents" { in_spam=14; in_ham=11}
|> Map.add "resolution" { in_spam=2; in_ham=16}
|> Map.add "resolve" { in_spam=1; in_ham=17}
|> Map.add "resolved" { in_spam=7; in_ham=15}
|> Map.add "resource" { in_spam=4; in_ham=11}
|> Map.add "resources" { in_spam=11; in_ham=18}
|> Map.add "respect" { in_spam=18; in_ham=70}
|> Map.add "respecting" { in_spam=1; in_ham=8}
|> Map.add "respond" { in_spam=11; in_ham=15}
|> Map.add "responded" { in_spam=8; in_ham=10}
|> Map.add "responding" { in_spam=1; in_ham=8}
|> Map.add "response" { in_spam=59; in_ham=33}
|> Map.add "responses" { in_spam=9; in_ham=8}
|> Map.add "responsible" { in_spam=5; in_ham=15}
|> Map.add "rest" { in_spam=15; in_ham=66}
|> Map.add "restaurant" { in_spam=3; in_ham=7}
|> Map.add "restaurants" { in_spam=2; in_ham=10}
|> Map.add "restore" { in_spam=1; in_ham=9}
|> Map.add "restored" { in_spam=0; in_ham=9}
|> Map.add "restrictions" { in_spam=6; in_ham=14}
|> Map.add "result" { in_spam=14; in_ham=50}
|> Map.add "resulted" { in_spam=5; in_ham=10}
|> Map.add "resulting" { in_spam=2; in_ham=30}
|> Map.add "results" { in_spam=22; in_ham=79}
|> Map.add "resume" { in_spam=2; in_ham=11}
|> Map.add "retail" { in_spam=35; in_ham=7}
|> Map.add "retain" { in_spam=3; in_ham=9}
|> Map.add "retained" { in_spam=3; in_ham=6}
|> Map.add "retrieving" { in_spam=1; in_ham=15}
|> Map.add "return" { in_spam=26; in_ham=54}
|> Map.add "returned" { in_spam=8; in_ham=28}
|> Map.add "returning" { in_spam=0; in_ham=12}
|> Map.add "returns" { in_spam=7; in_ham=8}
|> Map.add "reuters" { in_spam=0; in_ham=20}
|> Map.add "reveal" { in_spam=4; in_ham=13}
|> Map.add "revealed" { in_spam=10; in_ham=15}
|> Map.add "revenue" { in_spam=6; in_ham=13}
|> Map.add "revenues" { in_spam=9; in_ham=9}
|> Map.add "reverse" { in_spam=4; in_ham=18}
|> Map.add "review" { in_spam=7; in_ham=41}
|> Map.add "reviews" { in_spam=1; in_ham=8}
|> Map.add "revision" { in_spam=1; in_ham=16}
|> Map.add "revolution" { in_spam=0; in_ham=9}
|> Map.add "reward" { in_spam=11; in_ham=3}
|> Map.add "rewrite" { in_spam=0; in_ham=10}
|> Map.add "reza" { in_spam=2; in_ham=12}
|> Map.add "rfc" { in_spam=1; in_ham=12}
|> Map.add "riaa" { in_spam=0; in_ham=9}
|> Map.add "rich" { in_spam=9; in_ham=14}
|> Map.add "richard" { in_spam=1; in_ham=10}
|> Map.add "rick" { in_spam=0; in_ham=23}
|> Map.add "rid" { in_spam=1; in_ham=11}
|> Map.add "ride" { in_spam=4; in_ham=11}
|> Map.add "right" { in_spam=116; in_ham=264}
|> Map.add "rights" { in_spam=21; in_ham=118}
|> Map.add "ring" { in_spam=5; in_ham=5}
|> Map.add "ripped" { in_spam=6; in_ham=5}
|> Map.add "rise" { in_spam=2; in_ham=14}
|> Map.add "risk" { in_spam=51; in_ham=23}
|> Map.add "risks" { in_spam=5; in_ham=8}
|> Map.add "rival" { in_spam=0; in_ham=10}
|> Map.add "rivals" { in_spam=0; in_ham=10}
|> Map.add "road" { in_spam=15; in_ham=30}
|> Map.add "rob" { in_spam=4; in_ham=24}
|> Map.add "robert" { in_spam=7; in_ham=72}
|> Map.add "robin" { in_spam=0; in_ham=18}
|> Map.add "robot" { in_spam=2; in_ham=7}
|> Map.add "rock" { in_spam=3; in_ham=23}
|> Map.add "rocket" { in_spam=4; in_ham=6}
|> Map.add "rocks" { in_spam=1; in_ham=25}
|> Map.add "rogers" { in_spam=0; in_ham=31}
|> Map.add "rohit" { in_spam=0; in_ham=33}
|> Map.add "roi" { in_spam=0; in_ham=18}
|> Map.add "role" { in_spam=2; in_ham=21}
|> Map.add "role'" { in_spam=0; in_ham=8}
|> Map.add "roles" { in_spam=0; in_ham=11}
|> Map.add "roll" { in_spam=9; in_ham=9}
|> Map.add "rolling" { in_spam=10; in_ham=6}
|> Map.add "roman" { in_spam=39; in_ham=50}
|> Map.add "romantic" { in_spam=0; in_ham=8}
|> Map.add "room" { in_spam=3; in_ham=38}
|> Map.add "rooms" { in_spam=7; in_ham=6}
|> Map.add "root" { in_spam=2; in_ham=83}
|> Map.add "roots" { in_spam=1; in_ham=11}
|> Map.add "rose" { in_spam=1; in_ham=20}
|> Map.add "ross" { in_spam=0; in_ham=8}
|> Map.add "rossum" { in_spam=0; in_ham=26}
|> Map.add "roughly" { in_spam=1; in_ham=15}
|> Map.add "round" { in_spam=2; in_ham=20}
|> Map.add "route" { in_spam=1; in_ham=7}
|> Map.add "router" { in_spam=0; in_ham=14}
|> Map.add "routers" { in_spam=0; in_ham=8}
|> Map.add "routine" { in_spam=6; in_ham=17}
|> Map.add "routing" { in_spam=0; in_ham=14}
|> Map.add "row" { in_spam=5; in_ham=5}
|> Map.add "rowspan" { in_spam=44; in_ham=1}
|> Map.add "rpm" { in_spam=0; in_ham=145}
|> Map.add "rpm-list" { in_spam=0; in_ham=251}
|> Map.add "rpmbuild" { in_spam=0; in_ham=20}
|> Map.add "rpmforge" { in_spam=0; in_ham=13}
|> Map.add "rpms" { in_spam=0; in_ham=63}
|> Map.add "rss" { in_spam=0; in_ham=23}
|> Map.add "rude" { in_spam=0; in_ham=12}
|> Map.add "rug" { in_spam=0; in_ham=12}
|> Map.add "rule" { in_spam=0; in_ham=49}
|> Map.add "ruled" { in_spam=1; in_ham=12}
|> Map.add "rules" { in_spam=6; in_ham=69}
|> Map.add "ruling" { in_spam=2; in_ham=11}
|> Map.add "run" { in_spam=30; in_ham=221}
|> Map.add "running" { in_spam=4; in_ham=205}
|> Map.add "runs" { in_spam=2; in_ham=63}
|> Map.add "runtime" { in_spam=0; in_ham=8}
|> Map.add "rush" { in_spam=5; in_ham=6}
|> Map.add "russell" { in_spam=1; in_ham=23}
|> Map.add "russia" { in_spam=2; in_ham=8}
|> Map.add "russian" { in_spam=1; in_ham=8}
|> Map.add "sad" { in_spam=2; in_ham=12}
|> Map.add "safe" { in_spam=8; in_ham=32}
|> Map.add "safely" { in_spam=18; in_ham=5}
|> Map.add "safety" { in_spam=10; in_ham=13}
|> Map.add "said" { in_spam=28; in_ham=313}
|> Map.add "sake" { in_spam=3; in_ham=12}
|> Map.add "sale" { in_spam=20; in_ham=15}
|> Map.add "sales" { in_spam=43; in_ham=24}
|> Map.add "same" { in_spam=43; in_ham=381}
|> Map.add "sample" { in_spam=5; in_ham=18}
|> Map.add "samples" { in_spam=5; in_ham=6}
|> Map.add "san" { in_spam=7; in_ham=26}
|> Map.add "sane" { in_spam=0; in_ham=8}
|> Map.add "sans" { in_spam=10; in_ham=3}
|> Map.add "sans-serif" { in_spam=82; in_ham=0}
|> Map.add "santa" { in_spam=2; in_ham=10}
|> Map.add "saou" { in_spam=0; in_ham=106}
|> Map.add "sarvega" { in_spam=0; in_ham=8}
|> Map.add "sat" { in_spam=3; in_ham=37}
|> Map.add "satalk" { in_spam=0; in_ham=9}
|> Map.add "satellite" { in_spam=2; in_ham=14}
|> Map.add "satisfaction" { in_spam=14; in_ham=7}
|> Map.add "satisfied" { in_spam=9; in_ham=5}
|> Map.add "saturday" { in_spam=1; in_ham=27}
|> Map.add "saudi" { in_spam=2; in_ham=7}
|> Map.add "save" { in_spam=61; in_ham=56}
|> Map.add "saved" { in_spam=7; in_ham=25}
|> Map.add "saving" { in_spam=7; in_ham=10}
|> Map.add "savings" { in_spam=18; in_ham=5}
|> Map.add "saw" { in_spam=4; in_ham=45}
|> Map.add "say" { in_spam=25; in_ham=241}
|> Map.add "saying" { in_spam=5; in_ham=71}
|> Map.add "says" { in_spam=9; in_ham=121}
|> Map.add "scalable" { in_spam=0; in_ham=25}
|> Map.add "scale" { in_spam=0; in_ham=25}
|> Map.add "scam" { in_spam=3; in_ham=10}
|> Map.add "scan" { in_spam=0; in_ham=22}
|> Map.add "scanned" { in_spam=1; in_ham=8}
|> Map.add "scanning" { in_spam=0; in_ham=11}
|> Map.add "scarce" { in_spam=0; in_ham=9}
|> Map.add "scary" { in_spam=0; in_ham=11}
|> Map.add "scenario" { in_spam=0; in_ham=12}
|> Map.add "scene" { in_spam=1; in_ham=10}
|> Map.add "scheduled" { in_spam=0; in_ham=10}
|> Map.add "scheme" { in_spam=3; in_ham=25}
|> Map.add "school" { in_spam=12; in_ham=58}
|> Map.add "schools" { in_spam=4; in_ham=9}
|> Map.add "schuman" { in_spam=0; in_ham=35}
|> Map.add "schwartz" { in_spam=0; in_ham=11}
|> Map.add "science" { in_spam=8; in_ham=35}
|> Map.add "sciences" { in_spam=0; in_ham=11}
|> Map.add "scientiam" { in_spam=0; in_ham=9}
|> Map.add "scientific" { in_spam=1; in_ham=13}
|> Map.add "scientist" { in_spam=0; in_ham=12}
|> Map.add "scientists" { in_spam=0; in_ham=26}
|> Map.add "scope" { in_spam=0; in_ham=14}
|> Map.add "score" { in_spam=0; in_ham=49}
|> Map.add "scored" { in_spam=0; in_ham=8}
|> Map.add "scores" { in_spam=0; in_ham=36}
|> Map.add "scoring" { in_spam=0; in_ham=9}
|> Map.add "scott" { in_spam=0; in_ham=29}
|> Map.add "scratch" { in_spam=0; in_ham=13}
|> Map.add "screaming" { in_spam=0; in_ham=9}
|> Map.add "screen" { in_spam=3; in_ham=37}
|> Map.add "script" { in_spam=9; in_ham=69}
|> Map.add "scripting" { in_spam=0; in_ham=8}
|> Map.add "scripts" { in_spam=1; in_ham=30}
|> Map.add "scrutiny" { in_spam=1; in_ham=14}
|> Map.add "sdl" { in_spam=0; in_ham=9}
|> Map.add "sdw" { in_spam=0; in_ham=12}
|> Map.add "sea" { in_spam=4; in_ham=13}
|> Map.add "search" { in_spam=34; in_ham=63}
|> Map.add "searching" { in_spam=7; in_ham=17}
|> Map.add "season" { in_spam=2; in_ham=7}
|> Map.add "seat" { in_spam=1; in_ham=8}
|> Map.add "seattle" { in_spam=4; in_ham=17}
|> Map.add "sec" { in_spam=0; in_ham=17}
|> Map.add "second" { in_spam=31; in_ham=110}
|> Map.add "secondary" { in_spam=3; in_ham=17}
|> Map.add "seconds" { in_spam=8; in_ham=34}
|> Map.add "secrecy" { in_spam=8; in_ham=4}
|> Map.add "secret" { in_spam=24; in_ham=28}
|> Map.add "secretary" { in_spam=2; in_ham=12}
|> Map.add "secrets" { in_spam=13; in_ham=4}
|> Map.add "section" { in_spam=23; in_ham=41}
|> Map.add "sections" { in_spam=2; in_ham=11}
|> Map.add "sector" { in_spam=2; in_ham=11}
|> Map.add "secure" { in_spam=34; in_ham=39}
|> Map.add "secured" { in_spam=0; in_ham=8}
|> Map.add "security" { in_spam=41; in_ham=67}
|> Map.add "sed" { in_spam=0; in_ham=14}
|> Map.add "sedit" { in_spam=0; in_ham=11}
|> Map.add "see" { in_spam=76; in_ham=391}
|> Map.add "seed" { in_spam=1; in_ham=9}
|> Map.add "seeing" { in_spam=2; in_ham=50}
|> Map.add "seek" { in_spam=14; in_ham=16}
|> Map.add "seeking" { in_spam=6; in_ham=9}
|> Map.add "seeks" { in_spam=1; in_ham=20}
|> Map.add "seem" { in_spam=10; in_ham=137}
|> Map.add "seemed" { in_spam=2; in_ham=23}
|> Map.add "seemingly" { in_spam=0; in_ham=8}
|> Map.add "seems" { in_spam=6; in_ham=212}
|> Map.add "seen" { in_spam=31; in_ham=134}
|> Map.add "sees" { in_spam=2; in_ham=9}
|> Map.add "seized" { in_spam=4; in_ham=6}
|> Map.add "sel" { in_spam=0; in_ham=9}
|> Map.add "seldom" { in_spam=0; in_ham=8}
|> Map.add "select" { in_spam=17; in_ham=31}
|> Map.add "selected" { in_spam=16; in_ham=22}
|> Map.add "selection" { in_spam=13; in_ham=20}
|> Map.add "self" { in_spam=20; in_ham=17}
|> Map.add "sell" { in_spam=35; in_ham=58}
|> Map.add "selling" { in_spam=14; in_ham=48}
|> Map.add "sells" { in_spam=7; in_ham=6}
|> Map.add "seminar" { in_spam=5; in_ham=5}
|> Map.add "send" { in_spam=110; in_ham=188}
|> Map.add "sender" { in_spam=6; in_ham=41}
|> Map.add "senders" { in_spam=0; in_ham=12}
|> Map.add "sending" { in_spam=46; in_ham=44}
|> Map.add "sendmail" { in_spam=0; in_ham=23}
|> Map.add "sends" { in_spam=1; in_ham=9}
|> Map.add "senior" { in_spam=9; in_ham=23}
|> Map.add "sense" { in_spam=9; in_ham=62}
|> Map.add "sent" { in_spam=128; in_ham=211}
|> Map.add "sentence" { in_spam=0; in_ham=10}
|> Map.add "sentto'" { in_spam=28; in_ham=0}
|> Map.add "sep" { in_spam=5; in_ham=331}
|> Map.add "separate" { in_spam=2; in_ham=35}
|> Map.add "separately" { in_spam=5; in_ham=7}
|> Map.add "sept" { in_spam=4; in_ham=17}
|> Map.add "september" { in_spam=10; in_ham=184}
|> Map.add "seq" { in_spam=0; in_ham=17}
|> Map.add "sequence" { in_spam=7; in_ham=36}
|> Map.add "sequences" { in_spam=0; in_ham=43}
|> Map.add "serial" { in_spam=10; in_ham=13}
|> Map.add "series" { in_spam=3; in_ham=34}
|> Map.add "serif" { in_spam=15; in_ham=0}
|> Map.add "serious" { in_spam=16; in_ham=38}
|> Map.add "seriously" { in_spam=11; in_ham=26}
|> Map.add "served" { in_spam=2; in_ham=11}
|> Map.add "server" { in_spam=28; in_ham=155}
|> Map.add "servers" { in_spam=1; in_ham=56}
|> Map.add "serves" { in_spam=1; in_ham=7}
|> Map.add "service" { in_spam=100; in_ham=112}
|> Map.add "services" { in_spam=76; in_ham=80}
|> Map.add "servlet" { in_spam=0; in_ham=9}
|> Map.add "session" { in_spam=1; in_ham=12}
|> Map.add "set" { in_spam=16; in_ham=236}
|> Map.add "sets" { in_spam=1; in_ham=37}
|> Map.add "setting" { in_spam=1; in_ham=31}
|> Map.add "settings" { in_spam=0; in_ham=16}
|> Map.add "settle" { in_spam=6; in_ham=6}
|> Map.add "settled" { in_spam=3; in_ham=9}
|> Map.add "settlement" { in_spam=5; in_ham=16}
|> Map.add "setup" { in_spam=6; in_ham=41}
|> Map.add "seven" { in_spam=10; in_ham=25}
|> Map.add "seventh" { in_spam=3; in_ham=9}
|> Map.add "several" { in_spam=20; in_ham=100}
|> Map.add "severe" { in_spam=5; in_ham=6}
|> Map.add "sex" { in_spam=12; in_ham=45}
|> Map.add "sexual" { in_spam=5; in_ham=15}
|> Map.add "sexy" { in_spam=8; in_ham=5}
|> Map.add "sez" { in_spam=0; in_ham=9}
|> Map.add "sha" { in_spam=0; in_ham=23}
|> Map.add "shafer" { in_spam=0; in_ham=8}
|> Map.add "shall" { in_spam=16; in_ham=8}
|> Map.add "shape" { in_spam=21; in_ham=25}
|> Map.add "share" { in_spam=30; in_ham=61}
|> Map.add "shared" { in_spam=7; in_ham=33}
|> Map.add "shares" { in_spam=9; in_ham=12}
|> Map.add "sharing" { in_spam=7; in_ham=16}
|> Map.add "she" { in_spam=11; in_ham=93}
|> Map.add "sheep" { in_spam=0; in_ham=9}
|> Map.add "shell" { in_spam=1; in_ham=20}
|> Map.add "shift" { in_spam=0; in_ham=12}
|> Map.add "ship" { in_spam=3; in_ham=20}
|> Map.add "shipped" { in_spam=7; in_ham=9}
|> Map.add "shipping" { in_spam=45; in_ham=8}
|> Map.add "shipwright" { in_spam=0; in_ham=19}
|> Map.add "shit" { in_spam=0; in_ham=16}
|> Map.add "shock" { in_spam=3; in_ham=11}
|> Map.add "shocked" { in_spam=8; in_ham=6}
|> Map.add "shoot" { in_spam=0; in_ham=13}
|> Map.add "shooting" { in_spam=0; in_ham=11}
|> Map.add "shop" { in_spam=22; in_ham=14}
|> Map.add "shopping" { in_spam=9; in_ham=4}
|> Map.add "shore" { in_spam=0; in_ham=9}
|> Map.add "short" { in_spam=18; in_ham=55}
|> Map.add "shot" { in_spam=2; in_ham=19}
|> Map.add "should" { in_spam=80; in_ham=384}
|> Map.add "shoulders" { in_spam=0; in_ham=8}
|> Map.add "shouldn't" { in_spam=0; in_ham=35}
|> Map.add "shout" { in_spam=0; in_ham=14}
|> Map.add "shouting" { in_spam=0; in_ham=13}
|> Map.add "show" { in_spam=33; in_ham=122}
|> Map.add "showed" { in_spam=1; in_ham=17}
|> Map.add "showing" { in_spam=1; in_ham=34}
|> Map.add "shown" { in_spam=12; in_ham=9}
|> Map.add "shows" { in_spam=12; in_ham=38}
|> Map.add "shtml" { in_spam=0; in_ham=29}
|> Map.add "shut" { in_spam=1; in_ham=16}
|> Map.add "sick" { in_spam=2; in_ham=10}
|> Map.add "sid" { in_spam=3; in_ham=67}
|> Map.add "side" { in_spam=8; in_ham=52}
|> Map.add "sides" { in_spam=0; in_ham=12}
|> Map.add "sig" { in_spam=0; in_ham=13}
|> Map.add "sigh" { in_spam=0; in_ham=21}
|> Map.add "sight" { in_spam=0; in_ham=8}
|> Map.add "sign" { in_spam=19; in_ham=27}
|> Map.add "signal" { in_spam=3; in_ham=21}
|> Map.add "signals" { in_spam=0; in_ham=8}
|> Map.add "signature" { in_spam=6; in_ham=35}
|> Map.add "signatures" { in_spam=2; in_ham=26}
|> Map.add "signed" { in_spam=18; in_ham=40}
|> Map.add "significant" { in_spam=3; in_ham=40}
|> Map.add "signing" { in_spam=2; in_ham=16}
|> Map.add "signs" { in_spam=0; in_ham=17}
|> Map.add "signup" { in_spam=10; in_ham=3}
|> Map.add "sigs" { in_spam=0; in_ham=9}
|> Map.add "silly" { in_spam=0; in_ham=24}
|> Map.add "similar" { in_spam=15; in_ham=108}
|> Map.add "similarity" { in_spam=0; in_ham=8}
|> Map.add "similarly" { in_spam=1; in_ham=12}
|> Map.add "simple" { in_spam=60; in_ham=76}
|> Map.add "simpler" { in_spam=2; in_ham=11}
|> Map.add "simply" { in_spam=64; in_ham=79}
|> Map.add "simpson" { in_spam=6; in_ham=6}
|> Map.add "since" { in_spam=39; in_ham=272}
|> Map.add "sincerely" { in_spam=35; in_ham=3}
|> Map.add "singapore" { in_spam=2; in_ham=7}
|> Map.add "single" { in_spam=8; in_ham=103}
|> Map.add "sir" { in_spam=31; in_ham=3}
|> Map.add "sister" { in_spam=7; in_ham=9}
|> Map.add "sit" { in_spam=2; in_ham=19}
|> Map.add "sitaker" { in_spam=0; in_ham=10}
|> Map.add "site" { in_spam=60; in_ham=128}
|> Map.add "sites" { in_spam=56; in_ham=39}
|> Map.add "sitting" { in_spam=3; in_ham=27}
|> Map.add "situation" { in_spam=16; in_ham=38}
|> Map.add "situations" { in_spam=2; in_ham=12}
|> Map.add "six" { in_spam=33; in_ham=41}
|> Map.add "size" { in_spam=207; in_ham=77}
|> Map.add "sizes" { in_spam=4; in_ham=16}
|> Map.add "skeptical" { in_spam=6; in_ham=10}
|> Map.add "skills" { in_spam=13; in_ham=9}
|> Map.add "skip" { in_spam=1; in_ham=43}
|> Map.add "skipped" { in_spam=0; in_ham=25}
|> Map.add "sky" { in_spam=0; in_ham=9}
|> Map.add "skytt" { in_spam=0; in_ham=15}
|> Map.add "skytta" { in_spam=0; in_ham=15}
|> Map.add "slashdot" { in_spam=0; in_ham=20}
|> Map.add "slavery" { in_spam=1; in_ham=7}
|> Map.add "slight" { in_spam=0; in_ham=13}
|> Map.add "slightly" { in_spam=1; in_ham=30}
|> Map.add "slim" { in_spam=13; in_ham=7}
|> Map.add "slip" { in_spam=3; in_ham=6}
|> Map.add "slow" { in_spam=5; in_ham=48}
|> Map.add "slower" { in_spam=0; in_ham=17}
|> Map.add "slowly" { in_spam=2; in_ham=11}
|> Map.add "small" { in_spam=30; in_ham=105}
|> Map.add "smaller" { in_spam=1; in_ham=23}
|> Map.add "smart" { in_spam=1; in_ham=20}
|> Map.add "smarter" { in_spam=0; in_ham=8}
|> Map.add "smell" { in_spam=5; in_ham=5}
|> Map.add "smile" { in_spam=1; in_ham=8}
|> Map.add "smith" { in_spam=2; in_ham=14}
|> Map.add "smoke" { in_spam=3; in_ham=6}
|> Map.add "smoking" { in_spam=4; in_ham=6}
|> Map.add "smooth" { in_spam=4; in_ham=6}
|> Map.add "smp" { in_spam=0; in_ham=11}
|> Map.add "smtp" { in_spam=0; in_ham=17}
|> Map.add "snip" { in_spam=0; in_ham=18}
|> Map.add "snna" { in_spam=0; in_ham=13}
|> Map.add "so-called" { in_spam=7; in_ham=7}
|> Map.add "soap" { in_spam=0; in_ham=11}
|> Map.add "social" { in_spam=16; in_ham=44}
|> Map.add "socialism" { in_spam=0; in_ham=11}
|> Map.add "societies" { in_spam=0; in_ham=17}
|> Map.add "society" { in_spam=6; in_ham=44}
|> Map.add "socket" { in_spam=0; in_ham=11}
|> Map.add "software" { in_spam=63; in_ham=186}
|> Map.add "solaris" { in_spam=0; in_ham=25}
|> Map.add "sold" { in_spam=23; in_ham=21}
|> Map.add "sole" { in_spam=8; in_ham=8}
|> Map.add "solely" { in_spam=8; in_ham=7}
|> Map.add "solid" { in_spam=10; in_ham=10}
|> Map.add "solution" { in_spam=5; in_ham=62}
|> Map.add "solutions" { in_spam=12; in_ham=33}
|> Map.add "solve" { in_spam=8; in_ham=27}
|> Map.add "solved" { in_spam=0; in_ham=12}
|> Map.add "solving" { in_spam=1; in_ham=15}
|> Map.add "some" { in_spam=61; in_ham=640}
|> Map.add "somebody" { in_spam=2; in_ham=28}
|> Map.add "somehow" { in_spam=9; in_ham=33}
|> Map.add "someone" { in_spam=21; in_ham=191}
|> Map.add "someone's" { in_spam=1; in_ham=11}
|> Map.add "something" { in_spam=20; in_ham=324}
|> Map.add "sometime" { in_spam=1; in_ham=8}
|> Map.add "sometimes" { in_spam=6; in_ham=47}
|> Map.add "somewhat" { in_spam=0; in_ham=20}
|> Map.add "somewhere" { in_spam=1; in_ham=55}
|> Map.add "son" { in_spam=18; in_ham=9}
|> Map.add "song" { in_spam=1; in_ham=7}
|> Map.add "soon" { in_spam=26; in_ham=76}
|> Map.add "sooner" { in_spam=0; in_ham=11}
|> Map.add "sorry" { in_spam=8; in_ham=55}
|> Map.add "sort" { in_spam=2; in_ham=83}
|> Map.add "sorting" { in_spam=2; in_ham=11}
|> Map.add "sortm" { in_spam=0; in_ham=9}
|> Map.add "sorts" { in_spam=2; in_ham=25}
|> Map.add "soul" { in_spam=2; in_ham=10}
|> Map.add "sound" { in_spam=6; in_ham=54}
|> Map.add "sounding" { in_spam=0; in_ham=12}
|> Map.add "sounds" { in_spam=5; in_ham=48}
|> Map.add "source" { in_spam=12; in_ham=124}
|> Map.add "sourceforge" { in_spam=5; in_ham=275}
|> Map.add "sources" { in_spam=7; in_ham=41}
|> Map.add "south" { in_spam=12; in_ham=30}
|> Map.add "southern" { in_spam=5; in_ham=13}
|> Map.add "space" { in_spam=14; in_ham=60}
|> Map.add "spaces" { in_spam=3; in_ham=11}
|> Map.add "spain" { in_spam=15; in_ham=45}
|> Map.add "spam" { in_spam=31; in_ham=211}
|> Map.add "spamassassin" { in_spam=0; in_ham=153}
|> Map.add "spambayes" { in_spam=0; in_ham=24}
|> Map.add "spamc" { in_spam=0; in_ham=25}
|> Map.add "spamd" { in_spam=0; in_ham=43}
|> Map.add "spammer" { in_spam=0; in_ham=26}
|> Map.add "spammers" { in_spam=0; in_ham=34}
|> Map.add "spamprob" { in_spam=0; in_ham=10}
|> Map.add "spams" { in_spam=0; in_ham=19}
|> Map.add "span" { in_spam=30; in_ham=13}
|> Map.add "spare" { in_spam=1; in_ham=12}
|> Map.add "speak" { in_spam=4; in_ham=34}
|> Map.add "speakers" { in_spam=1; in_ham=20}
|> Map.add "speaking" { in_spam=1; in_ham=41}
|> Map.add "speaks" { in_spam=0; in_ham=8}
|> Map.add "spec" { in_spam=1; in_ham=62}
|> Map.add "special" { in_spam=84; in_ham=57}
|> Map.add "specializes" { in_spam=0; in_ham=9}
|> Map.add "species" { in_spam=0; in_ham=10}
|> Map.add "specific" { in_spam=19; in_ham=58}
|> Map.add "specifically" { in_spam=11; in_ham=42}
|> Map.add "specified" { in_spam=2; in_ham=15}
|> Map.add "specify" { in_spam=0; in_ham=15}
|> Map.add "speech" { in_spam=0; in_ham=40}
|> Map.add "speed" { in_spam=8; in_ham=39}
|> Map.add "speeds" { in_spam=2; in_ham=13}
|> Map.add "spell" { in_spam=2; in_ham=7}
|> Map.add "spend" { in_spam=9; in_ham=36}
|> Map.add "spending" { in_spam=8; in_ham=22}
|> Map.add "spent" { in_spam=4; in_ham=45}
|> Map.add "spin" { in_spam=0; in_ham=10}
|> Map.add "spirit" { in_spam=3; in_ham=9}
|> Map.add "split" { in_spam=3; in_ham=25}
|> Map.add "spoke" { in_spam=0; in_ham=16}
|> Map.add "spokesman" { in_spam=0; in_ham=16}
|> Map.add "sponsor" { in_spam=4; in_ham=96}
|> Map.add "sponsored" { in_spam=4; in_ham=255}
|> Map.add "sport" { in_spam=0; in_ham=8}
|> Map.add "sports" { in_spam=7; in_ham=7}
|> Map.add "spot" { in_spam=0; in_ham=18}
|> Map.add "spots" { in_spam=0; in_ham=15}
|> Map.add "spotted" { in_spam=0; in_ham=13}
|> Map.add "spread" { in_spam=4; in_ham=13}
|> Map.add "spring" { in_spam=4; in_ham=18}
|> Map.add "spy" { in_spam=1; in_ham=11}
|> Map.add "sql" { in_spam=2; in_ham=8}
|> Map.add "square" { in_spam=4; in_ham=12}
|> Map.add "squeeze" { in_spam=0; in_ham=8}
|> Map.add "src" { in_spam=122; in_ham=42}
|> Map.add "ssh" { in_spam=0; in_ham=19}
|> Map.add "ssl" { in_spam=3; in_ham=12}
|> Map.add "stability" { in_spam=9; in_ham=9}
|> Map.add "stable" { in_spam=2; in_ham=15}
|> Map.add "staff" { in_spam=6; in_ham=22}
|> Map.add "stage" { in_spam=0; in_ham=14}
|> Map.add "stages" { in_spam=0; in_ham=9}
|> Map.add "staggering" { in_spam=14; in_ham=3}
|> Map.add "stamp" { in_spam=2; in_ham=7}
|> Map.add "stand" { in_spam=7; in_ham=25}
|> Map.add "standard" { in_spam=29; in_ham=53}
|> Map.add "standards" { in_spam=4; in_ham=23}
|> Map.add "stands" { in_spam=4; in_ham=15}
|> Map.add "stanford" { in_spam=0; in_ham=8}
|> Map.add "stanza" { in_spam=0; in_ham=9}
|> Map.add "star" { in_spam=2; in_ham=13}
|> Map.add "start" { in_spam=50; in_ham=122}
|> Map.add "start-ups" { in_spam=0; in_ham=8}
|> Map.add "started" { in_spam=28; in_ham=62}
|> Map.add "starting" { in_spam=9; in_ham=59}
|> Map.add "starts" { in_spam=5; in_ham=29}
|> Map.add "startup" { in_spam=6; in_ham=30}
|> Map.add "state" { in_spam=111; in_ham=106}
|> Map.add "stated" { in_spam=14; in_ham=8}
|> Map.add "statement" { in_spam=5; in_ham=33}
|> Map.add "statements" { in_spam=7; in_ham=19}
|> Map.add "states" { in_spam=50; in_ham=62}
|> Map.add "static" { in_spam=0; in_ham=23}
|> Map.add "station" { in_spam=4; in_ham=11}
|> Map.add "stations" { in_spam=1; in_ham=13}
|> Map.add "statistical" { in_spam=0; in_ham=8}
|> Map.add "statistics" { in_spam=10; in_ham=19}
|> Map.add "stats" { in_spam=0; in_ham=11}
|> Map.add "status" { in_spam=12; in_ham=75}
|> Map.add "stay" { in_spam=10; in_ham=20}
|> Map.add "staying" { in_spam=5; in_ham=5}
|> Map.add "std" { in_spam=1; in_ham=7}
|> Map.add "stdin" { in_spam=0; in_ham=13}
|> Map.add "stdout" { in_spam=0; in_ham=13}
|> Map.add "steady" { in_spam=6; in_ham=10}
|> Map.add "steal" { in_spam=5; in_ham=8}
|> Map.add "stealing" { in_spam=4; in_ham=9}
|> Map.add "step" { in_spam=8; in_ham=36}
|> Map.add "step-by-step" { in_spam=9; in_ham=3}
|> Map.add "stephen" { in_spam=0; in_ham=20}
|> Map.add "stepped" { in_spam=2; in_ham=10}
|> Map.add "steps" { in_spam=11; in_ham=17}
|> Map.add "stern" { in_spam=0; in_ham=8}
|> Map.add "steve" { in_spam=2; in_ham=31}
|> Map.add "stew" { in_spam=0; in_ham=9}
|> Map.add "stewart" { in_spam=1; in_ham=7}
|> Map.add "stick" { in_spam=1; in_ham=31}
|> Map.add "still" { in_spam=34; in_ham=347}
|> Map.add "stm" { in_spam=0; in_ham=14}
|> Map.add "stock" { in_spam=17; in_ham=25}
|> Map.add "stocks" { in_spam=4; in_ham=27}
|> Map.add "stoddard" { in_spam=0; in_ham=11}
|> Map.add "stole" { in_spam=0; in_ham=14}
|> Map.add "stolen" { in_spam=0; in_ham=11}
|> Map.add "stone" { in_spam=1; in_ham=7}
|> Map.add "stop" { in_spam=14; in_ham=116}
|> Map.add "stopped" { in_spam=4; in_ham=13}
|> Map.add "storage" { in_spam=1; in_ham=45}
|> Map.add "store" { in_spam=14; in_ham=43}
|> Map.add "stored" { in_spam=0; in_ham=12}
|> Map.add "stores" { in_spam=2; in_ham=15}
|> Map.add "stories" { in_spam=11; in_ham=28}
|> Map.add "storing" { in_spam=0; in_ham=8}
|> Map.add "story" { in_spam=11; in_ham=146}
|> Map.add "straight" { in_spam=5; in_ham=40}
|> Map.add "strain" { in_spam=1; in_ham=8}
|> Map.add "strange" { in_spam=3; in_ham=31}
|> Map.add "strategic" { in_spam=1; in_ham=7}
|> Map.add "strategies" { in_spam=9; in_ham=9}
|> Map.add "strategy" { in_spam=9; in_ham=24}
|> Map.add "stream" { in_spam=5; in_ham=19}
|> Map.add "streams" { in_spam=5; in_ham=8}
|> Map.add "street" { in_spam=17; in_ham=75}
|> Map.add "strength" { in_spam=7; in_ham=11}
|> Map.add "stress" { in_spam=1; in_ham=8}
|> Map.add "strict" { in_spam=4; in_ham=8}
|> Map.add "strictly" { in_spam=11; in_ham=14}
|> Map.add "striking" { in_spam=0; in_ham=8}
|> Map.add "string" { in_spam=1; in_ham=21}
|> Map.add "strings" { in_spam=0; in_ham=9}
|> Map.add "strip" { in_spam=0; in_ham=18}
|> Map.add "stripped" { in_spam=0; in_ham=8}
|> Map.add "strong" { in_spam=40; in_ham=34}
|> Map.add "stronger" { in_spam=1; in_ham=9}
|> Map.add "strongly" { in_spam=26; in_ham=8}
|> Map.add "struck" { in_spam=2; in_ham=7}
|> Map.add "structure" { in_spam=2; in_ham=18}
|> Map.add "structures" { in_spam=0; in_ham=12}
|> Map.add "struggle" { in_spam=2; in_ham=8}
|> Map.add "stuck" { in_spam=0; in_ham=26}
|> Map.add "student" { in_spam=9; in_ham=15}
|> Map.add "students" { in_spam=1; in_ham=7}
|> Map.add "studies" { in_spam=7; in_ham=16}
|> Map.add "study" { in_spam=6; in_ham=34}
|> Map.add "studying" { in_spam=3; in_ham=8}
|> Map.add "stuff" { in_spam=7; in_ham=171}
|> Map.add "stupid" { in_spam=1; in_ham=37}
|> Map.add "style" { in_spam=100; in_ham=37}
|> Map.add "sub" { in_spam=2; in_ham=16}
|> Map.add "subject" { in_spam=97; in_ham=287}
|> Map.add "subjects" { in_spam=2; in_ham=7}
|> Map.add "submission" { in_spam=3; in_ham=6}
|> Map.add "submit" { in_spam=61; in_ham=14}
|> Map.add "submitting" { in_spam=6; in_ham=5}
|> Map.add "subscribe" { in_spam=6; in_ham=15}
|> Map.add "subscribed" { in_spam=29; in_ham=58}
|> Map.add "subscriber" { in_spam=13; in_ham=2}
|> Map.add "subscription" { in_spam=65; in_ham=105}
|> Map.add "subsequently" { in_spam=1; in_ham=7}
|> Map.add "substantial" { in_spam=7; in_ham=13}
|> Map.add "subtle" { in_spam=0; in_ham=9}
|> Map.add "suburban" { in_spam=0; in_ham=14}
|> Map.add "succeed" { in_spam=10; in_ham=9}
|> Map.add "success" { in_spam=23; in_ham=34}
|> Map.add "successful" { in_spam=29; in_ham=34}
|> Map.add "successfully" { in_spam=6; in_ham=19}
|> Map.add "such" { in_spam=50; in_ham=274}
|> Map.add "suck" { in_spam=0; in_ham=14}
|> Map.add "sucked" { in_spam=0; in_ham=8}
|> Map.add "sucks" { in_spam=0; in_ham=11}
|> Map.add "suddenly" { in_spam=1; in_ham=12}
|> Map.add "sue" { in_spam=0; in_ham=11}
|> Map.add "suffer" { in_spam=1; in_ham=8}
|> Map.add "suffered" { in_spam=3; in_ham=11}
|> Map.add "suffering" { in_spam=3; in_ham=12}
|> Map.add "sufficient" { in_spam=4; in_ham=19}
|> Map.add "suggest" { in_spam=12; in_ham=28}
|> Map.add "suggested" { in_spam=2; in_ham=18}
|> Map.add "suggesting" { in_spam=0; in_ham=13}
|> Map.add "suggestion" { in_spam=1; in_ham=8}
|> Map.add "suggestions" { in_spam=3; in_ham=37}
|> Map.add "suggests" { in_spam=0; in_ham=19}
|> Map.add "suit" { in_spam=5; in_ham=7}
|> Map.add "suitable" { in_spam=4; in_ham=9}
|> Map.add "suite" { in_spam=28; in_ham=48}
|> Map.add "suits" { in_spam=0; in_ham=10}
|> Map.add "sum" { in_spam=33; in_ham=13}
|> Map.add "summaries" { in_spam=0; in_ham=16}
|> Map.add "summary" { in_spam=2; in_ham=25}
|> Map.add "summer" { in_spam=5; in_ham=26}
|> Map.add "sun" { in_spam=0; in_ham=78}
|> Map.add "sun's" { in_spam=0; in_ham=10}
|> Map.add "sunday" { in_spam=1; in_ham=39}
|> Map.add "super" { in_spam=12; in_ham=12}
|> Map.add "superior" { in_spam=23; in_ham=8}
|> Map.add "supplied" { in_spam=1; in_ham=225}
|> Map.add "supplies" { in_spam=9; in_ham=8}
|> Map.add "supply" { in_spam=8; in_ham=19}
|> Map.add "support" { in_spam=43; in_ham=154}
|> Map.add "supported" { in_spam=7; in_ham=29}
|> Map.add "supporting" { in_spam=1; in_ham=21}
|> Map.add "supports" { in_spam=2; in_ham=31}
|> Map.add "suppose" { in_spam=2; in_ham=33}
|> Map.add "supposed" { in_spam=9; in_ham=50}
|> Map.add "supposedly" { in_spam=0; in_ham=11}
|> Map.add "supreme" { in_spam=0; in_ham=9}
|> Map.add "sure" { in_spam=45; in_ham=254}
|> Map.add "surely" { in_spam=2; in_ham=15}
|> Map.add "surface" { in_spam=2; in_ham=13}
|> Map.add "surprise" { in_spam=7; in_ham=7}
|> Map.add "surprised" { in_spam=14; in_ham=17}
|> Map.add "surprising" { in_spam=0; in_ham=9}
|> Map.add "surprisingly" { in_spam=2; in_ham=17}
|> Map.add "surrounding" { in_spam=1; in_ham=17}
|> Map.add "survey" { in_spam=4; in_ham=7}
|> Map.add "survive" { in_spam=0; in_ham=13}
|> Map.add "suspect" { in_spam=2; in_ham=41}
|> Map.add "suspected" { in_spam=0; in_ham=8}
|> Map.add "suspicious" { in_spam=3; in_ham=7}
|> Map.add "svanstrom" { in_spam=0; in_ham=14}
|> Map.add "swap" { in_spam=0; in_ham=16}
|> Map.add "sweet" { in_spam=3; in_ham=9}
|> Map.add "switch" { in_spam=0; in_ham=44}
|> Map.add "switching" { in_spam=0; in_ham=15}
|> Map.add "symbol" { in_spam=6; in_ham=19}
|> Map.add "symbols" { in_spam=0; in_ham=9}
|> Map.add "syntax" { in_spam=0; in_ham=17}
|> Map.add "sys" { in_spam=2; in_ham=11}
|> Map.add "system" { in_spam=52; in_ham=256}
|> Map.add "systems" { in_spam=10; in_ham=106}
|> Map.add "systemworks" { in_spam=23; in_ham=0}
|> Map.add "table" { in_spam=177; in_ham=28}
|> Map.add "tactic" { in_spam=0; in_ham=9}
|> Map.add "tactics" { in_spam=0; in_ham=12}
|> Map.add "tag" { in_spam=4; in_ham=42}
|> Map.add "tagged" { in_spam=1; in_ham=11}
|> Map.add "tagline" { in_spam=0; in_ham=19}
|> Map.add "tags" { in_spam=2; in_ham=20}
|> Map.add "tahoma" { in_spam=32; in_ham=0}
|> Map.add "taint" { in_spam=5; in_ham=8}
|> Map.add "take" { in_spam=88; in_ham=221}
|> Map.add "taken" { in_spam=13; in_ham=57}
|> Map.add "takes" { in_spam=17; in_ham=70}
|> Map.add "taking" { in_spam=12; in_ham=53}
|> Map.add "tale" { in_spam=0; in_ham=8}
|> Map.add "talented" { in_spam=0; in_ham=10}
|> Map.add "taliban" { in_spam=0; in_ham=9}
|> Map.add "talios" { in_spam=0; in_ham=10}
|> Map.add "talk" { in_spam=4; in_ham=65}
|> Map.add "talked" { in_spam=0; in_ham=8}
|> Map.add "talking" { in_spam=4; in_ham=78}
|> Map.add "talkread" { in_spam=0; in_ham=10}
|> Map.add "talks" { in_spam=0; in_ham=19}
|> Map.add "tall" { in_spam=3; in_ham=14}
|> Map.add "tape" { in_spam=2; in_ham=12}
|> Map.add "tar" { in_spam=0; in_ham=13}
|> Map.add "tarari" { in_spam=0; in_ham=8}
|> Map.add "target" { in_spam=42; in_ham=36}
|> Map.add "targeted" { in_spam=6; in_ham=7}
|> Map.add "targeting" { in_spam=1; in_ham=9}
|> Map.add "targets" { in_spam=0; in_ham=10}
|> Map.add "task" { in_spam=2; in_ham=30}
|> Map.add "taste" { in_spam=8; in_ham=6}
|> Map.add "taught" { in_spam=3; in_ham=11}
|> Map.add "tax" { in_spam=16; in_ham=20}
|> Map.add "taxes" { in_spam=6; in_ham=18}
|> Map.add "taxing" { in_spam=0; in_ham=8}
|> Map.add "tbody" { in_spam=48; in_ham=0}
|> Map.add "tcl" { in_spam=0; in_ham=35}
|> Map.add "tea" { in_spam=1; in_ham=10}
|> Map.add "teach" { in_spam=15; in_ham=15}
|> Map.add "teaching" { in_spam=1; in_ham=8}
|> Map.add "team" { in_spam=13; in_ham=34}
|> Map.add "teams" { in_spam=0; in_ham=8}
|> Map.add "tech" { in_spam=2; in_ham=26}
|> Map.add "technical" { in_spam=12; in_ham=37}
|> Map.add "technique" { in_spam=6; in_ham=9}
|> Map.add "techniques" { in_spam=6; in_ham=27}
|> Map.add "technologies" { in_spam=2; in_ham=27}
|> Map.add "technology" { in_spam=24; in_ham=84}
|> Map.add "technomad" { in_spam=0; in_ham=8}
|> Map.add "teeming" { in_spam=0; in_ham=8}
|> Map.add "tel" { in_spam=15; in_ham=16}
|> Map.add "telecom" { in_spam=1; in_ham=9}
|> Map.add "teledyn" { in_spam=0; in_ham=46}
|> Map.add "teledynamics" { in_spam=0; in_ham=45}
|> Map.add "telephone" { in_spam=28; in_ham=17}
|> Map.add "television" { in_spam=5; in_ham=17}
|> Map.add "tell" { in_spam=31; in_ham=130}
|> Map.add "telling" { in_spam=1; in_ham=31}
|> Map.add "tells" { in_spam=0; in_ham=20}
|> Map.add "temperature" { in_spam=0; in_ham=13}
|> Map.add "temperatures" { in_spam=0; in_ham=9}
|> Map.add "temple" { in_spam=1; in_ham=7}
|> Map.add "temporary" { in_spam=0; in_ham=15}
|> Map.add "ten" { in_spam=6; in_ham=29}
|> Map.add "tend" { in_spam=1; in_ham=30}
|> Map.add "tendency" { in_spam=0; in_ham=9}
|> Map.add "tends" { in_spam=2; in_ham=16}
|> Map.add "tens" { in_spam=0; in_ham=11}
|> Map.add "tenure" { in_spam=4; in_ham=12}
|> Map.add "term" { in_spam=33; in_ham=24}
|> Map.add "terminal" { in_spam=2; in_ham=24}
|> Map.add "terms" { in_spam=27; in_ham=124}
|> Map.add "terrible" { in_spam=3; in_ham=18}
|> Map.add "territory" { in_spam=3; in_ham=7}
|> Map.add "terror" { in_spam=0; in_ham=8}
|> Map.add "terrorism" { in_spam=0; in_ham=16}
|> Map.add "terrorist" { in_spam=3; in_ham=7}
|> Map.add "terrorists" { in_spam=1; in_ham=10}
|> Map.add "test" { in_spam=13; in_ham=123}
|> Map.add "tested" { in_spam=8; in_ham=25}
|> Map.add "testing" { in_spam=4; in_ham=58}
|> Map.add "tests" { in_spam=2; in_ham=37}
|> Map.add "texas" { in_spam=3; in_ham=10}
|> Map.add "text" { in_spam=155; in_ham=116}
|> Map.add "text-align" { in_spam=17; in_ham=2}
|> Map.add "than" { in_spam=89; in_ham=470}

