open Database
open BayesianBody_004
let db = db 
|> Map.add "ethnic" { in_spam=2; in_ham=5}
|> Map.add "eugen" { in_spam=0; in_ham=23}
|> Map.add "eugene" { in_spam=0; in_ham=11}
|> Map.add "euro" { in_spam=3; in_ham=2}
|> Map.add "europe" { in_spam=9; in_ham=32}
|> Map.add "europe's" { in_spam=0; in_ham=3}
|> Map.add "european" { in_spam=6; in_ham=19}
|> Map.add "europeans" { in_spam=0; in_ham=7}
|> Map.add "euros" { in_spam=10; in_ham=1}
|> Map.add "eval" { in_spam=0; in_ham=12}
|> Map.add "evaluate" { in_spam=6; in_ham=1}
|> Map.add "evaluated" { in_spam=0; in_ham=3}
|> Map.add "evaluation" { in_spam=6; in_ham=7}
|> Map.add "evans" { in_spam=0; in_ham=3}
|> Map.add "evansville" { in_spam=0; in_ham=8}
|> Map.add "evdemon" { in_spam=0; in_ham=3}
|> Map.add "even" { in_spam=66; in_ham=363}
|> Map.add "evening" { in_spam=0; in_ham=16}
|> Map.add "evenly" { in_spam=0; in_ham=6}
|> Map.add "event" { in_spam=4; in_ham=30}
|> Map.add "events" { in_spam=19; in_ham=16}
|> Map.add "eventually" { in_spam=7; in_ham=39}
|> Map.add "ever" { in_spam=46; in_ham=125}
|> Map.add "evergo" { in_spam=0; in_ham=18}
|> Map.add "every" { in_spam=60; in_ham=179}
|> Map.add "everybody" { in_spam=4; in_ham=27}
|> Map.add "everyday" { in_spam=5; in_ham=7}
|> Map.add "everyone" { in_spam=19; in_ham=73}
|> Map.add "everyone's" { in_spam=1; in_ham=12}
|> Map.add "everything" { in_spam=22; in_ham=102}
|> Map.add "everywhere" { in_spam=3; in_ham=22}
|> Map.add "evidence" { in_spam=2; in_ham=49}
|> Map.add "evident" { in_spam=0; in_ham=5}
|> Map.add "evidently" { in_spam=0; in_ham=5}
|> Map.add "evil" { in_spam=0; in_ham=24}
|> Map.add "evil-doers" { in_spam=0; in_ham=36}
|> Map.add "evoked" { in_spam=0; in_ham=4}
|> Map.add "evokes" { in_spam=0; in_ham=4}
|> Map.add "evolution" { in_spam=0; in_ham=4}
|> Map.add "evolve" { in_spam=0; in_ham=9}
|> Map.add "evolved" { in_spam=1; in_ham=14}
|> Map.add "evolving" { in_spam=0; in_ham=4}
|> Map.add "exact" { in_spam=12; in_ham=11}
|> Map.add "exactly" { in_spam=24; in_ham=94}
|> Map.add "exam" { in_spam=1; in_ham=2}
|> Map.add "examine" { in_spam=0; in_ham=5}
|> Map.add "examined" { in_spam=2; in_ham=3}
|> Map.add "examining" { in_spam=0; in_ham=3}
|> Map.add "example" { in_spam=45; in_ham=219}
|> Map.add "examples" { in_spam=4; in_ham=28}
|> Map.add "exceed" { in_spam=8; in_ham=4}
|> Map.add "exceedingly" { in_spam=5; in_ham=2}
|> Map.add "excel" { in_spam=2; in_ham=3}
|> Map.add "excellent" { in_spam=20; in_ham=18}
|> Map.add "except" { in_spam=5; in_ham=95}
|> Map.add "exception" { in_spam=1; in_ham=7}
|> Map.add "exceptional" { in_spam=3; in_ham=1}
|> Map.add "exceptions" { in_spam=5; in_ham=2}
|> Map.add "excerpt" { in_spam=2; in_ham=3}
|> Map.add "excerpted" { in_spam=0; in_ham=3}
|> Map.add "excess" { in_spam=13; in_ham=6}
|> Map.add "excessive" { in_spam=1; in_ham=3}
|> Map.add "exchange" { in_spam=19; in_ham=16}
|> Map.add "exchanged" { in_spam=2; in_ham=3}
|> Map.add "excite" { in_spam=5; in_ham=0}
|> Map.add "excited" { in_spam=1; in_ham=9}
|> Map.add "excitement" { in_spam=1; in_ham=6}
|> Map.add "exciting" { in_spam=14; in_ham=3}
|> Map.add "exclamation" { in_spam=0; in_ham=3}
|> Map.add "exclude" { in_spam=6; in_ham=9}
|> Map.add "excluded" { in_spam=13; in_ham=2}
|> Map.add "exclusive" { in_spam=9; in_ham=10}
|> Map.add "exclusively" { in_spam=1; in_ham=5}
|> Map.add "excuse" { in_spam=2; in_ham=10}
|> Map.add "excuses" { in_spam=2; in_ham=4}
|> Map.add "exe" { in_spam=1; in_ham=5}
|> Map.add "exec" { in_spam=1; in_ham=14}
|> Map.add "executable" { in_spam=0; in_ham=7}
|> Map.add "execute" { in_spam=4; in_ham=16}
|> Map.add "executed" { in_spam=8; in_ham=4}
|> Map.add "executing" { in_spam=0; in_ham=11}
|> Map.add "execution" { in_spam=6; in_ham=13}
|> Map.add "executive" { in_spam=5; in_ham=25}
|> Map.add "executives" { in_spam=3; in_ham=16}
|> Map.add "exempt" { in_spam=0; in_ham=5}
|> Map.add "exercise" { in_spam=10; in_ham=9}
|> Map.add "exercising" { in_spam=3; in_ham=4}
|> Map.add "exhaustion" { in_spam=0; in_ham=3}
|> Map.add "exhaustive" { in_spam=0; in_ham=4}
|> Map.add "exhibits" { in_spam=1; in_ham=2}
|> Map.add "exim" { in_spam=0; in_ham=4}
|> Map.add "exist" { in_spam=5; in_ham=56}
|> Map.add "existed" { in_spam=1; in_ham=19}
|> Map.add "existence" { in_spam=5; in_ham=16}
|> Map.add "existing" { in_spam=8; in_ham=48}
|> Map.add "exists" { in_spam=3; in_ham=31}
|> Map.add "exit" { in_spam=0; in_ham=21}
|> Map.add "exmh" { in_spam=0; in_ham=135}
|> Map.add "exmh's" { in_spam=0; in_ham=6}
|> Map.add "exmh-" { in_spam=0; in_ham=3}
|> Map.add "exmh-users" { in_spam=0; in_ham=86}
|> Map.add "exmh-workers" { in_spam=0; in_ham=55}
|> Map.add "exmhbindings" { in_spam=0; in_ham=3}
|> Map.add "exmhunseen" { in_spam=0; in_ham=3}
|> Map.add "exotic" { in_spam=1; in_ham=2}
|> Map.add "exp" { in_spam=3; in_ham=2}
|> Map.add "expand" { in_spam=3; in_ham=13}
|> Map.add "expanding" { in_spam=4; in_ham=6}
|> Map.add "expansion" { in_spam=3; in_ham=2}
|> Map.add "expect" { in_spam=17; in_ham=52}
|> Map.add "expectancy" { in_spam=0; in_ham=4}
|> Map.add "expectation" { in_spam=0; in_ham=4}
|> Map.add "expectations" { in_spam=1; in_ham=5}
|> Map.add "expected" { in_spam=4; in_ham=41}
|> Map.add "expecting" { in_spam=6; in_ham=6}
|> Map.add "expects" { in_spam=0; in_ham=14}
|> Map.add "expediently" { in_spam=0; in_ham=3}
|> Map.add "expenditures" { in_spam=0; in_ham=3}
|> Map.add "expense" { in_spam=14; in_ham=14}
|> Map.add "expenses" { in_spam=12; in_ham=6}
|> Map.add "expensive" { in_spam=5; in_ham=26}
|> Map.add "experience" { in_spam=27; in_ham=112}
|> Map.add "experienced" { in_spam=1; in_ham=14}
|> Map.add "experiences" { in_spam=3; in_ham=10}
|> Map.add "experiencing" { in_spam=1; in_ham=2}
|> Map.add "experiment" { in_spam=1; in_ham=22}
|> Map.add "experimental" { in_spam=0; in_ham=4}
|> Map.add "experiments" { in_spam=0; in_ham=6}
|> Map.add "expert" { in_spam=7; in_ham=16}
|> Map.add "expertise" { in_spam=5; in_ham=9}
|> Map.add "experts" { in_spam=12; in_ham=21}
|> Map.add "expiration" { in_spam=8; in_ham=0}
|> Map.add "expired" { in_spam=1; in_ham=2}
|> Map.add "expiry" { in_spam=1; in_ham=2}
|> Map.add "explain" { in_spam=3; in_ham=38}
|> Map.add "explained" { in_spam=4; in_ham=31}
|> Map.add "explaining" { in_spam=0; in_ham=5}
|> Map.add "explains" { in_spam=0; in_ham=18}
|> Map.add "explanation" { in_spam=4; in_ham=22}
|> Map.add "explicit" { in_spam=0; in_ham=10}
|> Map.add "explicitely" { in_spam=0; in_ham=3}
|> Map.add "explicitly" { in_spam=1; in_ham=21}
|> Map.add "exploit" { in_spam=0; in_ham=9}
|> Map.add "exploitation" { in_spam=1; in_ham=2}
|> Map.add "exploited" { in_spam=0; in_ham=11}
|> Map.add "exploiting" { in_spam=0; in_ham=5}
|> Map.add "exploits" { in_spam=0; in_ham=3}
|> Map.add "explore" { in_spam=4; in_ham=8}
|> Map.add "explorer" { in_spam=1; in_ham=9}
|> Map.add "explosion" { in_spam=0; in_ham=4}
|> Map.add "explosive" { in_spam=5; in_ham=3}
|> Map.add "exponential" { in_spam=0; in_ham=3}
|> Map.add "export" { in_spam=2; in_ham=11}
|> Map.add "exports" { in_spam=0; in_ham=3}
|> Map.add "expose" { in_spam=3; in_ham=5}
|> Map.add "exposed" { in_spam=0; in_ham=6}
|> Map.add "exposing" { in_spam=1; in_ham=4}
|> Map.add "exposure" { in_spam=0; in_ham=5}
|> Map.add "expr" { in_spam=0; in_ham=6}
|> Map.add "express" { in_spam=5; in_ham=9}
|> Map.add "expressed" { in_spam=2; in_ham=8}
|> Map.add "expressing" { in_spam=0; in_ham=3}
|> Map.add "expression" { in_spam=0; in_ham=16}
|> Map.add "expressions" { in_spam=0; in_ham=5}
|> Map.add "exquisite" { in_spam=1; in_ham=2}
|> Map.add "ext" { in_spam=29; in_ham=6}
|> Map.add "extend" { in_spam=1; in_ham=8}
|> Map.add "extended" { in_spam=9; in_ham=15}
|> Map.add "extending" { in_spam=0; in_ham=3}
|> Map.add "extends" { in_spam=0; in_ham=3}
|> Map.add "extension" { in_spam=0; in_ham=9}
|> Map.add "extensions" { in_spam=6; in_ham=6}
|> Map.add "extensive" { in_spam=2; in_ham=19}
|> Map.add "extent" { in_spam=1; in_ham=15}
|> Map.add "external" { in_spam=2; in_ham=17}
|> Map.add "extorting" { in_spam=0; in_ham=4}
|> Map.add "extortion" { in_spam=0; in_ham=3}
|> Map.add "extra" { in_spam=12; in_ham=37}
|> Map.add "extra-group" { in_spam=0; in_ham=5}
|> Map.add "extract" { in_spam=4; in_ham=5}
|> Map.add "extracted" { in_spam=3; in_ham=3}
|> Map.add "extracting" { in_spam=4; in_ham=1}
|> Map.add "extraction" { in_spam=0; in_ham=3}
|> Map.add "extras" { in_spam=0; in_ham=4}
|> Map.add "extreme" { in_spam=3; in_ham=18}
|> Map.add "extremely" { in_spam=15; in_ham=29}
|> Map.add "extremes" { in_spam=0; in_ham=5}
|> Map.add "extremist" { in_spam=0; in_ham=3}
|> Map.add "extremists'" { in_spam=0; in_ham=4}
|> Map.add "extricate" { in_spam=0; in_ham=4}
|> Map.add "eye" { in_spam=4; in_ham=12}
|> Map.add "eyeball" { in_spam=0; in_ham=3}
|> Map.add "eyes" { in_spam=2; in_ham=16}
|> Map.add "f-n" { in_spam=0; in_ham=15}
|> Map.add "f-p" { in_spam=0; in_ham=10}
|> Map.add "fabrics" { in_spam=0; in_ham=3}
|> Map.add "fabulous" { in_spam=3; in_ham=2}
|> Map.add "face" { in_spam=183; in_ham=52}
|> Map.add "faced" { in_spam=0; in_ham=11}
|> Map.add "faces" { in_spam=5; in_ham=6}
|> Map.add "facilitate" { in_spam=2; in_ham=10}
|> Map.add "facilitated" { in_spam=0; in_ham=3}
|> Map.add "facilitating" { in_spam=0; in_ham=3}
|> Map.add "facility" { in_spam=0; in_ham=3}
|> Map.add "facing" { in_spam=1; in_ham=13}
|> Map.add "fact" { in_spam=29; in_ham=119}
|> Map.add "factor" { in_spam=1; in_ham=14}
|> Map.add "factors" { in_spam=3; in_ham=7}
|> Map.add "factory" { in_spam=1; in_ham=4}
|> Map.add "facts" { in_spam=12; in_ham=16}
|> Map.add "factual" { in_spam=5; in_ham=1}
|> Map.add "factually" { in_spam=0; in_ham=3}
|> Map.add "faculty" { in_spam=0; in_ham=3}
|> Map.add "fad" { in_spam=0; in_ham=5}
|> Map.add "fafaf" { in_spam=5; in_ham=0}
|> Map.add "fagnan" { in_spam=0; in_ham=6}
|> Map.add "fahrl" { in_spam=0; in_ham=8}
|> Map.add "fahrt" { in_spam=0; in_ham=3}
|> Map.add "fail" { in_spam=7; in_ham=31}
|> Map.add "failed" { in_spam=6; in_ham=46}
|> Map.add "failing" { in_spam=1; in_ham=14}
|> Map.add "fails" { in_spam=0; in_ham=39}
|> Map.add "failure" { in_spam=4; in_ham=34}
|> Map.add "failures" { in_spam=0; in_ham=6}
|> Map.add "fair" { in_spam=16; in_ham=34}
|> Map.add "fairly" { in_spam=0; in_ham=26}
|> Map.add "fairness" { in_spam=0; in_ham=3}
|> Map.add "faith" { in_spam=2; in_ham=11}
|> Map.add "faithful" { in_spam=2; in_ham=3}
|> Map.add "faithfully" { in_spam=9; in_ham=0}
|> Map.add "fake" { in_spam=0; in_ham=12}
|> Map.add "faking" { in_spam=0; in_ham=3}
|> Map.add "fall" { in_spam=18; in_ham=67}
|> Map.add "fallen" { in_spam=1; in_ham=7}
|> Map.add "falling" { in_spam=1; in_ham=9}
|> Map.add "fallout" { in_spam=1; in_ham=2}
|> Map.add "falls" { in_spam=2; in_ham=5}
|> Map.add "false" { in_spam=4; in_ham=72}
|> Map.add "falter" { in_spam=0; in_ham=3}
|> Map.add "familar" { in_spam=0; in_ham=3}
|> Map.add "familiar" { in_spam=2; in_ham=12}
|> Map.add "families" { in_spam=4; in_ham=12}
|> Map.add "family" { in_spam=48; in_ham=55}
|> Map.add "family's" { in_spam=7; in_ham=0}
|> Map.add "famous" { in_spam=2; in_ham=16}
|> Map.add "fan" { in_spam=0; in_ham=6}
|> Map.add "fancy" { in_spam=4; in_ham=8}
|> Map.add "fans" { in_spam=0; in_ham=4}
|> Map.add "fantastic" { in_spam=2; in_ham=5}
|> Map.add "fantasy" { in_spam=4; in_ham=6}
|> Map.add "faq" { in_spam=7; in_ham=10}
|> Map.add "far" { in_spam=17; in_ham=140}
|> Map.add "far-fetched" { in_spam=0; in_ham=6}
|> Map.add "fark" { in_spam=0; in_ham=29}
|> Map.add "farm" { in_spam=8; in_ham=5}
|> Map.add "farmer" { in_spam=2; in_ham=2}
|> Map.add "farmers" { in_spam=4; in_ham=3}
|> Map.add "farming" { in_spam=0; in_ham=5}
|> Map.add "farms" { in_spam=4; in_ham=3}
|> Map.add "farquhar" { in_spam=0; in_ham=41}
|> Map.add "farther" { in_spam=0; in_ham=5}
|> Map.add "farting" { in_spam=0; in_ham=3}
|> Map.add "fascinating" { in_spam=1; in_ham=5}
|> Map.add "fascination" { in_spam=0; in_ham=3}
|> Map.add "fascism" { in_spam=0; in_ham=3}
|> Map.add "fashion" { in_spam=2; in_ham=9}
|> Map.add "fashioned" { in_spam=0; in_ham=7}
|> Map.add "fast" { in_spam=30; in_ham=82}
|> Map.add "faster" { in_spam=10; in_ham=33}
|> Map.add "fastest" { in_spam=21; in_ham=53}
|> Map.add "fastmail" { in_spam=0; in_ham=15}
|> Map.add "fat" { in_spam=9; in_ham=20}
|> Map.add "fatal" { in_spam=0; in_ham=4}
|> Map.add "fate" { in_spam=2; in_ham=2}
|> Map.add "father" { in_spam=17; in_ham=22}
|> Map.add "fathers" { in_spam=3; in_ham=4}
|> Map.add "fathom" { in_spam=0; in_ham=4}
|> Map.add "fault" { in_spam=1; in_ham=16}
|> Map.add "faulty" { in_spam=0; in_ham=3}
|> Map.add "favor" { in_spam=5; in_ham=23}
|> Map.add "favorite" { in_spam=7; in_ham=22}
|> Map.add "favors" { in_spam=0; in_ham=9}
|> Map.add "favour" { in_spam=4; in_ham=1}
|> Map.add "favourite" { in_spam=0; in_ham=11}
|> Map.add "fax" { in_spam=56; in_ham=32}
|> Map.add "faxes" { in_spam=1; in_ham=3}
|> Map.add "fbi" { in_spam=1; in_ham=12}
|> Map.add "fcc" { in_spam=1; in_ham=7}
|> Map.add "fddi" { in_spam=0; in_ham=6}
|> Map.add "fear" { in_spam=2; in_ham=13}
|> Map.add "feared" { in_spam=0; in_ham=4}
|> Map.add "fearing" { in_spam=0; in_ham=3}
|> Map.add "feasible" { in_spam=0; in_ham=7}
|> Map.add "feast" { in_spam=0; in_ham=3}
|> Map.add "feature" { in_spam=2; in_ham=57}
|> Map.add "featured" { in_spam=9; in_ham=5}
|> Map.add "features" { in_spam=9; in_ham=46}
|> Map.add "featuring" { in_spam=5; in_ham=1}
|> Map.add "feb" { in_spam=1; in_ham=17}
|> Map.add "february" { in_spam=3; in_ham=9}
|> Map.add "fed" { in_spam=8; in_ham=10}
|> Map.add "federal" { in_spam=25; in_ham=33}
|> Map.add "federation" { in_spam=7; in_ham=4}
|> Map.add "fee" { in_spam=15; in_ham=18}
|> Map.add "feed" { in_spam=2; in_ham=24}
|> Map.add "feedback" { in_spam=5; in_ham=22}
|> Map.add "feeding" { in_spam=0; in_ham=9}
|> Map.add "feeds" { in_spam=4; in_ham=8}
|> Map.add "feel" { in_spam=31; in_ham=68}
|> Map.add "feeling" { in_spam=10; in_ham=22}
|> Map.add "feelings" { in_spam=4; in_ham=10}
|> Map.add "feels" { in_spam=0; in_ham=13}
|> Map.add "fees" { in_spam=21; in_ham=5}
|> Map.add "feet" { in_spam=8; in_ham=28}
|> Map.add "fel" { in_spam=0; in_ham=9}
|> Map.add "felicity" { in_spam=0; in_ham=4}
|> Map.add "felinda" { in_spam=0; in_ham=8}
|> Map.add "fell" { in_spam=1; in_ham=10}
|> Map.add "fellas" { in_spam=0; in_ham=4}
|> Map.add "fellow" { in_spam=0; in_ham=11}
|> Map.add "felt" { in_spam=3; in_ham=16}
|> Map.add "female" { in_spam=7; in_ham=19}
|> Map.add "females" { in_spam=1; in_ham=11}
|> Map.add "fen" { in_spam=1; in_ham=2}
|> Map.add "fence" { in_spam=0; in_ham=4}
|> Map.add "fergal" { in_spam=0; in_ham=3}
|> Map.add "ferguson" { in_spam=0; in_ham=3}
|> Map.add "fertile" { in_spam=1; in_ham=6}
|> Map.add "fertility" { in_spam=0; in_ham=3}
|> Map.add "fest" { in_spam=0; in_ham=3}
|> Map.add "fetched" { in_spam=0; in_ham=8}
|> Map.add "fetching" { in_spam=0; in_ham=4}
|> Map.add "fetchmail" { in_spam=0; in_ham=11}
|> Map.add "few" { in_spam=39; in_ham=258}
|> Map.add "fewer" { in_spam=0; in_ham=5}
|> Map.add "ffa" { in_spam=5; in_ham=0}
|> Map.add "ffcc" { in_spam=12; in_ham=0}
|> Map.add "ffff" { in_spam=31; in_ham=1}
|> Map.add "ffffae" { in_spam=5; in_ham=0}
|> Map.add "ffffcc" { in_spam=28; in_ham=1}
|> Map.add "ffffff" { in_spam=134; in_ham=6}
|> Map.add "fiber" { in_spam=2; in_ham=3}
|> Map.add "fiber-ringed" { in_spam=0; in_ham=4}
|> Map.add "fiction" { in_spam=0; in_ham=13}
|> Map.add "fiddles" { in_spam=0; in_ham=3}
|> Map.add "fiddling" { in_spam=0; in_ham=5}
|> Map.add "field" { in_spam=8; in_ham=37}
|> Map.add "fields" { in_spam=4; in_ham=13}
|> Map.add "fierce" { in_spam=0; in_ham=3}
|> Map.add "fiercely" { in_spam=0; in_ham=3}
|> Map.add "fifteen" { in_spam=1; in_ham=2}
|> Map.add "fifth" { in_spam=0; in_ham=5}
|> Map.add "fifty" { in_spam=3; in_ham=2}
|> Map.add "fight" { in_spam=9; in_ham=27}
|> Map.add "fighting" { in_spam=1; in_ham=16}
|> Map.add "figure" { in_spam=19; in_ham=57}
|> Map.add "figured" { in_spam=2; in_ham=27}
|> Map.add "figures" { in_spam=1; in_ham=21}
|> Map.add "figuring" { in_spam=0; in_ham=8}
|> Map.add "file" { in_spam=10; in_ham=265}
|> Map.add "filed" { in_spam=5; in_ham=23}
|> Map.add "filename" { in_spam=1; in_ham=9}
|> Map.add "files" { in_spam=22; in_ham=197}
|> Map.add "filesystem" { in_spam=0; in_ham=7}
|> Map.add "filesystems" { in_spam=0; in_ham=3}
|> Map.add "filing" { in_spam=1; in_ham=6}
|> Map.add "fill" { in_spam=81; in_ham=13}
|> Map.add "filled" { in_spam=3; in_ham=6}
|> Map.add "filling" { in_spam=3; in_ham=5}
|> Map.add "film" { in_spam=0; in_ham=17}
|> Map.add "films" { in_spam=0; in_ham=4}
|> Map.add "filter" { in_spam=3; in_ham=29}
|> Map.add "filtered" { in_spam=3; in_ham=2}
|> Map.add "filtering" { in_spam=0; in_ham=26}
|> Map.add "filters" { in_spam=0; in_ham=18}
|> Map.add "filthy" { in_spam=3; in_ham=1}
|> Map.add "final" { in_spam=3; in_ham=26}
|> Map.add "finally" { in_spam=33; in_ham=57}
|> Map.add "finance" { in_spam=11; in_ham=13}
|> Map.add "finances" { in_spam=0; in_ham=4}
|> Map.add "financial" { in_spam=59; in_ham=35}
|> Map.add "financially" { in_spam=15; in_ham=4}
|> Map.add "financing" { in_spam=2; in_ham=8}
|> Map.add "find" { in_spam=67; in_ham=267}
|> Map.add "findall" { in_spam=0; in_ham=4}
|> Map.add "finding" { in_spam=8; in_ham=82}
|> Map.add "findings" { in_spam=7; in_ham=6}
|> Map.add "findmsg" { in_spam=0; in_ham=4}
|> Map.add "finds" { in_spam=1; in_ham=18}
|> Map.add "findseqs" { in_spam=0; in_ham=3}
|> Map.add "findunseen" { in_spam=0; in_ham=3}
|> Map.add "fine" { in_spam=3; in_ham=87}
|> Map.add "finer" { in_spam=1; in_ham=2}
|> Map.add "finest" { in_spam=4; in_ham=2}
|> Map.add "finger" { in_spam=0; in_ham=9}
|> Map.add "fingerprint" { in_spam=0; in_ham=7}
|> Map.add "fingers" { in_spam=1; in_ham=11}
|> Map.add "finish" { in_spam=1; in_ham=8}
|> Map.add "finished" { in_spam=2; in_ham=18}
|> Map.add "finite" { in_spam=0; in_ham=3}
|> Map.add "finland" { in_spam=2; in_ham=3}
|> Map.add "finn" { in_spam=0; in_ham=23}
|> Map.add "fire" { in_spam=6; in_ham=21}
|> Map.add "fired" { in_spam=0; in_ham=3}
|> Map.add "fires" { in_spam=0; in_ham=5}
|> Map.add "firewall" { in_spam=0; in_ham=19}
|> Map.add "firewalls" { in_spam=0; in_ham=12}
|> Map.add "firewire" { in_spam=0; in_ham=5}
|> Map.add "firing" { in_spam=0; in_ham=3}
|> Map.add "firm" { in_spam=15; in_ham=23}
|> Map.add "firmly" { in_spam=0; in_ham=7}
|> Map.add "firms" { in_spam=4; in_ham=10}
|> Map.add "first" { in_spam=56; in_ham=348}
|> Map.add "first-hand" { in_spam=0; in_ham=4}
|> Map.add "firstly" { in_spam=2; in_ham=2}
|> Map.add "fiscal" { in_spam=2; in_ham=7}
|> Map.add "fiscally" { in_spam=0; in_ham=4}
|> Map.add "fish" { in_spam=0; in_ham=13}
|> Map.add "fishing" { in_spam=1; in_ham=2}
|> Map.add "fit" { in_spam=9; in_ham=19}
|> Map.add "fitness" { in_spam=3; in_ham=2}
|> Map.add "fits" { in_spam=0; in_ham=17}
|> Map.add "five" { in_spam=28; in_ham=37}
|> Map.add "fix" { in_spam=1; in_ham=70}
|> Map.add "fixed" { in_spam=8; in_ham=59}
|> Map.add "fixes" { in_spam=0; in_ham=19}
|> Map.add "fixing" { in_spam=1; in_ham=10}
|> Map.add "flag" { in_spam=1; in_ham=23}
|> Map.add "flagged" { in_spam=0; in_ham=7}
|> Map.add "flags" { in_spam=1; in_ham=10}
|> Map.add "flagship" { in_spam=0; in_ham=7}
|> Map.add "flames" { in_spam=0; in_ham=6}
|> Map.add "flash" { in_spam=5; in_ham=5}
|> Map.add "flat" { in_spam=0; in_ham=5}
|> Map.add "flavors" { in_spam=0; in_ham=6}
|> Map.add "flavour" { in_spam=0; in_ham=3}
|> Map.add "flaw" { in_spam=0; in_ham=4}
|> Map.add "flaws" { in_spam=1; in_ham=6}
|> Map.add "flesh" { in_spam=0; in_ham=5}
|> Map.add "flew" { in_spam=0; in_ham=5}
|> Map.add "flexibility" { in_spam=0; in_ham=9}
|> Map.add "flexible" { in_spam=2; in_ham=4}
|> Map.add "flies" { in_spam=0; in_ham=4}
|> Map.add "flight" { in_spam=3; in_ham=17}
|> Map.add "flip" { in_spam=0; in_ham=9}
|> Map.add "flist" { in_spam=0; in_ham=18}
|> Map.add "flist'" { in_spam=0; in_ham=4}
|> Map.add "floating" { in_spam=2; in_ham=2}
|> Map.add "floats" { in_spam=0; in_ham=3}
|> Map.add "flocked" { in_spam=0; in_ham=3}
|> Map.add "flooded" { in_spam=0; in_ham=10}
|> Map.add "floor" { in_spam=2; in_ham=13}
|> Map.add "floors" { in_spam=0; in_ham=3}
|> Map.add "floppy" { in_spam=13; in_ham=7}
|> Map.add "florence" { in_spam=0; in_ham=3}
|> Map.add "florida" { in_spam=5; in_ham=9}
|> Map.add "flow" { in_spam=4; in_ham=14}
|> Map.add "flowers" { in_spam=1; in_ham=3}
|> Map.add "flowing" { in_spam=0; in_ham=3}
|> Map.add "flows" { in_spam=0; in_ham=3}
|> Map.add "fluctuations" { in_spam=0; in_ham=3}
|> Map.add "fluid" { in_spam=0; in_ham=6}
|> Map.add "flush" { in_spam=1; in_ham=4}
|> Map.add "fly" { in_spam=4; in_ham=7}
|> Map.add "flying" { in_spam=0; in_ham=8}
|> Map.add "fmi" { in_spam=0; in_ham=3}
|> Map.add "fmi's" { in_spam=0; in_ham=3}
|> Map.add "fmurata" { in_spam=0; in_ham=4}
|> Map.add "foaf" { in_spam=0; in_ham=8}
|> Map.add "focal-point" { in_spam=0; in_ham=3}
|> Map.add "focus" { in_spam=3; in_ham=34}
|> Map.add "focused" { in_spam=1; in_ham=20}
|> Map.add "focuses" { in_spam=0; in_ham=3}
|> Map.add "focusing" { in_spam=1; in_ham=2}
|> Map.add "foeman" { in_spam=0; in_ham=3}
|> Map.add "fog" { in_spam=0; in_ham=4}
|> Map.add "fogbugz" { in_spam=0; in_ham=4}
|> Map.add "fogcreek" { in_spam=0; in_ham=3}
|> Map.add "fold" { in_spam=1; in_ham=4}
|> Map.add "folde" { in_spam=0; in_ham=6}
|> Map.add "folder" { in_spam=0; in_ham=103}
|> Map.add "folderchange" { in_spam=0; in_ham=4}
|> Map.add "folders" { in_spam=0; in_ham=35}
|> Map.add "folding" { in_spam=1; in_ham=2}
|> Map.add "folds" { in_spam=0; in_ham=4}
|> Map.add "folk" { in_spam=0; in_ham=9}
|> Map.add "folks" { in_spam=3; in_ham=75}
|> Map.add "follow" { in_spam=30; in_ham=23}
|> Map.add "followed" { in_spam=13; in_ham=19}
|> Map.add "followers" { in_spam=2; in_ham=2}
|> Map.add "following" { in_spam=63; in_ham=102}
|> Map.add "follows" { in_spam=3; in_ham=14}
|> Map.add "followup" { in_spam=0; in_ham=6}
|> Map.add "fond" { in_spam=0; in_ham=4}
|> Map.add "font" { in_spam=210; in_ham=14}
|> Map.add "font-family" { in_spam=33; in_ham=3}
|> Map.add "font-size" { in_spam=36; in_ham=3}
|> Map.add "font-style" { in_spam=4; in_ham=1}
|> Map.add "font-weight" { in_spam=21; in_ham=2}
|> Map.add "fonts" { in_spam=0; in_ham=7}
|> Map.add "foo" { in_spam=0; in_ham=4}
|> Map.add "food" { in_spam=4; in_ham=17}
|> Map.add "fool" { in_spam=1; in_ham=7}
|> Map.add "fooled" { in_spam=1; in_ham=2}
|> Map.add "foolish" { in_spam=1; in_ham=3}
|> Map.add "fools-errant" { in_spam=0; in_ham=3}
|> Map.add "foot" { in_spam=0; in_ham=17}
|> Map.add "footage" { in_spam=0; in_ham=5}
|> Map.add "football" { in_spam=0; in_ham=7}
|> Map.add "footer" { in_spam=5; in_ham=3}
|> Map.add "fops" { in_spam=0; in_ham=6}
|> Map.add "for" { in_spam=367; in_ham=1536}
|> Map.add "forbes" { in_spam=0; in_ham=11}
|> Map.add "forbid" { in_spam=0; in_ham=3}
|> Map.add "forbidden" { in_spam=1; in_ham=5}
|> Map.add "forbids" { in_spam=2; in_ham=2}
|> Map.add "force" { in_spam=10; in_ham=62}
|> Map.add "forced" { in_spam=4; in_ham=21}
|> Map.add "forces" { in_spam=5; in_ham=30}
|> Map.add "forcibly" { in_spam=0; in_ham=4}
|> Map.add "forcing" { in_spam=0; in_ham=8}
|> Map.add "ford" { in_spam=0; in_ham=5}
|> Map.add "foreach" { in_spam=0; in_ham=8}
|> Map.add "forecast" { in_spam=0; in_ham=4}
|> Map.add "foreground" { in_spam=0; in_ham=3}
|> Map.add "foreign" { in_spam=22; in_ham=24}
|> Map.add "foremost" { in_spam=1; in_ham=2}
|> Map.add "foresaw" { in_spam=0; in_ham=6}
|> Map.add "foreseeable" { in_spam=0; in_ham=3}
|> Map.add "forest" { in_spam=1; in_ham=8}
|> Map.add "forests" { in_spam=2; in_ham=5}
|> Map.add "forever" { in_spam=7; in_ham=16}
|> Map.add "forge" { in_spam=2; in_ham=5}
|> Map.add "forged" { in_spam=0; in_ham=9}
|> Map.add "forges" { in_spam=0; in_ham=3}
|> Map.add "forget" { in_spam=11; in_ham=19}
|> Map.add "forging" { in_spam=0; in_ham=7}
|> Map.add "forgive" { in_spam=1; in_ham=4}
|> Map.add "forgone" { in_spam=0; in_ham=4}
|> Map.add "forgot" { in_spam=0; in_ham=22}
|> Map.add "forgotten" { in_spam=0; in_ham=9}
|> Map.add "fork" { in_spam=0; in_ham=208}
|> Map.add "fork-admin" { in_spam=0; in_ham=68}
|> Map.add "fork-archive" { in_spam=0; in_ham=3}
|> Map.add "forked" { in_spam=0; in_ham=4}
|> Map.add "forkers" { in_spam=0; in_ham=3}
|> Map.add "forking" { in_spam=4; in_ham=4}
|> Map.add "forks" { in_spam=0; in_ham=4}
|> Map.add "form" { in_spam=128; in_ham=66}
|> Map.add "formal" { in_spam=5; in_ham=8}
|> Map.add "formally" { in_spam=1; in_ham=4}
|> Map.add "format" { in_spam=8; in_ham=39}
|> Map.add "formating" { in_spam=0; in_ham=3}
|> Map.add "formation" { in_spam=3; in_ham=7}
|> Map.add "formative" { in_spam=3; in_ham=7}
|> Map.add "formats" { in_spam=0; in_ham=8}
|> Map.add "formatting" { in_spam=0; in_ham=6}
|> Map.add "formed" { in_spam=1; in_ham=9}
|> Map.add "former" { in_spam=6; in_ham=34}
|> Map.add "formerly" { in_spam=2; in_ham=9}
|> Map.add "forming" { in_spam=4; in_ham=3}
|> Map.add "forms" { in_spam=17; in_ham=25}
|> Map.add "forms-based" { in_spam=0; in_ham=3}
|> Map.add "formula" { in_spam=10; in_ham=1}
|> Map.add "fort" { in_spam=7; in_ham=3}
|> Map.add "fortean" { in_spam=0; in_ham=3}
|> Map.add "forteana" { in_spam=0; in_ham=11}
|> Map.add "forth" { in_spam=1; in_ham=14}
|> Map.add "forthcoming" { in_spam=0; in_ham=4}
|> Map.add "forthrightly" { in_spam=1; in_ham=2}
|> Map.add "fortnight" { in_spam=0; in_ham=3}
|> Map.add "fortran" { in_spam=0; in_ham=3}
|> Map.add "fortunate" { in_spam=4; in_ham=2}
|> Map.add "fortunately" { in_spam=1; in_ham=7}
|> Map.add "fortune" { in_spam=25; in_ham=11}
|> Map.add "fortunes" { in_spam=6; in_ham=1}
|> Map.add "forty" { in_spam=8; in_ham=1}
|> Map.add "forum" { in_spam=7; in_ham=13}
|> Map.add "forum's" { in_spam=0; in_ham=6}
|> Map.add "forums" { in_spam=0; in_ham=4}
|> Map.add "forward" { in_spam=26; in_ham=42}
|> Map.add "forwarded" { in_spam=4; in_ham=34}
|> Map.add "forwarded-by" { in_spam=0; in_ham=16}
|> Map.add "forwarding" { in_spam=2; in_ham=16}
|> Map.add "forwards" { in_spam=0; in_ham=4}
|> Map.add "forwcomps" { in_spam=0; in_ham=3}
|> Map.add "fought" { in_spam=0; in_ham=7}
|> Map.add "foul" { in_spam=0; in_ham=4}
|> Map.add "found" { in_spam=24; in_ham=250}
|> Map.add "foundation" { in_spam=1; in_ham=13}
|> Map.add "foundations" { in_spam=3; in_ham=5}
|> Map.add "founded" { in_spam=4; in_ham=12}
|> Map.add "founder" { in_spam=0; in_ham=14}
|> Map.add "founding" { in_spam=3; in_ham=9}
|> Map.add "four" { in_spam=14; in_ham=56}
|> Map.add "fournier" { in_spam=0; in_ham=6}
|> Map.add "fourth" { in_spam=1; in_ham=18}
|> Map.add "fox" { in_spam=0; in_ham=14}
|> Map.add "fox's" { in_spam=0; in_ham=4}
|> Map.add "fpp" { in_spam=1; in_ham=2}
|> Map.add "fps" { in_spam=4; in_ham=9}
|> Map.add "fraction" { in_spam=4; in_ham=2}
|> Map.add "fragile" { in_spam=1; in_ham=4}
|> Map.add "frailties" { in_spam=0; in_ham=3}
|> Map.add "frame" { in_spam=3; in_ham=12}
|> Map.add "frames" { in_spam=1; in_ham=3}
|> Map.add "framework" { in_spam=0; in_ham=12}
|> Map.add "fran" { in_spam=2; in_ham=2}
|> Map.add "france" { in_spam=9; in_ham=32}
|> Map.add "france's" { in_spam=0; in_ham=3}
|> Map.add "franchise" { in_spam=3; in_ham=6}
|> Map.add "francisco" { in_spam=1; in_ham=19}
|> Map.add "frank" { in_spam=0; in_ham=12}
|> Map.add "franklin" { in_spam=0; in_ham=7}
|> Map.add "frankly" { in_spam=3; in_ham=12}
|> Map.add "franza" { in_spam=0; in_ham=6}
|> Map.add "fraud" { in_spam=1; in_ham=4}
|> Map.add "freaking" { in_spam=0; in_ham=9}
|> Map.add "fred" { in_spam=6; in_ham=3}
|> Map.add "frederick" { in_spam=0; in_ham=3}
|> Map.add "free" { in_spam=209; in_ham=308}
|> Map.add "free-form" { in_spam=0; in_ham=5}
|> Map.add "freebsd" { in_spam=8; in_ham=20}
|> Map.add "freedom" { in_spam=12; in_ham=30}
|> Map.add "freedoms" { in_spam=0; in_ham=3}
|> Map.add "freely" { in_spam=0; in_ham=6}
|> Map.add "freenet" { in_spam=0; in_ham=3}
|> Map.add "freeserve" { in_spam=0; in_ham=4}
|> Map.add "freetype" { in_spam=0; in_ham=4}
|> Map.add "freetype-" { in_spam=0; in_ham=3}
|> Map.add "freeware" { in_spam=0; in_ham=3}
|> Map.add "freeze" { in_spam=3; in_ham=10}
|> Map.add "freight" { in_spam=1; in_ham=3}
|> Map.add "french" { in_spam=4; in_ham=45}
|> Map.add "frequency" { in_spam=2; in_ham=4}
|> Map.add "frequently" { in_spam=3; in_ham=22}
|> Map.add "fresh" { in_spam=6; in_ham=16}
|> Map.add "freshly" { in_spam=0; in_ham=4}
|> Map.add "freshmeat" { in_spam=0; in_ham=3}
|> Map.add "freshrpm" { in_spam=0; in_ham=5}
|> Map.add "freshrpms" { in_spam=0; in_ham=254}
|> Map.add "fri" { in_spam=0; in_ham=73}
|> Map.add "friday" { in_spam=0; in_ham=45}
|> Map.add "fried" { in_spam=0; in_ham=3}
|> Map.add "friend" { in_spam=30; in_ham=34}
|> Map.add "friendly" { in_spam=2; in_ham=11}
|> Map.add "friends" { in_spam=32; in_ham=63}
|> Map.add "friendships" { in_spam=0; in_ham=3}
|> Map.add "frightening" { in_spam=0; in_ham=4}
|> Map.add "frihet" { in_spam=0; in_ham=9}
|> Map.add "frii" { in_spam=0; in_ham=3}
|> Map.add "fringe" { in_spam=0; in_ham=5}
|> Map.add "fringes" { in_spam=0; in_ham=3}
|> Map.add "fro" { in_spam=1; in_ham=2}
|> Map.add "frogstone" { in_spam=0; in_ham=8}
|> Map.add "from" { in_spam=301; in_ham=1139}
|> Map.add "front" { in_spam=11; in_ham=31}
|> Map.add "frontiers" { in_spam=1; in_ham=3}
|> Map.add "frontpage" { in_spam=37; in_ham=0}
|> Map.add "fronts" { in_spam=4; in_ham=3}
|> Map.add "frozen" { in_spam=0; in_ham=6}
|> Map.add "frugaljoe" { in_spam=6; in_ham=0}
|> Map.add "fruit" { in_spam=1; in_ham=4}
|> Map.add "fruitful" { in_spam=0; in_ham=4}
|> Map.add "fruits" { in_spam=2; in_ham=4}
|> Map.add "frustrate" { in_spam=1; in_ham=2}
|> Map.add "frustrated" { in_spam=3; in_ham=5}
|> Map.add "frustrating" { in_spam=7; in_ham=3}
|> Map.add "fry" { in_spam=0; in_ham=6}
|> Map.add "fsf" { in_spam=0; in_ham=5}
|> Map.add "ftam" { in_spam=0; in_ham=6}
|> Map.add "ftc" { in_spam=0; in_ham=4}
|> Map.add "ften" { in_spam=0; in_ham=3}
|> Map.add "ftoc" { in_spam=0; in_ham=24}
|> Map.add "ftp" { in_spam=3; in_ham=31}
|> Map.add "ftrain" { in_spam=0; in_ham=3}
|> Map.add "fu-berlin" { in_spam=0; in_ham=8}
|> Map.add "fucking" { in_spam=3; in_ham=16}
|> Map.add "fuel" { in_spam=3; in_ham=10}
|> Map.add "full" { in_spam=42; in_ham=75}
|> Map.add "full-time" { in_spam=1; in_ham=2}
|> Map.add "fuller" { in_spam=0; in_ham=3}
|> Map.add "fullscreen" { in_spam=0; in_ham=3}
|> Map.add "fully" { in_spam=22; in_ham=44}
|> Map.add "fulton" { in_spam=0; in_ham=3}
|> Map.add "fun" { in_spam=14; in_ham=51}
|> Map.add "func" { in_spam=0; in_ham=3}
|> Map.add "function" { in_spam=7; in_ham=44}
|> Map.add "functional" { in_spam=4; in_ham=8}
|> Map.add "functions" { in_spam=1; in_ham=18}
|> Map.add "fund" { in_spam=35; in_ham=16}
|> Map.add "fundamental" { in_spam=1; in_ham=15}
|> Map.add "fundamentals" { in_spam=6; in_ham=0}
|> Map.add "funded" { in_spam=0; in_ham=3}
|> Map.add "funding" { in_spam=8; in_ham=12}
|> Map.add "funds" { in_spam=18; in_ham=10}
|> Map.add "funeral" { in_spam=1; in_ham=3}
|> Map.add "funet" { in_spam=0; in_ham=4}
|> Map.add "funky" { in_spam=0; in_ham=5}
|> Map.add "funny" { in_spam=1; in_ham=41}
|> Map.add "fur" { in_spam=0; in_ham=3}
|> Map.add "furious" { in_spam=2; in_ham=3}
|> Map.add "furnish" { in_spam=10; in_ham=0}
|> Map.add "further" { in_spam=72; in_ham=64}
|> Map.add "furthering" { in_spam=1; in_ham=2}
|> Map.add "furthermore" { in_spam=7; in_ham=6}
|> Map.add "fusion" { in_spam=0; in_ham=3}
|> Map.add "futily" { in_spam=0; in_ham=3}
|> Map.add "future" { in_spam=87; in_ham=92}
|> Map.add "fuzzy" { in_spam=0; in_ham=7}
|> Map.add "fwiw" { in_spam=0; in_ham=8}
|> Map.add "fyi" { in_spam=1; in_ham=6}
|> Map.add "gab" { in_spam=1; in_ham=3}
|> Map.add "gads" { in_spam=0; in_ham=3}
|> Map.add "gail" { in_spam=0; in_ham=5}
|> Map.add "gain" { in_spam=12; in_ham=30}
|> Map.add "gained" { in_spam=4; in_ham=11}
|> Map.add "gains" { in_spam=3; in_ham=7}
|> Map.add "gallery" { in_spam=1; in_ham=4}
|> Map.add "gamble" { in_spam=7; in_ham=3}
|> Map.add "gambling" { in_spam=8; in_ham=4}
|> Map.add "game" { in_spam=9; in_ham=57}
|> Map.add "games" { in_spam=8; in_ham=29}
|> Map.add "gaming" { in_spam=0; in_ham=4}
|> Map.add "gamixer" { in_spam=0; in_ham=4}
|> Map.add "gang-bang" { in_spam=0; in_ham=3}
|> Map.add "gangs" { in_spam=0; in_ham=3}
|> Map.add "ganz" { in_spam=0; in_ham=3}
|> Map.add "gap" { in_spam=0; in_ham=14}
|> Map.add "garage" { in_spam=0; in_ham=4}
|> Map.add "garbage" { in_spam=1; in_ham=4}
|> Map.add "garden" { in_spam=3; in_ham=7}
|> Map.add "gardner" { in_spam=0; in_ham=3}
|> Map.add "garrigues" { in_spam=0; in_ham=54}
|> Map.add "gary" { in_spam=0; in_ham=90}
|> Map.add "gary's" { in_spam=0; in_ham=3}
|> Map.add "garym" { in_spam=0; in_ham=53}
|> Map.add "gas" { in_spam=1; in_ham=16}
|> Map.add "gases" { in_spam=0; in_ham=4}
|> Map.add "gate" { in_spam=0; in_ham=8}
|> Map.add "gateway" { in_spam=2; in_ham=2}
|> Map.add "gather" { in_spam=0; in_ham=5}
|> Map.add "gathered" { in_spam=1; in_ham=4}
|> Map.add "gathering" { in_spam=0; in_ham=6}
|> Map.add "gave" { in_spam=10; in_ham=30}
|> Map.add "gay" { in_spam=0; in_ham=16}
|> Map.add "gaybars" { in_spam=0; in_ham=4}
|> Map.add "gays" { in_spam=0; in_ham=7}
|> Map.add "gazing" { in_spam=0; in_ham=3}
|> Map.add "gbayes" { in_spam=0; in_ham=5}
|> Map.add "gbolcer" { in_spam=0; in_ham=9}
|> Map.add "gcc" { in_spam=0; in_ham=14}
|> Map.add "gdc" { in_spam=0; in_ham=4}
|> Map.add "ge-energy" { in_spam=5; in_ham=0}
|> Map.add "gear" { in_spam=0; in_ham=5}
|> Map.add "geared" { in_spam=1; in_ham=2}
|> Map.add "gecko" { in_spam=0; in_ham=3}
|> Map.add "gee" { in_spam=0; in_ham=3}
|> Map.add "geege" { in_spam=0; in_ham=47}
|> Map.add "geege's" { in_spam=0; in_ham=4}
|> Map.add "geek" { in_spam=2; in_ham=120}
|> Map.add "geeks" { in_spam=0; in_ham=9}
|> Map.add "geeks'" { in_spam=0; in_ham=3}
|> Map.add "geez" { in_spam=2; in_ham=4}
|> Map.add "geforce" { in_spam=0; in_ham=5}
|> Map.add "gel" { in_spam=1; in_ham=3}
|> Map.add "gen" { in_spam=8; in_ham=6}
|> Map.add "gender" { in_spam=1; in_ham=5}
|> Map.add "gene" { in_spam=0; in_ham=3}
|> Map.add "general" { in_spam=38; in_ham=76}
|> Map.add "generalize" { in_spam=0; in_ham=3}
|> Map.add "generally" { in_spam=0; in_ham=41}
|> Map.add "generals" { in_spam=1; in_ham=3}
|> Map.add "generate" { in_spam=19; in_ham=26}
|> Map.add "generated" { in_spam=3; in_ham=44}
|> Map.add "generates" { in_spam=1; in_ham=7}
|> Map.add "generating" { in_spam=5; in_ham=7}
|> Map.add "generation" { in_spam=3; in_ham=24}
|> Map.add "generations" { in_spam=1; in_ham=7}
|> Map.add "generator" { in_spam=68; in_ham=9}
|> Map.add "generators" { in_spam=0; in_ham=3}
|> Map.add "generic" { in_spam=2; in_ham=8}
|> Map.add "generically" { in_spam=0; in_ham=3}
|> Map.add "generous" { in_spam=0; in_ham=3}
|> Map.add "genetic" { in_spam=0; in_ham=3}
|> Map.add "genetically" { in_spam=0; in_ham=3}
|> Map.add "geneva" { in_spam=11; in_ham=3}
|> Map.add "genom" { in_spam=0; in_ham=9}
|> Map.add "genome" { in_spam=0; in_ham=5}
|> Map.add "genre" { in_spam=1; in_ham=2}
|> Map.add "gentle" { in_spam=1; in_ham=2}
|> Map.add "gentlemen" { in_spam=0; in_ham=6}
|> Map.add "gentoo" { in_spam=0; in_ham=5}
|> Map.add "genuine" { in_spam=0; in_ham=5}
|> Map.add "genuinely" { in_spam=3; in_ham=1}
|> Map.add "geocities" { in_spam=3; in_ham=3}
|> Map.add "geodesic" { in_spam=0; in_ham=3}
|> Map.add "geographic" { in_spam=1; in_ham=3}
|> Map.add "geographical" { in_spam=1; in_ham=2}
|> Map.add "geography" { in_spam=0; in_ham=3}
|> Map.add "geological" { in_spam=0; in_ham=4}
|> Map.add "geometry" { in_spam=0; in_ham=22}
|> Map.add "george" { in_spam=5; in_ham=35}
|> Map.add "georgia" { in_spam=8; in_ham=0}
|> Map.add "gerg" { in_spam=0; in_ham=7}
|> Map.add "german" { in_spam=2; in_ham=7}
|> Map.add "germans" { in_spam=0; in_ham=3}
|> Map.add "germany" { in_spam=7; in_ham=16}
|> Map.add "gerontocracy" { in_spam=0; in_ham=9}
|> Map.add "gerry" { in_spam=0; in_ham=4}
|> Map.add "gestappo" { in_spam=0; in_ham=3}
|> Map.add "gestures" { in_spam=0; in_ham=3}
|> Map.add "get" { in_spam=171; in_ham=698}
|> Map.add "gets" { in_spam=11; in_ham=99}
|> Map.add "getting" { in_spam=24; in_ham=165}
|> Map.add "ghetto" { in_spam=2; in_ham=3}
|> Map.add "ghost" { in_spam=5; in_ham=6}
|> Map.add "ghosting" { in_spam=0; in_ham=4}
|> Map.add "ghz" { in_spam=1; in_ham=6}
|> Map.add "giant" { in_spam=2; in_ham=7}
|> Map.add "giants" { in_spam=0; in_ham=7}
|> Map.add "gibbon" { in_spam=0; in_ham=41}
|> Map.add "gibson" { in_spam=0; in_ham=11}
|> Map.add "gif" { in_spam=92; in_ham=40}
|> Map.add "gift" { in_spam=9; in_ham=8}
|> Map.add "gifts" { in_spam=5; in_ham=0}
|> Map.add "gigantic" { in_spam=1; in_ham=2}
|> Map.add "gigs" { in_spam=0; in_ham=3}
|> Map.add "gillmor" { in_spam=0; in_ham=4}
|> Map.add "gillmor's" { in_spam=0; in_ham=4}
|> Map.add "ginger" { in_spam=1; in_ham=4}
|> Map.add "gingras" { in_spam=0; in_ham=13}
|> Map.add "girl" { in_spam=4; in_ham=23}
|> Map.add "girls" { in_spam=12; in_ham=12}
|> Map.add "give" { in_spam=57; in_ham=195}
|> Map.add "given" { in_spam=23; in_ham=92}
|> Map.add "gives" { in_spam=2; in_ham=79}
|> Map.add "giving" { in_spam=12; in_ham=52}
|> Map.add "gkrellm" { in_spam=0; in_ham=4}
|> Map.add "glaciers" { in_spam=0; in_ham=8}
|> Map.add "glad" { in_spam=9; in_ham=15}
|> Map.add "gladly" { in_spam=0; in_ham=3}
|> Map.add "glance" { in_spam=0; in_ham=4}
|> Map.add "glass" { in_spam=0; in_ham=6}
|> Map.add "glasses" { in_spam=1; in_ham=4}
|> Map.add "glenn" { in_spam=0; in_ham=4}
|> Map.add "gloating" { in_spam=0; in_ham=5}
|> Map.add "glob" { in_spam=0; in_ham=4}
|> Map.add "global" { in_spam=5; in_ham=70}
|> Map.add "globally" { in_spam=0; in_ham=3}
|> Map.add "globe" { in_spam=1; in_ham=12}
|> Map.add "glorified" { in_spam=0; in_ham=3}
|> Map.add "glory" { in_spam=0; in_ham=4}
|> Map.add "glossary" { in_spam=3; in_ham=1}
|> Map.add "glossed" { in_spam=0; in_ham=3}
|> Map.add "glow" { in_spam=0; in_ham=3}
|> Map.add "glue" { in_spam=0; in_ham=5}
|> Map.add "glut" { in_spam=0; in_ham=3}
|> Map.add "gmane" { in_spam=0; in_ham=3}
|> Map.add "gmt" { in_spam=2; in_ham=57}
|> Map.add "gnat" { in_spam=0; in_ham=10}
|> Map.add "gnome" { in_spam=0; in_ham=18}
|> Map.add "gnomecore" { in_spam=0; in_ham=3}
|> Map.add "gnomehide" { in_spam=0; in_ham=3}
|> Map.add "gnu" { in_spam=0; in_ham=92}
|> Map.add "gnupg" { in_spam=0; in_ham=97}
|> Map.add "go-to-market" { in_spam=0; in_ham=6}
|> Map.add "goal" { in_spam=5; in_ham=30}
|> Map.add "goals" { in_spam=2; in_ham=10}
|> Map.add "goat" { in_spam=1; in_ham=2}
|> Map.add "goback" { in_spam=5; in_ham=0}
|> Map.add "god" { in_spam=11; in_ham=28}
|> Map.add "god's" { in_spam=0; in_ham=6}
|> Map.add "god-given" { in_spam=1; in_ham=2}
|> Map.add "godhra" { in_spam=0; in_ham=3}
|> Map.add "gods" { in_spam=0; in_ham=3}
|> Map.add "goes" { in_spam=15; in_ham=72}
|> Map.add "going" { in_spam=29; in_ham=189}
|> Map.add "gold" { in_spam=6; in_ham=15}
|> Map.add "golden" { in_spam=0; in_ham=7}
|> Map.add "golf" { in_spam=1; in_ham=5}
|> Map.add "golux" { in_spam=0; in_ham=6}
|> Map.add "gone" { in_spam=10; in_ham=33}
|> Map.add "goneforgood" { in_spam=5; in_ham=0}
|> Map.add "gonna" { in_spam=0; in_ham=11}
|> Map.add "gonze" { in_spam=0; in_ham=6}
|> Map.add "good" { in_spam=48; in_ham=334}
|> Map.add "goodbye" { in_spam=2; in_ham=9}
|> Map.add "goodens" { in_spam=0; in_ham=3}
|> Map.add "goodness" { in_spam=0; in_ham=6}
|> Map.add "goods" { in_spam=2; in_ham=7}
|> Map.add "goofy" { in_spam=3; in_ham=1}
|> Map.add "google" { in_spam=0; in_ham=47}
|> Map.add "google's" { in_spam=0; in_ham=5}
|> Map.add "googling" { in_spam=0; in_ham=6}
|> Map.add "gordon" { in_spam=0; in_ham=31}
|> Map.add "gore" { in_spam=1; in_ham=6}
|> Map.add "got" { in_spam=34; in_ham=250}
|> Map.add "gothic" { in_spam=5; in_ham=0}
|> Map.add "gotta" { in_spam=0; in_ham=6}
|> Map.add "gotten" { in_spam=2; in_ham=22}
|> Map.add "gouging" { in_spam=0; in_ham=3}
|> Map.add "gov" { in_spam=4; in_ham=21}
|> Map.add "govern" { in_spam=0; in_ham=4}
|> Map.add "governance" { in_spam=0; in_ham=5}
|> Map.add "governing" { in_spam=0; in_ham=3}
|> Map.add "government" { in_spam=40; in_ham=81}
|> Map.add "government's" { in_spam=0; in_ham=10}
|> Map.add "governments" { in_spam=1; in_ham=12}
|> Map.add "govt" { in_spam=0; in_ham=5}
|> Map.add "gpg" { in_spam=2; in_ham=24}
|> Map.add "gpl" { in_spam=0; in_ham=10}
|> Map.add "gprs" { in_spam=0; in_ham=5}
|> Map.add "gqj" { in_spam=0; in_ham=3}
|> Map.add "grab" { in_spam=5; in_ham=10}
|> Map.add "grabbed" { in_spam=0; in_ham=7}
|> Map.add "grabbing" { in_spam=3; in_ham=1}
|> Map.add "grace" { in_spam=0; in_ham=3}
|> Map.add "gracefully" { in_spam=0; in_ham=3}
|> Map.add "grade" { in_spam=4; in_ham=3}
|> Map.add "grades" { in_spam=0; in_ham=4}
|> Map.add "gradually" { in_spam=0; in_ham=4}
|> Map.add "graduate" { in_spam=3; in_ham=4}
|> Map.add "graduates" { in_spam=0; in_ham=5}
|> Map.add "graham" { in_spam=2; in_ham=4}
|> Map.add "graham's" { in_spam=0; in_ham=5}
|> Map.add "grain" { in_spam=1; in_ham=4}
|> Map.add "grams" { in_spam=0; in_ham=3}
|> Map.add "grand" { in_spam=13; in_ham=8}
|> Map.add "grant" { in_spam=4; in_ham=10}
|> Map.add "granted" { in_spam=2; in_ham=23}
|> Map.add "granting" { in_spam=0; in_ham=5}
|> Map.add "grants" { in_spam=3; in_ham=11}
|> Map.add "granular" { in_spam=0; in_ham=6}
|> Map.add "graphical" { in_spam=3; in_ham=2}
|> Map.add "graphics" { in_spam=4; in_ham=10}
|> Map.add "grass" { in_spam=1; in_ham=7}
|> Map.add "grata" { in_spam=0; in_ham=3}
|> Map.add "grateful" { in_spam=1; in_ham=6}
|> Map.add "gratis" { in_spam=0; in_ham=5}
|> Map.add "gratuite" { in_spam=4; in_ham=1}
|> Map.add "grave" { in_spam=0; in_ham=3}
|> Map.add "gray" { in_spam=4; in_ham=2}
|> Map.add "great" { in_spam=63; in_ham=165}
|> Map.add "greater" { in_spam=7; in_ham=45}
|> Map.add "greatest" { in_spam=8; in_ham=7}
|> Map.add "greatly" { in_spam=2; in_ham=13}
|> Map.add "greed" { in_spam=3; in_ham=3}
|> Map.add "greedy" { in_spam=7; in_ham=0}
|> Map.add "green" { in_spam=9; in_ham=23}
|> Map.add "green'" { in_spam=0; in_ham=3}
|> Map.add "greenhouse" { in_spam=0; in_ham=4}
|> Map.add "greenzer" { in_spam=6; in_ham=0}
|> Map.add "greeting" { in_spam=2; in_ham=2}
|> Map.add "greetings" { in_spam=1; in_ham=6}
|> Map.add "greg" { in_spam=0; in_ham=49}
|> Map.add "gregory" { in_spam=0; in_ham=19}
|> Map.add "grep" { in_spam=0; in_ham=21}
|> Map.add "grepping" { in_spam=0; in_ham=3}
|> Map.add "grew" { in_spam=1; in_ham=11}
|> Map.add "grey" { in_spam=1; in_ham=5}
|> Map.add "grid" { in_spam=0; in_ham=4}
|> Map.add "grief" { in_spam=0; in_ham=5}
|> Map.add "grievances" { in_spam=0; in_ham=5}
|> Map.add "grim" { in_spam=0; in_ham=4}
|> Map.add "grinch" { in_spam=0; in_ham=3}
|> Map.add "grinding" { in_spam=1; in_ham=3}
|> Map.add "grips" { in_spam=0; in_ham=3}
|> Map.add "grok" { in_spam=0; in_ham=7}
|> Map.add "grokked" { in_spam=0; in_ham=5}
|> Map.add "groove" { in_spam=0; in_ham=3}
|> Map.add "gross" { in_spam=0; in_ham=5}
|> Map.add "grossi" { in_spam=0; in_ham=6}
|> Map.add "grossly" { in_spam=3; in_ham=2}
|> Map.add "ground" { in_spam=0; in_ham=35}
|> Map.add "grounds" { in_spam=0; in_ham=3}
|> Map.add "group" { in_spam=53; in_ham=303}
|> Map.add "groups" { in_spam=3; in_ham=140}
|> Map.add "grove" { in_spam=0; in_ham=4}
|> Map.add "grow" { in_spam=6; in_ham=14}
|> Map.add "growing" { in_spam=26; in_ham=76}
|> Map.add "grown" { in_spam=2; in_ham=9}
|> Map.add "grows" { in_spam=0; in_ham=4}
|> Map.add "growth" { in_spam=5; in_ham=20}
|> Map.add "grub" { in_spam=0; in_ham=4}
|> Map.add "grumbled" { in_spam=7; in_ham=0}
|> Map.add "gsm" { in_spam=0; in_ham=4}
|> Map.add "gsolb" { in_spam=0; in_ham=87}
|> Map.add "gst" { in_spam=0; in_ham=4}
|> Map.add "gstreamer" { in_spam=0; in_ham=3}
|> Map.add "gtk" { in_spam=0; in_ham=10}
|> Map.add "guarantee" { in_spam=33; in_ham=17}
|> Map.add "guaranteed" { in_spam=57; in_ham=7}
|> Map.add "guarantees" { in_spam=7; in_ham=4}
|> Map.add "guard" { in_spam=0; in_ham=6}
|> Map.add "guardian" { in_spam=2; in_ham=15}
|> Map.add "guards" { in_spam=2; in_ham=2}
|> Map.add "guess" { in_spam=0; in_ham=99}
|> Map.add "guessed" { in_spam=2; in_ham=4}
|> Map.add "guessing" { in_spam=0; in_ham=4}

