open Database
let db = Map.empty 
|> Map.add "0,,1" { in_spam=0; in_ham=9}
|> Map.add "0.00" { in_spam=0; in_ham=19}
|> Map.add "0.000" { in_spam=0; in_ham=11}
|> Map.add "0.01" { in_spam=0; in_ham=15}
|> Map.add "0.02" { in_spam=0; in_ham=8}
|> Map.add "0.03" { in_spam=0; in_ham=9}
|> Map.add "0.06" { in_spam=0; in_ham=8}
|> Map.add "0.5" { in_spam=0; in_ham=12}
|> Map.add "0.99" { in_spam=1; in_ham=8}
|> Map.add "0000" { in_spam=102; in_ham=23}
|> Map.add "000000" { in_spam=135; in_ham=3}
|> Map.add "000066" { in_spam=21; in_ham=0}
|> Map.add "000080" { in_spam=21; in_ham=0}
|> Map.add "002" { in_spam=12; in_ham=2}
|> Map.add "007" { in_spam=13; in_ham=4}
|> Map.add "01," { in_spam=0; in_ham=19}
|> Map.add "01." { in_spam=21; in_ham=11}
|> Map.add "0100" { in_spam=0; in_ham=10}
|> Map.add "0100," { in_spam=0; in_ham=27}
|> Map.add "02," { in_spam=0; in_ham=46}
|> Map.add "02." { in_spam=21; in_ham=13}
|> Map.add "0200" { in_spam=1; in_ham=29}
|> Map.add "0200," { in_spam=0; in_ham=34}
|> Map.add "02131" { in_spam=0; in_ham=41}
|> Map.add "03," { in_spam=1; in_ham=14}
|> Map.add "03." { in_spam=13; in_ham=7}
|> Map.add "04," { in_spam=0; in_ham=13}
|> Map.add "04." { in_spam=14; in_ham=4}
|> Map.add "0400" { in_spam=1; in_ham=44}
|> Map.add "0400," { in_spam=0; in_ham=31}
|> Map.add "05," { in_spam=0; in_ham=34}
|> Map.add "05." { in_spam=12; in_ham=3}
|> Map.add "0500" { in_spam=0; in_ham=58}
|> Map.add "0500," { in_spam=0; in_ham=10}
|> Map.add "06," { in_spam=0; in_ham=25}
|> Map.add "06." { in_spam=9; in_ham=6}
|> Map.add "07," { in_spam=0; in_ham=15}
|> Map.add "07." { in_spam=8; in_ham=11}
|> Map.add "0700" { in_spam=0; in_ham=59}
|> Map.add "0700," { in_spam=0; in_ham=24}
|> Map.add "08," { in_spam=0; in_ham=14}
|> Map.add "08." { in_spam=10; in_ham=9}
|> Map.add "08039" { in_spam=0; in_ham=42}
|> Map.add "09," { in_spam=0; in_ham=10}
|> Map.add "09." { in_spam=7; in_ham=6}
|> Map.add "1,000" { in_spam=18; in_ham=9}
|> Map.add "1,400" { in_spam=3; in_ham=6}
|> Map.add "1.0" { in_spam=7; in_ham=22}
|> Map.add "1.0.6" { in_spam=0; in_ham=73}
|> Map.add "1.0.7" { in_spam=0; in_ham=19}
|> Map.add "1.4" { in_spam=0; in_ham=8}
|> Map.add "1.5" { in_spam=7; in_ham=12}
|> Map.add "10%" { in_spam=12; in_ham=14}
|> Map.add "10," { in_spam=2; in_ham=13}
|> Map.add "10,000" { in_spam=22; in_ham=4}
|> Map.add "10." { in_spam=9; in_ham=9}
|> Map.add "100" { in_spam=55; in_ham=64}
|> Map.add "100%" { in_spam=142; in_ham=40}
|> Map.add "100,000" { in_spam=22; in_ham=5}
|> Map.add "1000" { in_spam=13; in_ham=18}
|> Map.add "10000" { in_spam=1; in_ham=8}
|> Map.add "101" { in_spam=17; in_ham=7}
|> Map.add "101." { in_spam=16; in_ham=1}
|> Map.add "1024" { in_spam=0; in_ham=15}
|> Map.add "105" { in_spam=26; in_ham=2}
|> Map.add "106" { in_spam=7; in_ham=9}
|> Map.add "11," { in_spam=2; in_ham=19}
|> Map.add "11." { in_spam=6; in_ham=14}
|> Map.add "110" { in_spam=9; in_ham=3}
|> Map.add "111" { in_spam=11; in_ham=2}
|> Map.add "111111" { in_spam=19; in_ham=1}
|> Map.add "115" { in_spam=12; in_ham=2}
|> Map.add "12." { in_spam=5; in_ham=14}
|> Map.add "12.6" { in_spam=0; in_ham=9}
|> Map.add "120" { in_spam=5; in_ham=7}
|> Map.add "123" { in_spam=2; in_ham=7}
|> Map.add "125" { in_spam=5; in_ham=7}
|> Map.add "1252" { in_spam=46; in_ham=2}
|> Map.add "130" { in_spam=5; in_ham=5}
|> Map.add "132" { in_spam=11; in_ham=2}
|> Map.add "145" { in_spam=9; in_ham=3}
|> Map.add "149" { in_spam=15; in_ham=0}
|> Map.add "15%" { in_spam=30; in_ham=3}
|> Map.add "15," { in_spam=1; in_ham=7}
|> Map.add "15." { in_spam=2; in_ham=7}
|> Map.add "150" { in_spam=24; in_ham=13}
|> Map.add "151" { in_spam=16; in_ham=2}
|> Map.add "16," { in_spam=3; in_ham=17}
|> Map.add "161" { in_spam=5; in_ham=5}
|> Map.add "17," { in_spam=1; in_ham=12}
|> Map.add "19," { in_spam=2; in_ham=12}
|> Map.add "1930" { in_spam=0; in_ham=10}
|> Map.add "1934853" { in_spam=0; in_ham=9}
|> Map.add "1980" { in_spam=0; in_ham=10}
|> Map.add "1990" { in_spam=1; in_ham=12}
|> Map.add "1993" { in_spam=3; in_ham=6}
|> Map.add "1995" { in_spam=1; in_ham=11}
|> Map.add "1996" { in_spam=0; in_ham=8}
|> Map.add "1996." { in_spam=4; in_ham=6}
|> Map.add "1997" { in_spam=4; in_ham=60}
|> Map.add "1998" { in_spam=4; in_ham=9}
|> Map.add "1998," { in_spam=2; in_ham=8}
|> Map.add "1999" { in_spam=3; in_ham=23}
|> Map.add "1999," { in_spam=3; in_ham=10}
|> Map.add "2.0" { in_spam=2; in_ham=14}
|> Map.add "2.14" { in_spam=0; in_ham=13}
|> Map.add "2.2" { in_spam=0; in_ham=41}
|> Map.add "2.31" { in_spam=0; in_ham=8}
|> Map.add "2.4" { in_spam=0; in_ham=11}
|> Map.add "2.4.18" { in_spam=0; in_ham=51}
|> Map.add "2.40" { in_spam=0; in_ham=22}
|> Map.add "2.41" { in_spam=0; in_ham=23}
|> Map.add "2.5" { in_spam=2; in_ham=40}
|> Map.add "20%" { in_spam=37; in_ham=4}
|> Map.add "20," { in_spam=4; in_ham=14}
|> Map.add "20,000" { in_spam=8; in_ham=5}
|> Map.add "20." { in_spam=4; in_ham=8}
|> Map.add "200" { in_spam=24; in_ham=64}
|> Map.add "2000" { in_spam=15; in_ham=74}
|> Map.add "2000." { in_spam=2; in_ham=15}
|> Map.add "20000822" { in_spam=0; in_ham=34}
|> Map.add "2001" { in_spam=19; in_ham=40}
|> Map.add "2001," { in_spam=1; in_ham=21}
|> Map.add "2002" { in_spam=75; in_ham=1172}
|> Map.add "2002," { in_spam=8; in_ham=249}
|> Map.add "2002." { in_spam=9; in_ham=26}
|> Map.add "2003" { in_spam=7; in_ham=7}
|> Map.add "21," { in_spam=3; in_ham=8}
|> Map.add "2100" { in_spam=1; in_ham=12}
|> Map.add "211," { in_spam=0; in_ham=8}
|> Map.add "22," { in_spam=1; in_ham=34}
|> Map.add "220" { in_spam=5; in_ham=6}
|> Map.add "23," { in_spam=0; in_ham=31}
|> Map.add "23." { in_spam=1; in_ham=8}
|> Map.add "24." { in_spam=6; in_ham=17}
|> Map.add "245" { in_spam=13; in_ham=3}
|> Map.add "25," { in_spam=2; in_ham=16}
|> Map.add "25." { in_spam=3; in_ham=13}
|> Map.add "250" { in_spam=15; in_ham=15}
|> Map.add "255" { in_spam=7; in_ham=4}
|> Map.add "26," { in_spam=3; in_ham=15}
|> Map.add "27," { in_spam=1; in_ham=21}
|> Map.add "275" { in_spam=11; in_ham=3}
|> Map.add "28," { in_spam=2; in_ham=19}
|> Map.add "29," { in_spam=1; in_ham=12}
|> Map.add "29.99" { in_spam=25; in_ham=0}
|> Map.add "3.0" { in_spam=0; in_ham=9}
|> Map.add "3.5" { in_spam=3; in_ham=6}
|> Map.add "30%" { in_spam=30; in_ham=2}
|> Map.add "30," { in_spam=1; in_ham=18}
|> Map.add "30,000" { in_spam=11; in_ham=2}
|> Map.add "300" { in_spam=44; in_ham=27}
|> Map.add "304704" { in_spam=28; in_ham=0}
|> Map.add "31," { in_spam=1; in_ham=7}
|> Map.add "315" { in_spam=8; in_ham=4}
|> Map.add "321" { in_spam=8; in_ham=6}
|> Map.add "324" { in_spam=3; in_ham=8}
|> Map.add "3390" { in_spam=2; in_ham=106}
|> Map.add "35,000" { in_spam=3; in_ham=7}
|> Map.add "350" { in_spam=8; in_ham=16}
|> Map.add "353" { in_spam=1; in_ham=10}
|> Map.add "374" { in_spam=2; in_ham=36}
|> Map.add "386" { in_spam=1; in_ham=18}
|> Map.add "386." { in_spam=0; in_ham=19}
|> Map.add "4.0" { in_spam=46; in_ham=12}
|> Map.add "4.1" { in_spam=0; in_ham=8}
|> Map.add "400" { in_spam=22; in_ham=30}
|> Map.add "4000" { in_spam=1; in_ham=7}
|> Map.add "450" { in_spam=7; in_ham=8}
|> Map.add "5,000" { in_spam=16; in_ham=6}
|> Map.add "5.0" { in_spam=19; in_ham=6}
|> Map.add "5.1," { in_spam=1; in_ham=7}
|> Map.add "5.6.1" { in_spam=0; in_ham=17}
|> Map.add "5.8.0" { in_spam=0; in_ham=9}
|> Map.add "50%" { in_spam=21; in_ham=6}
|> Map.add "50,000" { in_spam=17; in_ham=10}
|> Map.add "500" { in_spam=51; in_ham=26}
|> Map.add "500,000" { in_spam=22; in_ham=5}
|> Map.add "5119262" { in_spam=0; in_ham=8}
|> Map.add "512" { in_spam=2; in_ham=39}
|> Map.add "540" { in_spam=23; in_ham=0}
|> Map.add "550" { in_spam=45; in_ham=7}
|> Map.add "555" { in_spam=13; in_ham=1}
|> Map.add "567" { in_spam=9; in_ham=3}
|> Map.add "60%" { in_spam=14; in_ham=2}
|> Map.add "600" { in_spam=21; in_ham=9}
|> Map.add "617" { in_spam=0; in_ham=9}
|> Map.add "666666" { in_spam=29; in_ham=0}
|> Map.add "686" { in_spam=1; in_ham=13}
|> Map.add "7,000" { in_spam=0; in_ham=10}
|> Map.add "7.0" { in_spam=6; in_ham=6}
|> Map.add "7.2" { in_spam=0; in_ham=20}
|> Map.add "7.3" { in_spam=2; in_ham=64}
|> Map.add "7.5" { in_spam=1; in_ham=9}
|> Map.add "70%" { in_spam=15; in_ham=3}
|> Map.add "700" { in_spam=9; in_ham=8}
|> Map.add "716" { in_spam=0; in_ham=36}
|> Map.add "75%" { in_spam=16; in_ham=1}
|> Map.add "78701" { in_spam=0; in_ham=35}
|> Map.add "8.0" { in_spam=1; in_ham=40}
|> Map.add "800" { in_spam=52; in_ham=9}
|> Map.add "800000" { in_spam=15; in_ham=0}
|> Map.add "802.11" { in_spam=0; in_ham=10}
|> Map.add "8212" { in_spam=9; in_ham=5}
|> Map.add "8220" { in_spam=3; in_ham=36}
|> Map.add "8221" { in_spam=2; in_ham=36}
|> Map.add "864" { in_spam=1; in_ham=7}
|> Map.add "8859" { in_spam=71; in_ham=9}
|> Map.add "90%" { in_spam=11; in_ham=15}
|> Map.add "900" { in_spam=6; in_ham=5}
|> Map.add "911" { in_spam=1; in_ham=10}
|> Map.add "936" { in_spam=0; in_ham=42}
|> Map.add "95%" { in_spam=21; in_ham=5}
|> Map.add "95," { in_spam=4; in_ham=6}
|> Map.add "99%" { in_spam=5; in_ham=5}
|> Map.add "997" { in_spam=0; in_ham=13}
|> Map.add "ADDRESS" { in_spam=15; in_ham=1}
|> Map.add "AGAIN" { in_spam=23; in_ham=0}
|> Map.add "AIDS" { in_spam=0; in_ham=11}
|> Map.add "ALB" { in_spam=0; in_ham=8}
|> Map.add "ALL" { in_spam=59; in_ham=2}
|> Map.add "ALSA" { in_spam=0; in_ham=35}
|> Map.add "ALWAYS" { in_spam=0; in_ham=9}
|> Map.add "AND" { in_spam=58; in_ham=11}
|> Map.add "ANY" { in_spam=23; in_ham=5}
|> Map.add "AOL" { in_spam=7; in_ham=12}
|> Map.add "API" { in_spam=0; in_ham=13}
|> Map.add "ARE" { in_spam=24; in_ham=2}
|> Map.add "ATM" { in_spam=0; in_ham=8}
|> Map.add "BBC" { in_spam=0; in_ham=16}
|> Map.add "BEGIN" { in_spam=0; in_ham=102}
|> Map.add "BGCOLOR" { in_spam=20; in_ham=0}
|> Map.add "BODY" { in_spam=79; in_ham=6}
|> Map.add "BORDER" { in_spam=21; in_ham=2}
|> Map.add "BTW" { in_spam=0; in_ham=52}
|> Map.add "BUSINESS" { in_spam=18; in_ham=1}
|> Map.add "CAN" { in_spam=19; in_ham=4}
|> Map.add "CASH" { in_spam=18; in_ham=0}
|> Map.add "CELLPADDING" { in_spam=17; in_ham=0}
|> Map.add "CELLSPACING" { in_spam=17; in_ham=0}
|> Map.add "CENTER" { in_spam=47; in_ham=1}
|> Map.add "CEO" { in_spam=3; in_ham=17}
|> Map.add "CET" { in_spam=0; in_ham=8}
|> Map.add "CLICK" { in_spam=69; in_ham=0}
|> Map.add "COLOR" { in_spam=37; in_ham=2}
|> Map.add "COM" { in_spam=24; in_ham=11}
|> Map.add "CONTACT" { in_spam=6; in_ham=6}
|> Map.add "CONTENT" { in_spam=19; in_ham=0}
|> Map.add "CPU" { in_spam=5; in_ham=8}
|> Map.add "CTO" { in_spam=0; in_ham=15}
|> Map.add "CVS" { in_spam=0; in_ham=48}
|> Map.add "DATA" { in_spam=6; in_ham=5}
|> Map.add "DATAPOWER" { in_spam=0; in_ham=10}
|> Map.add "DBQE" { in_spam=0; in_ham=80}
|> Map.add "DCC" { in_spam=0; in_ham=9}
|> Map.add "DISPLAY" { in_spam=1; in_ham=8}
|> Map.add "DIV" { in_spam=30; in_ham=5}
|> Map.add "DMA" { in_spam=0; in_ham=13}
|> Map.add "DMCA" { in_spam=0; in_ham=9}
|> Map.add "DNS" { in_spam=1; in_ham=23}
|> Map.add "DOCTYPE" { in_spam=36; in_ham=5}
|> Map.add "DSA" { in_spam=0; in_ham=13}
|> Map.add "DTD" { in_spam=36; in_ham=7}
|> Map.add "DVD" { in_spam=8; in_ham=24}
|> Map.add "EDT" { in_spam=0; in_ham=19}
|> Map.add "EMAIL" { in_spam=20; in_ham=2}
|> Map.add "END" { in_spam=4; in_ham=99}
|> Map.add "EVER" { in_spam=17; in_ham=1}
|> Map.add "EXMH" { in_spam=0; in_ham=8}
|> Map.add "FAQ" { in_spam=6; in_ham=6}
|> Map.add "FAX" { in_spam=15; in_ham=2}
|> Map.add "FBI" { in_spam=1; in_ham=12}
|> Map.add "FCC" { in_spam=0; in_ham=8}
|> Map.add "FFFF" { in_spam=29; in_ham=1}
|> Map.add "FFFFCC" { in_spam=13; in_ham=1}
|> Map.add "FFFFFF" { in_spam=98; in_ham=1}
|> Map.add "FOAF" { in_spam=0; in_ham=8}
|> Map.add "FONT" { in_spam=84; in_ham=7}
|> Map.add "FOR" { in_spam=58; in_ham=7}
|> Map.add "FORM" { in_spam=23; in_ham=0}
|> Map.add "FREE" { in_spam=154; in_ham=111}
|> Map.add "FROM" { in_spam=29; in_ham=4}
|> Map.add "GENERATOR" { in_spam=63; in_ham=5}
|> Map.add "GET" { in_spam=28; in_ham=0}
|> Map.add "GMT" { in_spam=0; in_ham=57}
|> Map.add "GNU" { in_spam=0; in_ham=89}
|> Map.add "GPG" { in_spam=1; in_ham=11}
|> Map.add "GPL" { in_spam=0; in_ham=10}
|> Map.add "GUARANTEED" { in_spam=20; in_ham=0}
|> Map.add "HAA" { in_spam=0; in_ham=11}
|> Map.add "HAVE" { in_spam=15; in_ham=3}
|> Map.add "HEAD" { in_spam=60; in_ham=8}
|> Map.add "HERE" { in_spam=80; in_ham=0}
|> Map.add "HOW" { in_spam=15; in_ham=6}
|> Map.add "HREF" { in_spam=20; in_ham=2}
|> Map.add "HTML" { in_spam=90; in_ham=53}
|> Map.add "HTTP" { in_spam=0; in_ham=11}
|> Map.add "IBM" { in_spam=1; in_ham=12}
|> Map.add "ICQ" { in_spam=0; in_ham=22}
|> Map.add "IDE" { in_spam=0; in_ham=8}
|> Map.add "IEEE" { in_spam=0; in_ham=10}
|> Map.add "III" { in_spam=9; in_ham=54}
|> Map.add "IIRC" { in_spam=0; in_ham=12}
|> Map.add "ILUG" { in_spam=0; in_ham=11}
|> Map.add "IMAP" { in_spam=0; in_ham=8}
|> Map.add "IMG" { in_spam=52; in_ham=52}
|> Map.add "IMHO" { in_spam=0; in_ham=16}
|> Map.add "IMO" { in_spam=0; in_ham=13}
|> Map.add "IMPORTANT" { in_spam=13; in_ham=1}
|> Map.add "INFO" { in_spam=13; in_ham=4}
|> Map.add "INFORMATION" { in_spam=13; in_ham=1}
|> Map.add "INPUT" { in_spam=16; in_ham=0}
|> Map.add "INTERNET" { in_spam=14; in_ham=1}
|> Map.add "ISO" { in_spam=0; in_ham=8}
|> Map.add "ISP" { in_spam=3; in_ham=14}
|> Map.add "JID" { in_spam=0; in_ham=9}
|> Map.add "JUST" { in_spam=16; in_ham=3}
|> Map.add "KDE" { in_spam=0; in_ham=8}
|> Map.add "KERNEL" { in_spam=0; in_ham=8}
|> Map.add "LAN" { in_spam=1; in_ham=11}
|> Map.add "LIKE" { in_spam=10; in_ham=4}
|> Map.add "LIST" { in_spam=18; in_ham=0}
|> Map.add "LLC" { in_spam=6; in_ham=8}
|> Map.add "LOL" { in_spam=0; in_ham=10}
|> Map.add "LOST" { in_spam=1; in_ham=11}
|> Map.add "LOW" { in_spam=21; in_ham=0}
|> Map.add "MDT" { in_spam=0; in_ham=10}
|> Map.add "META" { in_spam=45; in_ham=5}
|> Map.add "MIME" { in_spam=1; in_ham=18}
|> Map.add "MIT" { in_spam=0; in_ham=11}
|> Map.add "MONEY" { in_spam=29; in_ham=0}
|> Map.add "MORE" { in_spam=30; in_ham=3}
|> Map.add "MSHTML" { in_spam=24; in_ham=4}
|> Map.add "MSN" { in_spam=0; in_ham=33}
|> Map.add "MTA" { in_spam=0; in_ham=15}
|> Map.add "MUST" { in_spam=13; in_ham=5}
|> Map.add "NAME" { in_spam=40; in_ham=7}
|> Map.add "NASA" { in_spam=1; in_ham=9}
|> Map.add "NET" { in_spam=7; in_ham=12}
|> Map.add "NETNOTEINC" { in_spam=15; in_ham=0}
|> Map.add "NEVER" { in_spam=23; in_ham=1}
|> Map.add "NEW" { in_spam=18; in_ham=20}
|> Map.add "NOT" { in_spam=127; in_ham=35}
|> Map.add "NOTE" { in_spam=18; in_ham=2}
|> Map.add "NOW" { in_spam=84; in_ham=2}
|> Map.add "OFFER" { in_spam=12; in_ham=2}
|> Map.add "ONE" { in_spam=13; in_ham=1}
|> Map.add "ONLY" { in_spam=30; in_ham=1}
|> Map.add "ORDER" { in_spam=32; in_ham=1}
|> Map.add "OSDN" { in_spam=2; in_ham=106}
|> Map.add "OSI" { in_spam=0; in_ham=8}
|> Map.add "OSS" { in_spam=1; in_ham=18}
|> Map.add "OTHER" { in_spam=14; in_ham=2}
|> Map.add "OTOH" { in_spam=0; in_ham=11}
|> Map.add "OUT" { in_spam=22; in_ham=1}
|> Map.add "PDT" { in_spam=0; in_ham=14}
|> Map.add "PGP" { in_spam=0; in_ham=112}
|> Map.add "PLEASE" { in_spam=20; in_ham=2}
|> Map.add "POP" { in_spam=4; in_ham=12}
|> Map.add "PUBLIC" { in_spam=37; in_ham=6}
|> Map.add "RAH" { in_spam=0; in_ham=24}
|> Map.add "RAM" { in_spam=1; in_ham=8}
|> Map.add "RCS" { in_spam=0; in_ham=15}
|> Map.add "RDF" { in_spam=0; in_ham=12}
|> Map.add "READ" { in_spam=9; in_ham=3}
|> Map.add "README" { in_spam=0; in_ham=17}
|> Map.add "REMOVE" { in_spam=41; in_ham=1}
|> Map.add "REPLY" { in_spam=65; in_ham=0}
|> Map.add "RFC" { in_spam=0; in_ham=10}
|> Map.add "RIAA" { in_spam=0; in_ham=9}
|> Map.add "RPM" { in_spam=0; in_ham=46}
|> Map.add "RPMS" { in_spam=0; in_ham=11}
|> Map.add "RSS" { in_spam=0; in_ham=19}
|> Map.add "SEC" { in_spam=0; in_ham=9}
|> Map.add "SEND" { in_spam=14; in_ham=1}
|> Map.add "SHA" { in_spam=0; in_ham=22}
|> Map.add "SIGNED" { in_spam=1; in_ham=24}
|> Map.add "SIZE" { in_spam=17; in_ham=1}
|> Map.add "SMTP" { in_spam=0; in_ham=17}
|> Map.add "SOAP" { in_spam=0; in_ham=11}
|> Map.add "SPAM" { in_spam=9; in_ham=20}
|> Map.add "SPECIAL" { in_spam=9; in_ham=3}
|> Map.add "SQL" { in_spam=1; in_ham=8}
|> Map.add "SRC" { in_spam=16; in_ham=1}
|> Map.add "SSH" { in_spam=0; in_ham=8}
|> Map.add "SSL" { in_spam=3; in_ham=10}
|> Map.add "STDIN" { in_spam=0; in_ham=12}
|> Map.add "STRONG" { in_spam=15; in_ham=1}
|> Map.add "STYLE" { in_spam=22; in_ham=5}
|> Map.add "TABLE" { in_spam=66; in_ham=1}
|> Map.add "TBODY" { in_spam=45; in_ham=0}
|> Map.add "TECHNOLOGY" { in_spam=0; in_ham=12}
|> Map.add "THAN" { in_spam=14; in_ham=1}
|> Map.add "THAT" { in_spam=18; in_ham=12}
|> Map.add "THE" { in_spam=49; in_ham=20}
|> Map.add "THIS" { in_spam=34; in_ham=5}
|> Map.add "TITLE" { in_spam=46; in_ham=1}
|> Map.add "TMDA" { in_spam=0; in_ham=20}
|> Map.add "TODAY" { in_spam=22; in_ham=0}
|> Map.add "UNIX" { in_spam=0; in_ham=14}
|> Map.add "URL" { in_spam=14; in_ham=665}
|> Map.add "USA" { in_spam=18; in_ham=56}
|> Map.add "USB" { in_spam=1; in_ham=8}
|> Map.add "USD" { in_spam=11; in_ham=2}
|> Map.add "VERY" { in_spam=6; in_ham=5}
|> Map.add "WANT" { in_spam=16; in_ham=6}
|> Map.add "WIDTH" { in_spam=25; in_ham=0}
|> Map.add "WILL" { in_spam=30; in_ham=1}
|> Map.add "WITH" { in_spam=21; in_ham=1}
|> Map.add "WTF" { in_spam=0; in_ham=9}
|> Map.add "XML" { in_spam=0; in_ham=33}
|> Map.add "XMMS" { in_spam=0; in_ham=8}
|> Map.add "XXX" { in_spam=10; in_ham=3}
|> Map.add "YBB" { in_spam=0; in_ham=51}
|> Map.add "YOU" { in_spam=77; in_ham=1}
|> Map.add "YOUR" { in_spam=56; in_ham=0}
|> Map.add "YOURS" { in_spam=17; in_ham=0}
|> Map.add "aaron" { in_spam=0; in_ham=9}
|> Map.add "aaronsw" { in_spam=0; in_ham=20}
|> Map.add "abandoned" { in_spam=3; in_ham=9}
|> Map.add "ability" { in_spam=14; in_ham=71}
|> Map.add "able" { in_spam=21; in_ham=119}
|> Map.add "about" { in_spam=128; in_ham=675}
|> Map.add "above" { in_spam=54; in_ham=74}
|> Map.add "abroad" { in_spam=5; in_ham=6}
|> Map.add "absence" { in_spam=2; in_ham=8}
|> Map.add "absolute" { in_spam=6; in_ham=18}
|> Map.add "absolutely" { in_spam=43; in_ham=33}
|> Map.add "abuse" { in_spam=14; in_ham=8}
|> Map.add "academic" { in_spam=3; in_ham=7}
|> Map.add "accelerate" { in_spam=0; in_ham=8}
|> Map.add "acceleration" { in_spam=0; in_ham=9}
|> Map.add "accept" { in_spam=29; in_ham=42}
|> Map.add "acceptable" { in_spam=2; in_ham=12}
|> Map.add "acceptance" { in_spam=5; in_ham=7}
|> Map.add "accepted" { in_spam=24; in_ham=12}
|> Map.add "accepting" { in_spam=2; in_ham=9}
|> Map.add "access" { in_spam=59; in_ham=89}
|> Map.add "accessible" { in_spam=7; in_ham=8}
|> Map.add "accident" { in_spam=2; in_ham=11}
|> Map.add "accomplish" { in_spam=1; in_ham=11}
|> Map.add "accomplished" { in_spam=1; in_ham=7}
|> Map.add "according" { in_spam=16; in_ham=65}
|> Map.add "accordingly" { in_spam=1; in_ham=8}
|> Map.add "account" { in_spam=41; in_ham=35}
|> Map.add "accounting" { in_spam=1; in_ham=11}
|> Map.add "accounts" { in_spam=16; in_ham=23}
|> Map.add "accuracy" { in_spam=2; in_ham=7}
|> Map.add "accurate" { in_spam=2; in_ham=21}
|> Map.add "accurately" { in_spam=7; in_ham=6}
|> Map.add "accused" { in_spam=0; in_ham=10}
|> Map.add "achieve" { in_spam=9; in_ham=14}
|> Map.add "achievement" { in_spam=0; in_ham=16}
|> Map.add "acm" { in_spam=0; in_ham=8}
|> Map.add "acpi" { in_spam=0; in_ham=25}
|> Map.add "acquire" { in_spam=10; in_ham=10}
|> Map.add "acquired" { in_spam=0; in_ham=23}
|> Map.add "acquisition" { in_spam=7; in_ham=7}
|> Map.add "across" { in_spam=8; in_ham=72}
|> Map.add "act" { in_spam=33; in_ham=46}
|> Map.add "acting" { in_spam=5; in_ham=11}
|> Map.add "action" { in_spam=65; in_ham=45}
|> Map.add "actions" { in_spam=3; in_ham=21}
|> Map.add "active" { in_spam=12; in_ham=22}
|> Map.add "actively" { in_spam=4; in_ham=15}
|> Map.add "activists" { in_spam=0; in_ham=12}
|> Map.add "activities" { in_spam=11; in_ham=19}
|> Map.add "activity" { in_spam=7; in_ham=15}
|> Map.add "acts" { in_spam=6; in_ham=17}
|> Map.add "actual" { in_spam=7; in_ham=50}
|> Map.add "actually" { in_spam=30; in_ham=207}
|> Map.add "adam" { in_spam=0; in_ham=66}
|> Map.add "adapt" { in_spam=5; in_ham=8}
|> Map.add "adclick" { in_spam=15; in_ham=0}
|> Map.add "add" { in_spam=21; in_ham=168}
|> Map.add "added" { in_spam=15; in_ham=95}
|> Map.add "adding" { in_spam=1; in_ham=56}
|> Map.add "addition" { in_spam=8; in_ham=27}
|> Map.add "additional" { in_spam=20; in_ham=47}
|> Map.add "additionally" { in_spam=1; in_ham=7}
|> Map.add "addr" { in_spam=5; in_ham=10}
|> Map.add "address" { in_spam=122; in_ham=89}
|> Map.add "addressed" { in_spam=1; in_ham=8}
|> Map.add "addresses" { in_spam=37; in_ham=51}
|> Map.add "addressing" { in_spam=0; in_ham=11}
|> Map.add "adds" { in_spam=0; in_ham=23}
|> Map.add "admanmail" { in_spam=15; in_ham=0}
|> Map.add "admin" { in_spam=0; in_ham=10}
|> Map.add "admit" { in_spam=0; in_ham=16}
|> Map.add "admits" { in_spam=0; in_ham=8}
|> Map.add "adopt" { in_spam=0; in_ham=11}
|> Map.add "adopting" { in_spam=0; in_ham=13}
|> Map.add "adoption" { in_spam=1; in_ham=11}
|> Map.add "ads" { in_spam=20; in_ham=14}
|> Map.add "adult" { in_spam=15; in_ham=5}
|> Map.add "advance" { in_spam=7; in_ham=18}
|> Map.add "advanced" { in_spam=10; in_ham=34}
|> Map.add "advantage" { in_spam=18; in_ham=50}
|> Map.add "advantages" { in_spam=2; in_ham=8}
|> Map.add "advertise" { in_spam=13; in_ham=7}
|> Map.add "advertised" { in_spam=6; in_ham=6}
|> Map.add "advertising" { in_spam=34; in_ham=19}
|> Map.add "advice" { in_spam=21; in_ham=11}
|> Map.add "advise" { in_spam=2; in_ham=12}
|> Map.add "advised" { in_spam=8; in_ham=4}
|> Map.add "advisors" { in_spam=0; in_ham=8}
|> Map.add "aeriksson" { in_spam=0; in_ham=15}
|> Map.add "affair" { in_spam=0; in_ham=8}
|> Map.add "affected" { in_spam=2; in_ham=8}
|> Map.add "affects" { in_spam=0; in_ham=10}
|> Map.add "affiliate" { in_spam=25; in_ham=4}
|> Map.add "affiliated" { in_spam=12; in_ham=6}
|> Map.add "affiliates" { in_spam=15; in_ham=1}
|> Map.add "afford" { in_spam=2; in_ham=13}
|> Map.add "afghanistan" { in_spam=1; in_ham=11}
|> Map.add "afraid" { in_spam=3; in_ham=22}
|> Map.add "africa" { in_spam=16; in_ham=12}
|> Map.add "african" { in_spam=7; in_ham=7}
|> Map.add "after" { in_spam=63; in_ham=311}
|> Map.add "afternoon" { in_spam=1; in_ham=14}
|> Map.add "afterwards" { in_spam=0; in_ham=9}
|> Map.add "again" { in_spam=58; in_ham=204}
|> Map.add "against" { in_spam=37; in_ham=126}
|> Map.add "age" { in_spam=37; in_ham=33}
|> Map.add "agencies" { in_spam=10; in_ham=12}
|> Map.add "agency" { in_spam=8; in_ham=21}
|> Map.add "agenda" { in_spam=2; in_ham=11}
|> Map.add "agent" { in_spam=23; in_ham=36}
|> Map.add "agents" { in_spam=19; in_ham=21}
|> Map.add "ages" { in_spam=7; in_ham=6}
|> Map.add "aggregator" { in_spam=0; in_ham=9}
|> Map.add "aggressive" { in_spam=2; in_ham=18}
|> Map.add "agile" { in_spam=0; in_ham=21}
|> Map.add "ago" { in_spam=7; in_ham=121}
|> Map.add "agree" { in_spam=4; in_ham=66}
|> Map.add "agreeable" { in_spam=0; in_ham=39}
|> Map.add "agreed" { in_spam=12; in_ham=26}
|> Map.add "agreement" { in_spam=9; in_ham=13}
|> Map.add "ahead" { in_spam=4; in_ham=20}
|> Map.add "ahem" { in_spam=0; in_ham=8}
|> Map.add "ahh" { in_spam=0; in_ham=8}
|> Map.add "aid" { in_spam=11; in_ham=27}
|> Map.add "aids" { in_spam=0; in_ham=13}
|> Map.add "aim" { in_spam=3; in_ham=14}
|> Map.add "ain't" { in_spam=3; in_ham=6}
|> Map.add "air" { in_spam=17; in_ham=34}
|> Map.add "aircraft" { in_spam=3; in_ham=10}
|> Map.add "airline" { in_spam=6; in_ham=8}
|> Map.add "airport" { in_spam=3; in_ham=6}
|> Map.add "akamai" { in_spam=1; in_ham=9}
|> Map.add "alabama" { in_spam=4; in_ham=6}
|> Map.add "alan" { in_spam=0; in_ham=26}
|> Map.add "alarm" { in_spam=1; in_ham=8}
|> Map.add "alb" { in_spam=0; in_ham=8}
|> Map.add "album" { in_spam=7; in_ham=7}
|> Map.add "algorithm" { in_spam=0; in_ham=14}
|> Map.add "align" { in_spam=172; in_ham=5}
|> Map.add "alive" { in_spam=0; in_ham=12}
|> Map.add "all" { in_spam=245; in_ham=877}
|> Map.add "allen" { in_spam=0; in_ham=9}
|> Map.add "alliance" { in_spam=5; in_ham=12}
|> Map.add "allow" { in_spam=51; in_ham=71}
|> Map.add "allowed" { in_spam=4; in_ham=40}
|> Map.add "allowing" { in_spam=2; in_ham=14}
|> Map.add "allows" { in_spam=9; in_ham=42}
|> Map.add "almost" { in_spam=19; in_ham=105}
|> Map.add "alone" { in_spam=16; in_ham=28}
|> Map.add "along" { in_spam=22; in_ham=71}
|> Map.add "already" { in_spam=30; in_ham=155}
|> Map.add "alsa" { in_spam=0; in_ham=44}
|> Map.add "alsa-driver" { in_spam=0; in_ham=19}
|> Map.add "alsa-kernel" { in_spam=0; in_ham=15}
|> Map.add "alsamixer" { in_spam=0; in_ham=12}
|> Map.add "alsaplayer" { in_spam=0; in_ham=10}
|> Map.add "also" { in_spam=105; in_ham=428}
|> Map.add "alt" { in_spam=61; in_ham=9}
|> Map.add "alter" { in_spam=10; in_ham=9}
|> Map.add "alternate" { in_spam=2; in_ham=16}
|> Map.add "alternative" { in_spam=15; in_ham=45}
|> Map.add "alternatives" { in_spam=2; in_ham=10}
|> Map.add "although" { in_spam=14; in_ham=102}
|> Map.add "altitude" { in_spam=0; in_ham=8}
|> Map.add "alumni" { in_spam=0; in_ham=10}
|> Map.add "always" { in_spam=33; in_ham=140}
|> Map.add "amazing" { in_spam=9; in_ham=16}
|> Map.add "amazingly" { in_spam=3; in_ham=8}
|> Map.add "amazon" { in_spam=2; in_ham=12}
|> Map.add "ambitious" { in_spam=2; in_ham=9}
|> Map.add "amendment" { in_spam=0; in_ham=23}
|> Map.add "america" { in_spam=15; in_ham=46}
|> Map.add "america's" { in_spam=2; in_ham=12}
|> Map.add "american" { in_spam=22; in_ham=78}
|> Map.add "americans" { in_spam=3; in_ham=37}
|> Map.add "among" { in_spam=6; in_ham=39}
|> Map.add "amongst" { in_spam=0; in_ham=14}
|> Map.add "amount" { in_spam=35; in_ham=49}
|> Map.add "amounts" { in_spam=10; in_ham=15}
|> Map.add "amp" { in_spam=48; in_ham=2}
|> Map.add "amusing" { in_spam=0; in_ham=14}
|> Map.add "analog" { in_spam=0; in_ham=13}
|> Map.add "analysis" { in_spam=2; in_ham=29}
|> Map.add "analyst" { in_spam=6; in_ham=20}
|> Map.add "ancient" { in_spam=0; in_ham=11}
|> Map.add "and" { in_spam=407; in_ham=1881}
|> Map.add "anders" { in_spam=0; in_ham=21}
|> Map.add "anderson" { in_spam=4; in_ham=8}
|> Map.add "andrew" { in_spam=0; in_ham=14}
|> Map.add "anecdotal" { in_spam=0; in_ham=14}
|> Map.add "anecdote" { in_spam=0; in_ham=13}
|> Map.add "angeles" { in_spam=4; in_ham=13}
|> Map.add "anger" { in_spam=0; in_ham=11}
|> Map.add "angle" { in_spam=0; in_ham=23}
|> Map.add "angles" { in_spam=0; in_ham=14}
|> Map.add "angry" { in_spam=0; in_ham=14}
|> Map.add "animal" { in_spam=0; in_ham=13}
|> Map.add "animals" { in_spam=7; in_ham=5}
|> Map.add "announced" { in_spam=4; in_ham=31}
|> Map.add "announcement" { in_spam=3; in_ham=6}
|> Map.add "annoying" { in_spam=0; in_ham=24}
|> Map.add "annual" { in_spam=8; in_ham=20}
|> Map.add "annually" { in_spam=6; in_ham=9}
|> Map.add "annuity" { in_spam=16; in_ham=0}
|> Map.add "anonymous" { in_spam=1; in_ham=18}
|> Map.add "another" { in_spam=30; in_ham=244}
|> Map.add "answer" { in_spam=32; in_ham=56}
|> Map.add "answers" { in_spam=4; in_ham=61}
|> Map.add "antequated" { in_spam=0; in_ham=8}
|> Map.add "anthony" { in_spam=0; in_ham=21}
|> Map.add "anthony's" { in_spam=0; in_ham=8}
|> Map.add "anti-spam" { in_spam=2; in_ham=12}
|> Map.add "anticipated" { in_spam=0; in_ham=8}
|> Map.add "antiquity" { in_spam=1; in_ham=39}
|> Map.add "any" { in_spam=185; in_ham=557}
|> Map.add "anybody" { in_spam=19; in_ham=30}
|> Map.add "anymore" { in_spam=5; in_ham=26}
|> Map.add "anyone" { in_spam=69; in_ham=211}
|> Map.add "anything" { in_spam=32; in_ham=191}
|> Map.add "anytime" { in_spam=13; in_ham=3}
|> Map.add "anyway" { in_spam=0; in_ham=122}
|> Map.add "anywhere" { in_spam=24; in_ham=34}
|> Map.add "aol" { in_spam=11; in_ham=19}
|> Map.add "apache" { in_spam=0; in_ham=8}
|> Map.add "apart" { in_spam=0; in_ham=19}
|> Map.add "apartment" { in_spam=4; in_ham=6}
|> Map.add "apestaart" { in_spam=0; in_ham=8}
|> Map.add "api" { in_spam=1; in_ham=15}
|> Map.add "apologies" { in_spam=19; in_ham=12}
|> Map.add "apologize" { in_spam=15; in_ham=4}
|> Map.add "app" { in_spam=5; in_ham=23}
|> Map.add "apparent" { in_spam=1; in_ham=18}
|> Map.add "apparently" { in_spam=1; in_ham=59}
|> Map.add "appear" { in_spam=4; in_ham=49}
|> Map.add "appeared" { in_spam=0; in_ham=17}
|> Map.add "appears" { in_spam=11; in_ham=47}
|> Map.add "apple" { in_spam=0; in_ham=27}
|> Map.add "application" { in_spam=23; in_ham=52}
|> Map.add "applications" { in_spam=10; in_ham=55}
|> Map.add "applied" { in_spam=7; in_ham=17}
|> Map.add "applies" { in_spam=7; in_ham=6}
|> Map.add "apply" { in_spam=16; in_ham=19}
|> Map.add "applying" { in_spam=5; in_ham=9}
|> Map.add "appreciate" { in_spam=4; in_ham=17}
|> Map.add "appreciated" { in_spam=3; in_ham=23}
|> Map.add "approach" { in_spam=6; in_ham=44}
|> Map.add "approached" { in_spam=7; in_ham=11}
|> Map.add "approaches" { in_spam=0; in_ham=10}
|> Map.add "approaching" { in_spam=2; in_ham=7}
|> Map.add "appropriate" { in_spam=8; in_ham=17}
|> Map.add "approved" { in_spam=33; in_ham=9}
|> Map.add "approx" { in_spam=6; in_ham=5}
|> Map.add "apps" { in_spam=4; in_ham=23}
|> Map.add "apt" { in_spam=0; in_ham=66}
|> Map.add "apt-get" { in_spam=0; in_ham=34}
|> Map.add "arbitrary" { in_spam=0; in_ham=10}
|> Map.add "arch" { in_spam=0; in_ham=9}
|> Map.add "architect" { in_spam=0; in_ham=28}
|> Map.add "architecture" { in_spam=0; in_ham=22}
|> Map.add "archive" { in_spam=2; in_ham=36}
|> Map.add "archives" { in_spam=1; in_ham=146}
|> Map.add "are" { in_spam=302; in_ham=995}
|> Map.add "area" { in_spam=21; in_ham=68}
|> Map.add "areas" { in_spam=2; in_ham=33}
|> Map.add "aren't" { in_spam=7; in_ham=72}
|> Map.add "argue" { in_spam=0; in_ham=14}
|> Map.add "argued" { in_spam=0; in_ham=11}
|> Map.add "arguing" { in_spam=0; in_ham=12}
|> Map.add "argument" { in_spam=1; in_ham=50}
|> Map.add "arguments" { in_spam=1; in_ham=15}
|> Map.add "arial" { in_spam=160; in_ham=7}
|> Map.add "arm" { in_spam=3; in_ham=13}
|> Map.add "armed" { in_spam=1; in_ham=11}
|> Map.add "arms" { in_spam=7; in_ham=15}
|> Map.add "army" { in_spam=1; in_ham=9}
|> Map.add "around" { in_spam=38; in_ham=160}
|> Map.add "arrangement" { in_spam=10; in_ham=5}
|> Map.add "arrested" { in_spam=2; in_ham=19}
|> Map.add "arrival" { in_spam=1; in_ham=7}
|> Map.add "arrived" { in_spam=9; in_ham=19}
|> Map.add "art" { in_spam=12; in_ham=23}
|> Map.add "article" { in_spam=1; in_ham=165}
|> Map.add "articles" { in_spam=6; in_ham=44}
|> Map.add "artifacts" { in_spam=0; in_ham=9}
|> Map.add "artist" { in_spam=0; in_ham=17}
|> Map.add "artists" { in_spam=0; in_ham=9}
|> Map.add "arts" { in_spam=0; in_ham=20}
|> Map.add "asia" { in_spam=3; in_ham=12}
|> Map.add "asian" { in_spam=3; in_ham=6}
|> Map.add "aside" { in_spam=4; in_ham=11}
|> Map.add "ask" { in_spam=24; in_ham=75}
|> Map.add "asked" { in_spam=12; in_ham=57}
|> Map.add "asking" { in_spam=4; in_ham=42}
|> Map.add "asks" { in_spam=1; in_ham=13}
|> Map.add "asp" { in_spam=103; in_ham=146}
|> Map.add "aspect" { in_spam=1; in_ham=10}
|> Map.add "aspects" { in_spam=1; in_ham=10}
|> Map.add "ass" { in_spam=1; in_ham=23}
|> Map.add "assembled" { in_spam=1; in_ham=7}
|> Map.add "assembly" { in_spam=3; in_ham=7}
|> Map.add "assertion" { in_spam=2; in_ham=7}
|> Map.add "assessment" { in_spam=1; in_ham=7}
|> Map.add "assets" { in_spam=4; in_ham=15}
|> Map.add "assignee" { in_spam=0; in_ham=23}
|> Map.add "assigning" { in_spam=0; in_ham=8}
|> Map.add "assist" { in_spam=28; in_ham=4}
|> Map.add "assistance" { in_spam=43; in_ham=6}
|> Map.add "assistant" { in_spam=3; in_ham=6}
|> Map.add "associate" { in_spam=10; in_ham=5}
|> Map.add "associated" { in_spam=2; in_ham=28}
|> Map.add "associates" { in_spam=9; in_ham=9}
|> Map.add "association" { in_spam=20; in_ham=13}
|> Map.add "assume" { in_spam=9; in_ham=49}
|> Map.add "assumed" { in_spam=0; in_ham=9}
|> Map.add "assuming" { in_spam=10; in_ham=28}
|> Map.add "assumption" { in_spam=0; in_ham=18}
|> Map.add "assumptions" { in_spam=2; in_ham=7}
|> Map.add "assurance" { in_spam=8; in_ham=8}
|> Map.add "assured" { in_spam=8; in_ham=10}
|> Map.add "athenet" { in_spam=0; in_ham=8}
|> Map.add "atm" { in_spam=1; in_ham=9}
|> Map.add "attached" { in_spam=2; in_ham=22}
|> Map.add "attachment" { in_spam=2; in_ham=9}
|> Map.add "attachments" { in_spam=0; in_ham=13}
|> Map.add "attack" { in_spam=8; in_ham=26}
|> Map.add "attacked" { in_spam=1; in_ham=14}
|> Map.add "attacker" { in_spam=0; in_ham=8}
|> Map.add "attacks" { in_spam=4; in_ham=33}
|> Map.add "attained" { in_spam=23; in_ham=0}
|> Map.add "attempt" { in_spam=3; in_ham=44}
|> Map.add "attempting" { in_spam=3; in_ham=14}
|> Map.add "attempts" { in_spam=3; in_ham=18}
|> Map.add "attend" { in_spam=3; in_ham=6}
|> Map.add "attended" { in_spam=0; in_ham=11}
|> Map.add "attention" { in_spam=24; in_ham=24}
|> Map.add "attitude" { in_spam=3; in_ham=6}
|> Map.add "attorney" { in_spam=16; in_ham=5}
|> Map.add "attractive" { in_spam=6; in_ham=7}
|> Map.add "attributes" { in_spam=1; in_ham=8}
|> Map.add "auction" { in_spam=3; in_ham=8}
|> Map.add "audience" { in_spam=2; in_ham=13}
|> Map.add "audio" { in_spam=4; in_ham=29}
|> Map.add "aug" { in_spam=3; in_ham=177}
|> Map.add "august" { in_spam=11; in_ham=125}
|> Map.add "aumix" { in_spam=0; in_ham=13}
|> Map.add "auracom" { in_spam=0; in_ham=23}
|> Map.add "austin" { in_spam=0; in_ham=38}
|> Map.add "australia" { in_spam=8; in_ham=14}
|> Map.add "author" { in_spam=6; in_ham=37}
|> Map.add "authorities" { in_spam=1; in_ham=10}
|> Map.add "authority" { in_spam=3; in_ham=16}
|> Map.add "authors" { in_spam=3; in_ham=15}
|> Map.add "auto" { in_spam=20; in_ham=11}
|> Map.add "automated" { in_spam=2; in_ham=10}
|> Map.add "automatic" { in_spam=6; in_ham=18}
|> Map.add "autonumber" { in_spam=14; in_ham=1}
|> Map.add "availability" { in_spam=1; in_ham=9}
|> Map.add "available" { in_spam=84; in_ham=114}
|> Map.add "ave" { in_spam=7; in_ham=5}
|> Map.add "average" { in_spam=11; in_ham=49}
|> Map.add "averages" { in_spam=0; in_ham=9}
|> Map.add "avoid" { in_spam=15; in_ham=41}
|> Map.add "aware" { in_spam=5; in_ham=31}
|> Map.add "away" { in_spam=26; in_ham=112}
|> Map.add "awful" { in_spam=0; in_ham=9}
|> Map.add "axel" { in_spam=0; in_ham=12}
|> Map.add "b'far" { in_spam=0; in_ham=12}
|> Map.add "baartman" { in_spam=0; in_ham=9}
|> Map.add "baby" { in_spam=5; in_ham=18}
|> Map.add "back" { in_spam=51; in_ham=228}
|> Map.add "background" { in_spam=26; in_ham=27}
|> Map.add "backissues" { in_spam=0; in_ham=56}
|> Map.add "backup" { in_spam=23; in_ham=19}
|> Map.add "bad" { in_spam=11; in_ham=103}
|> Map.add "badly" { in_spam=0; in_ham=13}
|> Map.add "baffled" { in_spam=0; in_ham=9}
|> Map.add "balance" { in_spam=4; in_ham=16}
|> Map.add "balancing" { in_spam=0; in_ham=11}
|> Map.add "balloon" { in_spam=0; in_ham=8}
|> Map.add "balls" { in_spam=0; in_ham=10}
|> Map.add "bandwidth" { in_spam=2; in_ham=28}
|> Map.add "bang" { in_spam=2; in_ham=7}
|> Map.add "bank" { in_spam=37; in_ham=23}
|> Map.add "banking" { in_spam=3; in_ham=13}
|> Map.add "banks" { in_spam=7; in_ham=4}
|> Map.add "bar" { in_spam=7; in_ham=20}
|> Map.add "barcelona" { in_spam=0; in_ham=42}
|> Map.add "baroness" { in_spam=0; in_ham=9}
|> Map.add "barrera" { in_spam=0; in_ham=28}
|> Map.add "barriers" { in_spam=1; in_ham=7}
|> Map.add "barry" { in_spam=1; in_ham=18}
|> Map.add "bars" { in_spam=0; in_ham=10}
|> Map.add "base" { in_spam=14; in_ham=59}
|> Map.add "based" { in_spam=37; in_ham=101}
|> Map.add "basic" { in_spam=12; in_ham=38}
|> Map.add "basically" { in_spam=1; in_ham=34}
|> Map.add "basis" { in_spam=4; in_ham=30}
|> Map.add "batch" { in_spam=9; in_ham=6}
|> Map.add "battery" { in_spam=2; in_ham=30}
|> Map.add "battle" { in_spam=4; in_ham=23}
|> Map.add "baxter" { in_spam=0; in_ham=13}
|> Map.add "bay" { in_spam=0; in_ham=21}
|> Map.add "bayes" { in_spam=0; in_ham=9}
|> Map.add "bbc" { in_spam=0; in_ham=28}
|> Map.add "beach" { in_spam=1; in_ham=17}
|> Map.add "bear" { in_spam=1; in_ham=13}
|> Map.add "bearer" { in_spam=0; in_ham=43}
|> Map.add "beat" { in_spam=18; in_ham=22}
|> Map.add "beating" { in_spam=0; in_ham=12}
|> Map.add "beautiful" { in_spam=11; in_ham=15}
|> Map.add "beberg" { in_spam=0; in_ham=61}
|> Map.add "became" { in_spam=2; in_ham=41}
|> Map.add "because" { in_spam=116; in_ham=416}
|> Map.add "become" { in_spam=30; in_ham=73}
|> Map.add "becomes" { in_spam=1; in_ham=23}
|> Map.add "becoming" { in_spam=1; in_ham=24}
|> Map.add "bed" { in_spam=5; in_ham=14}
|> Map.add "been" { in_spam=111; in_ham=503}
|> Map.add "beer" { in_spam=1; in_ham=8}
|> Map.add "before" { in_spam=53; in_ham=273}
|> Map.add "began" { in_spam=6; in_ham=17}
|> Map.add "begin" { in_spam=15; in_ham=141}
|> Map.add "beginning" { in_spam=3; in_ham=42}
|> Map.add "begins" { in_spam=1; in_ham=12}
|> Map.add "begun" { in_spam=1; in_ham=15}
|> Map.add "behalf" { in_spam=7; in_ham=83}
|> Map.add "behavior" { in_spam=4; in_ham=33}
|> Map.add "behaviour" { in_spam=0; in_ham=19}
|> Map.add "behind" { in_spam=11; in_ham=50}
|> Map.add "being" { in_spam=69; in_ham=287}
|> Map.add "belief" { in_spam=2; in_ham=11}
|> Map.add "beliefs" { in_spam=1; in_ham=14}
|> Map.add "believe" { in_spam=39; in_ham=94}
|> Map.add "believed" { in_spam=8; in_ham=16}
|> Map.add "believes" { in_spam=2; in_ham=28}
|> Map.add "bell" { in_spam=0; in_ham=35}
|> Map.add "belong" { in_spam=7; in_ham=5}
|> Map.add "below" { in_spam=154; in_ham=54}
|> Map.add "ben" { in_spam=4; in_ham=32}
|> Map.add "beneath" { in_spam=3; in_ham=7}
|> Map.add "benefit" { in_spam=28; in_ham=34}
|> Map.add "benefits" { in_spam=20; in_ham=19}
|> Map.add "berkeley" { in_spam=0; in_ham=21}
|> Map.add "besides" { in_spam=0; in_ham=14}
|> Map.add "best" { in_spam=109; in_ham=210}
|> Map.add "bet" { in_spam=2; in_ham=13}
|> Map.add "beta" { in_spam=0; in_ham=20}
|> Map.add "better" { in_spam=40; in_ham=217}
|> Map.add "between" { in_spam=7; in_ham=183}
|> Map.add "beyond" { in_spam=4; in_ham=34}
|> Map.add "bgcolor" { in_spam=170; in_ham=5}
|> Map.add "biased" { in_spam=1; in_ham=12}
|> Map.add "bid" { in_spam=1; in_ham=8}
|> Map.add "big" { in_spam=32; in_ham=123}
|> Map.add "bigger" { in_spam=1; in_ham=23}
|> Map.add "biggest" { in_spam=13; in_ham=35}
|> Map.add "bill" { in_spam=26; in_ham=68}
|> Map.add "billion" { in_spam=16; in_ham=25}
|> Map.add "billions" { in_spam=3; in_ham=10}
|> Map.add "bills" { in_spam=16; in_ham=3}
|> Map.add "bin" { in_spam=0; in_ham=39}
|> Map.add "binary" { in_spam=0; in_ham=30}
|> Map.add "bindings" { in_spam=0; in_ham=15}
|> Map.add "biological" { in_spam=0; in_ham=9}
|> Map.add "birds" { in_spam=1; in_ham=7}
|> Map.add "birth" { in_spam=4; in_ham=7}
|> Map.add "bit" { in_spam=15; in_ham=144}
|> Map.add "bitbitch" { in_spam=0; in_ham=57}
|> Map.add "bite" { in_spam=0; in_ham=9}
|> Map.add "bits" { in_spam=1; in_ham=38}
|> Map.add "biz" { in_spam=8; in_ham=25}
|> Map.add "bizarre" { in_spam=0; in_ham=12}
|> Map.add "black" { in_spam=38; in_ham=40}
|> Map.add "blair" { in_spam=1; in_ham=18}
|> Map.add "blair's" { in_spam=0; in_ham=11}
|> Map.add "blame" { in_spam=0; in_ham=27}
|> Map.add "blamed" { in_spam=0; in_ham=9}
|> Map.add "blank" { in_spam=30; in_ham=5}
|> Map.add "blast" { in_spam=2; in_ham=7}
|> Map.add "bless" { in_spam=10; in_ham=4}
|> Map.add "blew" { in_spam=0; in_ham=10}
|> Map.add "blind" { in_spam=0; in_ham=21}
|> Map.add "bliss" { in_spam=0; in_ham=10}
|> Map.add "bloat" { in_spam=0; in_ham=10}
|> Map.add "block" { in_spam=1; in_ham=32}
|> Map.add "blocked" { in_spam=2; in_ham=9}
|> Map.add "blocking" { in_spam=0; in_ham=9}
|> Map.add "blockquote" { in_spam=12; in_ham=3}
|> Map.add "blog" { in_spam=0; in_ham=79}
|> Map.add "blood" { in_spam=4; in_ham=23}
|> Map.add "bloody" { in_spam=1; in_ham=7}
|> Map.add "blow" { in_spam=1; in_ham=13}
|> Map.add "blue" { in_spam=14; in_ham=23}
|> Map.add "bml" { in_spam=0; in_ham=10}
|> Map.add "board" { in_spam=0; in_ham=30}
|> Map.add "bob" { in_spam=1; in_ham=24}
|> Map.add "bobby" { in_spam=0; in_ham=8}
|> Map.add "bodies" { in_spam=0; in_ham=12}
|> Map.add "body" { in_spam=229; in_ham=60}
|> Map.add "bogus" { in_spam=1; in_ham=10}
|> Map.add "boing" { in_spam=0; in_ham=98}
|> Map.add "boingboing" { in_spam=0; in_ham=114}
|> Map.add "bolcer" { in_spam=0; in_ham=17}
|> Map.add "bold" { in_spam=18; in_ham=6}
|> Map.add "bone" { in_spam=0; in_ham=9}
|> Map.add "bones" { in_spam=3; in_ham=6}
|> Map.add "bonus" { in_spam=25; in_ham=8}
|> Map.add "book" { in_spam=15; in_ham=52}
|> Map.add "books" { in_spam=11; in_ham=26}
|> Map.add "boom" { in_spam=0; in_ham=9}
|> Map.add "boost" { in_spam=3; in_ham=8}
|> Map.add "boot" { in_spam=1; in_ham=18}
|> Map.add "border" { in_spam=172; in_ham=10}
|> Map.add "bordercolor" { in_spam=90; in_ham=1}
|> Map.add "borders" { in_spam=0; in_ham=8}
|> Map.add "bored" { in_spam=0; in_ham=11}
|> Map.add "boring" { in_spam=2; in_ham=8}
|> Map.add "born" { in_spam=1; in_ham=15}
|> Map.add "borrow" { in_spam=3; in_ham=7}
|> Map.add "boss" { in_spam=5; in_ham=7}
|> Map.add "boston" { in_spam=0; in_ham=47}
|> Map.add "bot" { in_spam=4; in_ham=7}
|> Map.add "both" { in_spam=45; in_ham=188}
|> Map.add "bother" { in_spam=1; in_ham=22}
|> Map.add "bothered" { in_spam=2; in_ham=7}
|> Map.add "bottle" { in_spam=4; in_ham=6}
|> Map.add "bottom" { in_spam=23; in_ham=31}
|> Map.add "bought" { in_spam=8; in_ham=20}
|> Map.add "bound" { in_spam=7; in_ham=13}
|> Map.add "boundaries" { in_spam=1; in_ham=9}
|> Map.add "bow" { in_spam=0; in_ham=8}
|> Map.add "box" { in_spam=20; in_ham=86}
|> Map.add "boxes" { in_spam=9; in_ham=13}
|> Map.add "boy" { in_spam=4; in_ham=24}
|> Map.add "boys" { in_spam=3; in_ham=10}
|> Map.add "brain" { in_spam=4; in_ham=26}
|> Map.add "branch" { in_spam=4; in_ham=9}
|> Map.add "brand" { in_spam=12; in_ham=9}
|> Map.add "break" { in_spam=3; in_ham=56}
|> Map.add "breaking" { in_spam=2; in_ham=14}
|> Map.add "breaks" { in_spam=0; in_ham=11}
|> Map.add "brent" { in_spam=0; in_ham=36}
|> Map.add "brian" { in_spam=2; in_ham=35}
|> Map.add "bridge" { in_spam=0; in_ham=14}
|> Map.add "brief" { in_spam=6; in_ham=22}
|> Map.add "briefly" { in_spam=2; in_ham=8}
|> Map.add "bright" { in_spam=0; in_ham=16}
|> Map.add "brighton" { in_spam=0; in_ham=11}
|> Map.add "bring" { in_spam=7; in_ham=34}
|> Map.add "bringing" { in_spam=3; in_ham=12}
|> Map.add "brings" { in_spam=1; in_ham=21}
|> Map.add "britain" { in_spam=2; in_ham=18}
|> Map.add "britain's" { in_spam=0; in_ham=12}
|> Map.add "british" { in_spam=8; in_ham=37}
|> Map.add "broad" { in_spam=2; in_ham=18}
|> Map.add "broadcasting" { in_spam=1; in_ham=10}
|> Map.add "broken" { in_spam=1; in_ham=32}
|> Map.add "broker" { in_spam=14; in_ham=5}
|> Map.add "brought" { in_spam=8; in_ham=28}
|> Map.add "brown" { in_spam=2; in_ham=9}
|> Map.add "browser" { in_spam=14; in_ham=23}
|> Map.add "bruce" { in_spam=0; in_ham=10}
|> Map.add "btamail" { in_spam=24; in_ham=0}
|> Map.add "btnsubmit" { in_spam=25; in_ham=0}
|> Map.add "btw" { in_spam=0; in_ham=59}
|> Map.add "bucks" { in_spam=13; in_ham=9}
|> Map.add "budget" { in_spam=4; in_ham=10}
|> Map.add "buffer" { in_spam=0; in_ham=20}
|> Map.add "bug" { in_spam=1; in_ham=98}
|> Map.add "bugs" { in_spam=0; in_ham=26}
|> Map.add "bugzilla" { in_spam=0; in_ham=39}
|> Map.add "build" { in_spam=17; in_ham=168}
|> Map.add "building" { in_spam=13; in_ham=71}
|> Map.add "buildings" { in_spam=3; in_ham=7}
|> Map.add "builds" { in_spam=0; in_ham=22}
|> Map.add "built" { in_spam=1; in_ham=63}
|> Map.add "built-in" { in_spam=1; in_ham=9}
|> Map.add "bulk" { in_spam=14; in_ham=8}
|> Map.add "bunch" { in_spam=0; in_ham=43}
|> Map.add "bundling" { in_spam=0; in_ham=9}
|> Map.add "burger" { in_spam=0; in_ham=9}
|> Map.add "buried" { in_spam=3; in_ham=12}

