open Database
open BayesianBody_002
let db = db 
|> Map.add "leads" { in_spam=7; in_ham=13}
|> Map.add "league" { in_spam=0; in_ham=8}
|> Map.add "learn" { in_spam=37; in_ham=54}
|> Map.add "learned" { in_spam=6; in_ham=19}
|> Map.add "learning" { in_spam=9; in_ham=13}
|> Map.add "least" { in_spam=25; in_ham=159}
|> Map.add "leave" { in_spam=15; in_ham=60}
|> Map.add "leaving" { in_spam=4; in_ham=28}
|> Map.add "led" { in_spam=2; in_ham=35}
|> Map.add "lee" { in_spam=7; in_ham=5}
|> Map.add "left" { in_spam=83; in_ham=90}
|> Map.add "leftmargin" { in_spam=21; in_ham=0}
|> Map.add "legacy" { in_spam=1; in_ham=7}
|> Map.add "legal" { in_spam=94; in_ham=57}
|> Map.add "legally" { in_spam=17; in_ham=11}
|> Map.add "legit" { in_spam=0; in_ham=10}
|> Map.add "legitimate" { in_spam=9; in_ham=13}
|> Map.add "legs" { in_spam=0; in_ham=11}
|> Map.add "leitl" { in_spam=0; in_ham=15}
|> Map.add "length" { in_spam=4; in_ham=16}
|> Map.add "less" { in_spam=48; in_ham=161}
|> Map.add "let" { in_spam=38; in_ham=123}
|> Map.add "let's" { in_spam=14; in_ham=42}
|> Map.add "lets" { in_spam=6; in_ham=19}
|> Map.add "letter" { in_spam=24; in_ham=23}
|> Map.add "letters" { in_spam=1; in_ham=15}
|> Map.add "level" { in_spam=21; in_ham=63}
|> Map.add "levels" { in_spam=2; in_ham=17}
|> Map.add "leverage" { in_spam=3; in_ham=12}
|> Map.add "liability" { in_spam=1; in_ham=8}
|> Map.add "liable" { in_spam=0; in_ham=8}
|> Map.add "lib" { in_spam=0; in_ham=75}
|> Map.add "liberal" { in_spam=2; in_ham=22}
|> Map.add "libertatem" { in_spam=0; in_ham=9}
|> Map.add "liberty" { in_spam=0; in_ham=12}
|> Map.add "libraries" { in_spam=0; in_ham=30}
|> Map.add "library" { in_spam=2; in_ham=26}
|> Map.add "license" { in_spam=4; in_ham=20}
|> Map.add "licensed" { in_spam=3; in_ham=9}
|> Map.add "licenses" { in_spam=1; in_ham=7}
|> Map.add "licensing" { in_spam=1; in_ham=10}
|> Map.add "lie" { in_spam=8; in_ham=11}
|> Map.add "lies" { in_spam=5; in_ham=7}
|> Map.add "lieu" { in_spam=3; in_ham=8}
|> Map.add "life" { in_spam=98; in_ham=115}
|> Map.add "lifestyle" { in_spam=5; in_ham=5}
|> Map.add "lifetime" { in_spam=17; in_ham=4}
|> Map.add "lift" { in_spam=5; in_ham=9}
|> Map.add "lifted" { in_spam=1; in_ham=7}
|> Map.add "lig" { in_spam=0; in_ham=8}
|> Map.add "light" { in_spam=20; in_ham=35}
|> Map.add "like" { in_spam=114; in_ham=648}
|> Map.add "liked" { in_spam=4; in_ham=16}
|> Map.add "likely" { in_spam=5; in_ham=75}
|> Map.add "likes" { in_spam=1; in_ham=12}
|> Map.add "limit" { in_spam=16; in_ham=20}
|> Map.add "limitations" { in_spam=5; in_ham=11}
|> Map.add "limited" { in_spam=43; in_ham=33}
|> Map.add "limits" { in_spam=2; in_ham=12}
|> Map.add "line" { in_spam=67; in_ham=208}
|> Map.add "lines" { in_spam=3; in_ham=69}
|> Map.add "link" { in_spam=119; in_ham=175}
|> Map.add "linked" { in_spam=0; in_ham=18}
|> Map.add "linking" { in_spam=0; in_ham=8}
|> Map.add "links" { in_spam=15; in_ham=59}
|> Map.add "linux" { in_spam=47; in_ham=316}
|> Map.add "lirc" { in_spam=0; in_ham=10}
|> Map.add "list" { in_spam=255; in_ham=920}
|> Map.add "listed" { in_spam=20; in_ham=25}
|> Map.add "listen" { in_spam=5; in_ham=19}
|> Map.add "listening" { in_spam=0; in_ham=24}
|> Map.add "listinfo" { in_spam=51; in_ham=837}
|> Map.add "listing" { in_spam=6; in_ham=5}
|> Map.add "listman" { in_spam=0; in_ham=140}
|> Map.add "listmaster" { in_spam=46; in_ham=92}
|> Map.add "lists" { in_spam=22; in_ham=555}
|> Map.add "literally" { in_spam=8; in_ham=17}
|> Map.add "litigation" { in_spam=5; in_ham=5}
|> Map.add "little" { in_spam=39; in_ham=126}
|> Map.add "live" { in_spam=33; in_ham=82}
|> Map.add "lived" { in_spam=2; in_ham=11}
|> Map.add "livejournal" { in_spam=0; in_ham=10}
|> Map.add "lives" { in_spam=4; in_ham=36}
|> Map.add "living" { in_spam=17; in_ham=50}
|> Map.add "llc" { in_spam=9; in_ham=8}
|> Map.add "load" { in_spam=3; in_ham=103}
|> Map.add "loaded" { in_spam=4; in_ham=24}
|> Map.add "loading" { in_spam=0; in_ham=15}
|> Map.add "loads" { in_spam=0; in_ham=8}
|> Map.add "loan" { in_spam=23; in_ham=9}
|> Map.add "loans" { in_spam=20; in_ham=3}
|> Map.add "local" { in_spam=20; in_ham=124}
|> Map.add "locale" { in_spam=2; in_ham=12}
|> Map.add "localhost" { in_spam=0; in_ham=10}
|> Map.add "locally" { in_spam=1; in_ham=7}
|> Map.add "locate" { in_spam=5; in_ham=14}
|> Map.add "located" { in_spam=5; in_ham=12}
|> Map.add "location" { in_spam=11; in_ham=24}
|> Map.add "lock" { in_spam=5; in_ham=21}
|> Map.add "locked" { in_spam=6; in_ham=10}
|> Map.add "locking" { in_spam=2; in_ham=9}
|> Map.add "log" { in_spam=3; in_ham=146}
|> Map.add "logic" { in_spam=0; in_ham=8}
|> Map.add "logical" { in_spam=4; in_ham=11}
|> Map.add "login" { in_spam=4; in_ham=14}
|> Map.add "logo" { in_spam=25; in_ham=6}
|> Map.add "logs" { in_spam=0; in_ham=13}
|> Map.add "lol" { in_spam=0; in_ham=11}
|> Map.add "london" { in_spam=4; in_ham=19}
|> Map.add "long" { in_spam=47; in_ham=193}
|> Map.add "long-term" { in_spam=7; in_ham=21}
|> Map.add "longer" { in_spam=33; in_ham=53}
|> Map.add "longest" { in_spam=1; in_ham=7}
|> Map.add "look" { in_spam=36; in_ham=229}
|> Map.add "looked" { in_spam=6; in_ham=54}
|> Map.add "looking" { in_spam=39; in_ham=118}
|> Map.add "looks" { in_spam=0; in_ham=120}
|> Map.add "looney" { in_spam=0; in_ham=9}
|> Map.add "loop" { in_spam=0; in_ham=8}
|> Map.add "loose" { in_spam=5; in_ham=12}
|> Map.add "lord" { in_spam=0; in_ham=9}
|> Map.add "los" { in_spam=4; in_ham=13}
|> Map.add "lose" { in_spam=40; in_ham=27}
|> Map.add "losing" { in_spam=11; in_ham=14}
|> Map.add "loss" { in_spam=26; in_ham=20}
|> Map.add "lost" { in_spam=13; in_ham=66}
|> Map.add "lot" { in_spam=27; in_ham=170}
|> Map.add "lots" { in_spam=4; in_ham=78}
|> Map.add "love" { in_spam=16; in_ham=68}
|> Map.add "loved" { in_spam=2; in_ham=9}
|> Map.add "lovely" { in_spam=0; in_ham=8}
|> Map.add "lovers" { in_spam=2; in_ham=11}
|> Map.add "low" { in_spam=57; in_ham=32}
|> Map.add "lower" { in_spam=16; in_ham=36}
|> Map.add "lowest" { in_spam=31; in_ham=5}
|> Map.add "ltd" { in_spam=12; in_ham=7}
|> Map.add "lucas" { in_spam=0; in_ham=14}
|> Map.add "luck" { in_spam=9; in_ham=23}
|> Map.add "lucky" { in_spam=5; in_ham=12}
|> Map.add "lunch" { in_spam=3; in_ham=8}
|> Map.add "lynn" { in_spam=0; in_ham=13}
|> Map.add "lynx" { in_spam=0; in_ham=12}
|> Map.add "mac" { in_spam=1; in_ham=35}
|> Map.add "machine" { in_spam=10; in_ham=71}
|> Map.add "machines" { in_spam=0; in_ham=31}
|> Map.add "macintosh" { in_spam=0; in_ham=8}
|> Map.add "macosx" { in_spam=0; in_ham=8}
|> Map.add "mad" { in_spam=0; in_ham=11}
|> Map.add "madam" { in_spam=17; in_ham=2}
|> Map.add "made" { in_spam=70; in_ham=177}
|> Map.add "magazine" { in_spam=8; in_ham=19}
|> Map.add "magazines" { in_spam=9; in_ham=3}
|> Map.add "magic" { in_spam=1; in_ham=15}
|> Map.add "magnesium" { in_spam=0; in_ham=56}
|> Map.add "magnitude" { in_spam=0; in_ham=22}
|> Map.add "maid" { in_spam=0; in_ham=9}
|> Map.add "mail" { in_spam=86; in_ham=263}
|> Map.add "mailbox" { in_spam=3; in_ham=11}
|> Map.add "mailed" { in_spam=10; in_ham=4}
|> Map.add "mailer" { in_spam=9; in_ham=34}
|> Map.add "mailers" { in_spam=0; in_ham=8}
|> Map.add "mailing" { in_spam=121; in_ham=706}
|> Map.add "mailings" { in_spam=87; in_ham=3}
|> Map.add "mailman" { in_spam=46; in_ham=584}
|> Map.add "mails" { in_spam=2; in_ham=12}
|> Map.add "mailto" { in_spam=69; in_ham=209}
|> Map.add "main" { in_spam=16; in_ham=70}
|> Map.add "mainly" { in_spam=0; in_ham=16}
|> Map.add "maintain" { in_spam=7; in_ham=29}
|> Map.add "maintained" { in_spam=5; in_ham=5}
|> Map.add "maintainer" { in_spam=46; in_ham=96}
|> Map.add "maintaining" { in_spam=0; in_ham=10}
|> Map.add "maintains" { in_spam=1; in_ham=12}
|> Map.add "maintenance" { in_spam=2; in_ham=15}
|> Map.add "major" { in_spam=29; in_ham=75}
|> Map.add "majordomo" { in_spam=8; in_ham=4}
|> Map.add "majority" { in_spam=9; in_ham=21}
|> Map.add "make" { in_spam=101; in_ham=375}
|> Map.add "makefile" { in_spam=0; in_ham=11}
|> Map.add "makers" { in_spam=6; in_ham=12}
|> Map.add "makes" { in_spam=23; in_ham=117}
|> Map.add "making" { in_spam=41; in_ham=118}
|> Map.add "male" { in_spam=20; in_ham=21}
|> Map.add "males" { in_spam=2; in_ham=16}
|> Map.add "malte" { in_spam=0; in_ham=9}
|> Map.add "man" { in_spam=11; in_ham=92}
|> Map.add "man's" { in_spam=1; in_ham=12}
|> Map.add "manage" { in_spam=16; in_ham=29}
|> Map.add "managed" { in_spam=2; in_ham=34}
|> Map.add "management" { in_spam=30; in_ham=43}
|> Map.add "manager" { in_spam=30; in_ham=38}
|> Map.add "managers" { in_spam=6; in_ham=11}
|> Map.add "manages" { in_spam=0; in_ham=9}
|> Map.add "managing" { in_spam=9; in_ham=16}
|> Map.add "mandated" { in_spam=10; in_ham=3}
|> Map.add "manhattan" { in_spam=6; in_ham=5}
|> Map.add "manner" { in_spam=4; in_ham=17}
|> Map.add "manual" { in_spam=6; in_ham=16}
|> Map.add "manually" { in_spam=2; in_ham=22}
|> Map.add "many" { in_spam=46; in_ham=281}
|> Map.add "map" { in_spam=4; in_ham=20}
|> Map.add "maps" { in_spam=0; in_ham=11}
|> Map.add "march" { in_spam=6; in_ham=21}
|> Map.add "margin" { in_spam=5; in_ham=9}
|> Map.add "marginal" { in_spam=0; in_ham=11}
|> Map.add "mark" { in_spam=7; in_ham=88}
|> Map.add "marked" { in_spam=12; in_ham=11}
|> Map.add "market" { in_spam=59; in_ham=61}
|> Map.add "marketing" { in_spam=80; in_ham=23}
|> Map.add "marketplace" { in_spam=6; in_ham=11}
|> Map.add "markets" { in_spam=4; in_ham=24}
|> Map.add "marks" { in_spam=5; in_ham=12}
|> Map.add "markup" { in_spam=0; in_ham=8}
|> Map.add "marriage" { in_spam=0; in_ham=16}
|> Map.add "married" { in_spam=0; in_ham=12}
|> Map.add "marry" { in_spam=0; in_ham=12}
|> Map.add "marrying" { in_spam=0; in_ham=11}
|> Map.add "marshall" { in_spam=2; in_ham=11}
|> Map.add "martin" { in_spam=2; in_ham=17}
|> Map.add "mason" { in_spam=0; in_ham=48}
|> Map.add "mass" { in_spam=8; in_ham=31}
|> Map.add "mass-check" { in_spam=0; in_ham=8}
|> Map.add "masses" { in_spam=3; in_ham=11}
|> Map.add "massive" { in_spam=1; in_ham=18}
|> Map.add "master" { in_spam=7; in_ham=13}
|> Map.add "match" { in_spam=1; in_ham=26}
|> Map.add "matches" { in_spam=0; in_ham=11}
|> Map.add "matching" { in_spam=7; in_ham=8}
|> Map.add "mate" { in_spam=2; in_ham=7}
|> Map.add "material" { in_spam=6; in_ham=27}
|> Map.add "materials" { in_spam=12; in_ham=14}
|> Map.add "math" { in_spam=2; in_ham=12}
|> Map.add "mathematics" { in_spam=0; in_ham=28}
|> Map.add "matt" { in_spam=1; in_ham=19}
|> Map.add "matter" { in_spam=27; in_ham=65}
|> Map.add "matters" { in_spam=4; in_ham=26}
|> Map.add "matthew" { in_spam=0; in_ham=9}
|> Map.add "matthias" { in_spam=0; in_ham=152}
|> Map.add "max" { in_spam=2; in_ham=11}
|> Map.add "maximum" { in_spam=9; in_ham=3}
|> Map.add "may" { in_spam=112; in_ham=300}
|> Map.add "maybe" { in_spam=13; in_ham=171}
|> Map.add "mbps" { in_spam=0; in_ham=11}
|> Map.add "mdt" { in_spam=0; in_ham=10}
|> Map.add "mean" { in_spam=18; in_ham=102}
|> Map.add "meaning" { in_spam=11; in_ham=23}
|> Map.add "meaningful" { in_spam=0; in_ham=10}
|> Map.add "means" { in_spam=20; in_ham=107}
|> Map.add "meant" { in_spam=6; in_ham=30}
|> Map.add "meantime" { in_spam=0; in_ham=9}
|> Map.add "meanwhile" { in_spam=2; in_ham=13}
|> Map.add "measure" { in_spam=2; in_ham=18}
|> Map.add "measured" { in_spam=0; in_ham=11}
|> Map.add "measures" { in_spam=1; in_ham=7}
|> Map.add "measuring" { in_spam=1; in_ham=7}
|> Map.add "mechanism" { in_spam=2; in_ham=13}
|> Map.add "mechanisms" { in_spam=1; in_ham=10}
|> Map.add "media" { in_spam=14; in_ham=57}
|> Map.add "medical" { in_spam=9; in_ham=6}
|> Map.add "medicine" { in_spam=7; in_ham=8}
|> Map.add "medium" { in_spam=17; in_ham=7}
|> Map.add "meet" { in_spam=14; in_ham=41}
|> Map.add "meeting" { in_spam=8; in_ham=20}
|> Map.add "meetings" { in_spam=3; in_ham=16}
|> Map.add "member" { in_spam=46; in_ham=27}
|> Map.add "members" { in_spam=26; in_ham=37}
|> Map.add "membership" { in_spam=15; in_ham=5}
|> Map.add "memorial" { in_spam=1; in_ham=8}
|> Map.add "memory" { in_spam=8; in_ham=54}
|> Map.add "men" { in_spam=9; in_ham=51}
|> Map.add "mention" { in_spam=4; in_ham=32}
|> Map.add "mentioned" { in_spam=3; in_ham=41}
|> Map.add "mentioning" { in_spam=0; in_ham=11}
|> Map.add "menu" { in_spam=1; in_ham=27}
|> Map.add "merely" { in_spam=0; in_ham=17}
|> Map.add "merge" { in_spam=0; in_ham=12}
|> Map.add "merit" { in_spam=2; in_ham=8}
|> Map.add "mess" { in_spam=2; in_ham=13}
|> Map.add "message" { in_spam=150; in_ham=369}
|> Map.add "message's" { in_spam=0; in_ham=8}
|> Map.add "message-----" { in_spam=0; in_ham=119}
|> Map.add "message-id" { in_spam=0; in_ham=34}
|> Map.add "messages" { in_spam=13; in_ham=242}
|> Map.add "messed" { in_spam=0; in_ham=8}
|> Map.add "messenger" { in_spam=0; in_ham=16}
|> Map.add "met" { in_spam=8; in_ham=36}
|> Map.add "meta" { in_spam=133; in_ham=8}
|> Map.add "method" { in_spam=69; in_ham=63}
|> Map.add "methods" { in_spam=12; in_ham=25}
|> Map.add "metro" { in_spam=0; in_ham=14}
|> Map.add "mhprofile" { in_spam=0; in_ham=8}
|> Map.add "mhseqexpand" { in_spam=0; in_ham=8}
|> Map.add "mhz" { in_spam=2; in_ham=9}
|> Map.add "miami" { in_spam=6; in_ham=6}
|> Map.add "michael" { in_spam=3; in_ham=48}
|> Map.add "michel" { in_spam=0; in_ham=9}
|> Map.add "microsoft" { in_spam=38; in_ham=50}
|> Map.add "middle" { in_spam=70; in_ham=44}
|> Map.add "might" { in_spam=21; in_ham=215}
|> Map.add "mike" { in_spam=1; in_ham=33}
|> Map.add "mile" { in_spam=2; in_ham=11}
|> Map.add "miles" { in_spam=10; in_ham=18}
|> Map.add "military" { in_spam=10; in_ham=32}
|> Map.add "millennium" { in_spam=2; in_ham=13}
|> Map.add "million" { in_spam=88; in_ham=61}
|> Map.add "millionaire" { in_spam=11; in_ham=4}
|> Map.add "millions" { in_spam=31; in_ham=29}
|> Map.add "milter" { in_spam=0; in_ham=8}
|> Map.add "mime" { in_spam=1; in_ham=29}
|> Map.add "mime-version" { in_spam=1; in_ham=9}
|> Map.add "mind" { in_spam=31; in_ham=65}
|> Map.add "mine" { in_spam=5; in_ham=24}
|> Map.add "minimal" { in_spam=14; in_ham=8}
|> Map.add "minimize" { in_spam=0; in_ham=11}
|> Map.add "minimum" { in_spam=12; in_ham=4}
|> Map.add "minister" { in_spam=5; in_ham=13}
|> Map.add "minor" { in_spam=1; in_ham=10}
|> Map.add "minority" { in_spam=1; in_ham=8}
|> Map.add "minute" { in_spam=23; in_ham=24}
|> Map.add "minutes" { in_spam=21; in_ham=30}
|> Map.add "mirror" { in_spam=0; in_ham=12}
|> Map.add "mirrors" { in_spam=1; in_ham=13}
|> Map.add "misc" { in_spam=1; in_ham=15}
|> Map.add "miss" { in_spam=14; in_ham=23}
|> Map.add "missed" { in_spam=1; in_ham=12}
|> Map.add "missing" { in_spam=4; in_ham=46}
|> Map.add "mission" { in_spam=3; in_ham=14}
|> Map.add "mistake" { in_spam=2; in_ham=25}
|> Map.add "mistakes" { in_spam=11; in_ham=6}
|> Map.add "mit" { in_spam=1; in_ham=27}
|> Map.add "mithral" { in_spam=0; in_ham=38}
|> Map.add "mix" { in_spam=2; in_ham=16}
|> Map.add "mixed" { in_spam=2; in_ham=16}
|> Map.add "mld" { in_spam=0; in_ham=10}
|> Map.add "mobile" { in_spam=8; in_ham=28}
|> Map.add "mod" { in_spam=0; in_ham=9}
|> Map.add "mode" { in_spam=2; in_ham=56}
|> Map.add "model" { in_spam=2; in_ham=47}
|> Map.add "models" { in_spam=2; in_ham=22}
|> Map.add "modem" { in_spam=1; in_ham=19}
|> Map.add "moderate" { in_spam=3; in_ham=7}
|> Map.add "modern" { in_spam=2; in_ham=34}
|> Map.add "modes" { in_spam=3; in_ham=9}
|> Map.add "modest" { in_spam=3; in_ham=10}
|> Map.add "modified" { in_spam=8; in_ham=39}
|> Map.add "modify" { in_spam=0; in_ham=19}
|> Map.add "module" { in_spam=0; in_ham=34}
|> Map.add "modules" { in_spam=0; in_ham=56}
|> Map.add "mohr" { in_spam=0; in_ham=11}
|> Map.add "mom" { in_spam=2; in_ham=7}
|> Map.add "moment" { in_spam=21; in_ham=30}
|> Map.add "moments" { in_spam=4; in_ham=7}
|> Map.add "mon" { in_spam=3; in_ham=120}
|> Map.add "monday" { in_spam=1; in_ham=99}
|> Map.add "mondo" { in_spam=0; in_ham=10}
|> Map.add "money" { in_spam=118; in_ham=106}
|> Map.add "monitor" { in_spam=1; in_ham=14}
|> Map.add "monitoring" { in_spam=1; in_ham=8}
|> Map.add "monitors" { in_spam=0; in_ham=9}
|> Map.add "monkey" { in_spam=0; in_ham=12}
|> Map.add "monopoly" { in_spam=0; in_ham=8}
|> Map.add "montanaro" { in_spam=0; in_ham=9}
|> Map.add "month" { in_spam=61; in_ham=71}
|> Map.add "monthly" { in_spam=18; in_ham=4}
|> Map.add "months" { in_spam=35; in_ham=79}
|> Map.add "mood" { in_spam=2; in_ham=7}
|> Map.add "moral" { in_spam=1; in_ham=8}
|> Map.add "moran" { in_spam=0; in_ham=8}
|> Map.add "more" { in_spam=217; in_ham=638}
|> Map.add "morning" { in_spam=1; in_ham=31}
|> Map.add "mortgage" { in_spam=34; in_ham=2}
|> Map.add "most" { in_spam=82; in_ham=315}
|> Map.add "mostly" { in_spam=5; in_ham=49}
|> Map.add "mot" { in_spam=2; in_ham=9}
|> Map.add "mother" { in_spam=11; in_ham=22}
|> Map.add "motivated" { in_spam=19; in_ham=7}
|> Map.add "mount" { in_spam=0; in_ham=8}
|> Map.add "mountain" { in_spam=7; in_ham=18}
|> Map.add "mouse" { in_spam=1; in_ham=31}
|> Map.add "move" { in_spam=28; in_ham=76}
|> Map.add "moved" { in_spam=15; in_ham=35}
|> Map.add "movement" { in_spam=2; in_ham=9}
|> Map.add "moves" { in_spam=0; in_ham=13}
|> Map.add "movie" { in_spam=15; in_ham=19}
|> Map.add "movies" { in_spam=14; in_ham=14}
|> Map.add "moving" { in_spam=4; in_ham=27}
|> Map.add "mozilla" { in_spam=1; in_ham=22}
|> Map.add "mozillazine" { in_spam=0; in_ham=8}
|> Map.add "mplayer" { in_spam=0; in_ham=26}
|> Map.add "mrs" { in_spam=8; in_ham=5}
|> Map.add "msg" { in_spam=0; in_ham=51}
|> Map.add "msgchange" { in_spam=0; in_ham=9}
|> Map.add "msgid" { in_spam=4; in_ham=9}
|> Map.add "msgids" { in_spam=0; in_ham=8}
|> Map.add "msgs" { in_spam=0; in_ham=36}
|> Map.add "mshtml" { in_spam=24; in_ham=4}
|> Map.add "msn" { in_spam=3; in_ham=39}
|> Map.add "msnbc" { in_spam=0; in_ham=9}
|> Map.add "mta" { in_spam=0; in_ham=15}
|> Map.add "much" { in_spam=68; in_ham=324}
|> Map.add "multipart" { in_spam=1; in_ham=11}
|> Map.add "multiple" { in_spam=12; in_ham=55}
|> Map.add "munnari" { in_spam=0; in_ham=11}
|> Map.add "murcko" { in_spam=0; in_ham=11}
|> Map.add "murder" { in_spam=0; in_ham=13}
|> Map.add "murphy" { in_spam=0; in_ham=81}
|> Map.add "muscle" { in_spam=7; in_ham=5}
|> Map.add "museum" { in_spam=0; in_ham=8}
|> Map.add "music" { in_spam=9; in_ham=50}
|> Map.add "muslim" { in_spam=0; in_ham=13}
|> Map.add "muslims" { in_spam=0; in_ham=9}
|> Map.add "must" { in_spam=73; in_ham=115}
|> Map.add "mutual" { in_spam=9; in_ham=10}
|> Map.add "mvfiaa" { in_spam=0; in_ham=76}
|> Map.add "myjabber" { in_spam=0; in_ham=9}
|> Map.add "myself" { in_spam=12; in_ham=51}
|> Map.add "mysql" { in_spam=1; in_ham=10}
|> Map.add "name" { in_spam=217; in_ham=110}
|> Map.add "named" { in_spam=3; in_ham=33}
|> Map.add "names" { in_spam=32; in_ham=34}
|> Map.add "narrow" { in_spam=3; in_ham=12}
|> Map.add "nasa" { in_spam=1; in_ham=9}
|> Map.add "nasty" { in_spam=2; in_ham=12}
|> Map.add "nation" { in_spam=3; in_ham=15}
|> Map.add "nation's" { in_spam=0; in_ham=10}
|> Map.add "national" { in_spam=30; in_ham=57}
|> Map.add "nations" { in_spam=1; in_ham=24}
|> Map.add "nationwide" { in_spam=11; in_ham=4}
|> Map.add "native" { in_spam=2; in_ham=12}
|> Map.add "natural" { in_spam=12; in_ham=17}
|> Map.add "naturally" { in_spam=6; in_ham=9}
|> Map.add "nature" { in_spam=10; in_ham=25}
|> Map.add "nbsp" { in_spam=143; in_ham=12}
|> Map.add "nder" { in_spam=0; in_ham=8}
|> Map.add "neale" { in_spam=0; in_ham=13}
|> Map.add "near" { in_spam=10; in_ham=42}
|> Map.add "nearby" { in_spam=0; in_ham=9}
|> Map.add "nearly" { in_spam=2; in_ham=26}
|> Map.add "neat" { in_spam=1; in_ham=13}
|> Map.add "necessarily" { in_spam=0; in_ham=21}
|> Map.add "necessary" { in_spam=10; in_ham=36}
|> Map.add "need" { in_spam=97; in_ham=282}
|> Map.add "needed" { in_spam=23; in_ham=79}
|> Map.add "needs" { in_spam=22; in_ham=106}
|> Map.add "negative" { in_spam=6; in_ham=35}
|> Map.add "negatives" { in_spam=1; in_ham=7}
|> Map.add "neighbor" { in_spam=1; in_ham=8}
|> Map.add "neil" { in_spam=0; in_ham=12}
|> Map.add "neither" { in_spam=4; in_ham=23}
|> Map.add "net" { in_spam=129; in_ham=868}
|> Map.add "netnoteinc" { in_spam=17; in_ham=0}
|> Map.add "netscape" { in_spam=8; in_ham=15}
|> Map.add "network" { in_spam=14; in_ham=152}
|> Map.add "networking" { in_spam=2; in_ham=17}
|> Map.add "networks" { in_spam=1; in_ham=39}
|> Map.add "never" { in_spam=73; in_ham=188}
|> Map.add "nevertheless" { in_spam=0; in_ham=10}
|> Map.add "new" { in_spam=193; in_ham=530}
|> Map.add "newer" { in_spam=0; in_ham=15}
|> Map.add "newest" { in_spam=5; in_ham=12}
|> Map.add "newly" { in_spam=1; in_ham=8}
|> Map.add "news" { in_spam=38; in_ham=227}
|> Map.add "newsisfree" { in_spam=0; in_ham=307}
|> Map.add "newsletter" { in_spam=15; in_ham=39}
|> Map.add "newsletters" { in_spam=10; in_ham=17}
|> Map.add "newspaper" { in_spam=5; in_ham=16}
|> Map.add "next" { in_spam=54; in_ham=173}
|> Map.add "nice" { in_spam=7; in_ham=95}
|> Map.add "nick" { in_spam=0; in_ham=9}
|> Map.add "nigeria" { in_spam=18; in_ham=2}
|> Map.add "nigerian" { in_spam=5; in_ham=8}
|> Map.add "night" { in_spam=4; in_ham=49}
|> Map.add "nightly" { in_spam=2; in_ham=14}
|> Map.add "nightmare" { in_spam=0; in_ham=9}
|> Map.add "nights" { in_spam=3; in_ham=6}
|> Map.add "nine" { in_spam=2; in_ham=8}
|> Map.add "nmh" { in_spam=0; in_ham=17}
|> Map.add "nobel" { in_spam=0; in_ham=10}
|> Map.add "nobody" { in_spam=6; in_ham=53}
|> Map.add "nodes" { in_spam=0; in_ham=8}
|> Map.add "noise" { in_spam=1; in_ham=11}
|> Map.add "non" { in_spam=5; in_ham=8}
|> Map.add "non-spam" { in_spam=0; in_ham=23}
|> Map.add "non-text" { in_spam=0; in_ham=15}
|> Map.add "none" { in_spam=33; in_ham=54}
|> Map.add "nonsense" { in_spam=0; in_ham=11}
|> Map.add "nonspam" { in_spam=0; in_ham=12}
|> Map.add "nope" { in_spam=0; in_ham=13}
|> Map.add "nor" { in_spam=6; in_ham=36}
|> Map.add "normal" { in_spam=13; in_ham=64}
|> Map.add "normally" { in_spam=4; in_ham=32}
|> Map.add "norte" { in_spam=0; in_ham=42}
|> Map.add "north" { in_spam=11; in_ham=23}
|> Map.add "northern" { in_spam=2; in_ham=14}
|> Map.add "norton" { in_spam=19; in_ham=5}
|> Map.add "noshade" { in_spam=23; in_ham=2}
|> Map.add "not" { in_spam=288; in_ham=1251}
|> Map.add "notably" { in_spam=0; in_ham=11}
|> Map.add "note" { in_spam=35; in_ham=69}
|> Map.add "noted" { in_spam=0; in_ham=21}
|> Map.add "notes" { in_spam=7; in_ham=26}
|> Map.add "nothing" { in_spam=34; in_ham=147}
|> Map.add "notice" { in_spam=70; in_ham=35}
|> Map.add "noticed" { in_spam=6; in_ham=43}
|> Map.add "notification" { in_spam=7; in_ham=6}
|> Map.add "notified" { in_spam=18; in_ham=4}
|> Map.add "noting" { in_spam=1; in_ham=10}
|> Map.add "notion" { in_spam=1; in_ham=10}
|> Map.add "november" { in_spam=2; in_ham=12}
|> Map.add "now" { in_spam=189; in_ham=578}
|> Map.add "nowadays" { in_spam=0; in_ham=18}
|> Map.add "nowhere" { in_spam=2; in_ham=7}
|> Map.add "nuclear" { in_spam=1; in_ham=10}
|> Map.add "null" { in_spam=0; in_ham=35}
|> Map.add "number" { in_spam=70; in_ham=157}
|> Map.add "numbers" { in_spam=34; in_ham=54}
|> Map.add "numerous" { in_spam=4; in_ham=16}
|> Map.add "nvidia" { in_spam=0; in_ham=10}
|> Map.add "nxieaa" { in_spam=0; in_ham=51}
|> Map.add "nytimes" { in_spam=0; in_ham=20}
|> Map.add "object" { in_spam=1; in_ham=42}
|> Map.add "objections" { in_spam=1; in_ham=8}
|> Map.add "objective" { in_spam=1; in_ham=7}
|> Map.add "objects" { in_spam=0; in_ham=8}
|> Map.add "obligated" { in_spam=1; in_ham=7}
|> Map.add "obligation" { in_spam=27; in_ham=7}
|> Map.add "obligations" { in_spam=6; in_ham=6}
|> Map.add "obscure" { in_spam=0; in_ham=10}
|> Map.add "observation" { in_spam=1; in_ham=7}
|> Map.add "obtain" { in_spam=11; in_ham=8}
|> Map.add "obtained" { in_spam=19; in_ham=1}
|> Map.add "obvious" { in_spam=0; in_ham=52}
|> Map.add "obviously" { in_spam=0; in_ham=40}
|> Map.add "occasion" { in_spam=1; in_ham=7}
|> Map.add "occasional" { in_spam=0; in_ham=13}
|> Map.add "occasionally" { in_spam=1; in_ham=10}
|> Map.add "occupation" { in_spam=4; in_ham=6}
|> Map.add "occur" { in_spam=0; in_ham=10}
|> Map.add "occurred" { in_spam=0; in_ham=14}
|> Map.add "occurs" { in_spam=1; in_ham=14}
|> Map.add "ocean" { in_spam=2; in_ham=7}
|> Map.add "oct" { in_spam=3; in_ham=84}
|> Map.add "october" { in_spam=6; in_ham=75}
|> Map.add "odd" { in_spam=0; in_ham=30}
|> Map.add "odds" { in_spam=0; in_ham=13}
|> Map.add "off" { in_spam=42; in_ham=211}
|> Map.add "offensive" { in_spam=4; in_ham=10}
|> Map.add "offer" { in_spam=106; in_ham=48}
|> Map.add "offered" { in_spam=8; in_ham=14}
|> Map.add "offering" { in_spam=14; in_ham=17}
|> Map.add "offers" { in_spam=76; in_ham=21}
|> Map.add "office" { in_spam=38; in_ham=52}
|> Map.add "officer" { in_spam=1; in_ham=12}
|> Map.add "offices" { in_spam=0; in_ham=15}
|> Map.add "official" { in_spam=6; in_ham=40}
|> Map.add "officially" { in_spam=1; in_ham=11}
|> Map.add "officials" { in_spam=6; in_ham=41}
|> Map.add "offspring" { in_spam=0; in_ham=13}
|> Map.add "often" { in_spam=8; in_ham=107}
|> Map.add "ogle" { in_spam=0; in_ham=9}
|> Map.add "oil" { in_spam=13; in_ham=12}
|> Map.add "okay" { in_spam=2; in_ham=26}
|> Map.add "old" { in_spam=45; in_ham=255}
|> Map.add "older" { in_spam=5; in_ham=17}
|> Map.add "oldest" { in_spam=0; in_ham=10}
|> Map.add "omega" { in_spam=0; in_ham=8}
|> Map.add "on-line" { in_spam=5; in_ham=15}
|> Map.add "once" { in_spam=57; in_ham=223}
|> Map.add "one" { in_spam=173; in_ham=659}
|> Map.add "one's" { in_spam=1; in_ham=14}
|> Map.add "ones" { in_spam=2; in_ham=57}
|> Map.add "online" { in_spam=82; in_ham=71}
|> Map.add "only" { in_spam=161; in_ham=560}
|> Map.add "ontario" { in_spam=2; in_ham=10}
|> Map.add "onto" { in_spam=2; in_ham=19}
|> Map.add "oooops" { in_spam=0; in_ham=8}
|> Map.add "oops" { in_spam=3; in_ham=12}
|> Map.add "open" { in_spam=36; in_ham=117}
|> Map.add "opened" { in_spam=8; in_ham=17}
|> Map.add "opening" { in_spam=3; in_ham=11}
|> Map.add "opens" { in_spam=1; in_ham=10}
|> Map.add "openssh" { in_spam=0; in_ham=11}
|> Map.add "openssl" { in_spam=0; in_ham=8}
|> Map.add "operate" { in_spam=7; in_ham=15}
|> Map.add "operating" { in_spam=6; in_ham=29}
|> Map.add "operation" { in_spam=0; in_ham=29}
|> Map.add "operational" { in_spam=1; in_ham=9}
|> Map.add "operations" { in_spam=4; in_ham=16}
|> Map.add "opinion" { in_spam=6; in_ham=39}
|> Map.add "opinions" { in_spam=1; in_ham=17}
|> Map.add "opportunity" { in_spam=59; in_ham=25}
|> Map.add "oppose" { in_spam=1; in_ham=7}
|> Map.add "opposed" { in_spam=5; in_ham=10}
|> Map.add "opposite" { in_spam=1; in_ham=19}
|> Map.add "opposition" { in_spam=6; in_ham=9}
|> Map.add "opt" { in_spam=3; in_ham=7}
|> Map.add "opt-in" { in_spam=36; in_ham=2}
|> Map.add "opted" { in_spam=21; in_ham=4}
|> Map.add "optical" { in_spam=1; in_ham=14}
|> Map.add "optimization" { in_spam=0; in_ham=15}
|> Map.add "optimized" { in_spam=0; in_ham=13}
|> Map.add "optimizing" { in_spam=0; in_ham=9}
|> Map.add "option" { in_spam=12; in_ham=55}
|> Map.add "optional" { in_spam=4; in_ham=19}
|> Map.add "options" { in_spam=10; in_ham=36}
|> Map.add "optout" { in_spam=63; in_ham=0}
|> Map.add "order" { in_spam=77; in_ham=87}
|> Map.add "ordered" { in_spam=15; in_ham=8}
|> Map.add "ordering" { in_spam=11; in_ham=2}
|> Map.add "orders" { in_spam=22; in_ham=14}
|> Map.add "ordinary" { in_spam=9; in_ham=4}
|> Map.add "org" { in_spam=32; in_ham=432}
|> Map.add "organization" { in_spam=4; in_ham=20}
|> Map.add "organized" { in_spam=3; in_ham=9}
|> Map.add "original" { in_spam=24; in_ham=200}
|> Map.add "originally" { in_spam=9; in_ham=17}
|> Map.add "orleans" { in_spam=2; in_ham=11}
|> Map.add "osdn" { in_spam=3; in_ham=156}
|> Map.add "osi" { in_spam=1; in_ham=8}
|> Map.add "oss" { in_spam=1; in_ham=20}
|> Map.add "other" { in_spam=92; in_ham=561}
|> Map.add "others" { in_spam=23; in_ham=116}
|> Map.add "otherwise" { in_spam=4; in_ham=47}
|> Map.add "otoh" { in_spam=0; in_ham=11}
|> Map.add "ouch" { in_spam=0; in_ham=14}
|> Map.add "ought" { in_spam=0; in_ham=23}
|> Map.add "our" { in_spam=325; in_ham=195}
|> Map.add "ourselves" { in_spam=6; in_ham=9}
|> Map.add "out" { in_spam=208; in_ham=651}
|> Map.add "outlook" { in_spam=4; in_ham=17}
|> Map.add "output" { in_spam=1; in_ham=39}
|> Map.add "outside" { in_spam=8; in_ham=50}
|> Map.add "over" { in_spam=115; in_ham=285}
|> Map.add "over-sized" { in_spam=0; in_ham=10}
|> Map.add "overall" { in_spam=4; in_ham=20}
|> Map.add "overlook" { in_spam=16; in_ham=0}
|> Map.add "overwhelming" { in_spam=2; in_ham=10}
|> Map.add "owen" { in_spam=0; in_ham=47}
|> Map.add "owl" { in_spam=0; in_ham=9}
|> Map.add "own" { in_spam=63; in_ham=211}
|> Map.add "owned" { in_spam=6; in_ham=8}
|> Map.add "owner" { in_spam=12; in_ham=10}
|> Map.add "owners" { in_spam=20; in_ham=14}
|> Map.add "pablo" { in_spam=0; in_ham=22}
|> Map.add "pacific" { in_spam=5; in_ham=7}
|> Map.add "pack" { in_spam=2; in_ham=19}
|> Map.add "package" { in_spam=25; in_ham=127}
|> Map.add "packages" { in_spam=3; in_ham=109}
|> Map.add "packaging" { in_spam=1; in_ham=10}
|> Map.add "packet" { in_spam=0; in_ham=15}
|> Map.add "packets" { in_spam=0; in_ham=10}
|> Map.add "page" { in_spam=30; in_ham=167}
|> Map.add "pages" { in_spam=9; in_ham=39}
|> Map.add "paid" { in_spam=38; in_ham=38}
|> Map.add "pain" { in_spam=0; in_ham=23}
|> Map.add "paint" { in_spam=1; in_ham=9}
|> Map.add "pair" { in_spam=2; in_ham=14}
|> Map.add "pakistan" { in_spam=1; in_ham=8}
|> Map.add "palestinian" { in_spam=0; in_ham=16}
|> Map.add "palestinians" { in_spam=0; in_ham=13}
|> Map.add "panasas" { in_spam=0; in_ham=30}
|> Map.add "panel" { in_spam=15; in_ham=16}
|> Map.add "panu" { in_spam=0; in_ham=9}
|> Map.add "paper" { in_spam=14; in_ham=31}
|> Map.add "papers" { in_spam=8; in_ham=11}
|> Map.add "paragraph" { in_spam=8; in_ham=5}
|> Map.add "paramount" { in_spam=1; in_ham=8}
|> Map.add "parents" { in_spam=5; in_ham=16}
|> Map.add "park" { in_spam=2; in_ham=34}
|> Map.add "parse" { in_spam=0; in_ham=9}
|> Map.add "parsing" { in_spam=0; in_ham=19}
|> Map.add "part" { in_spam=34; in_ham=152}
|> Map.add "partial" { in_spam=4; in_ham=6}
|> Map.add "participants" { in_spam=5; in_ham=5}
|> Map.add "participate" { in_spam=13; in_ham=4}
|> Map.add "particular" { in_spam=3; in_ham=86}
|> Map.add "particularly" { in_spam=1; in_ham=54}
|> Map.add "parties" { in_spam=11; in_ham=18}
|> Map.add "partition" { in_spam=0; in_ham=15}
|> Map.add "partitioned" { in_spam=0; in_ham=9}
|> Map.add "partitions" { in_spam=0; in_ham=11}
|> Map.add "partner" { in_spam=21; in_ham=21}
|> Map.add "partners" { in_spam=18; in_ham=31}
|> Map.add "partnership" { in_spam=7; in_ham=9}
|> Map.add "parts" { in_spam=3; in_ham=46}
|> Map.add "party" { in_spam=37; in_ham=58}
|> Map.add "pass" { in_spam=12; in_ham=26}
|> Map.add "passed" { in_spam=19; in_ham=15}
|> Map.add "passes" { in_spam=2; in_ham=20}
|> Map.add "passing" { in_spam=2; in_ham=20}
|> Map.add "passphrase" { in_spam=0; in_ham=8}
|> Map.add "password" { in_spam=8; in_ham=10}
|> Map.add "passwords" { in_spam=1; in_ham=8}
|> Map.add "past" { in_spam=34; in_ham=89}
|> Map.add "paste" { in_spam=16; in_ham=19}
|> Map.add "patch" { in_spam=7; in_ham=47}
|> Map.add "patches" { in_spam=5; in_ham=12}
|> Map.add "patent" { in_spam=0; in_ham=19}
|> Map.add "path" { in_spam=2; in_ham=62}
|> Map.add "pattern" { in_spam=0; in_ham=11}
|> Map.add "patterns" { in_spam=1; in_ham=18}
|> Map.add "paul" { in_spam=1; in_ham=51}
|> Map.add "pause" { in_spam=0; in_ham=11}
|> Map.add "pay" { in_spam=76; in_ham=65}
|> Map.add "paying" { in_spam=26; in_ham=22}
|> Map.add "payment" { in_spam=20; in_ham=6}
|> Map.add "payments" { in_spam=12; in_ham=2}
|> Map.add "pays" { in_spam=3; in_ham=7}
|> Map.add "pc's" { in_spam=16; in_ham=1}
|> Map.add "pdf" { in_spam=2; in_ham=9}
|> Map.add "pdt" { in_spam=0; in_ham=14}
|> Map.add "peace" { in_spam=3; in_ham=12}
|> Map.add "peltonen" { in_spam=0; in_ham=8}
|> Map.add "pending" { in_spam=1; in_ham=9}
|> Map.add "pennsylvania" { in_spam=3; in_ham=8}
|> Map.add "people" { in_spam=80; in_ham=416}
|> Map.add "people's" { in_spam=4; in_ham=24}
|> Map.add "peoples" { in_spam=3; in_ham=7}
|> Map.add "per" { in_spam=56; in_ham=97}
|> Map.add "percent" { in_spam=3; in_ham=26}
|> Map.add "percentage" { in_spam=8; in_ham=13}
|> Map.add "percentages" { in_spam=7; in_ham=8}
|> Map.add "perception" { in_spam=3; in_ham=7}
|> Map.add "perfect" { in_spam=23; in_ham=15}
|> Map.add "perfectly" { in_spam=0; in_ham=33}
|> Map.add "performance" { in_spam=17; in_ham=67}
|> Map.add "performed" { in_spam=0; in_ham=10}
|> Map.add "performing" { in_spam=2; in_ham=9}
|> Map.add "performs" { in_spam=0; in_ham=8}
|> Map.add "perhaps" { in_spam=4; in_ham=99}
|> Map.add "period" { in_spam=17; in_ham=39}
|> Map.add "periodically" { in_spam=9; in_ham=7}
|> Map.add "perl" { in_spam=0; in_ham=134}
|> Map.add "permanent" { in_spam=5; in_ham=14}
|> Map.add "permission" { in_spam=10; in_ham=26}
|> Map.add "permissions" { in_spam=0; in_ham=12}
|> Map.add "permit" { in_spam=3; in_ham=12}
|> Map.add "permitted" { in_spam=1; in_ham=16}
|> Map.add "persist" { in_spam=0; in_ham=8}
|> Map.add "person" { in_spam=30; in_ham=88}
|> Map.add "personal" { in_spam=63; in_ham=78}
|> Map.add "personally" { in_spam=9; in_ham=33}
|> Map.add "persons" { in_spam=5; in_ham=6}
|> Map.add "perspective" { in_spam=2; in_ham=13}
|> Map.add "peru" { in_spam=2; in_ham=8}
|> Map.add "pet" { in_spam=5; in_ham=7}
|> Map.add "peter" { in_spam=2; in_ham=40}
|> Map.add "peters" { in_spam=0; in_ham=16}
|> Map.add "pgp" { in_spam=0; in_ham=114}
|> Map.add "phase" { in_spam=0; in_ham=8}
|> Map.add "phd" { in_spam=1; in_ham=14}
|> Map.add "phil" { in_spam=0; in_ham=16}
|> Map.add "philippines" { in_spam=3; in_ham=8}
|> Map.add "phone" { in_spam=108; in_ham=208}
|> Map.add "phones" { in_spam=3; in_ham=18}
|> Map.add "photo" { in_spam=13; in_ham=15}
|> Map.add "photos" { in_spam=2; in_ham=23}
|> Map.add "php" { in_spam=45; in_ham=62}
|> Map.add "phrase" { in_spam=0; in_ham=10}
|> Map.add "physical" { in_spam=1; in_ham=27}
|> Map.add "physically" { in_spam=1; in_ham=10}
|> Map.add "physics" { in_spam=0; in_ham=8}
|> Map.add "picasso" { in_spam=0; in_ham=45}
|> Map.add "pick" { in_spam=5; in_ham=55}
|> Map.add "picked" { in_spam=3; in_ham=16}
|> Map.add "picking" { in_spam=5; in_ham=6}
|> Map.add "pickle" { in_spam=0; in_ham=22}
|> Map.add "picks" { in_spam=1; in_ham=8}
|> Map.add "pics" { in_spam=8; in_ham=6}
|> Map.add "picture" { in_spam=9; in_ham=34}
|> Map.add "pictures" { in_spam=1; in_ham=19}
|> Map.add "piece" { in_spam=3; in_ham=31}
|> Map.add "pioneered" { in_spam=0; in_ham=8}
|> Map.add "pioneering" { in_spam=0; in_ham=24}
|> Map.add "pipe" { in_spam=3; in_ham=8}
|> Map.add "piracy" { in_spam=1; in_ham=9}
|> Map.add "pitfalls" { in_spam=0; in_ham=14}
|> Map.add "place" { in_spam=39; in_ham=146}
|> Map.add "placed" { in_spam=11; in_ham=17}
|> Map.add "places" { in_spam=14; in_ham=50}
|> Map.add "plain" { in_spam=10; in_ham=33}
|> Map.add "plan" { in_spam=48; in_ham=51}
|> Map.add "planet" { in_spam=2; in_ham=17}
|> Map.add "planned" { in_spam=1; in_ham=13}
|> Map.add "planning" { in_spam=11; in_ham=28}
|> Map.add "plans" { in_spam=12; in_ham=33}
|> Map.add "plant" { in_spam=1; in_ham=8}
|> Map.add "planta" { in_spam=0; in_ham=42}
|> Map.add "platform" { in_spam=1; in_ham=81}
|> Map.add "platforms" { in_spam=0; in_ham=14}
|> Map.add "plausible" { in_spam=0; in_ham=10}
|> Map.add "play" { in_spam=16; in_ham=74}
|> Map.add "playback" { in_spam=1; in_ham=9}
|> Map.add "played" { in_spam=4; in_ham=21}
|> Map.add "player" { in_spam=2; in_ham=20}
|> Map.add "players" { in_spam=4; in_ham=17}
|> Map.add "playing" { in_spam=14; in_ham=46}
|> Map.add "plays" { in_spam=2; in_ham=8}
|> Map.add "please" { in_spam=299; in_ham=152}
|> Map.add "pleased" { in_spam=3; in_ham=8}
|> Map.add "plenty" { in_spam=5; in_ham=21}
|> Map.add "plot" { in_spam=5; in_ham=5}
|> Map.add "plug" { in_spam=2; in_ham=9}
|> Map.add "plugin" { in_spam=0; in_ham=17}
|> Map.add "plugins" { in_spam=0; in_ham=18}
|> Map.add "plus" { in_spam=31; in_ham=29}
|> Map.add "pobox" { in_spam=0; in_ham=23}
|> Map.add "pocket" { in_spam=13; in_ham=4}
|> Map.add "point" { in_spam=24; in_ham=194}
|> Map.add "pointed" { in_spam=0; in_ham=16}
|> Map.add "pointing" { in_spam=0; in_ham=21}
|> Map.add "points" { in_spam=9; in_ham=56}
|> Map.add "police" { in_spam=4; in_ham=37}
|> Map.add "policies" { in_spam=11; in_ham=16}
|> Map.add "policy" { in_spam=30; in_ham=36}
|> Map.add "political" { in_spam=13; in_ham=65}
|> Map.add "politically" { in_spam=0; in_ham=9}
|> Map.add "politician" { in_spam=0; in_ham=9}
|> Map.add "politicians" { in_spam=0; in_ham=14}
|> Map.add "politics" { in_spam=2; in_ham=55}
|> Map.add "poll" { in_spam=0; in_ham=12}
|> Map.add "ponce" { in_spam=0; in_ham=8}
|> Map.add "poor" { in_spam=8; in_ham=30}
|> Map.add "pop" { in_spam=7; in_ham=34}
|> Map.add "popular" { in_spam=14; in_ham=37}
|> Map.add "popularity" { in_spam=7; in_ham=4}
|> Map.add "population" { in_spam=7; in_ham=44}
|> Map.add "populations" { in_spam=1; in_ham=7}
|> Map.add "porn" { in_spam=9; in_ham=6}
|> Map.add "port" { in_spam=0; in_ham=26}
|> Map.add "portable" { in_spam=3; in_ham=9}
|> Map.add "ported" { in_spam=0; in_ham=9}
|> Map.add "porters" { in_spam=0; in_ham=16}
|> Map.add "portfolio" { in_spam=11; in_ham=9}
|> Map.add "portion" { in_spam=6; in_ham=9}
|> Map.add "portions" { in_spam=0; in_ham=15}
|> Map.add "ports" { in_spam=0; in_ham=17}
|> Map.add "position" { in_spam=33; in_ham=27}
|> Map.add "positioning" { in_spam=0; in_ham=8}
|> Map.add "positions" { in_spam=1; in_ham=15}
|> Map.add "positive" { in_spam=3; in_ham=28}
|> Map.add "positives" { in_spam=0; in_ham=22}
|> Map.add "possession" { in_spam=7; in_ham=4}
|> Map.add "possibility" { in_spam=1; in_ham=18}
|> Map.add "possible" { in_spam=33; in_ham=133}
|> Map.add "possibly" { in_spam=2; in_ham=29}
|> Map.add "post" { in_spam=65; in_ham=91}
|> Map.add "postal" { in_spam=13; in_ham=1}
|> Map.add "posted" { in_spam=2; in_ham=100}
|> Map.add "postgresql" { in_spam=1; in_ham=8}
|> Map.add "posting" { in_spam=1; in_ham=23}
|> Map.add "posts" { in_spam=1; in_ham=14}
|> Map.add "potential" { in_spam=20; in_ham=40}
|> Map.add "potentially" { in_spam=3; in_ham=17}
|> Map.add "pound" { in_spam=2; in_ham=7}
|> Map.add "poverty" { in_spam=2; in_ham=23}
|> Map.add "power" { in_spam=17; in_ham=60}
|> Map.add "powered" { in_spam=2; in_ham=7}
|> Map.add "powerful" { in_spam=17; in_ham=28}
|> Map.add "powerhouse" { in_spam=2; in_ham=8}
|> Map.add "powers" { in_spam=2; in_ham=27}
|> Map.add "practical" { in_spam=7; in_ham=16}
|> Map.add "practically" { in_spam=3; in_ham=15}
|> Map.add "practice" { in_spam=3; in_ham=42}
|> Map.add "practices" { in_spam=8; in_ham=15}
|> Map.add "prakash" { in_spam=0; in_ham=8}
|> Map.add "pre" { in_spam=3; in_ham=8}
|> Map.add "precisely" { in_spam=2; in_ham=13}
|> Map.add "predict" { in_spam=6; in_ham=6}
|> Map.add "predicting" { in_spam=0; in_ham=45}
|> Map.add "prefer" { in_spam=6; in_ham=33}
|> Map.add "preferences" { in_spam=0; in_ham=85}
|> Map.add "preferred" { in_spam=6; in_ham=12}
|> Map.add "prefix" { in_spam=1; in_ham=7}
|> Map.add "prefs" { in_spam=0; in_ham=10}
|> Map.add "premium" { in_spam=19; in_ham=3}
|> Map.add "prepare" { in_spam=6; in_ham=7}
|> Map.add "prepared" { in_spam=2; in_ham=22}
|> Map.add "preparing" { in_spam=2; in_ham=16}
|> Map.add "presence" { in_spam=1; in_ham=16}
|> Map.add "present" { in_spam=22; in_ham=29}
|> Map.add "presented" { in_spam=12; in_ham=7}
|> Map.add "preserve" { in_spam=2; in_ham=10}
|> Map.add "president" { in_spam=24; in_ham=50}
|> Map.add "presidential" { in_spam=0; in_ham=8}
|> Map.add "press" { in_spam=11; in_ham=54}
|> Map.add "pressure" { in_spam=1; in_ham=13}
|> Map.add "presumably" { in_spam=0; in_ham=22}
|> Map.add "presume" { in_spam=0; in_ham=11}
|> Map.add "pretty" { in_spam=9; in_ham=115}
|> Map.add "prevent" { in_spam=7; in_ham=22}
|> Map.add "preventing" { in_spam=0; in_ham=8}
|> Map.add "prevents" { in_spam=0; in_ham=9}
|> Map.add "previous" { in_spam=6; in_ham=35}
|> Map.add "previously" { in_spam=14; in_ham=40}
|> Map.add "prey" { in_spam=15; in_ham=4}
|> Map.add "price" { in_spam=69; in_ham=33}
|> Map.add "priced" { in_spam=4; in_ham=9}
|> Map.add "prices" { in_spam=34; in_ham=16}
|> Map.add "pricing" { in_spam=10; in_ham=5}
|> Map.add "primarily" { in_spam=2; in_ham=16}
|> Map.add "primary" { in_spam=15; in_ham=27}
|> Map.add "prime" { in_spam=2; in_ham=8}
|> Map.add "principle" { in_spam=1; in_ham=11}
|> Map.add "principles" { in_spam=4; in_ham=7}
|> Map.add "print" { in_spam=15; in_ham=43}
|> Map.add "printed" { in_spam=3; in_ham=9}
|> Map.add "printer" { in_spam=5; in_ham=10}
|> Map.add "printing" { in_spam=5; in_ham=12}
|> Map.add "prior" { in_spam=4; in_ham=28}
|> Map.add "priority" { in_spam=3; in_ham=16}
|> Map.add "privacy" { in_spam=18; in_ham=13}
|> Map.add "private" { in_spam=56; in_ham=40}
|> Map.add "privately" { in_spam=1; in_ham=11}
|> Map.add "privilege" { in_spam=3; in_ham=6}
|> Map.add "privileged" { in_spam=0; in_ham=9}
|> Map.add "privileges" { in_spam=0; in_ham=8}
|> Map.add "prize" { in_spam=2; in_ham=12}
|> Map.add "pro" { in_spam=9; in_ham=8}
|> Map.add "prob" { in_spam=0; in_ham=8}
|> Map.add "probability" { in_spam=0; in_ham=12}
|> Map.add "probably" { in_spam=15; in_ham=225}
|> Map.add "problem" { in_spam=22; in_ham=281}
|> Map.add "problems" { in_spam=27; in_ham=144}
|> Map.add "proc" { in_spam=0; in_ham=15}
|> Map.add "procedure" { in_spam=0; in_ham=22}
|> Map.add "procedures" { in_spam=8; in_ham=4}
|> Map.add "proceed" { in_spam=7; in_ham=8}
|> Map.add "process" { in_spam=24; in_ham=82}
|> Map.add "processed" { in_spam=8; in_ham=5}
|> Map.add "processes" { in_spam=2; in_ham=34}
|> Map.add "processing" { in_spam=11; in_ham=36}
|> Map.add "processor" { in_spam=1; in_ham=7}
|> Map.add "procmail" { in_spam=0; in_ham=52}
|> Map.add "procmailrc" { in_spam=0; in_ham=17}
|> Map.add "produce" { in_spam=5; in_ham=26}
|> Map.add "produced" { in_spam=2; in_ham=29}
|> Map.add "producers" { in_spam=4; in_ham=8}
|> Map.add "producing" { in_spam=1; in_ham=9}
|> Map.add "product" { in_spam=49; in_ham=61}
|> Map.add "production" { in_spam=1; in_ham=22}
|> Map.add "productive" { in_spam=0; in_ham=14}
|> Map.add "products" { in_spam=70; in_ham=32}
|> Map.add "professional" { in_spam=93; in_ham=23}
|> Map.add "professor" { in_spam=4; in_ham=9}
|> Map.add "profile" { in_spam=4; in_ham=16}
|> Map.add "profit" { in_spam=16; in_ham=12}
|> Map.add "profitable" { in_spam=29; in_ham=4}
|> Map.add "profits" { in_spam=17; in_ham=5}
|> Map.add "progid" { in_spam=31; in_ham=0}
|> Map.add "program" { in_spam=52; in_ham=72}
|> Map.add "programme" { in_spam=3; in_ham=11}
|> Map.add "programmer" { in_spam=0; in_ham=18}
|> Map.add "programmers" { in_spam=4; in_ham=8}
|> Map.add "programming" { in_spam=3; in_ham=35}
|> Map.add "programs" { in_spam=36; in_ham=33}
|> Map.add "progress" { in_spam=9; in_ham=31}
|> Map.add "prohibited" { in_spam=8; in_ham=6}
|> Map.add "project" { in_spam=10; in_ham=80}
|> Map.add "projects" { in_spam=10; in_ham=30}
|> Map.add "proliferate" { in_spam=1; in_ham=7}
|> Map.add "promiscuity" { in_spam=0; in_ham=13}
|> Map.add "promiscuous" { in_spam=0; in_ham=18}
|> Map.add "promise" { in_spam=16; in_ham=27}
|> Map.add "promised" { in_spam=7; in_ham=15}
|> Map.add "promises" { in_spam=1; in_ham=14}
|> Map.add "promising" { in_spam=0; in_ham=12}
|> Map.add "promote" { in_spam=11; in_ham=10}
|> Map.add "promoting" { in_spam=1; in_ham=11}
|> Map.add "promotion" { in_spam=25; in_ham=3}
|> Map.add "prompt" { in_spam=20; in_ham=10}
|> Map.add "proof" { in_spam=4; in_ham=16}
|> Map.add "proper" { in_spam=12; in_ham=24}
|> Map.add "properly" { in_spam=3; in_ham=10}
|> Map.add "properties" { in_spam=13; in_ham=5}
|> Map.add "property" { in_spam=7; in_ham=29}
|> Map.add "proposal" { in_spam=21; in_ham=5}
|> Map.add "propose" { in_spam=4; in_ham=11}
|> Map.add "proposed" { in_spam=12; in_ham=26}
|> Map.add "proprietary" { in_spam=2; in_ham=20}
|> Map.add "prostitute" { in_spam=0; in_ham=9}
|> Map.add "protect" { in_spam=31; in_ham=37}
|> Map.add "protected" { in_spam=3; in_ham=19}
|> Map.add "protecting" { in_spam=3; in_ham=10}
|> Map.add "protection" { in_spam=16; in_ham=28}
|> Map.add "protest" { in_spam=1; in_ham=9}
|> Map.add "protesting" { in_spam=1; in_ham=10}
|> Map.add "protests" { in_spam=1; in_ham=10}
|> Map.add "protocol" { in_spam=2; in_ham=17}
|> Map.add "protocols" { in_spam=0; in_ham=8}
|> Map.add "prototype" { in_spam=0; in_ham=8}
|> Map.add "prove" { in_spam=1; in_ham=9}
|> Map.add "proven" { in_spam=24; in_ham=23}
|> Map.add "provide" { in_spam=52; in_ham=86}
|> Map.add "provided" { in_spam=16; in_ham=58}
|> Map.add "provider" { in_spam=2; in_ham=16}
|> Map.add "providers" { in_spam=3; in_ham=8}
|> Map.add "provides" { in_spam=9; in_ham=40}
|> Map.add "providing" { in_spam=12; in_ham=25}
|> Map.add "province" { in_spam=1; in_ham=13}

