open Database
open BayesianBody_001
let db = db 
|> Map.add "execution" { in_spam=7; in_ham=13}
|> Map.add "executive" { in_spam=6; in_ham=25}
|> Map.add "executives" { in_spam=4; in_ham=16}
|> Map.add "exercise" { in_spam=10; in_ham=9}
|> Map.add "exist" { in_spam=5; in_ham=56}
|> Map.add "existed" { in_spam=1; in_ham=19}
|> Map.add "existence" { in_spam=6; in_ham=16}
|> Map.add "existing" { in_spam=9; in_ham=48}
|> Map.add "exists" { in_spam=3; in_ham=31}
|> Map.add "exit" { in_spam=0; in_ham=21}
|> Map.add "exmh" { in_spam=0; in_ham=160}
|> Map.add "exmh-users" { in_spam=0; in_ham=86}
|> Map.add "exmh-workers" { in_spam=0; in_ham=55}
|> Map.add "expand" { in_spam=3; in_ham=13}
|> Map.add "expanding" { in_spam=4; in_ham=6}
|> Map.add "expect" { in_spam=17; in_ham=52}
|> Map.add "expected" { in_spam=4; in_ham=42}
|> Map.add "expecting" { in_spam=6; in_ham=6}
|> Map.add "expects" { in_spam=0; in_ham=14}
|> Map.add "expense" { in_spam=14; in_ham=14}
|> Map.add "expenses" { in_spam=13; in_ham=6}
|> Map.add "expensive" { in_spam=5; in_ham=26}
|> Map.add "experience" { in_spam=27; in_ham=112}
|> Map.add "experienced" { in_spam=1; in_ham=14}
|> Map.add "experiences" { in_spam=3; in_ham=10}
|> Map.add "experiment" { in_spam=1; in_ham=22}
|> Map.add "expert" { in_spam=7; in_ham=16}
|> Map.add "expertise" { in_spam=5; in_ham=9}
|> Map.add "experts" { in_spam=12; in_ham=21}
|> Map.add "explain" { in_spam=3; in_ham=38}
|> Map.add "explained" { in_spam=4; in_ham=31}
|> Map.add "explains" { in_spam=0; in_ham=18}
|> Map.add "explanation" { in_spam=4; in_ham=22}
|> Map.add "explicit" { in_spam=0; in_ham=10}
|> Map.add "explicitly" { in_spam=1; in_ham=21}
|> Map.add "exploit" { in_spam=0; in_ham=9}
|> Map.add "exploited" { in_spam=0; in_ham=11}
|> Map.add "explore" { in_spam=4; in_ham=8}
|> Map.add "explorer" { in_spam=1; in_ham=10}
|> Map.add "export" { in_spam=2; in_ham=11}
|> Map.add "express" { in_spam=7; in_ham=9}
|> Map.add "expressed" { in_spam=2; in_ham=8}
|> Map.add "expression" { in_spam=0; in_ham=16}
|> Map.add "ext" { in_spam=37; in_ham=6}
|> Map.add "extend" { in_spam=1; in_ham=8}
|> Map.add "extended" { in_spam=9; in_ham=15}
|> Map.add "extension" { in_spam=0; in_ham=9}
|> Map.add "extensions" { in_spam=6; in_ham=6}
|> Map.add "extensive" { in_spam=2; in_ham=20}
|> Map.add "extent" { in_spam=1; in_ham=15}
|> Map.add "external" { in_spam=2; in_ham=18}
|> Map.add "extra" { in_spam=12; in_ham=37}
|> Map.add "extract" { in_spam=4; in_ham=6}
|> Map.add "extreme" { in_spam=3; in_ham=18}
|> Map.add "extremely" { in_spam=15; in_ham=29}
|> Map.add "eye" { in_spam=4; in_ham=12}
|> Map.add "eyes" { in_spam=2; in_ham=16}
|> Map.add "f-n" { in_spam=0; in_ham=15}
|> Map.add "f-p" { in_spam=0; in_ham=10}
|> Map.add "face" { in_spam=190; in_ham=52}
|> Map.add "faced" { in_spam=0; in_ham=11}
|> Map.add "faces" { in_spam=5; in_ham=6}
|> Map.add "facilitate" { in_spam=3; in_ham=10}
|> Map.add "facing" { in_spam=1; in_ham=13}
|> Map.add "fact" { in_spam=30; in_ham=120}
|> Map.add "factor" { in_spam=1; in_ham=14}
|> Map.add "factors" { in_spam=3; in_ham=7}
|> Map.add "facts" { in_spam=12; in_ham=16}
|> Map.add "fahrl" { in_spam=0; in_ham=8}
|> Map.add "fail" { in_spam=7; in_ham=31}
|> Map.add "failed" { in_spam=6; in_ham=46}
|> Map.add "failing" { in_spam=1; in_ham=14}
|> Map.add "fails" { in_spam=0; in_ham=39}
|> Map.add "failure" { in_spam=5; in_ham=34}
|> Map.add "fair" { in_spam=16; in_ham=34}
|> Map.add "fairly" { in_spam=0; in_ham=26}
|> Map.add "faith" { in_spam=2; in_ham=12}
|> Map.add "fake" { in_spam=0; in_ham=12}
|> Map.add "fall" { in_spam=19; in_ham=67}
|> Map.add "fallen" { in_spam=1; in_ham=7}
|> Map.add "falling" { in_spam=1; in_ham=9}
|> Map.add "false" { in_spam=4; in_ham=72}
|> Map.add "familiar" { in_spam=2; in_ham=12}
|> Map.add "families" { in_spam=4; in_ham=12}
|> Map.add "family" { in_spam=50; in_ham=55}
|> Map.add "famous" { in_spam=2; in_ham=17}
|> Map.add "fancy" { in_spam=4; in_ham=8}
|> Map.add "fantasy" { in_spam=4; in_ham=6}
|> Map.add "faq" { in_spam=7; in_ham=10}
|> Map.add "far" { in_spam=17; in_ham=140}
|> Map.add "fark" { in_spam=0; in_ham=29}
|> Map.add "farm" { in_spam=8; in_ham=5}
|> Map.add "farquhar" { in_spam=0; in_ham=41}
|> Map.add "fashion" { in_spam=2; in_ham=9}
|> Map.add "fast" { in_spam=33; in_ham=83}
|> Map.add "faster" { in_spam=11; in_ham=33}
|> Map.add "fastest" { in_spam=23; in_ham=53}
|> Map.add "fastmail" { in_spam=0; in_ham=15}
|> Map.add "fat" { in_spam=9; in_ham=20}
|> Map.add "father" { in_spam=18; in_ham=22}
|> Map.add "fault" { in_spam=1; in_ham=16}
|> Map.add "favor" { in_spam=5; in_ham=23}
|> Map.add "favorite" { in_spam=7; in_ham=22}
|> Map.add "favors" { in_spam=0; in_ham=9}
|> Map.add "favourite" { in_spam=0; in_ham=11}
|> Map.add "fax" { in_spam=59; in_ham=32}
|> Map.add "fbi" { in_spam=1; in_ham=12}
|> Map.add "fcc" { in_spam=1; in_ham=8}
|> Map.add "fear" { in_spam=2; in_ham=13}
|> Map.add "feature" { in_spam=3; in_ham=59}
|> Map.add "featured" { in_spam=9; in_ham=5}
|> Map.add "features" { in_spam=11; in_ham=47}
|> Map.add "feb" { in_spam=1; in_ham=17}
|> Map.add "february" { in_spam=3; in_ham=9}
|> Map.add "fed" { in_spam=8; in_ham=10}
|> Map.add "federal" { in_spam=25; in_ham=34}
|> Map.add "federation" { in_spam=7; in_ham=4}
|> Map.add "fee" { in_spam=17; in_ham=18}
|> Map.add "feed" { in_spam=2; in_ham=24}
|> Map.add "feedback" { in_spam=5; in_ham=22}
|> Map.add "feeding" { in_spam=0; in_ham=9}
|> Map.add "feeds" { in_spam=4; in_ham=8}
|> Map.add "feel" { in_spam=31; in_ham=68}
|> Map.add "feeling" { in_spam=10; in_ham=22}
|> Map.add "feelings" { in_spam=4; in_ham=10}
|> Map.add "feels" { in_spam=0; in_ham=13}
|> Map.add "fees" { in_spam=23; in_ham=5}
|> Map.add "feet" { in_spam=8; in_ham=28}
|> Map.add "fel" { in_spam=0; in_ham=9}
|> Map.add "felinda" { in_spam=0; in_ham=8}
|> Map.add "fell" { in_spam=1; in_ham=10}
|> Map.add "fellow" { in_spam=0; in_ham=11}
|> Map.add "felt" { in_spam=3; in_ham=17}
|> Map.add "female" { in_spam=11; in_ham=19}
|> Map.add "females" { in_spam=1; in_ham=11}
|> Map.add "fetched" { in_spam=0; in_ham=8}
|> Map.add "fetchmail" { in_spam=0; in_ham=11}
|> Map.add "few" { in_spam=39; in_ham=260}
|> Map.add "ffff" { in_spam=31; in_ham=1}
|> Map.add "ffffcc" { in_spam=28; in_ham=1}
|> Map.add "ffffff" { in_spam=134; in_ham=6}
|> Map.add "fiction" { in_spam=0; in_ham=13}
|> Map.add "field" { in_spam=8; in_ham=37}
|> Map.add "fields" { in_spam=4; in_ham=13}
|> Map.add "fight" { in_spam=9; in_ham=28}
|> Map.add "fighting" { in_spam=1; in_ham=16}
|> Map.add "figure" { in_spam=20; in_ham=57}
|> Map.add "figured" { in_spam=2; in_ham=27}
|> Map.add "figures" { in_spam=2; in_ham=21}
|> Map.add "figuring" { in_spam=0; in_ham=8}
|> Map.add "file" { in_spam=10; in_ham=268}
|> Map.add "filed" { in_spam=5; in_ham=23}
|> Map.add "filename" { in_spam=1; in_ham=9}
|> Map.add "files" { in_spam=24; in_ham=198}
|> Map.add "fill" { in_spam=109; in_ham=13}
|> Map.add "filled" { in_spam=3; in_ham=6}
|> Map.add "film" { in_spam=0; in_ham=17}
|> Map.add "filter" { in_spam=3; in_ham=29}
|> Map.add "filtering" { in_spam=0; in_ham=26}
|> Map.add "filters" { in_spam=0; in_ham=18}
|> Map.add "final" { in_spam=4; in_ham=26}
|> Map.add "finally" { in_spam=33; in_ham=57}
|> Map.add "finance" { in_spam=11; in_ham=13}
|> Map.add "financial" { in_spam=73; in_ham=36}
|> Map.add "financially" { in_spam=16; in_ham=4}
|> Map.add "financing" { in_spam=2; in_ham=8}
|> Map.add "find" { in_spam=77; in_ham=267}
|> Map.add "finding" { in_spam=8; in_ham=82}
|> Map.add "findings" { in_spam=7; in_ham=6}
|> Map.add "finds" { in_spam=1; in_ham=18}
|> Map.add "fine" { in_spam=3; in_ham=87}
|> Map.add "finger" { in_spam=0; in_ham=9}
|> Map.add "fingers" { in_spam=1; in_ham=11}
|> Map.add "finish" { in_spam=1; in_ham=8}
|> Map.add "finished" { in_spam=2; in_ham=18}
|> Map.add "finn" { in_spam=0; in_ham=23}
|> Map.add "fire" { in_spam=6; in_ham=21}
|> Map.add "firewall" { in_spam=0; in_ham=20}
|> Map.add "firewalls" { in_spam=0; in_ham=12}
|> Map.add "firm" { in_spam=15; in_ham=23}
|> Map.add "firms" { in_spam=4; in_ham=10}
|> Map.add "first" { in_spam=58; in_ham=349}
|> Map.add "fiscal" { in_spam=2; in_ham=7}
|> Map.add "fish" { in_spam=0; in_ham=13}
|> Map.add "fit" { in_spam=12; in_ham=19}
|> Map.add "fits" { in_spam=0; in_ham=17}
|> Map.add "five" { in_spam=28; in_ham=37}
|> Map.add "fix" { in_spam=1; in_ham=70}
|> Map.add "fixed" { in_spam=11; in_ham=59}
|> Map.add "fixes" { in_spam=0; in_ham=19}
|> Map.add "fixing" { in_spam=1; in_ham=11}
|> Map.add "flag" { in_spam=1; in_ham=24}
|> Map.add "flags" { in_spam=1; in_ham=11}
|> Map.add "flash" { in_spam=5; in_ham=5}
|> Map.add "flexibility" { in_spam=0; in_ham=9}
|> Map.add "flight" { in_spam=4; in_ham=17}
|> Map.add "flip" { in_spam=0; in_ham=9}
|> Map.add "flist" { in_spam=0; in_ham=18}
|> Map.add "flooded" { in_spam=0; in_ham=10}
|> Map.add "floor" { in_spam=2; in_ham=13}
|> Map.add "floppy" { in_spam=13; in_ham=7}
|> Map.add "florida" { in_spam=5; in_ham=9}
|> Map.add "flow" { in_spam=4; in_ham=15}
|> Map.add "fly" { in_spam=5; in_ham=7}
|> Map.add "flying" { in_spam=0; in_ham=8}
|> Map.add "foaf" { in_spam=0; in_ham=8}
|> Map.add "focus" { in_spam=4; in_ham=35}
|> Map.add "focused" { in_spam=1; in_ham=20}
|> Map.add "folder" { in_spam=0; in_ham=105}
|> Map.add "folders" { in_spam=0; in_ham=36}
|> Map.add "folk" { in_spam=0; in_ham=9}
|> Map.add "folks" { in_spam=3; in_ham=75}
|> Map.add "follow" { in_spam=30; in_ham=23}
|> Map.add "followed" { in_spam=14; in_ham=19}
|> Map.add "following" { in_spam=64; in_ham=103}
|> Map.add "follows" { in_spam=3; in_ham=15}
|> Map.add "font" { in_spam=210; in_ham=14}
|> Map.add "font-family" { in_spam=33; in_ham=3}
|> Map.add "font-size" { in_spam=36; in_ham=3}
|> Map.add "font-weight" { in_spam=21; in_ham=2}
|> Map.add "food" { in_spam=4; in_ham=17}
|> Map.add "fool" { in_spam=1; in_ham=8}
|> Map.add "foot" { in_spam=0; in_ham=17}
|> Map.add "for" { in_spam=409; in_ham=1561}
|> Map.add "forbes" { in_spam=0; in_ham=12}
|> Map.add "force" { in_spam=12; in_ham=62}
|> Map.add "forced" { in_spam=4; in_ham=21}
|> Map.add "forces" { in_spam=5; in_ham=31}
|> Map.add "forcing" { in_spam=0; in_ham=9}
|> Map.add "foreach" { in_spam=0; in_ham=8}
|> Map.add "foreign" { in_spam=23; in_ham=24}
|> Map.add "forest" { in_spam=1; in_ham=8}
|> Map.add "forever" { in_spam=7; in_ham=16}
|> Map.add "forged" { in_spam=0; in_ham=9}
|> Map.add "forget" { in_spam=12; in_ham=19}
|> Map.add "forgot" { in_spam=0; in_ham=22}
|> Map.add "forgotten" { in_spam=0; in_ham=9}
|> Map.add "fork" { in_spam=0; in_ham=210}
|> Map.add "fork-admin" { in_spam=0; in_ham=68}
|> Map.add "form" { in_spam=160; in_ham=67}
|> Map.add "formal" { in_spam=5; in_ham=8}
|> Map.add "format" { in_spam=9; in_ham=40}
|> Map.add "formation" { in_spam=3; in_ham=7}
|> Map.add "formative" { in_spam=3; in_ham=7}
|> Map.add "formats" { in_spam=0; in_ham=8}
|> Map.add "formed" { in_spam=1; in_ham=9}
|> Map.add "former" { in_spam=6; in_ham=34}
|> Map.add "formerly" { in_spam=2; in_ham=9}
|> Map.add "forms" { in_spam=20; in_ham=25}
|> Map.add "forteana" { in_spam=0; in_ham=11}
|> Map.add "forth" { in_spam=1; in_ham=14}
|> Map.add "fortunately" { in_spam=2; in_ham=7}
|> Map.add "fortune" { in_spam=25; in_ham=11}
|> Map.add "forum" { in_spam=7; in_ham=13}
|> Map.add "forward" { in_spam=26; in_ham=43}
|> Map.add "forwarded" { in_spam=4; in_ham=34}
|> Map.add "forwarded-by" { in_spam=0; in_ham=16}
|> Map.add "forwarding" { in_spam=2; in_ham=16}
|> Map.add "found" { in_spam=25; in_ham=251}
|> Map.add "foundation" { in_spam=1; in_ham=13}
|> Map.add "founded" { in_spam=4; in_ham=12}
|> Map.add "founder" { in_spam=0; in_ham=14}
|> Map.add "founding" { in_spam=3; in_ham=9}
|> Map.add "four" { in_spam=15; in_ham=56}
|> Map.add "fourth" { in_spam=1; in_ham=18}
|> Map.add "fox" { in_spam=0; in_ham=14}
|> Map.add "fps" { in_spam=4; in_ham=9}
|> Map.add "frame" { in_spam=3; in_ham=12}
|> Map.add "framework" { in_spam=0; in_ham=12}
|> Map.add "france" { in_spam=9; in_ham=32}
|> Map.add "franchise" { in_spam=3; in_ham=6}
|> Map.add "francisco" { in_spam=2; in_ham=20}
|> Map.add "frank" { in_spam=0; in_ham=12}
|> Map.add "frankly" { in_spam=5; in_ham=12}
|> Map.add "freaking" { in_spam=0; in_ham=9}
|> Map.add "free" { in_spam=218; in_ham=311}
|> Map.add "freebsd" { in_spam=8; in_ham=20}
|> Map.add "freedom" { in_spam=12; in_ham=30}
|> Map.add "freeze" { in_spam=3; in_ham=10}
|> Map.add "french" { in_spam=4; in_ham=45}
|> Map.add "frequently" { in_spam=3; in_ham=22}
|> Map.add "fresh" { in_spam=6; in_ham=16}
|> Map.add "freshrpms" { in_spam=0; in_ham=254}
|> Map.add "fri" { in_spam=0; in_ham=73}
|> Map.add "friday" { in_spam=0; in_ham=45}
|> Map.add "friend" { in_spam=30; in_ham=34}
|> Map.add "friendly" { in_spam=2; in_ham=11}
|> Map.add "friends" { in_spam=32; in_ham=63}
|> Map.add "frihet" { in_spam=0; in_ham=9}
|> Map.add "frogstone" { in_spam=0; in_ham=8}
|> Map.add "from" { in_spam=337; in_ham=1145}
|> Map.add "front" { in_spam=11; in_ham=31}
|> Map.add "frontpage" { in_spam=39; in_ham=0}
|> Map.add "frustrating" { in_spam=9; in_ham=3}
|> Map.add "ftoc" { in_spam=0; in_ham=25}
|> Map.add "ftp" { in_spam=3; in_ham=31}
|> Map.add "fu-berlin" { in_spam=0; in_ham=8}
|> Map.add "fucking" { in_spam=3; in_ham=16}
|> Map.add "fuel" { in_spam=3; in_ham=10}
|> Map.add "full" { in_spam=44; in_ham=75}
|> Map.add "fully" { in_spam=23; in_ham=44}
|> Map.add "fun" { in_spam=14; in_ham=51}
|> Map.add "function" { in_spam=7; in_ham=44}
|> Map.add "functional" { in_spam=4; in_ham=8}
|> Map.add "functions" { in_spam=1; in_ham=18}
|> Map.add "fund" { in_spam=37; in_ham=16}
|> Map.add "fundamental" { in_spam=1; in_ham=15}
|> Map.add "funding" { in_spam=9; in_ham=12}
|> Map.add "funds" { in_spam=19; in_ham=10}
|> Map.add "funny" { in_spam=1; in_ham=41}
|> Map.add "further" { in_spam=72; in_ham=64}
|> Map.add "furthermore" { in_spam=7; in_ham=6}
|> Map.add "future" { in_spam=91; in_ham=93}
|> Map.add "fwiw" { in_spam=0; in_ham=8}
|> Map.add "gain" { in_spam=12; in_ham=30}
|> Map.add "gained" { in_spam=4; in_ham=11}
|> Map.add "gains" { in_spam=3; in_ham=7}
|> Map.add "gambling" { in_spam=8; in_ham=4}
|> Map.add "game" { in_spam=11; in_ham=57}
|> Map.add "games" { in_spam=8; in_ham=29}
|> Map.add "gap" { in_spam=0; in_ham=14}
|> Map.add "garden" { in_spam=4; in_ham=7}
|> Map.add "garrigues" { in_spam=0; in_ham=54}
|> Map.add "gary" { in_spam=0; in_ham=90}
|> Map.add "garym" { in_spam=0; in_ham=53}
|> Map.add "gas" { in_spam=1; in_ham=17}
|> Map.add "gate" { in_spam=0; in_ham=8}
|> Map.add "gave" { in_spam=10; in_ham=30}
|> Map.add "gay" { in_spam=0; in_ham=16}
|> Map.add "gbolcer" { in_spam=0; in_ham=9}
|> Map.add "gcc" { in_spam=0; in_ham=14}
|> Map.add "geege" { in_spam=0; in_ham=47}
|> Map.add "geek" { in_spam=2; in_ham=120}
|> Map.add "geeks" { in_spam=0; in_ham=9}
|> Map.add "gen" { in_spam=9; in_ham=7}
|> Map.add "general" { in_spam=42; in_ham=76}
|> Map.add "generally" { in_spam=0; in_ham=41}
|> Map.add "generate" { in_spam=20; in_ham=26}
|> Map.add "generated" { in_spam=3; in_ham=44}
|> Map.add "generates" { in_spam=1; in_ham=7}
|> Map.add "generating" { in_spam=5; in_ham=7}
|> Map.add "generation" { in_spam=3; in_ham=24}
|> Map.add "generations" { in_spam=1; in_ham=7}
|> Map.add "generator" { in_spam=68; in_ham=9}
|> Map.add "generic" { in_spam=3; in_ham=8}
|> Map.add "geneva" { in_spam=11; in_ham=3}
|> Map.add "genom" { in_spam=0; in_ham=9}
|> Map.add "geometry" { in_spam=0; in_ham=22}
|> Map.add "george" { in_spam=6; in_ham=35}
|> Map.add "german" { in_spam=2; in_ham=7}
|> Map.add "germany" { in_spam=7; in_ham=16}
|> Map.add "gerontocracy" { in_spam=0; in_ham=9}
|> Map.add "get" { in_spam=183; in_ham=705}
|> Map.add "gets" { in_spam=11; in_ham=100}
|> Map.add "getting" { in_spam=24; in_ham=165}
|> Map.add "ghost" { in_spam=5; in_ham=6}
|> Map.add "giant" { in_spam=2; in_ham=7}
|> Map.add "gibbon" { in_spam=0; in_ham=41}
|> Map.add "gibson" { in_spam=0; in_ham=11}
|> Map.add "gif" { in_spam=92; in_ham=40}
|> Map.add "gift" { in_spam=9; in_ham=8}
|> Map.add "gingras" { in_spam=0; in_ham=13}
|> Map.add "girl" { in_spam=4; in_ham=23}
|> Map.add "girls" { in_spam=12; in_ham=12}
|> Map.add "give" { in_spam=59; in_ham=195}
|> Map.add "given" { in_spam=23; in_ham=93}
|> Map.add "gives" { in_spam=2; in_ham=80}
|> Map.add "giving" { in_spam=12; in_ham=52}
|> Map.add "glaciers" { in_spam=0; in_ham=8}
|> Map.add "glad" { in_spam=9; in_ham=15}
|> Map.add "global" { in_spam=6; in_ham=70}
|> Map.add "globe" { in_spam=1; in_ham=12}
|> Map.add "gmt" { in_spam=2; in_ham=57}
|> Map.add "gnat" { in_spam=0; in_ham=10}
|> Map.add "gnome" { in_spam=0; in_ham=18}
|> Map.add "gnu" { in_spam=0; in_ham=92}
|> Map.add "gnupg" { in_spam=0; in_ham=99}
|> Map.add "goal" { in_spam=5; in_ham=30}
|> Map.add "goals" { in_spam=3; in_ham=10}
|> Map.add "god" { in_spam=11; in_ham=28}
|> Map.add "goes" { in_spam=16; in_ham=72}
|> Map.add "going" { in_spam=29; in_ham=190}
|> Map.add "gold" { in_spam=6; in_ham=15}
|> Map.add "gone" { in_spam=10; in_ham=33}
|> Map.add "gonna" { in_spam=0; in_ham=11}
|> Map.add "good" { in_spam=50; in_ham=336}
|> Map.add "goodbye" { in_spam=2; in_ham=9}
|> Map.add "goods" { in_spam=2; in_ham=7}
|> Map.add "google" { in_spam=0; in_ham=47}
|> Map.add "gordon" { in_spam=0; in_ham=31}
|> Map.add "got" { in_spam=36; in_ham=251}
|> Map.add "gotten" { in_spam=2; in_ham=22}
|> Map.add "gov" { in_spam=4; in_ham=21}
|> Map.add "government" { in_spam=41; in_ham=81}
|> Map.add "government's" { in_spam=0; in_ham=10}
|> Map.add "governments" { in_spam=1; in_ham=12}
|> Map.add "gpg" { in_spam=2; in_ham=24}
|> Map.add "gpl" { in_spam=0; in_ham=10}
|> Map.add "grab" { in_spam=5; in_ham=10}
|> Map.add "grand" { in_spam=13; in_ham=8}
|> Map.add "grant" { in_spam=4; in_ham=10}
|> Map.add "granted" { in_spam=2; in_ham=23}
|> Map.add "grants" { in_spam=3; in_ham=11}
|> Map.add "graphics" { in_spam=4; in_ham=10}
|> Map.add "grass" { in_spam=1; in_ham=7}
|> Map.add "grateful" { in_spam=1; in_ham=7}
|> Map.add "great" { in_spam=67; in_ham=167}
|> Map.add "greater" { in_spam=8; in_ham=45}
|> Map.add "greatest" { in_spam=8; in_ham=7}
|> Map.add "greatly" { in_spam=2; in_ham=13}
|> Map.add "green" { in_spam=9; in_ham=23}
|> Map.add "greg" { in_spam=0; in_ham=49}
|> Map.add "gregory" { in_spam=0; in_ham=19}
|> Map.add "grep" { in_spam=0; in_ham=21}
|> Map.add "grew" { in_spam=1; in_ham=11}
|> Map.add "ground" { in_spam=0; in_ham=36}
|> Map.add "group" { in_spam=54; in_ham=304}
|> Map.add "groups" { in_spam=4; in_ham=140}
|> Map.add "grow" { in_spam=6; in_ham=14}
|> Map.add "growing" { in_spam=28; in_ham=76}
|> Map.add "grown" { in_spam=3; in_ham=9}
|> Map.add "growth" { in_spam=5; in_ham=20}
|> Map.add "gsolb" { in_spam=0; in_ham=87}
|> Map.add "gtk" { in_spam=0; in_ham=11}
|> Map.add "guarantee" { in_spam=36; in_ham=17}
|> Map.add "guaranteed" { in_spam=64; in_ham=7}
|> Map.add "guarantees" { in_spam=11; in_ham=4}
|> Map.add "guardian" { in_spam=2; in_ham=15}
|> Map.add "guess" { in_spam=0; in_ham=100}
|> Map.add "gui" { in_spam=0; in_ham=8}
|> Map.add "guide" { in_spam=20; in_ham=8}
|> Map.add "guidelines" { in_spam=12; in_ham=4}
|> Map.add "guides" { in_spam=4; in_ham=6}
|> Map.add "guido" { in_spam=0; in_ham=46}
|> Map.add "guilty" { in_spam=1; in_ham=7}
|> Map.add "gulf" { in_spam=0; in_ham=10}
|> Map.add "gun" { in_spam=5; in_ham=8}
|> Map.add "guy" { in_spam=3; in_ham=48}
|> Map.add "guys" { in_spam=5; in_ham=62}
|> Map.add "gward" { in_spam=0; in_ham=8}
|> Map.add "haa" { in_spam=0; in_ham=11}
|> Map.add "habeas" { in_spam=0; in_ham=17}
|> Map.add "habeus" { in_spam=0; in_ham=8}
|> Map.add "hack" { in_spam=0; in_ham=24}
|> Map.add "hackers" { in_spam=11; in_ham=6}
|> Map.add "hacking" { in_spam=0; in_ham=15}
|> Map.add "had" { in_spam=38; in_ham=357}
|> Map.add "hadn't" { in_spam=0; in_ham=26}
|> Map.add "haiku" { in_spam=0; in_ham=13}
|> Map.add "hair" { in_spam=5; in_ham=16}
|> Map.add "hal" { in_spam=0; in_ham=29}
|> Map.add "half" { in_spam=10; in_ham=92}
|> Map.add "hall" { in_spam=1; in_ham=40}
|> Map.add "hallgrimsson" { in_spam=0; in_ham=12}
|> Map.add "ham" { in_spam=2; in_ham=57}
|> Map.add "hamilton" { in_spam=0; in_ham=9}
|> Map.add "hammie" { in_spam=0; in_ham=14}
|> Map.add "hams" { in_spam=0; in_ham=8}
|> Map.add "hand" { in_spam=13; in_ham=84}
|> Map.add "handed" { in_spam=2; in_ham=7}
|> Map.add "handful" { in_spam=0; in_ham=8}
|> Map.add "handle" { in_spam=4; in_ham=38}
|> Map.add "handled" { in_spam=4; in_ham=11}
|> Map.add "handling" { in_spam=11; in_ham=22}
|> Map.add "hands" { in_spam=9; in_ham=33}
|> Map.add "handy" { in_spam=1; in_ham=12}
|> Map.add "hang" { in_spam=0; in_ham=10}
|> Map.add "hanging" { in_spam=2; in_ham=11}
|> Map.add "happen" { in_spam=23; in_ham=62}
|> Map.add "happened" { in_spam=10; in_ham=67}
|> Map.add "happening" { in_spam=1; in_ham=14}
|> Map.add "happens" { in_spam=11; in_ham=38}
|> Map.add "happily" { in_spam=2; in_ham=7}
|> Map.add "happy" { in_spam=20; in_ham=71}
|> Map.add "harbor" { in_spam=3; in_ham=6}
|> Map.add "hard" { in_spam=23; in_ham=94}
|> Map.add "harder" { in_spam=2; in_ham=25}
|> Map.add "hardly" { in_spam=2; in_ham=12}
|> Map.add "hardware" { in_spam=2; in_ham=57}
|> Map.add "harley" { in_spam=0; in_ham=35}
|> Map.add "harm" { in_spam=1; in_ham=10}
|> Map.add "harri" { in_spam=0; in_ham=12}
|> Map.add "harvard" { in_spam=0; in_ham=8}
|> Map.add "has" { in_spam=124; in_ham=707}
|> Map.add "hash" { in_spam=2; in_ham=26}
|> Map.add "hasn't" { in_spam=0; in_ham=35}
|> Map.add "hassles" { in_spam=2; in_ham=8}
|> Map.add "hat" { in_spam=3; in_ham=103}
|> Map.add "hate" { in_spam=0; in_ham=24}
|> Map.add "hatred" { in_spam=0; in_ham=8}
|> Map.add "haun" { in_spam=0; in_ham=9}
|> Map.add "have" { in_spam=264; in_ham=1173}
|> Map.add "haven't" { in_spam=4; in_ham=85}
|> Map.add "having" { in_spam=25; in_ham=151}
|> Map.add "hazardous" { in_spam=15; in_ham=0}
|> Map.add "he'd" { in_spam=0; in_ham=10}
|> Map.add "he's" { in_spam=0; in_ham=45}
|> Map.add "head" { in_spam=189; in_ham=61}
|> Map.add "headed" { in_spam=3; in_ham=7}
|> Map.add "header" { in_spam=6; in_ham=55}
|> Map.add "headers" { in_spam=0; in_ham=75}
|> Map.add "headline" { in_spam=4; in_ham=35}
|> Map.add "headlines" { in_spam=6; in_ham=8}
|> Map.add "headquarters" { in_spam=0; in_ham=8}
|> Map.add "heads" { in_spam=0; in_ham=8}
|> Map.add "health" { in_spam=28; in_ham=24}
|> Map.add "healthy" { in_spam=3; in_ham=12}
|> Map.add "hear" { in_spam=12; in_ham=36}
|> Map.add "heard" { in_spam=16; in_ham=65}
|> Map.add "hearing" { in_spam=12; in_ham=21}
|> Map.add "heart" { in_spam=9; in_ham=22}
|> Map.add "heat" { in_spam=1; in_ham=9}
|> Map.add "heather" { in_spam=0; in_ham=13}
|> Map.add "heaven" { in_spam=3; in_ham=111}
|> Map.add "heavily" { in_spam=0; in_ham=10}
|> Map.add "heavy" { in_spam=7; in_ham=15}
|> Map.add "heck" { in_spam=6; in_ham=13}
|> Map.add "heh" { in_spam=0; in_ham=9}
|> Map.add "height" { in_spam=142; in_ham=8}
|> Map.add "held" { in_spam=17; in_ham=33}
|> Map.add "helium" { in_spam=0; in_ham=9}
|> Map.add "hell" { in_spam=5; in_ham=43}
|> Map.add "hello" { in_spam=9; in_ham=46}
|> Map.add "help" { in_spam=99; in_ham=178}
|> Map.add "helped" { in_spam=10; in_ham=32}
|> Map.add "helpful" { in_spam=1; in_ham=21}
|> Map.add "helping" { in_spam=9; in_ham=16}
|> Map.add "helps" { in_spam=10; in_ham=35}
|> Map.add "helvetica" { in_spam=94; in_ham=0}
|> Map.add "hence" { in_spam=17; in_ham=7}
|> Map.add "her" { in_spam=22; in_ham=99}
|> Map.add "here" { in_spam=298; in_ham=404}
|> Map.add "here's" { in_spam=13; in_ham=64}
|> Map.add "heritage" { in_spam=3; in_ham=15}
|> Map.add "hesitate" { in_spam=4; in_ham=6}
|> Map.add "hets" { in_spam=0; in_ham=8}
|> Map.add "hettinga" { in_spam=0; in_ham=64}
|> Map.add "hey" { in_spam=0; in_ham=33}
|> Map.add "hidden" { in_spam=58; in_ham=7}
|> Map.add "hidden'" { in_spam=28; in_ham=3}
|> Map.add "hide" { in_spam=3; in_ham=12}
|> Map.add "high" { in_spam=46; in_ham=107}
|> Map.add "high-speed" { in_spam=0; in_ham=11}
|> Map.add "higher" { in_spam=5; in_ham=50}
|> Map.add "highest" { in_spam=11; in_ham=16}
|> Map.add "highlight" { in_spam=0; in_ham=8}
|> Map.add "highlighted" { in_spam=0; in_ham=10}
|> Map.add "highlighting" { in_spam=0; in_ham=9}
|> Map.add "highly" { in_spam=9; in_ham=21}
|> Map.add "hill" { in_spam=2; in_ham=11}
|> Map.add "him" { in_spam=13; in_ham=83}
|> Map.add "himself" { in_spam=4; in_ham=32}
|> Map.add "hint" { in_spam=1; in_ham=14}
|> Map.add "hints" { in_spam=0; in_ham=11}
|> Map.add "hire" { in_spam=1; in_ham=10}
|> Map.add "hired" { in_spam=1; in_ham=8}
|> Map.add "his" { in_spam=36; in_ham=230}
|> Map.add "historic" { in_spam=0; in_ham=9}
|> Map.add "historical" { in_spam=1; in_ham=17}
|> Map.add "history" { in_spam=5; in_ham=52}
|> Map.add "hit" { in_spam=11; in_ham=70}
|> Map.add "hits" { in_spam=1; in_ham=26}
|> Map.add "hitting" { in_spam=3; in_ham=17}
|> Map.add "hmm" { in_spam=0; in_ham=25}
|> Map.add "hmmm" { in_spam=0; in_ham=31}
|> Map.add "hold" { in_spam=3; in_ham=49}
|> Map.add "holding" { in_spam=8; in_ham=13}
|> Map.add "holds" { in_spam=4; in_ham=14}
|> Map.add "hole" { in_spam=0; in_ham=16}
|> Map.add "holes" { in_spam=0; in_ham=8}
|> Map.add "holidays" { in_spam=2; in_ham=10}
|> Map.add "holy" { in_spam=0; in_ham=9}
|> Map.add "home" { in_spam=87; in_ham=190}
|> Map.add "homer" { in_spam=0; in_ham=8}
|> Map.add "homes" { in_spam=10; in_ham=7}
|> Map.add "honest" { in_spam=4; in_ham=11}
|> Map.add "honor" { in_spam=21; in_ham=12}
|> Map.add "hood" { in_spam=1; in_ham=7}
|> Map.add "hook" { in_spam=4; in_ham=11}
|> Map.add "hooked" { in_spam=4; in_ham=8}
|> Map.add "hoover" { in_spam=0; in_ham=9}
|> Map.add "hope" { in_spam=17; in_ham=77}
|> Map.add "hoped" { in_spam=0; in_ham=9}
|> Map.add "hopefully" { in_spam=1; in_ham=26}
|> Map.add "hopes" { in_spam=1; in_ham=21}
|> Map.add "hoping" { in_spam=1; in_ham=21}
|> Map.add "horror" { in_spam=0; in_ham=8}
|> Map.add "horse" { in_spam=0; in_ham=10}
|> Map.add "host" { in_spam=6; in_ham=21}
|> Map.add "hosted" { in_spam=1; in_ham=7}
|> Map.add "hostile" { in_spam=1; in_ham=7}
|> Map.add "hosting" { in_spam=5; in_ham=13}
|> Map.add "hosts" { in_spam=0; in_ham=10}
|> Map.add "hot" { in_spam=21; in_ham=16}
|> Map.add "hotel" { in_spam=4; in_ham=15}
|> Map.add "hotels" { in_spam=4; in_ham=6}
|> Map.add "hotmail" { in_spam=5; in_ham=29}
|> Map.add "hottest" { in_spam=5; in_ham=6}
|> Map.add "hour" { in_spam=20; in_ham=38}
|> Map.add "hours" { in_spam=70; in_ham=58}
|> Map.add "house" { in_spam=20; in_ham=50}
|> Map.add "housing" { in_spam=8; in_ham=6}
|> Map.add "how" { in_spam=88; in_ham=446}
|> Map.add "however" { in_spam=28; in_ham=153}
|> Map.add "href" { in_spam=235; in_ham=13}
|> Map.add "hspace" { in_spam=19; in_ham=2}
|> Map.add "htm" { in_spam=101; in_ham=64}
|> Map.add "html" { in_spam=255; in_ham=446}
|> Map.add "http" { in_spam=455; in_ham=1876}
|> Map.add "http-equiv" { in_spam=130; in_ham=6}
|> Map.add "https" { in_spam=7; in_ham=405}
|> Map.add "huckleberry" { in_spam=0; in_ham=23}
|> Map.add "huge" { in_spam=27; in_ham=36}
|> Map.add "hughes" { in_spam=0; in_ham=13}
|> Map.add "huh" { in_spam=0; in_ham=13}
|> Map.add "human" { in_spam=6; in_ham=67}
|> Map.add "humanity" { in_spam=1; in_ham=8}
|> Map.add "humans" { in_spam=0; in_ham=16}
|> Map.add "hundred" { in_spam=19; in_ham=16}
|> Map.add "hundreds" { in_spam=39; in_ham=31}
|> Map.add "hunt" { in_spam=0; in_ham=12}
|> Map.add "hurry" { in_spam=3; in_ham=9}
|> Map.add "hurt" { in_spam=0; in_ham=10}
|> Map.add "hurting" { in_spam=1; in_ham=8}
|> Map.add "husband" { in_spam=8; in_ham=11}
|> Map.add "hyatt" { in_spam=0; in_ham=8}
|> Map.add "i'd" { in_spam=3; in_ham=222}
|> Map.add "i'll" { in_spam=14; in_ham=206}
|> Map.add "i'm" { in_spam=24; in_ham=506}
|> Map.add "i've" { in_spam=14; in_ham=334}
|> Map.add "ian" { in_spam=0; in_ham=19}
|> Map.add "ibm" { in_spam=1; in_ham=15}
|> Map.add "ibuc" { in_spam=0; in_ham=41}
|> Map.add "ice" { in_spam=0; in_ham=10}
|> Map.add "icq" { in_spam=1; in_ham=24}
|> Map.add "ide" { in_spam=0; in_ham=9}
|> Map.add "idea" { in_spam=19; in_ham=139}
|> Map.add "ideal" { in_spam=2; in_ham=11}
|> Map.add "ideas" { in_spam=18; in_ham=82}
|> Map.add "identical" { in_spam=3; in_ham=16}
|> Map.add "identified" { in_spam=6; in_ham=10}
|> Map.add "identify" { in_spam=1; in_ham=20}
|> Map.add "identifying" { in_spam=1; in_ham=10}
|> Map.add "identity" { in_spam=5; in_ham=16}
|> Map.add "idiot" { in_spam=0; in_ham=10}
|> Map.add "ieee" { in_spam=0; in_ham=12}
|> Map.add "ignorance" { in_spam=2; in_ham=8}
|> Map.add "ignore" { in_spam=4; in_ham=31}
|> Map.add "ignored" { in_spam=8; in_ham=18}
|> Map.add "ignores" { in_spam=1; in_ham=8}
|> Map.add "ignoring" { in_spam=1; in_ham=10}
|> Map.add "iii" { in_spam=9; in_ham=54}
|> Map.add "iiq" { in_spam=30; in_ham=0}
|> Map.add "iirc" { in_spam=0; in_ham=13}
|> Map.add "iki" { in_spam=1; in_ham=17}
|> Map.add "ill" { in_spam=3; in_ham=13}
|> Map.add "ille" { in_spam=0; in_ham=15}
|> Map.add "illegal" { in_spam=7; in_ham=20}
|> Map.add "illinois" { in_spam=12; in_ham=8}
|> Map.add "ilug" { in_spam=32; in_ham=92}
|> Map.add "image" { in_spam=16; in_ham=27}
|> Map.add "images" { in_spam=69; in_ham=78}
|> Map.add "imagine" { in_spam=9; in_ham=39}
|> Map.add "imagined" { in_spam=9; in_ham=5}
|> Map.add "imap" { in_spam=0; in_ham=11}
|> Map.add "img" { in_spam=119; in_ham=54}
|> Map.add "imho" { in_spam=0; in_ham=16}
|> Map.add "immediate" { in_spam=28; in_ham=24}
|> Map.add "immediately" { in_spam=45; in_ham=38}
|> Map.add "immoral" { in_spam=1; in_ham=8}
|> Map.add "imo" { in_spam=0; in_ham=13}
|> Map.add "impact" { in_spam=19; in_ham=14}
|> Map.add "implement" { in_spam=0; in_ham=22}
|> Map.add "implemented" { in_spam=0; in_ham=20}
|> Map.add "implementing" { in_spam=0; in_ham=8}
|> Map.add "implications" { in_spam=3; in_ham=9}
|> Map.add "import" { in_spam=2; in_ham=9}
|> Map.add "importance" { in_spam=0; in_ham=21}
|> Map.add "important" { in_spam=34; in_ham=85}
|> Map.add "importantly" { in_spam=3; in_ham=7}
|> Map.add "impose" { in_spam=0; in_ham=8}
|> Map.add "impossible" { in_spam=4; in_ham=22}
|> Map.add "impoverished" { in_spam=2; in_ham=11}
|> Map.add "impression" { in_spam=1; in_ham=11}
|> Map.add "impressive" { in_spam=5; in_ham=6}
|> Map.add "improve" { in_spam=20; in_ham=18}
|> Map.add "improved" { in_spam=7; in_ham=13}
|> Map.add "improvement" { in_spam=14; in_ham=13}
|> Map.add "improvements" { in_spam=5; in_ham=8}
|> Map.add "improves" { in_spam=0; in_ham=8}
|> Map.add "improving" { in_spam=1; in_ham=8}
|> Map.add "inbetween" { in_spam=1; in_ham=9}
|> Map.add "inbox" { in_spam=1; in_ham=30}
|> Map.add "inc" { in_spam=18; in_ham=90}
|> Map.add "incentive" { in_spam=2; in_ham=8}
|> Map.add "inches" { in_spam=5; in_ham=5}
|> Map.add "incident" { in_spam=2; in_ham=9}
|> Map.add "include" { in_spam=50; in_ham=83}
|> Map.add "included" { in_spam=27; in_ham=54}
|> Map.add "includes" { in_spam=53; in_ham=25}
|> Map.add "including" { in_spam=37; in_ham=93}
|> Map.add "income" { in_spam=50; in_ham=18}
|> Map.add "incoming" { in_spam=0; in_ham=21}
|> Map.add "incompatible" { in_spam=0; in_ham=17}
|> Map.add "incorporate" { in_spam=1; in_ham=9}
|> Map.add "incorporated" { in_spam=1; in_ham=7}
|> Map.add "incorrect" { in_spam=0; in_ham=10}
|> Map.add "incr" { in_spam=0; in_ham=8}
|> Map.add "increase" { in_spam=33; in_ham=37}
|> Map.add "increased" { in_spam=8; in_ham=14}
|> Map.add "increases" { in_spam=3; in_ham=20}
|> Map.add "increasing" { in_spam=8; in_ham=24}
|> Map.add "increasingly" { in_spam=0; in_ham=17}
|> Map.add "incredible" { in_spam=10; in_ham=10}
|> Map.add "incredibly" { in_spam=8; in_ham=8}
|> Map.add "indeed" { in_spam=4; in_ham=44}
|> Map.add "independence" { in_spam=2; in_ham=8}
|> Map.add "independent" { in_spam=42; in_ham=24}
|> Map.add "index" { in_spam=46; in_ham=75}
|> Map.add "india" { in_spam=3; in_ham=11}
|> Map.add "india's" { in_spam=0; in_ham=12}
|> Map.add "indian" { in_spam=1; in_ham=11}
|> Map.add "indians" { in_spam=0; in_ham=9}
|> Map.add "indicate" { in_spam=12; in_ham=11}
|> Map.add "indicates" { in_spam=0; in_ham=10}
|> Map.add "indicating" { in_spam=3; in_ham=11}
|> Map.add "indicators" { in_spam=0; in_ham=11}
|> Map.add "individual" { in_spam=7; in_ham=50}
|> Map.add "individuals" { in_spam=29; in_ham=31}
|> Map.add "industrial" { in_spam=1; in_ham=11}
|> Map.add "industries" { in_spam=9; in_ham=19}
|> Map.add "industry" { in_spam=22; in_ham=64}
|> Map.add "industry's" { in_spam=2; in_ham=7}
|> Map.add "inevitable" { in_spam=3; in_ham=6}
|> Map.add "influence" { in_spam=1; in_ham=14}
|> Map.add "info" { in_spam=52; in_ham=183}
|> Map.add "information" { in_spam=220; in_ham=198}
|> Map.add "informed" { in_spam=9; in_ham=5}
|> Map.add "infringement" { in_spam=1; in_ham=8}
|> Map.add "inhabitants" { in_spam=1; in_ham=8}
|> Map.add "init" { in_spam=1; in_ham=22}
|> Map.add "initial" { in_spam=14; in_ham=24}
|> Map.add "initially" { in_spam=1; in_ham=15}
|> Map.add "initiated" { in_spam=1; in_ham=15}
|> Map.add "initiative" { in_spam=1; in_ham=10}
|> Map.add "initiatives" { in_spam=0; in_ham=9}
|> Map.add "inline" { in_spam=0; in_ham=10}
|> Map.add "innovation" { in_spam=2; in_ham=12}
|> Map.add "inphonic" { in_spam=2; in_ham=106}
|> Map.add "input" { in_spam=52; in_ham=19}
|> Map.add "inquiry" { in_spam=35; in_ham=7}
|> Map.add "insane" { in_spam=0; in_ham=14}
|> Map.add "insecure" { in_spam=0; in_ham=8}
|> Map.add "insert" { in_spam=8; in_ham=28}
|> Map.add "inserted" { in_spam=3; in_ham=9}
|> Map.add "inserts" { in_spam=0; in_ham=8}
|> Map.add "inside" { in_spam=7; in_ham=51}
|> Map.add "insider's" { in_spam=9; in_ham=3}
|> Map.add "insiq" { in_spam=20; in_ham=0}
|> Map.add "insist" { in_spam=3; in_ham=16}
|> Map.add "inspect" { in_spam=0; in_ham=9}
|> Map.add "inspection" { in_spam=2; in_ham=10}
|> Map.add "inspired" { in_spam=1; in_ham=11}
|> Map.add "install" { in_spam=1; in_ham=102}
|> Map.add "installation" { in_spam=3; in_ham=32}
|> Map.add "installed" { in_spam=2; in_ham=113}
|> Map.add "installing" { in_spam=3; in_ham=30}
|> Map.add "installs" { in_spam=1; in_ham=9}
|> Map.add "instance" { in_spam=5; in_ham=29}
|> Map.add "instances" { in_spam=0; in_ham=13}
|> Map.add "instant" { in_spam=23; in_ham=18}
|> Map.add "instantly" { in_spam=14; in_ham=18}
|> Map.add "instead" { in_spam=70; in_ham=154}
|> Map.add "institute" { in_spam=1; in_ham=17}
|> Map.add "instructed" { in_spam=13; in_ham=1}
|> Map.add "instruction" { in_spam=14; in_ham=1}
|> Map.add "instructions" { in_spam=33; in_ham=11}
|> Map.add "insurance" { in_spam=79; in_ham=11}
|> Map.add "insuranceiq" { in_spam=58; in_ham=0}
|> Map.add "int" { in_spam=2; in_ham=15}
|> Map.add "integral" { in_spam=16; in_ham=4}
|> Map.add "integrate" { in_spam=0; in_ham=15}
|> Map.add "integrated" { in_spam=1; in_ham=12}
|> Map.add "integrating" { in_spam=0; in_ham=9}
|> Map.add "integration" { in_spam=0; in_ham=21}
|> Map.add "intel" { in_spam=1; in_ham=11}
|> Map.add "intellectual" { in_spam=0; in_ham=17}
|> Map.add "intelligence" { in_spam=11; in_ham=26}
|> Map.add "intelligent" { in_spam=2; in_ham=9}
|> Map.add "intend" { in_spam=8; in_ham=5}
|> Map.add "intended" { in_spam=20; in_ham=17}
|> Map.add "intense" { in_spam=1; in_ham=11}
|> Map.add "intention" { in_spam=2; in_ham=8}
|> Map.add "interact" { in_spam=0; in_ham=11}
|> Map.add "interaction" { in_spam=1; in_ham=14}
|> Map.add "interactions" { in_spam=0; in_ham=8}
|> Map.add "interactive" { in_spam=12; in_ham=53}
|> Map.add "interest" { in_spam=57; in_ham=41}
|> Map.add "interested" { in_spam=30; in_ham=49}
|> Map.add "interesting" { in_spam=0; in_ham=98}
|> Map.add "interests" { in_spam=5; in_ham=17}
|> Map.add "interface" { in_spam=2; in_ham=39}
|> Map.add "interlink" { in_spam=0; in_ham=8}
|> Map.add "internal" { in_spam=4; in_ham=24}
|> Map.add "internet" { in_spam=82; in_ham=147}
|> Map.add "interpreter" { in_spam=0; in_ham=11}
|> Map.add "intervention" { in_spam=7; in_ham=9}
|> Map.add "interview" { in_spam=5; in_ham=17}
|> Map.add "interviewed" { in_spam=0; in_ham=11}
|> Map.add "into" { in_spam=78; in_ham=424}
|> Map.add "introduce" { in_spam=15; in_ham=10}
|> Map.add "introduced" { in_spam=3; in_ham=18}
|> Map.add "introduction" { in_spam=4; in_ham=14}
|> Map.add "invalid" { in_spam=1; in_ham=9}
|> Map.add "invaluable" { in_spam=7; in_ham=4}
|> Map.add "invent" { in_spam=0; in_ham=9}
|> Map.add "invented" { in_spam=0; in_ham=15}
|> Map.add "invest" { in_spam=23; in_ham=7}
|> Map.add "invested" { in_spam=5; in_ham=5}
|> Map.add "investigate" { in_spam=2; in_ham=8}
|> Map.add "investing" { in_spam=12; in_ham=3}
|> Map.add "investment" { in_spam=55; in_ham=26}
|> Map.add "investments" { in_spam=11; in_ham=10}
|> Map.add "investors" { in_spam=18; in_ham=17}
|> Map.add "invisible" { in_spam=0; in_ham=13}
|> Map.add "invite" { in_spam=5; in_ham=6}
|> Map.add "invited" { in_spam=1; in_ham=9}
|> Map.add "invoke" { in_spam=0; in_ham=11}
|> Map.add "invoked" { in_spam=0; in_ham=20}
|> Map.add "involve" { in_spam=3; in_ham=13}
|> Map.add "involved" { in_spam=20; in_ham=43}
|> Map.add "involves" { in_spam=1; in_ham=12}
|> Map.add "ips" { in_spam=1; in_ham=7}
|> Map.add "iqa" { in_spam=0; in_ham=9}
|> Map.add "iraq" { in_spam=2; in_ham=30}
|> Map.add "ireland" { in_spam=5; in_ham=20}
|> Map.add "irish" { in_spam=48; in_ham=101}
|> Map.add "irony" { in_spam=0; in_ham=8}
|> Map.add "irrelevant" { in_spam=0; in_ham=8}
|> Map.add "irvine" { in_spam=2; in_ham=10}
|> Map.add "island" { in_spam=5; in_ham=10}
|> Map.add "isn't" { in_spam=13; in_ham=168}
|> Map.add "iso" { in_spam=0; in_ham=9}
|> Map.add "iso-" { in_spam=71; in_ham=10}
|> Map.add "isp" { in_spam=5; in_ham=15}
|> Map.add "isps" { in_spam=0; in_ham=13}
|> Map.add "israel" { in_spam=2; in_ham=17}
|> Map.add "issue" { in_spam=18; in_ham=129}
|> Map.add "issued" { in_spam=17; in_ham=9}
|> Map.add "issues" { in_spam=4; in_ham=81}
|> Map.add "it'd" { in_spam=0; in_ham=16}
|> Map.add "it'll" { in_spam=0; in_ham=24}
|> Map.add "it's" { in_spam=61; in_ham=571}
|> Map.add "item" { in_spam=3; in_ham=19}
|> Map.add "itemid" { in_spam=0; in_ham=10}
|> Map.add "items" { in_spam=5; in_ham=22}
|> Map.add "its" { in_spam=35; in_ham=339}
|> Map.add "itself" { in_spam=6; in_ham=68}
|> Map.add "ive" { in_spam=0; in_ham=8}
|> Map.add "ivh" { in_spam=0; in_ham=8}
|> Map.add "jabber" { in_spam=0; in_ham=47}
|> Map.add "jack" { in_spam=0; in_ham=15}
|> Map.add "jacob" { in_spam=0; in_ham=9}
|> Map.add "james" { in_spam=3; in_ham=53}
|> Map.add "jamesr" { in_spam=0; in_ham=28}
|> Map.add "january" { in_spam=9; in_ham=17}
|> Map.add "japan" { in_spam=3; in_ham=9}
|> Map.add "japanese" { in_spam=5; in_ham=12}
|> Map.add "jar" { in_spam=1; in_ham=8}
|> Map.add "jason" { in_spam=1; in_ham=12}
|> Map.add "java" { in_spam=3; in_ham=47}
|> Map.add "javascript" { in_spam=7; in_ham=6}
|> Map.add "jdk" { in_spam=1; in_ham=7}
|> Map.add "jeff" { in_spam=1; in_ham=11}
|> Map.add "jeremy" { in_spam=1; in_ham=64}
|> Map.add "jersey" { in_spam=12; in_ham=4}
|> Map.add "jesse" { in_spam=0; in_ham=14}
|> Map.add "jesus" { in_spam=1; in_ham=9}
|> Map.add "jid" { in_spam=0; in_ham=9}
|> Map.add "jim" { in_spam=0; in_ham=55}
|> Map.add "jkeating" { in_spam=0; in_ham=8}
|> Map.add "jmason" { in_spam=7; in_ham=20}
|> Map.add "job" { in_spam=19; in_ham=96}
|> Map.add "jobs" { in_spam=4; in_ham=19}
|> Map.add "joe" { in_spam=7; in_ham=37}
|> Map.add "john" { in_spam=10; in_ham=104}
|> Map.add "johnhall" { in_spam=0; in_ham=18}
|> Map.add "join" { in_spam=32; in_ham=79}
|> Map.add "joined" { in_spam=13; in_ham=19}
|> Map.add "joining" { in_spam=5; in_ham=7}
|> Map.add "joint" { in_spam=1; in_ham=14}
|> Map.add "joke" { in_spam=1; in_ham=23}
|> Map.add "jon" { in_spam=0; in_ham=12}
|> Map.add "jones" { in_spam=1; in_ham=11}
|> Map.add "jordan" { in_spam=2; in_ham=7}
|> Map.add "joseph" { in_spam=10; in_ham=25}
|> Map.add "journal" { in_spam=8; in_ham=35}
|> Map.add "journalist" { in_spam=1; in_ham=10}
|> Map.add "jpg" { in_spam=74; in_ham=32}
|> Map.add "jsp" { in_spam=7; in_ham=10}
|> Map.add "judge" { in_spam=1; in_ham=19}
|> Map.add "jul" { in_spam=3; in_ham=14}
|> Map.add "julian" { in_spam=0; in_ham=9}
|> Map.add "july" { in_spam=4; in_ham=23}
|> Map.add "jump" { in_spam=4; in_ham=23}
|> Map.add "june" { in_spam=6; in_ham=17}
|> Map.add "junk" { in_spam=7; in_ham=15}
|> Map.add "just" { in_spam=126; in_ham=764}
|> Map.add "justice" { in_spam=1; in_ham=21}
|> Map.add "justify" { in_spam=6; in_ham=13}
|> Map.add "justin" { in_spam=0; in_ham=60}
|> Map.add "jwz" { in_spam=0; in_ham=11}
|> Map.add "kde" { in_spam=0; in_ham=9}
|> Map.add "kearney" { in_spam=0; in_ham=8}
|> Map.add "keating" { in_spam=0; in_ham=10}
|> Map.add "keep" { in_spam=55; in_ham=153}
|> Map.add "keeping" { in_spam=3; in_ham=36}
|> Map.add "keeps" { in_spam=6; in_ham=8}
|> Map.add "kelly" { in_spam=2; in_ham=12}
|> Map.add "ken" { in_spam=2; in_ham=19}
|> Map.add "kept" { in_spam=7; in_ham=28}
|> Map.add "kernel" { in_spam=0; in_ham=88}
|> Map.add "kernels" { in_spam=0; in_ham=14}
|> Map.add "kevin" { in_spam=3; in_ham=31}
|> Map.add "key" { in_spam=28; in_ham=101}
|> Map.add "keyboard" { in_spam=1; in_ham=21}
|> Map.add "keys" { in_spam=0; in_ham=27}
|> Map.add "keyserver" { in_spam=0; in_ham=10}
|> Map.add "keywords" { in_spam=6; in_ham=6}
|> Map.add "khare" { in_spam=0; in_ham=24}
|> Map.add "kick" { in_spam=2; in_ham=17}
|> Map.add "kid" { in_spam=4; in_ham=10}
|> Map.add "kids" { in_spam=4; in_ham=35}
|> Map.add "kill" { in_spam=2; in_ham=30}
|> Map.add "killed" { in_spam=6; in_ham=31}
|> Map.add "killer" { in_spam=0; in_ham=16}
|> Map.add "killing" { in_spam=1; in_ham=13}
|> Map.add "kills" { in_spam=0; in_ham=10}
|> Map.add "kind" { in_spam=16; in_ham=107}
|> Map.add "kinda" { in_spam=0; in_ham=14}
|> Map.add "kindly" { in_spam=21; in_ham=2}
|> Map.add "kinds" { in_spam=0; in_ham=16}
|> Map.add "king" { in_spam=3; in_ham=18}
|> Map.add "kit" { in_spam=5; in_ham=5}
|> Map.add "knew" { in_spam=5; in_ham=36}
|> Map.add "know" { in_spam=71; in_ham=390}
|> Map.add "knowing" { in_spam=3; in_ham=9}
|> Map.add "knowledge" { in_spam=22; in_ham=44}
|> Map.add "known" { in_spam=13; in_ham=84}
|> Map.add "knows" { in_spam=2; in_ham=48}
|> Map.add "kragen" { in_spam=0; in_ham=11}
|> Map.add "kre" { in_spam=0; in_ham=37}
|> Map.add "kunskap" { in_spam=0; in_ham=9}
|> Map.add "label" { in_spam=1; in_ham=11}
|> Map.add "labor" { in_spam=0; in_ham=19}
|> Map.add "labour" { in_spam=1; in_ham=10}
|> Map.add "lack" { in_spam=4; in_ham=35}
|> Map.add "lady" { in_spam=2; in_ham=11}
|> Map.add "laid" { in_spam=0; in_ham=10}
|> Map.add "lame" { in_spam=1; in_ham=13}
|> Map.add "lan" { in_spam=2; in_ham=11}
|> Map.add "lance" { in_spam=0; in_ham=14}
|> Map.add "land" { in_spam=10; in_ham=24}
|> Map.add "landed" { in_spam=2; in_ham=7}
|> Map.add "lang" { in_spam=16; in_ham=7}
|> Map.add "language" { in_spam=6; in_ham=53}
|> Map.add "languages" { in_spam=0; in_ham=24}
|> Map.add "laptop" { in_spam=1; in_ham=31}
|> Map.add "large" { in_spam=31; in_ham=110}
|> Map.add "largely" { in_spam=1; in_ham=17}
|> Map.add "larger" { in_spam=16; in_ham=35}
|> Map.add "largest" { in_spam=8; in_ham=46}
|> Map.add "larry" { in_spam=0; in_ham=16}
|> Map.add "last" { in_spam=49; in_ham=227}
|> Map.add "late" { in_spam=29; in_ham=43}
|> Map.add "lately" { in_spam=7; in_ham=11}
|> Map.add "later" { in_spam=30; in_ham=73}
|> Map.add "latest" { in_spam=7; in_ham=96}
|> Map.add "latter" { in_spam=1; in_ham=21}
|> Map.add "laugh" { in_spam=8; in_ham=11}
|> Map.add "laughing" { in_spam=3; in_ham=12}
|> Map.add "launch" { in_spam=2; in_ham=21}
|> Map.add "launched" { in_spam=8; in_ham=18}
|> Map.add "launching" { in_spam=2; in_ham=12}
|> Map.add "law" { in_spam=14; in_ham=76}
|> Map.add "lawrence" { in_spam=0; in_ham=96}
|> Map.add "laws" { in_spam=21; in_ham=22}
|> Map.add "lawsuits" { in_spam=0; in_ham=15}
|> Map.add "lawyer" { in_spam=1; in_ham=12}
|> Map.add "lawyers" { in_spam=2; in_ham=7}
|> Map.add "lay" { in_spam=7; in_ham=6}
|> Map.add "layer" { in_spam=3; in_ham=21}
|> Map.add "laying" { in_spam=4; in_ham=6}
|> Map.add "lbs" { in_spam=20; in_ham=2}
|> Map.add "leaa" { in_spam=0; in_ham=13}
|> Map.add "lead" { in_spam=8; in_ham=43}
|> Map.add "leader" { in_spam=12; in_ham=22}
|> Map.add "leaders" { in_spam=1; in_ham=20}
|> Map.add "leadership" { in_spam=4; in_ham=15}
|> Map.add "leading" { in_spam=7; in_ham=24}

