open Database
open BayesianBody_009
let db = db 
|> Map.add "relevance" { in_spam=0; in_ham=5}
|> Map.add "relevant" { in_spam=12; in_ham=29}
|> Map.add "reliability" { in_spam=0; in_ham=7}
|> Map.add "reliable" { in_spam=8; in_ham=13}
|> Map.add "reliably" { in_spam=1; in_ham=2}
|> Map.add "reliance" { in_spam=0; in_ham=4}
|> Map.add "relief" { in_spam=1; in_ham=9}
|> Map.add "relies" { in_spam=0; in_ham=7}
|> Map.add "relieving" { in_spam=0; in_ham=4}
|> Map.add "religion" { in_spam=2; in_ham=18}
|> Map.add "religions" { in_spam=0; in_ham=8}
|> Map.add "religiosity" { in_spam=0; in_ham=5}
|> Map.add "religious" { in_spam=1; in_ham=24}
|> Map.add "reluctant" { in_spam=0; in_ham=3}
|> Map.add "rely" { in_spam=5; in_ham=18}
|> Map.add "relying" { in_spam=0; in_ham=4}
|> Map.add "remain" { in_spam=9; in_ham=31}
|> Map.add "remained" { in_spam=3; in_ham=5}
|> Map.add "remaining" { in_spam=2; in_ham=11}
|> Map.add "remains" { in_spam=8; in_ham=33}
|> Map.add "remarkable" { in_spam=4; in_ham=5}
|> Map.add "remarkably" { in_spam=1; in_ham=2}
|> Map.add "remarks" { in_spam=0; in_ham=5}
|> Map.add "remeber" { in_spam=0; in_ham=3}
|> Map.add "remedies" { in_spam=0; in_ham=4}
|> Map.add "remember" { in_spam=19; in_ham=76}
|> Map.add "remembering" { in_spam=0; in_ham=7}
|> Map.add "remembrance" { in_spam=1; in_ham=9}
|> Map.add "remind" { in_spam=1; in_ham=3}
|> Map.add "reminder" { in_spam=2; in_ham=6}
|> Map.add "reminders" { in_spam=0; in_ham=4}
|> Map.add "reminds" { in_spam=0; in_ham=6}
|> Map.add "remnants" { in_spam=0; in_ham=3}
|> Map.add "remodeling" { in_spam=0; in_ham=5}
|> Map.add "remote" { in_spam=9; in_ham=27}
|> Map.add "remotely" { in_spam=0; in_ham=7}
|> Map.add "removal" { in_spam=58; in_ham=4}
|> Map.add "removal'" { in_spam=6; in_ham=0}
|> Map.add "remove" { in_spam=168; in_ham=72}
|> Map.add "remove'" { in_spam=5; in_ham=1}
|> Map.add "removed" { in_spam=162; in_ham=69}
|> Map.add "removeme" { in_spam=9; in_ham=0}
|> Map.add "removes" { in_spam=6; in_ham=4}
|> Map.add "removing" { in_spam=3; in_ham=17}
|> Map.add "renamed" { in_spam=0; in_ham=6}
|> Map.add "render" { in_spam=1; in_ham=8}
|> Map.add "rendered" { in_spam=0; in_ham=4}
|> Map.add "rendering" { in_spam=1; in_ham=6}
|> Map.add "renew" { in_spam=0; in_ham=4}
|> Map.add "renewable" { in_spam=0; in_ham=4}
|> Map.add "renewal" { in_spam=6; in_ham=4}
|> Map.add "rennie" { in_spam=0; in_ham=4}
|> Map.add "renovate" { in_spam=0; in_ham=4}
|> Map.add "rent" { in_spam=4; in_ham=8}
|> Map.add "rental" { in_spam=10; in_ham=2}
|> Map.add "renting" { in_spam=0; in_ham=3}
|> Map.add "rep" { in_spam=3; in_ham=2}
|> Map.add "repackage" { in_spam=0; in_ham=5}
|> Map.add "repackaged" { in_spam=0; in_ham=7}
|> Map.add "repair" { in_spam=17; in_ham=6}
|> Map.add "repairs" { in_spam=5; in_ham=3}
|> Map.add "repeat" { in_spam=4; in_ham=6}
|> Map.add "repeated" { in_spam=1; in_ham=3}
|> Map.add "repeatedly" { in_spam=1; in_ham=9}
|> Map.add "replace" { in_spam=4; in_ham=26}
|> Map.add "replaced" { in_spam=1; in_ham=13}
|> Map.add "replacement" { in_spam=4; in_ham=11}
|> Map.add "replacements" { in_spam=2; in_ham=6}
|> Map.add "replaces" { in_spam=0; in_ham=3}
|> Map.add "replacing" { in_spam=3; in_ham=5}
|> Map.add "replcomps" { in_spam=0; in_ham=4}
|> Map.add "replete" { in_spam=1; in_ham=2}
|> Map.add "replicate" { in_spam=2; in_ham=2}
|> Map.add "replied" { in_spam=0; in_ham=12}
|> Map.add "replies" { in_spam=1; in_ham=4}
|> Map.add "reply" { in_spam=128; in_ham=19}
|> Map.add "reply-to" { in_spam=1; in_ham=9}
|> Map.add "replying" { in_spam=6; in_ham=8}
|> Map.add "report" { in_spam=35; in_ham=62}
|> Map.add "reported" { in_spam=7; in_ham=48}
|> Map.add "reportedby" { in_spam=0; in_ham=3}
|> Map.add "reporter" { in_spam=1; in_ham=8}
|> Map.add "reporters" { in_spam=1; in_ham=4}
|> Map.add "reporting" { in_spam=3; in_ham=22}
|> Map.add "reports" { in_spam=14; in_ham=44}
|> Map.add "repositories" { in_spam=0; in_ham=4}
|> Map.add "repository" { in_spam=0; in_ham=36}
|> Map.add "repositry" { in_spam=0; in_ham=3}
|> Map.add "represent" { in_spam=7; in_ham=9}
|> Map.add "represented" { in_spam=0; in_ham=3}
|> Map.add "representing" { in_spam=6; in_ham=4}
|> Map.add "represents" { in_spam=3; in_ham=2}
|> Map.add "reproduce" { in_spam=0; in_ham=15}
|> Map.add "reproduction" { in_spam=1; in_ham=2}
|> Map.add "republic" { in_spam=16; in_ham=12}
|> Map.add "republican" { in_spam=0; in_ham=23}
|> Map.add "republicans" { in_spam=0; in_ham=4}
|> Map.add "republics" { in_spam=0; in_ham=4}
|> Map.add "republocrat" { in_spam=0; in_ham=3}
|> Map.add "reputation" { in_spam=2; in_ham=11}
|> Map.add "req's" { in_spam=0; in_ham=3}
|> Map.add "request" { in_spam=43; in_ham=16}
|> Map.add "requested" { in_spam=7; in_ham=5}
|> Map.add "requesting" { in_spam=21; in_ham=1}
|> Map.add "requests" { in_spam=23; in_ham=15}
|> Map.add "require" { in_spam=13; in_ham=52}
|> Map.add "required" { in_spam=68; in_ham=42}
|> Map.add "requirement" { in_spam=6; in_ham=16}
|> Map.add "requirements" { in_spam=14; in_ham=18}
|> Map.add "requires" { in_spam=11; in_ham=59}
|> Map.add "requiring" { in_spam=0; in_ham=16}
|> Map.add "rereads" { in_spam=0; in_ham=5}
|> Map.add "res" { in_spam=3; in_ham=4}
|> Map.add "resaon" { in_spam=0; in_ham=3}
|> Map.add "rescue" { in_spam=0; in_ham=8}
|> Map.add "research" { in_spam=19; in_ham=63}
|> Map.add "researchers" { in_spam=0; in_ham=16}
|> Map.add "researching" { in_spam=4; in_ham=1}
|> Map.add "resell" { in_spam=11; in_ham=1}
|> Map.add "resembling" { in_spam=0; in_ham=3}
|> Map.add "resent" { in_spam=0; in_ham=6}
|> Map.add "reservations" { in_spam=0; in_ham=6}
|> Map.add "reserve" { in_spam=5; in_ham=7}
|> Map.add "reserved" { in_spam=13; in_ham=64}
|> Map.add "reservoir" { in_spam=0; in_ham=11}
|> Map.add "reset" { in_spam=3; in_ham=10}
|> Map.add "reshuffler" { in_spam=0; in_ham=3}
|> Map.add "residence" { in_spam=2; in_ham=4}
|> Map.add "resident" { in_spam=4; in_ham=3}
|> Map.add "residents" { in_spam=14; in_ham=11}
|> Map.add "residing" { in_spam=2; in_ham=2}
|> Map.add "residual" { in_spam=3; in_ham=1}
|> Map.add "resist" { in_spam=0; in_ham=7}
|> Map.add "resistance" { in_spam=0; in_ham=7}
|> Map.add "resolution" { in_spam=2; in_ham=16}
|> Map.add "resolve" { in_spam=1; in_ham=17}
|> Map.add "resolved" { in_spam=7; in_ham=15}
|> Map.add "resolving" { in_spam=0; in_ham=4}
|> Map.add "resort" { in_spam=0; in_ham=5}
|> Map.add "resource" { in_spam=4; in_ham=11}
|> Map.add "resources" { in_spam=11; in_ham=18}
|> Map.add "respect" { in_spam=18; in_ham=70}
|> Map.add "respectable" { in_spam=0; in_ham=6}
|> Map.add "respected" { in_spam=1; in_ham=3}
|> Map.add "respecting" { in_spam=1; in_ham=8}
|> Map.add "respective" { in_spam=1; in_ham=4}
|> Map.add "respectively" { in_spam=0; in_ham=3}
|> Map.add "respond" { in_spam=11; in_ham=15}
|> Map.add "responded" { in_spam=8; in_ham=10}
|> Map.add "responding" { in_spam=1; in_ham=8}
|> Map.add "response" { in_spam=59; in_ham=33}
|> Map.add "responses" { in_spam=9; in_ham=8}
|> Map.add "responsible" { in_spam=5; in_ham=15}
|> Map.add "responsive" { in_spam=3; in_ham=1}
|> Map.add "rest" { in_spam=15; in_ham=66}
|> Map.add "restart" { in_spam=0; in_ham=3}
|> Map.add "restaurant" { in_spam=3; in_ham=7}
|> Map.add "restaurants" { in_spam=2; in_ham=10}
|> Map.add "restore" { in_spam=1; in_ham=9}
|> Map.add "restored" { in_spam=0; in_ham=9}
|> Map.add "restoring" { in_spam=1; in_ham=3}
|> Map.add "restrict" { in_spam=0; in_ham=7}
|> Map.add "restricted" { in_spam=6; in_ham=2}
|> Map.add "restrictions" { in_spam=6; in_ham=14}
|> Map.add "restrictive" { in_spam=0; in_ham=3}
|> Map.add "result" { in_spam=14; in_ham=50}
|> Map.add "resulted" { in_spam=5; in_ham=10}
|> Map.add "resulting" { in_spam=2; in_ham=30}
|> Map.add "resultion" { in_spam=0; in_ham=3}
|> Map.add "results" { in_spam=22; in_ham=79}
|> Map.add "resume" { in_spam=2; in_ham=11}
|> Map.add "resumes" { in_spam=5; in_ham=0}
|> Map.add "retail" { in_spam=35; in_ham=7}
|> Map.add "retailers" { in_spam=1; in_ham=3}
|> Map.add "retain" { in_spam=3; in_ham=9}
|> Map.add "retained" { in_spam=3; in_ham=6}
|> Map.add "retigcionon" { in_spam=0; in_ham=3}
|> Map.add "retired" { in_spam=1; in_ham=4}
|> Map.add "retirement" { in_spam=7; in_ham=3}
|> Map.add "retrain" { in_spam=0; in_ham=4}
|> Map.add "retreat" { in_spam=0; in_ham=5}
|> Map.add "retrieve" { in_spam=1; in_ham=4}
|> Map.add "retrieved" { in_spam=1; in_ham=3}
|> Map.add "retrieving" { in_spam=1; in_ham=15}
|> Map.add "return" { in_spam=26; in_ham=54}
|> Map.add "return-path" { in_spam=0; in_ham=5}
|> Map.add "returned" { in_spam=8; in_ham=28}
|> Map.add "returning" { in_spam=0; in_ham=12}
|> Map.add "returns" { in_spam=7; in_ham=8}
|> Map.add "reuse" { in_spam=2; in_ham=2}
|> Map.add "reuters" { in_spam=0; in_ham=20}
|> Map.add "rev" { in_spam=0; in_ham=6}
|> Map.add "rev's" { in_spam=0; in_ham=3}
|> Map.add "reveal" { in_spam=4; in_ham=13}
|> Map.add "revealed" { in_spam=10; in_ham=15}
|> Map.add "revealing" { in_spam=2; in_ham=2}
|> Map.add "reveals" { in_spam=2; in_ham=4}
|> Map.add "revel" { in_spam=0; in_ham=3}
|> Map.add "revelation" { in_spam=0; in_ham=3}
|> Map.add "revenue" { in_spam=6; in_ham=13}
|> Map.add "revenues" { in_spam=9; in_ham=9}
|> Map.add "revered" { in_spam=1; in_ham=2}
|> Map.add "reversal" { in_spam=0; in_ham=3}
|> Map.add "reverse" { in_spam=4; in_ham=18}
|> Map.add "revert" { in_spam=3; in_ham=4}
|> Map.add "reverted" { in_spam=0; in_ham=3}
|> Map.add "review" { in_spam=7; in_ham=41}
|> Map.add "reviewed" { in_spam=0; in_ham=4}
|> Map.add "reviewing" { in_spam=0; in_ham=4}
|> Map.add "reviews" { in_spam=1; in_ham=8}
|> Map.add "revision" { in_spam=1; in_ham=16}
|> Map.add "revisions" { in_spam=0; in_ham=3}
|> Map.add "revival" { in_spam=0; in_ham=3}
|> Map.add "revolution" { in_spam=0; in_ham=9}
|> Map.add "reward" { in_spam=11; in_ham=3}
|> Map.add "rewards" { in_spam=3; in_ham=2}
|> Map.add "rewrite" { in_spam=0; in_ham=10}
|> Map.add "rewriting" { in_spam=0; in_ham=7}
|> Map.add "reynolds" { in_spam=0; in_ham=6}
|> Map.add "reza" { in_spam=2; in_ham=12}
|> Map.add "rfc" { in_spam=1; in_ham=12}
|> Map.add "rgb" { in_spam=3; in_ham=1}
|> Map.add "rgds" { in_spam=0; in_ham=4}
|> Map.add "rhetoric" { in_spam=0; in_ham=3}
|> Map.add "rhetorical" { in_spam=0; in_ham=7}
|> Map.add "rhyolite" { in_spam=0; in_ham=4}
|> Map.add "riaa" { in_spam=0; in_ham=9}
|> Map.add "rice" { in_spam=2; in_ham=3}
|> Map.add "rich" { in_spam=9; in_ham=14}
|> Map.add "richard" { in_spam=1; in_ham=10}
|> Map.add "rick" { in_spam=0; in_ham=23}
|> Map.add "rid" { in_spam=1; in_ham=11}
|> Map.add "ride" { in_spam=4; in_ham=11}
|> Map.add "rider" { in_spam=2; in_ham=2}
|> Map.add "ridge" { in_spam=0; in_ham=6}
|> Map.add "ridiculous" { in_spam=1; in_ham=5}
|> Map.add "ridiculously" { in_spam=0; in_ham=4}
|> Map.add "riding" { in_spam=2; in_ham=4}
|> Map.add "rifle" { in_spam=0; in_ham=3}
|> Map.add "right" { in_spam=116; in_ham=264}
|> Map.add "right-wing" { in_spam=0; in_ham=5}
|> Map.add "rights" { in_spam=21; in_ham=118}
|> Map.add "ring" { in_spam=5; in_ham=5}
|> Map.add "ringnalda" { in_spam=0; in_ham=5}
|> Map.add "rings" { in_spam=0; in_ham=6}
|> Map.add "riots" { in_spam=0; in_ham=4}
|> Map.add "rip" { in_spam=0; in_ham=6}
|> Map.add "ripped" { in_spam=6; in_ham=5}
|> Map.add "ripping" { in_spam=0; in_ham=3}
|> Map.add "rise" { in_spam=2; in_ham=14}
|> Map.add "rises" { in_spam=0; in_ham=3}
|> Map.add "rising" { in_spam=2; in_ham=3}
|> Map.add "risk" { in_spam=51; in_ham=23}
|> Map.add "risk-free" { in_spam=7; in_ham=0}
|> Map.add "risks" { in_spam=5; in_ham=8}
|> Map.add "risky" { in_spam=3; in_ham=3}
|> Map.add "rit" { in_spam=1; in_ham=2}
|> Map.add "rival" { in_spam=0; in_ham=10}
|> Map.add "rivalries" { in_spam=0; in_ham=4}
|> Map.add "rivals" { in_spam=0; in_ham=10}
|> Map.add "rivers" { in_spam=0; in_ham=4}
|> Map.add "rmi" { in_spam=1; in_ham=2}
|> Map.add "road" { in_spam=15; in_ham=30}
|> Map.add "roads" { in_spam=0; in_ham=6}
|> Map.add "roadside" { in_spam=6; in_ham=0}
|> Map.add "rob" { in_spam=4; in_ham=24}
|> Map.add "robb" { in_spam=0; in_ham=3}
|> Map.add "robbed" { in_spam=2; in_ham=2}
|> Map.add "robert" { in_spam=7; in_ham=72}
|> Map.add "roberts" { in_spam=0; in_ham=4}
|> Map.add "robin" { in_spam=0; in_ham=18}
|> Map.add "robot" { in_spam=2; in_ham=7}
|> Map.add "robots" { in_spam=0; in_ham=3}
|> Map.add "robust" { in_spam=0; in_ham=3}
|> Map.add "rock" { in_spam=3; in_ham=23}
|> Map.add "rockefeller" { in_spam=0; in_ham=6}
|> Map.add "rocket" { in_spam=4; in_ham=6}
|> Map.add "rocking" { in_spam=0; in_ham=6}
|> Map.add "rocks" { in_spam=1; in_ham=25}
|> Map.add "rocky" { in_spam=0; in_ham=4}
|> Map.add "rod" { in_spam=0; in_ham=6}
|> Map.add "roger" { in_spam=1; in_ham=3}
|> Map.add "rogers" { in_spam=0; in_ham=31}
|> Map.add "rogue" { in_spam=0; in_ham=7}
|> Map.add "rohit" { in_spam=0; in_ham=33}
|> Map.add "roi" { in_spam=0; in_ham=18}
|> Map.add "role" { in_spam=2; in_ham=21}
|> Map.add "role'" { in_spam=0; in_ham=8}
|> Map.add "roles" { in_spam=0; in_ham=11}
|> Map.add "roll" { in_spam=9; in_ham=9}
|> Map.add "rolled" { in_spam=5; in_ham=2}
|> Map.add "rolling" { in_spam=10; in_ham=6}
|> Map.add "rolls" { in_spam=2; in_ham=3}
|> Map.add "rolon" { in_spam=0; in_ham=3}
|> Map.add "rom" { in_spam=1; in_ham=2}
|> Map.add "roman" { in_spam=39; in_ham=50}
|> Map.add "romantic" { in_spam=0; in_ham=8}
|> Map.add "rome" { in_spam=0; in_ham=5}
|> Map.add "ronald" { in_spam=1; in_ham=2}
|> Map.add "roof" { in_spam=5; in_ham=2}
|> Map.add "room" { in_spam=3; in_ham=38}
|> Map.add "rooms" { in_spam=7; in_ham=6}
|> Map.add "roongthip" { in_spam=0; in_ham=3}
|> Map.add "roost" { in_spam=0; in_ham=5}
|> Map.add "root" { in_spam=2; in_ham=83}
|> Map.add "roots" { in_spam=1; in_ham=11}
|> Map.add "rory" { in_spam=0; in_ham=3}
|> Map.add "rose" { in_spam=1; in_ham=20}
|> Map.add "ross" { in_spam=0; in_ham=8}
|> Map.add "rosso" { in_spam=0; in_ham=4}
|> Map.add "rossum" { in_spam=0; in_ham=26}
|> Map.add "rotate" { in_spam=0; in_ham=5}
|> Map.add "rotating" { in_spam=0; in_ham=6}
|> Map.add "rotting" { in_spam=0; in_ham=4}
|> Map.add "rough" { in_spam=1; in_ham=4}
|> Map.add "roughly" { in_spam=1; in_ham=15}
|> Map.add "round" { in_spam=2; in_ham=20}
|> Map.add "round-up" { in_spam=0; in_ham=4}
|> Map.add "route" { in_spam=1; in_ham=7}
|> Map.add "routed" { in_spam=0; in_ham=5}
|> Map.add "router" { in_spam=0; in_ham=14}
|> Map.add "routers" { in_spam=0; in_ham=8}
|> Map.add "routine" { in_spam=6; in_ham=17}
|> Map.add "routinely" { in_spam=0; in_ham=3}
|> Map.add "routines" { in_spam=0; in_ham=4}
|> Map.add "routing" { in_spam=0; in_ham=14}
|> Map.add "row" { in_spam=5; in_ham=5}
|> Map.add "rowdy" { in_spam=0; in_ham=3}
|> Map.add "rowspan" { in_spam=44; in_ham=1}
|> Map.add "roy" { in_spam=0; in_ham=3}
|> Map.add "royal" { in_spam=4; in_ham=4}
|> Map.add "royalties" { in_spam=0; in_ham=3}
|> Map.add "royalty" { in_spam=0; in_ham=6}
|> Map.add "rpm" { in_spam=0; in_ham=145}
|> Map.add "rpm'" { in_spam=0; in_ham=6}
|> Map.add "rpm's" { in_spam=0; in_ham=5}
|> Map.add "rpm-list" { in_spam=0; in_ham=251}
|> Map.add "rpm-zzzlist" { in_spam=0; in_ham=4}
|> Map.add "rpmbuild" { in_spam=0; in_ham=20}
|> Map.add "rpmfind" { in_spam=0; in_ham=3}
|> Map.add "rpmforge" { in_spam=0; in_ham=13}
|> Map.add "rpmlib" { in_spam=0; in_ham=4}
|> Map.add "rpmnew" { in_spam=0; in_ham=4}
|> Map.add "rpms" { in_spam=0; in_ham=63}
|> Map.add "rrpzmc" { in_spam=0; in_ham=4}
|> Map.add "rsa" { in_spam=0; in_ham=6}
|> Map.add "rseq" { in_spam=0; in_ham=4}
|> Map.add "rss" { in_spam=0; in_ham=23}
|> Map.add "rss-dev" { in_spam=0; in_ham=4}
|> Map.add "rsync" { in_spam=0; in_ham=6}
|> Map.add "rtfm" { in_spam=0; in_ham=5}
|> Map.add "rtr" { in_spam=1; in_ham=2}
|> Map.add "ruban" { in_spam=0; in_ham=4}
|> Map.add "rubber" { in_spam=1; in_ham=3}
|> Map.add "ruby" { in_spam=0; in_ham=3}
|> Map.add "rude" { in_spam=0; in_ham=12}
|> Map.add "rug" { in_spam=0; in_ham=12}
|> Map.add "rule" { in_spam=0; in_ham=49}
|> Map.add "ruled" { in_spam=1; in_ham=12}
|> Map.add "rulers" { in_spam=0; in_ham=4}
|> Map.add "rules" { in_spam=6; in_ham=69}
|> Map.add "ruling" { in_spam=2; in_ham=11}
|> Map.add "rumored" { in_spam=0; in_ham=3}
|> Map.add "rumsfeld" { in_spam=0; in_ham=5}
|> Map.add "rumsfield" { in_spam=0; in_ham=3}
|> Map.add "run" { in_spam=30; in_ham=221}
|> Map.add "rundown" { in_spam=0; in_ham=3}
|> Map.add "runn" { in_spam=0; in_ham=5}
|> Map.add "runner" { in_spam=0; in_ham=3}
|> Map.add "running" { in_spam=4; in_ham=205}
|> Map.add "runs" { in_spam=2; in_ham=63}
|> Map.add "runtime" { in_spam=0; in_ham=8}
|> Map.add "rupert" { in_spam=1; in_ham=3}
|> Map.add "rural" { in_spam=0; in_ham=3}
|> Map.add "rush" { in_spam=5; in_ham=6}
|> Map.add "rushdie" { in_spam=0; in_ham=3}
|> Map.add "rushed" { in_spam=1; in_ham=2}
|> Map.add "russ" { in_spam=0; in_ham=5}
|> Map.add "russell" { in_spam=1; in_ham=23}
|> Map.add "russia" { in_spam=2; in_ham=8}
|> Map.add "russia's" { in_spam=0; in_ham=3}
|> Map.add "russian" { in_spam=1; in_ham=8}
|> Map.add "russians" { in_spam=0; in_ham=4}
|> Map.add "ryan" { in_spam=1; in_ham=2}
|> Map.add "saberi's" { in_spam=0; in_ham=3}
|> Map.add "sacred" { in_spam=2; in_ham=3}
|> Map.add "sacrificing" { in_spam=0; in_ham=7}
|> Map.add "sad" { in_spam=2; in_ham=12}
|> Map.add "saddam" { in_spam=0; in_ham=5}
|> Map.add "sadly" { in_spam=1; in_ham=4}
|> Map.add "safe" { in_spam=8; in_ham=32}
|> Map.add "safeguard" { in_spam=0; in_ham=5}
|> Map.add "safeguards" { in_spam=4; in_ham=4}
|> Map.add "safely" { in_spam=18; in_ham=5}
|> Map.add "safer" { in_spam=3; in_ham=4}
|> Map.add "safety" { in_spam=10; in_ham=13}
|> Map.add "sahara" { in_spam=1; in_ham=2}
|> Map.add "said" { in_spam=28; in_ham=313}
|> Map.add "sailed" { in_spam=1; in_ham=3}
|> Map.add "sailor" { in_spam=0; in_ham=3}
|> Map.add "sake" { in_spam=3; in_ham=12}
|> Map.add "sakes" { in_spam=0; in_ham=4}
|> Map.add "salary" { in_spam=1; in_ham=3}
|> Map.add "sale" { in_spam=20; in_ham=15}
|> Map.add "salealerts" { in_spam=6; in_ham=0}
|> Map.add "sales" { in_spam=43; in_ham=24}
|> Map.add "salman" { in_spam=0; in_ham=3}
|> Map.add "salon" { in_spam=0; in_ham=7}
|> Map.add "salt" { in_spam=2; in_ham=2}
|> Map.add "salted" { in_spam=0; in_ham=3}
|> Map.add "sam" { in_spam=1; in_ham=3}
|> Map.add "samba" { in_spam=0; in_ham=3}
|> Map.add "same" { in_spam=43; in_ham=381}
|> Map.add "sample" { in_spam=5; in_ham=18}
|> Map.add "sample-spam" { in_spam=0; in_ham=4}
|> Map.add "samples" { in_spam=5; in_ham=6}
|> Map.add "sampling" { in_spam=0; in_ham=3}
|> Map.add "samskar" { in_spam=0; in_ham=3}
|> Map.add "samuel" { in_spam=1; in_ham=4}
|> Map.add "san" { in_spam=7; in_ham=26}
|> Map.add "san-serif" { in_spam=6; in_ham=0}
|> Map.add "sand" { in_spam=1; in_ham=3}
|> Map.add "sandy" { in_spam=2; in_ham=3}
|> Map.add "sane" { in_spam=0; in_ham=8}
|> Map.add "sani" { in_spam=6; in_ham=0}
|> Map.add "sans" { in_spam=10; in_ham=3}
|> Map.add "sans-serif" { in_spam=82; in_ham=0}
|> Map.add "santa" { in_spam=2; in_ham=10}
|> Map.add "saou" { in_spam=0; in_ham=106}
|> Map.add "sapros" { in_spam=0; in_ham=4}
|> Map.add "sarah" { in_spam=4; in_ham=3}
|> Map.add "sarcastic" { in_spam=0; in_ham=3}
|> Map.add "sarvega" { in_spam=0; in_ham=8}
|> Map.add "saskatchewan" { in_spam=1; in_ham=3}
|> Map.add "sat" { in_spam=3; in_ham=37}
|> Map.add "satalk" { in_spam=0; in_ham=9}
|> Map.add "satan" { in_spam=0; in_ham=4}
|> Map.add "satellite" { in_spam=2; in_ham=14}
|> Map.add "satellites" { in_spam=0; in_ham=7}
|> Map.add "satest" { in_spam=0; in_ham=3}
|> Map.add "satisfaction" { in_spam=14; in_ham=7}
|> Map.add "satisfied" { in_spam=9; in_ham=5}
|> Map.add "satisfy" { in_spam=1; in_ham=2}
|> Map.add "saturation" { in_spam=0; in_ham=5}
|> Map.add "saturday" { in_spam=1; in_ham=27}
|> Map.add "saudi" { in_spam=2; in_ham=7}
|> Map.add "save" { in_spam=61; in_ham=56}
|> Map.add "saved" { in_spam=7; in_ham=25}
|> Map.add "saves" { in_spam=2; in_ham=4}
|> Map.add "saving" { in_spam=7; in_ham=10}
|> Map.add "savings" { in_spam=18; in_ham=5}
|> Map.add "saw" { in_spam=4; in_ham=45}
|> Map.add "sawa" { in_spam=0; in_ham=4}
|> Map.add "sax" { in_spam=0; in_ham=3}
|> Map.add "say" { in_spam=25; in_ham=241}
|> Map.add "saying" { in_spam=5; in_ham=71}
|> Map.add "says" { in_spam=9; in_ham=121}
|> Map.add "sbc" { in_spam=0; in_ham=5}
|> Map.add "sbin" { in_spam=0; in_ham=4}
|> Map.add "sblive" { in_spam=0; in_ham=7}
|> Map.add "scalable" { in_spam=0; in_ham=25}
|> Map.add "scale" { in_spam=0; in_ham=25}
|> Map.add "scaling" { in_spam=0; in_ham=4}
|> Map.add "scam" { in_spam=3; in_ham=10}
|> Map.add "scams" { in_spam=0; in_ham=4}
|> Map.add "scan" { in_spam=0; in_ham=22}
|> Map.add "scandal" { in_spam=0; in_ham=4}
|> Map.add "scandals" { in_spam=0; in_ham=3}
|> Map.add "scanfolder" { in_spam=0; in_ham=4}
|> Map.add "scanned" { in_spam=1; in_ham=8}
|> Map.add "scanning" { in_spam=0; in_ham=11}
|> Map.add "scans" { in_spam=0; in_ham=3}
|> Map.add "scarce" { in_spam=0; in_ham=9}
|> Map.add "scare" { in_spam=3; in_ham=5}
|> Map.add "scared" { in_spam=0; in_ham=4}
|> Map.add "scary" { in_spam=0; in_ham=11}
|> Map.add "scattered" { in_spam=0; in_ham=7}
|> Map.add "scavenger" { in_spam=0; in_ham=3}
|> Map.add "scenario" { in_spam=0; in_ham=12}
|> Map.add "scenarios" { in_spam=2; in_ham=2}
|> Map.add "scene" { in_spam=1; in_ham=10}
|> Map.add "scenes" { in_spam=0; in_ham=4}
|> Map.add "scent" { in_spam=2; in_ham=2}
|> Map.add "sceptical" { in_spam=0; in_ham=3}
|> Map.add "schaefer" { in_spam=0; in_ham=3}
|> Map.add "schedule" { in_spam=5; in_ham=2}
|> Map.add "scheduled" { in_spam=0; in_ham=10}
|> Map.add "schedules" { in_spam=0; in_ham=3}
|> Map.add "schema" { in_spam=0; in_ham=3}
|> Map.add "scheme" { in_spam=3; in_ham=25}
|> Map.add "schemenauer" { in_spam=0; in_ham=5}
|> Map.add "schemes" { in_spam=1; in_ham=6}
|> Map.add "schlange-h" { in_spam=0; in_ham=3}
|> Map.add "schleslib" { in_spam=0; in_ham=3}
|> Map.add "scholars" { in_spam=1; in_ham=5}
|> Map.add "scholarship" { in_spam=3; in_ham=2}
|> Map.add "school" { in_spam=12; in_ham=58}
|> Map.add "schoolgirls" { in_spam=4; in_ham=1}
|> Map.add "schools" { in_spam=4; in_ham=9}
|> Map.add "schuman" { in_spam=0; in_ham=35}
|> Map.add "schwartz" { in_spam=0; in_ham=11}
|> Map.add "schwartz-pr" { in_spam=0; in_ham=6}
|> Map.add "sci-fi" { in_spam=1; in_ham=4}
|> Map.add "science" { in_spam=8; in_ham=35}
|> Map.add "sciences" { in_spam=0; in_ham=11}
|> Map.add "scientiam" { in_spam=0; in_ham=9}
|> Map.add "scientific" { in_spam=1; in_ham=13}
|> Map.add "scientist" { in_spam=0; in_ham=12}
|> Map.add "scientists" { in_spam=0; in_ham=26}
|> Map.add "scientology" { in_spam=0; in_ham=5}
|> Map.add "scissors" { in_spam=0; in_ham=3}
|> Map.add "scnieitst" { in_spam=0; in_ham=3}
|> Map.add "sco" { in_spam=1; in_ham=5}
|> Map.add "scoop" { in_spam=0; in_ham=3}
|> Map.add "scope" { in_spam=0; in_ham=14}
|> Map.add "score" { in_spam=0; in_ham=49}
|> Map.add "scored" { in_spam=0; in_ham=8}
|> Map.add "scores" { in_spam=0; in_ham=36}
|> Map.add "scoring" { in_spam=0; in_ham=9}
|> Map.add "scotch" { in_spam=0; in_ham=3}
|> Map.add "scotland" { in_spam=0; in_ham=4}
|> Map.add "scots" { in_spam=0; in_ham=3}
|> Map.add "scotsman" { in_spam=0; in_ham=3}
|> Map.add "scott" { in_spam=0; in_ham=29}
|> Map.add "scottish" { in_spam=0; in_ham=7}
|> Map.add "scr" { in_spam=0; in_ham=4}
|> Map.add "scraped" { in_spam=0; in_ham=3}
|> Map.add "scratch" { in_spam=0; in_ham=13}
|> Map.add "scream" { in_spam=1; in_ham=4}
|> Map.add "screaming" { in_spam=0; in_ham=9}
|> Map.add "screams" { in_spam=0; in_ham=4}
|> Map.add "screen" { in_spam=3; in_ham=37}
|> Map.add "screened" { in_spam=1; in_ham=2}
|> Map.add "screening" { in_spam=8; in_ham=0}
|> Map.add "screenshot" { in_spam=0; in_ham=6}
|> Map.add "screw" { in_spam=0; in_ham=5}
|> Map.add "screwed" { in_spam=0; in_ham=6}
|> Map.add "screwing" { in_spam=0; in_ham=6}
|> Map.add "script" { in_spam=9; in_ham=69}
|> Map.add "scripted" { in_spam=0; in_ham=6}
|> Map.add "scripting" { in_spam=0; in_ham=8}
|> Map.add "scripts" { in_spam=1; in_ham=30}
|> Map.add "scroll" { in_spam=3; in_ham=3}
|> Map.add "scrutiny" { in_spam=1; in_ham=14}
|> Map.add "scsi" { in_spam=0; in_ham=6}
|> Map.add "sculptor" { in_spam=0; in_ham=3}
|> Map.add "sculpture" { in_spam=0; in_ham=3}
|> Map.add "sdl" { in_spam=0; in_ham=9}
|> Map.add "sdw" { in_spam=0; in_ham=12}
|> Map.add "sea" { in_spam=4; in_ham=13}
|> Map.add "sealing" { in_spam=0; in_ham=5}
|> Map.add "seals" { in_spam=0; in_ham=3}
|> Map.add "seamless" { in_spam=0; in_ham=3}
|> Map.add "seamlessly" { in_spam=0; in_ham=5}
|> Map.add "sean" { in_spam=0; in_ham=3}
|> Map.add "search" { in_spam=34; in_ham=63}
|> Map.add "search-adv" { in_spam=0; in_ham=3}
|> Map.add "searched" { in_spam=0; in_ham=6}
|> Map.add "searches" { in_spam=0; in_ham=4}
|> Map.add "searching" { in_spam=7; in_ham=17}
|> Map.add "season" { in_spam=2; in_ham=7}
|> Map.add "seat" { in_spam=1; in_ham=8}
|> Map.add "seats" { in_spam=0; in_ham=5}
|> Map.add "seattle" { in_spam=4; in_ham=17}
|> Map.add "seattle's" { in_spam=0; in_ham=4}
|> Map.add "sec" { in_spam=0; in_ham=17}
|> Map.add "second" { in_spam=31; in_ham=110}
|> Map.add "secondary" { in_spam=3; in_ham=17}
|> Map.add "secondly" { in_spam=4; in_ham=2}
|> Map.add "seconds" { in_spam=8; in_ham=34}
|> Map.add "secprog" { in_spam=0; in_ham=4}
|> Map.add "secrecy" { in_spam=8; in_ham=4}
|> Map.add "secret" { in_spam=24; in_ham=28}
|> Map.add "secretary" { in_spam=2; in_ham=12}
|> Map.add "secrets" { in_spam=13; in_ham=4}
|> Map.add "sect" { in_spam=0; in_ham=5}
|> Map.add "section" { in_spam=23; in_ham=41}
|> Map.add "sections" { in_spam=2; in_ham=11}
|> Map.add "sector" { in_spam=2; in_ham=11}
|> Map.add "sectors" { in_spam=2; in_ham=4}
|> Map.add "secular" { in_spam=0; in_ham=3}
|> Map.add "secure" { in_spam=34; in_ham=39}
|> Map.add "secured" { in_spam=0; in_ham=8}
|> Map.add "securely" { in_spam=0; in_ham=3}
|> Map.add "secures" { in_spam=1; in_ham=6}
|> Map.add "securing" { in_spam=2; in_ham=3}
|> Map.add "securities" { in_spam=6; in_ham=4}
|> Map.add "security" { in_spam=41; in_ham=67}
|> Map.add "sed" { in_spam=0; in_ham=14}
|> Map.add "sedit" { in_spam=0; in_ham=11}
|> Map.add "see" { in_spam=76; in_ham=391}
|> Map.add "seed" { in_spam=1; in_ham=9}
|> Map.add "seedcp" { in_spam=0; in_ham=6}
|> Map.add "seeds" { in_spam=1; in_ham=3}
|> Map.add "seeing" { in_spam=2; in_ham=50}
|> Map.add "seek" { in_spam=14; in_ham=16}
|> Map.add "seeker" { in_spam=4; in_ham=1}
|> Map.add "seeking" { in_spam=6; in_ham=9}
|> Map.add "seeks" { in_spam=1; in_ham=20}
|> Map.add "seem" { in_spam=10; in_ham=137}
|> Map.add "seemed" { in_spam=2; in_ham=23}
|> Map.add "seemingly" { in_spam=0; in_ham=8}
|> Map.add "seems" { in_spam=6; in_ham=212}
|> Map.add "seen" { in_spam=31; in_ham=134}
|> Map.add "sees" { in_spam=2; in_ham=9}
|> Map.add "seeya" { in_spam=0; in_ham=6}
|> Map.add "segfault" { in_spam=0; in_ham=4}
|> Map.add "sein" { in_spam=0; in_ham=3}
|> Map.add "seize" { in_spam=0; in_ham=5}
|> Map.add "seized" { in_spam=4; in_ham=6}
|> Map.add "sel" { in_spam=0; in_ham=9}
|> Map.add "seldom" { in_spam=0; in_ham=8}
|> Map.add "select" { in_spam=17; in_ham=31}
|> Map.add "selected" { in_spam=16; in_ham=22}
|> Map.add "selecting" { in_spam=3; in_ham=4}
|> Map.add "selection" { in_spam=13; in_ham=20}
|> Map.add "selections" { in_spam=1; in_ham=3}
|> Map.add "selects" { in_spam=0; in_ham=4}
|> Map.add "selecttypein" { in_spam=0; in_ham=6}
|> Map.add "self" { in_spam=20; in_ham=17}
|> Map.add "self-censor" { in_spam=0; in_ham=3}
|> Map.add "self-defense" { in_spam=0; in_ham=4}
|> Map.add "self-made" { in_spam=0; in_ham=6}
|> Map.add "selfish" { in_spam=1; in_ham=4}
|> Map.add "sell" { in_spam=35; in_ham=58}
|> Map.add "seller" { in_spam=1; in_ham=2}
|> Map.add "sellers" { in_spam=2; in_ham=3}
|> Map.add "selling" { in_spam=14; in_ham=48}
|> Map.add "sells" { in_spam=7; in_ham=6}
|> Map.add "semantic" { in_spam=0; in_ham=6}
|> Map.add "semantics" { in_spam=0; in_ham=5}
|> Map.add "seminar" { in_spam=5; in_ham=5}
|> Map.add "sen" { in_spam=2; in_ham=2}
|> Map.add "senate" { in_spam=1; in_ham=6}
|> Map.add "senator" { in_spam=0; in_ham=7}
|> Map.add "send" { in_spam=110; in_ham=188}
|> Map.add "sender" { in_spam=6; in_ham=41}
|> Map.add "senders" { in_spam=0; in_ham=12}
|> Map.add "sending" { in_spam=46; in_ham=44}
|> Map.add "sendmail" { in_spam=0; in_ham=23}
|> Map.add "sends" { in_spam=1; in_ham=9}
|> Map.add "senior" { in_spam=9; in_ham=23}
|> Map.add "senqeuce" { in_spam=0; in_ham=3}
|> Map.add "sensation" { in_spam=3; in_ham=2}
|> Map.add "sense" { in_spam=9; in_ham=62}
|> Map.add "senseless" { in_spam=0; in_ham=3}
|> Map.add "senses" { in_spam=0; in_ham=3}
|> Map.add "sensible" { in_spam=0; in_ham=6}
|> Map.add "sensing" { in_spam=0; in_ham=4}
|> Map.add "sensitive" { in_spam=4; in_ham=2}
|> Map.add "sensor" { in_spam=0; in_ham=3}
|> Map.add "sensors" { in_spam=0; in_ham=3}
|> Map.add "sent" { in_spam=128; in_ham=211}
|> Map.add "sentence" { in_spam=0; in_ham=10}
|> Map.add "sentenced" { in_spam=0; in_ham=4}
|> Map.add "sentences" { in_spam=0; in_ham=3}
|> Map.add "sentimental" { in_spam=0; in_ham=5}
|> Map.add "sentiments" { in_spam=1; in_ham=3}
|> Map.add "sentto'" { in_spam=28; in_ham=0}
|> Map.add "sep" { in_spam=5; in_ham=331}
|> Map.add "separate" { in_spam=2; in_ham=35}
|> Map.add "separated" { in_spam=1; in_ham=5}
|> Map.add "separately" { in_spam=5; in_ham=7}
|> Map.add "separating" { in_spam=1; in_ham=3}
|> Map.add "seperate" { in_spam=2; in_ham=2}
|> Map.add "sept" { in_spam=4; in_ham=17}
|> Map.add "september" { in_spam=10; in_ham=184}
|> Map.add "seq" { in_spam=0; in_ham=17}
|> Map.add "sequence" { in_spam=7; in_ham=36}
|> Map.add "sequences" { in_spam=0; in_ham=43}
|> Map.add "sergeant" { in_spam=0; in_ham=4}
|> Map.add "serial" { in_spam=10; in_ham=13}
|> Map.add "series" { in_spam=3; in_ham=34}
|> Map.add "serif" { in_spam=15; in_ham=0}
|> Map.add "serious" { in_spam=16; in_ham=38}
|> Map.add "seriously" { in_spam=11; in_ham=26}
|> Map.add "servants" { in_spam=4; in_ham=5}
|> Map.add "serve" { in_spam=6; in_ham=4}
|> Map.add "served" { in_spam=2; in_ham=11}
|> Map.add "server" { in_spam=28; in_ham=155}
|> Map.add "server's" { in_spam=0; in_ham=6}
|> Map.add "servers" { in_spam=1; in_ham=56}
|> Map.add "serves" { in_spam=1; in_ham=7}
|> Map.add "service" { in_spam=100; in_ham=112}
|> Map.add "services" { in_spam=76; in_ham=80}
|> Map.add "serving" { in_spam=1; in_ham=5}
|> Map.add "servlet" { in_spam=0; in_ham=9}
|> Map.add "servlets" { in_spam=0; in_ham=4}
|> Map.add "session" { in_spam=1; in_ham=12}
|> Map.add "sessions" { in_spam=1; in_ham=4}
|> Map.add "set" { in_spam=16; in_ham=236}
|> Map.add "set-up" { in_spam=5; in_ham=1}
|> Map.add "setcur" { in_spam=0; in_ham=5}
|> Map.add "setgid" { in_spam=0; in_ham=3}
|> Map.add "seth" { in_spam=0; in_ham=4}
|> Map.add "sets" { in_spam=1; in_ham=37}
|> Map.add "setting" { in_spam=1; in_ham=31}
|> Map.add "settings" { in_spam=0; in_ham=16}
|> Map.add "settle" { in_spam=6; in_ham=6}
|> Map.add "settled" { in_spam=3; in_ham=9}
|> Map.add "settlement" { in_spam=5; in_ham=16}
|> Map.add "settlements" { in_spam=6; in_ham=1}
|> Map.add "settler" { in_spam=0; in_ham=4}
|> Map.add "setuid" { in_spam=0; in_ham=7}
|> Map.add "setup" { in_spam=6; in_ham=41}
|> Map.add "seven" { in_spam=10; in_ham=25}
|> Map.add "seventh" { in_spam=3; in_ham=9}
|> Map.add "seventy" { in_spam=3; in_ham=1}
|> Map.add "several" { in_spam=20; in_ham=100}
|> Map.add "severe" { in_spam=5; in_ham=6}
|> Map.add "severely" { in_spam=0; in_ham=6}
|> Map.add "severity" { in_spam=0; in_ham=5}
|> Map.add "sex" { in_spam=12; in_ham=45}
|> Map.add "sexaholics" { in_spam=0; in_ham=4}
|> Map.add "sexual" { in_spam=5; in_ham=15}
|> Map.add "sexy" { in_spam=8; in_ham=5}
|> Map.add "sez" { in_spam=0; in_ham=9}
|> Map.add "sf's" { in_spam=0; in_ham=3}
|> Map.add "sgo" { in_spam=14; in_ham=0}
|> Map.add "sha" { in_spam=0; in_ham=23}
|> Map.add "shackle" { in_spam=0; in_ham=3}
|> Map.add "shadow" { in_spam=0; in_ham=3}
|> Map.add "shadowy" { in_spam=0; in_ham=4}
|> Map.add "shafer" { in_spam=0; in_ham=8}
|> Map.add "shake" { in_spam=1; in_ham=5}
|> Map.add "shaking" { in_spam=0; in_ham=3}
|> Map.add "shall" { in_spam=16; in_ham=8}
|> Map.add "shallow" { in_spam=0; in_ham=7}
|> Map.add "shalt" { in_spam=0; in_ham=3}
|> Map.add "shambles" { in_spam=0; in_ham=3}
|> Map.add "shame" { in_spam=3; in_ham=5}
|> Map.add "shankar" { in_spam=0; in_ham=6}
|> Map.add "shantytowns" { in_spam=0; in_ham=5}
|> Map.add "shape" { in_spam=21; in_ham=25}
|> Map.add "shapes" { in_spam=1; in_ham=4}
|> Map.add "shaping" { in_spam=0; in_ham=6}
|> Map.add "share" { in_spam=30; in_ham=61}
|> Map.add "shareable" { in_spam=0; in_ham=3}
|> Map.add "shared" { in_spam=7; in_ham=33}
|> Map.add "shareholders" { in_spam=0; in_ham=4}
|> Map.add "shareinnn" { in_spam=0; in_ham=3}
|> Map.add "shares" { in_spam=9; in_ham=12}
|> Map.add "sharing" { in_spam=7; in_ham=16}
|> Map.add "sharp" { in_spam=0; in_ham=6}
|> Map.add "sharper" { in_spam=1; in_ham=3}
|> Map.add "sharply" { in_spam=0; in_ham=4}
|> Map.add "shavell" { in_spam=0; in_ham=3}
|> Map.add "she" { in_spam=11; in_ham=93}
|> Map.add "she'd" { in_spam=0; in_ham=3}
|> Map.add "she'll" { in_spam=0; in_ham=3}
|> Map.add "she's" { in_spam=0; in_ham=6}
|> Map.add "shed" { in_spam=0; in_ham=4}
|> Map.add "sheep" { in_spam=0; in_ham=9}
|> Map.add "sheer" { in_spam=0; in_ham=4}
|> Map.add "sheets" { in_spam=9; in_ham=2}
|> Map.add "sheffield" { in_spam=0; in_ham=3}
|> Map.add "shell" { in_spam=1; in_ham=20}
|> Map.add "shelley" { in_spam=0; in_ham=7}
|> Map.add "shells" { in_spam=0; in_ham=3}
|> Map.add "sherman" { in_spam=1; in_ham=3}
|> Map.add "shield" { in_spam=0; in_ham=5}
|> Map.add "shift" { in_spam=0; in_ham=12}
|> Map.add "shifting" { in_spam=0; in_ham=4}
|> Map.add "shine" { in_spam=0; in_ham=5}
|> Map.add "shining" { in_spam=0; in_ham=5}
|> Map.add "ship" { in_spam=3; in_ham=20}
|> Map.add "shipments" { in_spam=1; in_ham=2}
|> Map.add "shipped" { in_spam=7; in_ham=9}
|> Map.add "shipping" { in_spam=45; in_ham=8}
|> Map.add "ships" { in_spam=0; in_ham=4}
|> Map.add "shipwright" { in_spam=0; in_ham=19}
|> Map.add "shirley" { in_spam=0; in_ham=7}
|> Map.add "shirt" { in_spam=6; in_ham=3}
|> Map.add "shit" { in_spam=0; in_ham=16}
|> Map.add "shite" { in_spam=0; in_ham=6}
|> Map.add "shiver" { in_spam=0; in_ham=4}
|> Map.add "shock" { in_spam=3; in_ham=11}
|> Map.add "shocked" { in_spam=8; in_ham=6}
|> Map.add "shoe" { in_spam=0; in_ham=7}
|> Map.add "shoes" { in_spam=0; in_ham=7}
|> Map.add "shoot" { in_spam=0; in_ham=13}
|> Map.add "shooting" { in_spam=0; in_ham=11}
|> Map.add "shop" { in_spam=22; in_ham=14}
|> Map.add "shopping" { in_spam=9; in_ham=4}
|> Map.add "shops" { in_spam=2; in_ham=4}
|> Map.add "shore" { in_spam=0; in_ham=9}
|> Map.add "shores" { in_spam=1; in_ham=3}
|> Map.add "short" { in_spam=18; in_ham=55}
|> Map.add "short-term" { in_spam=0; in_ham=5}
|> Map.add "shortage" { in_spam=0; in_ham=4}
|> Map.add "shorter" { in_spam=0; in_ham=7}
|> Map.add "shortest" { in_spam=5; in_ham=0}
|> Map.add "shortly" { in_spam=1; in_ham=6}
|> Map.add "shot" { in_spam=2; in_ham=19}
|> Map.add "shotgun" { in_spam=3; in_ham=3}
|> Map.add "shots" { in_spam=3; in_ham=2}
|> Map.add "should" { in_spam=80; in_ham=384}
|> Map.add "shoulder" { in_spam=1; in_ham=2}
|> Map.add "shoulders" { in_spam=0; in_ham=8}
|> Map.add "shouldn't" { in_spam=0; in_ham=35}
|> Map.add "shout" { in_spam=0; in_ham=14}
|> Map.add "shouted" { in_spam=0; in_ham=4}
|> Map.add "shouting" { in_spam=0; in_ham=13}
|> Map.add "show" { in_spam=33; in_ham=122}
|> Map.add "showcase" { in_spam=1; in_ham=3}
|> Map.add "showed" { in_spam=1; in_ham=17}
|> Map.add "showfiles" { in_spam=0; in_ham=4}
|> Map.add "showing" { in_spam=1; in_ham=34}
|> Map.add "shown" { in_spam=12; in_ham=9}
|> Map.add "shownew" { in_spam=0; in_ham=4}
|> Map.add "shows" { in_spam=12; in_ham=38}
|> Map.add "shrimp" { in_spam=0; in_ham=6}
|> Map.add "shrink" { in_spam=0; in_ham=6}
|> Map.add "shrinks" { in_spam=0; in_ham=5}
|> Map.add "shrub" { in_spam=0; in_ham=3}
|> Map.add "shtml" { in_spam=0; in_ham=29}
|> Map.add "shuffle" { in_spam=0; in_ham=5}
|> Map.add "shuffling" { in_spam=4; in_ham=1}
|> Map.add "shut" { in_spam=1; in_ham=16}
|> Map.add "shutdown" { in_spam=0; in_ham=5}
|> Map.add "shutting" { in_spam=1; in_ham=3}
|> Map.add "shuttle" { in_spam=2; in_ham=5}
|> Map.add "shy" { in_spam=1; in_ham=6}
|> Map.add "shyness" { in_spam=0; in_ham=3}
|> Map.add "sic" { in_spam=1; in_ham=4}
|> Map.add "sick" { in_spam=2; in_ham=10}
|> Map.add "sid" { in_spam=3; in_ham=67}
|> Map.add "side" { in_spam=8; in_ham=52}
|> Map.add "side-by-side" { in_spam=1; in_ham=3}
|> Map.add "sidebar" { in_spam=0; in_ham=7}
|> Map.add "sides" { in_spam=0; in_ham=12}
|> Map.add "sidewalk" { in_spam=0; in_ham=6}
|> Map.add "siemens" { in_spam=0; in_ham=6}
|> Map.add "sierra" { in_spam=6; in_ham=0}
|> Map.add "sifting" { in_spam=2; in_ham=2}
|> Map.add "sig" { in_spam=0; in_ham=13}
|> Map.add "sigh" { in_spam=0; in_ham=21}
|> Map.add "sight" { in_spam=0; in_ham=8}
|> Map.add "sighting" { in_spam=0; in_ham=3}
|> Map.add "sightings" { in_spam=0; in_ham=3}
|> Map.add "sign" { in_spam=19; in_ham=27}
|> Map.add "signal" { in_spam=3; in_ham=21}
|> Map.add "signals" { in_spam=0; in_ham=8}
|> Map.add "signature" { in_spam=6; in_ham=35}
|> Map.add "signatures" { in_spam=2; in_ham=26}
|> Map.add "signed" { in_spam=18; in_ham=40}
|> Map.add "significance" { in_spam=2; in_ham=5}
|> Map.add "significant" { in_spam=3; in_ham=40}
|> Map.add "signing" { in_spam=2; in_ham=16}
|> Map.add "signs" { in_spam=0; in_ham=17}
|> Map.add "signup" { in_spam=10; in_ham=3}
|> Map.add "sigs" { in_spam=0; in_ham=9}
|> Map.add "silcom" { in_spam=0; in_ham=3}
|> Map.add "silence" { in_spam=0; in_ham=6}
|> Map.add "silent" { in_spam=1; in_ham=5}
|> Map.add "silently" { in_spam=0; in_ham=5}
|> Map.add "silicon" { in_spam=1; in_ham=6}
|> Map.add "silly" { in_spam=0; in_ham=24}
|> Map.add "silver" { in_spam=0; in_ham=7}
|> Map.add "similar" { in_spam=15; in_ham=108}
|> Map.add "similarity" { in_spam=0; in_ham=8}
|> Map.add "similarly" { in_spam=1; in_ham=12}
|> Map.add "simon" { in_spam=0; in_ham=6}
|> Map.add "simple" { in_spam=60; in_ham=76}
|> Map.add "simpler" { in_spam=2; in_ham=11}
|> Map.add "simplicity" { in_spam=3; in_ham=3}
|> Map.add "simplified" { in_spam=6; in_ham=4}
|> Map.add "simply" { in_spam=64; in_ham=79}
|> Map.add "simpson" { in_spam=6; in_ham=6}
|> Map.add "simpsons" { in_spam=0; in_ham=4}
|> Map.add "sims" { in_spam=0; in_ham=3}
|> Map.add "simulate" { in_spam=0; in_ham=3}
|> Map.add "since" { in_spam=39; in_ham=272}
|> Map.add "sincere" { in_spam=5; in_ham=0}
|> Map.add "sincerely" { in_spam=35; in_ham=3}
|> Map.add "sinderson" { in_spam=0; in_ham=3}
|> Map.add "sing" { in_spam=0; in_ham=4}
|> Map.add "singapore" { in_spam=2; in_ham=7}
|> Map.add "singing" { in_spam=0; in_ham=5}
|> Map.add "single" { in_spam=8; in_ham=103}
|> Map.add "singles" { in_spam=7; in_ham=3}
|> Map.add "sink" { in_spam=3; in_ham=2}
|> Map.add "sinking" { in_spam=2; in_ham=2}
|> Map.add "sir" { in_spam=31; in_ham=3}
|> Map.add "sircam" { in_spam=0; in_ham=3}
|> Map.add "sister" { in_spam=7; in_ham=9}
|> Map.add "sit" { in_spam=2; in_ham=19}
|> Map.add "sitaker" { in_spam=0; in_ham=10}
|> Map.add "site" { in_spam=60; in_ham=128}
|> Map.add "site-wide" { in_spam=0; in_ham=4}
|> Map.add "sites" { in_spam=56; in_ham=39}
|> Map.add "sitescooper" { in_spam=0; in_ham=3}
|> Map.add "sitting" { in_spam=3; in_ham=27}
|> Map.add "situation" { in_spam=16; in_ham=38}
|> Map.add "situations" { in_spam=2; in_ham=12}
|> Map.add "six" { in_spam=33; in_ham=41}
|> Map.add "six-figure" { in_spam=0; in_ham=3}
|> Map.add "size" { in_spam=207; in_ham=77}
|> Map.add "sizes" { in_spam=4; in_ham=16}
|> Map.add "skeptical" { in_spam=6; in_ham=10}
|> Map.add "skepticism" { in_spam=0; in_ham=4}
|> Map.add "skewed" { in_spam=1; in_ham=4}
|> Map.add "skies" { in_spam=0; in_ham=4}
|> Map.add "skill" { in_spam=0; in_ham=4}
|> Map.add "skilled" { in_spam=0; in_ham=4}
|> Map.add "skills" { in_spam=13; in_ham=9}
|> Map.add "skin" { in_spam=4; in_ham=5}
|> Map.add "skip" { in_spam=1; in_ham=43}
|> Map.add "skipped" { in_spam=0; in_ham=25}
|> Map.add "skipping" { in_spam=0; in_ham=6}
|> Map.add "skirmish" { in_spam=0; in_ham=3}
|> Map.add "sky" { in_spam=0; in_ham=9}
|> Map.add "skyrocket" { in_spam=5; in_ham=0}
|> Map.add "skytt" { in_spam=0; in_ham=15}
|> Map.add "skytta" { in_spam=0; in_ham=15}
|> Map.add "slack" { in_spam=0; in_ham=3}
|> Map.add "slackware" { in_spam=0; in_ham=3}
|> Map.add "slash" { in_spam=0; in_ham=3}
|> Map.add "slashdot" { in_spam=0; in_ham=20}
|> Map.add "slate's" { in_spam=0; in_ham=3}
|> Map.add "slave" { in_spam=0; in_ham=3}
|> Map.add "slavery" { in_spam=1; in_ham=7}
|> Map.add "slaves" { in_spam=0; in_ham=6}
|> Map.add "sledgehammer" { in_spam=0; in_ham=3}
|> Map.add "sleep" { in_spam=7; in_ham=3}
|> Map.add "sleeping" { in_spam=2; in_ham=4}
|> Map.add "sleepycat" { in_spam=0; in_ham=6}
|> Map.add "slept" { in_spam=0; in_ham=4}
|> Map.add "slice" { in_spam=5; in_ham=1}
|> Map.add "slick" { in_spam=4; in_ham=4}
|> Map.add "slides" { in_spam=0; in_ham=4}
|> Map.add "slight" { in_spam=0; in_ham=13}
|> Map.add "slightly" { in_spam=1; in_ham=30}
|> Map.add "slim" { in_spam=13; in_ham=7}
|> Map.add "slip" { in_spam=3; in_ham=6}
|> Map.add "slipcon" { in_spam=0; in_ham=6}
|> Map.add "slipping" { in_spam=0; in_ham=3}
|> Map.add "slips" { in_spam=0; in_ham=3}
|> Map.add "slobbering" { in_spam=0; in_ham=4}
|> Map.add "slogans" { in_spam=0; in_ham=3}
|> Map.add "slot" { in_spam=1; in_ham=2}
|> Map.add "slow" { in_spam=5; in_ham=48}
|> Map.add "slower" { in_spam=0; in_ham=17}
|> Map.add "slowly" { in_spam=2; in_ham=11}
|> Map.add "sluts" { in_spam=2; in_ham=2}
|> Map.add "small" { in_spam=30; in_ham=105}
|> Map.add "small-time" { in_spam=2; in_ham=2}
|> Map.add "smaller" { in_spam=1; in_ham=23}
|> Map.add "smallest" { in_spam=1; in_ham=5}
|> Map.add "smart" { in_spam=1; in_ham=20}
|> Map.add "smartass" { in_spam=0; in_ham=3}
|> Map.add "smarter" { in_spam=0; in_ham=8}
|> Map.add "smarterchild" { in_spam=0; in_ham=3}
|> Map.add "smartest" { in_spam=1; in_ham=2}
|> Map.add "smartgroups" { in_spam=0; in_ham=3}
|> Map.add "smartobject" { in_spam=0; in_ham=6}
|> Map.add "smell" { in_spam=5; in_ham=5}
|> Map.add "smile" { in_spam=1; in_ham=8}
|> Map.add "smiles" { in_spam=0; in_ham=5}
|> Map.add "smiling" { in_spam=1; in_ham=4}
|> Map.add "smith" { in_spam=2; in_ham=14}
|> Map.add "smoke" { in_spam=3; in_ham=6}
|> Map.add "smoker" { in_spam=5; in_ham=0}
|> Map.add "smokers" { in_spam=10; in_ham=0}
|> Map.add "smokestacks" { in_spam=0; in_ham=3}
|> Map.add "smoking" { in_spam=4; in_ham=6}
|> Map.add "smooth" { in_spam=4; in_ham=6}
|> Map.add "smoothly" { in_spam=0; in_ham=7}
|> Map.add "smp" { in_spam=0; in_ham=11}
|> Map.add "smrazor" { in_spam=0; in_ham=4}
|> Map.add "sms" { in_spam=3; in_ham=4}
|> Map.add "smtp" { in_spam=0; in_ham=17}
|> Map.add "snail" { in_spam=0; in_ham=4}
|> Map.add "snake" { in_spam=0; in_ham=3}
|> Map.add "snap" { in_spam=0; in_ham=6}
|> Map.add "snapshots" { in_spam=0; in_ham=6}
|> Map.add "snd" { in_spam=0; in_ham=5}
|> Map.add "snickers" { in_spam=0; in_ham=3}
|> Map.add "snip" { in_spam=0; in_ham=18}
|> Map.add "snipped" { in_spam=0; in_ham=3}
|> Map.add "snippet" { in_spam=3; in_ham=2}
|> Map.add "snmp" { in_spam=0; in_ham=6}
|> Map.add "snna" { in_spam=0; in_ham=13}
|> Map.add "snopes" { in_spam=0; in_ham=5}
|> Map.add "snow" { in_spam=0; in_ham=4}
|> Map.add "so-called" { in_spam=7; in_ham=7}
|> Map.add "soaking" { in_spam=0; in_ham=4}
|> Map.add "soap" { in_spam=0; in_ham=11}
|> Map.add "soapbox" { in_spam=0; in_ham=5}
|> Map.add "sober" { in_spam=0; in_ham=3}
|> Map.add "social" { in_spam=16; in_ham=44}
|> Map.add "socialism" { in_spam=0; in_ham=11}
|> Map.add "socialist" { in_spam=0; in_ham=4}
|> Map.add "societies" { in_spam=0; in_ham=17}
|> Map.add "society" { in_spam=6; in_ham=44}
|> Map.add "socket" { in_spam=0; in_ham=11}
|> Map.add "sockets" { in_spam=0; in_ham=3}
|> Map.add "soft" { in_spam=1; in_ham=4}
|> Map.add "softalla" { in_spam=0; in_ham=4}
|> Map.add "softbank" { in_spam=0; in_ham=6}

