open Database

let db =
  Map.empty
  |> Map.add "0.5.7" { in_spam = 0; in_ham = 5 }
  |> Map.add "2.14" { in_spam = 0; in_ham = 13 }
  |> Map.add "2.40" { in_spam = 0; in_ham = 19 }
  |> Map.add "2.41" { in_spam = 0; in_ham = 17 }
  |> Map.add "2002" { in_spam = 13; in_ham = 64 }
  |> Map.add "7.3" { in_spam = 0; in_ham = 6 }
  |> Map.add "8.0" { in_spam = 0; in_ham = 22 }
  |> Map.add "ADV" { in_spam = 18; in_ham = 0 }
  |> Map.add "ALSA" { in_spam = 0; in_ham = 32 }
  |> Map.add "ARRRGHHH" { in_spam = 0; in_ham = 9 }
  |> Map.add "CVS" { in_spam = 0; in_ham = 39 }
  |> Map.add "DMA" { in_spam = 0; in_ham = 17 }
  |> Map.add "DNS" { in_spam = 0; in_ham = 7 }
  |> Map.add "DVD" { in_spam = 2; in_ham = 25 }
  |> Map.add "FREE" { in_spam = 10; in_ham = 0 }
  |> Map.add "GDC" { in_spam = 0; in_ham = 6 }
  |> Map.add "GPG" { in_spam = 0; in_ham = 9 }
  |> Map.add "HTML" { in_spam = 0; in_ham = 5 }
  |> Map.add "IDE" { in_spam = 0; in_ham = 5 }
  |> Map.add "ILUG" { in_spam = 32; in_ham = 92 }
  |> Map.add "IRR" { in_spam = 0; in_ham = 5 }
  |> Map.add "RELEASE" { in_spam = 0; in_ham = 7 }
  |> Map.add "RSS" { in_spam = 0; in_ham = 10 }
  |> Map.add "SACVS" { in_spam = 0; in_ham = 18 }
  |> Map.add "SYSTEMWORKS" { in_spam = 12; in_ham = 0 }
  |> Map.add "USB" { in_spam = 0; in_ham = 5 }
  |> Map.add "YOUR" { in_spam = 13; in_ham = 3 }
  |> Map.add "about" { in_spam = 4; in_ham = 20 }
  |> Map.add "absurdities" { in_spam = 0; in_ham = 9 }
  |> Map.add "access" { in_spam = 3; in_ham = 5 }
  |> Map.add "activebuddy" { in_spam = 0; in_ham = 11 }
  |> Map.add "adhesion" { in_spam = 0; in_ham = 5 }
  |> Map.add "adsl" { in_spam = 0; in_ham = 7 }
  |> Map.add "adv" { in_spam = 20; in_ham = 0 }
  |> Map.add "advice" { in_spam = 0; in_ham = 5 }
  |> Map.add "after" { in_spam = 0; in_ham = 10 }
  |> Map.add "again" { in_spam = 2; in_ham = 8 }
  |> Map.add "all" { in_spam = 3; in_ham = 19 }
  |> Map.add "almost" { in_spam = 0; in_ham = 25 }
  |> Map.add "alsa" { in_spam = 0; in_ham = 34 }
  |> Map.add "alsa-driver" { in_spam = 0; in_ham = 12 }
  |> Map.add "amendment" { in_spam = 0; in_ham = 20 }
  |> Map.add "analog" { in_spam = 0; in_ham = 5 }
  |> Map.add "and" { in_spam = 24; in_ham = 116 }
  |> Map.add "angry" { in_spam = 0; in_ham = 7 }
  |> Map.add "announces" { in_spam = 0; in_ham = 13 }
  |> Map.add "annual" { in_spam = 0; in_ham = 5 }
  |> Map.add "anolther" { in_spam = 0; in_ham = 12 }
  |> Map.add "another" { in_spam = 0; in_ham = 8 }
  |> Map.add "apple" { in_spam = 0; in_ham = 10 }
  |> Map.add "approach" { in_spam = 1; in_ham = 7 }
  |> Map.add "apt" { in_spam = 0; in_ham = 57 }
  |> Map.add "apt-get" { in_spam = 0; in_ham = 13 }
  |> Map.add "are" { in_spam = 11; in_ham = 27 }
  |> Map.add "arrrghhh" { in_spam = 0; in_ham = 9 }
  |> Map.add "article" { in_spam = 0; in_ham = 9 }
  |> Map.add "assistance" { in_spam = 9; in_ham = 1 }
  |> Map.add "asynchronous" { in_spam = 0; in_ham = 5 }
  |> Map.add "attacks" { in_spam = 0; in_ham = 11 }
  |> Map.add "automated" { in_spam = 0; in_ham = 14 }
  |> Map.add "available" { in_spam = 5; in_ham = 7 }
  |> Map.add "avast" { in_spam = 0; in_ham = 5 }
  |> Map.add "back" { in_spam = 3; in_ham = 10 }
  |> Map.add "bad" { in_spam = 0; in_ham = 22 }
  |> Map.add "bank" { in_spam = 5; in_ham = 6 }
  |> Map.add "base" { in_spam = 2; in_ham = 12 }
  |> Map.add "based" { in_spam = 0; in_ham = 7 }
  |> Map.add "before" { in_spam = 0; in_ham = 7 }
  |> Map.add "behaviours" { in_spam = 0; in_ham = 17 }
  |> Map.add "behind" { in_spam = 2; in_ham = 6 }
  |> Map.add "best" { in_spam = 19; in_ham = 3 }
  |> Map.add "biblical" { in_spam = 0; in_ham = 5 }
  |> Map.add "big" { in_spam = 8; in_ham = 29 }
  |> Map.add "biggest" { in_spam = 0; in_ham = 7 }
  |> Map.add "bits" { in_spam = 0; in_ham = 7 }
  |> Map.add "bliss" { in_spam = 0; in_ham = 55 }
  |> Map.add "boycotting" { in_spam = 0; in_ham = 8 }
  |> Map.add "brown" { in_spam = 0; in_ham = 7 }
  |> Map.add "bucks" { in_spam = 1; in_ham = 12 }
  |> Map.add "bug" { in_spam = 0; in_ham = 43 }
  |> Map.add "build" { in_spam = 1; in_ham = 10 }
  |> Map.add "bush" { in_spam = 0; in_ham = 9 }
  |> Map.add "business" { in_spam = 7; in_ham = 7 }
  |> Map.add "but" { in_spam = 0; in_ham = 10 }
  |> Map.add "buy" { in_spam = 3; in_ham = 6 }
  |> Map.add "buys" { in_spam = 0; in_ham = 5 }
  |> Map.add "cafe" { in_spam = 0; in_ham = 5 }
  |> Map.add "call" { in_spam = 0; in_ham = 5 }
  |> Map.add "can" { in_spam = 4; in_ham = 15 }
  |> Map.add "can't" { in_spam = 0; in_ham = 12 }
  |> Map.add "canadians" { in_spam = 0; in_ham = 8 }
  |> Map.add "capitalism" { in_spam = 0; in_ham = 6 }
  |> Map.add "car" { in_spam = 0; in_ham = 8 }
  |> Map.add "card" { in_spam = 4; in_ham = 3 }
  |> Map.add "case" { in_spam = 2; in_ham = 14 }
  |> Map.add "change" { in_spam = 0; in_ham = 16 }
  |> Map.add "changed" { in_spam = 0; in_ham = 5 }
  |> Map.add "city" { in_spam = 1; in_ham = 5 }
  |> Map.add "click" { in_spam = 1; in_ham = 17 }
  |> Map.add "client" { in_spam = 0; in_ham = 6 }
  |> Map.add "cloudmark" { in_spam = 0; in_ham = 5 }
  |> Map.add "cluetrain" { in_spam = 0; in_ham = 9 }
  |> Map.add "code" { in_spam = 0; in_ham = 6 }
  |> Map.add "collision" { in_spam = 0; in_ham = 6 }
  |> Map.add "com" { in_spam = 8; in_ham = 24 }
  |> Map.add "communism" { in_spam = 0; in_ham = 5 }
  |> Map.add "companies" { in_spam = 2; in_ham = 4 }
  |> Map.add "company" { in_spam = 6; in_ham = 2 }
  |> Map.add "compile" { in_spam = 0; in_ham = 9 }
  |> Map.add "complete" { in_spam = 3; in_ham = 9 }
  |> Map.add "computer" { in_spam = 10; in_ham = 5 }
  |> Map.add "computing" { in_spam = 0; in_ham = 5 }
  |> Map.add "comrade" { in_spam = 0; in_ham = 5 }
  |> Map.add "consult" { in_spam = 0; in_ham = 5 }
  |> Map.add "content" { in_spam = 1; in_ham = 6 }
  |> Map.add "could" { in_spam = 0; in_ham = 7 }
  |> Map.add "cpx" { in_spam = 0; in_ham = 5 }
  |> Map.add "crony" { in_spam = 0; in_ham = 6 }
  |> Map.add "current" { in_spam = 0; in_ham = 12 }
  |> Map.add "curse" { in_spam = 0; in_ham = 9 }
  |> Map.add "curseen" { in_spam = 0; in_ham = 5 }
  |> Map.add "custom" { in_spam = 4; in_ham = 4 }
  |> Map.add "cvs" { in_spam = 0; in_ham = 42 }
  |> Map.add "cystals" { in_spam = 0; in_ham = 5 }
  |> Map.add "data" { in_spam = 0; in_ham = 6 }
  |> Map.add "datapower" { in_spam = 0; in_ham = 13 }
  |> Map.add "date" { in_spam = 0; in_ham = 8 }
  |> Map.add "day" { in_spam = 3; in_ham = 11 }
  |> Map.add "deal" { in_spam = 1; in_ham = 6 }
  |> Map.add "defnitions" { in_spam = 0; in_ham = 7 }
  |> Map.add "deleting" { in_spam = 0; in_ham = 5 }
  |> Map.add "dell" { in_spam = 0; in_ham = 9 }
  |> Map.add "delta" { in_spam = 0; in_ham = 11 }
  |> Map.add "dependencies" { in_spam = 0; in_ham = 7 }
  |> Map.add "deployment" { in_spam = 0; in_ham = 28 }
  |> Map.add "device" { in_spam = 0; in_ham = 5 }
  |> Map.add "digital" { in_spam = 1; in_ham = 16 }
  |> Map.add "digression" { in_spam = 0; in_ham = 5 }
  |> Map.add "display" { in_spam = 0; in_ham = 5 }
  |> Map.add "dist-upgrade" { in_spam = 0; in_ham = 5 }
  |> Map.add "distributed" { in_spam = 0; in_ham = 6 }
  |> Map.add "ditching" { in_spam = 0; in_ham = 7 }
  |> Map.add "dma" { in_spam = 0; in_ham = 17 }
  |> Map.add "dns" { in_spam = 0; in_ham = 7 }
  |> Map.add "doc" { in_spam = 0; in_ham = 6 }
  |> Map.add "doesnt" { in_spam = 0; in_ham = 9 }
  |> Map.add "domain" { in_spam = 3; in_ham = 4 }
  |> Map.add "don't" { in_spam = 5; in_ham = 5 }
  |> Map.add "drive" { in_spam = 0; in_ham = 17 }
  |> Map.add "dude" { in_spam = 0; in_ham = 5 }
  |> Map.add "dumb" { in_spam = 0; in_ham = 6 }
  |> Map.add "duplicate" { in_spam = 0; in_ham = 5 }
  |> Map.add "dvd" { in_spam = 2; in_ham = 27 }
  |> Map.add "dylsexics" { in_spam = 0; in_ham = 8 }
  |> Map.add "earthviewer" { in_spam = 0; in_ham = 6 }
  |> Map.add "easy" { in_spam = 2; in_ham = 26 }
  |> Map.add "ebay" { in_spam = 7; in_ham = 3 }
  |> Map.add "ebusiness" { in_spam = 0; in_ham = 9 }
  |> Map.add "edsel" { in_spam = 0; in_ham = 7 }
  |> Map.add "electric" { in_spam = 0; in_ham = 8 }
  |> Map.add "else" { in_spam = 0; in_ham = 7 }
  |> Map.add "email" { in_spam = 5; in_ham = 13 }
  |> Map.add "empire" { in_spam = 0; in_ham = 26 }
  |> Map.add "error" { in_spam = 1; in_ham = 12 }
  |> Map.add "errors" { in_spam = 0; in_ham = 8 }
  |> Map.add "europe" { in_spam = 0; in_ham = 5 }
  |> Map.add "example" { in_spam = 4; in_ham = 3 }
  |> Map.add "exmh" { in_spam = 0; in_ham = 26 }
  |> Map.add "fails" { in_spam = 0; in_ham = 6 }
  |> Map.add "false" { in_spam = 0; in_ham = 20 }
  |> Map.add "file" { in_spam = 0; in_ham = 17 }
  |> Map.add "files" { in_spam = 0; in_ham = 5 }
  |> Map.add "finally" { in_spam = 0; in_ham = 11 }
  |> Map.add "finance" { in_spam = 0; in_ham = 5 }
  |> Map.add "find" { in_spam = 5; in_ham = 14 }
  |> Map.add "firewall" { in_spam = 0; in_ham = 5 }
  |> Map.add "first" { in_spam = 2; in_ham = 25 }
  |> Map.add "flavor" { in_spam = 0; in_ham = 5 }
  |> Map.add "focus" { in_spam = 1; in_ham = 17 }
  |> Map.add "for" { in_spam = 49; in_ham = 296 }
  |> Map.add "forteana" { in_spam = 0; in_ham = 5 }
  |> Map.add "forum" { in_spam = 1; in_ham = 5 }
  |> Map.add "free" { in_spam = 30; in_ham = 11 }
  |> Map.add "freetype" { in_spam = 0; in_ham = 7 }
  |> Map.add "freshrpms" { in_spam = 0; in_ham = 7 }
  |> Map.add "friends" { in_spam = 0; in_ham = 13 }
  |> Map.add "from" { in_spam = 10; in_ham = 68 }
  |> Map.add "funny" { in_spam = 0; in_ham = 8 }
  |> Map.add "fwd" { in_spam = 4; in_ham = 30 }
  |> Map.add "game" { in_spam = 2; in_ham = 5 }
  |> Map.add "gasp" { in_spam = 0; in_ham = 7 }
  |> Map.add "gbayes" { in_spam = 0; in_ham = 5 }
  |> Map.add "gdc" { in_spam = 0; in_ham = 6 }
  |> Map.add "gecko" { in_spam = 0; in_ham = 5 }
  |> Map.add "get" { in_spam = 19; in_ham = 13 }
  |> Map.add "gets" { in_spam = 2; in_ham = 19 }
  |> Map.add "getting" { in_spam = 0; in_ham = 11 }
  |> Map.add "gives" { in_spam = 0; in_ham = 7 }
  |> Map.add "giving" { in_spam = 1; in_ham = 6 }
  |> Map.add "global" { in_spam = 0; in_ham = 27 }
  |> Map.add "god" { in_spam = 0; in_ham = 16 }
  |> Map.add "goes" { in_spam = 0; in_ham = 5 }
  |> Map.add "going" { in_spam = 0; in_ham = 8 }
  |> Map.add "good" { in_spam = 0; in_ham = 15 }
  |> Map.add "goodbye" { in_spam = 0; in_ham = 26 }
  |> Map.add "google" { in_spam = 0; in_ham = 17 }
  |> Map.add "got" { in_spam = 3; in_ham = 4 }
  |> Map.add "gov" { in_spam = 0; in_ham = 14 }
  |> Map.add "government" { in_spam = 1; in_ham = 12 }
  |> Map.add "gpg" { in_spam = 0; in_ham = 9 }
  |> Map.add "great" { in_spam = 1; in_ham = 6 }
  |> Map.add "habeus" { in_spam = 0; in_ham = 20 }
  |> Map.add "had" { in_spam = 0; in_ham = 9 }
  |> Map.add "hangs" { in_spam = 0; in_ham = 5 }
  |> Map.add "hanson's" { in_spam = 0; in_ham = 21 }
  |> Map.add "has" { in_spam = 2; in_ham = 25 }
  |> Map.add "hashes" { in_spam = 0; in_ham = 6 }
  |> Map.add "hat" { in_spam = 0; in_ham = 10 }
  |> Map.add "have" { in_spam = 7; in_ham = 8 }
  |> Map.add "having" { in_spam = 0; in_ham = 5 }
  |> Map.add "headlines" { in_spam = 0; in_ham = 28 }
  |> Map.add "help" { in_spam = 5; in_ham = 13 }
  |> Map.add "here" { in_spam = 12; in_ham = 5 }
  |> Map.add "high" { in_spam = 1; in_ham = 14 }
  |> Map.add "his" { in_spam = 1; in_ham = 21 }
  |> Map.add "histograms" { in_spam = 0; in_ham = 8 }
  |> Map.add "hit" { in_spam = 5; in_ham = 3 }
  |> Map.add "home" { in_spam = 15; in_ham = 8 }
  |> Map.add "homemade" { in_spam = 0; in_ham = 7 }
  |> Map.add "honor" { in_spam = 0; in_ham = 6 }
  |> Map.add "horse" { in_spam = 0; in_ham = 6 }
  |> Map.add "hottest" { in_spam = 1; in_ham = 12 }
  |> Map.add "how" { in_spam = 4; in_ham = 19 }
  |> Map.add "html" { in_spam = 0; in_ham = 5 }
  |> Map.add "http" { in_spam = 1; in_ham = 14 }
  |> Map.add "human" { in_spam = 1; in_ham = 6 }
  |> Map.add "hyperion" { in_spam = 0; in_ham = 5 }
  |> Map.add "i'm" { in_spam = 1; in_ham = 9 }
  |> Map.add "i've" { in_spam = 0; in_ham = 8 }
  |> Map.add "ide" { in_spam = 1; in_ham = 5 }
  |> Map.add "idea" { in_spam = 0; in_ham = 6 }
  |> Map.add "identity" { in_spam = 0; in_ham = 5 }
  |> Map.add "ilug" { in_spam = 34; in_ham = 92 }
  |> Map.add "ilug-social" { in_spam = 14; in_ham = 0 }
  |> Map.add "image" { in_spam = 1; in_ham = 22 }
  |> Map.add "india's" { in_spam = 0; in_ham = 10 }
  |> Map.add "information" { in_spam = 6; in_ham = 5 }
  |> Map.add "insert" { in_spam = 0; in_ham = 9 }
  |> Map.add "install" { in_spam = 0; in_ham = 9 }
  |> Map.add "insurance" { in_spam = 12; in_ham = 0 }
  |> Map.add "interesting" { in_spam = 0; in_ham = 9 }
  |> Map.add "internet" { in_spam = 7; in_ham = 12 }
  |> Map.add "into" { in_spam = 0; in_ham = 10 }
  |> Map.add "iraq" { in_spam = 1; in_ham = 7 }
  |> Map.add "irr" { in_spam = 0; in_ham = 5 }
  |> Map.add "it's" { in_spam = 0; in_ham = 8 }
  |> Map.add "java" { in_spam = 0; in_ham = 35 }
  |> Map.add "job" { in_spam = 1; in_ham = 5 }
  |> Map.add "jump" { in_spam = 0; in_ham = 9 }
  |> Map.add "just" { in_spam = 4; in_ham = 10 }
  |> Map.add "kernel" { in_spam = 0; in_ham = 8 }
  |> Map.add "kernels" { in_spam = 0; in_ham = 7 }
  |> Map.add "key" { in_spam = 0; in_ham = 16 }
  |> Map.add "kiddies" { in_spam = 0; in_ham = 35 }
  |> Map.add "kill" { in_spam = 0; in_ham = 6 }
  |> Map.add "laptop" { in_spam = 1; in_ham = 8 }
  |> Map.add "last" { in_spam = 3; in_ham = 8 }
  |> Map.add "latest" { in_spam = 0; in_ham = 6 }
  |> Map.add "latitude" { in_spam = 0; in_ham = 5 }
  |> Map.add "left" { in_spam = 0; in_ham = 10 }
  |> Map.add "liberal" { in_spam = 0; in_ham = 9 }
  |> Map.add "life" { in_spam = 10; in_ham = 10 }
  |> Map.add "lifegem" { in_spam = 0; in_ham = 6 }
  |> Map.add "like" { in_spam = 1; in_ham = 9 }
  |> Map.add "lineup" { in_spam = 0; in_ham = 7 }
  |> Map.add "linking" { in_spam = 0; in_ham = 7 }
  |> Map.add "linux" { in_spam = 0; in_ham = 18 }
  |> Map.add "list" { in_spam = 0; in_ham = 7 }
  |> Map.add "lists" { in_spam = 0; in_ham = 6 }
  |> Map.add "location" { in_spam = 0; in_ham = 6 }
  |> Map.add "log" { in_spam = 0; in_ham = 8 }
  |> Map.add "looking" { in_spam = 2; in_ham = 7 }
  |> Map.add "lost" { in_spam = 0; in_ham = 6 }
  |> Map.add "low" { in_spam = 13; in_ham = 14 }
  |> Map.add "mac" { in_spam = 0; in_ham = 8 }
  |> Map.add "machine" { in_spam = 0; in_ham = 6 }
  |> Map.add "made" { in_spam = 0; in_ham = 26 }
  |> Map.add "mail" { in_spam = 0; in_ham = 18 }
  |> Map.add "make" { in_spam = 9; in_ham = 3 }
  |> Map.add "makes" { in_spam = 1; in_ham = 6 }
  |> Map.add "man" { in_spam = 1; in_ham = 24 }
  |> Map.add "management" { in_spam = 1; in_ham = 7 }
  |> Map.add "mark" { in_spam = 0; in_ham = 8 }
  |> Map.add "mass-check" { in_spam = 0; in_ham = 7 }
  |> Map.add "masses" { in_spam = 0; in_ham = 5 }
  |> Map.add "matey" { in_spam = 0; in_ham = 5 }
  |> Map.add "matter" { in_spam = 0; in_ham = 6 }
  |> Map.add "may" { in_spam = 2; in_ham = 7 }
  |> Map.add "maybe" { in_spam = 1; in_ham = 6 }
  |> Map.add "meet" { in_spam = 1; in_ham = 13 }
  |> Map.add "meetings" { in_spam = 0; in_ham = 12 }
  |> Map.add "men" { in_spam = 0; in_ham = 6 }
  |> Map.add "message" { in_spam = 1; in_ham = 40 }
  |> Map.add "microsoft" { in_spam = 0; in_ham = 6 }
  |> Map.add "modem" { in_spam = 0; in_ham = 6 }
  |> Map.add "moment" { in_spam = 1; in_ham = 20 }
  |> Map.add "money" { in_spam = 16; in_ham = 0 }
  |> Map.add "month" { in_spam = 7; in_ham = 3 }
  |> Map.add "more" { in_spam = 3; in_ham = 13 }
  |> Map.add "mortgage" { in_spam = 10; in_ham = 0 }
  |> Map.add "mplayer" { in_spam = 0; in_ham = 15 }
  |> Map.add "music" { in_spam = 0; in_ham = 5 }
  |> Map.add "name" { in_spam = 1; in_ham = 15 }
  |> Map.add "national" { in_spam = 0; in_ham = 22 }
  |> Map.add "need" { in_spam = 12; in_ham = 1 }
  |> Map.add "negative" { in_spam = 0; in_ham = 13 }
  |> Map.add "nessus" { in_spam = 0; in_ham = 6 }
  |> Map.add "net" { in_spam = 2; in_ham = 27 }
  |> Map.add "new" { in_spam = 13; in_ham = 103 }
  |> Map.add "newbie" { in_spam = 0; in_ham = 8 }
  |> Map.add "news" { in_spam = 5; in_ham = 17 }
  |> Map.add "next" { in_spam = 1; in_ham = 7 }
  |> Map.add "nixia" { in_spam = 0; in_ham = 10 }
  |> Map.add "nobel" { in_spam = 0; in_ham = 11 }
  |> Map.add "normal" { in_spam = 0; in_ham = 5 }
  |> Map.add "not" { in_spam = 3; in_ham = 35 }
  |> Map.add "notes" { in_spam = 0; in_ham = 5 }
  |> Map.add "now" { in_spam = 12; in_ham = 14 }
  |> Map.add "null" { in_spam = 0; in_ham = 20 }
  |> Map.add "off" { in_spam = 2; in_ham = 4 }
  |> Map.add "old" { in_spam = 1; in_ham = 6 }
  |> Map.add "one" { in_spam = 10; in_ham = 9 }
  |> Map.add "online" { in_spam = 9; in_ham = 8 }
  |> Map.add "only" { in_spam = 9; in_ham = 2 }
  |> Map.add "optical" { in_spam = 0; in_ham = 5 }
  |> Map.add "org" { in_spam = 3; in_ham = 4 }
  |> Map.add "osxcon" { in_spam = 0; in_ham = 6 }
  |> Map.add "other" { in_spam = 3; in_ham = 9 }
  |> Map.add "ouch" { in_spam = 0; in_ham = 71 }
  |> Map.add "our" { in_spam = 0; in_ham = 23 }
  |> Map.add "out" { in_spam = 3; in_ham = 17 }
  |> Map.add "over" { in_spam = 3; in_ham = 9 }
  |> Map.add "own" { in_spam = 3; in_ham = 9 }
  |> Map.add "package" { in_spam = 1; in_ham = 15 }
  |> Map.add "packages" { in_spam = 0; in_ham = 12 }
  |> Map.add "palestinians" { in_spam = 0; in_ham = 10 }
  |> Map.add "patch" { in_spam = 1; in_ham = 12 }
  |> Map.add "patent" { in_spam = 0; in_ham = 8 }
  |> Map.add "pay" { in_spam = 3; in_ham = 4 }
  |> Map.add "people" { in_spam = 2; in_ham = 5 }
  |> Map.add "perl" { in_spam = 0; in_ham = 60 }
  |> Map.add "personals" { in_spam = 0; in_ham = 11 }
  |> Map.add "photoshop" { in_spam = 0; in_ham = 6 }
  |> Map.add "pirates" { in_spam = 0; in_ham = 15 }
  |> Map.add "place" { in_spam = 1; in_ham = 13 }
  |> Map.add "planet" { in_spam = 0; in_ham = 5 }
  |> Map.add "plans" { in_spam = 3; in_ham = 4 }
  |> Map.add "play" { in_spam = 4; in_ham = 8 }
  |> Map.add "player" { in_spam = 0; in_ham = 8 }
  |> Map.add "please" { in_spam = 7; in_ham = 11 }
  |> Map.add "police" { in_spam = 1; in_ham = 5 }
  |> Map.add "pop" { in_spam = 0; in_ham = 7 }
  |> Map.add "positive" { in_spam = 0; in_ham = 7 }
  |> Map.add "price" { in_spam = 6; in_ham = 2 }
  |> Map.add "prize" { in_spam = 0; in_ham = 6 }
  |> Map.add "problem" { in_spam = 0; in_ham = 45 }
  |> Map.add "problems" { in_spam = 1; in_ham = 23 }
  |> Map.add "process" { in_spam = 0; in_ham = 7 }
  |> Map.add "public" { in_spam = 0; in_ham = 6 }
  |> Map.add "put" { in_spam = 2; in_ham = 4 }
  |> Map.add "puts" { in_spam = 0; in_ham = 6 }
  |> Map.add "python" { in_spam = 0; in_ham = 7 }
  |> Map.add "query" { in_spam = 0; in_ham = 6 }
  |> Map.add "question" { in_spam = 0; in_ham = 13 }
  |> Map.add "questions" { in_spam = 0; in_ham = 5 }
  |> Map.add "quick" { in_spam = 1; in_ham = 6 }
  |> Map.add "radio" { in_spam = 0; in_ham = 8 }
  |> Map.add "rate" { in_spam = 3; in_ham = 14 }
  |> Map.add "rates" { in_spam = 18; in_ham = 0 }
  |> Map.add "razor" { in_spam = 0; in_ham = 52 }
  |> Map.add "razor-users" { in_spam = 0; in_ham = 89 }
  |> Map.add "read" { in_spam = 1; in_ham = 7 }
  |> Map.add "ready" { in_spam = 2; in_ham = 8 }
  |> Map.add "real" { in_spam = 2; in_ham = 7 }
  |> Map.add "rebuild" { in_spam = 0; in_ham = 6 }
  |> Map.add "recommended" { in_spam = 0; in_ham = 13 }
  |> Map.add "record" { in_spam = 0; in_ham = 6 }
  |> Map.add "recovery" { in_spam = 0; in_ham = 11 }
  |> Map.add "red" { in_spam = 0; in_ham = 10 }
  |> Map.add "redhat" { in_spam = 0; in_ham = 12 }
  |> Map.add "related" { in_spam = 0; in_ham = 12 }
  |> Map.add "release" { in_spam = 1; in_ham = 20 }
  |> Map.add "released" { in_spam = 0; in_ham = 8 }
  |> Map.add "report" { in_spam = 1; in_ham = 20 }
  |> Map.add "reports" { in_spam = 0; in_ham = 5 }
  |> Map.add "results" { in_spam = 1; in_ham = 9 }
  |> Map.add "review" { in_spam = 0; in_ham = 25 }
  |> Map.add "risks" { in_spam = 0; in_ham = 5 }
  |> Map.add "roman" { in_spam = 0; in_ham = 27 }
  |> Map.add "rpm" { in_spam = 0; in_ham = 14 }
  |> Map.add "rpms" { in_spam = 0; in_ham = 5 }
  |> Map.add "rss" { in_spam = 0; in_ham = 10 }
  |> Map.add "rule" { in_spam = 0; in_ham = 5 }
  |> Map.add "rules" { in_spam = 0; in_ham = 8 }
  |> Map.add "sacvs" { in_spam = 0; in_ham = 18 }
  |> Map.add "sadev" { in_spam = 0; in_ham = 73 }
  |> Map.add "sale" { in_spam = 10; in_ham = 0 }
  |> Map.add "satalk" { in_spam = 1; in_ham = 138 }
  |> Map.add "sauced" { in_spam = 0; in_ham = 6 }
  |> Map.add "save" { in_spam = 7; in_ham = 5 }
  |> Map.add "scoop" { in_spam = 3; in_ham = 9 }
  |> Map.add "secure" { in_spam = 0; in_ham = 19 }
  |> Map.add "sed" { in_spam = 0; in_ham = 26 }
  |> Map.add "see" { in_spam = 2; in_ham = 4 }
  |> Map.add "seeks" { in_spam = 0; in_ham = 5 }
  |> Map.add "selling" { in_spam = 0; in_ham = 54 }
  |> Map.add "sendmail" { in_spam = 0; in_ham = 7 }
  |> Map.add "sept" { in_spam = 0; in_ham = 21 }
  |> Map.add "sequence" { in_spam = 0; in_ham = 12 }
  |> Map.add "sequences" { in_spam = 0; in_ham = 26 }
  |> Map.add "servants" { in_spam = 0; in_ham = 10 }
  |> Map.add "set" { in_spam = 0; in_ham = 7 }
  |> Map.add "sets" { in_spam = 0; in_ham = 30 }
  |> Map.add "should" { in_spam = 0; in_ham = 5 }
  |> Map.add "signature" { in_spam = 0; in_ham = 9 }
  |> Map.add "silence" { in_spam = 0; in_ham = 20 }
  |> Map.add "site" { in_spam = 2; in_ham = 9 }
  |> Map.add "slaughter" { in_spam = 0; in_ham = 15 }
  |> Map.add "slow" { in_spam = 0; in_ham = 6 }
  |> Map.add "socialism" { in_spam = 0; in_ham = 9 }
  |> Map.add "software" { in_spam = 7; in_ham = 13 }
  |> Map.add "sofware" { in_spam = 0; in_ham = 14 }
  |> Map.add "solaris" { in_spam = 0; in_ham = 7 }
  |> Map.add "some" { in_spam = 0; in_ham = 10 }
  |> Map.add "something" { in_spam = 1; in_ham = 12 }
  |> Map.add "sorting" { in_spam = 0; in_ham = 23 }
  |> Map.add "sourceforge" { in_spam = 0; in_ham = 5 }
  |> Map.add "spam" { in_spam = 2; in_ham = 48 }
  |> Map.add "spamassassin" { in_spam = 0; in_ham = 57 }
  |> Map.add "spambayes" { in_spam = 0; in_ham = 143 }
  |> Map.add "spamd" { in_spam = 0; in_ham = 7 }
  |> Map.add "spec" { in_spam = 0; in_ham = 10 }
  |> Map.add "speed" { in_spam = 1; in_ham = 10 }
  |> Map.add "src" { in_spam = 0; in_ham = 10 }
  |> Map.add "states" { in_spam = 0; in_ham = 26 }
  |> Map.add "station" { in_spam = 0; in_ham = 11 }
  |> Map.add "status" { in_spam = 3; in_ham = 7 }
  |> Map.add "still" { in_spam = 1; in_ham = 11 }
  |> Map.add "storage" { in_spam = 0; in_ham = 7 }
  |> Map.add "stories" { in_spam = 0; in_ham = 29 }
  |> Map.add "strong" { in_spam = 0; in_ham = 5 }
  |> Map.add "stupid" { in_spam = 0; in_ham = 7 }
  |> Map.add "subject" { in_spam = 469; in_ham = 2537 }
  |> Map.add "sun" { in_spam = 0; in_ham = 10 }
  |> Map.add "support" { in_spam = 3; in_ham = 6 }
  |> Map.add "sussed" { in_spam = 0; in_ham = 5 }
  |> Map.add "symbol" { in_spam = 0; in_ham = 5 }
  |> Map.add "system" { in_spam = 1; in_ham = 17 }
  |> Map.add "systemworks" { in_spam = 12; in_ham = 0 }
  |> Map.add "take" { in_spam = 3; in_ham = 5 }
  |> Map.add "test" { in_spam = 0; in_ham = 38 }
  |> Map.add "testing" { in_spam = 1; in_ham = 21 }
  |> Map.add "tests" { in_spam = 0; in_ham = 5 }
  |> Map.add "that" { in_spam = 0; in_ham = 23 }
  |> Map.add "the" { in_spam = 53; in_ham = 371 }
  |> Map.add "their" { in_spam = 0; in_ham = 7 }
  |> Map.add "there" { in_spam = 0; in_ham = 10 }
  |> Map.add "thing" { in_spam = 0; in_ham = 7 }
  |> Map.add "this" { in_spam = 9; in_ham = 21 }
  |> Map.add "time" { in_spam = 8; in_ham = 7 }
  |> Map.add "times" { in_spam = 0; in_ham = 6 }
  |> Map.add "tiny" { in_spam = 0; in_ham = 5 }
  |> Map.add "tip" { in_spam = 0; in_ham = 12 }
  |> Map.add "tmda-like" { in_spam = 0; in_ham = 6 }
  |> Map.add "toddlers" { in_spam = 0; in_ham = 8 }
  |> Map.add "too" { in_spam = 3; in_ham = 11 }
  |> Map.add "tough" { in_spam = 0; in_ham = 15 }
  |> Map.add "traceback" { in_spam = 0; in_ham = 19 }
  |> Map.add "training" { in_spam = 0; in_ham = 8 }
  |> Map.add "trial" { in_spam = 4; in_ham = 3 }
  |> Map.add "trying" { in_spam = 0; in_ham = 5 }
  |> Map.add "tweak" { in_spam = 0; in_ham = 7 }
  |> Map.add "two" { in_spam = 0; in_ham = 6 }
  |> Map.add "ultimate" { in_spam = 0; in_ham = 7 }
  |> Map.add "undeclared" { in_spam = 0; in_ham = 5 }
  |> Map.add "united" { in_spam = 0; in_ham = 26 }
  |> Map.add "untie" { in_spam = 0; in_ham = 8 }
  |> Map.add "update" { in_spam = 0; in_ham = 5 }
  |> Map.add "updates" { in_spam = 0; in_ham = 8 }
  |> Map.add "upgrade" { in_spam = 0; in_ham = 18 }
  |> Map.add "urgent" { in_spam = 8; in_ham = 2 }
  |> Map.add "usb" { in_spam = 0; in_ham = 5 }
  |> Map.add "use" { in_spam = 2; in_ham = 88 }
  |> Map.add "users" { in_spam = 0; in_ham = 18 }
  |> Map.add "using" { in_spam = 0; in_ham = 8 }
  |> Map.add "viewing" { in_spam = 0; in_ham = 14 }
  |> Map.add "virus" { in_spam = 3; in_ham = 4 }
  |> Map.add "void" { in_spam = 0; in_ham = 11 }
  |> Map.add "warming" { in_spam = 0; in_ham = 25 }
  |> Map.add "was" { in_spam = 1; in_ham = 108 }
  |> Map.add "web" { in_spam = 2; in_ham = 11 }
  |> Map.add "webforms" { in_spam = 0; in_ham = 9 }
  |> Map.add "wedded" { in_spam = 0; in_ham = 54 }
  |> Map.add "weekly's" { in_spam = 0; in_ham = 7 }
  |> Map.add "west" { in_spam = 0; in_ham = 5 }
  |> Map.add "what" { in_spam = 7; in_ham = 4 }
  |> Map.add "when" { in_spam = 0; in_ham = 6 }
  |> Map.add "where" { in_spam = 2; in_ham = 6 }
  |> Map.add "which" { in_spam = 0; in_ham = 5 }
  |> Map.add "whitelist" { in_spam = 0; in_ham = 6 }
  |> Map.add "who" { in_spam = 0; in_ham = 5 }
  |> Map.add "whoa" { in_spam = 0; in_ham = 11 }
  |> Map.add "why" { in_spam = 2; in_ham = 25 }
  |> Map.add "wifi" { in_spam = 0; in_ham = 11 }
  |> Map.add "will" { in_spam = 9; in_ham = 5 }
  |> Map.add "win" { in_spam = 2; in_ham = 7 }
  |> Map.add "window" { in_spam = 0; in_ham = 34 }
  |> Map.add "wireless" { in_spam = 0; in_ham = 6 }
  |> Map.add "with" { in_spam = 17; in_ham = 115 }
  |> Map.add "women" { in_spam = 0; in_ham = 13 }
  |> Map.add "word" { in_spam = 0; in_ham = 6 }
  |> Map.add "wordinfo" { in_spam = 0; in_ham = 7 }
  |> Map.add "work" { in_spam = 6; in_ham = 7 }
  |> Map.add "working" { in_spam = 3; in_ham = 22 }
  |> Map.add "world" { in_spam = 1; in_ham = 10 }
  |> Map.add "write" { in_spam = 1; in_ham = 5 }
  |> Map.add "wrold" { in_spam = 0; in_ham = 8 }
  |> Map.add "wrong" { in_spam = 0; in_ham = 7 }
  |> Map.add "xine" { in_spam = 0; in_ham = 12 }
  |> Map.add "yahoo" { in_spam = 0; in_ham = 12 }
  |> Map.add "year" { in_spam = 11; in_ham = 2 }
  |> Map.add "years" { in_spam = 3; in_ham = 4 }
  |> Map.add "you" { in_spam = 46; in_ham = 25 }
  |> Map.add "your" { in_spam = 70; in_ham = 15 }
  |> Map.add "zzzz" { in_spam = 13; in_ham = 0 }
  |> Map.add "zzzzteana" { in_spam = 0; in_ham = 87 }
