open Bayesian.Database
open BayesianBody_005
let db = db 
|> Map.add "guest" { in_spam=2; in_ham=2}
|> Map.add "gui" { in_spam=0; in_ham=8}
|> Map.add "guide" { in_spam=20; in_ham=8}
|> Map.add "guided" { in_spam=0; in_ham=7}
|> Map.add "guidelines" { in_spam=12; in_ham=4}
|> Map.add "guides" { in_spam=4; in_ham=6}
|> Map.add "guido" { in_spam=0; in_ham=46}
|> Map.add "guilty" { in_spam=1; in_ham=6}
|> Map.add "gulf" { in_spam=0; in_ham=10}
|> Map.add "gun" { in_spam=5; in_ham=8}
|> Map.add "guns" { in_spam=2; in_ham=5}
|> Map.add "gurus" { in_spam=4; in_ham=1}
|> Map.add "guts" { in_spam=0; in_ham=4}
|> Map.add "guy" { in_spam=3; in_ham=48}
|> Map.add "guys" { in_spam=5; in_ham=62}
|> Map.add "gvim" { in_spam=0; in_ham=7}
|> Map.add "gward" { in_spam=0; in_ham=8}
|> Map.add "gzipped" { in_spam=0; in_ham=3}
|> Map.add "haa" { in_spam=0; in_ham=11}
|> Map.add "haase" { in_spam=0; in_ham=4}
|> Map.add "haataja" { in_spam=0; in_ham=6}
|> Map.add "habeas" { in_spam=0; in_ham=17}
|> Map.add "habeas's" { in_spam=0; in_ham=3}
|> Map.add "habeus" { in_spam=0; in_ham=8}
|> Map.add "habit" { in_spam=2; in_ham=2}
|> Map.add "habitrail" { in_spam=0; in_ham=3}
|> Map.add "habits" { in_spam=0; in_ham=7}
|> Map.add "hack" { in_spam=0; in_ham=24}
|> Map.add "hacked" { in_spam=0; in_ham=5}
|> Map.add "hackedbox" { in_spam=0; in_ham=4}
|> Map.add "hacker" { in_spam=0; in_ham=7}
|> Map.add "hackers" { in_spam=11; in_ham=6}
|> Map.add "hacking" { in_spam=0; in_ham=15}
|> Map.add "hackish" { in_spam=0; in_ham=4}
|> Map.add "hacks" { in_spam=0; in_ham=5}
|> Map.add "hacksaw" { in_spam=0; in_ham=5}
|> Map.add "had" { in_spam=36; in_ham=356}
|> Map.add "had-" { in_spam=0; in_ham=5}
|> Map.add "hadn't" { in_spam=0; in_ham=26}
|> Map.add "hadrly" { in_spam=0; in_ham=3}
|> Map.add "haha" { in_spam=0; in_ham=3}
|> Map.add "haiku" { in_spam=0; in_ham=13}
|> Map.add "hail" { in_spam=0; in_ham=3}
|> Map.add "hair" { in_spam=5; in_ham=16}
|> Map.add "hal" { in_spam=0; in_ham=29}
|> Map.add "haldevore" { in_spam=0; in_ham=7}
|> Map.add "half" { in_spam=10; in_ham=91}
|> Map.add "halfway" { in_spam=0; in_ham=5}
|> Map.add "hall" { in_spam=1; in_ham=40}
|> Map.add "hallgrimsson" { in_spam=0; in_ham=12}
|> Map.add "hallikainen" { in_spam=0; in_ham=3}
|> Map.add "hallmark" { in_spam=0; in_ham=4}
|> Map.add "hallway" { in_spam=0; in_ham=4}
|> Map.add "halt" { in_spam=0; in_ham=5}
|> Map.add "ham" { in_spam=2; in_ham=57}
|> Map.add "ham'" { in_spam=0; in_ham=3}
|> Map.add "hamilton" { in_spam=0; in_ham=9}
|> Map.add "hammer" { in_spam=1; in_ham=5}
|> Map.add "hammersley" { in_spam=0; in_ham=4}
|> Map.add "hammie" { in_spam=0; in_ham=14}
|> Map.add "hampshire" { in_spam=3; in_ham=1}
|> Map.add "hams" { in_spam=0; in_ham=8}
|> Map.add "hamza's" { in_spam=0; in_ham=3}
|> Map.add "hand" { in_spam=13; in_ham=83}
|> Map.add "handed" { in_spam=2; in_ham=7}
|> Map.add "handful" { in_spam=0; in_ham=8}
|> Map.add "handing" { in_spam=0; in_ham=5}
|> Map.add "handle" { in_spam=4; in_ham=38}
|> Map.add "handled" { in_spam=4; in_ham=11}
|> Map.add "handler" { in_spam=0; in_ham=4}
|> Map.add "handles" { in_spam=0; in_ham=4}
|> Map.add "handling" { in_spam=9; in_ham=21}
|> Map.add "hands" { in_spam=9; in_ham=33}
|> Map.add "handshake" { in_spam=0; in_ham=7}
|> Map.add "handy" { in_spam=1; in_ham=12}
|> Map.add "hang" { in_spam=0; in_ham=10}
|> Map.add "hanging" { in_spam=2; in_ham=11}
|> Map.add "happen" { in_spam=23; in_ham=62}
|> Map.add "happened" { in_spam=9; in_ham=67}
|> Map.add "happening" { in_spam=1; in_ham=14}
|> Map.add "happens" { in_spam=11; in_ham=38}
|> Map.add "happily" { in_spam=2; in_ham=7}
|> Map.add "happiness" { in_spam=3; in_ham=4}
|> Map.add "happy" { in_spam=19; in_ham=71}
|> Map.add "harassement" { in_spam=0; in_ham=3}
|> Map.add "harbor" { in_spam=2; in_ham=6}
|> Map.add "hard" { in_spam=21; in_ham=94}
|> Map.add "hardcoded" { in_spam=0; in_ham=4}
|> Map.add "hardcore" { in_spam=6; in_ham=0}
|> Map.add "harder" { in_spam=2; in_ham=25}
|> Map.add "hardest" { in_spam=0; in_ham=3}
|> Map.add "hardly" { in_spam=2; in_ham=12}
|> Map.add "hardware" { in_spam=2; in_ham=57}
|> Map.add "hardwired" { in_spam=0; in_ham=5}
|> Map.add "hare" { in_spam=2; in_ham=2}
|> Map.add "harem" { in_spam=0; in_ham=4}
|> Map.add "harley" { in_spam=0; in_ham=35}
|> Map.add "harm" { in_spam=1; in_ham=10}
|> Map.add "harmful" { in_spam=1; in_ham=5}
|> Map.add "harmless" { in_spam=0; in_ham=3}
|> Map.add "harmony" { in_spam=1; in_ham=2}
|> Map.add "harness" { in_spam=0; in_ham=4}
|> Map.add "harold" { in_spam=0; in_ham=5}
|> Map.add "harper's" { in_spam=0; in_ham=3}
|> Map.add "harri" { in_spam=0; in_ham=12}
|> Map.add "harsh" { in_spam=0; in_ham=3}
|> Map.add "harvard" { in_spam=0; in_ham=8}
|> Map.add "harvest" { in_spam=2; in_ham=2}
|> Map.add "harvesting" { in_spam=2; in_ham=2}
|> Map.add "harvey" { in_spam=0; in_ham=5}
|> Map.add "has" { in_spam=115; in_ham=703}
|> Map.add "has-" { in_spam=0; in_ham=3}
|> Map.add "hash" { in_spam=2; in_ham=26}
|> Map.add "hasn't" { in_spam=0; in_ham=35}
|> Map.add "hassle" { in_spam=0; in_ham=4}
|> Map.add "hassles" { in_spam=2; in_ham=8}
|> Map.add "hat" { in_spam=3; in_ham=103}
|> Map.add "hat's" { in_spam=0; in_ham=7}
|> Map.add "hate" { in_spam=0; in_ham=24}
|> Map.add "hated" { in_spam=1; in_ham=3}
|> Map.add "hates" { in_spam=0; in_ham=4}
|> Map.add "hatred" { in_spam=0; in_ham=8}
|> Map.add "haun" { in_spam=0; in_ham=8}
|> Map.add "have" { in_spam=250; in_ham=1167}
|> Map.add "have-" { in_spam=0; in_ham=3}
|> Map.add "haven't" { in_spam=4; in_ham=85}
|> Map.add "havent" { in_spam=0; in_ham=4}
|> Map.add "having" { in_spam=25; in_ham=150}
|> Map.add "havoc" { in_spam=0; in_ham=7}
|> Map.add "hawaii" { in_spam=5; in_ham=3}
|> Map.add "hawks" { in_spam=0; in_ham=3}
|> Map.add "hay" { in_spam=2; in_ham=2}
|> Map.add "hazard" { in_spam=0; in_ham=5}
|> Map.add "hazardous" { in_spam=15; in_ham=0}
|> Map.add "hazards" { in_spam=0; in_ham=3}
|> Map.add "hbs" { in_spam=3; in_ham=1}
|> Map.add "hda" { in_spam=1; in_ham=2}
|> Map.add "hdc" { in_spam=0; in_ham=3}
|> Map.add "hdi" { in_spam=0; in_ham=3}
|> Map.add "hdparm" { in_spam=0; in_ham=3}
|> Map.add "hdr" { in_spam=0; in_ham=3}
|> Map.add "he'd" { in_spam=0; in_ham=10}
|> Map.add "he'll" { in_spam=0; in_ham=3}
|> Map.add "he's" { in_spam=0; in_ham=45}
|> Map.add "head" { in_spam=189; in_ham=60}
|> Map.add "headaches" { in_spam=1; in_ham=2}
|> Map.add "headed" { in_spam=3; in_ham=7}
|> Map.add "header" { in_spam=6; in_ham=55}
|> Map.add "headers" { in_spam=0; in_ham=75}
|> Map.add "heading" { in_spam=2; in_ham=4}
|> Map.add "headline" { in_spam=4; in_ham=35}
|> Map.add "headlines" { in_spam=6; in_ham=7}
|> Map.add "headquarters" { in_spam=0; in_ham=8}
|> Map.add "heads" { in_spam=0; in_ham=8}
|> Map.add "health" { in_spam=23; in_ham=23}
|> Map.add "healthcare" { in_spam=1; in_ham=6}
|> Map.add "healthy" { in_spam=2; in_ham=12}
|> Map.add "heap" { in_spam=0; in_ham=3}
|> Map.add "hear" { in_spam=10; in_ham=36}
|> Map.add "heard" { in_spam=16; in_ham=65}
|> Map.add "hearing" { in_spam=12; in_ham=21}
|> Map.add "hearings" { in_spam=0; in_ham=7}
|> Map.add "hears" { in_spam=0; in_ham=4}
|> Map.add "heart" { in_spam=5; in_ham=22}
|> Map.add "hearts" { in_spam=0; in_ham=4}
|> Map.add "heat" { in_spam=1; in_ham=9}
|> Map.add "heather" { in_spam=0; in_ham=13}
|> Map.add "heating" { in_spam=3; in_ham=2}
|> Map.add "heaven" { in_spam=3; in_ham=111}
|> Map.add "heavily" { in_spam=0; in_ham=10}
|> Map.add "heavy" { in_spam=7; in_ham=15}
|> Map.add "hebrew" { in_spam=0; in_ham=4}
|> Map.add "heck" { in_spam=6; in_ham=13}
|> Map.add "heckled" { in_spam=0; in_ham=3}
|> Map.add "hedland" { in_spam=7; in_ham=0}
|> Map.add "heels" { in_spam=1; in_ham=2}
|> Map.add "hefty" { in_spam=0; in_ham=4}
|> Map.add "hegemony" { in_spam=0; in_ham=3}
|> Map.add "heh" { in_spam=0; in_ham=9}
|> Map.add "height" { in_spam=142; in_ham=8}
|> Map.add "heightened" { in_spam=0; in_ham=3}
|> Map.add "held" { in_spam=16; in_ham=33}
|> Map.add "helen" { in_spam=0; in_ham=3}
|> Map.add "helium" { in_spam=0; in_ham=9}
|> Map.add "hell" { in_spam=5; in_ham=43}
|> Map.add "hello" { in_spam=9; in_ham=46}
|> Map.add "helo" { in_spam=0; in_ham=3}
|> Map.add "help" { in_spam=92; in_ham=176}
|> Map.add "helpdesk" { in_spam=2; in_ham=2}
|> Map.add "helped" { in_spam=10; in_ham=32}
|> Map.add "helpful" { in_spam=1; in_ham=21}
|> Map.add "helping" { in_spam=8; in_ham=16}
|> Map.add "helps" { in_spam=9; in_ham=35}
|> Map.add "helvetica" { in_spam=94; in_ham=0}
|> Map.add "hemenway" { in_spam=0; in_ham=4}
|> Map.add "hemisphere" { in_spam=1; in_ham=3}
|> Map.add "hence" { in_spam=17; in_ham=7}
|> Map.add "her" { in_spam=22; in_ham=99}
|> Map.add "herbal" { in_spam=7; in_ham=0}
|> Map.add "herbert" { in_spam=1; in_ham=3}
|> Map.add "herd" { in_spam=0; in_ham=3}
|> Map.add "herded" { in_spam=0; in_ham=3}
|> Map.add "here" { in_spam=264; in_ham=402}
|> Map.add "here's" { in_spam=13; in_ham=64}
|> Map.add "hereby" { in_spam=0; in_ham=3}
|> Map.add "herein" { in_spam=1; in_ham=2}
|> Map.add "heritage" { in_spam=3; in_ham=15}
|> Map.add "hernando" { in_spam=0; in_ham=3}
|> Map.add "herself" { in_spam=1; in_ham=3}
|> Map.add "hesitant" { in_spam=1; in_ham=2}
|> Map.add "hesitate" { in_spam=4; in_ham=6}
|> Map.add "hetero" { in_spam=0; in_ham=6}
|> Map.add "heterosexual" { in_spam=0; in_ham=7}
|> Map.add "hets" { in_spam=0; in_ham=8}
|> Map.add "hettinga" { in_spam=0; in_ham=64}
|> Map.add "hex" { in_spam=0; in_ham=4}
|> Map.add "hey" { in_spam=0; in_ham=33}
|> Map.add "hfb" { in_spam=2; in_ham=5}
|> Map.add "hgh" { in_spam=6; in_ham=0}
|> Map.add "hi-tech" { in_spam=5; in_ham=0}
|> Map.add "hickson" { in_spam=0; in_ham=3}
|> Map.add "hidden" { in_spam=55; in_ham=7}
|> Map.add "hidden'" { in_spam=28; in_ham=3}
|> Map.add "hide" { in_spam=3; in_ham=12}
|> Map.add "hiding" { in_spam=0; in_ham=5}
|> Map.add "hierarchy" { in_spam=0; in_ham=3}
|> Map.add "high" { in_spam=41; in_ham=106}
|> Map.add "high-bit" { in_spam=0; in_ham=3}
|> Map.add "high-fp-ing" { in_spam=0; in_ham=3}
|> Map.add "high-powered" { in_spam=0; in_ham=4}
|> Map.add "high-risk" { in_spam=5; in_ham=0}
|> Map.add "high-speed" { in_spam=0; in_ham=11}
|> Map.add "high-stakes" { in_spam=3; in_ham=1}
|> Map.add "higher" { in_spam=4; in_ham=50}
|> Map.add "highest" { in_spam=11; in_ham=16}
|> Map.add "highlight" { in_spam=0; in_ham=8}
|> Map.add "highlighted" { in_spam=0; in_ham=10}
|> Map.add "highlighting" { in_spam=0; in_ham=9}
|> Map.add "highlights" { in_spam=1; in_ham=4}
|> Map.add "highly" { in_spam=8; in_ham=21}
|> Map.add "hijacker" { in_spam=0; in_ham=6}
|> Map.add "hijacking" { in_spam=0; in_ham=4}
|> Map.add "hil" { in_spam=0; in_ham=5}
|> Map.add "hildebrand" { in_spam=0; in_ham=4}
|> Map.add "hill" { in_spam=1; in_ham=11}
|> Map.add "hills" { in_spam=1; in_ham=6}
|> Map.add "him" { in_spam=12; in_ham=82}
|> Map.add "himself" { in_spam=3; in_ham=32}
|> Map.add "hind" { in_spam=0; in_ham=3}
|> Map.add "hindu" { in_spam=0; in_ham=6}
|> Map.add "hindus" { in_spam=0; in_ham=6}
|> Map.add "hint" { in_spam=1; in_ham=14}
|> Map.add "hints" { in_spam=0; in_ham=11}
|> Map.add "hire" { in_spam=1; in_ham=10}
|> Map.add "hired" { in_spam=1; in_ham=8}
|> Map.add "hiring" { in_spam=1; in_ham=6}
|> Map.add "his" { in_spam=35; in_ham=228}
|> Map.add "historian" { in_spam=0; in_ham=3}
|> Map.add "historic" { in_spam=0; in_ham=9}
|> Map.add "historical" { in_spam=1; in_ham=17}
|> Map.add "historically" { in_spam=5; in_ham=3}
|> Map.add "history" { in_spam=4; in_ham=52}
|> Map.add "hit" { in_spam=11; in_ham=70}
|> Map.add "hitch" { in_spam=2; in_ham=4}
|> Map.add "hitherto" { in_spam=0; in_ham=3}
|> Map.add "hitler" { in_spam=0; in_ham=3}
|> Map.add "hitoff" { in_spam=0; in_ham=3}
|> Map.add "hits" { in_spam=1; in_ham=26}
|> Map.add "hitting" { in_spam=2; in_ham=17}
|> Map.add "hiukan" { in_spam=0; in_ham=4}
|> Map.add "hiv" { in_spam=1; in_ham=6}
|> Map.add "hive" { in_spam=0; in_ham=3}
|> Map.add "hixie" { in_spam=0; in_ham=4}
|> Map.add "hiya" { in_spam=0; in_ham=4}
|> Map.add "hmm" { in_spam=0; in_ham=25}
|> Map.add "hmmm" { in_spam=0; in_ham=31}
|> Map.add "hoc" { in_spam=0; in_ham=3}
|> Map.add "hodgson" { in_spam=0; in_ham=3}
|> Map.add "hoffstadler" { in_spam=0; in_ham=3}
|> Map.add "hoist" { in_spam=0; in_ham=3}
|> Map.add "hold" { in_spam=3; in_ham=48}
|> Map.add "holder" { in_spam=1; in_ham=6}
|> Map.add "holders" { in_spam=0; in_ham=5}
|> Map.add "holding" { in_spam=8; in_ham=13}
|> Map.add "holdings" { in_spam=0; in_ham=6}
|> Map.add "holdpkgs" { in_spam=0; in_ham=3}
|> Map.add "holds" { in_spam=4; in_ham=14}
|> Map.add "hole" { in_spam=0; in_ham=16}
|> Map.add "holes" { in_spam=0; in_ham=8}
|> Map.add "holiday" { in_spam=1; in_ham=6}
|> Map.add "holidays" { in_spam=2; in_ham=10}
|> Map.add "hollings" { in_spam=0; in_ham=3}
|> Map.add "hollywood" { in_spam=0; in_ham=7}
|> Map.add "hollywood's" { in_spam=0; in_ham=4}
|> Map.add "holy" { in_spam=0; in_ham=9}
|> Map.add "home" { in_spam=81; in_ham=188}
|> Map.add "homegrown" { in_spam=0; in_ham=6}
|> Map.add "homeland" { in_spam=1; in_ham=4}
|> Map.add "homemade" { in_spam=0; in_ham=3}
|> Map.add "homeowner" { in_spam=6; in_ham=1}
|> Map.add "homeowners" { in_spam=6; in_ham=0}
|> Map.add "homepage" { in_spam=5; in_ham=2}
|> Map.add "homer" { in_spam=0; in_ham=8}
|> Map.add "homes" { in_spam=10; in_ham=7}
|> Map.add "homework" { in_spam=6; in_ham=1}
|> Map.add "homeys" { in_spam=0; in_ham=4}
|> Map.add "hominem" { in_spam=0; in_ham=7}
|> Map.add "homo" { in_spam=0; in_ham=5}
|> Map.add "homogeneous" { in_spam=0; in_ham=4}
|> Map.add "homophobia" { in_spam=0; in_ham=4}
|> Map.add "homosexual" { in_spam=0; in_ham=5}
|> Map.add "honest" { in_spam=4; in_ham=11}
|> Map.add "honestly" { in_spam=1; in_ham=6}
|> Map.add "honesty" { in_spam=11; in_ham=1}
|> Map.add "honor" { in_spam=21; in_ham=12}
|> Map.add "honored" { in_spam=8; in_ham=3}
|> Map.add "honoring" { in_spam=0; in_ham=6}
|> Map.add "honors" { in_spam=0; in_ham=7}
|> Map.add "honour" { in_spam=2; in_ham=4}
|> Map.add "honoured" { in_spam=0; in_ham=3}
|> Map.add "hood" { in_spam=1; in_ham=7}
|> Map.add "hook" { in_spam=3; in_ham=11}
|> Map.add "hooked" { in_spam=4; in_ham=8}
|> Map.add "hooking" { in_spam=0; in_ham=6}
|> Map.add "hoover" { in_spam=0; in_ham=9}
|> Map.add "hoover's" { in_spam=0; in_ham=7}
|> Map.add "hope" { in_spam=17; in_ham=76}
|> Map.add "hoped" { in_spam=0; in_ham=9}
|> Map.add "hopeful" { in_spam=0; in_ham=3}
|> Map.add "hopefully" { in_spam=1; in_ham=26}
|> Map.add "hopes" { in_spam=1; in_ham=21}
|> Map.add "hoping" { in_spam=1; in_ham=21}
|> Map.add "horizon" { in_spam=1; in_ham=2}
|> Map.add "horizonlive" { in_spam=0; in_ham=3}
|> Map.add "horizontal" { in_spam=0; in_ham=5}
|> Map.add "hormone" { in_spam=2; in_ham=4}
|> Map.add "horrendous" { in_spam=0; in_ham=3}
|> Map.add "horrible" { in_spam=1; in_ham=4}
|> Map.add "horribly" { in_spam=0; in_ham=3}
|> Map.add "horrific" { in_spam=0; in_ham=3}
|> Map.add "horrifying" { in_spam=0; in_ham=4}
|> Map.add "horror" { in_spam=0; in_ham=8}
|> Map.add "horrors" { in_spam=0; in_ham=3}
|> Map.add "horse" { in_spam=0; in_ham=10}
|> Map.add "horses" { in_spam=0; in_ham=5}
|> Map.add "horseshit" { in_spam=0; in_ham=4}
|> Map.add "hospital" { in_spam=2; in_ham=6}
|> Map.add "host" { in_spam=6; in_ham=20}
|> Map.add "hosted" { in_spam=1; in_ham=7}
|> Map.add "hostile" { in_spam=1; in_ham=7}
|> Map.add "hosting" { in_spam=4; in_ham=11}
|> Map.add "hosts" { in_spam=0; in_ham=10}
|> Map.add "hot" { in_spam=19; in_ham=15}
|> Map.add "hotel" { in_spam=3; in_ham=15}
|> Map.add "hotels" { in_spam=4; in_ham=6}
|> Map.add "hotmail" { in_spam=5; in_ham=27}
|> Map.add "hottest" { in_spam=3; in_ham=6}
|> Map.add "hour" { in_spam=17; in_ham=38}
|> Map.add "hours" { in_spam=67; in_ham=58}
|> Map.add "house" { in_spam=17; in_ham=49}
|> Map.add "household" { in_spam=1; in_ham=5}
|> Map.add "housekeeper'" { in_spam=0; in_ham=3}
|> Map.add "housekeepers" { in_spam=1; in_ham=2}
|> Map.add "houses" { in_spam=2; in_ham=3}
|> Map.add "housing" { in_spam=8; in_ham=6}
|> Map.add "hover" { in_spam=10; in_ham=2}
|> Map.add "how" { in_spam=80; in_ham=443}
|> Map.add "how's" { in_spam=0; in_ham=4}
|> Map.add "how-to" { in_spam=2; in_ham=3}
|> Map.add "howard" { in_spam=0; in_ham=6}
|> Map.add "however" { in_spam=28; in_ham=149}
|> Map.add "howto" { in_spam=0; in_ham=4}
|> Map.add "hpti" { in_spam=0; in_ham=3}
|> Map.add "href" { in_spam=235; in_ham=13}
|> Map.add "hspace" { in_spam=19; in_ham=2}
|> Map.add "hte" { in_spam=0; in_ham=4}
|> Map.add "hth" { in_spam=0; in_ham=5}
|> Map.add "htm" { in_spam=73; in_ham=63}
|> Map.add "html" { in_spam=253; in_ham=443}
|> Map.add "html'" { in_spam=1; in_ham=3}
|> Map.add "html-only" { in_spam=0; in_ham=3}
|> Map.add "http" { in_spam=412; in_ham=1864}
|> Map.add "http-equiv" { in_spam=130; in_ham=6}
|> Map.add "https" { in_spam=7; in_ham=405}
|> Map.add "hub" { in_spam=0; in_ham=3}
|> Map.add "hubris" { in_spam=0; in_ham=3}
|> Map.add "huckleberry" { in_spam=0; in_ham=23}
|> Map.add "huge" { in_spam=26; in_ham=36}
|> Map.add "hugh" { in_spam=2; in_ham=3}
|> Map.add "hughes" { in_spam=0; in_ham=12}
|> Map.add "huh" { in_spam=0; in_ham=13}
|> Map.add "human" { in_spam=6; in_ham=67}
|> Map.add "humanity" { in_spam=1; in_ham=7}
|> Map.add "humans" { in_spam=0; in_ham=16}
|> Map.add "humble" { in_spam=1; in_ham=3}
|> Map.add "humbly" { in_spam=3; in_ham=2}
|> Map.add "humility" { in_spam=1; in_ham=2}
|> Map.add "humor" { in_spam=0; in_ham=3}
|> Map.add "humorous" { in_spam=0; in_ham=5}
|> Map.add "humphries" { in_spam=0; in_ham=6}
|> Map.add "hundred" { in_spam=18; in_ham=16}
|> Map.add "hundreds" { in_spam=37; in_ham=31}
|> Map.add "hung" { in_spam=0; in_ham=3}
|> Map.add "hunger" { in_spam=4; in_ham=5}
|> Map.add "hunt" { in_spam=0; in_ham=12}
|> Map.add "hunter" { in_spam=2; in_ham=5}
|> Map.add "hunters" { in_spam=1; in_ham=3}
|> Map.add "hunting" { in_spam=0; in_ham=7}
|> Map.add "huntsville" { in_spam=1; in_ham=4}
|> Map.add "hurdle" { in_spam=2; in_ham=2}
|> Map.add "hurricane" { in_spam=1; in_ham=3}
|> Map.add "hurry" { in_spam=3; in_ham=9}
|> Map.add "hurt" { in_spam=0; in_ham=10}
|> Map.add "hurting" { in_spam=1; in_ham=7}
|> Map.add "hurts" { in_spam=0; in_ham=6}
|> Map.add "husband" { in_spam=8; in_ham=11}
|> Map.add "husband's" { in_spam=4; in_ham=3}
|> Map.add "husbands" { in_spam=0; in_ham=3}
|> Map.add "hussein" { in_spam=0; in_ham=6}
|> Map.add "hut" { in_spam=0; in_ham=4}
|> Map.add "hyatt" { in_spam=0; in_ham=8}
|> Map.add "hyderabad" { in_spam=0; in_ham=3}
|> Map.add "hylton" { in_spam=0; in_ham=5}
|> Map.add "hype" { in_spam=8; in_ham=0}
|> Map.add "hyperion" { in_spam=0; in_ham=5}
|> Map.add "hysterical" { in_spam=0; in_ham=5}
|> Map.add "i'd" { in_spam=3; in_ham=220}
|> Map.add "i'll" { in_spam=14; in_ham=206}
|> Map.add "i'm" { in_spam=24; in_ham=503}
|> Map.add "i've" { in_spam=14; in_ham=333}
|> Map.add "iaa" { in_spam=3; in_ham=2}
|> Map.add "ian" { in_spam=0; in_ham=19}
|> Map.add "ibm" { in_spam=1; in_ham=15}
|> Map.add "ibooks" { in_spam=0; in_ham=4}
|> Map.add "ibuc" { in_spam=0; in_ham=41}
|> Map.add "icab" { in_spam=0; in_ham=4}
|> Map.add "icann" { in_spam=6; in_ham=0}
|> Map.add "ice" { in_spam=0; in_ham=10}
|> Map.add "iceland" { in_spam=2; in_ham=5}
|> Map.add "ick" { in_spam=0; in_ham=6}
|> Map.add "icon" { in_spam=0; in_ham=6}
|> Map.add "icq" { in_spam=1; in_ham=24}
|> Map.add "icy" { in_spam=0; in_ham=5}
|> Map.add "icylp" { in_spam=0; in_ham=3}
|> Map.add "ida" { in_spam=0; in_ham=3}
|> Map.add "ide" { in_spam=0; in_ham=9}
|> Map.add "ide-cd" { in_spam=0; in_ham=4}
|> Map.add "idea" { in_spam=19; in_ham=137}
|> Map.add "ideal" { in_spam=1; in_ham=11}
|> Map.add "ideally" { in_spam=0; in_ham=4}
|> Map.add "ideals" { in_spam=1; in_ham=3}
|> Map.add "ideas" { in_spam=16; in_ham=82}
|> Map.add "identical" { in_spam=3; in_ham=16}
|> Map.add "identified" { in_spam=6; in_ham=10}
|> Map.add "identify" { in_spam=1; in_ham=20}
|> Map.add "identifying" { in_spam=1; in_ham=10}
|> Map.add "identity" { in_spam=5; in_ham=16}
|> Map.add "ideologies" { in_spam=0; in_ham=3}
|> Map.add "ideology" { in_spam=1; in_ham=6}
|> Map.add "idiocy" { in_spam=1; in_ham=2}
|> Map.add "idiot" { in_spam=0; in_ham=10}
|> Map.add "idiotic" { in_spam=0; in_ham=7}
|> Map.add "idiots" { in_spam=0; in_ham=4}
|> Map.add "idle" { in_spam=0; in_ham=7}
|> Map.add "idnetiyfing" { in_spam=0; in_ham=3}
|> Map.add "idol" { in_spam=0; in_ham=3}
|> Map.add "idols" { in_spam=0; in_ham=4}
|> Map.add "ids" { in_spam=0; in_ham=4}
|> Map.add "ieee" { in_spam=0; in_ham=12}
|> Map.add "ietf" { in_spam=0; in_ham=6}
|> Map.add "if'" { in_spam=0; in_ham=3}
|> Map.add "iff" { in_spam=1; in_ham=3}
|> Map.add "iffy" { in_spam=1; in_ham=2}
|> Map.add "ign" { in_spam=1; in_ham=5}
|> Map.add "ignite" { in_spam=0; in_ham=4}
|> Map.add "ignorance" { in_spam=2; in_ham=8}
|> Map.add "ignorant" { in_spam=1; in_ham=3}
|> Map.add "ignore" { in_spam=4; in_ham=31}
|> Map.add "ignored" { in_spam=8; in_ham=18}
|> Map.add "ignores" { in_spam=1; in_ham=8}
|> Map.add "ignoring" { in_spam=1; in_ham=10}
|> Map.add "iht" { in_spam=1; in_ham=2}
|> Map.add "iii" { in_spam=9; in_ham=53}
|> Map.add "iiq" { in_spam=29; in_ham=0}
|> Map.add "iirc" { in_spam=0; in_ham=13}
|> Map.add "iis" { in_spam=0; in_ham=3}
|> Map.add "iiu" { in_spam=2; in_ham=3}
|> Map.add "iki" { in_spam=1; in_ham=17}
|> Map.add "iknow" { in_spam=0; in_ham=4}
|> Map.add "ill" { in_spam=3; in_ham=13}
|> Map.add "ille" { in_spam=0; in_ham=15}
|> Map.add "illegal" { in_spam=7; in_ham=20}
|> Map.add "illegality" { in_spam=1; in_ham=2}
|> Map.add "illegally" { in_spam=1; in_ham=3}
|> Map.add "illegitimate" { in_spam=0; in_ham=3}
|> Map.add "illinois" { in_spam=12; in_ham=8}
|> Map.add "illiterate" { in_spam=0; in_ham=3}
|> Map.add "illness" { in_spam=1; in_ham=2}
|> Map.add "ills" { in_spam=1; in_ham=2}
|> Map.add "illumina" { in_spam=0; in_ham=6}
|> Map.add "illusion" { in_spam=0; in_ham=3}
|> Map.add "illustrate" { in_spam=1; in_ham=2}
|> Map.add "illustrates" { in_spam=0; in_ham=3}
|> Map.add "ilug" { in_spam=32; in_ham=92}
|> Map.add "ilug-admin" { in_spam=0; in_ham=4}
|> Map.add "image" { in_spam=16; in_ham=27}
|> Map.add "images" { in_spam=68; in_ham=78}
|> Map.add "imagination" { in_spam=0; in_ham=4}
|> Map.add "imagine" { in_spam=9; in_ham=39}
|> Map.add "imagined" { in_spam=9; in_ham=5}
|> Map.add "imagining" { in_spam=0; in_ham=3}
|> Map.add "imap" { in_spam=0; in_ham=11}
|> Map.add "imbedded" { in_spam=0; in_ham=3}
|> Map.add "imf" { in_spam=3; in_ham=4}
|> Map.add "img" { in_spam=119; in_ham=54}
|> Map.add "imho" { in_spam=0; in_ham=16}
|> Map.add "immediate" { in_spam=26; in_ham=24}
|> Map.add "immediately" { in_spam=43; in_ham=38}
|> Map.add "imminent" { in_spam=0; in_ham=6}
|> Map.add "immoral" { in_spam=1; in_ham=8}
|> Map.add "imo" { in_spam=0; in_ham=13}
|> Map.add "impact" { in_spam=19; in_ham=14}
|> Map.add "impacts" { in_spam=0; in_ham=4}
|> Map.add "impaired" { in_spam=2; in_ham=2}
|> Map.add "impatient" { in_spam=0; in_ham=5}
|> Map.add "impeached" { in_spam=0; in_ham=4}
|> Map.add "imperative" { in_spam=0; in_ham=3}
|> Map.add "imperfect" { in_spam=0; in_ham=5}
|> Map.add "implement" { in_spam=0; in_ham=22}
|> Map.add "implemented" { in_spam=0; in_ham=20}
|> Map.add "implementing" { in_spam=0; in_ham=7}
|> Map.add "implications" { in_spam=2; in_ham=9}
|> Map.add "implied" { in_spam=0; in_ham=6}
|> Map.add "implies" { in_spam=1; in_ham=2}
|> Map.add "implying" { in_spam=0; in_ham=5}
|> Map.add "impolite" { in_spam=0; in_ham=5}
|> Map.add "import" { in_spam=2; in_ham=9}
|> Map.add "importance" { in_spam=0; in_ham=21}
|> Map.add "important" { in_spam=34; in_ham=85}
|> Map.add "importantly" { in_spam=2; in_ham=7}
|> Map.add "imported" { in_spam=0; in_ham=3}
|> Map.add "importing" { in_spam=1; in_ham=5}
|> Map.add "impose" { in_spam=0; in_ham=8}
|> Map.add "imposed" { in_spam=1; in_ham=4}
|> Map.add "imposes" { in_spam=0; in_ham=3}
|> Map.add "impossible" { in_spam=4; in_ham=22}
|> Map.add "impoverished" { in_spam=2; in_ham=11}
|> Map.add "impress" { in_spam=0; in_ham=3}
|> Map.add "impressed" { in_spam=0; in_ham=4}
|> Map.add "impression" { in_spam=1; in_ham=11}
|> Map.add "impressive" { in_spam=5; in_ham=6}
|> Map.add "improbable" { in_spam=0; in_ham=4}
|> Map.add "improve" { in_spam=20; in_ham=18}
|> Map.add "improved" { in_spam=5; in_ham=13}
|> Map.add "improvement" { in_spam=14; in_ham=13}
|> Map.add "improvements" { in_spam=5; in_ham=8}
|> Map.add "improves" { in_spam=0; in_ham=8}
|> Map.add "improving" { in_spam=1; in_ham=8}
|> Map.add "impulse" { in_spam=2; in_ham=2}
|> Map.add "in''" { in_spam=1; in_ham=2}
|> Map.add "inability" { in_spam=4; in_ham=3}
|> Map.add "inaction" { in_spam=0; in_ham=3}
|> Map.add "inactive" { in_spam=0; in_ham=6}
|> Map.add "inadequate" { in_spam=0; in_ham=6}
|> Map.add "inbetween" { in_spam=1; in_ham=9}
|> Map.add "inbox" { in_spam=1; in_ham=30}
|> Map.add "inc" { in_spam=12; in_ham=87}
|> Map.add "incarnations" { in_spam=0; in_ham=3}
|> Map.add "incentive" { in_spam=1; in_ham=8}
|> Map.add "incentives" { in_spam=2; in_ham=4}
|> Map.add "inch" { in_spam=0; in_ham=3}
|> Map.add "inches" { in_spam=5; in_ham=5}
|> Map.add "incident" { in_spam=2; in_ham=9}
|> Map.add "incidental" { in_spam=3; in_ham=1}
|> Map.add "incidentally" { in_spam=0; in_ham=6}
|> Map.add "incl" { in_spam=1; in_ham=2}
|> Map.add "inclination" { in_spam=1; in_ham=2}
|> Map.add "inclined" { in_spam=0; in_ham=3}
|> Map.add "include" { in_spam=49; in_ham=83}
|> Map.add "included" { in_spam=27; in_ham=53}
|> Map.add "includes" { in_spam=49; in_ham=25}
|> Map.add "including" { in_spam=35; in_ham=93}
|> Map.add "inclusion" { in_spam=3; in_ham=5}
|> Map.add "inclusive" { in_spam=8; in_ham=1}
|> Map.add "income" { in_spam=47; in_ham=18}
|> Map.add "incoming" { in_spam=0; in_ham=21}
|> Map.add "incompatible" { in_spam=0; in_ham=17}
|> Map.add "incomplete" { in_spam=0; in_ham=5}
|> Map.add "inconsistent" { in_spam=0; in_ham=3}
|> Map.add "inconvenient" { in_spam=0; in_ham=4}
|> Map.add "incorporate" { in_spam=1; in_ham=9}
|> Map.add "incorporated" { in_spam=1; in_ham=7}
|> Map.add "incorporates" { in_spam=1; in_ham=5}
|> Map.add "incorrect" { in_spam=0; in_ham=10}
|> Map.add "incorrectly" { in_spam=0; in_ham=5}
|> Map.add "incr" { in_spam=0; in_ham=8}
|> Map.add "increase" { in_spam=31; in_ham=36}
|> Map.add "increased" { in_spam=7; in_ham=14}
|> Map.add "increases" { in_spam=2; in_ham=20}
|> Map.add "increasing" { in_spam=6; in_ham=24}
|> Map.add "increasingly" { in_spam=0; in_ham=16}
|> Map.add "incredible" { in_spam=10; in_ham=10}
|> Map.add "incredibly" { in_spam=8; in_ham=8}
|> Map.add "incremental" { in_spam=0; in_ham=3}
|> Map.add "incurred" { in_spam=3; in_ham=2}
|> Map.add "indeed" { in_spam=4; in_ham=44}
|> Map.add "independence" { in_spam=2; in_ham=8}
|> Map.add "independent" { in_spam=38; in_ham=24}
|> Map.add "index" { in_spam=46; in_ham=73}
|> Map.add "indexes" { in_spam=0; in_ham=3}
|> Map.add "india" { in_spam=3; in_ham=11}
|> Map.add "india's" { in_spam=0; in_ham=12}
|> Map.add "indian" { in_spam=1; in_ham=11}
|> Map.add "indiana" { in_spam=3; in_ham=1}
|> Map.add "indians" { in_spam=0; in_ham=9}
|> Map.add "indicate" { in_spam=12; in_ham=11}
|> Map.add "indicated" { in_spam=3; in_ham=5}
|> Map.add "indicates" { in_spam=0; in_ham=10}
|> Map.add "indicating" { in_spam=2; in_ham=11}
|> Map.add "indication" { in_spam=1; in_ham=5}
|> Map.add "indications" { in_spam=1; in_ham=3}
|> Map.add "indicator" { in_spam=0; in_ham=5}
|> Map.add "indicators" { in_spam=0; in_ham=11}
|> Map.add "indices" { in_spam=0; in_ham=5}
|> Map.add "indictment" { in_spam=0; in_ham=5}
|> Map.add "indirect" { in_spam=0; in_ham=6}
|> Map.add "indirectly" { in_spam=0; in_ham=4}
|> Map.add "individual" { in_spam=6; in_ham=50}
|> Map.add "individually" { in_spam=0; in_ham=4}
|> Map.add "individuals" { in_spam=29; in_ham=31}
|> Map.add "indonesia" { in_spam=2; in_ham=2}
|> Map.add "induce" { in_spam=0; in_ham=3}
|> Map.add "industrial" { in_spam=1; in_ham=11}
|> Map.add "industries" { in_spam=9; in_ham=18}
|> Map.add "industrious" { in_spam=0; in_ham=6}
|> Map.add "industry" { in_spam=20; in_ham=64}
|> Map.add "industry's" { in_spam=1; in_ham=7}
|> Map.add "inefficient" { in_spam=0; in_ham=3}
|> Map.add "inevitable" { in_spam=3; in_ham=6}
|> Map.add "inevitably" { in_spam=0; in_ham=6}
|> Map.add "inexpensive" { in_spam=8; in_ham=2}
|> Map.add "infanticide" { in_spam=0; in_ham=4}
|> Map.add "infection" { in_spam=0; in_ham=3}
|> Map.add "infectious" { in_spam=0; in_ham=3}
|> Map.add "infinite" { in_spam=0; in_ham=4}
|> Map.add "influence" { in_spam=1; in_ham=14}
|> Map.add "influenced" { in_spam=0; in_ham=3}
|> Map.add "influential" { in_spam=0; in_ham=5}
|> Map.add "info" { in_spam=52; in_ham=179}
|> Map.add "infoe" { in_spam=0; in_ham=4}
|> Map.add "infolibria" { in_spam=0; in_ham=6}
|> Map.add "inform" { in_spam=6; in_ham=1}
|> Map.add "informal" { in_spam=2; in_ham=2}
|> Map.add "informatics" { in_spam=0; in_ham=6}
|> Map.add "information" { in_spam=191; in_ham=196}
|> Map.add "informative" { in_spam=4; in_ham=5}
|> Map.add "informed" { in_spam=8; in_ham=5}
|> Map.add "infoworld" { in_spam=0; in_ham=3}
|> Map.add "infringement" { in_spam=1; in_ham=8}
|> Map.add "infringers" { in_spam=0; in_ham=4}
|> Map.add "ing" { in_spam=2; in_ham=5}
|> Map.add "ingenious" { in_spam=1; in_ham=2}
|> Map.add "ingredients" { in_spam=2; in_ham=2}
|> Map.add "inhabitants" { in_spam=1; in_ham=8}
|> Map.add "inherent" { in_spam=1; in_ham=4}
|> Map.add "inheritance" { in_spam=1; in_ham=4}
|> Map.add "inherited" { in_spam=0; in_ham=5}
|> Map.add "ini" { in_spam=0; in_ham=3}
|> Map.add "init" { in_spam=1; in_ham=22}
|> Map.add "initial" { in_spam=13; in_ham=24}
|> Map.add "initializer" { in_spam=0; in_ham=4}
|> Map.add "initially" { in_spam=1; in_ham=15}
|> Map.add "initiated" { in_spam=1; in_ham=14}
|> Map.add "initiative" { in_spam=1; in_ham=10}
|> Map.add "initiatives" { in_spam=0; in_ham=9}
|> Map.add "inject" { in_spam=0; in_ham=3}
|> Map.add "injury" { in_spam=0; in_ham=6}
|> Map.add "inline" { in_spam=0; in_ham=10}
|> Map.add "inn" { in_spam=1; in_ham=4}
|> Map.add "innen" { in_spam=0; in_ham=3}
|> Map.add "inner" { in_spam=1; in_ham=5}
|> Map.add "innocent" { in_spam=0; in_ham=7}
|> Map.add "innocents" { in_spam=0; in_ham=4}
|> Map.add "innovation" { in_spam=2; in_ham=12}
|> Map.add "innovative" { in_spam=4; in_ham=4}
|> Map.add "innumerable" { in_spam=0; in_ham=3}
|> Map.add "innumeracy" { in_spam=0; in_ham=4}
|> Map.add "inphonic" { in_spam=2; in_ham=106}
|> Map.add "input" { in_spam=52; in_ham=19}
|> Map.add "inquiries" { in_spam=6; in_ham=1}
|> Map.add "inquiry" { in_spam=34; in_ham=7}
|> Map.add "insane" { in_spam=0; in_ham=14}
|> Map.add "insecure" { in_spam=0; in_ham=7}
|> Map.add "insensitive" { in_spam=0; in_ham=3}
|> Map.add "insert" { in_spam=8; in_ham=28}
|> Map.add "inserted" { in_spam=3; in_ham=9}
|> Map.add "inserts" { in_spam=0; in_ham=8}
|> Map.add "inside" { in_spam=7; in_ham=50}
|> Map.add "insider" { in_spam=4; in_ham=1}
|> Map.add "insider's" { in_spam=8; in_ham=3}
|> Map.add "insidious" { in_spam=1; in_ham=4}
|> Map.add "insiq" { in_spam=11; in_ham=0}
|> Map.add "insist" { in_spam=3; in_ham=16}
|> Map.add "inspect" { in_spam=0; in_ham=9}
|> Map.add "inspected" { in_spam=0; in_ham=6}
|> Map.add "inspection" { in_spam=2; in_ham=10}
|> Map.add "inspections" { in_spam=0; in_ham=6}
|> Map.add "inspired" { in_spam=1; in_ham=11}
|> Map.add "instability" { in_spam=0; in_ham=4}
|> Map.add "install" { in_spam=1; in_ham=101}
|> Map.add "install'" { in_spam=0; in_ham=5}
|> Map.add "installation" { in_spam=3; in_ham=31}
|> Map.add "installed" { in_spam=2; in_ham=112}
|> Map.add "installer" { in_spam=0; in_ham=3}
|> Map.add "installing" { in_spam=3; in_ham=30}
|> Map.add "installs" { in_spam=1; in_ham=9}
|> Map.add "instance" { in_spam=5; in_ham=29}
|> Map.add "instances" { in_spam=0; in_ham=13}
|> Map.add "instant" { in_spam=23; in_ham=18}
|> Map.add "instantly" { in_spam=14; in_ham=18}
|> Map.add "instead" { in_spam=41; in_ham=154}
|> Map.add "instincts" { in_spam=0; in_ham=3}
|> Map.add "institute" { in_spam=1; in_ham=17}
|> Map.add "institution" { in_spam=1; in_ham=5}
|> Map.add "institutions" { in_spam=1; in_ham=4}
|> Map.add "instructed" { in_spam=13; in_ham=1}
|> Map.add "instruction" { in_spam=14; in_ham=1}
|> Map.add "instructions" { in_spam=33; in_ham=11}
|> Map.add "instructor" { in_spam=1; in_ham=2}
|> Map.add "instruments" { in_spam=5; in_ham=2}
|> Map.add "instrumnet" { in_spam=0; in_ham=3}
|> Map.add "insufficient" { in_spam=0; in_ham=5}
|> Map.add "insult" { in_spam=2; in_ham=5}
|> Map.add "insurance" { in_spam=51; in_ham=11}
|> Map.add "insuranceiq" { in_spam=29; in_ham=0}
|> Map.add "insured" { in_spam=5; in_ham=0}
|> Map.add "int" { in_spam=2; in_ham=15}
|> Map.add "integer" { in_spam=2; in_ham=4}
|> Map.add "integral" { in_spam=16; in_ham=4}
|> Map.add "integrate" { in_spam=0; in_ham=15}
|> Map.add "integrated" { in_spam=1; in_ham=12}
|> Map.add "integrating" { in_spam=0; in_ham=9}
|> Map.add "integration" { in_spam=0; in_ham=21}
|> Map.add "integrity" { in_spam=4; in_ham=4}
|> Map.add "intel" { in_spam=1; in_ham=11}
|> Map.add "intel's" { in_spam=0; in_ham=5}
|> Map.add "intellectual" { in_spam=0; in_ham=17}
|> Map.add "intelligence" { in_spam=11; in_ham=26}
|> Map.add "intelligent" { in_spam=2; in_ham=9}
|> Map.add "intend" { in_spam=8; in_ham=5}
|> Map.add "intended" { in_spam=19; in_ham=17}
|> Map.add "intense" { in_spam=1; in_ham=11}
|> Map.add "intent" { in_spam=1; in_ham=5}
|> Map.add "intention" { in_spam=2; in_ham=8}
|> Map.add "inter-and" { in_spam=0; in_ham=6}
|> Map.add "interact" { in_spam=0; in_ham=11}
|> Map.add "interaction" { in_spam=1; in_ham=14}
|> Map.add "interactions" { in_spam=0; in_ham=8}
|> Map.add "interactive" { in_spam=12; in_ham=53}
|> Map.add "intercepted" { in_spam=0; in_ham=4}
|> Map.add "intercourse" { in_spam=0; in_ham=4}
|> Map.add "interest" { in_spam=49; in_ham=40}
|> Map.add "interested" { in_spam=30; in_ham=49}
|> Map.add "interesting" { in_spam=0; in_ham=97}
|> Map.add "interests" { in_spam=5; in_ham=17}
|> Map.add "interface" { in_spam=2; in_ham=39}
|> Map.add "interface'" { in_spam=0; in_ham=3}
|> Map.add "interfaces" { in_spam=0; in_ham=7}
|> Map.add "interference" { in_spam=0; in_ham=6}
|> Map.add "interferes" { in_spam=0; in_ham=3}
|> Map.add "interject" { in_spam=0; in_ham=6}
|> Map.add "interlink" { in_spam=0; in_ham=8}
|> Map.add "intermediate" { in_spam=0; in_ham=3}
|> Map.add "internal" { in_spam=4; in_ham=24}
|> Map.add "internally" { in_spam=0; in_ham=5}
|> Map.add "internet" { in_spam=78; in_ham=146}
|> Map.add "internet's" { in_spam=0; in_ham=6}
|> Map.add "interns" { in_spam=0; in_ham=3}
|> Map.add "interoperate" { in_spam=0; in_ham=5}
|> Map.add "interpret" { in_spam=0; in_ham=5}
|> Map.add "interpreter" { in_spam=0; in_ham=11}
|> Map.add "interrupted" { in_spam=2; in_ham=3}
|> Map.add "interruption" { in_spam=6; in_ham=1}
|> Map.add "intertwingly" { in_spam=0; in_ham=3}
|> Map.add "intervention" { in_spam=7; in_ham=8}
|> Map.add "interview" { in_spam=4; in_ham=17}
|> Map.add "interviewed" { in_spam=0; in_ham=11}
|> Map.add "interviews" { in_spam=0; in_ham=6}
|> Map.add "inthe" { in_spam=0; in_ham=3}
|> Map.add "intimate" { in_spam=3; in_ham=4}
|> Map.add "intimidate" { in_spam=3; in_ham=1}
|> Map.add "intimidation" { in_spam=0; in_ham=4}
|> Map.add "into" { in_spam=75; in_ham=423}
|> Map.add "intrigue" { in_spam=1; in_ham=2}
|> Map.add "introduce" { in_spam=13; in_ham=10}
|> Map.add "introduced" { in_spam=3; in_ham=18}
|> Map.add "introducing" { in_spam=1; in_ham=3}
|> Map.add "introduction" { in_spam=4; in_ham=14}
|> Map.add "introductory" { in_spam=6; in_ham=0}
|> Map.add "intuition" { in_spam=1; in_ham=5}
|> Map.add "invade" { in_spam=2; in_ham=3}
|> Map.add "invaded" { in_spam=2; in_ham=3}
|> Map.add "invalid" { in_spam=1; in_ham=9}
|> Map.add "invaluable" { in_spam=7; in_ham=4}
|> Map.add "invasion" { in_spam=1; in_ham=5}
|> Map.add "invent" { in_spam=0; in_ham=9}
|> Map.add "invented" { in_spam=0; in_ham=15}
|> Map.add "inventing" { in_spam=0; in_ham=3}
|> Map.add "invention" { in_spam=3; in_ham=3}
|> Map.add "inventor" { in_spam=0; in_ham=4}
|> Map.add "invest" { in_spam=23; in_ham=7}
|> Map.add "invested" { in_spam=4; in_ham=5}
|> Map.add "investigate" { in_spam=2; in_ham=8}
|> Map.add "investigated" { in_spam=7; in_ham=1}
|> Map.add "investing" { in_spam=12; in_ham=3}
|> Map.add "investment" { in_spam=52; in_ham=26}
|> Map.add "investments" { in_spam=10; in_ham=10}
|> Map.add "investor" { in_spam=6; in_ham=2}
|> Map.add "investor's" { in_spam=5; in_ham=0}
|> Map.add "investors" { in_spam=16; in_ham=16}
|> Map.add "invisible" { in_spam=0; in_ham=13}
|> Map.add "invitation" { in_spam=3; in_ham=2}
|> Map.add "invitations" { in_spam=6; in_ham=1}
|> Map.add "invite" { in_spam=5; in_ham=6}
|> Map.add "invited" { in_spam=1; in_ham=9}
|> Map.add "invoke" { in_spam=0; in_ham=11}
|> Map.add "invoked" { in_spam=0; in_ham=20}
|> Map.add "invoking" { in_spam=0; in_ham=4}
|> Map.add "involve" { in_spam=3; in_ham=13}
|> Map.add "involved" { in_spam=20; in_ham=43}
|> Map.add "involvement" { in_spam=1; in_ham=6}
|> Map.add "involves" { in_spam=1; in_ham=12}
|> Map.add "involving" { in_spam=2; in_ham=5}
|> Map.add "inw" { in_spam=1; in_ham=2}
|> Map.add "iol" { in_spam=0; in_ham=3}
|> Map.add "ion" { in_spam=1; in_ham=3}
|> Map.add "iowa" { in_spam=3; in_ham=1}
|> Map.add "ipo" { in_spam=0; in_ham=6}
|> Map.add "ips" { in_spam=1; in_ham=7}
|> Map.add "iqa" { in_spam=0; in_ham=9}
|> Map.add "iqs" { in_spam=0; in_ham=3}
|> Map.add "ira" { in_spam=0; in_ham=5}
|> Map.add "iran" { in_spam=1; in_ham=6}
|> Map.add "iraq" { in_spam=2; in_ham=29}
|> Map.add "iraq's" { in_spam=0; in_ham=4}
|> Map.add "irc" { in_spam=0; in_ham=6}
|> Map.add "ireland" { in_spam=4; in_ham=20}
|> Map.add "irish" { in_spam=47; in_ham=101}
|> Map.add "irix" { in_spam=0; in_ham=4}
|> Map.add "iron" { in_spam=1; in_ham=5}
|> Map.add "ironic" { in_spam=0; in_ham=5}
|> Map.add "irony" { in_spam=0; in_ham=8}
|> Map.add "irrational" { in_spam=0; in_ham=4}
|> Map.add "irregulars" { in_spam=0; in_ham=5}
|> Map.add "irrelevant" { in_spam=0; in_ham=8}
|> Map.add "irrespective" { in_spam=0; in_ham=4}
|> Map.add "irritating" { in_spam=0; in_ham=3}
|> Map.add "irs" { in_spam=1; in_ham=5}
|> Map.add "irtf" { in_spam=0; in_ham=6}
|> Map.add "irvine" { in_spam=1; in_ham=10}
|> Map.add "isapnp" { in_spam=0; in_ham=3}
|> Map.add "isdn" { in_spam=1; in_ham=2}
|> Map.add "islam" { in_spam=0; in_ham=7}
|> Map.add "islamic" { in_spam=0; in_ham=4}
|> Map.add "island" { in_spam=5; in_ham=10}
|> Map.add "islands" { in_spam=4; in_ham=4}
|> Map.add "isn't" { in_spam=13; in_ham=167}
|> Map.add "isnt" { in_spam=0; in_ham=5}
|> Map.add "iso" { in_spam=0; in_ham=9}
|> Map.add "iso's" { in_spam=0; in_ham=3}
|> Map.add "iso-" { in_spam=71; in_ham=10}
|> Map.add "isolated" { in_spam=1; in_ham=3}
|> Map.add "isos" { in_spam=0; in_ham=4}
|> Map.add "isp" { in_spam=5; in_ham=15}
|> Map.add "isp's" { in_spam=0; in_ham=4}
|> Map.add "isps" { in_spam=0; in_ham=13}
|> Map.add "israel" { in_spam=2; in_ham=17}
|> Map.add "israeli" { in_spam=0; in_ham=5}
|> Map.add "israelis" { in_spam=0; in_ham=6}
|> Map.add "issue" { in_spam=12; in_ham=128}
|> Map.add "issued" { in_spam=9; in_ham=9}
|> Map.add "issues" { in_spam=4; in_ham=81}
|> Map.add "ist" { in_spam=2; in_ham=4}
|> Map.add "it'd" { in_spam=0; in_ham=16}
|> Map.add "it'll" { in_spam=0; in_ham=24}
|> Map.add "it's" { in_spam=58; in_ham=569}
|> Map.add "italian" { in_spam=0; in_ham=7}
|> Map.add "italy" { in_spam=3; in_ham=4}
|> Map.add "item" { in_spam=3; in_ham=19}
|> Map.add "itemid" { in_spam=0; in_ham=10}
|> Map.add "items" { in_spam=5; in_ham=22}
|> Map.add "itmeaa" { in_spam=0; in_ham=6}
|> Map.add "its" { in_spam=32; in_ham=339}
|> Map.add "itself" { in_spam=6; in_ham=68}
|> Map.add "itselleni" { in_spam=0; in_ham=4}
|> Map.add "ive" { in_spam=0; in_ham=8}
|> Map.add "ivh" { in_spam=0; in_ham=8}
|> Map.add "ivory" { in_spam=3; in_ham=1}
|> Map.add "ivr" { in_spam=0; in_ham=3}
|> Map.add "ivy" { in_spam=0; in_ham=7}
|> Map.add "jabber" { in_spam=0; in_ham=47}
|> Map.add "jack" { in_spam=0; in_ham=15}
|> Map.add "jacket" { in_spam=1; in_ham=3}
|> Map.add "jackson" { in_spam=0; in_ham=4}
|> Map.add "jacob" { in_spam=0; in_ham=9}
|> Map.add "jacobs" { in_spam=0; in_ham=3}
|> Map.add "jacques" { in_spam=0; in_ham=7}
|> Map.add "jaguar" { in_spam=0; in_ham=6}
|> Map.add "jail" { in_spam=0; in_ham=7}
|> Map.add "jailed" { in_spam=0; in_ham=5}
|> Map.add "jakma" { in_spam=0; in_ham=4}
|> Map.add "jam" { in_spam=3; in_ham=1}
|> Map.add "jamaica" { in_spam=3; in_ham=1}
|> Map.add "james" { in_spam=3; in_ham=53}
|> Map.add "jamesr" { in_spam=0; in_ham=28}
|> Map.add "jamie" { in_spam=1; in_ham=3}
|> Map.add "jammed" { in_spam=0; in_ham=3}
|> Map.add "jan" { in_spam=2; in_ham=2}
|> Map.add "janis" { in_spam=0; in_ham=3}
|> Map.add "january" { in_spam=8; in_ham=17}
|> Map.add "japan" { in_spam=3; in_ham=9}
|> Map.add "japan's" { in_spam=0; in_ham=3}
|> Map.add "japanese" { in_spam=4; in_ham=12}
|> Map.add "jar" { in_spam=1; in_ham=8}
|> Map.add "jargon" { in_spam=0; in_ham=3}
|> Map.add "jason" { in_spam=1; in_ham=12}
|> Map.add "java" { in_spam=3; in_ham=47}
|> Map.add "javaone" { in_spam=0; in_ham=6}
|> Map.add "javapro" { in_spam=0; in_ham=6}
|> Map.add "javascript" { in_spam=7; in_ham=6}
|> Map.add "jay" { in_spam=0; in_ham=5}
|> Map.add "jdk" { in_spam=1; in_ham=7}
|> Map.add "jealous" { in_spam=0; in_ham=5}
|> Map.add "jeb" { in_spam=0; in_ham=5}
|> Map.add "jedi" { in_spam=0; in_ham=4}
|> Map.add "jeff" { in_spam=1; in_ham=11}
|> Map.add "jefferson" { in_spam=2; in_ham=3}
|> Map.add "jeffrey" { in_spam=0; in_ham=6}
|> Map.add "jennifer" { in_spam=8; in_ham=1}
|> Map.add "jeremy" { in_spam=1; in_ham=64}
|> Map.add "jeremy's" { in_spam=0; in_ham=4}
|> Map.add "jerry" { in_spam=1; in_ham=3}
|> Map.add "jersey" { in_spam=11; in_ham=4}
|> Map.add "jesse" { in_spam=0; in_ham=14}
|> Map.add "jesus" { in_spam=1; in_ham=9}
|> Map.add "jet" { in_spam=0; in_ham=3}
|> Map.add "jets" { in_spam=2; in_ham=2}
|> Map.add "jetzt" { in_spam=1; in_ham=3}
|> Map.add "jewish" { in_spam=3; in_ham=4}
|> Map.add "jhtml" { in_spam=0; in_ham=4}
|> Map.add "jid" { in_spam=0; in_ham=9}
|> Map.add "jif" { in_spam=0; in_ham=3}
|> Map.add "jim" { in_spam=0; in_ham=54}
|> Map.add "jimmy" { in_spam=0; in_ham=3}
|> Map.add "jit" { in_spam=0; in_ham=6}
|> Map.add "jkeating" { in_spam=0; in_ham=8}
|> Map.add "jmason" { in_spam=5; in_ham=20}
|> Map.add "job" { in_spam=19; in_ham=96}
|> Map.add "jobs" { in_spam=4; in_ham=19}
|> Map.add "jody" { in_spam=7; in_ham=0}
|> Map.add "joe" { in_spam=7; in_ham=36}
|> Map.add "joel" { in_spam=0; in_ham=6}
|> Map.add "john" { in_spam=9; in_ham=104}
|> Map.add "johnhall" { in_spam=0; in_ham=18}
|> Map.add "johnny" { in_spam=0; in_ham=3}
|> Map.add "johnson" { in_spam=2; in_ham=2}
|> Map.add "johnston" { in_spam=0; in_ham=6}
|> Map.add "join" { in_spam=29; in_ham=78}
|> Map.add "joined" { in_spam=11; in_ham=19}
|> Map.add "joining" { in_spam=5; in_ham=7}
|> Map.add "joint" { in_spam=1; in_ham=14}
|> Map.add "jointly" { in_spam=0; in_ham=5}
|> Map.add "joke" { in_spam=1; in_ham=23}
|> Map.add "jokes" { in_spam=0; in_ham=6}
|> Map.add "joking" { in_spam=0; in_ham=6}
|> Map.add "joliet" { in_spam=0; in_ham=3}
|> Map.add "jolt" { in_spam=0; in_ham=6}
|> Map.add "jon" { in_spam=0; in_ham=12}
|> Map.add "jonathan" { in_spam=0; in_ham=4}
|> Map.add "jones" { in_spam=1; in_ham=11}
|> Map.add "jordan" { in_spam=2; in_ham=7}
|> Map.add "joseph" { in_spam=10; in_ham=24}
|> Map.add "josh" { in_spam=0; in_ham=6}
|> Map.add "joshua" { in_spam=0; in_ham=3}
|> Map.add "jostain" { in_spam=0; in_ham=4}
|> Map.add "journal" { in_spam=8; in_ham=34}
|> Map.add "journalism" { in_spam=1; in_ham=6}
|> Map.add "journalist" { in_spam=1; in_ham=10}
|> Map.add "journalistic" { in_spam=1; in_ham=2}
|> Map.add "journalists" { in_spam=1; in_ham=2}
|> Map.add "journey" { in_spam=0; in_ham=3}
|> Map.add "joy" { in_spam=0; in_ham=3}
|> Map.add "joyously" { in_spam=0; in_ham=4}
|> Map.add "jpg" { in_spam=74; in_ham=32}
|> Map.add "jpwefu" { in_spam=0; in_ham=3}
|> Map.add "jrennie" { in_spam=0; in_ham=3}
|> Map.add "jsp" { in_spam=6; in_ham=10}
|> Map.add "jtauber" { in_spam=0; in_ham=3}
|> Map.add "jtmeaa" { in_spam=0; in_ham=4}
|> Map.add "judge" { in_spam=1; in_ham=19}

