open Bayesian.Database
open BayesianBody_002
let db = db 
|> Map.add "capital'" { in_spam=0; in_ham=3}
|> Map.add "capitalism" { in_spam=0; in_ham=9}
|> Map.add "capitalist" { in_spam=0; in_ham=9}
|> Map.add "capitalists" { in_spam=1; in_ham=2}
|> Map.add "caps" { in_spam=0; in_ham=4}
|> Map.add "caps-lock" { in_spam=0; in_ham=3}
|> Map.add "capsules" { in_spam=1; in_ham=2}
|> Map.add "captain" { in_spam=3; in_ham=4}
|> Map.add "capture" { in_spam=2; in_ham=9}
|> Map.add "captured" { in_spam=0; in_ham=4}
|> Map.add "captures" { in_spam=0; in_ham=5}
|> Map.add "capturing" { in_spam=0; in_ham=3}
|> Map.add "car" { in_spam=18; in_ham=26}
|> Map.add "caramail" { in_spam=5; in_ham=0}
|> Map.add "carbon" { in_spam=0; in_ham=9}
|> Map.add "carcinogenic" { in_spam=1; in_ham=2}
|> Map.add "carcooning" { in_spam=0; in_ham=3}
|> Map.add "card" { in_spam=30; in_ham=46}
|> Map.add "cards" { in_spam=18; in_ham=15}
|> Map.add "care" { in_spam=16; in_ham=49}
|> Map.add "career" { in_spam=17; in_ham=14}
|> Map.add "carefree" { in_spam=0; in_ham=5}
|> Map.add "careful" { in_spam=1; in_ham=20}
|> Map.add "carefully" { in_spam=11; in_ham=10}
|> Map.add "cares" { in_spam=1; in_ham=10}
|> Map.add "carey" { in_spam=0; in_ham=3}
|> Map.add "cargo" { in_spam=1; in_ham=2}
|> Map.add "caribbean" { in_spam=1; in_ham=3}
|> Map.add "caring" { in_spam=2; in_ham=5}
|> Map.add "carlo" { in_spam=0; in_ham=5}
|> Map.add "carnage" { in_spam=0; in_ham=3}
|> Map.add "carnegie" { in_spam=0; in_ham=3}
|> Map.add "carolina" { in_spam=4; in_ham=3}
|> Map.add "carried" { in_spam=0; in_ham=8}
|> Map.add "carrier" { in_spam=1; in_ham=3}
|> Map.add "carriers" { in_spam=7; in_ham=9}
|> Map.add "carry" { in_spam=7; in_ham=21}
|> Map.add "carrying" { in_spam=4; in_ham=12}
|> Map.add "cars" { in_spam=3; in_ham=12}
|> Map.add "cartels" { in_spam=1; in_ham=2}
|> Map.add "cartons" { in_spam=9; in_ham=0}
|> Map.add "cartoon" { in_spam=0; in_ham=6}
|> Map.add "cartoons" { in_spam=0; in_ham=6}
|> Map.add "cascade" { in_spam=0; in_ham=7}
|> Map.add "cascade's" { in_spam=0; in_ham=6}
|> Map.add "case" { in_spam=22; in_ham=183}
|> Map.add "cases" { in_spam=12; in_ham=44}
|> Map.add "cash" { in_spam=51; in_ham=21}
|> Map.add "caspian" { in_spam=0; in_ham=3}
|> Map.add "cassette" { in_spam=1; in_ham=5}
|> Map.add "cast" { in_spam=1; in_ham=4}
|> Map.add "casting" { in_spam=0; in_ham=6}
|> Map.add "castle" { in_spam=0; in_ham=8}
|> Map.add "casualties" { in_spam=0; in_ham=7}
|> Map.add "casualty" { in_spam=1; in_ham=2}
|> Map.add "cat" { in_spam=2; in_ham=21}
|> Map.add "catalog" { in_spam=3; in_ham=11}
|> Map.add "catalogs" { in_spam=2; in_ham=5}
|> Map.add "catalogue" { in_spam=0; in_ham=5}
|> Map.add "catalyst" { in_spam=0; in_ham=6}
|> Map.add "catastrophic" { in_spam=0; in_ham=4}
|> Map.add "catch" { in_spam=1; in_ham=29}
|> Map.add "catch-up" { in_spam=0; in_ham=11}
|> Map.add "catches" { in_spam=0; in_ham=9}
|> Map.add "catching" { in_spam=1; in_ham=7}
|> Map.add "catchup" { in_spam=0; in_ham=6}
|> Map.add "categories" { in_spam=2; in_ham=6}
|> Map.add "category" { in_spam=5; in_ham=19}
|> Map.add "cathedral" { in_spam=0; in_ham=3}
|> Map.add "catholic" { in_spam=3; in_ham=3}
|> Map.add "cato" { in_spam=0; in_ham=3}
|> Map.add "cats" { in_spam=1; in_ham=4}
|> Map.add "caught" { in_spam=1; in_ham=22}
|> Map.add "caughtspam" { in_spam=0; in_ham=5}
|> Map.add "causality" { in_spam=0; in_ham=3}
|> Map.add "cause" { in_spam=9; in_ham=60}
|> Map.add "caused" { in_spam=4; in_ham=36}
|> Map.add "causes" { in_spam=1; in_ham=21}
|> Map.add "causing" { in_spam=0; in_ham=17}
|> Map.add "cautious" { in_spam=1; in_ham=2}
|> Map.add "cb-" { in_spam=0; in_ham=3}
|> Map.add "cbphost" { in_spam=5; in_ham=0}
|> Map.add "cbs" { in_spam=6; in_ham=1}
|> Map.add "cbyi" { in_spam=5; in_ham=0}
|> Map.add "cc'ing" { in_spam=0; in_ham=3}
|> Map.add "cccc" { in_spam=6; in_ham=0}
|> Map.add "cccccc" { in_spam=30; in_ham=0}
|> Map.add "cce" { in_spam=0; in_ham=3}
|> Map.add "cd's" { in_spam=4; in_ham=4}
|> Map.add "cd-key" { in_spam=0; in_ham=4}
|> Map.add "cd-r" { in_spam=6; in_ham=2}
|> Map.add "cd-rom" { in_spam=11; in_ham=11}
|> Map.add "cd-rw" { in_spam=0; in_ham=4}
|> Map.add "cdale" { in_spam=0; in_ham=19}
|> Map.add "cdrom" { in_spam=1; in_ham=9}
|> Map.add "cds" { in_spam=7; in_ham=20}
|> Map.add "cdt" { in_spam=0; in_ham=8}
|> Map.add "ceci" { in_spam=0; in_ham=3}
|> Map.add "ceiling" { in_spam=2; in_ham=3}
|> Map.add "celebrate" { in_spam=0; in_ham=6}
|> Map.add "celebrity" { in_spam=0; in_ham=3}
|> Map.add "celeron" { in_spam=1; in_ham=2}
|> Map.add "cell" { in_spam=10; in_ham=130}
|> Map.add "cellpadding" { in_spam=145; in_ham=2}
|> Map.add "cells" { in_spam=0; in_ham=10}
|> Map.add "cellspacing" { in_spam=141; in_ham=2}
|> Map.add "cellular" { in_spam=3; in_ham=3}
|> Map.add "censeo" { in_spam=0; in_ham=4}
|> Map.add "censor" { in_spam=0; in_ham=5}
|> Map.add "censorship" { in_spam=0; in_ham=5}
|> Map.add "census" { in_spam=0; in_ham=5}
|> Map.add "cent" { in_spam=7; in_ham=4}
|> Map.add "center" { in_spam=197; in_ham=75}
|> Map.add "centered" { in_spam=2; in_ham=4}
|> Map.add "centers" { in_spam=0; in_ham=5}
|> Map.add "central" { in_spam=16; in_ham=23}
|> Map.add "centralized" { in_spam=0; in_ham=4}
|> Map.add "centre" { in_spam=3; in_ham=13}
|> Map.add "centres" { in_spam=0; in_ham=3}
|> Map.add "cents" { in_spam=11; in_ham=11}
|> Map.add "centuries" { in_spam=1; in_ham=7}
|> Map.add "century" { in_spam=10; in_ham=19}
|> Map.add "ceo" { in_spam=4; in_ham=17}
|> Map.add "ceos" { in_spam=0; in_ham=6}
|> Map.add "certain" { in_spam=11; in_ham=40}
|> Map.add "certainly" { in_spam=3; in_ham=77}
|> Map.add "certificate" { in_spam=5; in_ham=3}
|> Map.add "certified" { in_spam=12; in_ham=7}
|> Map.add "cet" { in_spam=2; in_ham=8}
|> Map.add "cfm" { in_spam=14; in_ham=7}
|> Map.add "cgi" { in_spam=23; in_ham=50}
|> Map.add "cgi-bin" { in_spam=23; in_ham=7}
|> Map.add "chain" { in_spam=2; in_ham=10}
|> Map.add "chair" { in_spam=0; in_ham=8}
|> Map.add "chairman" { in_spam=2; in_ham=15}
|> Map.add "chairman's" { in_spam=0; in_ham=3}
|> Map.add "chairs" { in_spam=0; in_ham=4}
|> Map.add "chalk" { in_spam=0; in_ham=5}
|> Map.add "chalking" { in_spam=0; in_ham=3}
|> Map.add "challenge" { in_spam=3; in_ham=13}
|> Map.add "challenges" { in_spam=1; in_ham=5}
|> Map.add "challenging" { in_spam=1; in_ham=4}
|> Map.add "chamber" { in_spam=6; in_ham=4}
|> Map.add "chamberlin" { in_spam=0; in_ham=3}
|> Map.add "champagne" { in_spam=2; in_ham=2}
|> Map.add "champion" { in_spam=1; in_ham=6}
|> Map.add "chance" { in_spam=17; in_ham=36}
|> Map.add "chancellor" { in_spam=0; in_ham=3}
|> Map.add "chances" { in_spam=0; in_ham=14}
|> Map.add "change" { in_spam=43; in_ham=234}
|> Map.add "changeable" { in_spam=0; in_ham=3}
|> Map.add "changed" { in_spam=10; in_ham=86}
|> Map.add "changelog" { in_spam=0; in_ham=3}
|> Map.add "changes" { in_spam=11; in_ham=75}
|> Map.add "changing" { in_spam=6; in_ham=41}
|> Map.add "channel" { in_spam=0; in_ham=14}
|> Map.add "channels" { in_spam=7; in_ham=15}
|> Map.add "chaos" { in_spam=2; in_ham=8}
|> Map.add "chaperoned" { in_spam=0; in_ham=3}
|> Map.add "chapesses" { in_spam=0; in_ham=5}
|> Map.add "chaps" { in_spam=0; in_ham=5}
|> Map.add "char" { in_spam=0; in_ham=10}
|> Map.add "character" { in_spam=0; in_ham=16}
|> Map.add "characters" { in_spam=2; in_ham=21}
|> Map.add "charge" { in_spam=31; in_ham=17}
|> Map.add "charged" { in_spam=4; in_ham=8}
|> Map.add "charges" { in_spam=14; in_ham=10}
|> Map.add "charging" { in_spam=0; in_ham=15}
|> Map.add "charities" { in_spam=0; in_ham=4}
|> Map.add "charity" { in_spam=0; in_ham=5}
|> Map.add "charles" { in_spam=0; in_ham=7}
|> Map.add "charlie" { in_spam=0; in_ham=4}
|> Map.add "charlotte" { in_spam=1; in_ham=3}
|> Map.add "charm" { in_spam=0; in_ham=8}
|> Map.add "charming" { in_spam=0; in_ham=4}
|> Map.add "chars" { in_spam=0; in_ham=6}
|> Map.add "charset" { in_spam=126; in_ham=21}
|> Map.add "charters" { in_spam=0; in_ham=3}
|> Map.add "charts" { in_spam=1; in_ham=8}
|> Map.add "chase" { in_spam=4; in_ham=1}
|> Map.add "chased" { in_spam=0; in_ham=7}
|> Map.add "chasing" { in_spam=3; in_ham=6}
|> Map.add "chat" { in_spam=5; in_ham=18}
|> Map.add "cheap" { in_spam=11; in_ham=20}
|> Map.add "cheaper" { in_spam=0; in_ham=25}
|> Map.add "cheating" { in_spam=1; in_ham=5}
|> Map.add "check" { in_spam=31; in_ham=153}
|> Map.add "check-files" { in_spam=0; in_ham=3}
|> Map.add "checkbox" { in_spam=6; in_ham=1}
|> Map.add "checked" { in_spam=4; in_ham=51}
|> Map.add "checking" { in_spam=0; in_ham=31}
|> Map.add "checkout" { in_spam=1; in_ham=3}
|> Map.add "checkpoint" { in_spam=0; in_ham=11}
|> Map.add "checks" { in_spam=11; in_ham=17}
|> Map.add "checksum" { in_spam=0; in_ham=5}
|> Map.add "cheer" { in_spam=0; in_ham=3}
|> Map.add "cheers" { in_spam=0; in_ham=75}
|> Map.add "chef" { in_spam=2; in_ham=2}
|> Map.add "chemical" { in_spam=0; in_ham=10}
|> Map.add "chemistry" { in_spam=0; in_ham=7}
|> Map.add "cheney" { in_spam=0; in_ham=6}
|> Map.add "cheryl" { in_spam=0; in_ham=3}
|> Map.add "chest" { in_spam=0; in_ham=9}
|> Map.add "chests" { in_spam=0; in_ham=3}
|> Map.add "chevron" { in_spam=5; in_ham=0}
|> Map.add "chganes" { in_spam=0; in_ham=3}
|> Map.add "chi" { in_spam=1; in_ham=2}
|> Map.add "chicago" { in_spam=9; in_ham=14}
|> Map.add "chichakly" { in_spam=0; in_ham=6}
|> Map.add "chick" { in_spam=0; in_ham=5}
|> Map.add "chicken" { in_spam=1; in_ham=3}
|> Map.add "chicks" { in_spam=0; in_ham=5}
|> Map.add "chief" { in_spam=4; in_ham=26}
|> Map.add "chiefs" { in_spam=1; in_ham=8}
|> Map.add "chiefs'" { in_spam=0; in_ham=3}
|> Map.add "child" { in_spam=15; in_ham=19}
|> Map.add "childhood" { in_spam=1; in_ham=11}
|> Map.add "children" { in_spam=13; in_ham=38}
|> Map.add "chile" { in_spam=2; in_ham=3}
|> Map.add "chimera" { in_spam=0; in_ham=6}
|> Map.add "china" { in_spam=8; in_ham=23}
|> Map.add "china's" { in_spam=0; in_ham=4}
|> Map.add "chinese" { in_spam=5; in_ham=14}
|> Map.add "chip" { in_spam=1; in_ham=12}
|> Map.add "chipset" { in_spam=0; in_ham=6}
|> Map.add "chirac" { in_spam=0; in_ham=12}
|> Map.add "chiu" { in_spam=0; in_ham=3}
|> Map.add "chmod" { in_spam=0; in_ham=7}
|> Map.add "chocolate" { in_spam=0; in_ham=8}
|> Map.add "choice" { in_spam=17; in_ham=52}
|> Map.add "choices" { in_spam=4; in_ham=18}
|> Map.add "choose" { in_spam=15; in_ham=48}
|> Map.add "chooses" { in_spam=0; in_ham=3}
|> Map.add "choosing" { in_spam=4; in_ham=12}
|> Map.add "chores" { in_spam=0; in_ham=5}
|> Map.add "chose" { in_spam=1; in_ham=12}
|> Map.add "chosen" { in_spam=6; in_ham=12}
|> Map.add "chris" { in_spam=1; in_ham=89}
|> Map.add "chris'" { in_spam=0; in_ham=3}
|> Map.add "chris-" { in_spam=0; in_ham=5}
|> Map.add "christian" { in_spam=5; in_ham=1}
|> Map.add "christianity" { in_spam=0; in_ham=4}
|> Map.add "christmas" { in_spam=1; in_ham=9}
|> Map.add "chronicle" { in_spam=1; in_ham=4}
|> Map.add "chronicled" { in_spam=1; in_ham=2}
|> Map.add "chroot" { in_spam=0; in_ham=3}
|> Map.add "chuck" { in_spam=0; in_ham=21}
|> Map.add "church" { in_spam=0; in_ham=20}
|> Map.add "chute" { in_spam=0; in_ham=3}
|> Map.add "chyp" { in_spam=0; in_ham=4}
|> Map.add "cia" { in_spam=0; in_ham=5}
|> Map.add "ciao" { in_spam=0; in_ham=3}
|> Map.add "ciaran" { in_spam=0; in_ham=4}
|> Map.add "cid" { in_spam=6; in_ham=13}
|> Map.add "cif" { in_spam=1; in_ham=3}
|> Map.add "cigarette" { in_spam=1; in_ham=2}
|> Map.add "cigarettes" { in_spam=10; in_ham=2}
|> Map.add "cindy" { in_spam=0; in_ham=17}
|> Map.add "cir" { in_spam=0; in_ham=4}
|> Map.add "circle" { in_spam=1; in_ham=6}
|> Map.add "circles" { in_spam=0; in_ham=10}
|> Map.add "circuits" { in_spam=0; in_ham=3}
|> Map.add "circulating" { in_spam=0; in_ham=3}
|> Map.add "circumstance" { in_spam=2; in_ham=3}
|> Map.add "cisco" { in_spam=0; in_ham=7}
|> Map.add "cite" { in_spam=0; in_ham=3}
|> Map.add "cited" { in_spam=1; in_ham=13}
|> Map.add "cites" { in_spam=0; in_ham=4}
|> Map.add "cities" { in_spam=2; in_ham=16}
|> Map.add "citing" { in_spam=0; in_ham=4}
|> Map.add "citizen" { in_spam=5; in_ham=6}
|> Map.add "citizens" { in_spam=7; in_ham=13}
|> Map.add "citizenship" { in_spam=1; in_ham=2}
|> Map.add "city" { in_spam=51; in_ham=44}
|> Map.add "city's" { in_spam=0; in_ham=6}
|> Map.add "civic" { in_spam=0; in_ham=3}
|> Map.add "civics" { in_spam=0; in_ham=3}
|> Map.add "civil" { in_spam=9; in_ham=19}
|> Map.add "civilian" { in_spam=1; in_ham=7}
|> Map.add "civilians" { in_spam=0; in_ham=3}
|> Map.add "civilization" { in_spam=1; in_ham=10}
|> Map.add "civilized" { in_spam=1; in_ham=2}
|> Map.add "cjw" { in_spam=1; in_ham=2}
|> Map.add "cked" { in_spam=0; in_ham=3}
|> Map.add "claim" { in_spam=27; in_ham=52}
|> Map.add "claimed" { in_spam=2; in_ham=20}
|> Map.add "claiming" { in_spam=4; in_ham=5}
|> Map.add "claims" { in_spam=13; in_ham=25}
|> Map.add "clamp" { in_spam=1; in_ham=2}
|> Map.add "clara" { in_spam=2; in_ham=2}
|> Map.add "clarified" { in_spam=0; in_ham=4}
|> Map.add "clarify" { in_spam=0; in_ham=9}
|> Map.add "clark" { in_spam=0; in_ham=9}
|> Map.add "class" { in_spam=35; in_ham=38}
|> Map.add "classes" { in_spam=3; in_ham=13}
|> Map.add "classic" { in_spam=1; in_ham=13}
|> Map.add "classical" { in_spam=0; in_ham=4}
|> Map.add "classified" { in_spam=11; in_ham=5}
|> Map.add "classifieds" { in_spam=5; in_ham=0}
|> Map.add "classifier" { in_spam=0; in_ham=25}
|> Map.add "claus" { in_spam=0; in_ham=4}
|> Map.add "clause" { in_spam=0; in_ham=4}
|> Map.add "claw" { in_spam=0; in_ham=4}
|> Map.add "claws" { in_spam=0; in_ham=4}
|> Map.add "clay" { in_spam=0; in_ham=3}
|> Map.add "clean" { in_spam=2; in_ham=95}
|> Map.add "cleaned" { in_spam=1; in_ham=8}
|> Map.add "cleaner" { in_spam=0; in_ham=8}
|> Map.add "cleanest" { in_spam=0; in_ham=6}
|> Map.add "cleaning" { in_spam=2; in_ham=24}
|> Map.add "cleanly" { in_spam=0; in_ham=13}
|> Map.add "cleans" { in_spam=4; in_ham=5}
|> Map.add "cleansweep" { in_spam=5; in_ham=0}
|> Map.add "clear" { in_spam=4; in_ham=71}
|> Map.add "clearance" { in_spam=5; in_ham=2}
|> Map.add "cleared" { in_spam=4; in_ham=6}
|> Map.add "clearer" { in_spam=0; in_ham=14}
|> Map.add "clearing" { in_spam=0; in_ham=7}
|> Map.add "clearly" { in_spam=4; in_ham=39}
|> Map.add "clemens" { in_spam=0; in_ham=10}
|> Map.add "clements" { in_spam=0; in_ham=6}
|> Map.add "clever" { in_spam=3; in_ham=14}
|> Map.add "cleverness" { in_spam=0; in_ham=4}
|> Map.add "click" { in_spam=245; in_ham=425}
|> Map.add "clicked" { in_spam=0; in_ham=3}
|> Map.add "clicking" { in_spam=16; in_ham=4}
|> Map.add "clicks" { in_spam=0; in_ham=5}
|> Map.add "client" { in_spam=16; in_ham=65}
|> Map.add "client's" { in_spam=7; in_ham=2}
|> Map.add "clients" { in_spam=20; in_ham=37}
|> Map.add "cliff" { in_spam=0; in_ham=4}
|> Map.add "cliffs" { in_spam=0; in_ham=4}
|> Map.add "climate" { in_spam=0; in_ham=16}
|> Map.add "climbing" { in_spam=0; in_ham=6}
|> Map.add "cline" { in_spam=0; in_ham=5}
|> Map.add "clinics" { in_spam=0; in_ham=3}
|> Map.add "clink" { in_spam=0; in_ham=3}
|> Map.add "clinton" { in_spam=1; in_ham=9}
|> Map.add "clinton's" { in_spam=0; in_ham=3}
|> Map.add "clipboard" { in_spam=0; in_ham=6}
|> Map.add "clock" { in_spam=1; in_ham=14}
|> Map.add "close" { in_spam=11; in_ham=60}
|> Map.add "closeby" { in_spam=0; in_ham=3}
|> Map.add "closed" { in_spam=2; in_ham=16}
|> Map.add "closely" { in_spam=2; in_ham=13}
|> Map.add "closer" { in_spam=1; in_ham=9}
|> Map.add "closest" { in_spam=0; in_ham=10}
|> Map.add "closing" { in_spam=3; in_ham=4}
|> Map.add "clothes" { in_spam=3; in_ham=14}
|> Map.add "clothing" { in_spam=5; in_ham=6}
|> Map.add "cloud" { in_spam=0; in_ham=4}
|> Map.add "cloudmark" { in_spam=0; in_ham=6}
|> Map.add "clouds" { in_spam=0; in_ham=3}
|> Map.add "clpm" { in_spam=0; in_ham=3}
|> Map.add "club" { in_spam=9; in_ham=13}
|> Map.add "clubs" { in_spam=0; in_ham=3}
|> Map.add "clue" { in_spam=0; in_ham=27}
|> Map.add "clueless" { in_spam=0; in_ham=9}
|> Map.add "clues" { in_spam=0; in_ham=20}
|> Map.add "clunky" { in_spam=0; in_ham=3}
|> Map.add "clutter" { in_spam=0; in_ham=7}
|> Map.add "cmd" { in_spam=0; in_ham=3}
|> Map.add "cmeclax" { in_spam=0; in_ham=4}
|> Map.add "cmp" { in_spam=0; in_ham=4}
|> Map.add "cms" { in_spam=1; in_ham=6}
|> Map.add "cnc" { in_spam=0; in_ham=7}
|> Map.add "cnet" { in_spam=0; in_ham=6}
|> Map.add "cnietonten" { in_spam=7; in_ham=0}
|> Map.add "cnn" { in_spam=6; in_ham=9}
|> Map.add "cnsnews" { in_spam=0; in_ham=5}
|> Map.add "co-founder" { in_spam=0; in_ham=7}
|> Map.add "co-processor" { in_spam=0; in_ham=6}
|> Map.add "co-workers" { in_spam=1; in_ham=3}
|> Map.add "coach" { in_spam=6; in_ham=1}
|> Map.add "coal" { in_spam=0; in_ham=3}
|> Map.add "coalition" { in_spam=1; in_ham=6}
|> Map.add "coalitions" { in_spam=0; in_ham=3}
|> Map.add "coar" { in_spam=0; in_ham=6}
|> Map.add "coase" { in_spam=0; in_ham=3}
|> Map.add "coast" { in_spam=9; in_ham=14}
|> Map.add "coat" { in_spam=0; in_ham=5}
|> Map.add "cocaine" { in_spam=1; in_ham=4}
|> Map.add "code" { in_spam=39; in_ham=185}
|> Map.add "codebase" { in_spam=1; in_ham=6}
|> Map.add "codecs" { in_spam=0; in_ham=7}
|> Map.add "coded" { in_spam=3; in_ham=4}
|> Map.add "coder" { in_spam=0; in_ham=10}
|> Map.add "codes" { in_spam=6; in_ham=7}
|> Map.add "codex" { in_spam=0; in_ham=6}
|> Map.add "coding" { in_spam=0; in_ham=14}
|> Map.add "coentnt" { in_spam=0; in_ham=3}
|> Map.add "coercion" { in_spam=0; in_ham=5}
|> Map.add "coercive" { in_spam=0; in_ham=3}
|> Map.add "coffee" { in_spam=2; in_ham=7}
|> Map.add "coglioni" { in_spam=0; in_ham=6}
|> Map.add "cohen" { in_spam=0; in_ham=6}
|> Map.add "coin" { in_spam=1; in_ham=2}
|> Map.add "coins" { in_spam=1; in_ham=2}
|> Map.add "coke" { in_spam=0; in_ham=3}
|> Map.add "col" { in_spam=1; in_ham=2}
|> Map.add "cold" { in_spam=2; in_ham=21}
|> Map.add "colin" { in_spam=0; in_ham=12}
|> Map.add "collaborate" { in_spam=0; in_ham=6}
|> Map.add "collapse" { in_spam=29; in_ham=18}
|> Map.add "collapsed" { in_spam=0; in_ham=4}
|> Map.add "collar" { in_spam=1; in_ham=3}
|> Map.add "collateral" { in_spam=3; in_ham=4}
|> Map.add "colleague" { in_spam=1; in_ham=4}
|> Map.add "colleagues" { in_spam=12; in_ham=4}
|> Map.add "collect" { in_spam=0; in_ham=16}
|> Map.add "collected" { in_spam=0; in_ham=14}
|> Map.add "collecting" { in_spam=1; in_ham=5}
|> Map.add "collection" { in_spam=6; in_ham=37}
|> Map.add "collections" { in_spam=3; in_ham=10}
|> Map.add "collective" { in_spam=2; in_ham=9}
|> Map.add "collectively" { in_spam=0; in_ham=4}
|> Map.add "college" { in_spam=8; in_ham=34}
|> Map.add "colombia" { in_spam=1; in_ham=2}
|> Map.add "colonial" { in_spam=1; in_ham=2}
|> Map.add "colonies" { in_spam=0; in_ham=5}
|> Map.add "colony" { in_spam=3; in_ham=1}
|> Map.add "colophon" { in_spam=0; in_ham=3}
|> Map.add "color" { in_spam=188; in_ham=16}
|> Map.add "colorado" { in_spam=4; in_ham=4}
|> Map.add "colors" { in_spam=0; in_ham=8}
|> Map.add "colour" { in_spam=0; in_ham=8}
|> Map.add "colours" { in_spam=0; in_ham=5}
|> Map.add "colspan" { in_spam=88; in_ham=2}
|> Map.add "columbia" { in_spam=4; in_ham=3}
|> Map.add "column" { in_spam=1; in_ham=23}
|> Map.add "columnists" { in_spam=0; in_ham=6}
|> Map.add "columns" { in_spam=0; in_ham=13}
|> Map.add "colums" { in_spam=0; in_ham=3}
|> Map.add "com" { in_spam=337; in_ham=1752}
|> Map.add "com'" { in_spam=0; in_ham=7}
|> Map.add "combat" { in_spam=0; in_ham=11}
|> Map.add "combatant" { in_spam=0; in_ham=3}
|> Map.add "combating" { in_spam=0; in_ham=3}
|> Map.add "combination" { in_spam=1; in_ham=15}
|> Map.add "combinations" { in_spam=0; in_ham=4}
|> Map.add "combine" { in_spam=2; in_ham=9}
|> Map.add "combined" { in_spam=20; in_ham=7}
|> Map.add "combines" { in_spam=0; in_ham=10}
|> Map.add "combining" { in_spam=1; in_ham=4}
|> Map.add "combo" { in_spam=0; in_ham=4}
|> Map.add "comcast" { in_spam=0; in_ham=10}
|> Map.add "come" { in_spam=35; in_ham=152}
|> Map.add "comeback" { in_spam=0; in_ham=3}
|> Map.add "comedy" { in_spam=0; in_ham=5}
|> Map.add "comers" { in_spam=0; in_ham=3}
|> Map.add "comes" { in_spam=14; in_ham=67}
|> Map.add "comfort" { in_spam=5; in_ham=3}
|> Map.add "comfortable" { in_spam=7; in_ham=12}
|> Map.add "comfortably" { in_spam=6; in_ham=2}
|> Map.add "comic" { in_spam=1; in_ham=6}
|> Map.add "coming" { in_spam=20; in_ham=52}
|> Map.add "command" { in_spam=1; in_ham=60}
|> Map.add "command-line" { in_spam=0; in_ham=3}
|> Map.add "commander" { in_spam=4; in_ham=3}
|> Map.add "commandment" { in_spam=0; in_ham=3}
|> Map.add "commandments" { in_spam=0; in_ham=4}
|> Map.add "commands" { in_spam=0; in_ham=12}
|> Map.add "commence" { in_spam=3; in_ham=1}
|> Map.add "comment" { in_spam=1; in_ham=110}
|> Map.add "commentary" { in_spam=3; in_ham=3}
|> Map.add "commented" { in_spam=0; in_ham=8}
|> Map.add "commenting" { in_spam=0; in_ham=6}
|> Map.add "comments" { in_spam=10; in_ham=87}
|> Map.add "commerce" { in_spam=8; in_ham=10}
|> Map.add "commercial" { in_spam=17; in_ham=34}
|> Map.add "commission" { in_spam=26; in_ham=6}
|> Map.add "commission's" { in_spam=0; in_ham=3}
|> Map.add "commissioned" { in_spam=4; in_ham=2}
|> Map.add "commissioner" { in_spam=0; in_ham=4}
|> Map.add "commissions" { in_spam=13; in_ham=2}
|> Map.add "commit" { in_spam=0; in_ham=14}
|> Map.add "commitment" { in_spam=8; in_ham=4}
|> Map.add "commitments" { in_spam=2; in_ham=2}
|> Map.add "committed" { in_spam=2; in_ham=10}
|> Map.add "committee" { in_spam=6; in_ham=18}
|> Map.add "committees" { in_spam=0; in_ham=7}
|> Map.add "common" { in_spam=5; in_ham=52}
|> Map.add "commonly" { in_spam=3; in_ham=5}
|> Map.add "communicate" { in_spam=3; in_ham=12}
|> Map.add "communicator" { in_spam=4; in_ham=1}
|> Map.add "communism" { in_spam=0; in_ham=3}
|> Map.add "communist" { in_spam=0; in_ham=3}
|> Map.add "community" { in_spam=14; in_ham=66}
|> Map.add "comp" { in_spam=0; in_ham=6}
|> Map.add "companies" { in_spam=47; in_ham=72}
|> Map.add "companies'" { in_spam=1; in_ham=3}
|> Map.add "companion" { in_spam=1; in_ham=5}
|> Map.add "company" { in_spam=117; in_ham=95}
|> Map.add "company's" { in_spam=5; in_ham=15}
|> Map.add "companydna" { in_spam=0; in_ham=6}
|> Map.add "comparable" { in_spam=1; in_ham=2}
|> Map.add "compare" { in_spam=15; in_ham=6}
|> Map.add "compared" { in_spam=2; in_ham=24}
|> Map.add "comparing" { in_spam=0; in_ham=9}
|> Map.add "comparison" { in_spam=0; in_ham=12}
|> Map.add "comparisons" { in_spam=2; in_ham=2}
|> Map.add "compassion" { in_spam=0; in_ham=4}
|> Map.add "compatible" { in_spam=6; in_ham=13}
|> Map.add "compelled" { in_spam=0; in_ham=5}
|> Map.add "compelling" { in_spam=1; in_ham=23}
|> Map.add "compells" { in_spam=0; in_ham=3}
|> Map.add "compels" { in_spam=0; in_ham=3}
|> Map.add "compensate" { in_spam=5; in_ham=6}
|> Map.add "compensated" { in_spam=1; in_ham=2}
|> Map.add "compensation" { in_spam=6; in_ham=9}
|> Map.add "compete" { in_spam=10; in_ham=6}
|> Map.add "competence" { in_spam=0; in_ham=7}
|> Map.add "competing" { in_spam=1; in_ham=21}
|> Map.add "competition" { in_spam=4; in_ham=23}
|> Map.add "competitive" { in_spam=9; in_ham=8}
|> Map.add "competitor" { in_spam=0; in_ham=4}
|> Map.add "competitors" { in_spam=1; in_ham=7}
|> Map.add "compilation" { in_spam=0; in_ham=7}
|> Map.add "compile" { in_spam=0; in_ham=31}
|> Map.add "compiled" { in_spam=6; in_ham=32}
|> Map.add "compiler" { in_spam=0; in_ham=13}
|> Map.add "complain" { in_spam=1; in_ham=16}
|> Map.add "complained" { in_spam=0; in_ham=11}
|> Map.add "complaining" { in_spam=0; in_ham=10}
|> Map.add "complains" { in_spam=0; in_ham=4}
|> Map.add "complaint" { in_spam=0; in_ham=6}
|> Map.add "complaints" { in_spam=0; in_ham=6}
|> Map.add "complemented" { in_spam=0; in_ham=6}
|> Map.add "complete" { in_spam=28; in_ham=49}
|> Map.add "completed" { in_spam=2; in_ham=8}
|> Map.add "completely" { in_spam=25; in_ham=56}
|> Map.add "completion" { in_spam=2; in_ham=8}
|> Map.add "complex" { in_spam=7; in_ham=19}
|> Map.add "complexity" { in_spam=0; in_ham=7}
|> Map.add "compliance" { in_spam=18; in_ham=1}
|> Map.add "compliant" { in_spam=3; in_ham=2}
|> Map.add "complicated" { in_spam=3; in_ham=17}
|> Map.add "comply" { in_spam=4; in_ham=3}
|> Map.add "component" { in_spam=1; in_ham=20}
|> Map.add "components" { in_spam=2; in_ham=16}
|> Map.add "composition" { in_spam=1; in_ham=8}
|> Map.add "compound" { in_spam=0; in_ham=3}
|> Map.add "comprehend" { in_spam=0; in_ham=4}
|> Map.add "compress" { in_spam=0; in_ham=3}
|> Map.add "compressed" { in_spam=2; in_ham=6}
|> Map.add "compression" { in_spam=1; in_ham=3}
|> Map.add "compromise" { in_spam=0; in_ham=9}
|> Map.add "compromised" { in_spam=0; in_ham=7}
|> Map.add "comps" { in_spam=0; in_ham=4}
|> Map.add "computation" { in_spam=0; in_ham=4}
|> Map.add "compute" { in_spam=0; in_ham=3}
|> Map.add "computed" { in_spam=0; in_ham=4}
|> Map.add "computer" { in_spam=49; in_ham=109}
|> Map.add "computers" { in_spam=4; in_ham=66}
|> Map.add "computing" { in_spam=1; in_ham=26}
|> Map.add "con" { in_spam=0; in_ham=12}
|> Map.add "concealed" { in_spam=6; in_ham=5}
|> Map.add "concealing" { in_spam=4; in_ham=2}
|> Map.add "concede" { in_spam=0; in_ham=3}
|> Map.add "conceived" { in_spam=3; in_ham=7}
|> Map.add "concentrate" { in_spam=1; in_ham=4}
|> Map.add "concentrated" { in_spam=1; in_ham=6}
|> Map.add "concentric" { in_spam=0; in_ham=7}
|> Map.add "concept" { in_spam=3; in_ham=23}
|> Map.add "concepts" { in_spam=4; in_ham=5}
|> Map.add "concern" { in_spam=2; in_ham=25}
|> Map.add "concerned" { in_spam=7; in_ham=18}
|> Map.add "concerning" { in_spam=2; in_ham=8}
|> Map.add "concerns" { in_spam=3; in_ham=17}
|> Map.add "concessions" { in_spam=0; in_ham=5}
|> Map.add "conclude" { in_spam=0; in_ham=8}
|> Map.add "concluded" { in_spam=9; in_ham=12}
|> Map.add "concludes" { in_spam=0; in_ham=4}
|> Map.add "conclusion" { in_spam=10; in_ham=15}
|> Map.add "conclusions" { in_spam=0; in_ham=5}
|> Map.add "concrete" { in_spam=0; in_ham=12}
|> Map.add "condemned" { in_spam=1; in_ham=3}
|> Map.add "condition" { in_spam=4; in_ham=12}
|> Map.add "conditional" { in_spam=1; in_ham=2}
|> Map.add "conditions" { in_spam=9; in_ham=18}
|> Map.add "condone" { in_spam=15; in_ham=2}
|> Map.add "conduct" { in_spam=4; in_ham=7}
|> Map.add "conducted" { in_spam=4; in_ham=4}
|> Map.add "conducting" { in_spam=0; in_ham=5}
|> Map.add "cone" { in_spam=0; in_ham=5}
|> Map.add "conf" { in_spam=3; in_ham=31}
|> Map.add "conference" { in_spam=4; in_ham=37}
|> Map.add "conferences" { in_spam=1; in_ham=9}
|> Map.add "conferencing" { in_spam=4; in_ham=1}
|> Map.add "confessed" { in_spam=1; in_ham=4}
|> Map.add "confided" { in_spam=4; in_ham=7}
|> Map.add "confidence" { in_spam=17; in_ham=8}
|> Map.add "confident" { in_spam=11; in_ham=11}
|> Map.add "confidential" { in_spam=17; in_ham=12}
|> Map.add "config" { in_spam=0; in_ham=38}
|> Map.add "configs" { in_spam=0; in_ham=3}
|> Map.add "configure" { in_spam=0; in_ham=37}
|> Map.add "configured" { in_spam=0; in_ham=14}
|> Map.add "confirm" { in_spam=5; in_ham=16}
|> Map.add "confirmation" { in_spam=7; in_ham=11}
|> Map.add "confirmed" { in_spam=5; in_ham=14}
|> Map.add "confirming" { in_spam=2; in_ham=3}
|> Map.add "confiscate" { in_spam=1; in_ham=2}
|> Map.add "confiscated" { in_spam=5; in_ham=5}
|> Map.add "confiscatory" { in_spam=0; in_ham=3}
|> Map.add "conflict" { in_spam=1; in_ham=15}
|> Map.add "conflicting" { in_spam=0; in_ham=3}
|> Map.add "conflicts" { in_spam=0; in_ham=5}
|> Map.add "conform" { in_spam=1; in_ham=3}
|> Map.add "confront" { in_spam=0; in_ham=3}
|> Map.add "confuse" { in_spam=0; in_ham=9}
|> Map.add "confused" { in_spam=3; in_ham=22}
|> Map.add "confusing" { in_spam=0; in_ham=6}
|> Map.add "confusion" { in_spam=0; in_ham=7}
|> Map.add "congo" { in_spam=10; in_ham=0}
|> Map.add "congregation" { in_spam=0; in_ham=4}
|> Map.add "congress" { in_spam=9; in_ham=52}
|> Map.add "conjunction" { in_spam=3; in_ham=2}
|> Map.add "connect" { in_spam=3; in_ham=18}
|> Map.add "connected" { in_spam=2; in_ham=15}
|> Map.add "connecticut" { in_spam=3; in_ham=7}
|> Map.add "connecting" { in_spam=1; in_ham=11}
|> Map.add "connection" { in_spam=3; in_ham=52}
|> Map.add "connections" { in_spam=1; in_ham=26}
|> Map.add "connectivity" { in_spam=0; in_ham=6}
|> Map.add "connectors" { in_spam=0; in_ham=4}
|> Map.add "connects" { in_spam=4; in_ham=5}
|> Map.add "conquer" { in_spam=0; in_ham=5}
|> Map.add "conry" { in_spam=0; in_ham=3}
|> Map.add "cons" { in_spam=0; in_ham=4}
|> Map.add "consecutive" { in_spam=1; in_ham=9}
|> Map.add "consensus" { in_spam=0; in_ham=7}
|> Map.add "consent" { in_spam=3; in_ham=2}
|> Map.add "consequence" { in_spam=2; in_ham=10}
|> Map.add "consequences" { in_spam=0; in_ham=9}
|> Map.add "consequently" { in_spam=4; in_ham=1}
|> Map.add "conservation" { in_spam=0; in_ham=5}
|> Map.add "conservative" { in_spam=7; in_ham=19}
|> Map.add "consider" { in_spam=8; in_ham=56}
|> Map.add "considerable" { in_spam=0; in_ham=11}
|> Map.add "considerably" { in_spam=0; in_ham=13}
|> Map.add "considered" { in_spam=10; in_ham=27}
|> Map.add "considering" { in_spam=4; in_ham=20}
|> Map.add "consistency" { in_spam=0; in_ham=3}
|> Map.add "consistent" { in_spam=0; in_ham=19}
|> Map.add "consistently" { in_spam=4; in_ham=6}
|> Map.add "consists" { in_spam=0; in_ham=3}
|> Map.add "console" { in_spam=1; in_ham=8}
|> Map.add "consolidate" { in_spam=5; in_ham=1}
|> Map.add "consortium" { in_spam=3; in_ham=1}
|> Map.add "conspiracy" { in_spam=0; in_ham=3}
|> Map.add "const" { in_spam=0; in_ham=3}
|> Map.add "constant" { in_spam=2; in_ham=10}
|> Map.add "constantly" { in_spam=0; in_ham=22}
|> Map.add "constituents" { in_spam=0; in_ham=3}
|> Map.add "constitute" { in_spam=1; in_ham=4}
|> Map.add "constitutes" { in_spam=0; in_ham=5}
|> Map.add "constitution" { in_spam=1; in_ham=6}
|> Map.add "constraints" { in_spam=0; in_ham=6}
|> Map.add "construct" { in_spam=5; in_ham=1}
|> Map.add "constructed" { in_spam=3; in_ham=3}
|> Map.add "constructing" { in_spam=3; in_ham=1}
|> Map.add "construction" { in_spam=2; in_ham=11}
|> Map.add "constructive" { in_spam=1; in_ham=8}
|> Map.add "consult" { in_spam=1; in_ham=7}
|> Map.add "consultancy" { in_spam=0; in_ham=3}
|> Map.add "consultant" { in_spam=7; in_ham=5}
|> Map.add "consultants" { in_spam=0; in_ham=5}
|> Map.add "consultation" { in_spam=9; in_ham=2}
|> Map.add "consulted" { in_spam=0; in_ham=6}
|> Map.add "consulting" { in_spam=5; in_ham=11}
|> Map.add "consumer" { in_spam=13; in_ham=24}
|> Map.add "consumers" { in_spam=2; in_ham=17}
|> Map.add "consumption" { in_spam=0; in_ham=7}
|> Map.add "contact" { in_spam=94; in_ham=39}
|> Map.add "contacted" { in_spam=7; in_ham=9}
|> Map.add "contacting" { in_spam=2; in_ham=4}
|> Map.add "contactname" { in_spam=28; in_ham=0}
|> Map.add "contacts" { in_spam=12; in_ham=9}
|> Map.add "contain" { in_spam=2; in_ham=30}
|> Map.add "contained" { in_spam=10; in_ham=10}
|> Map.add "containing" { in_spam=7; in_ham=13}
|> Map.add "contains" { in_spam=16; in_ham=29}
|> Map.add "contemporary" { in_spam=0; in_ham=4}
|> Map.add "contend" { in_spam=0; in_ham=3}
|> Map.add "content" { in_spam=150; in_ham=74}
|> Map.add "content-type" { in_spam=129; in_ham=28}
|> Map.add "contents" { in_spam=6; in_ham=28}
|> Map.add "contest" { in_spam=5; in_ham=7}
|> Map.add "context" { in_spam=0; in_ham=27}
|> Map.add "continent" { in_spam=0; in_ham=11}
|> Map.add "continental" { in_spam=2; in_ham=5}
|> Map.add "continually" { in_spam=1; in_ham=4}
|> Map.add "continue" { in_spam=19; in_ham=30}
|> Map.add "continued" { in_spam=5; in_ham=11}
|> Map.add "continues" { in_spam=5; in_ham=34}
|> Map.add "continuing" { in_spam=9; in_ham=15}
|> Map.add "continuous" { in_spam=0; in_ham=3}
|> Map.add "continuously" { in_spam=1; in_ham=3}
|> Map.add "contract" { in_spam=12; in_ham=19}
|> Map.add "contracted" { in_spam=5; in_ham=0}
|> Map.add "contractor" { in_spam=5; in_ham=5}
|> Map.add "contracts" { in_spam=21; in_ham=6}
|> Map.add "contractual" { in_spam=1; in_ham=9}
|> Map.add "contrary" { in_spam=1; in_ham=9}
|> Map.add "contrast" { in_spam=0; in_ham=10}
|> Map.add "contribute" { in_spam=1; in_ham=8}
|> Map.add "contributed" { in_spam=0; in_ham=4}
|> Map.add "contributing" { in_spam=0; in_ham=6}
|> Map.add "contribution" { in_spam=1; in_ham=13}
|> Map.add "contributor" { in_spam=0; in_ham=11}
|> Map.add "contributors" { in_spam=0; in_ham=6}
|> Map.add "contrived" { in_spam=0; in_ham=4}
|> Map.add "control" { in_spam=40; in_ham=62}
|> Map.add "controlled" { in_spam=3; in_ham=10}
|> Map.add "controller" { in_spam=1; in_ham=2}
|> Map.add "controllers" { in_spam=0; in_ham=3}
|> Map.add "controlling" { in_spam=0; in_ham=8}
|> Map.add "controls" { in_spam=0; in_ham=15}
|> Map.add "controversy" { in_spam=1; in_ham=2}
|> Map.add "convection" { in_spam=1; in_ham=3}
|> Map.add "convenience" { in_spam=6; in_ham=4}
|> Map.add "convenient" { in_spam=5; in_ham=5}
|> Map.add "conveniently" { in_spam=5; in_ham=1}
|> Map.add "convention" { in_spam=2; in_ham=9}
|> Map.add "conventional" { in_spam=4; in_ham=15}
|> Map.add "conventions" { in_spam=1; in_ham=3}
|> Map.add "convergence" { in_spam=1; in_ham=2}
|> Map.add "conversation" { in_spam=3; in_ham=21}
|> Map.add "conversely" { in_spam=0; in_ham=3}
|> Map.add "conversion" { in_spam=3; in_ham=3}
|> Map.add "convert" { in_spam=0; in_ham=5}
|> Map.add "converted" { in_spam=0; in_ham=5}
|> Map.add "converting" { in_spam=0; in_ham=11}
|> Map.add "converts" { in_spam=0; in_ham=12}
|> Map.add "conviction" { in_spam=2; in_ham=6}
|> Map.add "convince" { in_spam=2; in_ham=10}
|> Map.add "convinced" { in_spam=2; in_ham=14}
|> Map.add "convincing" { in_spam=1; in_ham=6}
|> Map.add "conway" { in_spam=0; in_ham=3}
|> Map.add "cook" { in_spam=1; in_ham=10}
|> Map.add "cooked" { in_spam=0; in_ham=4}
|> Map.add "cooking" { in_spam=2; in_ham=3}
|> Map.add "cooks" { in_spam=1; in_ham=8}
|> Map.add "cool" { in_spam=3; in_ham=50}
|> Map.add "cooler" { in_spam=0; in_ham=3}
|> Map.add "cooling" { in_spam=0; in_ham=6}
|> Map.add "cooper" { in_spam=0; in_ham=3}
|> Map.add "cooperate" { in_spam=3; in_ham=3}
|> Map.add "cooperating" { in_spam=0; in_ham=3}
|> Map.add "cooperation" { in_spam=19; in_ham=3}
|> Map.add "cooperative" { in_spam=1; in_ham=3}
|> Map.add "coordinate" { in_spam=1; in_ham=2}
|> Map.add "coordinated" { in_spam=0; in_ham=4}
|> Map.add "coordination" { in_spam=0; in_ham=3}
|> Map.add "coords" { in_spam=4; in_ham=1}
|> Map.add "copacetic" { in_spam=0; in_ham=3}
|> Map.add "cope" { in_spam=0; in_ham=9}
|> Map.add "copied" { in_spam=1; in_ham=9}
|> Map.add "copies" { in_spam=5; in_ham=15}
|> Map.add "coping" { in_spam=0; in_ham=3}
|> Map.add "copy" { in_spam=29; in_ham=58}
|> Map.add "copying" { in_spam=0; in_ham=16}
|> Map.add "copyright" { in_spam=21; in_ham=100}
|> Map.add "copyrighted" { in_spam=0; in_ham=7}
|> Map.add "copyrights" { in_spam=0; in_ham=5}
|> Map.add "coral" { in_spam=0; in_ham=3}
|> Map.add "cordless" { in_spam=1; in_ham=4}
|> Map.add "core" { in_spam=1; in_ham=32}
|> Map.add "corn" { in_spam=0; in_ham=4}
|> Map.add "corner" { in_spam=9; in_ham=15}
|> Map.add "corp" { in_spam=1; in_ham=4}
|> Map.add "corpora" { in_spam=0; in_ham=14}
|> Map.add "corporate" { in_spam=8; in_ham=29}
|> Map.add "corporation" { in_spam=16; in_ham=58}
|> Map.add "corporations" { in_spam=0; in_ham=15}
|> Map.add "corpus" { in_spam=2; in_ham=38}
|> Map.add "corpuses" { in_spam=0; in_ham=3}
|> Map.add "correct" { in_spam=3; in_ham=46}
|> Map.add "correcting" { in_spam=1; in_ham=2}
|> Map.add "correction" { in_spam=1; in_ham=4}
|> Map.add "correctly" { in_spam=3; in_ham=30}
|> Map.add "correctness" { in_spam=0; in_ham=3}
|> Map.add "correlated" { in_spam=0; in_ham=4}
|> Map.add "correlation" { in_spam=0; in_ham=5}
|> Map.add "correspond" { in_spam=1; in_ham=2}
|> Map.add "corrupt" { in_spam=2; in_ham=10}
|> Map.add "corrupted" { in_spam=0; in_ham=5}
|> Map.add "corruption" { in_spam=1; in_ham=9}
|> Map.add "cory" { in_spam=0; in_ham=5}
|> Map.add "cos" { in_spam=0; in_ham=3}
|> Map.add "cosmetic" { in_spam=1; in_ham=3}
|> Map.add "cost" { in_spam=41; in_ham=57}
|> Map.add "costly" { in_spam=5; in_ham=6}
|> Map.add "costs" { in_spam=18; in_ham=35}
|> Map.add "cote" { in_spam=5; in_ham=0}
|> Map.add "couch" { in_spam=0; in_ham=3}
|> Map.add "cough" { in_spam=0; in_ham=3}
|> Map.add "could" { in_spam=56; in_ham=401}
|> Map.add "couldn't" { in_spam=4; in_ham=54}
|> Map.add "council" { in_spam=2; in_ham=11}
|> Map.add "counsel" { in_spam=3; in_ham=2}
|> Map.add "counseling" { in_spam=3; in_ham=1}
|> Map.add "count" { in_spam=13; in_ham=30}
|> Map.add "countdown" { in_spam=0; in_ham=5}
|> Map.add "counted" { in_spam=0; in_ham=5}
|> Map.add "counter" { in_spam=7; in_ham=5}
|> Map.add "counteract" { in_spam=0; in_ham=3}
|> Map.add "countermoon" { in_spam=0; in_ham=8}
|> Map.add "counterpart" { in_spam=0; in_ham=3}
|> Map.add "counterparts" { in_spam=0; in_ham=7}
|> Map.add "counting" { in_spam=8; in_ham=11}
|> Map.add "countless" { in_spam=1; in_ham=7}
|> Map.add "countries" { in_spam=16; in_ham=40}
|> Map.add "countries'" { in_spam=0; in_ham=4}
|> Map.add "country" { in_spam=55; in_ham=84}
|> Map.add "country's" { in_spam=1; in_ham=10}
|> Map.add "countryside" { in_spam=0; in_ham=3}
|> Map.add "counts" { in_spam=0; in_ham=7}
|> Map.add "county" { in_spam=2; in_ham=4}
|> Map.add "coup" { in_spam=0; in_ham=4}
|> Map.add "couple" { in_spam=4; in_ham=65}
|> Map.add "couples" { in_spam=0; in_ham=6}
|> Map.add "couplings" { in_spam=0; in_ham=4}
|> Map.add "courage" { in_spam=1; in_ham=3}
|> Map.add "courageous" { in_spam=1; in_ham=2}
|> Map.add "courier" { in_spam=7; in_ham=3}
|> Map.add "course" { in_spam=23; in_ham=157}
|> Map.add "courses" { in_spam=1; in_ham=8}
|> Map.add "court" { in_spam=2; in_ham=35}
|> Map.add "courteous" { in_spam=2; in_ham=2}
|> Map.add "courtesy" { in_spam=3; in_ham=3}
|> Map.add "courts" { in_spam=0; in_ham=16}
|> Map.add "cover" { in_spam=13; in_ham=22}
|> Map.add "coverage" { in_spam=11; in_ham=20}
|> Map.add "covered" { in_spam=1; in_ham=16}
|> Map.add "covering" { in_spam=5; in_ham=5}
|> Map.add "covers" { in_spam=1; in_ham=7}
|> Map.add "covert" { in_spam=0; in_ham=3}
|> Map.add "coveted" { in_spam=0; in_ham=4}
|> Map.add "cow" { in_spam=0; in_ham=3}
|> Map.add "cowan" { in_spam=0; in_ham=4}
|> Map.add "coward" { in_spam=0; in_ham=4}
|> Map.add "coy" { in_spam=0; in_ham=4}
|> Map.add "coyote" { in_spam=0; in_ham=3}
|> Map.add "cozying" { in_spam=0; in_ham=4}
|> Map.add "cpan" { in_spam=0; in_ham=9}
|> Map.add "cpio" { in_spam=0; in_ham=3}
|> Map.add "cpp" { in_spam=0; in_ham=4}
|> Map.add "cpu" { in_spam=5; in_ham=9}
|> Map.add "cpus" { in_spam=0; in_ham=4}
|> Map.add "cpx" { in_spam=0; in_ham=3}
|> Map.add "cpxh" { in_spam=0; in_ham=3}
|> Map.add "crack" { in_spam=1; in_ham=10}
|> Map.add "cracked" { in_spam=0; in_ham=9}
|> Map.add "cracker" { in_spam=0; in_ham=5}
|> Map.add "crackers" { in_spam=1; in_ham=3}
|> Map.add "cracking" { in_spam=0; in_ham=13}
|> Map.add "cradle" { in_spam=0; in_ham=3}
|> Map.add "crafted" { in_spam=0; in_ham=4}
|> Map.add "craig" { in_spam=1; in_ham=21}
|> Map.add "crammed" { in_spam=7; in_ham=0}
|> Map.add "cranking" { in_spam=0; in_ham=4}
|> Map.add "crap" { in_spam=0; in_ham=31}
|> Map.add "craphound" { in_spam=0; in_ham=14}
|> Map.add "crappy" { in_spam=0; in_ham=9}
|> Map.add "crash" { in_spam=3; in_ham=7}
|> Map.add "crashed" { in_spam=0; in_ham=3}
|> Map.add "crashes" { in_spam=1; in_ham=5}
|> Map.add "crashing" { in_spam=0; in_ham=7}
|> Map.add "crates" { in_spam=0; in_ham=3}
|> Map.add "crawling" { in_spam=0; in_ham=3}
|> Map.add "crazy" { in_spam=4; in_ham=17}
|> Map.add "cream" { in_spam=0; in_ham=7}
|> Map.add "create" { in_spam=15; in_ham=74}
|> Map.add "created" { in_spam=13; in_ham=53}
|> Map.add "creates" { in_spam=0; in_ham=7}
|> Map.add "creating" { in_spam=1; in_ham=41}
|> Map.add "creation" { in_spam=1; in_ham=11}
|> Map.add "creative" { in_spam=2; in_ham=28}
|> Map.add "creativity" { in_spam=1; in_ham=4}
|> Map.add "creator" { in_spam=4; in_ham=8}
|> Map.add "creators" { in_spam=5; in_ham=6}
|> Map.add "creature" { in_spam=0; in_ham=3}
|> Map.add "credentials" { in_spam=0; in_ham=4}
|> Map.add "credibility" { in_spam=2; in_ham=3}
|> Map.add "credible" { in_spam=2; in_ham=3}
|> Map.add "credit" { in_spam=50; in_ham=23}
|> Map.add "credits" { in_spam=1; in_ham=2}
|> Map.add "creek" { in_spam=1; in_ham=2}
|> Map.add "crew" { in_spam=0; in_ham=9}
|> Map.add "crime" { in_spam=3; in_ham=14}
|> Map.add "crimes" { in_spam=0; in_ham=7}
|> Map.add "criminal" { in_spam=3; in_ham=17}
|> Map.add "criminals" { in_spam=0; in_ham=4}
|> Map.add "crippling" { in_spam=1; in_ham=4}
|> Map.add "crises" { in_spam=1; in_ham=4}
|> Map.add "crisis" { in_spam=2; in_ham=19}
|> Map.add "crispin" { in_spam=0; in_ham=4}
|> Map.add "criteria" { in_spam=6; in_ham=3}
|> Map.add "criterion" { in_spam=0; in_ham=3}
|> Map.add "critical" { in_spam=4; in_ham=35}
|> Map.add "criticism" { in_spam=0; in_ham=5}
|> Map.add "critics" { in_spam=0; in_ham=11}
|> Map.add "cron" { in_spam=0; in_ham=12}
|> Map.add "crook" { in_spam=0; in_ham=8}
|> Map.add "crop" { in_spam=0; in_ham=3}
|> Map.add "crops" { in_spam=0; in_ham=3}
|> Map.add "crosby" { in_spam=0; in_ham=8}
|> Map.add "cross" { in_spam=0; in_ham=12}
|> Map.add "crossed" { in_spam=0; in_ham=3}
|> Map.add "crossing" { in_spam=0; in_ham=5}
|> Map.add "crossover" { in_spam=0; in_ham=3}
|> Map.add "crossword" { in_spam=0; in_ham=4}
|> Map.add "crowd" { in_spam=0; in_ham=8}
|> Map.add "crtc" { in_spam=0; in_ham=3}
|> Map.add "crucial" { in_spam=0; in_ham=19}
|> Map.add "crud" { in_spam=0; in_ham=6}
|> Map.add "cruise" { in_spam=1; in_ham=8}
|> Map.add "crusades" { in_spam=0; in_ham=3}
|> Map.add "crush" { in_spam=0; in_ham=3}
|> Map.add "cry" { in_spam=1; in_ham=8}
|> Map.add "crying" { in_spam=0; in_ham=3}
|> Map.add "crypto" { in_spam=0; in_ham=7}
|> Map.add "cryptography" { in_spam=0; in_ham=7}
|> Map.add "crystal" { in_spam=1; in_ham=4}
|> Map.add "cse" { in_spam=0; in_ham=9}
|> Map.add "css" { in_spam=9; in_ham=9}
|> Map.add "cto" { in_spam=0; in_ham=14}
|> Map.add "ctype" { in_spam=0; in_ham=4}
|> Map.add "cuba" { in_spam=1; in_ham=3}
|> Map.add "cue" { in_spam=0; in_ham=4}
|> Map.add "cuisine" { in_spam=2; in_ham=2}
|> Map.add "cull" { in_spam=0; in_ham=5}
|> Map.add "cult" { in_spam=0; in_ham=5}
|> Map.add "cultural" { in_spam=1; in_ham=13}
|> Map.add "culturally" { in_spam=1; in_ham=2}
|> Map.add "culture" { in_spam=3; in_ham=28}
|> Map.add "cultures" { in_spam=1; in_ham=5}
|> Map.add "cum" { in_spam=4; in_ham=5}
|> Map.add "cumulative" { in_spam=1; in_ham=2}
|> Map.add "cup" { in_spam=1; in_ham=4}
|> Map.add "cur" { in_spam=1; in_ham=15}
|> Map.add "curator" { in_spam=0; in_ham=3}
|> Map.add "cure" { in_spam=0; in_ham=3}
|> Map.add "curious" { in_spam=6; in_ham=14}
|> Map.add "currency" { in_spam=11; in_ham=3}
|> Map.add "current" { in_spam=43; in_ham=140}
|> Map.add "currently" { in_spam=41; in_ham=75}
|> Map.add "curry" { in_spam=0; in_ham=3}
|> Map.add "curse" { in_spam=0; in_ham=9}
|> Map.add "curseen" { in_spam=0; in_ham=3}
|> Map.add "cursor" { in_spam=2; in_ham=4}
|> Map.add "curtail" { in_spam=0; in_ham=4}
|> Map.add "curve" { in_spam=1; in_ham=9}
|> Map.add "custid" { in_spam=7; in_ham=0}
|> Map.add "custody" { in_spam=3; in_ham=3}
|> Map.add "custom" { in_spam=9; in_ham=62}
|> Map.add "custom-built" { in_spam=0; in_ham=3}
|> Map.add "customer" { in_spam=21; in_ham=22}
|> Map.add "customers" { in_spam=26; in_ham=39}
|> Map.add "customizable" { in_spam=1; in_ham=4}
|> Map.add "customize" { in_spam=3; in_ham=3}
|> Map.add "customized" { in_spam=4; in_ham=1}
|> Map.add "cut" { in_spam=18; in_ham=37}
|> Map.add "cut'n'paste" { in_spam=0; in_ham=4}
|> Map.add "cutbuffer" { in_spam=0; in_ham=3}
|> Map.add "cute" { in_spam=0; in_ham=6}
|> Map.add "cuts" { in_spam=1; in_ham=8}
|> Map.add "cutter" { in_spam=0; in_ham=5}
|> Map.add "cutting" { in_spam=6; in_ham=14}
|> Map.add "cvs" { in_spam=0; in_ham=81}
|> Map.add "cvs'ed" { in_spam=0; in_ham=3}
|> Map.add "cvs-serv" { in_spam=0; in_ham=16}
|> Map.add "cvsroot" { in_spam=0; in_ham=18}
|> Map.add "cwg" { in_spam=0; in_ham=35}
|> Map.add "cwg-dated-" { in_spam=0; in_ham=18}
|> Map.add "cwg-exmh" { in_spam=0; in_ham=5}
|> Map.add "cxxabiv" { in_spam=0; in_ham=4}
|> Map.add "cybercrime" { in_spam=0; in_ham=3}
|> Map.add "cycle" { in_spam=8; in_ham=11}
|> Map.add "cycles" { in_spam=0; in_ham=6}
|> Map.add "cyclical" { in_spam=1; in_ham=4}
|> Map.add "cycling" { in_spam=0; in_ham=5}
|> Map.add "cygwin's" { in_spam=0; in_ham=3}
|> Map.add "cynical" { in_spam=1; in_ham=5}
|> Map.add "d'oh" { in_spam=0; in_ham=3}
|> Map.add "dad" { in_spam=2; in_ham=10}
|> Map.add "daemon" { in_spam=0; in_ham=3}
|> Map.add "dag" { in_spam=1; in_ham=4}
|> Map.add "daily" { in_spam=21; in_ham=83}
|> Map.add "daisy" { in_spam=0; in_ham=6}
|> Map.add "dakota" { in_spam=3; in_ham=2}
|> Map.add "dalai" { in_spam=0; in_ham=3}
|> Map.add "dalal" { in_spam=0; in_ham=4}
|> Map.add "dale" { in_spam=0; in_ham=5}
|> Map.add "dalsa" { in_spam=0; in_ham=3}
|> Map.add "damage" { in_spam=1; in_ham=17}
|> Map.add "damaged" { in_spam=2; in_ham=7}
|> Map.add "damian" { in_spam=0; in_ham=3}

