open Bayesian.Database
open BayesianBody_006
let db = db 
|> Map.add "judged" { in_spam=0; in_ham=5}
|> Map.add "judging" { in_spam=0; in_ham=3}
|> Map.add "judgment" { in_spam=0; in_ham=5}
|> Map.add "judgments" { in_spam=0; in_ham=4}
|> Map.add "juice" { in_spam=1; in_ham=3}
|> Map.add "jul" { in_spam=3; in_ham=14}
|> Map.add "julian" { in_spam=0; in_ham=9}
|> Map.add "julius" { in_spam=0; in_ham=6}
|> Map.add "julkista" { in_spam=0; in_ham=4}
|> Map.add "july" { in_spam=3; in_ham=23}
|> Map.add "jump" { in_spam=4; in_ham=23}
|> Map.add "jumped" { in_spam=7; in_ham=3}
|> Map.add "jumping" { in_spam=0; in_ham=3}
|> Map.add "jumpy" { in_spam=0; in_ham=3}
|> Map.add "jun" { in_spam=0; in_ham=4}
|> Map.add "june" { in_spam=5; in_ham=17}
|> Map.add "junior" { in_spam=1; in_ham=5}
|> Map.add "juniper" { in_spam=0; in_ham=6}
|> Map.add "junk" { in_spam=7; in_ham=15}
|> Map.add "jurisdiction" { in_spam=2; in_ham=2}
|> Map.add "jury" { in_spam=0; in_ham=3}
|> Map.add "just" { in_spam=122; in_ham=762}
|> Map.add "justice" { in_spam=1; in_ham=20}
|> Map.add "justified" { in_spam=1; in_ham=2}
|> Map.add "justifies" { in_spam=0; in_ham=3}
|> Map.add "justify" { in_spam=6; in_ham=13}
|> Map.add "justin" { in_spam=0; in_ham=60}
|> Map.add "jwb" { in_spam=0; in_ham=4}
|> Map.add "jwz" { in_spam=0; in_ham=11}
|> Map.add "kabila" { in_spam=8; in_ham=0}
|> Map.add "kamchat" { in_spam=0; in_ham=3}
|> Map.add "kanga" { in_spam=0; in_ham=4}
|> Map.add "kann" { in_spam=0; in_ham=3}
|> Map.add "kannattaa" { in_spam=0; in_ham=4}
|> Map.add "kannattanee" { in_spam=0; in_ham=4}
|> Map.add "kansas" { in_spam=4; in_ham=1}
|> Map.add "karl" { in_spam=0; in_ham=7}
|> Map.add "karnak" { in_spam=0; in_ham=3}
|> Map.add "kassabgi" { in_spam=0; in_ham=6}
|> Map.add "kate" { in_spam=0; in_ham=6}
|> Map.add "kazaa" { in_spam=0; in_ham=6}
|> Map.add "kbps" { in_spam=1; in_ham=2}
|> Map.add "kcet" { in_spam=0; in_ham=3}
|> Map.add "kde" { in_spam=0; in_ham=9}
|> Map.add "keaa" { in_spam=0; in_ham=3}
|> Map.add "kearney" { in_spam=0; in_ham=8}
|> Map.add "keating" { in_spam=0; in_ham=10}
|> Map.add "keeling" { in_spam=0; in_ham=3}
|> Map.add "keen" { in_spam=0; in_ham=7}
|> Map.add "keep" { in_spam=52; in_ham=151}
|> Map.add "keeping" { in_spam=3; in_ham=36}
|> Map.add "keeps" { in_spam=6; in_ham=8}
|> Map.add "keipeng" { in_spam=0; in_ham=3}
|> Map.add "kelly" { in_spam=2; in_ham=12}
|> Map.add "kelly's" { in_spam=0; in_ham=7}
|> Map.add "ken" { in_spam=2; in_ham=19}
|> Map.add "kenneth" { in_spam=0; in_ham=4}
|> Map.add "kenny" { in_spam=0; in_ham=5}
|> Map.add "kentucky" { in_spam=3; in_ham=1}
|> Map.add "kenya" { in_spam=4; in_ham=4}
|> Map.add "kept" { in_spam=7; in_ham=28}
|> Map.add "kernel" { in_spam=0; in_ham=86}
|> Map.add "kernel-" { in_spam=0; in_ham=5}
|> Map.add "kernel-smp" { in_spam=0; in_ham=6}
|> Map.add "kernels" { in_spam=0; in_ham=14}
|> Map.add "ketchup" { in_spam=0; in_ham=3}
|> Map.add "kevin" { in_spam=2; in_ham=31}
|> Map.add "key" { in_spam=28; in_ham=101}
|> Map.add "keyboard" { in_spam=1; in_ham=21}
|> Map.add "keymaster" { in_spam=0; in_ham=4}
|> Map.add "keys" { in_spam=0; in_ham=27}
|> Map.add "keyserver" { in_spam=0; in_ham=10}
|> Map.add "keystroke" { in_spam=0; in_ham=5}
|> Map.add "keyword" { in_spam=2; in_ham=2}
|> Map.add "keywords" { in_spam=5; in_ham=6}
|> Map.add "kfjc" { in_spam=0; in_ham=4}
|> Map.add "khare" { in_spam=0; in_ham=24}
|> Map.add "kick" { in_spam=1; in_ham=17}
|> Map.add "kicked" { in_spam=0; in_ham=4}
|> Map.add "kicks" { in_spam=0; in_ham=3}
|> Map.add "kid" { in_spam=4; in_ham=10}
|> Map.add "kiddie" { in_spam=0; in_ham=4}
|> Map.add "kiddies" { in_spam=0; in_ham=7}
|> Map.add "kidding" { in_spam=5; in_ham=3}
|> Map.add "kids" { in_spam=4; in_ham=35}
|> Map.add "kieran" { in_spam=0; in_ham=6}
|> Map.add "kill" { in_spam=2; in_ham=30}
|> Map.add "killed" { in_spam=5; in_ham=31}
|> Map.add "killer" { in_spam=0; in_ham=16}
|> Map.add "killers" { in_spam=0; in_ham=3}
|> Map.add "killing" { in_spam=1; in_ham=13}
|> Map.add "killings" { in_spam=0; in_ham=3}
|> Map.add "kills" { in_spam=0; in_ham=10}
|> Map.add "kilometres" { in_spam=0; in_ham=4}
|> Map.add "kin" { in_spam=6; in_ham=0}
|> Map.add "kind" { in_spam=15; in_ham=106}
|> Map.add "kinda" { in_spam=0; in_ham=14}
|> Map.add "kindly" { in_spam=21; in_ham=2}
|> Map.add "kinds" { in_spam=0; in_ham=16}
|> Map.add "king" { in_spam=2; in_ham=18}
|> Map.add "king's" { in_spam=1; in_ham=3}
|> Map.add "kingdom" { in_spam=6; in_ham=1}
|> Map.add "kings" { in_spam=0; in_ham=6}
|> Map.add "kinky" { in_spam=0; in_ham=3}
|> Map.add "kiss" { in_spam=2; in_ham=4}
|> Map.add "kit" { in_spam=4; in_ham=5}
|> Map.add "kitchen" { in_spam=0; in_ham=7}
|> Map.add "kitchens" { in_spam=0; in_ham=3}
|> Map.add "kjoeaa" { in_spam=0; in_ham=3}
|> Map.add "klaus" { in_spam=0; in_ham=3}
|> Map.add "kletnieks" { in_spam=0; in_ham=4}
|> Map.add "klez" { in_spam=0; in_ham=3}
|> Map.add "kloiber" { in_spam=0; in_ham=7}
|> Map.add "kluge" { in_spam=0; in_ham=4}
|> Map.add "knew" { in_spam=5; in_ham=35}
|> Map.add "knife" { in_spam=4; in_ham=3}
|> Map.add "knock" { in_spam=0; in_ham=5}
|> Map.add "knocked" { in_spam=0; in_ham=3}
|> Map.add "know" { in_spam=69; in_ham=390}
|> Map.add "knowing" { in_spam=3; in_ham=9}
|> Map.add "knowingly" { in_spam=1; in_ham=2}
|> Map.add "knowledge" { in_spam=22; in_ham=44}
|> Map.add "known" { in_spam=13; in_ham=83}
|> Map.add "knows" { in_spam=2; in_ham=48}
|> Map.add "kode-fu" { in_spam=0; in_ham=3}
|> Map.add "kohn" { in_spam=0; in_ham=4}
|> Map.add "korea" { in_spam=2; in_ham=2}
|> Map.add "kra" { in_spam=0; in_ham=3}
|> Map.add "kragen" { in_spam=0; in_ham=11}
|> Map.add "kre" { in_spam=0; in_ham=37}
|> Map.add "krpm" { in_spam=0; in_ham=4}
|> Map.add "ksymtab" { in_spam=0; in_ham=3}
|> Map.add "ktmeaa" { in_spam=0; in_ham=7}
|> Map.add "kuinka" { in_spam=0; in_ham=4}
|> Map.add "kun" { in_spam=0; in_ham=4}
|> Map.add "kunskap" { in_spam=0; in_ham=9}
|> Map.add "kurt" { in_spam=0; in_ham=3}
|> Map.add "kuznetsov" { in_spam=0; in_ham=6}
|> Map.add "kuznetsov's" { in_spam=0; in_ham=6}
|> Map.add "l-k" { in_spam=0; in_ham=6}
|> Map.add "lab" { in_spam=0; in_ham=6}
|> Map.add "label" { in_spam=1; in_ham=11}
|> Map.add "labeled" { in_spam=1; in_ham=5}
|> Map.add "labelled" { in_spam=4; in_ham=2}
|> Map.add "labels" { in_spam=2; in_ham=5}
|> Map.add "lableisms" { in_spam=0; in_ham=3}
|> Map.add "labor" { in_spam=0; in_ham=18}
|> Map.add "laboratories" { in_spam=0; in_ham=6}
|> Map.add "laboratory" { in_spam=0; in_ham=4}
|> Map.add "labour" { in_spam=1; in_ham=10}
|> Map.add "labs" { in_spam=0; in_ham=3}
|> Map.add "lace" { in_spam=4; in_ham=1}
|> Map.add "lack" { in_spam=4; in_ham=35}
|> Map.add "lacks" { in_spam=0; in_ham=6}
|> Map.add "laden" { in_spam=0; in_ham=6}
|> Map.add "ladies" { in_spam=0; in_ham=5}
|> Map.add "lady" { in_spam=2; in_ham=11}
|> Map.add "lagos" { in_spam=6; in_ham=0}
|> Map.add "laid" { in_spam=0; in_ham=10}
|> Map.add "lain" { in_spam=0; in_ham=4}
|> Map.add "laj" { in_spam=1; in_ham=2}
|> Map.add "lake" { in_spam=3; in_ham=5}
|> Map.add "lame" { in_spam=1; in_ham=13}
|> Map.add "lan" { in_spam=2; in_ham=11}
|> Map.add "lance" { in_spam=0; in_ham=14}
|> Map.add "land" { in_spam=8; in_ham=24}
|> Map.add "landed" { in_spam=2; in_ham=7}
|> Map.add "landmark" { in_spam=1; in_ham=3}
|> Map.add "lands" { in_spam=1; in_ham=4}
|> Map.add "lane" { in_spam=2; in_ham=3}
|> Map.add "lanes" { in_spam=0; in_ham=4}
|> Map.add "lang" { in_spam=16; in_ham=7}
|> Map.add "lange" { in_spam=1; in_ham=3}
|> Map.add "language" { in_spam=6; in_ham=53}
|> Map.add "languages" { in_spam=0; in_ham=24}
|> Map.add "langur" { in_spam=0; in_ham=4}
|> Map.add "langurs" { in_spam=0; in_ham=5}
|> Map.add "lap" { in_spam=0; in_ham=3}
|> Map.add "lappend" { in_spam=0; in_ham=4}
|> Map.add "laptop" { in_spam=1; in_ham=31}
|> Map.add "laptop's" { in_spam=0; in_ham=4}
|> Map.add "laptops" { in_spam=1; in_ham=6}
|> Map.add "large" { in_spam=30; in_ham=110}
|> Map.add "largely" { in_spam=1; in_ham=17}
|> Map.add "larger" { in_spam=16; in_ham=34}
|> Map.add "largest" { in_spam=8; in_ham=46}
|> Map.add "larry" { in_spam=0; in_ham=16}
|> Map.add "las" { in_spam=1; in_ham=3}
|> Map.add "laser" { in_spam=0; in_ham=4}
|> Map.add "last" { in_spam=45; in_ham=224}
|> Map.add "lasted" { in_spam=0; in_ham=5}
|> Map.add "lastest" { in_spam=2; in_ham=2}
|> Map.add "lasting" { in_spam=0; in_ham=3}
|> Map.add "late" { in_spam=27; in_ham=43}
|> Map.add "lately" { in_spam=7; in_ham=11}
|> Map.add "latency" { in_spam=0; in_ham=4}
|> Map.add "later" { in_spam=29; in_ham=73}
|> Map.add "latest" { in_spam=7; in_ham=96}
|> Map.add "lathe" { in_spam=0; in_ham=5}
|> Map.add "latin" { in_spam=0; in_ham=4}
|> Map.add "latitude" { in_spam=0; in_ham=3}
|> Map.add "latter" { in_spam=1; in_ham=21}
|> Map.add "laugh" { in_spam=8; in_ham=11}
|> Map.add "laughed" { in_spam=3; in_ham=5}
|> Map.add "laughing" { in_spam=3; in_ham=12}
|> Map.add "launch" { in_spam=2; in_ham=21}
|> Map.add "launched" { in_spam=8; in_ham=18}
|> Map.add "launches" { in_spam=1; in_ham=2}
|> Map.add "launching" { in_spam=2; in_ham=12}
|> Map.add "laurance" { in_spam=0; in_ham=6}
|> Map.add "laurent" { in_spam=8; in_ham=1}
|> Map.add "law" { in_spam=13; in_ham=76}
|> Map.add "lawful" { in_spam=6; in_ham=4}
|> Map.add "lawfully" { in_spam=1; in_ham=2}
|> Map.add "lawns" { in_spam=0; in_ham=4}
|> Map.add "lawrence" { in_spam=0; in_ham=96}
|> Map.add "laws" { in_spam=21; in_ham=22}
|> Map.add "lawsuit" { in_spam=0; in_ham=3}
|> Map.add "lawsuits" { in_spam=0; in_ham=15}
|> Map.add "lawyer" { in_spam=1; in_ham=12}
|> Map.add "lawyers" { in_spam=2; in_ham=7}
|> Map.add "lax" { in_spam=1; in_ham=2}
|> Map.add "lay" { in_spam=7; in_ham=6}
|> Map.add "layer" { in_spam=3; in_ham=21}
|> Map.add "layered" { in_spam=0; in_ham=4}
|> Map.add "laying" { in_spam=4; in_ham=6}
|> Map.add "layout" { in_spam=0; in_ham=5}
|> Map.add "lazy" { in_spam=2; in_ham=6}
|> Map.add "lbrace" { in_spam=0; in_ham=3}
|> Map.add "lbs" { in_spam=15; in_ham=2}
|> Map.add "lbw" { in_spam=1; in_ham=2}
|> Map.add "lcd" { in_spam=0; in_ham=6}
|> Map.add "ldap" { in_spam=0; in_ham=3}
|> Map.add "leaa" { in_spam=0; in_ham=13}
|> Map.add "lead" { in_spam=6; in_ham=43}
|> Map.add "leader" { in_spam=10; in_ham=22}
|> Map.add "leaders" { in_spam=1; in_ham=19}
|> Map.add "leadership" { in_spam=3; in_ham=15}
|> Map.add "leading" { in_spam=7; in_ham=23}
|> Map.add "leading-edge" { in_spam=0; in_ham=6}
|> Map.add "leads" { in_spam=6; in_ham=13}
|> Map.add "league" { in_spam=0; in_ham=8}
|> Map.add "leak" { in_spam=0; in_ham=5}
|> Map.add "lean" { in_spam=4; in_ham=3}
|> Map.add "leaner" { in_spam=0; in_ham=3}
|> Map.add "leaning" { in_spam=0; in_ham=3}
|> Map.add "learn" { in_spam=35; in_ham=54}
|> Map.add "learned" { in_spam=6; in_ham=19}
|> Map.add "learning" { in_spam=7; in_ham=13}
|> Map.add "lease" { in_spam=4; in_ham=2}
|> Map.add "leasing" { in_spam=4; in_ham=1}
|> Map.add "least" { in_spam=24; in_ham=158}
|> Map.add "leather" { in_spam=0; in_ham=6}
|> Map.add "leave" { in_spam=15; in_ham=60}
|> Map.add "leaves" { in_spam=0; in_ham=6}
|> Map.add "leaving" { in_spam=4; in_ham=28}
|> Map.add "leblanc" { in_spam=0; in_ham=4}
|> Map.add "lebowsky" { in_spam=0; in_ham=3}
|> Map.add "lecture" { in_spam=1; in_ham=2}
|> Map.add "led" { in_spam=2; in_ham=35}
|> Map.add "lee" { in_spam=7; in_ham=5}
|> Map.add "leeds" { in_spam=0; in_ham=3}
|> Map.add "left" { in_spam=81; in_ham=90}
|> Map.add "leftist" { in_spam=0; in_ham=4}
|> Map.add "leftmargin" { in_spam=21; in_ham=0}
|> Map.add "leg" { in_spam=1; in_ham=6}
|> Map.add "legacy" { in_spam=1; in_ham=7}
|> Map.add "legal" { in_spam=63; in_ham=57}
|> Map.add "legality" { in_spam=8; in_ham=2}
|> Map.add "legally" { in_spam=17; in_ham=11}
|> Map.add "legendary" { in_spam=0; in_ham=7}
|> Map.add "legislation" { in_spam=2; in_ham=6}
|> Map.add "legislative" { in_spam=1; in_ham=3}
|> Map.add "legit" { in_spam=0; in_ham=10}
|> Map.add "legitimacy" { in_spam=0; in_ham=3}
|> Map.add "legitimate" { in_spam=9; in_ham=13}
|> Map.add "legs" { in_spam=0; in_ham=11}
|> Map.add "leitl" { in_spam=0; in_ham=15}
|> Map.add "lemann" { in_spam=0; in_ham=3}
|> Map.add "len" { in_spam=0; in_ham=5}
|> Map.add "lend" { in_spam=1; in_ham=3}
|> Map.add "lenders" { in_spam=13; in_ham=0}
|> Map.add "length" { in_spam=4; in_ham=16}
|> Map.add "lengthy" { in_spam=0; in_ham=5}
|> Map.add "lens" { in_spam=0; in_ham=3}
|> Map.add "lenses" { in_spam=0; in_ham=4}
|> Map.add "lentz" { in_spam=0; in_ham=4}
|> Map.add "leone" { in_spam=5; in_ham=0}
|> Map.add "ler" { in_spam=3; in_ham=2}
|> Map.add "lerctr" { in_spam=2; in_ham=2}
|> Map.add "les" { in_spam=2; in_ham=6}
|> Map.add "leslie" { in_spam=0; in_ham=3}
|> Map.add "less" { in_spam=46; in_ham=159}
|> Map.add "lesser" { in_spam=1; in_ham=4}
|> Map.add "lessig" { in_spam=0; in_ham=4}
|> Map.add "lesson" { in_spam=2; in_ham=5}
|> Map.add "lessons" { in_spam=8; in_ham=2}
|> Map.add "lest" { in_spam=0; in_ham=3}
|> Map.add "let" { in_spam=31; in_ham=123}
|> Map.add "let's" { in_spam=14; in_ham=41}
|> Map.add "letetrs" { in_spam=0; in_ham=3}
|> Map.add "lethal" { in_spam=0; in_ham=5}
|> Map.add "lets" { in_spam=6; in_ham=19}
|> Map.add "letter" { in_spam=24; in_ham=22}
|> Map.add "letters" { in_spam=1; in_ham=14}
|> Map.add "letting" { in_spam=0; in_ham=7}
|> Map.add "level" { in_spam=19; in_ham=63}
|> Map.add "levels" { in_spam=2; in_ham=17}
|> Map.add "leverage" { in_spam=3; in_ham=12}
|> Map.add "leveraging" { in_spam=1; in_ham=6}
|> Map.add "levers" { in_spam=0; in_ham=4}
|> Map.add "levy" { in_spam=0; in_ham=4}
|> Map.add "lewis" { in_spam=0; in_ham=5}
|> Map.add "lexicon" { in_spam=0; in_ham=3}
|> Map.add "liability" { in_spam=1; in_ham=8}
|> Map.add "liable" { in_spam=0; in_ham=8}
|> Map.add "liar" { in_spam=0; in_ham=3}
|> Map.add "lib" { in_spam=0; in_ham=74}
|> Map.add "libaa" { in_spam=0; in_ham=3}
|> Map.add "libasound" { in_spam=0; in_ham=6}
|> Map.add "libaviplay-" { in_spam=0; in_ham=4}
|> Map.add "libdv" { in_spam=0; in_ham=7}
|> Map.add "libdv-devel" { in_spam=0; in_ham=4}
|> Map.add "libel" { in_spam=0; in_ham=3}
|> Map.add "liberal" { in_spam=1; in_ham=22}
|> Map.add "liberalism" { in_spam=0; in_ham=5}
|> Map.add "liberals" { in_spam=0; in_ham=3}
|> Map.add "liberated" { in_spam=0; in_ham=5}
|> Map.add "libertarian" { in_spam=0; in_ham=4}
|> Map.add "libertatem" { in_spam=0; in_ham=9}
|> Map.add "liberties" { in_spam=0; in_ham=5}
|> Map.add "liberty" { in_spam=0; in_ham=12}
|> Map.add "libgcj" { in_spam=0; in_ham=3}
|> Map.add "libglut" { in_spam=0; in_ham=3}
|> Map.add "libido" { in_spam=5; in_ham=0}
|> Map.add "liblit" { in_spam=0; in_ham=5}
|> Map.add "libmad" { in_spam=0; in_ham=3}
|> Map.add "libpq" { in_spam=0; in_ham=3}
|> Map.add "libraries" { in_spam=0; in_ham=30}
|> Map.add "library" { in_spam=2; in_ham=26}
|> Map.add "libs" { in_spam=0; in_ham=6}
|> Map.add "licence" { in_spam=0; in_ham=5}
|> Map.add "licences" { in_spam=0; in_ham=5}
|> Map.add "license" { in_spam=3; in_ham=20}
|> Map.add "licensed" { in_spam=3; in_ham=9}
|> Map.add "licenses" { in_spam=1; in_ham=7}
|> Map.add "licensing" { in_spam=1; in_ham=10}
|> Map.add "lid" { in_spam=1; in_ham=4}
|> Map.add "liddle" { in_spam=0; in_ham=3}
|> Map.add "lie" { in_spam=8; in_ham=11}
|> Map.add "lies" { in_spam=5; in_ham=7}
|> Map.add "lieu" { in_spam=3; in_ham=8}
|> Map.add "lieutenants" { in_spam=0; in_ham=3}
|> Map.add "life" { in_spam=84; in_ham=115}
|> Map.add "lifegem" { in_spam=0; in_ham=4}
|> Map.add "lifeline" { in_spam=2; in_ham=2}
|> Map.add "lifestyle" { in_spam=5; in_ham=5}
|> Map.add "lifetime" { in_spam=12; in_ham=4}
|> Map.add "lift" { in_spam=5; in_ham=9}
|> Map.add "lifted" { in_spam=1; in_ham=7}
|> Map.add "lig" { in_spam=0; in_ham=8}
|> Map.add "light" { in_spam=20; in_ham=35}
|> Map.add "lightly" { in_spam=0; in_ham=3}
|> Map.add "lightning" { in_spam=0; in_ham=3}
|> Map.add "lights" { in_spam=0; in_ham=3}
|> Map.add "lih" { in_spam=0; in_ham=7}
|> Map.add "liikkeelle" { in_spam=0; in_ham=4}
|> Map.add "like" { in_spam=110; in_ham=644}
|> Map.add "liked" { in_spam=4; in_ham=15}
|> Map.add "likelihood" { in_spam=0; in_ham=3}
|> Map.add "likely" { in_spam=5; in_ham=74}
|> Map.add "likes" { in_spam=1; in_ham=12}
|> Map.add "likewise" { in_spam=1; in_ham=5}
|> Map.add "lima" { in_spam=1; in_ham=6}
|> Map.add "limbo" { in_spam=0; in_ham=3}
|> Map.add "limit" { in_spam=16; in_ham=20}
|> Map.add "limitations" { in_spam=3; in_ham=11}
|> Map.add "limited" { in_spam=43; in_ham=33}
|> Map.add "limiting" { in_spam=0; in_ham=4}
|> Map.add "limits" { in_spam=1; in_ham=12}
|> Map.add "limousine" { in_spam=0; in_ham=4}
|> Map.add "lincoln" { in_spam=0; in_ham=3}
|> Map.add "lindex" { in_spam=0; in_ham=5}
|> Map.add "line" { in_spam=65; in_ham=205}
|> Map.add "linear" { in_spam=0; in_ham=4}
|> Map.add "lineno" { in_spam=0; in_ham=4}
|> Map.add "lines" { in_spam=2; in_ham=69}
|> Map.add "lingering" { in_spam=1; in_ham=2}
|> Map.add "link" { in_spam=118; in_ham=174}
|> Map.add "linka" { in_spam=0; in_ham=4}
|> Map.add "linked" { in_spam=0; in_ham=18}
|> Map.add "linking" { in_spam=0; in_ham=8}
|> Map.add "links" { in_spam=14; in_ham=59}
|> Map.add "linksys" { in_spam=0; in_ham=4}
|> Map.add "linux" { in_spam=47; in_ham=310}
|> Map.add "linux-" { in_spam=0; in_ham=3}
|> Map.add "linuxmafia" { in_spam=0; in_ham=5}
|> Map.add "linuxworks" { in_spam=0; in_ham=5}
|> Map.add "lipcon" { in_spam=0; in_ham=6}
|> Map.add "liposuction" { in_spam=0; in_ham=6}
|> Map.add "liquid" { in_spam=1; in_ham=2}
|> Map.add "lirc" { in_spam=0; in_ham=10}
|> Map.add "lisa" { in_spam=0; in_ham=5}
|> Map.add "list" { in_spam=223; in_ham=917}
|> Map.add "list's" { in_spam=1; in_ham=5}
|> Map.add "list-archive" { in_spam=0; in_ham=4}
|> Map.add "list-help" { in_spam=0; in_ham=3}
|> Map.add "list-id" { in_spam=0; in_ham=3}
|> Map.add "list-post" { in_spam=0; in_ham=3}
|> Map.add "listed" { in_spam=18; in_ham=24}
|> Map.add "listen" { in_spam=5; in_ham=18}
|> Map.add "listening" { in_spam=0; in_ham=23}
|> Map.add "listens" { in_spam=0; in_ham=3}
|> Map.add "listinfo" { in_spam=51; in_ham=837}
|> Map.add "listing" { in_spam=6; in_ham=5}
|> Map.add "listings" { in_spam=4; in_ham=1}
|> Map.add "listman" { in_spam=0; in_ham=140}
|> Map.add "listmaster" { in_spam=46; in_ham=92}
|> Map.add "lists" { in_spam=22; in_ham=555}
|> Map.add "lite" { in_spam=0; in_ham=3}
|> Map.add "literacy" { in_spam=0; in_ham=4}
|> Map.add "literally" { in_spam=8; in_ham=17}
|> Map.add "literature" { in_spam=0; in_ham=6}
|> Map.add "litigation" { in_spam=5; in_ham=5}
|> Map.add "little" { in_spam=37; in_ham=126}
|> Map.add "live" { in_spam=33; in_ham=82}
|> Map.add "lived" { in_spam=2; in_ham=11}
|> Map.add "livejournal" { in_spam=0; in_ham=10}
|> Map.add "lives" { in_spam=4; in_ham=36}
|> Map.add "living" { in_spam=16; in_ham=50}
|> Map.add "llc" { in_spam=8; in_ham=8}
|> Map.add "lloyd" { in_spam=0; in_ham=5}
|> Map.add "load" { in_spam=3; in_ham=103}
|> Map.add "loaded" { in_spam=4; in_ham=22}
|> Map.add "loading" { in_spam=0; in_ham=15}
|> Map.add "loads" { in_spam=0; in_ham=8}
|> Map.add "loan" { in_spam=22; in_ham=9}
|> Map.add "loans" { in_spam=19; in_ham=3}
|> Map.add "lobbyists" { in_spam=0; in_ham=4}
|> Map.add "local" { in_spam=17; in_ham=123}
|> Map.add "locale" { in_spam=2; in_ham=12}
|> Map.add "localhost" { in_spam=0; in_ham=10}
|> Map.add "localize" { in_spam=0; in_ham=4}
|> Map.add "locally" { in_spam=1; in_ham=7}
|> Map.add "locals" { in_spam=0; in_ham=5}
|> Map.add "locate" { in_spam=5; in_ham=14}
|> Map.add "located" { in_spam=4; in_ham=12}
|> Map.add "location" { in_spam=9; in_ham=24}
|> Map.add "locations" { in_spam=0; in_ham=7}
|> Map.add "lock" { in_spam=5; in_ham=21}
|> Map.add "locked" { in_spam=6; in_ham=9}
|> Map.add "lockergnome" { in_spam=0; in_ham=3}
|> Map.add "locking" { in_spam=2; in_ham=9}
|> Map.add "lodge" { in_spam=3; in_ham=1}
|> Map.add "lodged" { in_spam=6; in_ham=0}
|> Map.add "log" { in_spam=3; in_ham=144}
|> Map.add "logfile" { in_spam=0; in_ham=4}
|> Map.add "logged" { in_spam=0; in_ham=5}
|> Map.add "logger" { in_spam=0; in_ham=4}
|> Map.add "logging" { in_spam=0; in_ham=6}
|> Map.add "logic" { in_spam=0; in_ham=8}
|> Map.add "logical" { in_spam=4; in_ham=11}
|> Map.add "login" { in_spam=4; in_ham=14}
|> Map.add "logistics" { in_spam=3; in_ham=1}
|> Map.add "logo" { in_spam=23; in_ham=6}
|> Map.add "logs" { in_spam=0; in_ham=13}
|> Map.add "logs-to-c" { in_spam=0; in_ham=3}
|> Map.add "lokaalin" { in_spam=0; in_ham=4}
|> Map.add "lol" { in_spam=0; in_ham=11}
|> Map.add "london" { in_spam=4; in_ham=19}
|> Map.add "lonely" { in_spam=0; in_ham=7}
|> Map.add "long" { in_spam=43; in_ham=192}
|> Map.add "long-range" { in_spam=0; in_ham=4}
|> Map.add "long-term" { in_spam=6; in_ham=21}
|> Map.add "longer" { in_spam=29; in_ham=53}
|> Map.add "longest" { in_spam=1; in_ham=7}
|> Map.add "look" { in_spam=33; in_ham=229}
|> Map.add "looked" { in_spam=6; in_ham=54}
|> Map.add "looking" { in_spam=36; in_ham=118}
|> Map.add "looks" { in_spam=0; in_ham=120}
|> Map.add "lookup" { in_spam=1; in_ham=3}
|> Map.add "looming" { in_spam=0; in_ham=3}
|> Map.add "looney" { in_spam=0; in_ham=9}
|> Map.add "loop" { in_spam=0; in_ham=8}
|> Map.add "loops" { in_spam=0; in_ham=4}
|> Map.add "loose" { in_spam=5; in_ham=12}
|> Map.add "loosely" { in_spam=0; in_ham=3}
|> Map.add "loosing" { in_spam=4; in_ham=1}
|> Map.add "looters" { in_spam=0; in_ham=3}
|> Map.add "lord" { in_spam=0; in_ham=9}
|> Map.add "los" { in_spam=3; in_ham=13}
|> Map.add "lose" { in_spam=37; in_ham=27}
|> Map.add "loses" { in_spam=0; in_ham=7}
|> Map.add "losing" { in_spam=10; in_ham=14}
|> Map.add "loss" { in_spam=23; in_ham=20}
|> Map.add "lost" { in_spam=12; in_ham=64}
|> Map.add "lot" { in_spam=27; in_ham=170}
|> Map.add "lots" { in_spam=4; in_ham=78}
|> Map.add "lotus" { in_spam=3; in_ham=3}
|> Map.add "loud" { in_spam=0; in_ham=7}
|> Map.add "loudly" { in_spam=0; in_ham=3}
|> Map.add "louis" { in_spam=1; in_ham=2}
|> Map.add "louisiana" { in_spam=4; in_ham=1}
|> Map.add "lounge" { in_spam=0; in_ham=3}
|> Map.add "lousy" { in_spam=1; in_ham=2}
|> Map.add "love" { in_spam=13; in_ham=68}
|> Map.add "love-" { in_spam=0; in_ham=6}
|> Map.add "loved" { in_spam=2; in_ham=9}
|> Map.add "lovely" { in_spam=0; in_ham=8}
|> Map.add "lover" { in_spam=3; in_ham=5}
|> Map.add "lovers" { in_spam=2; in_ham=11}
|> Map.add "loves" { in_spam=0; in_ham=7}
|> Map.add "loving" { in_spam=0; in_ham=4}
|> Map.add "lovingly" { in_spam=0; in_ham=4}
|> Map.add "low" { in_spam=54; in_ham=32}
|> Map.add "low-level" { in_spam=0; in_ham=3}
|> Map.add "lower" { in_spam=15; in_ham=35}
|> Map.add "lowering" { in_spam=4; in_ham=3}
|> Map.add "lowest" { in_spam=31; in_ham=5}
|> Map.add "loyal" { in_spam=4; in_ham=2}
|> Map.add "loyalty" { in_spam=1; in_ham=2}
|> Map.add "lreplace" { in_spam=0; in_ham=3}
|> Map.add "lsearch" { in_spam=0; in_ham=4}
|> Map.add "lspeedhost" { in_spam=5; in_ham=0}
|> Map.add "lst" { in_spam=1; in_ham=2}
|> Map.add "ltd" { in_spam=11; in_ham=7}
|> Map.add "ltr" { in_spam=1; in_ham=2}
|> Map.add "lucas" { in_spam=0; in_ham=14}
|> Map.add "lucid" { in_spam=0; in_ham=4}
|> Map.add "lucida" { in_spam=6; in_ham=0}
|> Map.add "luck" { in_spam=8; in_ham=23}
|> Map.add "luckily" { in_spam=7; in_ham=1}
|> Map.add "lucky" { in_spam=5; in_ham=12}
|> Map.add "lucrative" { in_spam=2; in_ham=5}
|> Map.add "lude" { in_spam=0; in_ham=4}
|> Map.add "luis" { in_spam=3; in_ham=5}
|> Map.add "lunacy" { in_spam=0; in_ham=3}
|> Map.add "lunch" { in_spam=3; in_ham=8}
|> Map.add "lung" { in_spam=0; in_ham=3}
|> Map.add "lurking" { in_spam=1; in_ham=4}
|> Map.add "lutz" { in_spam=0; in_ham=6}
|> Map.add "luxury" { in_spam=2; in_ham=4}
|> Map.add "lwbtt" { in_spam=0; in_ham=3}
|> Map.add "lying" { in_spam=0; in_ham=6}
|> Map.add "lynch" { in_spam=0; in_ham=3}
|> Map.add "lynch's" { in_spam=0; in_ham=3}
|> Map.add "lynn" { in_spam=0; in_ham=13}
|> Map.add "lynx" { in_spam=0; in_ham=12}
|> Map.add "m-w" { in_spam=0; in_ham=4}
|> Map.add "mac" { in_spam=1; in_ham=35}
|> Map.add "maccarthy" { in_spam=0; in_ham=4}
|> Map.add "mach" { in_spam=0; in_ham=7}
|> Map.add "machine" { in_spam=10; in_ham=71}
|> Map.add "machinery" { in_spam=0; in_ham=4}
|> Map.add "machines" { in_spam=0; in_ham=31}
|> Map.add "macintosh" { in_spam=0; in_ham=8}
|> Map.add "mackenzie" { in_spam=0; in_ham=3}
|> Map.add "macos" { in_spam=0; in_ham=3}
|> Map.add "macosx" { in_spam=0; in_ham=8}
|> Map.add "macros" { in_spam=0; in_ham=5}
|> Map.add "macrumors" { in_spam=0; in_ham=3}
|> Map.add "macs" { in_spam=0; in_ham=3}
|> Map.add "mad" { in_spam=0; in_ham=11}
|> Map.add "madam" { in_spam=17; in_ham=2}
|> Map.add "madden" { in_spam=0; in_ham=3}
|> Map.add "made" { in_spam=69; in_ham=175}
|> Map.add "madison" { in_spam=0; in_ham=3}
|> Map.add "mag" { in_spam=0; in_ham=4}
|> Map.add "magazine" { in_spam=8; in_ham=19}
|> Map.add "magazines" { in_spam=9; in_ham=2}
|> Map.add "magi" { in_spam=0; in_ham=3}
|> Map.add "magic" { in_spam=1; in_ham=15}
|> Map.add "magnesium" { in_spam=0; in_ham=56}
|> Map.add "magnet" { in_spam=0; in_ham=3}
|> Map.add "magnets" { in_spam=0; in_ham=3}
|> Map.add "magnificent" { in_spam=5; in_ham=2}
|> Map.add "magnitude" { in_spam=0; in_ham=22}
|> Map.add "maid" { in_spam=0; in_ham=9}
|> Map.add "mail" { in_spam=80; in_ham=259}
|> Map.add "mailbox" { in_spam=3; in_ham=11}
|> Map.add "mailboxes" { in_spam=0; in_ham=3}
|> Map.add "mailed" { in_spam=10; in_ham=4}
|> Map.add "mailer" { in_spam=9; in_ham=34}
|> Map.add "mailers" { in_spam=0; in_ham=8}
|> Map.add "mailing" { in_spam=92; in_ham=706}
|> Map.add "mailings" { in_spam=64; in_ham=3}
|> Map.add "mailman" { in_spam=46; in_ham=584}
|> Map.add "mails" { in_spam=1; in_ham=12}
|> Map.add "mailscanner" { in_spam=0; in_ham=5}
|> Map.add "mailserver" { in_spam=0; in_ham=3}
|> Map.add "mailto" { in_spam=66; in_ham=209}
|> Map.add "main" { in_spam=15; in_ham=70}
|> Map.add "maine" { in_spam=3; in_ham=2}
|> Map.add "mainly" { in_spam=0; in_ham=16}
|> Map.add "mainstream" { in_spam=2; in_ham=2}
|> Map.add "maintain" { in_spam=6; in_ham=29}
|> Map.add "maintained" { in_spam=5; in_ham=5}
|> Map.add "maintainer" { in_spam=46; in_ham=96}
|> Map.add "maintaining" { in_spam=0; in_ham=10}
|> Map.add "maintains" { in_spam=1; in_ham=12}
|> Map.add "maintenance" { in_spam=2; in_ham=14}
|> Map.add "mais" { in_spam=2; in_ham=2}
|> Map.add "major" { in_spam=27; in_ham=74}
|> Map.add "majordomo" { in_spam=8; in_ham=4}
|> Map.add "majority" { in_spam=9; in_ham=21}
|> Map.add "make" { in_spam=97; in_ham=375}
|> Map.add "make'" { in_spam=0; in_ham=3}
|> Map.add "makedev" { in_spam=0; in_ham=5}
|> Map.add "makefile" { in_spam=0; in_ham=11}
|> Map.add "makemaker" { in_spam=0; in_ham=3}
|> Map.add "maker" { in_spam=4; in_ham=3}
|> Map.add "makers" { in_spam=6; in_ham=10}
|> Map.add "makes" { in_spam=22; in_ham=117}
|> Map.add "making" { in_spam=38; in_ham=118}
|> Map.add "male" { in_spam=13; in_ham=21}
|> Map.add "males" { in_spam=2; in_ham=16}
|> Map.add "malicious" { in_spam=0; in_ham=5}
|> Map.add "malte" { in_spam=0; in_ham=9}
|> Map.add "man" { in_spam=11; in_ham=92}
|> Map.add "man's" { in_spam=1; in_ham=12}
|> Map.add "manage" { in_spam=15; in_ham=29}
|> Map.add "manageable" { in_spam=0; in_ham=5}
|> Map.add "managed" { in_spam=2; in_ham=34}
|> Map.add "management" { in_spam=29; in_ham=43}
|> Map.add "manager" { in_spam=26; in_ham=38}
|> Map.add "managers" { in_spam=5; in_ham=11}
|> Map.add "manages" { in_spam=0; in_ham=9}
|> Map.add "managing" { in_spam=9; in_ham=16}
|> Map.add "manchester" { in_spam=0; in_ham=4}
|> Map.add "mandate" { in_spam=5; in_ham=3}
|> Map.add "mandated" { in_spam=9; in_ham=3}
|> Map.add "mandatory" { in_spam=5; in_ham=2}
|> Map.add "mandrake" { in_spam=0; in_ham=6}
|> Map.add "maneuver" { in_spam=1; in_ham=2}
|> Map.add "mangling" { in_spam=0; in_ham=3}
|> Map.add "manhattan" { in_spam=6; in_ham=5}
|> Map.add "manifest" { in_spam=1; in_ham=6}
|> Map.add "manifesto" { in_spam=0; in_ham=5}
|> Map.add "manifests" { in_spam=0; in_ham=3}
|> Map.add "manner" { in_spam=4; in_ham=17}
|> Map.add "mansions" { in_spam=0; in_ham=4}
|> Map.add "manual" { in_spam=6; in_ham=16}
|> Map.add "manually" { in_spam=2; in_ham=22}
|> Map.add "manufactured" { in_spam=0; in_ham=3}
|> Map.add "manufacturer" { in_spam=3; in_ham=2}
|> Map.add "many" { in_spam=42; in_ham=281}
|> Map.add "map" { in_spam=4; in_ham=20}
|> Map.add "mapped" { in_spam=2; in_ham=4}
|> Map.add "mapping" { in_spam=0; in_ham=4}
|> Map.add "maps" { in_spam=0; in_ham=11}
|> Map.add "mar" { in_spam=0; in_ham=4}
|> Map.add "marathon" { in_spam=0; in_ham=4}
|> Map.add "marc" { in_spam=0; in_ham=5}
|> Map.add "march" { in_spam=6; in_ham=21}
|> Map.add "marcus" { in_spam=0; in_ham=3}
|> Map.add "mare" { in_spam=0; in_ham=3}
|> Map.add "margin" { in_spam=5; in_ham=9}
|> Map.add "margin-left" { in_spam=9; in_ham=2}
|> Map.add "margin-right" { in_spam=10; in_ham=1}
|> Map.add "margin-top" { in_spam=13; in_ham=0}
|> Map.add "marginal" { in_spam=0; in_ham=11}
|> Map.add "marginally" { in_spam=0; in_ham=4}
|> Map.add "marginheight" { in_spam=10; in_ham=0}
|> Map.add "marginwidth" { in_spam=10; in_ham=0}
|> Map.add "mario" { in_spam=0; in_ham=5}
|> Map.add "marital" { in_spam=1; in_ham=4}
|> Map.add "mark" { in_spam=5; in_ham=88}
|> Map.add "marked" { in_spam=12; in_ham=10}
|> Map.add "market" { in_spam=52; in_ham=60}
|> Map.add "market's" { in_spam=0; in_ham=4}
|> Map.add "marketing" { in_spam=68; in_ham=23}
|> Map.add "marketplace" { in_spam=6; in_ham=11}
|> Map.add "markets" { in_spam=4; in_ham=24}
|> Map.add "marking" { in_spam=0; in_ham=6}
|> Map.add "marks" { in_spam=3; in_ham=12}
|> Map.add "markseen" { in_spam=0; in_ham=4}
|> Map.add "markup" { in_spam=0; in_ham=8}
|> Map.add "marla" { in_spam=0; in_ham=4}
|> Map.add "marriage" { in_spam=0; in_ham=16}
|> Map.add "marriage'" { in_spam=0; in_ham=3}
|> Map.add "marriages" { in_spam=0; in_ham=4}
|> Map.add "married" { in_spam=0; in_ham=12}
|> Map.add "marry" { in_spam=0; in_ham=12}
|> Map.add "marryat" { in_spam=0; in_ham=3}
|> Map.add "marrying" { in_spam=0; in_ham=11}
|> Map.add "marshall" { in_spam=2; in_ham=11}
|> Map.add "marshalling" { in_spam=0; in_ham=3}
|> Map.add "marta" { in_spam=0; in_ham=3}
|> Map.add "martin" { in_spam=2; in_ham=17}
|> Map.add "marvelous" { in_spam=1; in_ham=3}
|> Map.add "marx" { in_spam=0; in_ham=4}
|> Map.add "maryland" { in_spam=3; in_ham=2}
|> Map.add "mask" { in_spam=3; in_ham=3}
|> Map.add "masnick" { in_spam=0; in_ham=5}
|> Map.add "mason" { in_spam=0; in_ham=48}
|> Map.add "mass" { in_spam=8; in_ham=31}
|> Map.add "mass-check" { in_spam=0; in_ham=8}
|> Map.add "masse" { in_spam=0; in_ham=3}
|> Map.add "masses" { in_spam=3; in_ham=11}
|> Map.add "massive" { in_spam=1; in_ham=18}
|> Map.add "massively" { in_spam=0; in_ham=3}
|> Map.add "master" { in_spam=7; in_ham=13}
|> Map.add "mastercard" { in_spam=8; in_ham=0}
|> Map.add "masters" { in_spam=0; in_ham=4}
|> Map.add "match" { in_spam=1; in_ham=26}
|> Map.add "matched" { in_spam=0; in_ham=6}
|> Map.add "matches" { in_spam=0; in_ham=11}
|> Map.add "matching" { in_spam=6; in_ham=8}
|> Map.add "mate" { in_spam=2; in_ham=7}
|> Map.add "material" { in_spam=6; in_ham=27}
|> Map.add "materialized" { in_spam=0; in_ham=3}
|> Map.add "materials" { in_spam=12; in_ham=14}
|> Map.add "mates" { in_spam=3; in_ham=2}
|> Map.add "math" { in_spam=2; in_ham=12}
|> Map.add "mathematical" { in_spam=0; in_ham=6}
|> Map.add "mathematics" { in_spam=0; in_ham=28}
|> Map.add "mating" { in_spam=0; in_ham=6}
|> Map.add "matrix" { in_spam=2; in_ham=2}
|> Map.add "matt" { in_spam=1; in_ham=19}
|> Map.add "matter" { in_spam=27; in_ham=65}
|> Map.add "matters" { in_spam=4; in_ham=26}
|> Map.add "matthew" { in_spam=0; in_ham=9}
|> Map.add "matthias" { in_spam=0; in_ham=152}
|> Map.add "mature" { in_spam=2; in_ham=3}
|> Map.add "maturing" { in_spam=0; in_ham=3}
|> Map.add "maturity" { in_spam=3; in_ham=1}
|> Map.add "max" { in_spam=2; in_ham=11}
|> Map.add "maximize" { in_spam=2; in_ham=6}
|> Map.add "maximum" { in_spam=7; in_ham=3}
|> Map.add "maxlength" { in_spam=3; in_ham=1}
|> Map.add "maxline-" { in_spam=0; in_ham=4}
|> Map.add "maxmsg-" { in_spam=0; in_ham=4}
|> Map.add "maxwell" { in_spam=0; in_ham=4}
|> Map.add "may" { in_spam=104; in_ham=297}
|> Map.add "maybe" { in_spam=13; in_ham=171}
|> Map.add "mayor" { in_spam=0; in_ham=6}
|> Map.add "maze" { in_spam=0; in_ham=3}
|> Map.add "mba" { in_spam=1; in_ham=4}
|> Map.add "mbox" { in_spam=0; in_ham=7}
|> Map.add "mboxtest" { in_spam=0; in_ham=6}
|> Map.add "mbps" { in_spam=0; in_ham=11}
|> Map.add "mbs" { in_spam=0; in_ham=3}
|> Map.add "mccarthy" { in_spam=0; in_ham=5}
|> Map.add "mccullars" { in_spam=0; in_ham=3}
|> Map.add "mcgraw" { in_spam=0; in_ham=6}
|> Map.add "mcmasjc" { in_spam=0; in_ham=4}
|> Map.add "mcmaster" { in_spam=0; in_ham=3}
|> Map.add "mcnett" { in_spam=0; in_ham=3}
|> Map.add "mda" { in_spam=0; in_ham=3}
|> Map.add "mdt" { in_spam=0; in_ham=10}
|> Map.add "mea" { in_spam=1; in_ham=2}
|> Map.add "mean" { in_spam=17; in_ham=101}
|> Map.add "meaning" { in_spam=11; in_ham=23}
|> Map.add "meaningful" { in_spam=0; in_ham=10}
|> Map.add "meanings" { in_spam=0; in_ham=6}
|> Map.add "means" { in_spam=19; in_ham=107}
|> Map.add "meant" { in_spam=5; in_ham=30}
|> Map.add "meantime" { in_spam=0; in_ham=9}
|> Map.add "meanwhile" { in_spam=2; in_ham=13}
|> Map.add "measurable" { in_spam=0; in_ham=4}
|> Map.add "measure" { in_spam=2; in_ham=18}
|> Map.add "measured" { in_spam=0; in_ham=11}
|> Map.add "measurement" { in_spam=0; in_ham=5}
|> Map.add "measurements" { in_spam=0; in_ham=6}
|> Map.add "measures" { in_spam=1; in_ham=7}
|> Map.add "measuring" { in_spam=1; in_ham=7}
|> Map.add "meat" { in_spam=1; in_ham=3}
|> Map.add "meccas" { in_spam=0; in_ham=4}
|> Map.add "mechanical" { in_spam=0; in_ham=4}
|> Map.add "mechanism" { in_spam=1; in_ham=13}
|> Map.add "mechanisms" { in_spam=1; in_ham=10}
|> Map.add "med" { in_spam=2; in_ham=3}
|> Map.add "meddle" { in_spam=0; in_ham=4}
|> Map.add "meddling" { in_spam=0; in_ham=3}
|> Map.add "media" { in_spam=14; in_ham=56}
|> Map.add "media's" { in_spam=0; in_ham=4}
|> Map.add "median" { in_spam=0; in_ham=6}
|> Map.add "medical" { in_spam=7; in_ham=6}
|> Map.add "medication" { in_spam=3; in_ham=1}
|> Map.add "medicine" { in_spam=7; in_ham=8}
|> Map.add "medieval" { in_spam=0; in_ham=3}
|> Map.add "medium" { in_spam=17; in_ham=7}
|> Map.add "meet" { in_spam=12; in_ham=41}
|> Map.add "meeting" { in_spam=7; in_ham=20}
|> Map.add "meetings" { in_spam=3; in_ham=16}
|> Map.add "meets" { in_spam=3; in_ham=3}
|> Map.add "meg" { in_spam=0; in_ham=4}
|> Map.add "mega" { in_spam=9; in_ham=0}
|> Map.add "megabucks" { in_spam=1; in_ham=2}
|> Map.add "megs" { in_spam=5; in_ham=0}
|> Map.add "melbourne" { in_spam=0; in_ham=4}
|> Map.add "melting" { in_spam=0; in_ham=7}
|> Map.add "member" { in_spam=44; in_ham=27}
|> Map.add "members" { in_spam=25; in_ham=36}
|> Map.add "membership" { in_spam=15; in_ham=5}
|> Map.add "meme" { in_spam=0; in_ham=3}
|> Map.add "memo" { in_spam=2; in_ham=3}
|> Map.add "memorandum" { in_spam=0; in_ham=4}
|> Map.add "memorial" { in_spam=1; in_ham=8}
|> Map.add "memories" { in_spam=1; in_ham=6}
|> Map.add "memory" { in_spam=8; in_ham=54}
|> Map.add "memri" { in_spam=0; in_ham=3}
|> Map.add "men" { in_spam=9; in_ham=51}
|> Map.add "men's" { in_spam=2; in_ham=2}
|> Map.add "meniang" { in_spam=0; in_ham=3}
|> Map.add "menlo" { in_spam=0; in_ham=7}
|> Map.add "mental" { in_spam=0; in_ham=5}
|> Map.add "mentally" { in_spam=0; in_ham=7}
|> Map.add "mention" { in_spam=4; in_ham=31}
|> Map.add "mentioned" { in_spam=3; in_ham=40}
|> Map.add "mentioning" { in_spam=0; in_ham=11}
|> Map.add "mentions" { in_spam=1; in_ham=3}
|> Map.add "mentor" { in_spam=4; in_ham=1}
|> Map.add "menu" { in_spam=1; in_ham=27}
|> Map.add "menus" { in_spam=0; in_ham=5}
|> Map.add "mercea" { in_spam=0; in_ham=6}
|> Map.add "mercedes" { in_spam=1; in_ham=2}
|> Map.add "merchandise" { in_spam=6; in_ham=1}
|> Map.add "merchant" { in_spam=6; in_ham=3}
|> Map.add "merciless" { in_spam=7; in_ham=0}
|> Map.add "mercury" { in_spam=0; in_ham=5}
|> Map.add "mercurynews" { in_spam=0; in_ham=3}
|> Map.add "mere" { in_spam=1; in_ham=5}
|> Map.add "merely" { in_spam=0; in_ham=17}
|> Map.add "merge" { in_spam=0; in_ham=12}
|> Map.add "merged" { in_spam=0; in_ham=4}
|> Map.add "merit" { in_spam=2; in_ham=8}
|> Map.add "meritocracy" { in_spam=0; in_ham=4}
|> Map.add "mes" { in_spam=1; in_ham=2}
|> Map.add "mess" { in_spam=2; in_ham=13}
|> Map.add "message" { in_spam=118; in_ham=367}
|> Map.add "message's" { in_spam=0; in_ham=8}
|> Map.add "message-----" { in_spam=0; in_ham=119}
|> Map.add "message-id" { in_spam=0; in_ham=34}
|> Map.add "messages" { in_spam=11; in_ham=240}
|> Map.add "messaging" { in_spam=0; in_ham=6}
|> Map.add "messed" { in_spam=0; in_ham=8}
|> Map.add "messenger" { in_spam=0; in_ham=16}
|> Map.add "messing" { in_spam=0; in_ham=6}
|> Map.add "met" { in_spam=7; in_ham=36}
|> Map.add "meta" { in_spam=132; in_ham=8}
|> Map.add "metal" { in_spam=1; in_ham=6}
|> Map.add "metallic" { in_spam=1; in_ham=3}
|> Map.add "meter" { in_spam=0; in_ham=5}
|> Map.add "meters" { in_spam=0; in_ham=4}
|> Map.add "methane" { in_spam=0; in_ham=3}
|> Map.add "method" { in_spam=67; in_ham=63}
|> Map.add "methods" { in_spam=12; in_ham=25}
|> Map.add "metre" { in_spam=0; in_ham=7}
|> Map.add "metrix" { in_spam=0; in_ham=6}
|> Map.add "metro" { in_spam=0; in_ham=14}
|> Map.add "mexico" { in_spam=4; in_ham=4}
|> Map.add "meybee" { in_spam=0; in_ham=3}
|> Map.add "mgm" { in_spam=0; in_ham=3}
|> Map.add "mhpath" { in_spam=0; in_ham=3}
|> Map.add "mhprofile" { in_spam=0; in_ham=8}
|> Map.add "mhreadseqs" { in_spam=0; in_ham=6}
|> Map.add "mhseq" { in_spam=0; in_ham=4}
|> Map.add "mhseqexpand" { in_spam=0; in_ham=8}
|> Map.add "mhz" { in_spam=2; in_ham=9}
|> Map.add "miami" { in_spam=6; in_ham=6}
|> Map.add "mich" { in_spam=1; in_ham=2}
|> Map.add "michael" { in_spam=3; in_ham=48}
|> Map.add "michel" { in_spam=0; in_ham=9}
|> Map.add "michigan" { in_spam=3; in_ham=2}
|> Map.add "micro" { in_spam=0; in_ham=3}
|> Map.add "microscopic" { in_spam=1; in_ham=2}
|> Map.add "microsoft" { in_spam=38; in_ham=49}
|> Map.add "microsoft's" { in_spam=0; in_ham=5}
|> Map.add "microsystems" { in_spam=0; in_ham=3}
|> Map.add "microwave" { in_spam=1; in_ham=4}
|> Map.add "microwaves" { in_spam=0; in_ham=4}
|> Map.add "mid" { in_spam=4; in_ham=4}
|> Map.add "mid-" { in_spam=0; in_ham=5}
|> Map.add "middle" { in_spam=70; in_ham=44}
|> Map.add "middle-aged" { in_spam=0; in_ham=3}
|> Map.add "midi" { in_spam=0; in_ham=4}
|> Map.add "midnight" { in_spam=0; in_ham=4}
|> Map.add "midst" { in_spam=2; in_ham=5}
|> Map.add "might" { in_spam=20; in_ham=214}
|> Map.add "mighty" { in_spam=0; in_ham=3}
|> Map.add "mike" { in_spam=1; in_ham=32}
|> Map.add "mil" { in_spam=3; in_ham=3}
|> Map.add "mildly" { in_spam=0; in_ham=5}
|> Map.add "mile" { in_spam=2; in_ham=11}
|> Map.add "miles" { in_spam=10; in_ham=18}
|> Map.add "militant" { in_spam=0; in_ham=3}
|> Map.add "militarily" { in_spam=0; in_ham=3}
|> Map.add "military" { in_spam=9; in_ham=31}
|> Map.add "mill" { in_spam=0; in_ham=5}
|> Map.add "millennium" { in_spam=2; in_ham=13}
|> Map.add "miller" { in_spam=0; in_ham=5}
|> Map.add "million" { in_spam=84; in_ham=60}
|> Map.add "millionaire" { in_spam=11; in_ham=4}
|> Map.add "millions" { in_spam=30; in_ham=29}
|> Map.add "milter" { in_spam=0; in_ham=8}
|> Map.add "mime" { in_spam=1; in_ham=29}
|> Map.add "mime-version" { in_spam=1; in_ham=9}
|> Map.add "mimedefang" { in_spam=0; in_ham=3}
|> Map.add "min" { in_spam=5; in_ham=4}
|> Map.add "mincount" { in_spam=0; in_ham=4}
|> Map.add "mind" { in_spam=31; in_ham=64}
|> Map.add "minds" { in_spam=0; in_ham=6}
|> Map.add "mine" { in_spam=5; in_ham=24}
|> Map.add "mingle" { in_spam=0; in_ham=4}
|> Map.add "mini-itx" { in_spam=0; in_ham=4}
|> Map.add "minimal" { in_spam=12; in_ham=8}
|> Map.add "minimize" { in_spam=0; in_ham=11}
|> Map.add "minimum" { in_spam=11; in_ham=4}
|> Map.add "mining" { in_spam=1; in_ham=2}
|> Map.add "minister" { in_spam=5; in_ham=12}
|> Map.add "ministers" { in_spam=1; in_ham=4}
|> Map.add "ministry" { in_spam=10; in_ham=0}
|> Map.add "minline" { in_spam=0; in_ham=4}
|> Map.add "minline-" { in_spam=0; in_ham=4}
|> Map.add "minms" { in_spam=0; in_ham=3}
|> Map.add "minmsg" { in_spam=0; in_ham=4}
|> Map.add "minor" { in_spam=1; in_ham=10}
|> Map.add "minority" { in_spam=1; in_ham=8}
|> Map.add "minute" { in_spam=23; in_ham=23}
|> Map.add "minutes" { in_spam=21; in_ham=30}
|> Map.add "mirror" { in_spam=0; in_ham=12}
|> Map.add "mirrored" { in_spam=0; in_ham=3}
|> Map.add "mirrors" { in_spam=1; in_ham=13}
|> Map.add "misc" { in_spam=1; in_ham=15}
|> Map.add "miserable" { in_spam=0; in_ham=6}
|> Map.add "misery" { in_spam=0; in_ham=4}
|> Map.add "misfits" { in_spam=0; in_ham=4}
|> Map.add "mishaps" { in_spam=0; in_ham=3}
|> Map.add "misleading" { in_spam=6; in_ham=3}
|> Map.add "mismatch" { in_spam=0; in_ham=5}
|> Map.add "miss" { in_spam=14; in_ham=23}
|> Map.add "missed" { in_spam=1; in_ham=12}
|> Map.add "missile" { in_spam=1; in_ham=5}
|> Map.add "missiles" { in_spam=1; in_ham=5}
|> Map.add "missing" { in_spam=4; in_ham=46}
|> Map.add "mission" { in_spam=2; in_ham=14}
|> Map.add "missions" { in_spam=3; in_ham=2}
|> Map.add "missouri" { in_spam=3; in_ham=4}
|> Map.add "mist" { in_spam=0; in_ham=4}
|> Map.add "mistake" { in_spam=2; in_ham=25}
|> Map.add "mistakes" { in_spam=11; in_ham=6}
|> Map.add "mit" { in_spam=1; in_ham=26}
|> Map.add "mitchell" { in_spam=7; in_ham=2}
|> Map.add "mithral" { in_spam=0; in_ham=38}
|> Map.add "mitigate" { in_spam=1; in_ham=2}
|> Map.add "mitsubishi" { in_spam=5; in_ham=0}
|> Map.add "mix" { in_spam=2; in_ham=16}
|> Map.add "mixed" { in_spam=2; in_ham=16}
|> Map.add "mixer" { in_spam=0; in_ham=6}
|> Map.add "mixture" { in_spam=0; in_ham=3}
|> Map.add "mjd" { in_spam=0; in_ham=3}
|> Map.add "mld" { in_spam=0; in_ham=9}
|> Map.add "mlm" { in_spam=12; in_ham=0}
|> Map.add "mmkay" { in_spam=0; in_ham=6}
|> Map.add "mmmmmmmmmmm" { in_spam=0; in_ham=3}
|> Map.add "mmode" { in_spam=0; in_ham=4}
|> Map.add "mms" { in_spam=0; in_ham=3}
|> Map.add "mnt" { in_spam=1; in_ham=2}
|> Map.add "mob" { in_spam=0; in_ham=3}
|> Map.add "mobile" { in_spam=8; in_ham=28}
|> Map.add "mobius" { in_spam=0; in_ham=6}
|> Map.add "mobiusvc" { in_spam=0; in_ham=7}
|> Map.add "mobo" { in_spam=0; in_ham=3}
|> Map.add "moc" { in_spam=7; in_ham=0}
|> Map.add "mock" { in_spam=3; in_ham=5}
|> Map.add "mod" { in_spam=0; in_ham=9}
|> Map.add "modalities" { in_spam=10; in_ham=0}
|> Map.add "mode" { in_spam=2; in_ham=56}
|> Map.add "model" { in_spam=2; in_ham=47}
|> Map.add "modeling" { in_spam=1; in_ham=3}
|> Map.add "models" { in_spam=2; in_ham=22}
|> Map.add "modem" { in_spam=1; in_ham=19}
|> Map.add "moderate" { in_spam=3; in_ham=7}
|> Map.add "modern" { in_spam=2; in_ham=34}
|> Map.add "modern-day" { in_spam=0; in_ham=3}
|> Map.add "modes" { in_spam=3; in_ham=9}
|> Map.add "modest" { in_spam=3; in_ham=10}
|> Map.add "modicum" { in_spam=0; in_ham=3}
|> Map.add "modification" { in_spam=0; in_ham=3}
|> Map.add "modified" { in_spam=8; in_ham=39}
|> Map.add "modify" { in_spam=0; in_ham=19}
|> Map.add "modifying" { in_spam=0; in_ham=6}
|> Map.add "modular" { in_spam=1; in_ham=2}
|> Map.add "module" { in_spam=0; in_ham=34}
|> Map.add "modules" { in_spam=0; in_ham=56}
|> Map.add "modulo" { in_spam=0; in_ham=3}
|> Map.add "moen" { in_spam=0; in_ham=6}
|> Map.add "mohr" { in_spam=0; in_ham=11}
|> Map.add "molecular" { in_spam=1; in_ham=3}
|> Map.add "molecules" { in_spam=0; in_ham=5}
|> Map.add "mom" { in_spam=2; in_ham=7}
|> Map.add "moment" { in_spam=21; in_ham=30}
|> Map.add "moments" { in_spam=4; in_ham=7}
|> Map.add "momentum" { in_spam=3; in_ham=1}
|> Map.add "mon" { in_spam=3; in_ham=120}
|> Map.add "moncur" { in_spam=0; in_ham=5}
|> Map.add "monday" { in_spam=1; in_ham=98}
|> Map.add "mondo" { in_spam=0; in_ham=10}
|> Map.add "mondorescue" { in_spam=0; in_ham=6}

