open Bayesian.Database
open BayesianBody_007
let db = db 
|> Map.add "monetary" { in_spam=0; in_ham=6}
|> Map.add "money" { in_spam=116; in_ham=105}
|> Map.add "money-back" { in_spam=5; in_ham=0}
|> Map.add "monger" { in_spam=0; in_ham=3}
|> Map.add "mongers" { in_spam=0; in_ham=5}
|> Map.add "monies" { in_spam=1; in_ham=2}
|> Map.add "monitor" { in_spam=1; in_ham=14}
|> Map.add "monitored" { in_spam=1; in_ham=3}
|> Map.add "monitoring" { in_spam=1; in_ham=8}
|> Map.add "monitors" { in_spam=0; in_ham=9}
|> Map.add "monkey" { in_spam=0; in_ham=12}
|> Map.add "monkeys" { in_spam=0; in_ham=7}
|> Map.add "mono" { in_spam=3; in_ham=1}
|> Map.add "monolithic" { in_spam=0; in_ham=6}
|> Map.add "monopolies" { in_spam=0; in_ham=5}
|> Map.add "monopoly" { in_spam=0; in_ham=8}
|> Map.add "monster" { in_spam=0; in_ham=3}
|> Map.add "monsters" { in_spam=0; in_ham=4}
|> Map.add "montanaro" { in_spam=0; in_ham=9}
|> Map.add "month" { in_spam=54; in_ham=71}
|> Map.add "monthly" { in_spam=16; in_ham=4}
|> Map.add "months" { in_spam=31; in_ham=79}
|> Map.add "mood" { in_spam=2; in_ham=7}
|> Map.add "moon" { in_spam=0; in_ham=6}
|> Map.add "mooney" { in_spam=0; in_ham=3}
|> Map.add "moore" { in_spam=2; in_ham=2}
|> Map.add "moore's" { in_spam=1; in_ham=4}
|> Map.add "moral" { in_spam=1; in_ham=8}
|> Map.add "morally" { in_spam=0; in_ham=4}
|> Map.add "moran" { in_spam=0; in_ham=8}
|> Map.add "morbus" { in_spam=0; in_ham=3}
|> Map.add "mord" { in_spam=0; in_ham=5}
|> Map.add "more" { in_spam=185; in_ham=634}
|> Map.add "more-" { in_spam=0; in_ham=4}
|> Map.add "morelikethis" { in_spam=0; in_ham=5}
|> Map.add "moreover" { in_spam=3; in_ham=4}
|> Map.add "morgan" { in_spam=8; in_ham=2}
|> Map.add "morning" { in_spam=1; in_ham=31}
|> Map.add "morocco" { in_spam=2; in_ham=2}
|> Map.add "morons" { in_spam=0; in_ham=4}
|> Map.add "mort" { in_spam=1; in_ham=2}
|> Map.add "mortgage" { in_spam=33; in_ham=2}
|> Map.add "mortgages" { in_spam=5; in_ham=1}
|> Map.add "moscow" { in_spam=0; in_ham=4}
|> Map.add "mosque" { in_spam=0; in_ham=3}
|> Map.add "most" { in_spam=75; in_ham=315}
|> Map.add "mostly" { in_spam=5; in_ham=49}
|> Map.add "mot" { in_spam=2; in_ham=9}
|> Map.add "mother" { in_spam=11; in_ham=22}
|> Map.add "motherboard" { in_spam=0; in_ham=4}
|> Map.add "mothers" { in_spam=2; in_ham=5}
|> Map.add "motion" { in_spam=2; in_ham=2}
|> Map.add "motivate" { in_spam=0; in_ham=6}
|> Map.add "motivated" { in_spam=19; in_ham=7}
|> Map.add "motivation" { in_spam=1; in_ham=3}
|> Map.add "motivations" { in_spam=0; in_ham=3}
|> Map.add "motivator" { in_spam=0; in_ham=6}
|> Map.add "motives" { in_spam=0; in_ham=6}
|> Map.add "motor" { in_spam=0; in_ham=6}
|> Map.add "motorcade" { in_spam=0; in_ham=3}
|> Map.add "motorola" { in_spam=3; in_ham=2}
|> Map.add "mount" { in_spam=0; in_ham=8}
|> Map.add "mountain" { in_spam=4; in_ham=17}
|> Map.add "mountains" { in_spam=0; in_ham=3}
|> Map.add "mounted" { in_spam=0; in_ham=6}
|> Map.add "mounting" { in_spam=1; in_ham=4}
|> Map.add "mounts" { in_spam=0; in_ham=3}
|> Map.add "mouse" { in_spam=1; in_ham=31}
|> Map.add "mouth" { in_spam=1; in_ham=6}
|> Map.add "movable" { in_spam=0; in_ham=7}
|> Map.add "movabletype" { in_spam=0; in_ham=3}
|> Map.add "move" { in_spam=28; in_ham=76}
|> Map.add "moved" { in_spam=15; in_ham=35}
|> Map.add "movement" { in_spam=2; in_ham=9}
|> Map.add "moves" { in_spam=0; in_ham=12}
|> Map.add "movie" { in_spam=15; in_ham=19}
|> Map.add "movies" { in_spam=12; in_ham=14}
|> Map.add "moving" { in_spam=2; in_ham=26}
|> Map.add "moylan" { in_spam=0; in_ham=5}
|> Map.add "mozambique" { in_spam=2; in_ham=2}
|> Map.add "mozdev" { in_spam=0; in_ham=3}
|> Map.add "mozilla" { in_spam=1; in_ham=22}
|> Map.add "mozilla's" { in_spam=0; in_ham=3}
|> Map.add "mozillazine" { in_spam=0; in_ham=8}
|> Map.add "mpg" { in_spam=0; in_ham=4}
|> Map.add "mph" { in_spam=0; in_ham=7}
|> Map.add "mplayer" { in_spam=0; in_ham=26}
|> Map.add "mplayer-" { in_spam=0; in_ham=3}
|> Map.add "mrs" { in_spam=8; in_ham=5}
|> Map.add "msec" { in_spam=0; in_ham=6}
|> Map.add "msg" { in_spam=0; in_ham=51}
|> Map.add "msgchange" { in_spam=0; in_ham=9}
|> Map.add "msgid" { in_spam=2; in_ham=9}
|> Map.add "msgid-" { in_spam=0; in_ham=4}
|> Map.add "msgids" { in_spam=0; in_ham=8}
|> Map.add "msgs" { in_spam=0; in_ham=36}
|> Map.add "msgshow" { in_spam=0; in_ham=5}
|> Map.add "msgshowproc" { in_spam=0; in_ham=4}
|> Map.add "mshtml" { in_spam=24; in_ham=4}
|> Map.add "msie" { in_spam=0; in_ham=5}
|> Map.add "msm" { in_spam=0; in_ham=3}
|> Map.add "msn" { in_spam=3; in_ham=38}
|> Map.add "msnbc" { in_spam=0; in_ham=8}
|> Map.add "msobodytext" { in_spam=8; in_ham=0}
|> Map.add "msonormal" { in_spam=6; in_ham=0}
|> Map.add "msquadrat" { in_spam=0; in_ham=7}
|> Map.add "mta" { in_spam=0; in_ham=15}
|> Map.add "mtarchives" { in_spam=0; in_ham=3}
|> Map.add "mua" { in_spam=0; in_ham=4}
|> Map.add "much" { in_spam=65; in_ham=320}
|> Map.add "muddied" { in_spam=0; in_ham=7}
|> Map.add "muddled" { in_spam=0; in_ham=3}
|> Map.add "mugabe" { in_spam=4; in_ham=1}
|> Map.add "mughrabi" { in_spam=0; in_ham=4}
|> Map.add "multilateral" { in_spam=0; in_ham=3}
|> Map.add "multilevel" { in_spam=7; in_ham=0}
|> Map.add "multimedia" { in_spam=5; in_ham=4}
|> Map.add "multipart" { in_spam=1; in_ham=11}
|> Map.add "multiplayer" { in_spam=4; in_ham=1}
|> Map.add "multiple" { in_spam=8; in_ham=55}
|> Map.add "multiples" { in_spam=0; in_ham=7}
|> Map.add "multiply" { in_spam=0; in_ham=5}
|> Map.add "multiprocess" { in_spam=0; in_ham=4}
|> Map.add "mum" { in_spam=1; in_ham=2}
|> Map.add "mumbling" { in_spam=0; in_ham=3}
|> Map.add "munnari" { in_spam=0; in_ham=11}
|> Map.add "murcko" { in_spam=0; in_ham=11}
|> Map.add "murder" { in_spam=0; in_ham=13}
|> Map.add "murdered" { in_spam=2; in_ham=3}
|> Map.add "murderers" { in_spam=0; in_ham=3}
|> Map.add "murderous" { in_spam=0; in_ham=5}
|> Map.add "murkworks" { in_spam=0; in_ham=3}
|> Map.add "murphy" { in_spam=0; in_ham=81}
|> Map.add "murray" { in_spam=0; in_ham=3}
|> Map.add "muscle" { in_spam=7; in_ham=5}
|> Map.add "museum" { in_spam=0; in_ham=8}
|> Map.add "music" { in_spam=8; in_ham=50}
|> Map.add "musical" { in_spam=0; in_ham=6}
|> Map.add "muslim" { in_spam=0; in_ham=13}
|> Map.add "muslims" { in_spam=0; in_ham=9}
|> Map.add "musser" { in_spam=0; in_ham=3}
|> Map.add "must" { in_spam=71; in_ham=115}
|> Map.add "muted" { in_spam=0; in_ham=3}
|> Map.add "mutt" { in_spam=0; in_ham=4}
|> Map.add "mutual" { in_spam=9; in_ham=10}
|> Map.add "mvfiaa" { in_spam=0; in_ham=76}
|> Map.add "myjabber" { in_spam=0; in_ham=9}
|> Map.add "myriad" { in_spam=0; in_ham=3}
|> Map.add "myself" { in_spam=12; in_ham=51}
|> Map.add "mysql" { in_spam=1; in_ham=10}
|> Map.add "mysterious" { in_spam=0; in_ham=7}
|> Map.add "mystery" { in_spam=0; in_ham=7}
|> Map.add "myth" { in_spam=0; in_ham=7}
|> Map.add "mytokenizer" { in_spam=0; in_ham=6}
|> Map.add "nah" { in_spam=0; in_ham=7}
|> Map.add "naive" { in_spam=0; in_ham=6}
|> Map.add "naked" { in_spam=3; in_ham=1}
|> Map.add "name" { in_spam=187; in_ham=110}
|> Map.add "named" { in_spam=3; in_ham=33}
|> Map.add "namely" { in_spam=2; in_ham=6}
|> Map.add "names" { in_spam=29; in_ham=34}
|> Map.add "namespace" { in_spam=0; in_ham=3}
|> Map.add "namespaces" { in_spam=0; in_ham=5}
|> Map.add "naming" { in_spam=0; in_ham=5}
|> Map.add "napster" { in_spam=0; in_ham=6}
|> Map.add "narcotics" { in_spam=1; in_ham=2}
|> Map.add "nark" { in_spam=0; in_ham=3}
|> Map.add "narrow" { in_spam=3; in_ham=12}
|> Map.add "nasa" { in_spam=1; in_ham=9}
|> Map.add "nasdaq" { in_spam=0; in_ham=7}
|> Map.add "nasty" { in_spam=2; in_ham=12}
|> Map.add "nat" { in_spam=0; in_ham=6}
|> Map.add "nathan" { in_spam=0; in_ham=3}
|> Map.add "nation" { in_spam=3; in_ham=15}
|> Map.add "nation's" { in_spam=0; in_ham=10}
|> Map.add "national" { in_spam=27; in_ham=56}
|> Map.add "nationalist" { in_spam=0; in_ham=3}
|> Map.add "nationals" { in_spam=1; in_ham=5}
|> Map.add "nations" { in_spam=1; in_ham=24}
|> Map.add "nationwide" { in_spam=11; in_ham=4}
|> Map.add "native" { in_spam=2; in_ham=12}
|> Map.add "nato" { in_spam=1; in_ham=5}
|> Map.add "natural" { in_spam=12; in_ham=16}
|> Map.add "naturally" { in_spam=6; in_ham=9}
|> Map.add "nature" { in_spam=10; in_ham=25}
|> Map.add "natwest" { in_spam=0; in_ham=4}
|> Map.add "navigate" { in_spam=0; in_ham=3}
|> Map.add "navigator" { in_spam=1; in_ham=4}
|> Map.add "navy" { in_spam=3; in_ham=2}
|> Map.add "nazi" { in_spam=0; in_ham=4}
|> Map.add "nbc" { in_spam=6; in_ham=0}
|> Map.add "nbsp" { in_spam=143; in_ham=12}
|> Map.add "ncid" { in_spam=0; in_ham=5}
|> Map.add "nder" { in_spam=0; in_ham=8}
|> Map.add "neale" { in_spam=0; in_ham=13}
|> Map.add "near" { in_spam=8; in_ham=42}
|> Map.add "near-term" { in_spam=0; in_ham=3}
|> Map.add "nearby" { in_spam=0; in_ham=9}
|> Map.add "nearest" { in_spam=2; in_ham=5}
|> Map.add "nearing" { in_spam=0; in_ham=4}
|> Map.add "nearly" { in_spam=2; in_ham=26}
|> Map.add "neary" { in_spam=0; in_ham=6}
|> Map.add "neat" { in_spam=1; in_ham=13}
|> Map.add "neatly" { in_spam=2; in_ham=2}
|> Map.add "nebraska" { in_spam=3; in_ham=1}
|> Map.add "necessarily" { in_spam=0; in_ham=21}
|> Map.add "necessary" { in_spam=10; in_ham=36}
|> Map.add "necessities" { in_spam=3; in_ham=2}
|> Map.add "necessity" { in_spam=2; in_ham=4}
|> Map.add "neck" { in_spam=2; in_ham=3}
|> Map.add "ned" { in_spam=0; in_ham=6}
|> Map.add "need" { in_spam=90; in_ham=281}
|> Map.add "needed" { in_spam=21; in_ham=78}
|> Map.add "neediness" { in_spam=0; in_ham=3}
|> Map.add "needing" { in_spam=0; in_ham=4}
|> Map.add "needlessly" { in_spam=0; in_ham=7}
|> Map.add "needn't" { in_spam=0; in_ham=3}
|> Map.add "needs" { in_spam=19; in_ham=105}
|> Map.add "needy" { in_spam=0; in_ham=6}
|> Map.add "neg" { in_spam=0; in_ham=6}
|> Map.add "negative" { in_spam=6; in_ham=35}
|> Map.add "negatives" { in_spam=1; in_ham=7}
|> Map.add "neglect" { in_spam=2; in_ham=2}
|> Map.add "negligible" { in_spam=0; in_ham=4}
|> Map.add "negotiate" { in_spam=4; in_ham=1}
|> Map.add "negotiated" { in_spam=2; in_ham=3}
|> Map.add "negotiations" { in_spam=0; in_ham=4}
|> Map.add "neighbor" { in_spam=1; in_ham=8}
|> Map.add "neighborhood" { in_spam=2; in_ham=6}
|> Map.add "neighboring" { in_spam=0; in_ham=5}
|> Map.add "neighbors" { in_spam=1; in_ham=5}
|> Map.add "neighbors'" { in_spam=0; in_ham=3}
|> Map.add "neil" { in_spam=0; in_ham=12}
|> Map.add "neither" { in_spam=4; in_ham=23}
|> Map.add "nelson" { in_spam=0; in_ham=4}
|> Map.add "nemesis" { in_spam=0; in_ham=3}
|> Map.add "nervous" { in_spam=0; in_ham=6}
|> Map.add "nessus" { in_spam=0; in_ham=4}
|> Map.add "nest" { in_spam=0; in_ham=3}
|> Map.add "nested" { in_spam=0; in_ham=3}
|> Map.add "net" { in_spam=123; in_ham=867}
|> Map.add "net's" { in_spam=2; in_ham=3}
|> Map.add "netacgi" { in_spam=0; in_ham=3}
|> Map.add "netah" { in_spam=0; in_ham=3}
|> Map.add "netblah" { in_spam=5; in_ham=0}
|> Map.add "netbsd" { in_spam=0; in_ham=4}
|> Map.add "netedge" { in_spam=0; in_ham=6}
|> Map.add "netherlands" { in_spam=3; in_ham=2}
|> Map.add "netli" { in_spam=0; in_ham=3}
|> Map.add "netnoteinc" { in_spam=17; in_ham=0}
|> Map.add "nets" { in_spam=0; in_ham=3}
|> Map.add "netscape" { in_spam=8; in_ham=15}
|> Map.add "network" { in_spam=14; in_ham=150}
|> Map.add "networked" { in_spam=0; in_ham=4}
|> Map.add "networking" { in_spam=2; in_ham=17}
|> Map.add "networks" { in_spam=1; in_ham=39}
|> Map.add "nev" { in_spam=0; in_ham=6}
|> Map.add "nevada" { in_spam=5; in_ham=1}
|> Map.add "never" { in_spam=71; in_ham=188}
|> Map.add "nevertheless" { in_spam=0; in_ham=10}
|> Map.add "nevin" { in_spam=0; in_ham=3}
|> Map.add "new" { in_spam=182; in_ham=528}
|> Map.add "newbie" { in_spam=0; in_ham=3}
|> Map.add "newbies" { in_spam=0; in_ham=4}
|> Map.add "newer" { in_spam=0; in_ham=15}
|> Map.add "newest" { in_spam=4; in_ham=12}
|> Map.add "newly" { in_spam=1; in_ham=8}
|> Map.add "newnamedns" { in_spam=10; in_ham=0}
|> Map.add "news" { in_spam=38; in_ham=225}
|> Map.add "newscientist" { in_spam=0; in_ham=3}
|> Map.add "newsgroups" { in_spam=2; in_ham=3}
|> Map.add "newsisfree" { in_spam=0; in_ham=307}
|> Map.add "newsletter" { in_spam=15; in_ham=38}
|> Map.add "newsletters" { in_spam=10; in_ham=17}
|> Map.add "newspaper" { in_spam=5; in_ham=16}
|> Map.add "newspapers" { in_spam=2; in_ham=6}
|> Map.add "newspeak" { in_spam=0; in_ham=3}
|> Map.add "newyorker" { in_spam=0; in_ham=3}
|> Map.add "next" { in_spam=51; in_ham=172}
|> Map.add "nextpart" { in_spam=1; in_ham=2}
|> Map.add "nfl" { in_spam=0; in_ham=3}
|> Map.add "nfs" { in_spam=0; in_ham=4}
|> Map.add "niall" { in_spam=0; in_ham=4}
|> Map.add "nic" { in_spam=1; in_ham=4}
|> Map.add "nice" { in_spam=7; in_ham=95}
|> Map.add "nice-to-have" { in_spam=0; in_ham=6}
|> Map.add "nicely" { in_spam=1; in_ham=5}
|> Map.add "nicer" { in_spam=0; in_ham=5}
|> Map.add "niche" { in_spam=1; in_ham=2}
|> Map.add "nicholas" { in_spam=0; in_ham=5}
|> Map.add "nick" { in_spam=0; in_ham=7}
|> Map.add "nifty" { in_spam=0; in_ham=7}
|> Map.add "nigeria" { in_spam=17; in_ham=2}
|> Map.add "nigerian" { in_spam=5; in_ham=8}
|> Map.add "nigh" { in_spam=0; in_ham=3}
|> Map.add "night" { in_spam=4; in_ham=48}
|> Map.add "night's" { in_spam=0; in_ham=4}
|> Map.add "nightly" { in_spam=2; in_ham=14}
|> Map.add "nightmare" { in_spam=0; in_ham=9}
|> Map.add "nightrealms" { in_spam=0; in_ham=5}
|> Map.add "nights" { in_spam=3; in_ham=6}
|> Map.add "niku" { in_spam=0; in_ham=6}
|> Map.add "nine" { in_spam=2; in_ham=8}
|> Map.add "nines" { in_spam=0; in_ham=4}
|> Map.add "nintendo" { in_spam=0; in_ham=3}
|> Map.add "nit" { in_spam=0; in_ham=4}
|> Map.add "nits" { in_spam=0; in_ham=3}
|> Map.add "nix" { in_spam=0; in_ham=6}
|> Map.add "nixia" { in_spam=0; in_ham=6}
|> Map.add "njl" { in_spam=0; in_ham=4}
|> Map.add "nkiys" { in_spam=8; in_ham=0}
|> Map.add "nmh" { in_spam=0; in_ham=17}
|> Map.add "nmh-" { in_spam=0; in_ham=3}
|> Map.add "no-cache" { in_spam=3; in_ham=1}
|> Map.add "no-one" { in_spam=1; in_ham=4}
|> Map.add "nobel" { in_spam=0; in_ham=10}
|> Map.add "noble" { in_spam=2; in_ham=2}
|> Map.add "nobody" { in_spam=6; in_ham=53}
|> Map.add "nobody's" { in_spam=0; in_ham=6}
|> Map.add "node" { in_spam=0; in_ham=4}
|> Map.add "nodeps" { in_spam=0; in_ham=4}
|> Map.add "nodes" { in_spam=0; in_ham=8}
|> Map.add "noelle" { in_spam=0; in_ham=4}
|> Map.add "noglider" { in_spam=0; in_ham=3}
|> Map.add "noise" { in_spam=1; in_ham=11}
|> Map.add "nokey" { in_spam=0; in_ham=3}
|> Map.add "nokia" { in_spam=1; in_ham=3}
|> Map.add "nolinkage" { in_spam=0; in_ham=5}
|> Map.add "nomime" { in_spam=0; in_ham=4}
|> Map.add "nominated" { in_spam=4; in_ham=1}
|> Map.add "nomination" { in_spam=0; in_ham=5}
|> Map.add "non" { in_spam=5; in_ham=8}
|> Map.add "non-existent" { in_spam=1; in_ham=4}
|> Map.add "non-friendly" { in_spam=0; in_ham=5}
|> Map.add "non-issue" { in_spam=0; in_ham=6}
|> Map.add "non-root" { in_spam=0; in_ham=5}
|> Map.add "non-silly" { in_spam=0; in_ham=4}
|> Map.add "non-spam" { in_spam=0; in_ham=23}
|> Map.add "non-spammers" { in_spam=0; in_ham=5}
|> Map.add "non-text" { in_spam=0; in_ham=15}
|> Map.add "non-trivial" { in_spam=0; in_ham=3}
|> Map.add "non-volatile" { in_spam=0; in_ham=4}
|> Map.add "nonblocking" { in_spam=0; in_ham=3}
|> Map.add "none" { in_spam=32; in_ham=54}
|> Map.add "nonetheless" { in_spam=0; in_ham=6}
|> Map.add "nonprofit" { in_spam=0; in_ham=5}
|> Map.add "nonsense" { in_spam=0; in_ham=11}
|> Map.add "nonspam" { in_spam=0; in_ham=12}
|> Map.add "nonspamtrap" { in_spam=0; in_ham=3}
|> Map.add "nontrivial" { in_spam=0; in_ham=7}
|> Map.add "noone" { in_spam=0; in_ham=3}
|> Map.add "nope" { in_spam=0; in_ham=13}
|> Map.add "nor" { in_spam=6; in_ham=36}
|> Map.add "norm" { in_spam=0; in_ham=3}
|> Map.add "normal" { in_spam=12; in_ham=64}
|> Map.add "normally" { in_spam=4; in_ham=32}
|> Map.add "norms" { in_spam=0; in_ham=3}
|> Map.add "norte" { in_spam=0; in_ham=42}
|> Map.add "nortel" { in_spam=0; in_ham=7}
|> Map.add "north" { in_spam=10; in_ham=23}
|> Map.add "northeast" { in_spam=0; in_ham=3}
|> Map.add "northeastern" { in_spam=0; in_ham=6}
|> Map.add "northern" { in_spam=2; in_ham=14}
|> Map.add "northwest" { in_spam=2; in_ham=3}
|> Map.add "norton" { in_spam=19; in_ham=5}
|> Map.add "norway" { in_spam=2; in_ham=3}
|> Map.add "nose" { in_spam=0; in_ham=7}
|> Map.add "noshade" { in_spam=23; in_ham=2}
|> Map.add "noshow" { in_spam=0; in_ham=5}
|> Map.add "not" { in_spam=247; in_ham=1245}
|> Map.add "notable" { in_spam=0; in_ham=3}
|> Map.add "notably" { in_spam=0; in_ham=11}
|> Map.add "notch-filter" { in_spam=0; in_ham=3}
|> Map.add "note" { in_spam=35; in_ham=67}
|> Map.add "notebook" { in_spam=0; in_ham=3}
|> Map.add "noted" { in_spam=0; in_ham=21}
|> Map.add "notes" { in_spam=7; in_ham=26}
|> Map.add "nothing" { in_spam=34; in_ham=144}
|> Map.add "notice" { in_spam=41; in_ham=35}
|> Map.add "noticeable" { in_spam=0; in_ham=5}
|> Map.add "noticed" { in_spam=4; in_ham=43}
|> Map.add "notices" { in_spam=4; in_ham=1}
|> Map.add "noticing" { in_spam=0; in_ham=4}
|> Map.add "notification" { in_spam=7; in_ham=6}
|> Map.add "notified" { in_spam=18; in_ham=4}
|> Map.add "notify" { in_spam=5; in_ham=4}
|> Map.add "noting" { in_spam=1; in_ham=10}
|> Map.add "notion" { in_spam=1; in_ham=10}
|> Map.add "notions" { in_spam=1; in_ham=5}
|> Map.add "notorious" { in_spam=1; in_ham=2}
|> Map.add "nov" { in_spam=1; in_ham=5}
|> Map.add "nova" { in_spam=1; in_ham=2}
|> Map.add "novel" { in_spam=0; in_ham=5}
|> Map.add "novelist" { in_spam=0; in_ham=5}
|> Map.add "november" { in_spam=2; in_ham=12}
|> Map.add "now" { in_spam=181; in_ham=572}
|> Map.add "nowadays" { in_spam=0; in_ham=18}
|> Map.add "nowhere" { in_spam=2; in_ham=7}
|> Map.add "nph-parser" { in_spam=0; in_ham=3}
|> Map.add "npr" { in_spam=0; in_ham=7}
|> Map.add "npr's" { in_spam=0; in_ham=4}
|> Map.add "npv" { in_spam=1; in_ham=3}
|> Map.add "nth" { in_spam=1; in_ham=6}
|> Map.add "ntk" { in_spam=1; in_ham=4}
|> Map.add "nuclear" { in_spam=1; in_ham=10}
|> Map.add "nude" { in_spam=1; in_ham=2}
|> Map.add "nugent" { in_spam=0; in_ham=7}
|> Map.add "nuke" { in_spam=1; in_ham=4}
|> Map.add "null" { in_spam=0; in_ham=35}
|> Map.add "number" { in_spam=61; in_ham=157}
|> Map.add "numbered" { in_spam=2; in_ham=3}
|> Map.add "numbers" { in_spam=32; in_ham=54}
|> Map.add "numerous" { in_spam=3; in_ham=16}
|> Map.add "nurse" { in_spam=3; in_ham=1}
|> Map.add "nuts" { in_spam=0; in_ham=4}
|> Map.add "nutshell" { in_spam=0; in_ham=7}
|> Map.add "nvidia" { in_spam=0; in_ham=10}
|> Map.add "nxieaa" { in_spam=0; in_ham=51}
|> Map.add "nyc" { in_spam=0; in_ham=3}
|> Map.add "nytimes" { in_spam=0; in_ham=19}
|> Map.add "nzsjr" { in_spam=0; in_ham=4}
|> Map.add "o'brien" { in_spam=0; in_ham=4}
|> Map.add "o'neill" { in_spam=0; in_ham=3}
|> Map.add "o'reilly" { in_spam=0; in_ham=7}
|> Map.add "obb" { in_spam=0; in_ham=5}
|> Map.add "oberman" { in_spam=0; in_ham=5}
|> Map.add "obidos" { in_spam=1; in_ham=4}
|> Map.add "object" { in_spam=1; in_ham=42}
|> Map.add "objected" { in_spam=0; in_ham=3}
|> Map.add "objections" { in_spam=1; in_ham=8}
|> Map.add "objective" { in_spam=1; in_ham=7}
|> Map.add "objectives" { in_spam=3; in_ham=4}
|> Map.add "objects" { in_spam=0; in_ham=8}
|> Map.add "obligated" { in_spam=1; in_ham=7}
|> Map.add "obligation" { in_spam=27; in_ham=7}
|> Map.add "obligations" { in_spam=5; in_ham=6}
|> Map.add "obliged" { in_spam=3; in_ham=3}
|> Map.add "oblivion" { in_spam=1; in_ham=2}
|> Map.add "oblomovka" { in_spam=0; in_ham=3}
|> Map.add "obquote" { in_spam=0; in_ham=6}
|> Map.add "obscure" { in_spam=0; in_ham=10}
|> Map.add "obscures" { in_spam=0; in_ham=4}
|> Map.add "observation" { in_spam=1; in_ham=7}
|> Map.add "observed" { in_spam=0; in_ham=4}
|> Map.add "observer" { in_spam=0; in_ham=4}
|> Map.add "obsessed" { in_spam=0; in_ham=4}
|> Map.add "obsessive" { in_spam=0; in_ham=4}
|> Map.add "obsessively" { in_spam=0; in_ham=4}
|> Map.add "obsolete" { in_spam=1; in_ham=3}
|> Map.add "obsoletes" { in_spam=0; in_ham=3}
|> Map.add "obstacle" { in_spam=0; in_ham=6}
|> Map.add "obtain" { in_spam=10; in_ham=8}
|> Map.add "obtained" { in_spam=19; in_ham=1}
|> Map.add "obvious" { in_spam=0; in_ham=51}
|> Map.add "obviously" { in_spam=0; in_ham=40}
|> Map.add "occasion" { in_spam=1; in_ham=7}
|> Map.add "occasional" { in_spam=0; in_ham=13}
|> Map.add "occasionally" { in_spam=1; in_ham=10}
|> Map.add "occupation" { in_spam=4; in_ham=6}
|> Map.add "occupied" { in_spam=2; in_ham=2}
|> Map.add "occur" { in_spam=0; in_ham=10}
|> Map.add "occurred" { in_spam=0; in_ham=14}
|> Map.add "occurring" { in_spam=0; in_ham=4}
|> Map.add "occurs" { in_spam=1; in_ham=14}
|> Map.add "ocean" { in_spam=2; in_ham=7}
|> Map.add "oceans" { in_spam=0; in_ham=3}
|> Map.add "oct" { in_spam=2; in_ham=83}
|> Map.add "october" { in_spam=5; in_ham=74}
|> Map.add "ocw" { in_spam=1; in_ham=3}
|> Map.add "odbc" { in_spam=1; in_ham=2}
|> Map.add "odd" { in_spam=0; in_ham=30}
|> Map.add "oddly" { in_spam=0; in_ham=4}
|> Map.add "odds" { in_spam=0; in_ham=12}
|> Map.add "of-course" { in_spam=6; in_ham=0}
|> Map.add "off" { in_spam=40; in_ham=209}
|> Map.add "off'" { in_spam=5; in_ham=0}
|> Map.add "off-line" { in_spam=0; in_ham=4}
|> Map.add "off-topic" { in_spam=0; in_ham=3}
|> Map.add "offence" { in_spam=0; in_ham=3}
|> Map.add "offended" { in_spam=0; in_ham=4}
|> Map.add "offenders" { in_spam=2; in_ham=3}
|> Map.add "offending" { in_spam=0; in_ham=4}
|> Map.add "offense" { in_spam=0; in_ham=7}
|> Map.add "offensive" { in_spam=4; in_ham=10}
|> Map.add "offensively" { in_spam=0; in_ham=4}
|> Map.add "offer" { in_spam=98; in_ham=47}
|> Map.add "offered" { in_spam=7; in_ham=13}
|> Map.add "offering" { in_spam=14; in_ham=16}
|> Map.add "offers" { in_spam=69; in_ham=21}
|> Map.add "office" { in_spam=37; in_ham=51}
|> Map.add "officer" { in_spam=1; in_ham=11}
|> Map.add "officers" { in_spam=1; in_ham=6}
|> Map.add "offices" { in_spam=0; in_ham=15}
|> Map.add "official" { in_spam=6; in_ham=39}
|> Map.add "officially" { in_spam=1; in_ham=11}
|> Map.add "officials" { in_spam=6; in_ham=40}
|> Map.add "offline" { in_spam=0; in_ham=6}
|> Map.add "offload" { in_spam=0; in_ham=6}
|> Map.add "offscreen" { in_spam=0; in_ham=3}
|> Map.add "offset" { in_spam=1; in_ham=2}
|> Map.add "offshore" { in_spam=7; in_ham=1}
|> Map.add "offspring" { in_spam=0; in_ham=13}
|> Map.add "often" { in_spam=8; in_ham=106}
|> Map.add "ogle" { in_spam=0; in_ham=9}
|> Map.add "ohio" { in_spam=4; in_ham=2}
|> Map.add "oid" { in_spam=7; in_ham=0}
|> Map.add "oil" { in_spam=13; in_ham=12}
|> Map.add "ois" { in_spam=1; in_ham=4}
|> Map.add "okay" { in_spam=2; in_ham=26}
|> Map.add "oklahoma" { in_spam=3; in_ham=3}
|> Map.add "ol'" { in_spam=0; in_ham=6}
|> Map.add "old" { in_spam=43; in_ham=254}
|> Map.add "older" { in_spam=5; in_ham=17}
|> Map.add "oldest" { in_spam=0; in_ham=10}
|> Map.add "olen" { in_spam=0; in_ham=4}
|> Map.add "omaha" { in_spam=6; in_ham=0}
|> Map.add "omar" { in_spam=0; in_ham=4}
|> Map.add "omega" { in_spam=0; in_ham=8}
|> Map.add "omni" { in_spam=0; in_ham=3}
|> Map.add "omnibus" { in_spam=0; in_ham=3}
|> Map.add "omniweb" { in_spam=0; in_ham=4}
|> Map.add "on-line" { in_spam=4; in_ham=15}
|> Map.add "once" { in_spam=55; in_ham=222}
|> Map.add "one" { in_spam=164; in_ham=657}
|> Map.add "one's" { in_spam=1; in_ham=14}
|> Map.add "one-time" { in_spam=2; in_ham=2}
|> Map.add "ones" { in_spam=2; in_ham=57}
|> Map.add "oneself" { in_spam=0; in_ham=4}
|> Map.add "ongoing" { in_spam=0; in_ham=6}
|> Map.add "oni" { in_spam=3; in_ham=1}
|> Map.add "online" { in_spam=79; in_ham=70}
|> Map.add "onlinesales" { in_spam=0; in_ham=4}
|> Map.add "onload" { in_spam=6; in_ham=0}
|> Map.add "only" { in_spam=145; in_ham=557}
|> Map.add "onmouseover" { in_spam=5; in_ham=1}
|> Map.add "ontario" { in_spam=2; in_ham=10}
|> Map.add "onto" { in_spam=2; in_ham=19}
|> Map.add "onward" { in_spam=0; in_ham=4}
|> Map.add "oodles" { in_spam=0; in_ham=3}
|> Map.add "oooo" { in_spam=0; in_ham=4}
|> Map.add "oooops" { in_spam=0; in_ham=8}
|> Map.add "ooops" { in_spam=0; in_ham=4}
|> Map.add "oops" { in_spam=3; in_ham=12}
|> Map.add "open" { in_spam=36; in_ham=116}
|> Map.add "openbeatbox" { in_spam=0; in_ham=5}
|> Map.add "opened" { in_spam=8; in_ham=17}
|> Map.add "opening" { in_spam=3; in_ham=11}
|> Map.add "openly" { in_spam=2; in_ham=5}
|> Map.add "openness" { in_spam=0; in_ham=3}
|> Map.add "openoffice" { in_spam=0; in_ham=3}
|> Map.add "opens" { in_spam=1; in_ham=10}
|> Map.add "opensource" { in_spam=0; in_ham=3}
|> Map.add "openssh" { in_spam=0; in_ham=11}
|> Map.add "openssl" { in_spam=0; in_ham=8}
|> Map.add "openssl-" { in_spam=0; in_ham=3}
|> Map.add "opera" { in_spam=0; in_ham=6}
|> Map.add "operate" { in_spam=7; in_ham=15}
|> Map.add "operated" { in_spam=1; in_ham=2}
|> Map.add "operates" { in_spam=0; in_ham=3}
|> Map.add "operating" { in_spam=6; in_ham=29}
|> Map.add "operation" { in_spam=0; in_ham=29}
|> Map.add "operational" { in_spam=1; in_ham=9}
|> Map.add "operations" { in_spam=4; in_ham=16}
|> Map.add "operator" { in_spam=4; in_ham=4}
|> Map.add "operators" { in_spam=1; in_ham=3}
|> Map.add "opinion" { in_spam=6; in_ham=38}
|> Map.add "opinionist" { in_spam=0; in_ham=6}
|> Map.add "opinions" { in_spam=1; in_ham=17}
|> Map.add "opml" { in_spam=0; in_ham=3}
|> Map.add "opponents" { in_spam=0; in_ham=4}
|> Map.add "opportunity" { in_spam=55; in_ham=25}
|> Map.add "oppose" { in_spam=1; in_ham=7}
|> Map.add "opposed" { in_spam=5; in_ham=10}
|> Map.add "opposes" { in_spam=1; in_ham=2}
|> Map.add "opposing" { in_spam=0; in_ham=3}
|> Map.add "opposite" { in_spam=1; in_ham=19}
|> Map.add "opposition" { in_spam=6; in_ham=9}
|> Map.add "oppressed" { in_spam=1; in_ham=2}
|> Map.add "oppression" { in_spam=1; in_ham=3}
|> Map.add "oprah" { in_spam=5; in_ham=0}
|> Map.add "opt" { in_spam=3; in_ham=7}
|> Map.add "opt-in" { in_spam=36; in_ham=2}
|> Map.add "opt-out" { in_spam=14; in_ham=0}
|> Map.add "opted" { in_spam=21; in_ham=4}
|> Map.add "opted-in" { in_spam=11; in_ham=0}
|> Map.add "optical" { in_spam=1; in_ham=14}
|> Map.add "optimal" { in_spam=2; in_ham=3}
|> Map.add "optimistic" { in_spam=0; in_ham=4}
|> Map.add "optimization" { in_spam=0; in_ham=15}
|> Map.add "optimize" { in_spam=0; in_ham=4}
|> Map.add "optimized" { in_spam=0; in_ham=13}
|> Map.add "optimizing" { in_spam=0; in_ham=9}
|> Map.add "option" { in_spam=12; in_ham=53}
|> Map.add "optional" { in_spam=4; in_ham=19}
|> Map.add "options" { in_spam=8; in_ham=36}
|> Map.add "optout" { in_spam=35; in_ham=0}
|> Map.add "oracle" { in_spam=0; in_ham=5}
|> Map.add "oracle's" { in_spam=0; in_ham=3}
|> Map.add "oral" { in_spam=1; in_ham=6}
|> Map.add "orange" { in_spam=2; in_ham=4}
|> Map.add "oranges" { in_spam=0; in_ham=4}
|> Map.add "orbit" { in_spam=0; in_ham=4}
|> Map.add "orbt" { in_spam=5; in_ham=0}
|> Map.add "order" { in_spam=75; in_ham=86}
|> Map.add "ordered" { in_spam=15; in_ham=8}
|> Map.add "ordering" { in_spam=11; in_ham=2}
|> Map.add "orders" { in_spam=22; in_ham=14}
|> Map.add "ordinary" { in_spam=9; in_ham=4}
|> Map.add "ore" { in_spam=0; in_ham=5}
|> Map.add "oregon" { in_spam=3; in_ham=2}
|> Map.add "oreilly" { in_spam=0; in_ham=4}
|> Map.add "oreillynet" { in_spam=0; in_ham=7}
|> Map.add "org" { in_spam=28; in_ham=428}
|> Map.add "organ" { in_spam=1; in_ham=2}
|> Map.add "organic" { in_spam=1; in_ham=6}
|> Map.add "organisation" { in_spam=3; in_ham=3}
|> Map.add "organised" { in_spam=0; in_ham=3}
|> Map.add "organization" { in_spam=4; in_ham=20}
|> Map.add "organized" { in_spam=3; in_ham=9}
|> Map.add "organizing" { in_spam=0; in_ham=6}
|> Map.add "organs" { in_spam=1; in_ham=2}
|> Map.add "orgasm" { in_spam=1; in_ham=2}
|> Map.add "oriented" { in_spam=0; in_ham=7}
|> Map.add "orifice" { in_spam=0; in_ham=3}
|> Map.add "orig" { in_spam=0; in_ham=5}
|> Map.add "origin" { in_spam=0; in_ham=3}
|> Map.add "original" { in_spam=20; in_ham=199}
|> Map.add "originally" { in_spam=7; in_ham=17}
|> Map.add "originated" { in_spam=0; in_ham=4}
|> Map.add "originates" { in_spam=0; in_ham=5}
|> Map.add "originating" { in_spam=1; in_ham=3}
|> Map.add "originator" { in_spam=9; in_ham=1}
|> Map.add "origins" { in_spam=0; in_ham=5}
|> Map.add "orkplace" { in_spam=0; in_ham=5}
|> Map.add "orlando" { in_spam=1; in_ham=4}
|> Map.add "orleans" { in_spam=1; in_ham=11}
|> Map.add "orthogonal" { in_spam=0; in_ham=6}
|> Map.add "osaisitko" { in_spam=0; in_ham=4}
|> Map.add "osama" { in_spam=0; in_ham=4}
|> Map.add "oscillate" { in_spam=0; in_ham=3}
|> Map.add "oscom" { in_spam=0; in_ham=3}
|> Map.add "oscon" { in_spam=0; in_ham=4}
|> Map.add "osdn" { in_spam=3; in_ham=156}
|> Map.add "osi" { in_spam=1; in_ham=8}
|> Map.add "oss" { in_spam=1; in_ham=19}
|> Map.add "osxcon" { in_spam=0; in_ham=4}
|> Map.add "otc" { in_spam=5; in_ham=0}
|> Map.add "otcbb" { in_spam=6; in_ham=0}
|> Map.add "other" { in_spam=85; in_ham=557}
|> Map.add "other's" { in_spam=0; in_ham=3}
|> Map.add "others" { in_spam=21; in_ham=114}
|> Map.add "others'" { in_spam=0; in_ham=3}
|> Map.add "otherwise" { in_spam=4; in_ham=46}
|> Map.add "otoh" { in_spam=0; in_ham=11}
|> Map.add "ottawa" { in_spam=0; in_ham=3}
|> Map.add "ouch" { in_spam=0; in_ham=14}
|> Map.add "ought" { in_spam=0; in_ham=23}
|> Map.add "ounce" { in_spam=0; in_ham=7}
|> Map.add "our" { in_spam=290; in_ham=195}
|> Map.add "ours" { in_spam=1; in_ham=3}
|> Map.add "ourselves" { in_spam=6; in_ham=8}
|> Map.add "out" { in_spam=178; in_ham=648}
|> Map.add "outcome" { in_spam=1; in_ham=6}
|> Map.add "outdated" { in_spam=1; in_ham=5}
|> Map.add "outdoors" { in_spam=1; in_ham=2}
|> Map.add "outer" { in_spam=1; in_ham=5}
|> Map.add "outgoing" { in_spam=0; in_ham=3}
|> Map.add "outlawed" { in_spam=0; in_ham=4}
|> Map.add "outlets" { in_spam=0; in_ham=3}
|> Map.add "outline" { in_spam=0; in_ham=3}
|> Map.add "outlines" { in_spam=0; in_ham=3}
|> Map.add "outlook" { in_spam=2; in_ham=17}
|> Map.add "output" { in_spam=1; in_ham=39}
|> Map.add "outputs" { in_spam=0; in_ham=4}
|> Map.add "outputting" { in_spam=0; in_ham=4}
|> Map.add "outrageous" { in_spam=2; in_ham=5}
|> Map.add "outright" { in_spam=1; in_ham=4}
|> Map.add "outside" { in_spam=8; in_ham=50}
|> Map.add "outstanding" { in_spam=4; in_ham=3}
|> Map.add "outward" { in_spam=0; in_ham=3}
|> Map.add "oval" { in_spam=0; in_ham=3}
|> Map.add "over" { in_spam=109; in_ham=284}
|> Map.add "over-bill" { in_spam=0; in_ham=3}
|> Map.add "over-sized" { in_spam=0; in_ham=10}
|> Map.add "overall" { in_spam=4; in_ham=20}
|> Map.add "overcome" { in_spam=0; in_ham=7}
|> Map.add "overflow" { in_spam=0; in_ham=4}
|> Map.add "overhead" { in_spam=2; in_ham=6}
|> Map.add "overkill" { in_spam=0; in_ham=3}
|> Map.add "overlap" { in_spam=0; in_ham=5}
|> Map.add "overlay" { in_spam=1; in_ham=3}
|> Map.add "overlook" { in_spam=16; in_ham=0}
|> Map.add "overly" { in_spam=1; in_ham=3}
|> Map.add "overnight" { in_spam=5; in_ham=2}
|> Map.add "override" { in_spam=0; in_ham=5}
|> Map.add "overrun" { in_spam=1; in_ham=2}
|> Map.add "oversaw" { in_spam=0; in_ham=6}
|> Map.add "overseas" { in_spam=5; in_ham=4}
|> Map.add "oversight" { in_spam=1; in_ham=4}
|> Map.add "overspending" { in_spam=0; in_ham=4}
|> Map.add "overthrown" { in_spam=0; in_ham=3}
|> Map.add "overview" { in_spam=0; in_ham=3}
|> Map.add "overwhelming" { in_spam=2; in_ham=10}
|> Map.add "overwritten" { in_spam=0; in_ham=4}
|> Map.add "owe" { in_spam=1; in_ham=5}
|> Map.add "owed" { in_spam=1; in_ham=3}
|> Map.add "owen" { in_spam=0; in_ham=47}
|> Map.add "owl" { in_spam=0; in_ham=9}
|> Map.add "own" { in_spam=62; in_ham=209}
|> Map.add "owned" { in_spam=6; in_ham=8}
|> Map.add "owner" { in_spam=11; in_ham=10}
|> Map.add "owners" { in_spam=19; in_ham=14}
|> Map.add "ownership" { in_spam=6; in_ham=4}
|> Map.add "owning" { in_spam=5; in_ham=1}
|> Map.add "owns" { in_spam=0; in_ham=5}
|> Map.add "oxford" { in_spam=0; in_ham=4}
|> Map.add "oxygen" { in_spam=0; in_ham=5}
|> Map.add "ozzie" { in_spam=0; in_ham=3}
|> Map.add "paarllel" { in_spam=0; in_ham=3}
|> Map.add "pablo" { in_spam=0; in_ham=22}
|> Map.add "pac" { in_spam=0; in_ham=5}
|> Map.add "pace" { in_spam=0; in_ham=7}
|> Map.add "pacific" { in_spam=3; in_ham=7}
|> Map.add "pack" { in_spam=1; in_ham=19}
|> Map.add "package" { in_spam=25; in_ham=127}
|> Map.add "packaged" { in_spam=0; in_ham=7}
|> Map.add "packages" { in_spam=3; in_ham=109}
|> Map.add "packaging" { in_spam=1; in_ham=10}
|> Map.add "packed" { in_spam=4; in_ham=4}
|> Map.add "packet" { in_spam=0; in_ham=15}
|> Map.add "packets" { in_spam=0; in_ham=10}
|> Map.add "packing" { in_spam=3; in_ham=4}
|> Map.add "packs" { in_spam=0; in_ham=7}
|> Map.add "padding-left" { in_spam=8; in_ham=2}
|> Map.add "padraig" { in_spam=0; in_ham=3}
|> Map.add "page" { in_spam=30; in_ham=166}
|> Map.add "pagename" { in_spam=0; in_ham=4}
|> Map.add "pager" { in_spam=0; in_ham=4}
|> Map.add "pages" { in_spam=8; in_ham=39}
|> Map.add "paid" { in_spam=34; in_ham=37}
|> Map.add "pain" { in_spam=0; in_ham=23}
|> Map.add "painful" { in_spam=1; in_ham=5}
|> Map.add "painfully" { in_spam=0; in_ham=3}
|> Map.add "paint" { in_spam=1; in_ham=9}
|> Map.add "pair" { in_spam=2; in_ham=14}
|> Map.add "pairs" { in_spam=0; in_ham=3}
|> Map.add "pakistan" { in_spam=1; in_ham=8}
|> Map.add "pale" { in_spam=0; in_ham=4}
|> Map.add "palestinian" { in_spam=0; in_ham=16}
|> Map.add "palestinians" { in_spam=0; in_ham=13}
|> Map.add "palestininem" { in_spam=0; in_ham=4}
|> Map.add "palladium" { in_spam=0; in_ham=3}
|> Map.add "palm" { in_spam=0; in_ham=5}
|> Map.add "palmos" { in_spam=0; in_ham=3}
|> Map.add "palrlael" { in_spam=0; in_ham=3}
|> Map.add "pam" { in_spam=9; in_ham=1}
|> Map.add "panama" { in_spam=2; in_ham=4}
|> Map.add "panasas" { in_spam=0; in_ham=30}
|> Map.add "pane" { in_spam=0; in_ham=5}
|> Map.add "panel" { in_spam=15; in_ham=15}
|> Map.add "panels" { in_spam=1; in_ham=2}
|> Map.add "panic" { in_spam=0; in_ham=6}
|> Map.add "panu" { in_spam=0; in_ham=9}
|> Map.add "paper" { in_spam=14; in_ham=31}
|> Map.add "papers" { in_spam=6; in_ham=11}
|> Map.add "paperwork" { in_spam=7; in_ham=0}
|> Map.add "papier" { in_spam=0; in_ham=3}
|> Map.add "par" { in_spam=3; in_ham=2}
|> Map.add "parachute" { in_spam=0; in_ham=6}
|> Map.add "parade" { in_spam=0; in_ham=3}
|> Map.add "paradise" { in_spam=1; in_ham=4}
|> Map.add "paragraph" { in_spam=8; in_ham=5}
|> Map.add "parallel" { in_spam=0; in_ham=6}
|> Map.add "param" { in_spam=1; in_ham=2}
|> Map.add "parameter" { in_spam=0; in_ham=6}
|> Map.add "paramount" { in_spam=1; in_ham=8}
|> Map.add "paranoid" { in_spam=0; in_ham=4}
|> Map.add "parasites" { in_spam=0; in_ham=4}
|> Map.add "parent" { in_spam=0; in_ham=6}
|> Map.add "parents" { in_spam=4; in_ham=15}
|> Map.add "paris" { in_spam=0; in_ham=4}
|> Map.add "park" { in_spam=2; in_ham=32}
|> Map.add "parker" { in_spam=0; in_ham=4}
|> Map.add "parking" { in_spam=1; in_ham=4}
|> Map.add "parliament" { in_spam=0; in_ham=5}
|> Map.add "parroting" { in_spam=0; in_ham=6}
|> Map.add "parse" { in_spam=0; in_ham=9}
|> Map.add "parser" { in_spam=0; in_ham=7}
|> Map.add "parsing" { in_spam=0; in_ham=19}
|> Map.add "part" { in_spam=33; in_ham=152}
|> Map.add "partial" { in_spam=3; in_ham=6}
|> Map.add "participants" { in_spam=5; in_ham=5}
|> Map.add "participate" { in_spam=13; in_ham=4}
|> Map.add "participated" { in_spam=1; in_ham=4}
|> Map.add "particular" { in_spam=3; in_ham=85}
|> Map.add "particularly" { in_spam=1; in_ham=54}
|> Map.add "particulars" { in_spam=0; in_ham=3}
|> Map.add "parties" { in_spam=11; in_ham=18}
|> Map.add "partition" { in_spam=0; in_ham=15}
|> Map.add "partitioned" { in_spam=0; in_ham=9}
|> Map.add "partitions" { in_spam=0; in_ham=11}
|> Map.add "partly" { in_spam=0; in_ham=5}
|> Map.add "partner" { in_spam=19; in_ham=21}
|> Map.add "partners" { in_spam=16; in_ham=31}
|> Map.add "partnership" { in_spam=7; in_ham=9}
|> Map.add "partnerships" { in_spam=1; in_ham=3}
|> Map.add "parts" { in_spam=3; in_ham=45}
|> Map.add "party" { in_spam=35; in_ham=58}
|> Map.add "party's" { in_spam=0; in_ham=3}
|> Map.add "pas" { in_spam=2; in_ham=2}
|> Map.add "paso" { in_spam=0; in_ham=4}
|> Map.add "pass" { in_spam=12; in_ham=25}
|> Map.add "passage" { in_spam=1; in_ham=4}
|> Map.add "passed" { in_spam=19; in_ham=15}
|> Map.add "passenger" { in_spam=0; in_ham=5}
|> Map.add "passengers" { in_spam=0; in_ham=5}
|> Map.add "passes" { in_spam=2; in_ham=20}
|> Map.add "passing" { in_spam=2; in_ham=19}
|> Map.add "passion" { in_spam=1; in_ham=3}
|> Map.add "passionate" { in_spam=0; in_ham=3}
|> Map.add "passive" { in_spam=0; in_ham=4}
|> Map.add "passphrase" { in_spam=0; in_ham=7}
|> Map.add "passport" { in_spam=1; in_ham=4}
|> Map.add "password" { in_spam=8; in_ham=10}
|> Map.add "passwords" { in_spam=1; in_ham=8}
|> Map.add "past" { in_spam=34; in_ham=88}
|> Map.add "pasta" { in_spam=0; in_ham=4}
|> Map.add "paste" { in_spam=16; in_ham=19}
|> Map.add "pasted" { in_spam=0; in_ham=5}
|> Map.add "pasting" { in_spam=0; in_ham=3}
|> Map.add "pastor" { in_spam=5; in_ham=1}
|> Map.add "pat" { in_spam=0; in_ham=3}
|> Map.add "patch" { in_spam=4; in_ham=47}
|> Map.add "patches" { in_spam=3; in_ham=12}
|> Map.add "patent" { in_spam=0; in_ham=19}
|> Map.add "patented" { in_spam=1; in_ham=6}
|> Map.add "patenting" { in_spam=0; in_ham=3}
|> Map.add "patents" { in_spam=0; in_ham=4}
|> Map.add "path" { in_spam=2; in_ham=61}
|> Map.add "pathetic" { in_spam=0; in_ham=3}
|> Map.add "pathological" { in_spam=0; in_ham=3}
|> Map.add "paths" { in_spam=0; in_ham=3}
|> Map.add "patients" { in_spam=0; in_ham=7}
|> Map.add "patrick" { in_spam=2; in_ham=4}
|> Map.add "pattern" { in_spam=0; in_ham=11}
|> Map.add "patterns" { in_spam=1; in_ham=18}
|> Map.add "paul" { in_spam=1; in_ham=51}
|> Map.add "paulgraham" { in_spam=0; in_ham=3}
|> Map.add "pause" { in_spam=0; in_ham=10}
|> Map.add "pausing" { in_spam=0; in_ham=3}
|> Map.add "paved" { in_spam=0; in_ham=3}
|> Map.add "paving" { in_spam=3; in_ham=1}
|> Map.add "paw" { in_spam=1; in_ham=2}
|> Map.add "pay" { in_spam=71; in_ham=65}
|> Map.add "paying" { in_spam=25; in_ham=22}
|> Map.add "payment" { in_spam=18; in_ham=6}
|> Map.add "payments" { in_spam=11; in_ham=2}
|> Map.add "pays" { in_spam=2; in_ham=7}
|> Map.add "pbd" { in_spam=1; in_ham=2}
|> Map.add "pbort" { in_spam=0; in_ham=3}
|> Map.add "pbs" { in_spam=1; in_ham=5}
|> Map.add "pc's" { in_spam=16; in_ham=1}
|> Map.add "pci" { in_spam=0; in_ham=5}
|> Map.add "pcm" { in_spam=1; in_ham=4}
|> Map.add "pcmcia" { in_spam=0; in_ham=3}
|> Map.add "pcs" { in_spam=0; in_ham=5}
|> Map.add "pcworld" { in_spam=0; in_ham=3}
|> Map.add "pda" { in_spam=1; in_ham=4}
|> Map.add "pdas" { in_spam=0; in_ham=3}
|> Map.add "pdf" { in_spam=1; in_ham=9}
|> Map.add "pdif" { in_spam=0; in_ham=3}
|> Map.add "pdt" { in_spam=0; in_ham=14}
|> Map.add "peace" { in_spam=3; in_ham=12}
|> Map.add "peaceable" { in_spam=1; in_ham=3}
|> Map.add "peaceful" { in_spam=2; in_ham=3}
|> Map.add "peak" { in_spam=0; in_ham=6}
|> Map.add "pearl" { in_spam=1; in_ham=3}
|> Map.add "peculiar" { in_spam=0; in_ham=4}
|> Map.add "pedicures" { in_spam=0; in_ham=5}
|> Map.add "peek" { in_spam=0; in_ham=3}
|> Map.add "peer" { in_spam=0; in_ham=6}
|> Map.add "peer-to-peer" { in_spam=0; in_ham=4}
|> Map.add "peeve" { in_spam=0; in_ham=3}
|> Map.add "peilata" { in_spam=0; in_ham=4}
|> Map.add "peili" { in_spam=0; in_ham=4}
|> Map.add "peltonen" { in_spam=0; in_ham=8}
|> Map.add "penalties" { in_spam=1; in_ham=4}
|> Map.add "penalty" { in_spam=1; in_ham=5}
|> Map.add "pencil" { in_spam=7; in_ham=3}
|> Map.add "pending" { in_spam=1; in_ham=9}
|> Map.add "pendulum" { in_spam=0; in_ham=5}
|> Map.add "penetrate" { in_spam=0; in_ham=3}
|> Map.add "penetration" { in_spam=0; in_ham=3}
|> Map.add "penis" { in_spam=6; in_ham=1}
|> Map.add "pennies" { in_spam=1; in_ham=6}
|> Map.add "pennsylvania" { in_spam=3; in_ham=8}
|> Map.add "pension" { in_spam=1; in_ham=4}
|> Map.add "pensions" { in_spam=1; in_ham=2}
|> Map.add "pentagon" { in_spam=1; in_ham=4}
|> Map.add "pentium" { in_spam=1; in_ham=4}
|> Map.add "people" { in_spam=76; in_ham=415}
|> Map.add "people's" { in_spam=4; in_ham=24}
|> Map.add "peoples" { in_spam=3; in_ham=7}
|> Map.add "pepper" { in_spam=0; in_ham=3}
|> Map.add "per" { in_spam=54; in_ham=97}
|> Map.add "perceive" { in_spam=0; in_ham=3}
|> Map.add "perceived" { in_spam=0; in_ham=4}
|> Map.add "percent" { in_spam=3; in_ham=26}
|> Map.add "percentage" { in_spam=7; in_ham=13}
|> Map.add "percentages" { in_spam=7; in_ham=8}
|> Map.add "perception" { in_spam=3; in_ham=7}
|> Map.add "perceptive" { in_spam=0; in_ham=4}
|> Map.add "perfect" { in_spam=23; in_ham=15}
|> Map.add "perfectly" { in_spam=0; in_ham=33}
|> Map.add "perform" { in_spam=1; in_ham=5}
|> Map.add "performance" { in_spam=17; in_ham=67}
|> Map.add "performed" { in_spam=0; in_ham=10}
|> Map.add "performing" { in_spam=2; in_ham=9}
|> Map.add "performs" { in_spam=0; in_ham=8}
|> Map.add "perhaps" { in_spam=4; in_ham=98}
|> Map.add "period" { in_spam=15; in_ham=38}
|> Map.add "periodic" { in_spam=0; in_ham=6}
|> Map.add "periodically" { in_spam=7; in_ham=6}
|> Map.add "periods" { in_spam=1; in_ham=6}
|> Map.add "perkel" { in_spam=0; in_ham=5}
|> Map.add "perl" { in_spam=0; in_ham=132}
|> Map.add "permafrost" { in_spam=0; in_ham=3}
|> Map.add "permanent" { in_spam=3; in_ham=14}
|> Map.add "permission" { in_spam=10; in_ham=26}
|> Map.add "permissions" { in_spam=0; in_ham=12}
|> Map.add "permit" { in_spam=3; in_ham=12}
|> Map.add "permits" { in_spam=0; in_ham=7}
|> Map.add "permitted" { in_spam=1; in_ham=15}
|> Map.add "permitting" { in_spam=0; in_ham=4}
|> Map.add "permsgstatus" { in_spam=0; in_ham=3}
|> Map.add "permutations" { in_spam=0; in_ham=3}
|> Map.add "perpetrated" { in_spam=1; in_ham=3}
|> Map.add "perpetuate" { in_spam=2; in_ham=2}
|> Map.add "persist" { in_spam=0; in_ham=8}
|> Map.add "persistence" { in_spam=0; in_ham=4}
|> Map.add "persistent" { in_spam=0; in_ham=5}
|> Map.add "person" { in_spam=29; in_ham=87}
|> Map.add "personal" { in_spam=55; in_ham=78}
|> Map.add "personality" { in_spam=0; in_ham=3}
|> Map.add "personally" { in_spam=9; in_ham=33}
|> Map.add "personnel" { in_spam=2; in_ham=3}
|> Map.add "persons" { in_spam=5; in_ham=6}
|> Map.add "perspective" { in_spam=2; in_ham=13}
|> Map.add "persuade" { in_spam=0; in_ham=4}
|> Map.add "persuading" { in_spam=0; in_ham=3}
|> Map.add "pertinent" { in_spam=3; in_ham=2}
|> Map.add "peru" { in_spam=2; in_ham=8}
|> Map.add "peru's" { in_spam=0; in_ham=3}
|> Map.add "peruse" { in_spam=0; in_ham=7}
|> Map.add "pesky" { in_spam=0; in_ham=6}
|> Map.add "pet" { in_spam=5; in_ham=7}
|> Map.add "peter" { in_spam=2; in_ham=40}
|> Map.add "peters" { in_spam=0; in_ham=16}
|> Map.add "peterson" { in_spam=1; in_ham=3}
|> Map.add "petition" { in_spam=0; in_ham=4}
|> Map.add "petrified" { in_spam=0; in_ham=4}
|> Map.add "petroleum" { in_spam=2; in_ham=2}
|> Map.add "pets" { in_spam=1; in_ham=2}
|> Map.add "pgp" { in_spam=0; in_ham=110}
|> Map.add "phantom" { in_spam=0; in_ham=3}
|> Map.add "phase" { in_spam=0; in_ham=8}
|> Map.add "phd" { in_spam=1; in_ham=14}
|> Map.add "phenomena" { in_spam=0; in_ham=6}
|> Map.add "phenomenon" { in_spam=1; in_ham=4}
|> Map.add "phil" { in_spam=0; in_ham=16}
|> Map.add "philip" { in_spam=0; in_ham=7}
|> Map.add "philippines" { in_spam=3; in_ham=8}
|> Map.add "philodox" { in_spam=0; in_ham=7}
|> Map.add "philosophy" { in_spam=1; in_ham=6}
|> Map.add "phone" { in_spam=80; in_ham=208}
|> Map.add "phones" { in_spam=3; in_ham=18}
|> Map.add "phonetic" { in_spam=0; in_ham=3}
|> Map.add "photo" { in_spam=13; in_ham=15}
|> Map.add "photo'" { in_spam=0; in_ham=3}
|> Map.add "photograph" { in_spam=0; in_ham=3}
|> Map.add "photographer" { in_spam=0; in_ham=5}
|> Map.add "photographs" { in_spam=0; in_ham=5}
|> Map.add "photography" { in_spam=0; in_ham=3}
|> Map.add "photos" { in_spam=2; in_ham=23}
|> Map.add "php" { in_spam=41; in_ham=62}
|> Map.add "php-pgsql" { in_spam=0; in_ham=3}
|> Map.add "phrase" { in_spam=0; in_ham=10}
|> Map.add "phrases" { in_spam=0; in_ham=7}
|> Map.add "phtml" { in_spam=0; in_ham=3}
|> Map.add "physical" { in_spam=1; in_ham=27}
|> Map.add "physically" { in_spam=1; in_ham=10}
|> Map.add "physics" { in_spam=0; in_ham=8}
|> Map.add "physik" { in_spam=0; in_ham=7}
|> Map.add "pic" { in_spam=5; in_ham=2}
|> Map.add "picasso" { in_spam=0; in_ham=45}
|> Map.add "pick" { in_spam=5; in_ham=55}
|> Map.add "picked" { in_spam=3; in_ham=16}
|> Map.add "pickett" { in_spam=0; in_ham=4}
|> Map.add "picking" { in_spam=5; in_ham=6}
|> Map.add "pickle" { in_spam=0; in_ham=22}

