open Bayesian.Database
open BayesianBody_001
let db = db 
|> Map.add "anecdotal" { in_spam=0; in_ham=14}
|> Map.add "anecdote" { in_spam=0; in_ham=13}
|> Map.add "anecdotes" { in_spam=0; in_ham=5}
|> Map.add "angegangen" { in_spam=0; in_ham=3}
|> Map.add "angeles" { in_spam=3; in_ham=13}
|> Map.add "angels" { in_spam=0; in_ham=3}
|> Map.add "anger" { in_spam=0; in_ham=11}
|> Map.add "angle" { in_spam=0; in_ham=23}
|> Map.add "angle's" { in_spam=0; in_ham=3}
|> Map.add "angles" { in_spam=0; in_ham=14}
|> Map.add "anglo" { in_spam=0; in_ham=3}
|> Map.add "angry" { in_spam=0; in_ham=14}
|> Map.add "anil" { in_spam=0; in_ham=3}
|> Map.add "animal" { in_spam=0; in_ham=13}
|> Map.add "animals" { in_spam=7; in_ham=5}
|> Map.add "anime" { in_spam=0; in_ham=4}
|> Map.add "ann" { in_spam=1; in_ham=2}
|> Map.add "anniversary" { in_spam=1; in_ham=6}
|> Map.add "announce" { in_spam=0; in_ham=7}
|> Map.add "announced" { in_spam=4; in_ham=31}
|> Map.add "announcement" { in_spam=3; in_ham=6}
|> Map.add "announces" { in_spam=1; in_ham=5}
|> Map.add "announcing" { in_spam=5; in_ham=4}
|> Map.add "annoy" { in_spam=0; in_ham=4}
|> Map.add "annoyed" { in_spam=0; in_ham=5}
|> Map.add "annoying" { in_spam=0; in_ham=24}
|> Map.add "annual" { in_spam=5; in_ham=19}
|> Map.add "annually" { in_spam=5; in_ham=9}
|> Map.add "annuity" { in_spam=8; in_ham=0}
|> Map.add "anonymous" { in_spam=1; in_ham=16}
|> Map.add "anonymously" { in_spam=0; in_ham=5}
|> Map.add "another" { in_spam=30; in_ham=244}
|> Map.add "ansaylis" { in_spam=0; in_ham=3}
|> Map.add "answer" { in_spam=29; in_ham=56}
|> Map.add "answered" { in_spam=1; in_ham=4}
|> Map.add "answers" { in_spam=3; in_ham=61}
|> Map.add "antarctica" { in_spam=1; in_ham=3}
|> Map.add "antenna" { in_spam=2; in_ham=4}
|> Map.add "antequated" { in_spam=0; in_ham=8}
|> Map.add "anthony" { in_spam=0; in_ham=21}
|> Map.add "anthony's" { in_spam=0; in_ham=8}
|> Map.add "anti-spam" { in_spam=2; in_ham=12}
|> Map.add "anti-virus" { in_spam=5; in_ham=1}
|> Map.add "antibodies" { in_spam=0; in_ham=3}
|> Map.add "anticipated" { in_spam=0; in_ham=8}
|> Map.add "antilles" { in_spam=1; in_ham=2}
|> Map.add "antiquated" { in_spam=0; in_ham=5}
|> Map.add "antiquity" { in_spam=1; in_ham=39}
|> Map.add "antivirus" { in_spam=5; in_ham=1}
|> Map.add "anxiety" { in_spam=1; in_ham=3}
|> Map.add "any" { in_spam=173; in_ham=555}
|> Map.add "anybody" { in_spam=11; in_ham=29}
|> Map.add "anydbm" { in_spam=0; in_ham=6}
|> Map.add "anyhow" { in_spam=0; in_ham=3}
|> Map.add "anymore" { in_spam=5; in_ham=26}
|> Map.add "anyone" { in_spam=48; in_ham=211}
|> Map.add "anyone's" { in_spam=1; in_ham=4}
|> Map.add "anyones" { in_spam=0; in_ham=3}
|> Map.add "anyplace" { in_spam=1; in_ham=3}
|> Map.add "anything" { in_spam=32; in_ham=190}
|> Map.add "anytime" { in_spam=13; in_ham=3}
|> Map.add "anyway" { in_spam=0; in_ham=122}
|> Map.add "anyways" { in_spam=0; in_ham=3}
|> Map.add "anywhere" { in_spam=24; in_ham=33}
|> Map.add "aol" { in_spam=11; in_ham=18}
|> Map.add "aol-im" { in_spam=0; in_ham=3}
|> Map.add "apache" { in_spam=0; in_ham=8}
|> Map.add "apart" { in_spam=0; in_ham=19}
|> Map.add "apartment" { in_spam=2; in_ham=6}
|> Map.add "apc" { in_spam=1; in_ham=2}
|> Map.add "apestaart" { in_spam=0; in_ham=8}
|> Map.add "api" { in_spam=1; in_ham=15}
|> Map.add "api's" { in_spam=0; in_ham=4}
|> Map.add "apis" { in_spam=0; in_ham=6}
|> Map.add "apologies" { in_spam=19; in_ham=12}
|> Map.add "apologise" { in_spam=7; in_ham=0}
|> Map.add "apologize" { in_spam=14; in_ham=4}
|> Map.add "app" { in_spam=4; in_ham=23}
|> Map.add "apparent" { in_spam=1; in_ham=18}
|> Map.add "apparently" { in_spam=1; in_ham=59}
|> Map.add "appeal" { in_spam=2; in_ham=5}
|> Map.add "appealing" { in_spam=0; in_ham=3}
|> Map.add "appeals" { in_spam=2; in_ham=3}
|> Map.add "appear" { in_spam=4; in_ham=49}
|> Map.add "appearance" { in_spam=1; in_ham=3}
|> Map.add "appearances" { in_spam=0; in_ham=4}
|> Map.add "appeared" { in_spam=0; in_ham=16}
|> Map.add "appearing" { in_spam=0; in_ham=4}
|> Map.add "appears" { in_spam=11; in_ham=47}
|> Map.add "appft" { in_spam=0; in_ham=3}
|> Map.add "apple" { in_spam=0; in_ham=27}
|> Map.add "apple's" { in_spam=0; in_ham=4}
|> Map.add "applescript" { in_spam=0; in_ham=4}
|> Map.add "applicable" { in_spam=3; in_ham=3}
|> Map.add "application" { in_spam=20; in_ham=52}
|> Map.add "applications" { in_spam=9; in_ham=55}
|> Map.add "applied" { in_spam=7; in_ham=17}
|> Map.add "applies" { in_spam=7; in_ham=6}
|> Map.add "apply" { in_spam=13; in_ham=19}
|> Map.add "applying" { in_spam=5; in_ham=9}
|> Map.add "appointed" { in_spam=1; in_ham=4}
|> Map.add "appointing" { in_spam=0; in_ham=3}
|> Map.add "appointment" { in_spam=1; in_ham=2}
|> Map.add "appreciate" { in_spam=4; in_ham=17}
|> Map.add "appreciated" { in_spam=3; in_ham=22}
|> Map.add "appreciation" { in_spam=1; in_ham=3}
|> Map.add "approach" { in_spam=5; in_ham=44}
|> Map.add "approached" { in_spam=7; in_ham=11}
|> Map.add "approaches" { in_spam=0; in_ham=10}
|> Map.add "approaching" { in_spam=2; in_ham=7}
|> Map.add "appropriate" { in_spam=8; in_ham=17}
|> Map.add "approval" { in_spam=2; in_ham=5}
|> Map.add "approve" { in_spam=3; in_ham=2}
|> Map.add "approved" { in_spam=32; in_ham=9}
|> Map.add "approx" { in_spam=6; in_ham=5}
|> Map.add "apps" { in_spam=2; in_ham=23}
|> Map.add "apr" { in_spam=4; in_ham=2}
|> Map.add "april" { in_spam=1; in_ham=5}
|> Map.add "apropos" { in_spam=0; in_ham=3}
|> Map.add "apt" { in_spam=0; in_ham=66}
|> Map.add "apt-" { in_spam=0; in_ham=5}
|> Map.add "apt-cache" { in_spam=0; in_ham=3}
|> Map.add "apt-get" { in_spam=0; in_ham=34}
|> Map.add "apt-rpm" { in_spam=0; in_ham=7}
|> Map.add "apt-varaston" { in_spam=0; in_ham=4}
|> Map.add "arab" { in_spam=2; in_ham=6}
|> Map.add "arabia" { in_spam=2; in_ham=6}
|> Map.add "arafat's" { in_spam=0; in_ham=6}
|> Map.add "arbitrary" { in_spam=0; in_ham=10}
|> Map.add "arcane" { in_spam=0; in_ham=4}
|> Map.add "arch" { in_spam=0; in_ham=9}
|> Map.add "archi" { in_spam=0; in_ham=4}
|> Map.add "architect" { in_spam=0; in_ham=28}
|> Map.add "architecture" { in_spam=0; in_ham=22}
|> Map.add "archive" { in_spam=2; in_ham=36}
|> Map.add "archived" { in_spam=0; in_ham=7}
|> Map.add "archives" { in_spam=1; in_ham=146}
|> Map.add "arctic" { in_spam=0; in_ham=3}
|> Map.add "are" { in_spam=282; in_ham=989}
|> Map.add "area" { in_spam=17; in_ham=68}
|> Map.add "areas" { in_spam=2; in_ham=33}
|> Map.add "aren't" { in_spam=7; in_ham=71}
|> Map.add "arena" { in_spam=1; in_ham=2}
|> Map.add "argh" { in_spam=0; in_ham=6}
|> Map.add "argon" { in_spam=0; in_ham=6}
|> Map.add "args" { in_spam=0; in_ham=6}
|> Map.add "arguably" { in_spam=0; in_ham=3}
|> Map.add "argue" { in_spam=0; in_ham=14}
|> Map.add "argued" { in_spam=0; in_ham=11}
|> Map.add "arguing" { in_spam=0; in_ham=12}
|> Map.add "argument" { in_spam=1; in_ham=50}
|> Map.add "arguments" { in_spam=1; in_ham=15}
|> Map.add "arial" { in_spam=160; in_ham=7}
|> Map.add "arise" { in_spam=0; in_ham=4}
|> Map.add "arises" { in_spam=0; in_ham=3}
|> Map.add "arising" { in_spam=0; in_ham=3}
|> Map.add "arizona" { in_spam=3; in_ham=3}
|> Map.add "arm" { in_spam=3; in_ham=13}
|> Map.add "armed" { in_spam=1; in_ham=11}
|> Map.add "arms" { in_spam=6; in_ham=15}
|> Map.add "army" { in_spam=1; in_ham=9}
|> Map.add "arose" { in_spam=0; in_ham=4}
|> Map.add "around" { in_spam=37; in_ham=159}
|> Map.add "aroused" { in_spam=0; in_ham=4}
|> Map.add "arrange" { in_spam=1; in_ham=3}
|> Map.add "arranged" { in_spam=1; in_ham=3}
|> Map.add "arrangement" { in_spam=10; in_ham=5}
|> Map.add "arrangements" { in_spam=0; in_ham=3}
|> Map.add "array" { in_spam=1; in_ham=5}
|> Map.add "arrayed" { in_spam=0; in_ham=3}
|> Map.add "arrest" { in_spam=7; in_ham=3}
|> Map.add "arrested" { in_spam=2; in_ham=19}
|> Map.add "arresting" { in_spam=0; in_ham=3}
|> Map.add "arrival" { in_spam=1; in_ham=7}
|> Map.add "arrive" { in_spam=2; in_ham=4}
|> Map.add "arrived" { in_spam=6; in_ham=19}
|> Map.add "arriving" { in_spam=0; in_ham=3}
|> Map.add "arrow" { in_spam=2; in_ham=2}
|> Map.add "arse" { in_spam=0; in_ham=3}
|> Map.add "arsenal" { in_spam=1; in_ham=4}
|> Map.add "arstechnica" { in_spam=0; in_ham=3}
|> Map.add "art" { in_spam=12; in_ham=22}
|> Map.add "article" { in_spam=1; in_ham=163}
|> Map.add "articlenews" { in_spam=0; in_ham=3}
|> Map.add "articles" { in_spam=6; in_ham=43}
|> Map.add "artifact" { in_spam=0; in_ham=6}
|> Map.add "artifacts" { in_spam=0; in_ham=9}
|> Map.add "artificial" { in_spam=0; in_ham=5}
|> Map.add "artist" { in_spam=0; in_ham=17}
|> Map.add "artistic" { in_spam=0; in_ham=3}
|> Map.add "artists" { in_spam=0; in_ham=9}
|> Map.add "arts" { in_spam=0; in_ham=20}
|> Map.add "as-is" { in_spam=0; in_ham=4}
|> Map.add "asap" { in_spam=2; in_ham=3}
|> Map.add "ascending" { in_spam=0; in_ham=5}
|> Map.add "ascribed" { in_spam=0; in_ham=3}
|> Map.add "ash" { in_spam=0; in_ham=3}
|> Map.add "ashburn" { in_spam=0; in_ham=5}
|> Map.add "ashcroft" { in_spam=0; in_ham=4}
|> Map.add "ashcrofts" { in_spam=0; in_ham=3}
|> Map.add "asia" { in_spam=3; in_ham=12}
|> Map.add "asia-pacific" { in_spam=0; in_ham=4}
|> Map.add "asian" { in_spam=3; in_ham=6}
|> Map.add "asiassa" { in_spam=0; in_ham=4}
|> Map.add "aside" { in_spam=4; in_ham=11}
|> Map.add "ask" { in_spam=21; in_ham=73}
|> Map.add "asked" { in_spam=12; in_ham=55}
|> Map.add "asking" { in_spam=4; in_ham=42}
|> Map.add "asks" { in_spam=1; in_ham=13}
|> Map.add "asleep" { in_spam=0; in_ham=3}
|> Map.add "asound" { in_spam=0; in_ham=6}
|> Map.add "asp" { in_spam=101; in_ham=145}
|> Map.add "aspect" { in_spam=1; in_ham=10}
|> Map.add "aspects" { in_spam=1; in_ham=10}
|> Map.add "aspell" { in_spam=0; in_ham=3}
|> Map.add "aspirations" { in_spam=1; in_ham=3}
|> Map.add "aspx" { in_spam=0; in_ham=6}
|> Map.add "ass" { in_spam=1; in_ham=23}
|> Map.add "assault" { in_spam=0; in_ham=4}
|> Map.add "assemble" { in_spam=2; in_ham=4}
|> Map.add "assembled" { in_spam=1; in_ham=7}
|> Map.add "assembly" { in_spam=3; in_ham=7}
|> Map.add "assert" { in_spam=0; in_ham=3}
|> Map.add "asserting" { in_spam=1; in_ham=3}
|> Map.add "assertion" { in_spam=2; in_ham=7}
|> Map.add "assessment" { in_spam=1; in_ham=7}
|> Map.add "asset" { in_spam=2; in_ham=5}
|> Map.add "assets" { in_spam=4; in_ham=15}
|> Map.add "assholes" { in_spam=0; in_ham=5}
|> Map.add "assign" { in_spam=1; in_ham=4}
|> Map.add "assigned" { in_spam=1; in_ham=5}
|> Map.add "assignedto" { in_spam=0; in_ham=5}
|> Map.add "assignee" { in_spam=0; in_ham=23}
|> Map.add "assigning" { in_spam=0; in_ham=8}
|> Map.add "assist" { in_spam=28; in_ham=4}
|> Map.add "assistance" { in_spam=42; in_ham=6}
|> Map.add "assistant" { in_spam=3; in_ham=6}
|> Map.add "assisted" { in_spam=2; in_ham=4}
|> Map.add "assisting" { in_spam=2; in_ham=6}
|> Map.add "associate" { in_spam=10; in_ham=5}
|> Map.add "associated" { in_spam=2; in_ham=28}
|> Map.add "associates" { in_spam=7; in_ham=9}
|> Map.add "association" { in_spam=20; in_ham=13}
|> Map.add "assume" { in_spam=9; in_ham=49}
|> Map.add "assumed" { in_spam=0; in_ham=9}
|> Map.add "assumes" { in_spam=1; in_ham=4}
|> Map.add "assumiing" { in_spam=0; in_ham=4}
|> Map.add "assuming" { in_spam=9; in_ham=28}
|> Map.add "assumption" { in_spam=0; in_ham=18}
|> Map.add "assumptions" { in_spam=1; in_ham=7}
|> Map.add "assurance" { in_spam=6; in_ham=8}
|> Map.add "assure" { in_spam=2; in_ham=5}
|> Map.add "assured" { in_spam=8; in_ham=10}
|> Map.add "ast" { in_spam=1; in_ham=2}
|> Map.add "astonishment" { in_spam=5; in_ham=0}
|> Map.add "astounding" { in_spam=1; in_ham=3}
|> Map.add "astrophysics" { in_spam=0; in_ham=3}
|> Map.add "asylum" { in_spam=1; in_ham=2}
|> Map.add "async" { in_spam=0; in_ham=4}
|> Map.add "asynchronous" { in_spam=0; in_ham=5}
|> Map.add "atavistic" { in_spam=0; in_ham=3}
|> Map.add "ate" { in_spam=0; in_ham=3}
|> Map.add "athenet" { in_spam=0; in_ham=8}
|> Map.add "athlon" { in_spam=0; in_ham=4}
|> Map.add "atlanta" { in_spam=1; in_ham=2}
|> Map.add "atlantic" { in_spam=0; in_ham=6}
|> Map.add "atm" { in_spam=1; in_ham=9}
|> Map.add "atm-related" { in_spam=0; in_ham=6}
|> Map.add "atmosphere" { in_spam=0; in_ham=6}
|> Map.add "atmospheric" { in_spam=0; in_ham=6}
|> Map.add "atoms" { in_spam=0; in_ham=3}
|> Map.add "atop" { in_spam=0; in_ham=3}
|> Map.add "att" { in_spam=0; in_ham=5}
|> Map.add "atta" { in_spam=0; in_ham=3}
|> Map.add "attach" { in_spam=0; in_ham=6}
|> Map.add "attached" { in_spam=2; in_ham=22}
|> Map.add "attachment" { in_spam=2; in_ham=9}
|> Map.add "attachments" { in_spam=0; in_ham=13}
|> Map.add "attack" { in_spam=5; in_ham=26}
|> Map.add "attacked" { in_spam=1; in_ham=14}
|> Map.add "attacker" { in_spam=0; in_ham=8}
|> Map.add "attackers" { in_spam=0; in_ham=6}
|> Map.add "attacking" { in_spam=1; in_ham=4}
|> Map.add "attacks" { in_spam=2; in_ham=33}
|> Map.add "attained" { in_spam=23; in_ham=0}
|> Map.add "attempt" { in_spam=3; in_ham=44}
|> Map.add "attempting" { in_spam=3; in_ham=14}
|> Map.add "attempts" { in_spam=3; in_ham=18}
|> Map.add "attend" { in_spam=2; in_ham=6}
|> Map.add "attended" { in_spam=0; in_ham=11}
|> Map.add "attending" { in_spam=0; in_ham=3}
|> Map.add "attention" { in_spam=22; in_ham=24}
|> Map.add "attenuation" { in_spam=0; in_ham=3}
|> Map.add "attitude" { in_spam=3; in_ham=6}
|> Map.add "attn" { in_spam=9; in_ham=0}
|> Map.add "attorney" { in_spam=15; in_ham=5}
|> Map.add "attorneys" { in_spam=1; in_ham=4}
|> Map.add "attract" { in_spam=5; in_ham=2}
|> Map.add "attracted" { in_spam=0; in_ham=6}
|> Map.add "attractive" { in_spam=6; in_ham=7}
|> Map.add "attribute" { in_spam=0; in_ham=4}
|> Map.add "attributes" { in_spam=1; in_ham=8}
|> Map.add "attws" { in_spam=0; in_ham=4}
|> Map.add "atx" { in_spam=0; in_ham=3}
|> Map.add "auction" { in_spam=3; in_ham=8}
|> Map.add "auctions" { in_spam=2; in_ham=3}
|> Map.add "audacity" { in_spam=1; in_ham=2}
|> Map.add "audience" { in_spam=2; in_ham=12}
|> Map.add "audio" { in_spam=4; in_ham=29}
|> Map.add "audit" { in_spam=3; in_ham=4}
|> Map.add "audits" { in_spam=1; in_ham=2}
|> Map.add "aug" { in_spam=3; in_ham=177}
|> Map.add "augment" { in_spam=0; in_ham=3}
|> Map.add "august" { in_spam=9; in_ham=125}
|> Map.add "aumix" { in_spam=0; in_ham=13}
|> Map.add "auoquewas" { in_spam=0; in_ham=4}
|> Map.add "auracom" { in_spam=0; in_ham=23}
|> Map.add "austin" { in_spam=0; in_ham=38}
|> Map.add "australia" { in_spam=8; in_ham=14}
|> Map.add "australian" { in_spam=1; in_ham=4}
|> Map.add "authentic" { in_spam=0; in_ham=3}
|> Map.add "author" { in_spam=6; in_ham=37}
|> Map.add "authored" { in_spam=1; in_ham=6}
|> Map.add "authorities" { in_spam=1; in_ham=10}
|> Map.add "authority" { in_spam=3; in_ham=16}
|> Map.add "authorize" { in_spam=2; in_ham=2}
|> Map.add "authorized" { in_spam=5; in_ham=3}
|> Map.add "authors" { in_spam=3; in_ham=15}
|> Map.add "auto" { in_spam=19; in_ham=11}
|> Map.add "auto-ham" { in_spam=0; in_ham=5}
|> Map.add "autocomplete" { in_spam=0; in_ham=4}
|> Map.add "autoconf" { in_spam=0; in_ham=3}
|> Map.add "automagic" { in_spam=0; in_ham=4}
|> Map.add "automated" { in_spam=2; in_ham=10}
|> Map.add "automatic" { in_spam=6; in_ham=18}
|> Map.add "automobile" { in_spam=3; in_ham=1}
|> Map.add "autonumber" { in_spam=14; in_ham=1}
|> Map.add "avail" { in_spam=2; in_ham=2}
|> Map.add "availability" { in_spam=1; in_ham=9}
|> Map.add "available" { in_spam=74; in_ham=114}
|> Map.add "ave" { in_spam=6; in_ham=5}
|> Map.add "aver" { in_spam=0; in_ham=6}
|> Map.add "average" { in_spam=11; in_ham=49}
|> Map.add "averages" { in_spam=0; in_ham=9}
|> Map.add "avez" { in_spam=2; in_ham=3}
|> Map.add "avg" { in_spam=0; in_ham=5}
|> Map.add "aviation" { in_spam=3; in_ham=1}
|> Map.add "avid" { in_spam=0; in_ham=4}
|> Map.add "avifile" { in_spam=0; in_ham=6}
|> Map.add "avittaa" { in_spam=0; in_ham=4}
|> Map.add "avoid" { in_spam=15; in_ham=41}
|> Map.add "avoided" { in_spam=0; in_ham=6}
|> Map.add "avoiding" { in_spam=0; in_ham=6}
|> Map.add "avoids" { in_spam=3; in_ham=2}
|> Map.add "await" { in_spam=3; in_ham=4}
|> Map.add "awaiting" { in_spam=4; in_ham=1}
|> Map.add "award" { in_spam=4; in_ham=5}
|> Map.add "awarded" { in_spam=7; in_ham=2}
|> Map.add "awards" { in_spam=0; in_ham=7}
|> Map.add "aware" { in_spam=5; in_ham=31}
|> Map.add "awareness" { in_spam=1; in_ham=4}
|> Map.add "away" { in_spam=25; in_ham=112}
|> Map.add "awesome" { in_spam=1; in_ham=3}
|> Map.add "awful" { in_spam=0; in_ham=9}
|> Map.add "awfully" { in_spam=0; in_ham=7}
|> Map.add "awhile" { in_spam=1; in_ham=6}
|> Map.add "awkward" { in_spam=0; in_ham=4}
|> Map.add "awl" { in_spam=0; in_ham=4}
|> Map.add "awubpy" { in_spam=0; in_ham=3}
|> Map.add "axel" { in_spam=0; in_ham=12}
|> Map.add "b'far" { in_spam=0; in_ham=12}
|> Map.add "baartman" { in_spam=0; in_ham=9}
|> Map.add "babies" { in_spam=1; in_ham=6}
|> Map.add "baby" { in_spam=5; in_ham=17}
|> Map.add "back" { in_spam=48; in_ham=227}
|> Map.add "back-end" { in_spam=0; in_ham=6}
|> Map.add "backdoor" { in_spam=0; in_ham=5}
|> Map.add "backed" { in_spam=0; in_ham=6}
|> Map.add "backend" { in_spam=0; in_ham=3}
|> Map.add "background" { in_spam=26; in_ham=27}
|> Map.add "backing" { in_spam=7; in_ham=2}
|> Map.add "backissues" { in_spam=0; in_ham=56}
|> Map.add "backrubs" { in_spam=0; in_ham=5}
|> Map.add "backs" { in_spam=0; in_ham=6}
|> Map.add "backspace" { in_spam=0; in_ham=4}
|> Map.add "backup" { in_spam=21; in_ham=19}
|> Map.add "backuping" { in_spam=0; in_ham=4}
|> Map.add "backups" { in_spam=1; in_ham=3}
|> Map.add "backward" { in_spam=3; in_ham=5}
|> Map.add "backwards" { in_spam=1; in_ham=4}
|> Map.add "bacon" { in_spam=0; in_ham=6}
|> Map.add "bacteria" { in_spam=0; in_ham=3}
|> Map.add "bad" { in_spam=11; in_ham=102}
|> Map.add "badge" { in_spam=0; in_ham=7}
|> Map.add "badly" { in_spam=0; in_ham=12}
|> Map.add "baffled" { in_spam=0; in_ham=9}
|> Map.add "bag" { in_spam=3; in_ham=5}
|> Map.add "bags" { in_spam=1; in_ham=5}
|> Map.add "bail" { in_spam=0; in_ham=4}
|> Map.add "bait" { in_spam=0; in_ham=3}
|> Map.add "baj" { in_spam=0; in_ham=3}
|> Map.add "balance" { in_spam=4; in_ham=16}
|> Map.add "balanced" { in_spam=1; in_ham=2}
|> Map.add "balancer" { in_spam=0; in_ham=6}
|> Map.add "balancers" { in_spam=0; in_ham=6}
|> Map.add "balances" { in_spam=0; in_ham=5}
|> Map.add "balancing" { in_spam=0; in_ham=11}
|> Map.add "ball" { in_spam=0; in_ham=4}
|> Map.add "ballantine" { in_spam=0; in_ham=4}
|> Map.add "ballistic" { in_spam=0; in_ham=3}
|> Map.add "balloon" { in_spam=0; in_ham=8}
|> Map.add "balloons" { in_spam=0; in_ham=4}
|> Map.add "ballot" { in_spam=1; in_ham=2}
|> Map.add "balls" { in_spam=0; in_ham=10}
|> Map.add "baltimore" { in_spam=1; in_ham=3}
|> Map.add "ban" { in_spam=2; in_ham=5}
|> Map.add "band" { in_spam=1; in_ham=6}
|> Map.add "bandwidth" { in_spam=2; in_ham=28}
|> Map.add "bang" { in_spam=2; in_ham=7}
|> Map.add "bangkok" { in_spam=1; in_ham=3}
|> Map.add "bank" { in_spam=36; in_ham=23}
|> Map.add "bank's" { in_spam=0; in_ham=5}
|> Map.add "bankers" { in_spam=7; in_ham=3}
|> Map.add "banking" { in_spam=3; in_ham=12}
|> Map.add "bankrupt" { in_spam=0; in_ham=4}
|> Map.add "bankruptcy" { in_spam=6; in_ham=2}
|> Map.add "banks" { in_spam=6; in_ham=4}
|> Map.add "banned" { in_spam=0; in_ham=5}
|> Map.add "banner" { in_spam=5; in_ham=4}
|> Map.add "banners" { in_spam=3; in_ham=1}
|> Map.add "banning" { in_spam=0; in_ham=4}
|> Map.add "bar" { in_spam=7; in_ham=20}
|> Map.add "barbara" { in_spam=0; in_ham=7}
|> Map.add "barcelona" { in_spam=0; in_ham=42}
|> Map.add "bare" { in_spam=1; in_ham=3}
|> Map.add "barely" { in_spam=2; in_ham=3}
|> Map.add "bargain" { in_spam=0; in_ham=3}
|> Map.add "barney" { in_spam=0; in_ham=5}
|> Map.add "baroness" { in_spam=0; in_ham=9}
|> Map.add "barrera" { in_spam=0; in_ham=27}
|> Map.add "barrier" { in_spam=1; in_ham=3}
|> Map.add "barriers" { in_spam=1; in_ham=7}
|> Map.add "barrister" { in_spam=5; in_ham=0}
|> Map.add "barry" { in_spam=1; in_ham=18}
|> Map.add "barry's" { in_spam=0; in_ham=4}
|> Map.add "bars" { in_spam=0; in_ham=10}
|> Map.add "bart" { in_spam=0; in_ham=3}
|> Map.add "bas" { in_spam=5; in_ham=1}
|> Map.add "base" { in_spam=12; in_ham=58}
|> Map.add "based" { in_spam=33; in_ham=100}
|> Map.add "baseline" { in_spam=2; in_ham=2}
|> Map.add "bases" { in_spam=1; in_ham=5}
|> Map.add "baset" { in_spam=0; in_ham=6}
|> Map.add "basetel" { in_spam=6; in_ham=0}
|> Map.add "bash" { in_spam=0; in_ham=4}
|> Map.add "basic" { in_spam=12; in_ham=38}
|> Map.add "basically" { in_spam=1; in_ham=34}
|> Map.add "basis" { in_spam=3; in_ham=30}
|> Map.add "basket" { in_spam=0; in_ham=3}
|> Map.add "bass" { in_spam=0; in_ham=3}
|> Map.add "bastards" { in_spam=0; in_ham=7}
|> Map.add "batch" { in_spam=9; in_ham=6}
|> Map.add "batches" { in_spam=0; in_ham=3}
|> Map.add "bath" { in_spam=0; in_ham=4}
|> Map.add "bathroom" { in_spam=0; in_ham=4}
|> Map.add "batteries" { in_spam=1; in_ham=6}
|> Map.add "battery" { in_spam=2; in_ham=28}
|> Map.add "battle" { in_spam=4; in_ham=23}
|> Map.add "battlefield" { in_spam=0; in_ham=4}
|> Map.add "baxter" { in_spam=0; in_ham=13}
|> Map.add "bay" { in_spam=0; in_ham=21}
|> Map.add "bayarea" { in_spam=0; in_ham=4}
|> Map.add "bayes" { in_spam=0; in_ham=9}
|> Map.add "bayesian" { in_spam=0; in_ham=4}
|> Map.add "bb-april" { in_spam=0; in_ham=4}
|> Map.add "bbc" { in_spam=0; in_ham=28}
|> Map.add "bbs" { in_spam=1; in_ham=4}
|> Map.add "bdd" { in_spam=0; in_ham=6}
|> Map.add "bddf" { in_spam=0; in_ham=3}
|> Map.add "bea" { in_spam=0; in_ham=6}
|> Map.add "beach" { in_spam=1; in_ham=17}
|> Map.add "bear" { in_spam=1; in_ham=13}
|> Map.add "bearer" { in_spam=0; in_ham=43}
|> Map.add "bearing" { in_spam=3; in_ham=3}
|> Map.add "bears" { in_spam=0; in_ham=5}
|> Map.add "beast" { in_spam=0; in_ham=5}
|> Map.add "beat" { in_spam=18; in_ham=22}
|> Map.add "beaten" { in_spam=0; in_ham=7}
|> Map.add "beating" { in_spam=0; in_ham=12}
|> Map.add "beats" { in_spam=2; in_ham=4}
|> Map.add "beautiful" { in_spam=11; in_ham=15}
|> Map.add "beauty" { in_spam=2; in_ham=6}
|> Map.add "beberg" { in_spam=0; in_ham=61}
|> Map.add "became" { in_spam=2; in_ham=41}
|> Map.add "because" { in_spam=108; in_ham=415}
|> Map.add "become" { in_spam=29; in_ham=73}
|> Map.add "becomes" { in_spam=1; in_ham=23}
|> Map.add "becoming" { in_spam=1; in_ham=24}
|> Map.add "bed" { in_spam=5; in_ham=14}
|> Map.add "bedroom" { in_spam=4; in_ham=2}
|> Map.add "bedtime" { in_spam=1; in_ham=3}
|> Map.add "bee" { in_spam=1; in_ham=5}
|> Map.add "beeing" { in_spam=0; in_ham=3}
|> Map.add "been" { in_spam=103; in_ham=501}
|> Map.add "beer" { in_spam=1; in_ham=8}
|> Map.add "before" { in_spam=51; in_ham=271}
|> Map.add "beforehand" { in_spam=0; in_ham=3}
|> Map.add "befw" { in_spam=0; in_ham=3}
|> Map.add "beg" { in_spam=0; in_ham=3}
|> Map.add "began" { in_spam=6; in_ham=17}
|> Map.add "begin" { in_spam=12; in_ham=140}
|> Map.add "begining" { in_spam=0; in_ham=4}
|> Map.add "beginner" { in_spam=0; in_ham=4}
|> Map.add "beginners" { in_spam=5; in_ham=0}
|> Map.add "beginning" { in_spam=3; in_ham=42}
|> Map.add "beginnings" { in_spam=0; in_ham=3}
|> Map.add "begins" { in_spam=1; in_ham=12}
|> Map.add "begun" { in_spam=1; in_ham=14}
|> Map.add "behalf" { in_spam=7; in_ham=83}
|> Map.add "behave" { in_spam=0; in_ham=3}
|> Map.add "behaving" { in_spam=0; in_ham=4}
|> Map.add "behavior" { in_spam=4; in_ham=33}
|> Map.add "behaviors" { in_spam=0; in_ham=4}
|> Map.add "behaviour" { in_spam=0; in_ham=19}
|> Map.add "behind" { in_spam=10; in_ham=49}
|> Map.add "beijing" { in_spam=0; in_ham=3}
|> Map.add "being" { in_spam=64; in_ham=283}
|> Map.add "belief" { in_spam=2; in_ham=11}
|> Map.add "beliefs" { in_spam=1; in_ham=14}
|> Map.add "believe" { in_spam=37; in_ham=94}
|> Map.add "believed" { in_spam=8; in_ham=16}
|> Map.add "believer" { in_spam=0; in_ham=3}
|> Map.add "believes" { in_spam=2; in_ham=28}
|> Map.add "believing" { in_spam=2; in_ham=4}
|> Map.add "bell" { in_spam=0; in_ham=35}
|> Map.add "belle" { in_spam=0; in_ham=4}
|> Map.add "bells" { in_spam=0; in_ham=5}
|> Map.add "belong" { in_spam=7; in_ham=5}
|> Map.add "belonging" { in_spam=0; in_ham=4}
|> Map.add "belongings" { in_spam=6; in_ham=1}
|> Map.add "belongs" { in_spam=0; in_ham=3}
|> Map.add "beloved" { in_spam=1; in_ham=3}
|> Map.add "below" { in_spam=123; in_ham=54}
|> Map.add "belt" { in_spam=0; in_ham=4}
|> Map.add "ben" { in_spam=4; in_ham=32}
|> Map.add "benchmarks" { in_spam=0; in_ham=4}
|> Map.add "beneath" { in_spam=3; in_ham=7}
|> Map.add "beneficial" { in_spam=3; in_ham=3}
|> Map.add "beneficiary" { in_spam=9; in_ham=1}
|> Map.add "benefit" { in_spam=25; in_ham=33}
|> Map.add "benefits" { in_spam=17; in_ham=19}
|> Map.add "benefitting" { in_spam=2; in_ham=2}
|> Map.add "benjamin" { in_spam=0; in_ham=3}
|> Map.add "bent" { in_spam=1; in_ham=6}
|> Map.add "bentley" { in_spam=0; in_ham=6}
|> Map.add "ber" { in_spam=1; in_ham=3}
|> Map.add "berkeley" { in_spam=0; in_ham=21}
|> Map.add "berlin" { in_spam=1; in_ham=6}
|> Map.add "bernard" { in_spam=0; in_ham=4}
|> Map.add "berry" { in_spam=1; in_ham=5}
|> Map.add "beside" { in_spam=0; in_ham=3}
|> Map.add "besides" { in_spam=0; in_ham=14}
|> Map.add "best" { in_spam=100; in_ham=210}
|> Map.add "bet" { in_spam=2; in_ham=13}
|> Map.add "beta" { in_spam=0; in_ham=20}
|> Map.add "betas" { in_spam=0; in_ham=6}
|> Map.add "betcha" { in_spam=0; in_ham=7}
|> Map.add "betray" { in_spam=5; in_ham=4}
|> Map.add "betrayal" { in_spam=1; in_ham=2}
|> Map.add "better" { in_spam=35; in_ham=216}
|> Map.add "betting" { in_spam=0; in_ham=3}
|> Map.add "between" { in_spam=7; in_ham=182}
|> Map.add "beucase" { in_spam=0; in_ham=3}
|> Map.add "beverley" { in_spam=1; in_ham=2}
|> Map.add "beware" { in_spam=0; in_ham=4}
|> Map.add "beyond" { in_spam=3; in_ham=33}
|> Map.add "bgcolor" { in_spam=170; in_ham=5}
|> Map.add "bias" { in_spam=0; in_ham=6}
|> Map.add "biased" { in_spam=1; in_ham=12}
|> Map.add "biases" { in_spam=0; in_ham=3}
|> Map.add "bible" { in_spam=0; in_ham=3}
|> Map.add "biblical" { in_spam=0; in_ham=4}
|> Map.add "bid" { in_spam=1; in_ham=7}
|> Map.add "bidder" { in_spam=0; in_ham=3}
|> Map.add "big" { in_spam=32; in_ham=122}
|> Map.add "bigfoot" { in_spam=6; in_ham=1}
|> Map.add "bigger" { in_spam=1; in_ham=23}
|> Map.add "biggest" { in_spam=12; in_ham=34}
|> Map.add "bike" { in_spam=2; in_ham=3}
|> Map.add "bilk" { in_spam=0; in_ham=4}
|> Map.add "bill" { in_spam=26; in_ham=68}
|> Map.add "billing" { in_spam=3; in_ham=1}
|> Map.add "billion" { in_spam=16; in_ham=24}
|> Map.add "billions" { in_spam=3; in_ham=10}
|> Map.add "bills" { in_spam=16; in_ham=3}
|> Map.add "billy" { in_spam=0; in_ham=5}
|> Map.add "bin" { in_spam=0; in_ham=39}
|> Map.add "binaries" { in_spam=0; in_ham=4}
|> Map.add "binary" { in_spam=0; in_ham=30}
|> Map.add "bind" { in_spam=0; in_ham=6}
|> Map.add "binding" { in_spam=0; in_ham=6}
|> Map.add "bindings" { in_spam=0; in_ham=15}
|> Map.add "bio" { in_spam=3; in_ham=1}
|> Map.add "biological" { in_spam=0; in_ham=9}
|> Map.add "biologist" { in_spam=0; in_ham=4}
|> Map.add "biology" { in_spam=0; in_ham=4}
|> Map.add "bios" { in_spam=0; in_ham=3}
|> Map.add "birch" { in_spam=0; in_ham=5}
|> Map.add "bird" { in_spam=0; in_ham=3}
|> Map.add "birds" { in_spam=1; in_ham=6}
|> Map.add "birth" { in_spam=4; in_ham=7}
|> Map.add "birthright" { in_spam=0; in_ham=3}
|> Map.add "bit" { in_spam=15; in_ham=143}
|> Map.add "bit'" { in_spam=0; in_ham=3}
|> Map.add "bitbitch" { in_spam=0; in_ham=57}
|> Map.add "bitch" { in_spam=0; in_ham=4}
|> Map.add "bite" { in_spam=0; in_ham=9}
|> Map.add "bits" { in_spam=1; in_ham=38}
|> Map.add "bitten" { in_spam=0; in_ham=3}
|> Map.add "bitter" { in_spam=0; in_ham=6}
|> Map.add "biz" { in_spam=8; in_ham=25}
|> Map.add "bizarre" { in_spam=0; in_ham=12}
|> Map.add "bjk" { in_spam=6; in_ham=0}
|> Map.add "bkc" { in_spam=0; in_ham=3}
|> Map.add "bkclements" { in_spam=0; in_ham=3}
|> Map.add "black" { in_spam=38; in_ham=40}
|> Map.add "blackcomb" { in_spam=0; in_ham=5}
|> Map.add "blackmail" { in_spam=0; in_ham=4}
|> Map.add "blackouts" { in_spam=0; in_ham=6}
|> Map.add "blah" { in_spam=0; in_ham=6}
|> Map.add "blair" { in_spam=1; in_ham=18}
|> Map.add "blair'" { in_spam=0; in_ham=5}
|> Map.add "blair's" { in_spam=0; in_ham=11}
|> Map.add "blame" { in_spam=0; in_ham=27}
|> Map.add "blamed" { in_spam=0; in_ham=9}
|> Map.add "blaming" { in_spam=1; in_ham=6}
|> Map.add "blank" { in_spam=30; in_ham=5}
|> Map.add "blanket" { in_spam=1; in_ham=3}
|> Map.add "blast" { in_spam=2; in_ham=7}
|> Map.add "blatant" { in_spam=2; in_ham=3}
|> Map.add "blatantly" { in_spam=0; in_ham=4}
|> Map.add "bleeding" { in_spam=0; in_ham=3}
|> Map.add "bleedings" { in_spam=0; in_ham=3}
|> Map.add "blending" { in_spam=0; in_ham=3}
|> Map.add "blends" { in_spam=1; in_ham=3}
|> Map.add "bless" { in_spam=10; in_ham=4}
|> Map.add "blessed" { in_spam=3; in_ham=2}
|> Map.add "blessing" { in_spam=0; in_ham=3}
|> Map.add "bletchley" { in_spam=0; in_ham=3}
|> Map.add "blew" { in_spam=0; in_ham=10}
|> Map.add "blib" { in_spam=0; in_ham=3}
|> Map.add "blind" { in_spam=0; in_ham=21}
|> Map.add "blindly" { in_spam=0; in_ham=6}
|> Map.add "bliss" { in_spam=0; in_ham=10}
|> Map.add "bloat" { in_spam=0; in_ham=10}
|> Map.add "blob" { in_spam=0; in_ham=3}
|> Map.add "block" { in_spam=1; in_ham=31}
|> Map.add "blockage" { in_spam=0; in_ham=4}
|> Map.add "blocked" { in_spam=2; in_ham=9}
|> Map.add "blocking" { in_spam=0; in_ham=9}
|> Map.add "blockquote" { in_spam=12; in_ham=3}
|> Map.add "blocks" { in_spam=0; in_ham=7}
|> Map.add "blog" { in_spam=0; in_ham=79}
|> Map.add "bloggers" { in_spam=0; in_ham=4}
|> Map.add "blogging" { in_spam=0; in_ham=5}
|> Map.add "blogspot" { in_spam=0; in_ham=7}
|> Map.add "blood" { in_spam=3; in_ham=23}
|> Map.add "bloody" { in_spam=1; in_ham=7}
|> Map.add "blow" { in_spam=1; in_ham=13}
|> Map.add "blowing" { in_spam=1; in_ham=3}
|> Map.add "blows" { in_spam=0; in_ham=5}
|> Map.add "blue" { in_spam=14; in_ham=23}
|> Map.add "blueprint" { in_spam=3; in_ham=2}
|> Map.add "blunt" { in_spam=0; in_ham=3}
|> Map.add "blurb" { in_spam=0; in_ham=6}
|> Map.add "blurred" { in_spam=0; in_ham=4}
|> Map.add "blvd" { in_spam=3; in_ham=2}
|> Map.add "bmc" { in_spam=0; in_ham=3}
|> Map.add "bml" { in_spam=0; in_ham=10}
|> Map.add "board" { in_spam=0; in_ham=30}
|> Map.add "boards" { in_spam=0; in_ham=4}
|> Map.add "boat" { in_spam=4; in_ham=5}
|> Map.add "bob" { in_spam=1; in_ham=22}
|> Map.add "bobby" { in_spam=0; in_ham=8}
|> Map.add "bobm" { in_spam=0; in_ham=3}
|> Map.add "boca" { in_spam=3; in_ham=1}
|> Map.add "bodies" { in_spam=0; in_ham=12}
|> Map.add "body" { in_spam=229; in_ham=60}
|> Map.add "boggled" { in_spam=0; in_ham=4}
|> Map.add "bogofilter" { in_spam=0; in_ham=3}
|> Map.add "bogus" { in_spam=1; in_ham=10}
|> Map.add "boing" { in_spam=0; in_ham=98}
|> Map.add "boingboing" { in_spam=0; in_ham=114}
|> Map.add "bolcer" { in_spam=0; in_ham=17}
|> Map.add "bold" { in_spam=18; in_ham=6}
|> Map.add "bolster" { in_spam=0; in_ham=3}
|> Map.add "bomb" { in_spam=0; in_ham=5}
|> Map.add "bombing" { in_spam=0; in_ham=5}
|> Map.add "bond" { in_spam=0; in_ham=6}
|> Map.add "bonded" { in_spam=1; in_ham=3}
|> Map.add "bondedsender" { in_spam=0; in_ham=3}
|> Map.add "bonds" { in_spam=1; in_ham=2}
|> Map.add "bone" { in_spam=0; in_ham=9}
|> Map.add "bones" { in_spam=3; in_ham=6}
|> Map.add "bonus" { in_spam=22; in_ham=8}
|> Map.add "bonuses" { in_spam=7; in_ham=2}
|> Map.add "book" { in_spam=13; in_ham=52}
|> Map.add "bookmobile" { in_spam=0; in_ham=4}
|> Map.add "books" { in_spam=11; in_ham=26}
|> Map.add "bookstores" { in_spam=0; in_ham=3}
|> Map.add "boom" { in_spam=0; in_ham=9}
|> Map.add "booming" { in_spam=2; in_ham=2}
|> Map.add "boost" { in_spam=3; in_ham=8}
|> Map.add "boot" { in_spam=1; in_ham=18}
|> Map.add "bootable" { in_spam=0; in_ham=4}
|> Map.add "booting" { in_spam=0; in_ham=3}
|> Map.add "bootstraps" { in_spam=0; in_ham=4}
|> Map.add "bootup" { in_spam=0; in_ham=4}
|> Map.add "boquist" { in_spam=0; in_ham=3}
|> Map.add "border" { in_spam=172; in_ham=10}
|> Map.add "border-left" { in_spam=6; in_ham=2}
|> Map.add "border-style" { in_spam=5; in_ham=0}
|> Map.add "border-width" { in_spam=7; in_ham=0}
|> Map.add "bordercolor" { in_spam=90; in_ham=1}
|> Map.add "borders" { in_spam=0; in_ham=8}
|> Map.add "bored" { in_spam=0; in_ham=11}
|> Map.add "boring" { in_spam=2; in_ham=8}
|> Map.add "born" { in_spam=1; in_ham=15}
|> Map.add "borrow" { in_spam=3; in_ham=7}
|> Map.add "borrowing" { in_spam=0; in_ham=3}
|> Map.add "bort" { in_spam=0; in_ham=4}
|> Map.add "boss" { in_spam=5; in_ham=7}
|> Map.add "boston" { in_spam=0; in_ham=47}
|> Map.add "bot" { in_spam=4; in_ham=6}
|> Map.add "both" { in_spam=41; in_ham=187}
|> Map.add "bother" { in_spam=1; in_ham=22}
|> Map.add "bothered" { in_spam=2; in_ham=7}
|> Map.add "bottle" { in_spam=4; in_ham=6}
|> Map.add "bottleneck" { in_spam=0; in_ham=6}
|> Map.add "bottles" { in_spam=6; in_ham=0}
|> Map.add "bottom" { in_spam=22; in_ham=31}
|> Map.add "bought" { in_spam=7; in_ham=20}
|> Map.add "bounce" { in_spam=0; in_ham=7}
|> Map.add "bounced" { in_spam=0; in_ham=3}
|> Map.add "bounces" { in_spam=0; in_ham=6}
|> Map.add "bound" { in_spam=7; in_ham=13}
|> Map.add "boundaries" { in_spam=1; in_ham=9}
|> Map.add "boundary" { in_spam=1; in_ham=5}
|> Map.add "bounty" { in_spam=0; in_ham=3}
|> Map.add "bow" { in_spam=0; in_ham=8}
|> Map.add "bowel" { in_spam=0; in_ham=4}
|> Map.add "bowl" { in_spam=0; in_ham=5}
|> Map.add "box" { in_spam=20; in_ham=85}
|> Map.add "boxes" { in_spam=9; in_ham=13}
|> Map.add "boy" { in_spam=4; in_ham=24}
|> Map.add "boyfriend" { in_spam=3; in_ham=1}
|> Map.add "boys" { in_spam=3; in_ham=10}
|> Map.add "bra" { in_spam=5; in_ham=1}
|> Map.add "brad" { in_spam=1; in_ham=6}
|> Map.add "brady" { in_spam=0; in_ham=3}
|> Map.add "brain" { in_spam=4; in_ham=26}
|> Map.add "branch" { in_spam=4; in_ham=9}
|> Map.add "branches" { in_spam=1; in_ham=3}
|> Map.add "brand" { in_spam=12; in_ham=9}
|> Map.add "branded" { in_spam=0; in_ham=3}
|> Map.add "brands" { in_spam=5; in_ham=1}
|> Map.add "brass" { in_spam=1; in_ham=3}
|> Map.add "brave" { in_spam=0; in_ham=3}
|> Map.add "brazil" { in_spam=4; in_ham=4}
|> Map.add "brazilian" { in_spam=0; in_ham=3}
|> Map.add "breach" { in_spam=1; in_ham=2}
|> Map.add "bread" { in_spam=1; in_ham=2}
|> Map.add "breadth" { in_spam=0; in_ham=4}
|> Map.add "break" { in_spam=3; in_ham=55}
|> Map.add "breakage" { in_spam=0; in_ham=4}
|> Map.add "breakdown" { in_spam=0; in_ham=3}
|> Map.add "breaking" { in_spam=2; in_ham=14}
|> Map.add "breaks" { in_spam=0; in_ham=11}
|> Map.add "breakthrough" { in_spam=1; in_ham=6}
|> Map.add "breasts" { in_spam=5; in_ham=2}
|> Map.add "breath" { in_spam=0; in_ham=3}
|> Map.add "breathe" { in_spam=0; in_ham=6}
|> Map.add "breed" { in_spam=0; in_ham=3}
|> Map.add "breeding" { in_spam=0; in_ham=5}
|> Map.add "breeds" { in_spam=1; in_ham=3}
|> Map.add "breeze" { in_spam=0; in_ham=3}
|> Map.add "brendan" { in_spam=0; in_ham=4}
|> Map.add "brent" { in_spam=0; in_ham=36}
|> Map.add "brevity" { in_spam=0; in_ham=3}
|> Map.add "brian" { in_spam=2; in_ham=35}
|> Map.add "brick" { in_spam=0; in_ham=4}
|> Map.add "brickbats" { in_spam=0; in_ham=7}
|> Map.add "bridge" { in_spam=0; in_ham=14}
|> Map.add "bridges" { in_spam=0; in_ham=5}
|> Map.add "brief" { in_spam=6; in_ham=22}
|> Map.add "briefing" { in_spam=0; in_ham=3}
|> Map.add "briefly" { in_spam=2; in_ham=8}
|> Map.add "bright" { in_spam=0; in_ham=16}
|> Map.add "brighter" { in_spam=1; in_ham=2}
|> Map.add "brightest" { in_spam=0; in_ham=4}
|> Map.add "brighton" { in_spam=0; in_ham=11}
|> Map.add "brilliant" { in_spam=0; in_ham=4}
|> Map.add "bring" { in_spam=7; in_ham=34}
|> Map.add "bringing" { in_spam=3; in_ham=11}
|> Map.add "brings" { in_spam=1; in_ham=21}
|> Map.add "britain" { in_spam=2; in_ham=18}
|> Map.add "britain's" { in_spam=0; in_ham=12}
|> Map.add "british" { in_spam=8; in_ham=37}
|> Map.add "briton" { in_spam=0; in_ham=3}
|> Map.add "britons" { in_spam=0; in_ham=6}
|> Map.add "broad" { in_spam=2; in_ham=18}
|> Map.add "broadband" { in_spam=1; in_ham=4}
|> Map.add "broadcast" { in_spam=2; in_ham=5}
|> Map.add "broadcaster" { in_spam=0; in_ham=5}
|> Map.add "broadcasters" { in_spam=1; in_ham=4}
|> Map.add "broadcasting" { in_spam=1; in_ham=10}
|> Map.add "broadening" { in_spam=0; in_ham=3}
|> Map.add "broader" { in_spam=0; in_ham=7}
|> Map.add "broadest" { in_spam=0; in_ham=5}
|> Map.add "brochure" { in_spam=0; in_ham=3}
|> Map.add "broke" { in_spam=1; in_ham=6}
|> Map.add "broken" { in_spam=1; in_ham=32}
|> Map.add "broker" { in_spam=12; in_ham=5}
|> Map.add "brokerage" { in_spam=5; in_ham=0}
|> Map.add "brokers" { in_spam=5; in_ham=1}
|> Map.add "bronze" { in_spam=0; in_ham=4}
|> Map.add "brother" { in_spam=4; in_ham=2}
|> Map.add "brothers" { in_spam=0; in_ham=5}
|> Map.add "brought" { in_spam=8; in_ham=28}
|> Map.add "brown" { in_spam=2; in_ham=9}
|> Map.add "browse" { in_spam=2; in_ham=4}
|> Map.add "browser" { in_spam=14; in_ham=23}
|> Map.add "browser's" { in_spam=4; in_ham=1}
|> Map.add "browsers" { in_spam=4; in_ham=5}
|> Map.add "browsing" { in_spam=1; in_ham=6}
|> Map.add "bruce" { in_spam=0; in_ham=10}
|> Map.add "brutalize" { in_spam=0; in_ham=4}
|> Map.add "bryan" { in_spam=0; in_ham=3}
|> Map.add "bsd" { in_spam=0; in_ham=4}
|> Map.add "btamail" { in_spam=24; in_ham=0}
|> Map.add "btnsubmit" { in_spam=25; in_ham=0}
|> Map.add "btw" { in_spam=0; in_ham=58}
|> Map.add "bubble" { in_spam=2; in_ham=4}
|> Map.add "bubbles" { in_spam=0; in_ham=5}
|> Map.add "buckminster" { in_spam=0; in_ham=3}
|> Map.add "bucks" { in_spam=13; in_ham=9}
|> Map.add "buddhism" { in_spam=0; in_ham=5}
|> Map.add "buddies" { in_spam=0; in_ham=3}
|> Map.add "buddy" { in_spam=0; in_ham=4}
|> Map.add "budget" { in_spam=4; in_ham=10}
|> Map.add "budgets" { in_spam=0; in_ham=3}
|> Map.add "buf" { in_spam=0; in_ham=3}
|> Map.add "buff" { in_spam=0; in_ham=7}
|> Map.add "buffer" { in_spam=0; in_ham=20}
|> Map.add "bug" { in_spam=1; in_ham=98}
|> Map.add "bugs" { in_spam=0; in_ham=26}
|> Map.add "bugzilla" { in_spam=0; in_ham=39}
|> Map.add "build" { in_spam=15; in_ham=167}
|> Map.add "build-up" { in_spam=0; in_ham=4}
|> Map.add "builder" { in_spam=3; in_ham=1}
|> Map.add "building" { in_spam=10; in_ham=71}
|> Map.add "buildings" { in_spam=3; in_ham=7}
|> Map.add "buildroot" { in_spam=0; in_ham=5}
|> Map.add "builds" { in_spam=0; in_ham=22}
|> Map.add "buildup" { in_spam=4; in_ham=1}
|> Map.add "built" { in_spam=1; in_ham=63}
|> Map.add "built-in" { in_spam=1; in_ham=9}
|> Map.add "bulk" { in_spam=14; in_ham=8}
|> Map.add "bulky" { in_spam=0; in_ham=3}
|> Map.add "bull" { in_spam=7; in_ham=0}
|> Map.add "bullet" { in_spam=5; in_ham=3}
|> Map.add "bulletin" { in_spam=3; in_ham=3}
|> Map.add "bullets" { in_spam=1; in_ham=2}
|> Map.add "bullshit" { in_spam=0; in_ham=4}
|> Map.add "bump" { in_spam=0; in_ham=6}
|> Map.add "bunch" { in_spam=0; in_ham=43}
|> Map.add "bundle" { in_spam=2; in_ham=3}
|> Map.add "bundling" { in_spam=0; in_ham=9}
|> Map.add "burden" { in_spam=2; in_ham=4}
|> Map.add "bureau" { in_spam=9; in_ham=1}
|> Map.add "bureaucracy" { in_spam=0; in_ham=5}
|> Map.add "bureaucratic" { in_spam=0; in_ham=3}
|> Map.add "burgeoning" { in_spam=0; in_ham=3}
|> Map.add "burger" { in_spam=0; in_ham=9}
|> Map.add "buried" { in_spam=3; in_ham=12}
|> Map.add "burn" { in_spam=7; in_ham=10}
|> Map.add "burned" { in_spam=3; in_ham=8}
|> Map.add "burner" { in_spam=3; in_ham=1}
|> Map.add "burnham" { in_spam=0; in_ham=6}
|> Map.add "burning" { in_spam=13; in_ham=10}
|> Map.add "burningbird" { in_spam=0; in_ham=7}
|> Map.add "burns" { in_spam=2; in_ham=7}
|> Map.add "burnt" { in_spam=1; in_ham=2}
|> Map.add "burr" { in_spam=0; in_ham=6}
|> Map.add "bury" { in_spam=0; in_ham=5}
|> Map.add "bus" { in_spam=5; in_ham=16}
|> Map.add "bush" { in_spam=1; in_ham=39}
|> Map.add "bush's" { in_spam=0; in_ham=19}
|> Map.add "business" { in_spam=103; in_ham=137}
|> Map.add "businesses" { in_spam=8; in_ham=27}
|> Map.add "businessman" { in_spam=1; in_ham=2}
|> Map.add "businessmen" { in_spam=1; in_ham=3}
|> Map.add "bust" { in_spam=4; in_ham=5}
|> Map.add "busy" { in_spam=7; in_ham=18}
|> Map.add "but" { in_spam=83; in_ham=1125}
|> Map.add "butt" { in_spam=0; in_ham=5}
|> Map.add "button" { in_spam=15; in_ham=39}
|> Map.add "buttons" { in_spam=3; in_ham=3}
|> Map.add "buy" { in_spam=62; in_ham=54}
|> Map.add "buyer" { in_spam=1; in_ham=3}
|> Map.add "buyers" { in_spam=11; in_ham=2}
|> Map.add "buying" { in_spam=19; in_ham=16}
|> Map.add "buys" { in_spam=3; in_ham=4}
|> Map.add "bypass" { in_spam=1; in_ham=4}
|> Map.add "byrne" { in_spam=0; in_ham=17}
|> Map.add "byte" { in_spam=0; in_ham=3}
|> Map.add "bytecode" { in_spam=0; in_ham=7}
|> Map.add "bytes" { in_spam=0; in_ham=25}
|> Map.add "bzzt" { in_spam=0; in_ham=5}
|> Map.add "c'est" { in_spam=0; in_ham=3}
|> Map.add "cab" { in_spam=1; in_ham=11}
|> Map.add "cabeen" { in_spam=0; in_ham=4}
|> Map.add "cabin" { in_spam=0; in_ham=4}
|> Map.add "cabinet" { in_spam=6; in_ham=2}
|> Map.add "cable" { in_spam=5; in_ham=21}
|> Map.add "cables" { in_spam=0; in_ham=4}
|> Map.add "cac" { in_spam=1; in_ham=2}
|> Map.add "cache" { in_spam=0; in_ham=25}
|> Map.add "cached" { in_spam=0; in_ham=8}
|> Map.add "caches" { in_spam=0; in_ham=6}
|> Map.add "caching" { in_spam=0; in_ham=12}
|> Map.add "cafe" { in_spam=0; in_ham=8}
|> Map.add "cafeforteana" { in_spam=0; in_ham=6}
|> Map.add "cafes" { in_spam=0; in_ham=4}
|> Map.add "cafeteria" { in_spam=3; in_ham=1}
|> Map.add "caffeine" { in_spam=1; in_ham=2}
|> Map.add "cairo" { in_spam=0; in_ham=7}
|> Map.add "cake" { in_spam=1; in_ham=7}
|> Map.add "cakes" { in_spam=3; in_ham=3}
|> Map.add "cal-bay" { in_spam=5; in_ham=0}
|> Map.add "calamity" { in_spam=0; in_ham=3}
|> Map.add "calculate" { in_spam=9; in_ham=3}
|> Map.add "calculated" { in_spam=1; in_ham=6}
|> Map.add "calculating" { in_spam=0; in_ham=3}
|> Map.add "calculation" { in_spam=1; in_ham=2}
|> Map.add "calculations" { in_spam=1; in_ham=4}
|> Map.add "calculus" { in_spam=0; in_ham=4}
|> Map.add "calea" { in_spam=1; in_ham=2}
|> Map.add "calendar" { in_spam=2; in_ham=2}
|> Map.add "calendars" { in_spam=0; in_ham=3}
|> Map.add "calif" { in_spam=0; in_ham=6}
|> Map.add "california" { in_spam=15; in_ham=33}
|> Map.add "california's" { in_spam=0; in_ham=4}
|> Map.add "caliper" { in_spam=0; in_ham=6}
|> Map.add "call" { in_spam=78; in_ham=110}
|> Map.add "called" { in_spam=11; in_ham=113}
|> Map.add "calling" { in_spam=5; in_ham=20}
|> Map.add "callously" { in_spam=0; in_ham=4}
|> Map.add "calls" { in_spam=6; in_ham=45}
|> Map.add "calm" { in_spam=1; in_ham=6}
|> Map.add "calming" { in_spam=1; in_ham=3}
|> Map.add "caltech" { in_spam=0; in_ham=12}
|> Map.add "cambridge" { in_spam=0; in_ham=14}
|> Map.add "came" { in_spam=18; in_ham=80}
|> Map.add "camera" { in_spam=3; in_ham=12}
|> Map.add "cameras" { in_spam=0; in_ham=9}
|> Map.add "cameron" { in_spam=0; in_ham=3}
|> Map.add "camp" { in_spam=3; in_ham=5}
|> Map.add "camp'" { in_spam=0; in_ham=3}
|> Map.add "campaign" { in_spam=9; in_ham=23}
|> Map.add "campaigners" { in_spam=0; in_ham=4}
|> Map.add "campaigns" { in_spam=1; in_ham=5}
|> Map.add "campbell" { in_spam=0; in_ham=5}
|> Map.add "campus" { in_spam=1; in_ham=4}
|> Map.add "cams" { in_spam=7; in_ham=0}
|> Map.add "can" { in_spam=175; in_ham=813}
|> Map.add "can't" { in_spam=22; in_ham=274}
|> Map.add "canada" { in_spam=14; in_ham=38}
|> Map.add "canadian" { in_spam=1; in_ham=6}
|> Map.add "canadians" { in_spam=0; in_ham=4}
|> Map.add "canarsie" { in_spam=0; in_ham=3}
|> Map.add "cancel" { in_spam=6; in_ham=3}
|> Map.add "cancellation" { in_spam=2; in_ham=2}
|> Map.add "cancelled" { in_spam=0; in_ham=3}
|> Map.add "cancelling" { in_spam=0; in_ham=3}
|> Map.add "cancer" { in_spam=13; in_ham=12}
|> Map.add "candidate" { in_spam=0; in_ham=7}
|> Map.add "candidates" { in_spam=1; in_ham=16}
|> Map.add "cannibilizes" { in_spam=0; in_ham=3}
|> Map.add "cannot" { in_spam=27; in_ham=59}
|> Map.add "cant" { in_spam=0; in_ham=17}
|> Map.add "canvas" { in_spam=0; in_ham=4}
|> Map.add "capabilities" { in_spam=4; in_ham=15}
|> Map.add "capability" { in_spam=1; in_ham=13}
|> Map.add "capable" { in_spam=4; in_ham=25}
|> Map.add "capacities" { in_spam=0; in_ham=3}
|> Map.add "capacitors" { in_spam=0; in_ham=5}
|> Map.add "capacity" { in_spam=1; in_ham=14}
|> Map.add "capita" { in_spam=0; in_ham=8}
|> Map.add "capital" { in_spam=11; in_ham=32}

