open Bayesian.Database
open BayesianBody_010
let db = db 
|> Map.add "span" { in_spam=30; in_ham=13}
|> Map.add "spanish" { in_spam=1; in_ham=6}
|> Map.add "spans" { in_spam=0; in_ham=7}
|> Map.add "sparc" { in_spam=0; in_ham=5}
|> Map.add "spare" { in_spam=1; in_ham=12}
|> Map.add "spared" { in_spam=0; in_ham=3}
|> Map.add "spark" { in_spam=0; in_ham=3}
|> Map.add "sparking" { in_spam=0; in_ham=3}
|> Map.add "spawn" { in_spam=0; in_ham=7}
|> Map.add "spawned" { in_spam=0; in_ham=5}
|> Map.add "speak" { in_spam=4; in_ham=34}
|> Map.add "speaker" { in_spam=1; in_ham=6}
|> Map.add "speakers" { in_spam=1; in_ham=20}
|> Map.add "speaking" { in_spam=1; in_ham=41}
|> Map.add "speaks" { in_spam=0; in_ham=8}
|> Map.add "spearhead" { in_spam=0; in_ham=6}
|> Map.add "spearheaded" { in_spam=0; in_ham=6}
|> Map.add "spec" { in_spam=1; in_ham=61}
|> Map.add "specfile" { in_spam=0; in_ham=4}
|> Map.add "special" { in_spam=80; in_ham=56}
|> Map.add "specialist" { in_spam=11; in_ham=1}
|> Map.add "specializes" { in_spam=0; in_ham=9}
|> Map.add "specially" { in_spam=0; in_ham=4}
|> Map.add "specials" { in_spam=10; in_ham=1}
|> Map.add "species" { in_spam=0; in_ham=10}
|> Map.add "specific" { in_spam=17; in_ham=57}
|> Map.add "specifically" { in_spam=8; in_ham=41}
|> Map.add "specificly" { in_spam=0; in_ham=3}
|> Map.add "specified" { in_spam=1; in_ham=15}
|> Map.add "specifies" { in_spam=0; in_ham=6}
|> Map.add "specify" { in_spam=0; in_ham=15}
|> Map.add "specifying" { in_spam=0; in_ham=4}
|> Map.add "specs" { in_spam=0; in_ham=7}
|> Map.add "spectacular" { in_spam=0; in_ham=3}
|> Map.add "spectrum" { in_spam=0; in_ham=7}
|> Map.add "speculation" { in_spam=0; in_ham=6}
|> Map.add "sped" { in_spam=0; in_ham=4}
|> Map.add "speech" { in_spam=0; in_ham=40}
|> Map.add "speeches" { in_spam=0; in_ham=4}
|> Map.add "speed" { in_spam=7; in_ham=39}
|> Map.add "speeding" { in_spam=2; in_ham=2}
|> Map.add "speeds" { in_spam=2; in_ham=13}
|> Map.add "spell" { in_spam=2; in_ham=7}
|> Map.add "spelling" { in_spam=1; in_ham=3}
|> Map.add "spellingis" { in_spam=0; in_ham=3}
|> Map.add "spencer" { in_spam=0; in_ham=4}
|> Map.add "spend" { in_spam=8; in_ham=36}
|> Map.add "spending" { in_spam=8; in_ham=21}
|> Map.add "spends" { in_spam=1; in_ham=2}
|> Map.add "spent" { in_spam=4; in_ham=45}
|> Map.add "sphere" { in_spam=0; in_ham=3}
|> Map.add "spider" { in_spam=0; in_ham=5}
|> Map.add "spiderman" { in_spam=0; in_ham=3}
|> Map.add "spies" { in_spam=0; in_ham=6}
|> Map.add "spike" { in_spam=0; in_ham=3}
|> Map.add "spin" { in_spam=0; in_ham=10}
|> Map.add "spin-off" { in_spam=0; in_ham=6}
|> Map.add "spinning" { in_spam=0; in_ham=3}
|> Map.add "spirit" { in_spam=2; in_ham=9}
|> Map.add "spirits" { in_spam=0; in_ham=3}
|> Map.add "spit" { in_spam=0; in_ham=4}
|> Map.add "spite" { in_spam=3; in_ham=3}
|> Map.add "spits" { in_spam=0; in_ham=3}
|> Map.add "split" { in_spam=3; in_ham=25}
|> Map.add "splitting" { in_spam=0; in_ham=7}
|> Map.add "spoiled" { in_spam=0; in_ham=3}
|> Map.add "spoke" { in_spam=0; in_ham=15}
|> Map.add "spoken" { in_spam=0; in_ham=4}
|> Map.add "spokesman" { in_spam=0; in_ham=16}
|> Map.add "spokeswoman" { in_spam=0; in_ham=4}
|> Map.add "sponsor" { in_spam=4; in_ham=96}
|> Map.add "sponsored" { in_spam=4; in_ham=255}
|> Map.add "sponsors" { in_spam=1; in_ham=2}
|> Map.add "spontaneous" { in_spam=0; in_ham=5}
|> Map.add "spoof" { in_spam=0; in_ham=3}
|> Map.add "spooky" { in_spam=0; in_ham=3}
|> Map.add "spool" { in_spam=0; in_ham=6}
|> Map.add "sport" { in_spam=0; in_ham=8}
|> Map.add "sporting" { in_spam=2; in_ham=2}
|> Map.add "sports" { in_spam=7; in_ham=7}
|> Map.add "spot" { in_spam=0; in_ham=18}
|> Map.add "spots" { in_spam=0; in_ham=15}
|> Map.add "spotted" { in_spam=0; in_ham=13}
|> Map.add "spouse" { in_spam=1; in_ham=4}
|> Map.add "spouting" { in_spam=7; in_ham=0}
|> Map.add "spray" { in_spam=1; in_ham=2}
|> Map.add "spread" { in_spam=4; in_ham=13}
|> Map.add "spreading" { in_spam=0; in_ham=5}
|> Map.add "spreads" { in_spam=1; in_ham=4}
|> Map.add "spring" { in_spam=4; in_ham=18}
|> Map.add "springs" { in_spam=2; in_ham=3}
|> Map.add "sprint" { in_spam=0; in_ham=7}
|> Map.add "sprung" { in_spam=0; in_ham=4}
|> Map.add "spun" { in_spam=0; in_ham=5}
|> Map.add "spy" { in_spam=1; in_ham=11}
|> Map.add "spya" { in_spam=0; in_ham=3}
|> Map.add "sql" { in_spam=2; in_ham=6}
|> Map.add "squander" { in_spam=0; in_ham=4}
|> Map.add "square" { in_spam=4; in_ham=12}
|> Map.add "squeaky" { in_spam=0; in_ham=5}
|> Map.add "squeeze" { in_spam=0; in_ham=8}
|> Map.add "src" { in_spam=122; in_ham=42}
|> Map.add "srclist" { in_spam=0; in_ham=5}
|> Map.add "srl" { in_spam=0; in_ham=3}
|> Map.add "srpm" { in_spam=0; in_ham=5}
|> Map.add "srpms" { in_spam=0; in_ham=3}
|> Map.add "srpzmc" { in_spam=0; in_ham=7}
|> Map.add "sse" { in_spam=0; in_ham=3}
|> Map.add "ssh" { in_spam=0; in_ham=19}
|> Map.add "ssl" { in_spam=2; in_ham=12}
|> Map.add "stab" { in_spam=0; in_ham=3}
|> Map.add "stability" { in_spam=9; in_ham=9}
|> Map.add "stabilize" { in_spam=0; in_ham=3}
|> Map.add "stable" { in_spam=2; in_ham=15}
|> Map.add "stack" { in_spam=1; in_ham=4}
|> Map.add "staff" { in_spam=6; in_ham=21}
|> Map.add "stage" { in_spam=0; in_ham=14}
|> Map.add "stages" { in_spam=0; in_ham=9}
|> Map.add "staggering" { in_spam=14; in_ham=3}
|> Map.add "stairs" { in_spam=0; in_ham=3}
|> Map.add "stake" { in_spam=0; in_ham=7}
|> Map.add "stamp" { in_spam=2; in_ham=7}
|> Map.add "stamping" { in_spam=0; in_ham=5}
|> Map.add "stamps" { in_spam=2; in_ham=2}
|> Map.add "stance" { in_spam=0; in_ham=3}
|> Map.add "stand" { in_spam=7; in_ham=25}
|> Map.add "standard" { in_spam=23; in_ham=53}
|> Map.add "standardized" { in_spam=1; in_ham=4}
|> Map.add "standards" { in_spam=4; in_ham=23}
|> Map.add "standing" { in_spam=1; in_ham=6}
|> Map.add "standpoint" { in_spam=0; in_ham=3}
|> Map.add "stands" { in_spam=4; in_ham=15}
|> Map.add "stanford" { in_spam=0; in_ham=8}
|> Map.add "stanza" { in_spam=0; in_ham=9}
|> Map.add "star" { in_spam=2; in_ham=13}
|> Map.add "stark" { in_spam=0; in_ham=3}
|> Map.add "starlingtech" { in_spam=0; in_ham=3}
|> Map.add "stars" { in_spam=0; in_ham=7}
|> Map.add "start" { in_spam=50; in_ham=122}
|> Map.add "start-up" { in_spam=2; in_ham=6}
|> Map.add "start-ups" { in_spam=0; in_ham=8}
|> Map.add "started" { in_spam=28; in_ham=62}
|> Map.add "starting" { in_spam=9; in_ham=59}
|> Map.add "starts" { in_spam=4; in_ham=29}
|> Map.add "startup" { in_spam=6; in_ham=30}
|> Map.add "startups" { in_spam=0; in_ham=3}
|> Map.add "stat" { in_spam=3; in_ham=5}
|> Map.add "state" { in_spam=83; in_ham=106}
|> Map.add "state's" { in_spam=0; in_ham=4}
|> Map.add "stated" { in_spam=12; in_ham=8}
|> Map.add "stateless" { in_spam=0; in_ham=3}
|> Map.add "statement" { in_spam=5; in_ham=32}
|> Map.add "statements" { in_spam=7; in_ham=19}
|> Map.add "states" { in_spam=41; in_ham=62}
|> Map.add "states'" { in_spam=0; in_ham=4}
|> Map.add "static" { in_spam=0; in_ham=21}
|> Map.add "stating" { in_spam=1; in_ham=3}
|> Map.add "station" { in_spam=4; in_ham=11}
|> Map.add "stations" { in_spam=1; in_ham=13}
|> Map.add "statistical" { in_spam=0; in_ham=8}
|> Map.add "statistics" { in_spam=10; in_ham=19}
|> Map.add "stats" { in_spam=0; in_ham=11}
|> Map.add "statue" { in_spam=0; in_ham=3}
|> Map.add "status" { in_spam=11; in_ham=75}
|> Map.add "statutory" { in_spam=0; in_ham=5}
|> Map.add "stay" { in_spam=9; in_ham=20}
|> Map.add "stayed" { in_spam=0; in_ham=6}
|> Map.add "staying" { in_spam=5; in_ham=5}
|> Map.add "stays" { in_spam=0; in_ham=3}
|> Map.add "std" { in_spam=1; in_ham=6}
|> Map.add "stdin" { in_spam=0; in_ham=13}
|> Map.add "stdout" { in_spam=0; in_ham=12}
|> Map.add "steady" { in_spam=6; in_ham=10}
|> Map.add "steal" { in_spam=5; in_ham=8}
|> Map.add "stealing" { in_spam=4; in_ham=9}
|> Map.add "stealth" { in_spam=2; in_ham=4}
|> Map.add "steel" { in_spam=0; in_ham=7}
|> Map.add "stefan" { in_spam=0; in_ham=4}
|> Map.add "stem" { in_spam=1; in_ham=3}
|> Map.add "step" { in_spam=8; in_ham=35}
|> Map.add "step-by-step" { in_spam=9; in_ham=3}
|> Map.add "stephane" { in_spam=0; in_ham=5}
|> Map.add "stephen" { in_spam=0; in_ham=20}
|> Map.add "stepped" { in_spam=2; in_ham=9}
|> Map.add "steps" { in_spam=11; in_ham=17}
|> Map.add "stern" { in_spam=0; in_ham=8}
|> Map.add "steve" { in_spam=2; in_ham=31}
|> Map.add "stevek" { in_spam=0; in_ham=3}
|> Map.add "steven" { in_spam=1; in_ham=5}
|> Map.add "stew" { in_spam=0; in_ham=9}
|> Map.add "stewart" { in_spam=1; in_ham=7}
|> Map.add "stichele" { in_spam=0; in_ham=6}
|> Map.add "stick" { in_spam=1; in_ham=31}
|> Map.add "sticking" { in_spam=0; in_ham=6}
|> Map.add "sticks" { in_spam=0; in_ham=3}
|> Map.add "stiglitz" { in_spam=0; in_ham=3}
|> Map.add "still" { in_spam=34; in_ham=345}
|> Map.add "stir" { in_spam=0; in_ham=7}
|> Map.add "stirred" { in_spam=0; in_ham=5}
|> Map.add "stm" { in_spam=0; in_ham=14}
|> Map.add "stock" { in_spam=17; in_ham=24}
|> Map.add "stocks" { in_spam=4; in_ham=27}
|> Map.add "stoddard" { in_spam=0; in_ham=11}
|> Map.add "stole" { in_spam=0; in_ham=14}
|> Map.add "stolen" { in_spam=0; in_ham=11}
|> Map.add "stomach" { in_spam=1; in_ham=4}
|> Map.add "stone" { in_spam=1; in_ham=7}
|> Map.add "stonehorse" { in_spam=0; in_ham=3}
|> Map.add "stones" { in_spam=0; in_ham=3}
|> Map.add "stoopid" { in_spam=0; in_ham=3}
|> Map.add "stop" { in_spam=13; in_ham=116}
|> Map.add "stop-gap" { in_spam=0; in_ham=4}
|> Map.add "stopped" { in_spam=4; in_ham=13}
|> Map.add "stopping" { in_spam=0; in_ham=6}
|> Map.add "stops" { in_spam=0; in_ham=6}
|> Map.add "storage" { in_spam=1; in_ham=45}
|> Map.add "store" { in_spam=13; in_ham=43}
|> Map.add "stored" { in_spam=0; in_ham=12}
|> Map.add "stores" { in_spam=2; in_ham=15}
|> Map.add "stories" { in_spam=11; in_ham=27}
|> Map.add "storing" { in_spam=0; in_ham=8}
|> Map.add "storm" { in_spam=0; in_ham=6}
|> Map.add "stormont" { in_spam=0; in_ham=3}
|> Map.add "stortek" { in_spam=0; in_ham=4}
|> Map.add "story" { in_spam=10; in_ham=145}
|> Map.add "str" { in_spam=1; in_ham=3}
|> Map.add "straight" { in_spam=4; in_ham=39}
|> Map.add "strain" { in_spam=1; in_ham=8}
|> Map.add "strange" { in_spam=3; in_ham=31}
|> Map.add "strangely" { in_spam=0; in_ham=3}
|> Map.add "stranger" { in_spam=0; in_ham=3}
|> Map.add "strangers" { in_spam=0; in_ham=3}
|> Map.add "strangest" { in_spam=0; in_ham=3}
|> Map.add "strangle" { in_spam=0; in_ham=5}
|> Map.add "strategic" { in_spam=1; in_ham=7}
|> Map.add "strategies" { in_spam=8; in_ham=9}
|> Map.add "strategy" { in_spam=7; in_ham=24}
|> Map.add "straw" { in_spam=0; in_ham=3}
|> Map.add "stream" { in_spam=3; in_ham=19}
|> Map.add "streaming" { in_spam=1; in_ham=5}
|> Map.add "streams" { in_spam=5; in_ham=8}
|> Map.add "street" { in_spam=15; in_ham=74}
|> Map.add "streets" { in_spam=0; in_ham=4}
|> Map.add "strength" { in_spam=6; in_ham=11}
|> Map.add "strengthen" { in_spam=1; in_ham=3}
|> Map.add "strengthened" { in_spam=0; in_ham=3}
|> Map.add "strengths" { in_spam=1; in_ham=2}
|> Map.add "strenuous" { in_spam=4; in_ham=1}
|> Map.add "stress" { in_spam=1; in_ham=8}
|> Map.add "stretch" { in_spam=0; in_ham=4}
|> Map.add "stretz" { in_spam=0; in_ham=5}
|> Map.add "strict" { in_spam=4; in_ham=8}
|> Map.add "strictest" { in_spam=4; in_ham=1}
|> Map.add "strictly" { in_spam=11; in_ham=14}
|> Map.add "strike" { in_spam=0; in_ham=6}
|> Map.add "strikes" { in_spam=0; in_ham=7}
|> Map.add "striking" { in_spam=0; in_ham=8}
|> Map.add "string" { in_spam=1; in_ham=21}
|> Map.add "stringent" { in_spam=3; in_ham=1}
|> Map.add "strings" { in_spam=0; in_ham=9}
|> Map.add "strip" { in_spam=0; in_ham=18}
|> Map.add "stripes" { in_spam=0; in_ham=3}
|> Map.add "stripped" { in_spam=0; in_ham=8}
|> Map.add "stripping" { in_spam=0; in_ham=5}
|> Map.add "strips" { in_spam=2; in_ham=3}
|> Map.add "strive" { in_spam=1; in_ham=5}
|> Map.add "stroke" { in_spam=3; in_ham=1}
|> Map.add "strong" { in_spam=38; in_ham=34}
|> Map.add "stronger" { in_spam=1; in_ham=9}
|> Map.add "strongest" { in_spam=0; in_ham=4}
|> Map.add "strongly" { in_spam=26; in_ham=8}
|> Map.add "struck" { in_spam=1; in_ham=7}
|> Map.add "structural" { in_spam=0; in_ham=5}
|> Map.add "structure" { in_spam=2; in_ham=18}
|> Map.add "structured" { in_spam=0; in_ham=6}
|> Map.add "structures" { in_spam=0; in_ham=12}
|> Map.add "struggle" { in_spam=2; in_ham=8}
|> Map.add "struggled" { in_spam=0; in_ham=5}
|> Map.add "struggles" { in_spam=1; in_ham=3}
|> Map.add "struggling" { in_spam=1; in_ham=3}
|> Map.add "stuck" { in_spam=0; in_ham=26}
|> Map.add "student" { in_spam=7; in_ham=15}
|> Map.add "students" { in_spam=1; in_ham=7}
|> Map.add "studied" { in_spam=0; in_ham=3}
|> Map.add "studies" { in_spam=6; in_ham=16}
|> Map.add "studio" { in_spam=2; in_ham=2}
|> Map.add "studios" { in_spam=1; in_ham=5}
|> Map.add "study" { in_spam=6; in_ham=34}
|> Map.add "studying" { in_spam=3; in_ham=8}
|> Map.add "stuff" { in_spam=7; in_ham=171}
|> Map.add "stuffed" { in_spam=2; in_ham=2}
|> Map.add "stuffy" { in_spam=3; in_ham=1}
|> Map.add "stumbled" { in_spam=1; in_ham=3}
|> Map.add "stumbles" { in_spam=0; in_ham=5}
|> Map.add "stumbling" { in_spam=3; in_ham=1}
|> Map.add "stumped" { in_spam=0; in_ham=3}
|> Map.add "stunned" { in_spam=0; in_ham=3}
|> Map.add "stunt" { in_spam=0; in_ham=3}
|> Map.add "stupid" { in_spam=1; in_ham=37}
|> Map.add "stupidity" { in_spam=0; in_ham=7}
|> Map.add "style" { in_spam=100; in_ham=37}
|> Map.add "styles" { in_spam=4; in_ham=5}
|> Map.add "sub" { in_spam=2; in_ham=16}
|> Map.add "sub-process" { in_spam=0; in_ham=3}
|> Map.add "subcommittee" { in_spam=0; in_ham=3}
|> Map.add "subdir" { in_spam=0; in_ham=3}
|> Map.add "subdirectory" { in_spam=0; in_ham=4}
|> Map.add "subdivisions" { in_spam=0; in_ham=4}
|> Map.add "subj" { in_spam=0; in_ham=4}
|> Map.add "subject" { in_spam=93; in_ham=285}
|> Map.add "subjects" { in_spam=2; in_ham=7}
|> Map.add "submission" { in_spam=2; in_ham=6}
|> Map.add "submissions" { in_spam=0; in_ham=4}
|> Map.add "submit" { in_spam=56; in_ham=14}
|> Map.add "submitted" { in_spam=2; in_ham=4}
|> Map.add "submitting" { in_spam=4; in_ham=5}
|> Map.add "subscribe" { in_spam=6; in_ham=14}
|> Map.add "subscribed" { in_spam=28; in_ham=58}
|> Map.add "subscriber" { in_spam=13; in_ham=1}
|> Map.add "subscribers" { in_spam=12; in_ham=1}
|> Map.add "subscription" { in_spam=65; in_ham=104}
|> Map.add "subsequent" { in_spam=3; in_ham=3}
|> Map.add "subsequently" { in_spam=1; in_ham=7}
|> Map.add "subsets" { in_spam=0; in_ham=3}
|> Map.add "subsidiary" { in_spam=0; in_ham=5}
|> Map.add "subsidies" { in_spam=0; in_ham=5}
|> Map.add "substantial" { in_spam=7; in_ham=13}
|> Map.add "substitute" { in_spam=0; in_ham=4}
|> Map.add "subtle" { in_spam=0; in_ham=9}
|> Map.add "subtree" { in_spam=0; in_ham=4}
|> Map.add "suburban" { in_spam=0; in_ham=14}
|> Map.add "subversive" { in_spam=1; in_ham=2}
|> Map.add "subwoofer" { in_spam=0; in_ham=6}
|> Map.add "succeed" { in_spam=10; in_ham=9}
|> Map.add "succeeded" { in_spam=1; in_ham=4}
|> Map.add "succeeding" { in_spam=3; in_ham=1}
|> Map.add "success" { in_spam=23; in_ham=34}
|> Map.add "successes" { in_spam=4; in_ham=3}
|> Map.add "successful" { in_spam=28; in_ham=33}
|> Map.add "successfully" { in_spam=6; in_ham=17}
|> Map.add "successive" { in_spam=0; in_ham=3}
|> Map.add "such" { in_spam=48; in_ham=272}
|> Map.add "suck" { in_spam=0; in_ham=14}
|> Map.add "sucked" { in_spam=0; in_ham=8}
|> Map.add "suckiness" { in_spam=0; in_ham=3}
|> Map.add "sucking" { in_spam=1; in_ham=4}
|> Map.add "sucks" { in_spam=0; in_ham=11}
|> Map.add "sudden" { in_spam=0; in_ham=3}
|> Map.add "suddenly" { in_spam=1; in_ham=12}
|> Map.add "sue" { in_spam=0; in_ham=11}
|> Map.add "sued" { in_spam=0; in_ham=5}
|> Map.add "suerly" { in_spam=0; in_ham=3}
|> Map.add "suffer" { in_spam=1; in_ham=8}
|> Map.add "suffered" { in_spam=3; in_ham=11}
|> Map.add "suffering" { in_spam=3; in_ham=11}
|> Map.add "sufficient" { in_spam=3; in_ham=19}
|> Map.add "sufficiently" { in_spam=0; in_ham=5}
|> Map.add "sugar" { in_spam=0; in_ham=4}
|> Map.add "suggest" { in_spam=12; in_ham=28}
|> Map.add "suggested" { in_spam=2; in_ham=18}
|> Map.add "suggesting" { in_spam=0; in_ham=13}
|> Map.add "suggestion" { in_spam=1; in_ham=8}
|> Map.add "suggestions" { in_spam=3; in_ham=37}
|> Map.add "suggests" { in_spam=0; in_ham=19}
|> Map.add "sugsegts" { in_spam=0; in_ham=3}
|> Map.add "suicide" { in_spam=1; in_ham=4}
|> Map.add "suing" { in_spam=0; in_ham=5}
|> Map.add "suit" { in_spam=3; in_ham=7}
|> Map.add "suitable" { in_spam=4; in_ham=9}
|> Map.add "suite" { in_spam=28; in_ham=48}
|> Map.add "suited" { in_spam=0; in_ham=5}
|> Map.add "suites" { in_spam=3; in_ham=1}
|> Map.add "suits" { in_spam=0; in_ham=10}
|> Map.add "sum" { in_spam=32; in_ham=13}
|> Map.add "summaries" { in_spam=0; in_ham=16}
|> Map.add "summary" { in_spam=2; in_ham=25}
|> Map.add "summer" { in_spam=5; in_ham=26}
|> Map.add "summer's" { in_spam=0; in_ham=5}
|> Map.add "summit" { in_spam=1; in_ham=5}
|> Map.add "sums" { in_spam=0; in_ham=3}
|> Map.add "sun" { in_spam=0; in_ham=78}
|> Map.add "sun's" { in_spam=0; in_ham=10}
|> Map.add "sunday" { in_spam=1; in_ham=39}
|> Map.add "sunil" { in_spam=0; in_ham=3}
|> Map.add "sunken" { in_spam=0; in_ham=3}
|> Map.add "sunny" { in_spam=1; in_ham=3}
|> Map.add "suns" { in_spam=0; in_ham=3}
|> Map.add "suomesta" { in_spam=0; in_ham=4}
|> Map.add "sup" { in_spam=5; in_ham=1}
|> Map.add "super" { in_spam=9; in_ham=12}
|> Map.add "superior" { in_spam=22; in_ham=8}
|> Map.add "superiority" { in_spam=1; in_ham=3}
|> Map.add "superstition" { in_spam=0; in_ham=3}
|> Map.add "supervision" { in_spam=4; in_ham=2}
|> Map.add "supervisor" { in_spam=1; in_ham=2}
|> Map.add "supplements" { in_spam=1; in_ham=2}
|> Map.add "supplied" { in_spam=1; in_ham=225}
|> Map.add "suppliers" { in_spam=3; in_ham=1}
|> Map.add "supplies" { in_spam=9; in_ham=7}
|> Map.add "supply" { in_spam=8; in_ham=19}
|> Map.add "support" { in_spam=39; in_ham=152}
|> Map.add "supported" { in_spam=7; in_ham=29}
|> Map.add "supporters" { in_spam=2; in_ham=5}
|> Map.add "supporting" { in_spam=1; in_ham=21}
|> Map.add "supports" { in_spam=2; in_ham=31}
|> Map.add "suppose" { in_spam=2; in_ham=33}
|> Map.add "supposed" { in_spam=9; in_ham=50}
|> Map.add "supposedly" { in_spam=0; in_ham=11}
|> Map.add "supremacists" { in_spam=0; in_ham=4}
|> Map.add "supremacy" { in_spam=1; in_ham=2}
|> Map.add "supreme" { in_spam=0; in_ham=9}
|> Map.add "sur" { in_spam=5; in_ham=0}
|> Map.add "sure" { in_spam=43; in_ham=254}
|> Map.add "surely" { in_spam=2; in_ham=15}
|> Map.add "surest" { in_spam=0; in_ham=3}
|> Map.add "surface" { in_spam=2; in_ham=13}
|> Map.add "surfaces" { in_spam=0; in_ham=3}
|> Map.add "surfed" { in_spam=0; in_ham=3}
|> Map.add "surfers" { in_spam=1; in_ham=2}
|> Map.add "surpassing" { in_spam=0; in_ham=6}
|> Map.add "surprise" { in_spam=7; in_ham=7}
|> Map.add "surprised" { in_spam=12; in_ham=17}
|> Map.add "surprising" { in_spam=0; in_ham=9}
|> Map.add "surprisingly" { in_spam=2; in_ham=17}
|> Map.add "surrender" { in_spam=8; in_ham=1}
|> Map.add "surrounded" { in_spam=0; in_ham=3}
|> Map.add "surrounding" { in_spam=1; in_ham=17}
|> Map.add "surveillance" { in_spam=0; in_ham=5}
|> Map.add "survey" { in_spam=4; in_ham=7}
|> Map.add "survival" { in_spam=1; in_ham=2}
|> Map.add "survive" { in_spam=0; in_ham=13}
|> Map.add "survived" { in_spam=0; in_ham=3}
|> Map.add "susan" { in_spam=7; in_ham=0}
|> Map.add "suse" { in_spam=0; in_ham=7}
|> Map.add "suspect" { in_spam=2; in_ham=41}
|> Map.add "suspected" { in_spam=0; in_ham=8}
|> Map.add "suspicion" { in_spam=0; in_ham=4}
|> Map.add "suspicious" { in_spam=3; in_ham=7}
|> Map.add "sustain" { in_spam=0; in_ham=3}
|> Map.add "sustainable" { in_spam=0; in_ham=6}
|> Map.add "sustained" { in_spam=0; in_ham=7}
|> Map.add "sutff" { in_spam=0; in_ham=3}
|> Map.add "suv" { in_spam=6; in_ham=1}
|> Map.add "suza" { in_spam=7; in_ham=0}
|> Map.add "svanstrom" { in_spam=0; in_ham=14}
|> Map.add "svcs" { in_spam=0; in_ham=6}
|> Map.add "sven" { in_spam=0; in_ham=7}
|> Map.add "svensson" { in_spam=0; in_ham=4}
|> Map.add "swallow" { in_spam=0; in_ham=5}
|> Map.add "swap" { in_spam=0; in_ham=14}
|> Map.add "swapped" { in_spam=0; in_ham=7}
|> Map.add "swartz" { in_spam=0; in_ham=4}
|> Map.add "sweden" { in_spam=6; in_ham=3}
|> Map.add "swedish" { in_spam=0; in_ham=3}
|> Map.add "sweet" { in_spam=3; in_ham=9}
|> Map.add "swift" { in_spam=1; in_ham=3}
|> Map.add "swilliams" { in_spam=0; in_ham=3}
|> Map.add "swimming" { in_spam=1; in_ham=3}
|> Map.add "swing" { in_spam=0; in_ham=7}
|> Map.add "swiss" { in_spam=6; in_ham=0}
|> Map.add "switch" { in_spam=0; in_ham=44}
|> Map.add "switched" { in_spam=0; in_ham=5}
|> Map.add "switches" { in_spam=0; in_ham=7}
|> Map.add "switching" { in_spam=0; in_ham=15}
|> Map.add "switzerland" { in_spam=3; in_ham=5}
|> Map.add "sworn" { in_spam=1; in_ham=6}
|> Map.add "swung" { in_spam=0; in_ham=5}
|> Map.add "sxs" { in_spam=0; in_ham=5}
|> Map.add "sycamore" { in_spam=0; in_ham=6}
|> Map.add "sydney" { in_spam=2; in_ham=5}
|> Map.add "sylpheed" { in_spam=0; in_ham=3}
|> Map.add "symantec" { in_spam=5; in_ham=2}
|> Map.add "symbol" { in_spam=6; in_ham=19}
|> Map.add "symbolically" { in_spam=0; in_ham=3}
|> Map.add "symbols" { in_spam=0; in_ham=9}
|> Map.add "symlink" { in_spam=0; in_ham=4}
|> Map.add "sympathy" { in_spam=0; in_ham=3}
|> Map.add "symptoms" { in_spam=0; in_ham=4}
|> Map.add "symtab" { in_spam=0; in_ham=3}
|> Map.add "synapses" { in_spam=0; in_ham=4}
|> Map.add "synaptic" { in_spam=0; in_ham=4}
|> Map.add "sync" { in_spam=0; in_ham=4}
|> Map.add "synchronous" { in_spam=0; in_ham=3}
|> Map.add "syndication" { in_spam=0; in_ham=4}
|> Map.add "synoptics" { in_spam=0; in_ham=6}
|> Map.add "syntax" { in_spam=0; in_ham=17}
|> Map.add "synthetic" { in_spam=0; in_ham=3}
|> Map.add "sys" { in_spam=2; in_ham=11}
|> Map.add "sysadmin" { in_spam=0; in_ham=7}
|> Map.add "sysadmins" { in_spam=0; in_ham=4}
|> Map.add "syslog" { in_spam=0; in_ham=5}
|> Map.add "syst" { in_spam=2; in_ham=2}
|> Map.add "system" { in_spam=51; in_ham=254}
|> Map.add "system's" { in_spam=0; in_ham=4}
|> Map.add "system-wide" { in_spam=0; in_ham=3}
|> Map.add "systematic" { in_spam=0; in_ham=7}
|> Map.add "systems" { in_spam=9; in_ham=106}
|> Map.add "systemworks" { in_spam=23; in_ham=0}
|> Map.add "t-mobile" { in_spam=0; in_ham=4}
|> Map.add "tab" { in_spam=1; in_ham=4}
|> Map.add "table" { in_spam=175; in_ham=28}
|> Map.add "tables" { in_spam=4; in_ham=4}
|> Map.add "taboo" { in_spam=1; in_ham=3}
|> Map.add "tackle" { in_spam=0; in_ham=3}
|> Map.add "tackled" { in_spam=0; in_ham=3}
|> Map.add "tactic" { in_spam=0; in_ham=9}
|> Map.add "tactics" { in_spam=0; in_ham=12}
|> Map.add "tad" { in_spam=0; in_ham=6}
|> Map.add "tag" { in_spam=4; in_ham=41}
|> Map.add "tagged" { in_spam=1; in_ham=11}
|> Map.add "tagging" { in_spam=0; in_ham=7}
|> Map.add "tagline" { in_spam=0; in_ham=19}
|> Map.add "tags" { in_spam=1; in_ham=20}
|> Map.add "tahoma" { in_spam=32; in_ham=0}
|> Map.add "tail" { in_spam=0; in_ham=4}
|> Map.add "taint" { in_spam=3; in_ham=8}
|> Map.add "taiwan" { in_spam=2; in_ham=2}
|> Map.add "take" { in_spam=83; in_ham=218}
|> Map.add "takemeoff" { in_spam=8; in_ham=0}
|> Map.add "taken" { in_spam=13; in_ham=57}
|> Map.add "takers" { in_spam=0; in_ham=5}
|> Map.add "takes" { in_spam=15; in_ham=69}
|> Map.add "taking" { in_spam=12; in_ham=53}
|> Map.add "tale" { in_spam=0; in_ham=8}
|> Map.add "talent" { in_spam=2; in_ham=3}
|> Map.add "talented" { in_spam=0; in_ham=10}
|> Map.add "tales" { in_spam=0; in_ham=4}
|> Map.add "taliban" { in_spam=0; in_ham=9}
|> Map.add "talios" { in_spam=0; in_ham=10}
|> Map.add "talk" { in_spam=4; in_ham=64}
|> Map.add "talked" { in_spam=0; in_ham=6}
|> Map.add "talking" { in_spam=4; in_ham=78}
|> Map.add "talkread" { in_spam=0; in_ham=10}
|> Map.add "talks" { in_spam=0; in_ham=18}
|> Map.add "tall" { in_spam=3; in_ham=14}
|> Map.add "tangled" { in_spam=0; in_ham=3}
|> Map.add "tank" { in_spam=1; in_ham=6}
|> Map.add "tanks" { in_spam=0; in_ham=5}
|> Map.add "tao" { in_spam=0; in_ham=7}
|> Map.add "tap" { in_spam=2; in_ham=3}
|> Map.add "tape" { in_spam=2; in_ham=12}
|> Map.add "tapes" { in_spam=0; in_ham=5}
|> Map.add "tar" { in_spam=0; in_ham=13}
|> Map.add "tarari" { in_spam=0; in_ham=8}
|> Map.add "tarball" { in_spam=0; in_ham=4}
|> Map.add "tarballs" { in_spam=0; in_ham=4}
|> Map.add "target" { in_spam=39; in_ham=35}
|> Map.add "targeted" { in_spam=6; in_ham=7}
|> Map.add "targeting" { in_spam=1; in_ham=9}
|> Map.add "targets" { in_spam=0; in_ham=10}
|> Map.add "targetted" { in_spam=1; in_ham=2}
|> Map.add "task" { in_spam=2; in_ham=30}
|> Map.add "tasks" { in_spam=0; in_ham=6}
|> Map.add "taste" { in_spam=8; in_ham=6}
|> Map.add "tatanka" { in_spam=0; in_ham=4}
|> Map.add "tatum" { in_spam=0; in_ham=4}
|> Map.add "tauber" { in_spam=0; in_ham=3}
|> Map.add "taught" { in_spam=3; in_ham=11}
|> Map.add "taunt" { in_spam=0; in_ham=4}
|> Map.add "tax" { in_spam=13; in_ham=20}
|> Map.add "taxes" { in_spam=5; in_ham=18}
|> Map.add "taxing" { in_spam=0; in_ham=8}
|> Map.add "taxpayers" { in_spam=0; in_ham=5}
|> Map.add "taylor" { in_spam=1; in_ham=6}
|> Map.add "taylor's" { in_spam=0; in_ham=6}
|> Map.add "tbody" { in_spam=48; in_ham=0}
|> Map.add "tcl" { in_spam=0; in_ham=33}
|> Map.add "tcnet" { in_spam=0; in_ham=4}
|> Map.add "tcp" { in_spam=1; in_ham=2}
|> Map.add "tea" { in_spam=1; in_ham=10}
|> Map.add "teach" { in_spam=13; in_ham=15}
|> Map.add "teacher" { in_spam=0; in_ham=7}
|> Map.add "teaching" { in_spam=1; in_ham=8}
|> Map.add "team" { in_spam=13; in_ham=33}
|> Map.add "teamed" { in_spam=2; in_ham=2}
|> Map.add "teams" { in_spam=0; in_ham=8}
|> Map.add "tear" { in_spam=1; in_ham=5}
|> Map.add "tears" { in_spam=0; in_ham=4}
|> Map.add "teasing" { in_spam=4; in_ham=1}
|> Map.add "tech" { in_spam=2; in_ham=25}
|> Map.add "techdirt" { in_spam=0; in_ham=3}
|> Map.add "technical" { in_spam=12; in_ham=37}
|> Map.add "technically" { in_spam=0; in_ham=4}
|> Map.add "technique" { in_spam=6; in_ham=9}
|> Map.add "techniques" { in_spam=6; in_ham=27}
|> Map.add "technologies" { in_spam=2; in_ham=26}
|> Map.add "technology" { in_spam=21; in_ham=83}
|> Map.add "technology-" { in_spam=0; in_ham=6}
|> Map.add "technomad" { in_spam=0; in_ham=8}
|> Map.add "techtv" { in_spam=0; in_ham=3}
|> Map.add "ted" { in_spam=0; in_ham=7}
|> Map.add "tedious" { in_spam=0; in_ham=6}
|> Map.add "teeming" { in_spam=0; in_ham=8}
|> Map.add "teen" { in_spam=8; in_ham=2}
|> Map.add "teenage" { in_spam=0; in_ham=3}
|> Map.add "teenager" { in_spam=0; in_ham=5}
|> Map.add "teenagers" { in_spam=0; in_ham=4}
|> Map.add "teens" { in_spam=4; in_ham=1}
|> Map.add "teeth" { in_spam=1; in_ham=3}
|> Map.add "teh" { in_spam=0; in_ham=6}
|> Map.add "tehd" { in_spam=0; in_ham=4}
|> Map.add "tel" { in_spam=15; in_ham=16}
|> Map.add "telechoice" { in_spam=0; in_ham=6}
|> Map.add "telecom" { in_spam=1; in_ham=9}
|> Map.add "teledyn" { in_spam=0; in_ham=46}
|> Map.add "teledynamics" { in_spam=0; in_ham=45}
|> Map.add "telegraph" { in_spam=0; in_ham=4}
|> Map.add "telephone" { in_spam=26; in_ham=17}
|> Map.add "telephones" { in_spam=0; in_ham=3}
|> Map.add "television" { in_spam=5; in_ham=16}
|> Map.add "tell" { in_spam=30; in_ham=130}
|> Map.add "telling" { in_spam=1; in_ham=31}
|> Map.add "tells" { in_spam=0; in_ham=20}
|> Map.add "telnet" { in_spam=0; in_ham=6}
|> Map.add "temp" { in_spam=2; in_ham=3}
|> Map.add "temperate" { in_spam=0; in_ham=4}
|> Map.add "temperature" { in_spam=0; in_ham=13}
|> Map.add "temperatures" { in_spam=0; in_ham=9}
|> Map.add "template" { in_spam=4; in_ham=4}
|> Map.add "templates" { in_spam=3; in_ham=3}
|> Map.add "temple" { in_spam=1; in_ham=7}
|> Map.add "temporary" { in_spam=0; in_ham=15}
|> Map.add "ten" { in_spam=6; in_ham=29}
|> Map.add "tend" { in_spam=1; in_ham=29}
|> Map.add "tendencies" { in_spam=0; in_ham=4}
|> Map.add "tendency" { in_spam=0; in_ham=9}
|> Map.add "tends" { in_spam=2; in_ham=15}
|> Map.add "tennessee" { in_spam=5; in_ham=1}
|> Map.add "tens" { in_spam=0; in_ham=11}
|> Map.add "tension" { in_spam=1; in_ham=2}
|> Map.add "tenure" { in_spam=3; in_ham=12}
|> Map.add "ter" { in_spam=6; in_ham=0}
|> Map.add "term" { in_spam=23; in_ham=24}
|> Map.add "terminal" { in_spam=1; in_ham=24}
|> Map.add "terminate" { in_spam=0; in_ham=4}
|> Map.add "termlife" { in_spam=5; in_ham=0}
|> Map.add "terms" { in_spam=26; in_ham=124}
|> Map.add "terra" { in_spam=5; in_ham=0}
|> Map.add "terrace" { in_spam=0; in_ham=3}
|> Map.add "terrain" { in_spam=0; in_ham=5}
|> Map.add "terrible" { in_spam=3; in_ham=18}
|> Map.add "terribly" { in_spam=0; in_ham=5}
|> Map.add "terrific" { in_spam=0; in_ham=3}
|> Map.add "terrifying" { in_spam=0; in_ham=3}
|> Map.add "territories" { in_spam=2; in_ham=2}
|> Map.add "territory" { in_spam=3; in_ham=7}
|> Map.add "terror" { in_spam=0; in_ham=8}
|> Map.add "terrorism" { in_spam=0; in_ham=16}
|> Map.add "terrorist" { in_spam=3; in_ham=7}
|> Map.add "terrorists" { in_spam=1; in_ham=10}
|> Map.add "terrorists'" { in_spam=0; in_ham=3}
|> Map.add "test" { in_spam=13; in_ham=122}
|> Map.add "tested" { in_spam=8; in_ham=25}
|> Map.add "testers" { in_spam=0; in_ham=3}
|> Map.add "testimonials" { in_spam=12; in_ham=0}
|> Map.add "testing" { in_spam=4; in_ham=58}
|> Map.add "tests" { in_spam=2; in_ham=37}
|> Map.add "texas" { in_spam=3; in_ham=10}
|> Map.add "text" { in_spam=155; in_ham=116}
|> Map.add "text-align" { in_spam=17; in_ham=2}
|> Map.add "textbook" { in_spam=0; in_ham=3}
|> Map.add "texts" { in_spam=0; in_ham=7}
|> Map.add "tgz" { in_spam=1; in_ham=2}
|> Map.add "thai" { in_spam=0; in_ham=3}
|> Map.add "thailand" { in_spam=2; in_ham=5}
|> Map.add "than" { in_spam=86; in_ham=467}
|> Map.add "thank" { in_spam=53; in_ham=37}
|> Map.add "thanks" { in_spam=18; in_ham=259}
|> Map.add "thanx" { in_spam=5; in_ham=3}
|> Map.add "that" { in_spam=223; in_ham=1555}
|> Map.add "that'd" { in_spam=0; in_ham=3}
|> Map.add "that'll" { in_spam=1; in_ham=6}
|> Map.add "that's" { in_spam=37; in_ham=283}
|> Map.add "that-" { in_spam=0; in_ham=4}
|> Map.add "thats" { in_spam=0; in_ham=26}
|> Map.add "the" { in_spam=398; in_ham=2191}
|> Map.add "theadmanager" { in_spam=15; in_ham=0}
|> Map.add "theage" { in_spam=0; in_ham=4}
|> Map.add "theater" { in_spam=1; in_ham=11}
|> Map.add "theaters" { in_spam=0; in_ham=3}
|> Map.add "theatre" { in_spam=0; in_ham=5}
|> Map.add "theft" { in_spam=1; in_ham=14}
|> Map.add "their" { in_spam=90; in_ham=435}
|> Map.add "them" { in_spam=71; in_ham=407}
|> Map.add "theme" { in_spam=1; in_ham=4}
|> Map.add "themes" { in_spam=0; in_ham=6}
|> Map.add "themselves" { in_spam=10; in_ham=36}
|> Map.add "then" { in_spam=77; in_ham=464}
|> Map.add "then-current" { in_spam=0; in_ham=3}
|> Map.add "thenews" { in_spam=0; in_ham=3}
|> Map.add "theo" { in_spam=1; in_ham=16}
|> Map.add "theoretical" { in_spam=0; in_ham=7}
|> Map.add "theories" { in_spam=1; in_ham=6}
|> Map.add "theory" { in_spam=0; in_ham=38}
|> Map.add "therapy" { in_spam=7; in_ham=3}
|> Map.add "there" { in_spam=76; in_ham=711}
|> Map.add "there'd" { in_spam=0; in_ham=7}
|> Map.add "there'll" { in_spam=0; in_ham=5}
|> Map.add "there's" { in_spam=17; in_ham=184}
|> Map.add "thereby" { in_spam=2; in_ham=6}
|> Map.add "therefore" { in_spam=19; in_ham=25}
|> Map.add "theregister" { in_spam=0; in_ham=4}
|> Map.add "thereof" { in_spam=1; in_ham=9}
|> Map.add "theres" { in_spam=0; in_ham=3}
|> Map.add "thermal" { in_spam=3; in_ham=1}
|> Map.add "these" { in_spam=82; in_ham=279}
|> Map.add "they" { in_spam=61; in_ham=654}
|> Map.add "they'd" { in_spam=3; in_ham=20}
|> Map.add "they'll" { in_spam=0; in_ham=23}
|> Map.add "they're" { in_spam=10; in_ham=77}
|> Map.add "they've" { in_spam=1; in_ham=28}
|> Map.add "thick" { in_spam=1; in_ham=4}
|> Map.add "thier" { in_spam=0; in_ham=7}
|> Map.add "thieves" { in_spam=0; in_ham=4}
|> Map.add "thimm" { in_spam=0; in_ham=9}
|> Map.add "thin" { in_spam=2; in_ham=5}
|> Map.add "thing" { in_spam=23; in_ham=201}
|> Map.add "thingies" { in_spam=0; in_ham=3}
|> Map.add "things" { in_spam=19; in_ham=222}
|> Map.add "think" { in_spam=31; in_ham=420}
|> Map.add "thinkgeek" { in_spam=2; in_ham=101}
|> Map.add "thinking" { in_spam=14; in_ham=62}
|> Map.add "thinks" { in_spam=0; in_ham=34}
|> Map.add "thinly" { in_spam=0; in_ham=3}
|> Map.add "third" { in_spam=16; in_ham=50}
|> Map.add "third-party" { in_spam=0; in_ham=6}
|> Map.add "thirst" { in_spam=1; in_ham=2}
|> Map.add "thirteen" { in_spam=0; in_ham=3}
|> Map.add "thirty" { in_spam=9; in_ham=7}
|> Map.add "this" { in_spam=340; in_ham=1423}
|> Map.add "this-" { in_spam=0; in_ham=3}
|> Map.add "tho" { in_spam=0; in_ham=9}
|> Map.add "thoery" { in_spam=0; in_ham=3}
|> Map.add "thomas" { in_spam=2; in_ham=27}
|> Map.add "thorough" { in_spam=6; in_ham=1}
|> Map.add "thoroughly" { in_spam=1; in_ham=5}
|> Map.add "those" { in_spam=51; in_ham=261}
|> Map.add "thou" { in_spam=0; in_ham=4}
|> Map.add "though" { in_spam=17; in_ham=196}
|> Map.add "thought" { in_spam=11; in_ham=137}
|> Map.add "thoughts" { in_spam=0; in_ham=18}
|> Map.add "thousand" { in_spam=17; in_ham=20}
|> Map.add "thousands" { in_spam=46; in_ham=37}
|> Map.add "thrash" { in_spam=0; in_ham=4}
|> Map.add "thread" { in_spam=1; in_ham=21}
|> Map.add "threads" { in_spam=0; in_ham=14}
|> Map.add "threat" { in_spam=3; in_ham=14}
|> Map.add "threaten" { in_spam=0; in_ham=12}
|> Map.add "threatened" { in_spam=1; in_ham=4}
|> Map.add "threatening" { in_spam=3; in_ham=10}
|> Map.add "threatens" { in_spam=1; in_ham=4}
|> Map.add "threats" { in_spam=5; in_ham=12}
|> Map.add "three" { in_spam=24; in_ham=109}
|> Map.add "threshold" { in_spam=0; in_ham=8}
|> Map.add "thresholds" { in_spam=0; in_ham=4}
|> Map.add "thrive" { in_spam=1; in_ham=6}
|> Map.add "thriving" { in_spam=1; in_ham=2}
|> Map.add "throat" { in_spam=0; in_ham=3}
|> Map.add "through" { in_spam=78; in_ham=244}
|> Map.add "throughout" { in_spam=5; in_ham=23}
|> Map.add "throw" { in_spam=3; in_ham=19}
|> Map.add "throwing" { in_spam=3; in_ham=11}
|> Map.add "thrown" { in_spam=2; in_ham=6}
|> Map.add "thru" { in_spam=2; in_ham=15}
|> Map.add "thu" { in_spam=3; in_ham=132}
|> Map.add "thugs" { in_spam=1; in_ham=3}
|> Map.add "thumb" { in_spam=1; in_ham=2}
|> Map.add "thunder" { in_spam=0; in_ham=4}
|> Map.add "thursday" { in_spam=0; in_ham=60}
|> Map.add "thus" { in_spam=8; in_ham=45}
|> Map.add "thx" { in_spam=0; in_ham=7}
|> Map.add "tia" { in_spam=0; in_ham=4}
|> Map.add "tibetan" { in_spam=0; in_ham=5}
|> Map.add "ticker" { in_spam=1; in_ham=4}
|> Map.add "ticket" { in_spam=4; in_ham=5}
|> Map.add "tickets" { in_spam=3; in_ham=7}
|> Map.add "tid" { in_spam=0; in_ham=9}
|> Map.add "tidied" { in_spam=0; in_ham=3}
|> Map.add "tidy" { in_spam=3; in_ham=1}
|> Map.add "tie" { in_spam=0; in_ham=9}
|> Map.add "tied" { in_spam=0; in_ham=17}
|> Map.add "tier" { in_spam=2; in_ham=2}
|> Map.add "ties" { in_spam=2; in_ham=7}
|> Map.add "tight" { in_spam=2; in_ham=5}
|> Map.add "till" { in_spam=4; in_ham=10}
|> Map.add "tilt" { in_spam=1; in_ham=2}
|> Map.add "tim" { in_spam=1; in_ham=55}
|> Map.add "tim's" { in_spam=0; in_ham=10}
|> Map.add "timbers" { in_spam=0; in_ham=3}
|> Map.add "timc" { in_spam=0; in_ham=5}
|> Map.add "time" { in_spam=151; in_ham=539}
|> Map.add "timeline" { in_spam=0; in_ham=3}
|> Map.add "timely" { in_spam=4; in_ham=9}
|> Map.add "timeout" { in_spam=0; in_ham=9}
|> Map.add "timer" { in_spam=1; in_ham=2}
|> Map.add "times" { in_spam=55; in_ham=150}
|> Map.add "timesonline" { in_spam=0; in_ham=7}
|> Map.add "timezone" { in_spam=1; in_ham=2}
|> Map.add "timing" { in_spam=1; in_ham=5}
|> Map.add "timmy" { in_spam=0; in_ham=3}
|> Map.add "timtest" { in_spam=0; in_ham=13}
|> Map.add "timtoken" { in_spam=0; in_ham=4}
|> Map.add "tiny" { in_spam=1; in_ham=18}
|> Map.add "tip" { in_spam=6; in_ham=16}
|> Map.add "tips" { in_spam=7; in_ham=14}
|> Map.add "tired" { in_spam=8; in_ham=116}
|> Map.add "tithe" { in_spam=0; in_ham=4}
|> Map.add "title" { in_spam=154; in_ham=25}
|> Map.add "titled" { in_spam=0; in_ham=3}
|> Map.add "titles" { in_spam=4; in_ham=8}
|> Map.add "tkbuttonup" { in_spam=0; in_ham=4}
|> Map.add "tleilaxu" { in_spam=0; in_ham=4}
|> Map.add "tlkl" { in_spam=0; in_ham=3}
|> Map.add "tmda" { in_spam=0; in_ham=20}
|> Map.add "tmda's" { in_spam=0; in_ham=3}
|> Map.add "tmdaers" { in_spam=0; in_ham=4}
|> Map.add "tml" { in_spam=1; in_ham=3}
|> Map.add "tmp" { in_spam=0; in_ham=34}
|> Map.add "tmpl" { in_spam=0; in_ham=9}
|> Map.add "tmwsystems" { in_spam=0; in_ham=3}
|> Map.add "tobacco" { in_spam=11; in_ham=2}
|> Map.add "today" { in_spam=111; in_ham=141}
|> Map.add "today's" { in_spam=8; in_ham=29}
|> Map.add "todays" { in_spam=1; in_ham=4}
|> Map.add "toddler" { in_spam=1; in_ham=5}
|> Map.add "toddlers" { in_spam=0; in_ham=3}
|> Map.add "todo" { in_spam=0; in_ham=7}
|> Map.add "toes" { in_spam=0; in_ham=4}
|> Map.add "together" { in_spam=10; in_ham=69}
|> Map.add "toilet" { in_spam=1; in_ham=7}
|> Map.add "token" { in_spam=1; in_ham=5}
|> Map.add "tokenization" { in_spam=0; in_ham=6}
|> Map.add "tokenize" { in_spam=0; in_ham=19}
|> Map.add "tokenizer" { in_spam=0; in_ham=26}
|> Map.add "tokenizers" { in_spam=0; in_ham=3}
|> Map.add "tokens" { in_spam=0; in_ham=9}
|> Map.add "tokyo" { in_spam=0; in_ham=3}
|> Map.add "told" { in_spam=14; in_ham=79}
|> Map.add "tolerance" { in_spam=0; in_ham=7}
|> Map.add "tolerate" { in_spam=0; in_ham=3}
|> Map.add "tolerating" { in_spam=0; in_ham=3}
|> Map.add "toll" { in_spam=3; in_ham=4}
|> Map.add "toll-free" { in_spam=22; in_ham=1}
|> Map.add "tom" { in_spam=0; in_ham=73}
|> Map.add "tomorrow" { in_spam=3; in_ham=25}
|> Map.add "tomorrow's" { in_spam=5; in_ham=0}
|> Map.add "tomwhore" { in_spam=0; in_ham=3}
|> Map.add "ton" { in_spam=1; in_ham=7}
|> Map.add "tone" { in_spam=3; in_ham=7}
|> Map.add "tones" { in_spam=0; in_ham=3}
|> Map.add "tongue" { in_spam=0; in_ham=4}
|> Map.add "tongues" { in_spam=0; in_ham=3}
|> Map.add "tonight" { in_spam=0; in_ham=15}
|> Map.add "tonight's" { in_spam=0; in_ham=5}
|> Map.add "tons" { in_spam=1; in_ham=13}
|> Map.add "tony" { in_spam=0; in_ham=49}
|> Map.add "too" { in_spam=36; in_ham=281}
|> Map.add "took" { in_spam=20; in_ham=59}
|> Map.add "tool" { in_spam=12; in_ham=42}
|> Map.add "toolbar" { in_spam=1; in_ham=2}
|> Map.add "toolbars" { in_spam=0; in_ham=3}
|> Map.add "toolkits" { in_spam=0; in_ham=3}
|> Map.add "tools" { in_spam=23; in_ham=53}
|> Map.add "top" { in_spam=108; in_ham=89}
|> Map.add "top-" { in_spam=0; in_ham=4}
|> Map.add "topdir" { in_spam=0; in_ham=3}
|> Map.add "topic" { in_spam=0; in_ham=16}
|> Map.add "topics" { in_spam=3; in_ham=7}
|> Map.add "toplevel" { in_spam=0; in_ham=5}
|> Map.add "topmargin" { in_spam=22; in_ham=0}
|> Map.add "topping" { in_spam=0; in_ham=4}
|> Map.add "topsail" { in_spam=0; in_ham=3}
|> Map.add "torn" { in_spam=0; in_ham=4}
|> Map.add "torre" { in_spam=0; in_ham=4}
|> Map.add "tory" { in_spam=0; in_ham=4}
|> Map.add "toshiba" { in_spam=1; in_ham=4}
|> Map.add "toss" { in_spam=0; in_ham=5}
|> Map.add "tossing" { in_spam=2; in_ham=4}
|> Map.add "total" { in_spam=33; in_ham=51}
|> Map.add "totality" { in_spam=0; in_ham=5}
|> Map.add "totally" { in_spam=17; in_ham=30}
|> Map.add "totals" { in_spam=0; in_ham=4}
|> Map.add "totaly" { in_spam=1; in_ham=2}
|> Map.add "touch" { in_spam=3; in_ham=24}
|> Map.add "touched" { in_spam=1; in_ham=4}
|> Map.add "tough" { in_spam=3; in_ham=5}
|> Map.add "tought" { in_spam=0; in_ham=4}
|> Map.add "tour" { in_spam=5; in_ham=4}
|> Map.add "toward" { in_spam=2; in_ham=15}
|> Map.add "towards" { in_spam=5; in_ham=33}
|> Map.add "tower" { in_spam=0; in_ham=3}
|> Map.add "towers" { in_spam=0; in_ham=8}
|> Map.add "towing" { in_spam=6; in_ham=0}
|> Map.add "town" { in_spam=3; in_ham=21}
|> Map.add "toy" { in_spam=1; in_ham=3}
|> Map.add "toys" { in_spam=0; in_ham=10}
|> Map.add "tpc" { in_spam=0; in_ham=3}
|> Map.add "tpj" { in_spam=1; in_ham=2}
|> Map.add "trace" { in_spam=3; in_ham=8}
|> Map.add "traceback" { in_spam=0; in_ham=14}
|> Map.add "tracebacks" { in_spam=0; in_ham=4}
|> Map.add "traced" { in_spam=4; in_ham=1}
|> Map.add "traces" { in_spam=0; in_ham=4}
|> Map.add "track" { in_spam=26; in_ham=34}
|> Map.add "trackback" { in_spam=0; in_ham=3}
|> Map.add "tracked" { in_spam=0; in_ham=6}
|> Map.add "tracker" { in_spam=0; in_ham=4}
|> Map.add "tracking" { in_spam=1; in_ham=15}
|> Map.add "tracks" { in_spam=0; in_ham=3}
|> Map.add "trade" { in_spam=18; in_ham=69}
|> Map.add "traded" { in_spam=5; in_ham=4}
|> Map.add "trademark" { in_spam=0; in_ham=11}
|> Map.add "trademarks" { in_spam=0; in_ham=4}
|> Map.add "traders" { in_spam=4; in_ham=2}
|> Map.add "trades" { in_spam=1; in_ham=4}
|> Map.add "trading" { in_spam=10; in_ham=5}
|> Map.add "tradition" { in_spam=0; in_ham=9}
|> Map.add "traditional" { in_spam=7; in_ham=21}
|> Map.add "traditions" { in_spam=1; in_ham=5}
|> Map.add "traffic" { in_spam=4; in_ham=49}
|> Map.add "trafficking" { in_spam=1; in_ham=2}
|> Map.add "tragedy" { in_spam=0; in_ham=3}
|> Map.add "tragic" { in_spam=0; in_ham=3}
|> Map.add "tragically" { in_spam=0; in_ham=3}
|> Map.add "trail" { in_spam=1; in_ham=4}
|> Map.add "trailer" { in_spam=2; in_ham=5}
|> Map.add "trailing" { in_spam=0; in_ham=3}
|> Map.add "trails" { in_spam=0; in_ham=8}
|> Map.add "train" { in_spam=11; in_ham=25}
|> Map.add "train-load" { in_spam=0; in_ham=3}
|> Map.add "trained" { in_spam=0; in_ham=16}
|> Map.add "training" { in_spam=17; in_ham=52}
|> Map.add "tramp" { in_spam=0; in_ham=3}
|> Map.add "transaction" { in_spam=29; in_ham=15}
|> Map.add "transactions" { in_spam=0; in_ham=15}
|> Map.add "transcode" { in_spam=0; in_ham=3}
|> Map.add "transfer" { in_spam=32; in_ham=17}
|> Map.add "transferred" { in_spam=8; in_ham=6}
|> Map.add "transferring" { in_spam=5; in_ham=5}
|> Map.add "transfers" { in_spam=0; in_ham=3}
|> Map.add "transform" { in_spam=0; in_ham=7}
|> Map.add "transforming" { in_spam=0; in_ham=9}
|> Map.add "transforms" { in_spam=0; in_ham=3}
|> Map.add "transit" { in_spam=0; in_ham=5}
|> Map.add "transition" { in_spam=1; in_ham=6}
|> Map.add "transitional" { in_spam=29; in_ham=8}
|> Map.add "transitory" { in_spam=0; in_ham=3}
|> Map.add "translate" { in_spam=0; in_ham=9}
|> Map.add "translated" { in_spam=0; in_ham=3}
|> Map.add "translates" { in_spam=0; in_ham=3}
|> Map.add "translation" { in_spam=0; in_ham=7}
|> Map.add "translations" { in_spam=0; in_ham=3}
|> Map.add "translator" { in_spam=0; in_ham=3}
|> Map.add "transmission" { in_spam=1; in_ham=6}
|> Map.add "transmit" { in_spam=0; in_ham=3}
|> Map.add "transmitted" { in_spam=1; in_ham=7}
|> Map.add "transparency" { in_spam=2; in_ham=2}
|> Map.add "transparent" { in_spam=1; in_ham=5}
|> Map.add "transport" { in_spam=0; in_ham=3}
|> Map.add "trap" { in_spam=0; in_ham=6}
|> Map.add "trapped" { in_spam=0; in_ham=5}
|> Map.add "traps" { in_spam=3; in_ham=5}
|> Map.add "trash" { in_spam=0; in_ham=4}
|> Map.add "travail" { in_spam=2; in_ham=2}
|> Map.add "travel" { in_spam=10; in_ham=10}
|> Map.add "traveler" { in_spam=1; in_ham=3}
|> Map.add "travelling" { in_spam=1; in_ham=5}
|> Map.add "tre" { in_spam=3; in_ham=2}
|> Map.add "treasure" { in_spam=2; in_ham=6}
|> Map.add "treasures" { in_spam=5; in_ham=2}
|> Map.add "treasury" { in_spam=3; in_ham=2}
|> Map.add "treat" { in_spam=8; in_ham=3}
|> Map.add "treated" { in_spam=3; in_ham=12}
|> Map.add "treaties" { in_spam=1; in_ham=5}
|> Map.add "treating" { in_spam=0; in_ham=7}
|> Map.add "treatise" { in_spam=1; in_ham=3}
|> Map.add "treatment" { in_spam=0; in_ham=14}
|> Map.add "treatments" { in_spam=0; in_ham=3}
|> Map.add "treats" { in_spam=0; in_ham=3}
|> Map.add "treaty" { in_spam=1; in_ham=4}
|> Map.add "trebuchet" { in_spam=8; in_ham=0}
|> Map.add "tree" { in_spam=0; in_ham=27}
|> Map.add "trees" { in_spam=4; in_ham=11}
|> Map.add "trek" { in_spam=0; in_ham=8}
|> Map.add "tremendous" { in_spam=13; in_ham=4}
|> Map.add "tremendously" { in_spam=1; in_ham=2}
|> Map.add "trend" { in_spam=2; in_ham=10}
|> Map.add "trends" { in_spam=0; in_ham=5}
|> Map.add "trial" { in_spam=8; in_ham=6}
|> Map.add "tribal" { in_spam=0; in_ham=3}
|> Map.add "tribe" { in_spam=1; in_ham=2}
|> Map.add "tribute" { in_spam=0; in_ham=4}
|> Map.add "trick" { in_spam=4; in_ham=31}
|> Map.add "tricks" { in_spam=3; in_ham=10}
|> Map.add "tricky" { in_spam=0; in_ham=7}
|> Map.add "tried" { in_spam=13; in_ham=133}
|> Map.add "tries" { in_spam=0; in_ham=17}
|> Map.add "trigger" { in_spam=0; in_ham=9}
|> Map.add "triggered" { in_spam=0; in_ham=6}
|> Map.add "triggers" { in_spam=0; in_ham=4}

