open Bayesian.Database
let db = Map.empty 
|> Map.add "0.5.7" { in_spam=0; in_ham=5}
|> Map.add "100" { in_spam=4; in_ham=1}
|> Map.add "2.14" { in_spam=0; in_ham=13}
|> Map.add "2.2" { in_spam=0; in_ham=4}
|> Map.add "2.40" { in_spam=0; in_ham=19}
|> Map.add "2.41" { in_spam=0; in_ham=17}
|> Map.add "2002" { in_spam=13; in_ham=64}
|> Map.add "201" { in_spam=0; in_ham=4}
|> Map.add "2022" { in_spam=7; in_ham=0}
|> Map.add "29.99" { in_spam=5; in_ham=0}
|> Map.add "3.92" { in_spam=0; in_ham=4}
|> Map.add "300" { in_spam=1; in_ham=2}
|> Map.add "3154" { in_spam=0; in_ham=3}
|> Map.add "500" { in_spam=8; in_ham=0}
|> Map.add "7.2" { in_spam=0; in_ham=4}
|> Map.add "7.3" { in_spam=0; in_ham=6}
|> Map.add "8.0" { in_spam=0; in_ham=20}
|> Map.add "ADV" { in_spam=18; in_ham=0}
|> Map.add "ALSA" { in_spam=0; in_ham=32}
|> Map.add "ARRRGHHH" { in_spam=0; in_ham=9}
|> Map.add "ASSISTANCE" { in_spam=5; in_ham=0}
|> Map.add "ATT" { in_spam=0; in_ham=4}
|> Map.add "CLEARANCE" { in_spam=8; in_ham=0}
|> Map.add "COMPUTER" { in_spam=7; in_ham=0}
|> Map.add "CVS" { in_spam=0; in_ham=39}
|> Map.add "DCC" { in_spam=0; in_ham=4}
|> Map.add "DMA" { in_spam=0; in_ham=17}
|> Map.add "DNS" { in_spam=0; in_ham=7}
|> Map.add "DRM" { in_spam=0; in_ham=3}
|> Map.add "DVD" { in_spam=2; in_ham=25}
|> Map.add "FORTUNE" { in_spam=6; in_ham=0}
|> Map.add "FREE" { in_spam=10; in_ham=0}
|> Map.add "FROM" { in_spam=3; in_ham=1}
|> Map.add "FWD" { in_spam=1; in_ham=3}
|> Map.add "GDC" { in_spam=0; in_ham=6}
|> Map.add "GPG" { in_spam=0; in_ham=9}
|> Map.add "HIRING" { in_spam=6; in_ham=0}
|> Map.add "HOME" { in_spam=9; in_ham=0}
|> Map.add "HTML" { in_spam=0; in_ham=5}
|> Map.add "IDE" { in_spam=0; in_ham=5}
|> Map.add "IIU" { in_spam=0; in_ham=3}
|> Map.add "ILUG" { in_spam=32; in_ham=92}
|> Map.add "IMG" { in_spam=0; in_ham=4}
|> Map.add "IRA" { in_spam=0; in_ham=4}
|> Map.add "IRR" { in_spam=0; in_ham=5}
|> Map.add "ISP" { in_spam=2; in_ham=2}
|> Map.add "MIME" { in_spam=0; in_ham=3}
|> Map.add "MIT" { in_spam=0; in_ham=3}
|> Map.add "NEED" { in_spam=6; in_ham=0}
|> Map.add "NORTON" { in_spam=6; in_ham=0}
|> Map.add "ONLY" { in_spam=5; in_ham=0}
|> Map.add "POP" { in_spam=0; in_ham=4}
|> Map.add "PROCESS" { in_spam=0; in_ham=4}
|> Map.add "PROTECT" { in_spam=5; in_ham=0}
|> Map.add "RDF" { in_spam=0; in_ham=3}
|> Map.add "RELEASE" { in_spam=0; in_ham=7}
|> Map.add "REPS" { in_spam=8; in_ham=0}
|> Map.add "RPM" { in_spam=0; in_ham=3}
|> Map.add "RSS" { in_spam=0; in_ham=9}
|> Map.add "SACVS" { in_spam=0; in_ham=18}
|> Map.add "SALE" { in_spam=8; in_ham=0}
|> Map.add "SPAM" { in_spam=2; in_ham=2}
|> Map.add "SSL" { in_spam=0; in_ham=4}
|> Map.add "STUPID" { in_spam=0; in_ham=3}
|> Map.add "SYSTEMWORKS" { in_spam=12; in_ham=0}
|> Map.add "URGENT" { in_spam=5; in_ham=0}
|> Map.add "USB" { in_spam=0; in_ham=5}
|> Map.add "YOUR" { in_spam=11; in_ham=3}
|> Map.add "about" { in_spam=4; in_ham=20}
|> Map.add "absurdities" { in_spam=0; in_ham=9}
|> Map.add "access" { in_spam=3; in_ham=5}
|> Map.add "account" { in_spam=9; in_ham=0}
|> Map.add "activebuddy" { in_spam=0; in_ham=11}
|> Map.add "add" { in_spam=0; in_ham=3}
|> Map.add "address" { in_spam=0; in_ham=4}
|> Map.add "adhesion" { in_spam=0; in_ham=5}
|> Map.add "adsl" { in_spam=0; in_ham=7}
|> Map.add "adv" { in_spam=20; in_ham=0}
|> Map.add "advice" { in_spam=0; in_ham=5}
|> Map.add "after" { in_spam=0; in_ham=10}
|> Map.add "again" { in_spam=2; in_ham=8}
|> Map.add "against" { in_spam=2; in_ham=3}
|> Map.add "alive" { in_spam=0; in_ham=3}
|> Map.add "all" { in_spam=3; in_ham=19}
|> Map.add "alliance" { in_spam=0; in_ham=3}
|> Map.add "almost" { in_spam=0; in_ham=25}
|> Map.add "alsa" { in_spam=0; in_ham=34}
|> Map.add "alsa-driver" { in_spam=0; in_ham=12}
|> Map.add "amazon" { in_spam=1; in_ham=2}
|> Map.add "amendment" { in_spam=0; in_ham=20}
|> Map.add "america" { in_spam=1; in_ham=3}
|> Map.add "american" { in_spam=1; in_ham=2}
|> Map.add "analog" { in_spam=0; in_ham=5}
|> Map.add "and" { in_spam=23; in_ham=114}
|> Map.add "angry" { in_spam=0; in_ham=7}
|> Map.add "announces" { in_spam=0; in_ham=13}
|> Map.add "annual" { in_spam=0; in_ham=5}
|> Map.add "anolther" { in_spam=0; in_ham=12}
|> Map.add "another" { in_spam=0; in_ham=8}
|> Map.add "any" { in_spam=4; in_ham=1}
|> Map.add "anyone" { in_spam=1; in_ham=2}
|> Map.add "app" { in_spam=0; in_ham=4}
|> Map.add "apple" { in_spam=0; in_ham=10}
|> Map.add "applications" { in_spam=0; in_ham=4}
|> Map.add "approach" { in_spam=1; in_ham=7}
|> Map.add "apt" { in_spam=0; in_ham=57}
|> Map.add "apt-get" { in_spam=0; in_ham=13}
|> Map.add "archive" { in_spam=0; in_ham=3}
|> Map.add "are" { in_spam=10; in_ham=27}
|> Map.add "arrrghhh" { in_spam=0; in_ham=9}
|> Map.add "article" { in_spam=0; in_ham=9}
|> Map.add "artist" { in_spam=0; in_ham=3}
|> Map.add "ascii" { in_spam=0; in_ham=3}
|> Map.add "assassin" { in_spam=0; in_ham=3}
|> Map.add "assistance" { in_spam=9; in_ham=1}
|> Map.add "asynchronous" { in_spam=0; in_ham=5}
|> Map.add "ate" { in_spam=0; in_ham=3}
|> Map.add "att" { in_spam=0; in_ham=4}
|> Map.add "attacks" { in_spam=0; in_ham=11}
|> Map.add "attn" { in_spam=9; in_ham=0}
|> Map.add "auto" { in_spam=6; in_ham=1}
|> Map.add "automated" { in_spam=0; in_ham=14}
|> Map.add "available" { in_spam=5; in_ham=7}
|> Map.add "avast" { in_spam=0; in_ham=5}
|> Map.add "baby" { in_spam=1; in_ham=3}
|> Map.add "back" { in_spam=3; in_ham=10}
|> Map.add "bad" { in_spam=0; in_ham=22}
|> Map.add "bank" { in_spam=5; in_ham=5}
|> Map.add "base" { in_spam=2; in_ham=12}
|> Map.add "based" { in_spam=0; in_ham=5}
|> Map.add "because" { in_spam=0; in_ham=3}
|> Map.add "been" { in_spam=3; in_ham=2}
|> Map.add "before" { in_spam=0; in_ham=7}
|> Map.add "behaviours" { in_spam=0; in_ham=17}
|> Map.add "behind" { in_spam=2; in_ham=6}
|> Map.add "bell" { in_spam=0; in_ham=4}
|> Map.add "berkeley" { in_spam=0; in_ham=3}
|> Map.add "best" { in_spam=17; in_ham=3}
|> Map.add "biblical" { in_spam=0; in_ham=5}
|> Map.add "big" { in_spam=8; in_ham=29}
|> Map.add "biggest" { in_spam=0; in_ham=7}
|> Map.add "bill" { in_spam=0; in_ham=4}
|> Map.add "bindings" { in_spam=0; in_ham=3}
|> Map.add "bits" { in_spam=0; in_ham=7}
|> Map.add "blair" { in_spam=1; in_ham=4}
|> Map.add "blew" { in_spam=0; in_ham=3}
|> Map.add "bliss" { in_spam=0; in_ham=55}
|> Map.add "blog" { in_spam=0; in_ham=3}
|> Map.add "blood" { in_spam=0; in_ham=4}
|> Map.add "blue" { in_spam=0; in_ham=3}
|> Map.add "body" { in_spam=0; in_ham=3}
|> Map.add "books" { in_spam=0; in_ham=3}
|> Map.add "born" { in_spam=0; in_ham=3}
|> Map.add "boy" { in_spam=0; in_ham=3}
|> Map.add "boycotting" { in_spam=0; in_ham=8}
|> Map.add "breast" { in_spam=3; in_ham=2}
|> Map.add "british" { in_spam=0; in_ham=4}
|> Map.add "broke" { in_spam=0; in_ham=3}
|> Map.add "broken" { in_spam=0; in_ham=4}
|> Map.add "brown" { in_spam=0; in_ham=5}
|> Map.add "browsers" { in_spam=0; in_ham=4}
|> Map.add "bucks" { in_spam=1; in_ham=12}
|> Map.add "bug" { in_spam=0; in_ham=43}
|> Map.add "build" { in_spam=1; in_ham=10}
|> Map.add "building" { in_spam=0; in_ham=4}
|> Map.add "burns" { in_spam=0; in_ham=4}
|> Map.add "bush" { in_spam=0; in_ham=9}
|> Map.add "business" { in_spam=7; in_ham=7}
|> Map.add "but" { in_spam=0; in_ham=10}
|> Map.add "buy" { in_spam=3; in_ham=6}
|> Map.add "buys" { in_spam=0; in_ham=5}
|> Map.add "cable" { in_spam=3; in_ham=1}
|> Map.add "cafe" { in_spam=0; in_ham=5}
|> Map.add "california" { in_spam=0; in_ham=3}
|> Map.add "call" { in_spam=0; in_ham=5}
|> Map.add "calling" { in_spam=0; in_ham=3}
|> Map.add "calls" { in_spam=3; in_ham=2}
|> Map.add "can" { in_spam=4; in_ham=15}
|> Map.add "can't" { in_spam=0; in_ham=12}
|> Map.add "canadians" { in_spam=0; in_ham=8}
|> Map.add "cancer" { in_spam=0; in_ham=4}
|> Map.add "capitalism" { in_spam=0; in_ham=6}
|> Map.add "car" { in_spam=0; in_ham=8}
|> Map.add "carcooning" { in_spam=0; in_ham=3}
|> Map.add "card" { in_spam=4; in_ham=3}
|> Map.add "case" { in_spam=2; in_ham=14}
|> Map.add "cds" { in_spam=1; in_ham=2}
|> Map.add "cell" { in_spam=3; in_ham=1}
|> Map.add "change" { in_spam=0; in_ham=16}
|> Map.add "changed" { in_spam=0; in_ham=5}
|> Map.add "cheap" { in_spam=3; in_ham=2}
|> Map.add "child" { in_spam=3; in_ham=1}
|> Map.add "china" { in_spam=0; in_ham=3}
|> Map.add "cigarettes" { in_spam=3; in_ham=2}
|> Map.add "city" { in_spam=1; in_ham=5}
|> Map.add "clearance" { in_spam=8; in_ham=0}
|> Map.add "click" { in_spam=1; in_ham=17}
|> Map.add "client" { in_spam=0; in_ham=6}
|> Map.add "cloudmark" { in_spam=0; in_ham=5}
|> Map.add "cluetrain" { in_spam=0; in_ham=9}
|> Map.add "code" { in_spam=0; in_ham=6}
|> Map.add "codecs" { in_spam=0; in_ham=3}
|> Map.add "collision" { in_spam=0; in_ham=6}
|> Map.add "colophon" { in_spam=0; in_ham=3}
|> Map.add "com" { in_spam=8; in_ham=23}
|> Map.add "combo" { in_spam=0; in_ham=3}
|> Map.add "coming" { in_spam=1; in_ham=2}
|> Map.add "comment" { in_spam=0; in_ham=3}
|> Map.add "communism" { in_spam=0; in_ham=5}
|> Map.add "companies" { in_spam=2; in_ham=4}
|> Map.add "company" { in_spam=6; in_ham=2}
|> Map.add "competition" { in_spam=3; in_ham=2}
|> Map.add "compile" { in_spam=0; in_ham=9}
|> Map.add "complete" { in_spam=3; in_ham=9}
|> Map.add "computer" { in_spam=10; in_ham=5}
|> Map.add "computing" { in_spam=0; in_ham=5}
|> Map.add "comrade" { in_spam=0; in_ham=5}
|> Map.add "conf" { in_spam=0; in_ham=3}
|> Map.add "conference" { in_spam=3; in_ham=1}
|> Map.add "consult" { in_spam=0; in_ham=5}
|> Map.add "content" { in_spam=1; in_ham=6}
|> Map.add "converting" { in_spam=0; in_ham=3}
|> Map.add "copy" { in_spam=2; in_ham=2}
|> Map.add "corpus" { in_spam=0; in_ham=4}
|> Map.add "cost" { in_spam=6; in_ham=1}
|> Map.add "could" { in_spam=0; in_ham=7}
|> Map.add "court" { in_spam=0; in_ham=3}
|> Map.add "cpx" { in_spam=0; in_ham=5}
|> Map.add "crash" { in_spam=0; in_ham=4}
|> Map.add "critical" { in_spam=1; in_ham=4}
|> Map.add "crony" { in_spam=0; in_ham=6}
|> Map.add "csl" { in_spam=0; in_ham=3}
|> Map.add "current" { in_spam=0; in_ham=12}
|> Map.add "curse" { in_spam=0; in_ham=9}
|> Map.add "curseen" { in_spam=0; in_ham=5}
|> Map.add "custom" { in_spam=4; in_ham=4}
|> Map.add "cvs" { in_spam=0; in_ham=42}
|> Map.add "cystals" { in_spam=0; in_ham=5}
|> Map.add "data" { in_spam=0; in_ham=6}
|> Map.add "datapower" { in_spam=0; in_ham=13}
|> Map.add "date" { in_spam=0; in_ham=8}
|> Map.add "day" { in_spam=3; in_ham=11}
|> Map.add "days" { in_spam=4; in_ham=1}
|> Map.add "dcc" { in_spam=0; in_ham=4}
|> Map.add "deal" { in_spam=1; in_ham=6}
|> Map.add "defnitions" { in_spam=0; in_ham=7}
|> Map.add "deleting" { in_spam=0; in_ham=5}
|> Map.add "delivers" { in_spam=0; in_ham=4}
|> Map.add "dell" { in_spam=0; in_ham=9}
|> Map.add "delta" { in_spam=0; in_ham=11}
|> Map.add "dependencies" { in_spam=0; in_ham=7}
|> Map.add "deployment" { in_spam=0; in_ham=28}
|> Map.add "design" { in_spam=1; in_ham=2}
|> Map.add "development" { in_spam=0; in_ham=3}
|> Map.add "device" { in_spam=0; in_ham=5}
|> Map.add "die" { in_spam=0; in_ham=4}
|> Map.add "digital" { in_spam=1; in_ham=16}
|> Map.add "digression" { in_spam=0; in_ham=5}
|> Map.add "directory" { in_spam=0; in_ham=4}
|> Map.add "disappearing" { in_spam=0; in_ham=3}
|> Map.add "display" { in_spam=0; in_ham=5}
|> Map.add "dist-upgrade" { in_spam=0; in_ham=5}
|> Map.add "distributed" { in_spam=0; in_ham=6}
|> Map.add "ditching" { in_spam=0; in_ham=7}
|> Map.add "dma" { in_spam=0; in_ham=17}
|> Map.add "dns" { in_spam=0; in_ham=7}
|> Map.add "doc" { in_spam=0; in_ham=6}
|> Map.add "does" { in_spam=0; in_ham=3}
|> Map.add "doesnt" { in_spam=0; in_ham=9}
|> Map.add "doing" { in_spam=3; in_ham=1}
|> Map.add "domain" { in_spam=3; in_ham=4}
|> Map.add "don't" { in_spam=5; in_ham=5}
|> Map.add "dont" { in_spam=2; in_ham=2}
|> Map.add "double" { in_spam=1; in_ham=2}
|> Map.add "down" { in_spam=3; in_ham=1}
|> Map.add "drive" { in_spam=0; in_ham=17}
|> Map.add "drm" { in_spam=0; in_ham=3}
|> Map.add "dude" { in_spam=0; in_ham=5}
|> Map.add "duel" { in_spam=0; in_ham=3}
|> Map.add "dumb" { in_spam=0; in_ham=6}
|> Map.add "duplicate" { in_spam=0; in_ham=5}
|> Map.add "dvd" { in_spam=2; in_ham=27}
|> Map.add "dvds" { in_spam=1; in_ham=2}
|> Map.add "dylsexics" { in_spam=0; in_ham=8}
|> Map.add "earn" { in_spam=5; in_ham=1}
|> Map.add "earthviewer" { in_spam=0; in_ham=6}
|> Map.add "easy" { in_spam=2; in_ham=26}
|> Map.add "ebay" { in_spam=7; in_ham=3}
|> Map.add "ebusiness" { in_spam=0; in_ham=9}
|> Map.add "edsel" { in_spam=0; in_ham=7}
|> Map.add "effective" { in_spam=1; in_ham=2}
|> Map.add "eircom" { in_spam=0; in_ham=4}
|> Map.add "electric" { in_spam=0; in_ham=8}
|> Map.add "else" { in_spam=0; in_ham=7}
|> Map.add "email" { in_spam=5; in_ham=13}
|> Map.add "empire" { in_spam=0; in_ham=26}
|> Map.add "encryption" { in_spam=0; in_ham=4}
|> Map.add "erratum" { in_spam=0; in_ham=3}
|> Map.add "error" { in_spam=1; in_ham=12}
|> Map.add "errors" { in_spam=0; in_ham=8}
|> Map.add "etc" { in_spam=0; in_ham=3}
|> Map.add "euro" { in_spam=0; in_ham=3}
|> Map.add "europe" { in_spam=0; in_ham=5}
|> Map.add "event" { in_spam=0; in_ham=4}
|> Map.add "everyone" { in_spam=0; in_ham=3}
|> Map.add "example" { in_spam=4; in_ham=3}
|> Map.add "exmh" { in_spam=0; in_ham=26}
|> Map.add "exmh-unseen" { in_spam=0; in_ham=4}
|> Map.add "extended" { in_spam=6; in_ham=0}
|> Map.add "face" { in_spam=0; in_ham=4}
|> Map.add "fails" { in_spam=0; in_ham=6}
|> Map.add "fake" { in_spam=0; in_ham=4}
|> Map.add "false" { in_spam=0; in_ham=20}
|> Map.add "family" { in_spam=1; in_ham=2}
|> Map.add "fast" { in_spam=3; in_ham=3}
|> Map.add "feb" { in_spam=0; in_ham=3}
|> Map.add "feeds" { in_spam=1; in_ham=3}
|> Map.add "fight" { in_spam=0; in_ham=3}
|> Map.add "file" { in_spam=0; in_ham=15}
|> Map.add "files" { in_spam=0; in_ham=5}
|> Map.add "finally" { in_spam=0; in_ham=11}
|> Map.add "finance" { in_spam=0; in_ham=5}
|> Map.add "find" { in_spam=5; in_ham=14}
|> Map.add "finds" { in_spam=0; in_ham=3}
|> Map.add "fire" { in_spam=0; in_ham=4}
|> Map.add "fires" { in_spam=0; in_ham=4}
|> Map.add "firewall" { in_spam=0; in_ham=5}
|> Map.add "first" { in_spam=2; in_ham=25}
|> Map.add "flat" { in_spam=0; in_ham=3}
|> Map.add "flavor" { in_spam=0; in_ham=5}
|> Map.add "focus" { in_spam=1; in_ham=17}
|> Map.add "fogbugz" { in_spam=0; in_ham=3}
|> Map.add "folks" { in_spam=0; in_ham=4}
|> Map.add "food" { in_spam=0; in_ham=4}
|> Map.add "for" { in_spam=49; in_ham=289}
|> Map.add "forteana" { in_spam=0; in_ham=5}
|> Map.add "fortune" { in_spam=7; in_ham=0}
|> Map.add "forum" { in_spam=1; in_ham=5}
|> Map.add "found" { in_spam=1; in_ham=4}
|> Map.add "four" { in_spam=0; in_ham=4}
|> Map.add "francisco" { in_spam=0; in_ham=4}
|> Map.add "free" { in_spam=30; in_ham=10}
|> Map.add "freebsd" { in_spam=0; in_ham=3}
|> Map.add "freetype" { in_spam=0; in_ham=7}
|> Map.add "freqs" { in_spam=0; in_ham=3}
|> Map.add "freshrpms" { in_spam=0; in_ham=7}
|> Map.add "friend" { in_spam=2; in_ham=2}
|> Map.add "friends" { in_spam=0; in_ham=12}
|> Map.add "from" { in_spam=10; in_ham=67}
|> Map.add "fun" { in_spam=0; in_ham=3}
|> Map.add "funny" { in_spam=0; in_ham=8}
|> Map.add "future" { in_spam=2; in_ham=2}
|> Map.add "fwd" { in_spam=4; in_ham=30}
|> Map.add "game" { in_spam=2; in_ham=5}
|> Map.add "games" { in_spam=0; in_ham=3}
|> Map.add "gasp" { in_spam=0; in_ham=7}
|> Map.add "gawd" { in_spam=0; in_ham=3}
|> Map.add "gazing" { in_spam=0; in_ham=3}
|> Map.add "gbayes" { in_spam=0; in_ham=5}
|> Map.add "gdc" { in_spam=0; in_ham=6}
|> Map.add "gecko" { in_spam=0; in_ham=5}
|> Map.add "gene" { in_spam=0; in_ham=3}
|> Map.add "get" { in_spam=19; in_ham=13}
|> Map.add "gets" { in_spam=2; in_ham=18}
|> Map.add "getting" { in_spam=0; in_ham=10}
|> Map.add "giant" { in_spam=0; in_ham=3}
|> Map.add "gives" { in_spam=0; in_ham=7}
|> Map.add "giving" { in_spam=1; in_ham=6}
|> Map.add "gkrellm" { in_spam=0; in_ham=3}
|> Map.add "global" { in_spam=0; in_ham=27}
|> Map.add "god" { in_spam=0; in_ham=16}
|> Map.add "goes" { in_spam=0; in_ham=5}
|> Map.add "going" { in_spam=0; in_ham=8}
|> Map.add "gold" { in_spam=0; in_ham=3}
|> Map.add "good" { in_spam=0; in_ham=15}
|> Map.add "goodbye" { in_spam=0; in_ham=26}
|> Map.add "google" { in_spam=0; in_ham=17}
|> Map.add "got" { in_spam=3; in_ham=4}
|> Map.add "gov" { in_spam=0; in_ham=14}
|> Map.add "government" { in_spam=1; in_ham=12}
|> Map.add "gpg" { in_spam=0; in_ham=9}
|> Map.add "great" { in_spam=1; in_ham=6}
|> Map.add "grlygrl" { in_spam=0; in_ham=4}
|> Map.add "growing" { in_spam=3; in_ham=1}
|> Map.add "gst-devel" { in_spam=0; in_ham=3}
|> Map.add "guaranteed" { in_spam=6; in_ham=0}
|> Map.add "habeus" { in_spam=0; in_ham=20}
|> Map.add "hack" { in_spam=0; in_ham=4}
|> Map.add "had" { in_spam=0; in_ham=9}
|> Map.add "half" { in_spam=2; in_ham=2}
|> Map.add "hammie" { in_spam=0; in_ham=3}
|> Map.add "handling" { in_spam=0; in_ham=4}
|> Map.add "hangs" { in_spam=0; in_ham=5}
|> Map.add "hanson's" { in_spam=0; in_ham=21}
|> Map.add "has" { in_spam=2; in_ham=25}
|> Map.add "hashes" { in_spam=0; in_ham=6}
|> Map.add "hassle" { in_spam=1; in_ham=4}
|> Map.add "hat" { in_spam=0; in_ham=10}
|> Map.add "have" { in_spam=7; in_ham=8}
|> Map.add "having" { in_spam=0; in_ham=5}
|> Map.add "headline" { in_spam=0; in_ham=4}
|> Map.add "headlines" { in_spam=0; in_ham=28}
|> Map.add "hello" { in_spam=3; in_ham=2}
|> Map.add "help" { in_spam=5; in_ham=13}
|> Map.add "her" { in_spam=2; in_ham=2}
|> Map.add "here" { in_spam=12; in_ham=5}
|> Map.add "hex" { in_spam=0; in_ham=3}
|> Map.add "hgh" { in_spam=5; in_ham=0}
|> Map.add "hidden" { in_spam=0; in_ham=3}
|> Map.add "high" { in_spam=1; in_ham=14}
|> Map.add "hiring" { in_spam=6; in_ham=0}
|> Map.add "his" { in_spam=1; in_ham=21}
|> Map.add "histograms" { in_spam=0; in_ham=8}
|> Map.add "history" { in_spam=1; in_ham=2}
|> Map.add "hit" { in_spam=5; in_ham=3}
|> Map.add "hits" { in_spam=0; in_ham=3}
|> Map.add "holidays" { in_spam=1; in_ham=4}
|> Map.add "home" { in_spam=15; in_ham=8}
|> Map.add "homemade" { in_spam=0; in_ham=7}
|> Map.add "honor" { in_spam=0; in_ham=5}
|> Map.add "horse" { in_spam=0; in_ham=6}
|> Map.add "hottest" { in_spam=1; in_ham=12}
|> Map.add "house" { in_spam=3; in_ham=2}
|> Map.add "how" { in_spam=4; in_ham=19}
|> Map.add "howto" { in_spam=0; in_ham=3}
|> Map.add "html" { in_spam=0; in_ham=5}
|> Map.add "http" { in_spam=1; in_ham=14}
|> Map.add "human" { in_spam=1; in_ham=6}
|> Map.add "hybrid" { in_spam=0; in_ham=3}
|> Map.add "hyperion" { in_spam=0; in_ham=5}
|> Map.add "i'm" { in_spam=1; in_ham=9}
|> Map.add "i've" { in_spam=0; in_ham=8}
|> Map.add "ibooks" { in_spam=0; in_ham=3}
|> Map.add "iceland" { in_spam=0; in_ham=4}
|> Map.add "ide" { in_spam=1; in_ham=5}
|> Map.add "idea" { in_spam=0; in_ham=6}
|> Map.add "identity" { in_spam=0; in_ham=5}
|> Map.add "idj" { in_spam=0; in_ham=3}
|> Map.add "iiu" { in_spam=1; in_ham=3}
|> Map.add "ilug" { in_spam=32; in_ham=92}
|> Map.add "ilug-social" { in_spam=14; in_ham=0}
|> Map.add "image" { in_spam=1; in_ham=11}
|> Map.add "imam" { in_spam=0; in_ham=4}
|> Map.add "img" { in_spam=0; in_ham=4}
|> Map.add "impact" { in_spam=0; in_ham=3}
|> Map.add "increase" { in_spam=3; in_ham=1}
|> Map.add "india's" { in_spam=0; in_ham=10}
|> Map.add "information" { in_spam=6; in_ham=5}
|> Map.add "insert" { in_spam=0; in_ham=9}
|> Map.add "install" { in_spam=0; in_ham=9}
|> Map.add "install'" { in_spam=0; in_ham=3}
|> Map.add "insurance" { in_spam=12; in_ham=0}
|> Map.add "interest" { in_spam=5; in_ham=0}
|> Map.add "interesting" { in_spam=0; in_ham=9}
|> Map.add "internet" { in_spam=7; in_ham=12}
|> Map.add "into" { in_spam=0; in_ham=10}
|> Map.add "investment" { in_spam=7; in_ham=0}
|> Map.add "ira" { in_spam=0; in_ham=4}
|> Map.add "iraq" { in_spam=1; in_ham=7}
|> Map.add "irr" { in_spam=0; in_ham=5}
|> Map.add "iso-" { in_spam=7; in_ham=0}
|> Map.add "isp" { in_spam=2; in_ham=2}
|> Map.add "issues" { in_spam=0; in_ham=4}
|> Map.add "it's" { in_spam=0; in_ham=8}
|> Map.add "its" { in_spam=0; in_ham=3}
|> Map.add "java" { in_spam=0; in_ham=35}
|> Map.add "jeremy" { in_spam=0; in_ham=4}
|> Map.add "job" { in_spam=1; in_ham=5}
|> Map.add "journal" { in_spam=0; in_ham=3}
|> Map.add "jump" { in_spam=0; in_ham=9}
|> Map.add "junk" { in_spam=1; in_ham=2}
|> Map.add "just" { in_spam=4; in_ham=10}
|> Map.add "kernel" { in_spam=0; in_ham=8}
|> Map.add "kernels" { in_spam=0; in_ham=7}
|> Map.add "key" { in_spam=0; in_ham=16}
|> Map.add "kiddies" { in_spam=0; in_ham=35}
|> Map.add "kill" { in_spam=0; in_ham=6}
|> Map.add "kind" { in_spam=4; in_ham=1}
|> Map.add "know" { in_spam=1; in_ham=2}
|> Map.add "lame-" { in_spam=0; in_ham=4}
|> Map.add "language" { in_spam=0; in_ham=3}
|> Map.add "laptop" { in_spam=1; in_ham=8}
|> Map.add "last" { in_spam=3; in_ham=8}
|> Map.add "latest" { in_spam=0; in_ham=6}
|> Map.add "latitude" { in_spam=0; in_ham=5}
|> Map.add "left" { in_spam=0; in_ham=10}
|> Map.add "legacy" { in_spam=0; in_ham=3}
|> Map.add "less" { in_spam=3; in_ham=2}
|> Map.add "let" { in_spam=3; in_ham=2}
|> Map.add "level" { in_spam=1; in_ham=3}
|> Map.add "liberal" { in_spam=0; in_ham=9}
|> Map.add "libs" { in_spam=0; in_ham=4}
|> Map.add "licences" { in_spam=0; in_ham=4}
|> Map.add "lie" { in_spam=1; in_ham=2}
|> Map.add "life" { in_spam=10; in_ham=10}
|> Map.add "lifegem" { in_spam=0; in_ham=6}
|> Map.add "light" { in_spam=0; in_ham=3}
|> Map.add "like" { in_spam=1; in_ham=9}
|> Map.add "lineup" { in_spam=0; in_ham=7}
|> Map.add "linking" { in_spam=0; in_ham=7}
|> Map.add "linux" { in_spam=0; in_ham=18}
|> Map.add "list" { in_spam=0; in_ham=7}
|> Map.add "lists" { in_spam=0; in_ham=6}
|> Map.add "little" { in_spam=1; in_ham=2}
|> Map.add "live" { in_spam=0; in_ham=3}
|> Map.add "living" { in_spam=1; in_ham=3}
|> Map.add "location" { in_spam=0; in_ham=6}
|> Map.add "log" { in_spam=0; in_ham=8}
|> Map.add "looking" { in_spam=2; in_ham=7}
|> Map.add "looks" { in_spam=0; in_ham=3}
|> Map.add "lord" { in_spam=0; in_ham=3}
|> Map.add "lost" { in_spam=0; in_ham=6}
|> Map.add "lot" { in_spam=0; in_ham=3}
|> Map.add "love" { in_spam=0; in_ham=3}
|> Map.add "low" { in_spam=13; in_ham=14}
|> Map.add "lowest" { in_spam=6; in_ham=0}
|> Map.add "mac" { in_spam=0; in_ham=8}
|> Map.add "machine" { in_spam=0; in_ham=6}
|> Map.add "made" { in_spam=0; in_ham=26}
|> Map.add "mail" { in_spam=0; in_ham=18}
|> Map.add "major" { in_spam=0; in_ham=4}
|> Map.add "make" { in_spam=9; in_ham=3}
|> Map.add "makes" { in_spam=1; in_ham=5}
|> Map.add "making" { in_spam=1; in_ham=4}
|> Map.add "mama" { in_spam=0; in_ham=3}
|> Map.add "man" { in_spam=1; in_ham=24}
|> Map.add "management" { in_spam=1; in_ham=7}
|> Map.add "mark" { in_spam=0; in_ham=8}
|> Map.add "marked" { in_spam=0; in_ham=3}
|> Map.add "market" { in_spam=6; in_ham=1}
|> Map.add "marketing" { in_spam=7; in_ham=1}
|> Map.add "mass-check" { in_spam=0; in_ham=7}
|> Map.add "masses" { in_spam=0; in_ham=5}
|> Map.add "matey" { in_spam=0; in_ham=5}
|> Map.add "matter" { in_spam=0; in_ham=6}
|> Map.add "may" { in_spam=2; in_ham=6}
|> Map.add "maybe" { in_spam=1; in_ham=6}
|> Map.add "meet" { in_spam=1; in_ham=13}
|> Map.add "meetings" { in_spam=0; in_ham=12}
|> Map.add "memory" { in_spam=1; in_ham=2}
|> Map.add "men" { in_spam=0; in_ham=6}
|> Map.add "merging" { in_spam=0; in_ham=4}
|> Map.add "message" { in_spam=1; in_ham=40}
|> Map.add "messages" { in_spam=0; in_ham=3}
|> Map.add "microsoft" { in_spam=0; in_ham=6}
|> Map.add "mime" { in_spam=0; in_ham=3}
|> Map.add "missing" { in_spam=0; in_ham=3}
|> Map.add "mit" { in_spam=0; in_ham=3}
|> Map.add "modem" { in_spam=0; in_ham=6}
|> Map.add "moment" { in_spam=1; in_ham=20}
|> Map.add "money" { in_spam=16; in_ham=0}
|> Map.add "month" { in_spam=7; in_ham=2}
|> Map.add "moon" { in_spam=0; in_ham=4}
|> Map.add "more" { in_spam=3; in_ham=13}
|> Map.add "mortgage" { in_spam=10; in_ham=0}
|> Map.add "move" { in_spam=0; in_ham=3}
|> Map.add "movie" { in_spam=2; in_ham=2}
|> Map.add "mozilla" { in_spam=0; in_ham=4}
|> Map.add "mplayer" { in_spam=0; in_ham=15}
|> Map.add "multipart" { in_spam=0; in_ham=3}
|> Map.add "muppet" { in_spam=0; in_ham=3}
|> Map.add "music" { in_spam=0; in_ham=5}
|> Map.add "mystery" { in_spam=0; in_ham=3}
|> Map.add "name" { in_spam=1; in_ham=15}
|> Map.add "national" { in_spam=0; in_ham=22}
|> Map.add "navel" { in_spam=0; in_ham=3}
|> Map.add "need" { in_spam=12; in_ham=1}
|> Map.add "needed" { in_spam=9; in_ham=0}
|> Map.add "negative" { in_spam=0; in_ham=13}
|> Map.add "nessus" { in_spam=0; in_ham=6}
|> Map.add "net" { in_spam=2; in_ham=27}
|> Map.add "network" { in_spam=0; in_ham=3}
|> Map.add "never" { in_spam=2; in_ham=3}
|> Map.add "new" { in_spam=13; in_ham=102}
|> Map.add "newbie" { in_spam=0; in_ham=8}
|> Map.add "newer" { in_spam=0; in_ham=3}
|> Map.add "news" { in_spam=5; in_ham=17}
|> Map.add "next" { in_spam=1; in_ham=7}
|> Map.add "nile" { in_spam=0; in_ham=3}
|> Map.add "nintendo" { in_spam=0; in_ham=4}
|> Map.add "nixia" { in_spam=0; in_ham=10}
|> Map.add "nobel" { in_spam=0; in_ham=11}
|> Map.add "none" { in_spam=0; in_ham=3}
|> Map.add "normal" { in_spam=0; in_ham=5}
|> Map.add "norton" { in_spam=7; in_ham=0}
|> Map.add "not" { in_spam=3; in_ham=34}
|> Map.add "notes" { in_spam=0; in_ham=5}
|> Map.add "nothing" { in_spam=0; in_ham=4}
|> Map.add "now" { in_spam=12; in_ham=14}
|> Map.add "null" { in_spam=0; in_ham=19}
|> Map.add "number" { in_spam=0; in_ham=3}
|> Map.add "nytimes" { in_spam=0; in_ham=4}
|> Map.add "off" { in_spam=2; in_ham=4}
|> Map.add "offers" { in_spam=1; in_ham=2}
|> Map.add "old" { in_spam=1; in_ham=6}
|> Map.add "one" { in_spam=10; in_ham=9}
|> Map.add "online" { in_spam=9; in_ham=8}
|> Map.add "only" { in_spam=9; in_ham=2}
|> Map.add "oops" { in_spam=0; in_ham=3}
|> Map.add "opens" { in_spam=0; in_ham=4}
|> Map.add "openssh" { in_spam=0; in_ham=3}
|> Map.add "optical" { in_spam=0; in_ham=5}
|> Map.add "option" { in_spam=0; in_ham=3}
|> Map.add "oracle" { in_spam=0; in_ham=3}
|> Map.add "orbad" { in_spam=0; in_ham=4}
|> Map.add "orders" { in_spam=1; in_ham=4}
|> Map.add "org" { in_spam=3; in_ham=4}
|> Map.add "osxcon" { in_spam=0; in_ham=6}
|> Map.add "other" { in_spam=3; in_ham=9}
|> Map.add "ouch" { in_spam=0; in_ham=63}
|> Map.add "our" { in_spam=0; in_ham=13}
|> Map.add "out" { in_spam=3; in_ham=17}
|> Map.add "over" { in_spam=3; in_ham=9}
|> Map.add "own" { in_spam=3; in_ham=9}
|> Map.add "ozzie" { in_spam=0; in_ham=3}
|> Map.add "package" { in_spam=1; in_ham=15}
|> Map.add "packages" { in_spam=0; in_ham=11}
|> Map.add "packaging" { in_spam=0; in_ham=4}
|> Map.add "packge" { in_spam=0; in_ham=4}
|> Map.add "palestinians" { in_spam=0; in_ham=10}
|> Map.add "palm" { in_spam=0; in_ham=3}
|> Map.add "parodies" { in_spam=0; in_ham=3}
|> Map.add "partnership" { in_spam=5; in_ham=0}
|> Map.add "party" { in_spam=0; in_ham=3}
|> Map.add "patch" { in_spam=1; in_ham=12}
|> Map.add "patent" { in_spam=0; in_ham=8}
|> Map.add "path" { in_spam=0; in_ham=3}
|> Map.add "pay" { in_spam=3; in_ham=4}
|> Map.add "people" { in_spam=2; in_ham=5}
|> Map.add "per" { in_spam=9; in_ham=0}
|> Map.add "perl" { in_spam=0; in_ham=60}
|> Map.add "personals" { in_spam=0; in_ham=11}
|> Map.add "phew" { in_spam=0; in_ham=4}
|> Map.add "phil" { in_spam=0; in_ham=3}
|> Map.add "phone" { in_spam=4; in_ham=2}
|> Map.add "photoshop" { in_spam=0; in_ham=6}
|> Map.add "php" { in_spam=0; in_ham=3}
|> Map.add "pics" { in_spam=1; in_ham=3}
|> Map.add "pictures" { in_spam=3; in_ham=2}
|> Map.add "piece" { in_spam=1; in_ham=2}
|> Map.add "pine" { in_spam=0; in_ham=3}
|> Map.add "pirates" { in_spam=0; in_ham=15}
|> Map.add "place" { in_spam=1; in_ham=13}
|> Map.add "plan" { in_spam=1; in_ham=3}
|> Map.add "planet" { in_spam=0; in_ham=5}
|> Map.add "plans" { in_spam=3; in_ham=4}
|> Map.add "play" { in_spam=4; in_ham=6}
|> Map.add "player" { in_spam=0; in_ham=8}
|> Map.add "playing" { in_spam=0; in_ham=3}
|> Map.add "playlists" { in_spam=0; in_ham=4}
|> Map.add "please" { in_spam=7; in_ham=11}
|> Map.add "plucker" { in_spam=0; in_ham=3}
|> Map.add "plugins" { in_spam=0; in_ham=4}
|> Map.add "police" { in_spam=1; in_ham=5}
|> Map.add "pop" { in_spam=0; in_ham=7}
|> Map.add "port" { in_spam=0; in_ham=3}
|> Map.add "positive" { in_spam=0; in_ham=7}
|> Map.add "power" { in_spam=2; in_ham=3}
|> Map.add "powerbooks" { in_spam=0; in_ham=3}
|> Map.add "price" { in_spam=6; in_ham=2}
|> Map.add "private" { in_spam=3; in_ham=1}
|> Map.add "prize" { in_spam=0; in_ham=6}
|> Map.add "prob" { in_spam=0; in_ham=4}
|> Map.add "problem" { in_spam=0; in_ham=45}
|> Map.add "problems" { in_spam=1; in_ham=23}
|> Map.add "process" { in_spam=0; in_ham=7}
|> Map.add "procmail" { in_spam=0; in_ham=3}
|> Map.add "product" { in_spam=3; in_ham=2}
|> Map.add "prohibited" { in_spam=0; in_ham=4}
|> Map.add "property" { in_spam=1; in_ham=2}
|> Map.add "protect" { in_spam=5; in_ham=0}
|> Map.add "public" { in_spam=0; in_ham=6}
|> Map.add "put" { in_spam=2; in_ham=4}
|> Map.add "puts" { in_spam=0; in_ham=6}
|> Map.add "python" { in_spam=0; in_ham=7}
|> Map.add "query" { in_spam=0; in_ham=6}
|> Map.add "question" { in_spam=0; in_ham=13}
|> Map.add "questions" { in_spam=0; in_ham=5}
|> Map.add "quick" { in_spam=1; in_ham=6}
|> Map.add "quickly" { in_spam=1; in_ham=2}
|> Map.add "radio" { in_spam=0; in_ham=8}
|> Map.add "raid" { in_spam=0; in_ham=3}
|> Map.add "raises" { in_spam=0; in_ham=3}
|> Map.add "rambus" { in_spam=0; in_ham=4}
|> Map.add "rate" { in_spam=3; in_ham=14}
|> Map.add "rates" { in_spam=18; in_ham=0}
|> Map.add "ray" { in_spam=0; in_ham=3}
|> Map.add "razor" { in_spam=0; in_ham=52}
|> Map.add "razor-users" { in_spam=0; in_ham=89}
|> Map.add "rdf" { in_spam=0; in_ham=3}
|> Map.add "read" { in_spam=1; in_ham=7}
|> Map.add "ready" { in_spam=2; in_ham=8}
|> Map.add "real" { in_spam=2; in_ham=7}
|> Map.add "rebuild" { in_spam=0; in_ham=6}
|> Map.add "recommended" { in_spam=0; in_ham=13}
|> Map.add "record" { in_spam=0; in_ham=6}
|> Map.add "recovery" { in_spam=0; in_ham=11}
|> Map.add "recreations" { in_spam=0; in_ham=4}
|> Map.add "red" { in_spam=0; in_ham=10}
|> Map.add "redhat" { in_spam=0; in_ham=12}
|> Map.add "reducing" { in_spam=0; in_ham=3}
|> Map.add "related" { in_spam=0; in_ham=12}
|> Map.add "release" { in_spam=1; in_ham=20}
|> Map.add "released" { in_spam=0; in_ham=8}
|> Map.add "removed" { in_spam=0; in_ham=4}
|> Map.add "report" { in_spam=1; in_ham=20}
|> Map.add "reports" { in_spam=0; in_ham=5}
|> Map.add "repository" { in_spam=0; in_ham=3}
|> Map.add "reps" { in_spam=8; in_ham=0}
|> Map.add "requested" { in_spam=1; in_ham=3}
|> Map.add "results" { in_spam=1; in_ham=9}
|> Map.add "revealed" { in_spam=0; in_ham=3}
|> Map.add "reveals" { in_spam=1; in_ham=3}
|> Map.add "review" { in_spam=0; in_ham=25}
|> Map.add "revocation" { in_spam=0; in_ham=4}
|> Map.add "right" { in_spam=2; in_ham=3}
|> Map.add "rights" { in_spam=0; in_ham=3}
|> Map.add "ringing" { in_spam=0; in_ham=4}
|> Map.add "rip" { in_spam=0; in_ham=3}
|> Map.add "rise" { in_spam=0; in_ham=3}
|> Map.add "risk" { in_spam=2; in_ham=2}
|> Map.add "risks" { in_spam=0; in_ham=5}
|> Map.add "roman" { in_spam=0; in_ham=27}
|> Map.add "router" { in_spam=0; in_ham=3}
|> Map.add "rpm" { in_spam=0; in_ham=14}
|> Map.add "rpms" { in_spam=0; in_ham=5}
|> Map.add "rss" { in_spam=0; in_ham=9}
|> Map.add "rule" { in_spam=0; in_ham=5}
|> Map.add "rules" { in_spam=0; in_ham=8}
|> Map.add "sacvs" { in_spam=0; in_ham=18}
|> Map.add "sadev" { in_spam=0; in_ham=73}
|> Map.add "sale" { in_spam=10; in_ham=0}
|> Map.add "sales" { in_spam=3; in_ham=1}
|> Map.add "san" { in_spam=0; in_ham=4}
|> Map.add "satalk" { in_spam=1; in_ham=138}
|> Map.add "saturation" { in_spam=0; in_ham=4}
|> Map.add "sauced" { in_spam=0; in_ham=6}
|> Map.add "save" { in_spam=7; in_ham=5}
|> Map.add "says" { in_spam=0; in_ham=3}
|> Map.add "school" { in_spam=0; in_ham=3}
|> Map.add "scientists" { in_spam=0; in_ham=3}
|> Map.add "scoop" { in_spam=3; in_ham=6}
|> Map.add "score" { in_spam=0; in_ham=3}
|> Map.add "secret" { in_spam=3; in_ham=2}
|> Map.add "secure" { in_spam=0; in_ham=19}
|> Map.add "sed" { in_spam=0; in_ham=26}
|> Map.add "see" { in_spam=2; in_ham=4}
|> Map.add "seeks" { in_spam=0; in_ham=5}
|> Map.add "self" { in_spam=0; in_ham=4}
|> Map.add "selling" { in_spam=0; in_ham=54}
|> Map.add "sells" { in_spam=0; in_ham=4}
|> Map.add "sendmail" { in_spam=0; in_ham=7}
|> Map.add "sept" { in_spam=0; in_ham=21}
|> Map.add "sequence" { in_spam=0; in_ham=12}
|> Map.add "sequences" { in_spam=0; in_ham=26}
|> Map.add "serial" { in_spam=0; in_ham=4}
|> Map.add "servants" { in_spam=0; in_ham=10}
|> Map.add "server" { in_spam=0; in_ham=3}
|> Map.add "service" { in_spam=0; in_ham=3}
|> Map.add "set" { in_spam=0; in_ham=7}
|> Map.add "sets" { in_spam=0; in_ham=30}
|> Map.add "sex" { in_spam=1; in_ham=2}
|> Map.add "sexual" { in_spam=0; in_ham=3}
|> Map.add "shader" { in_spam=0; in_ham=4}
|> Map.add "ship" { in_spam=0; in_ham=3}
|> Map.add "shot" { in_spam=0; in_ham=3}
|> Map.add "should" { in_spam=0; in_ham=5}
|> Map.add "shuttle" { in_spam=0; in_ham=3}
|> Map.add "sign" { in_spam=0; in_ham=3}
|> Map.add "signature" { in_spam=0; in_ham=9}
|> Map.add "signers" { in_spam=0; in_ham=4}
|> Map.add "silence" { in_spam=0; in_ham=20}
|> Map.add "site" { in_spam=2; in_ham=9}
|> Map.add "sky" { in_spam=1; in_ham=4}
|> Map.add "slaughter" { in_spam=0; in_ham=15}
|> Map.add "slow" { in_spam=0; in_ham=6}
|> Map.add "socialism" { in_spam=0; in_ham=9}
|> Map.add "software" { in_spam=7; in_ham=13}
|> Map.add "sofware" { in_spam=0; in_ham=14}
|> Map.add "solaris" { in_spam=0; in_ham=7}
|> Map.add "some" { in_spam=0; in_ham=9}
|> Map.add "something" { in_spam=1; in_ham=12}
|> Map.add "sort" { in_spam=0; in_ham=3}
|> Map.add "sorting" { in_spam=0; in_ham=23}
|> Map.add "source" { in_spam=1; in_ham=4}
|> Map.add "sourceforge" { in_spam=0; in_ham=5}
|> Map.add "south" { in_spam=0; in_ham=3}
|> Map.add "space" { in_spam=0; in_ham=3}
|> Map.add "spam" { in_spam=2; in_ham=46}
|> Map.add "spamassassin" { in_spam=0; in_ham=52}
|> Map.add "spambayes" { in_spam=0; in_ham=135}
|> Map.add "spamc" { in_spam=0; in_ham=4}
|> Map.add "spamd" { in_spam=0; in_ham=7}
|> Map.add "spec" { in_spam=0; in_ham=10}
|> Map.add "speech" { in_spam=0; in_ham=4}
|> Map.add "speed" { in_spam=1; in_ham=10}
|> Map.add "sprint" { in_spam=0; in_ham=4}
|> Map.add "src" { in_spam=0; in_ham=10}
|> Map.add "ssl" { in_spam=0; in_ham=4}
|> Map.add "stack" { in_spam=0; in_ham=3}
|> Map.add "start" { in_spam=1; in_ham=2}
|> Map.add "started" { in_spam=0; in_ham=3}
|> Map.add "states" { in_spam=0; in_ham=26}
|> Map.add "station" { in_spam=0; in_ham=11}
|> Map.add "status" { in_spam=3; in_ham=7}
|> Map.add "still" { in_spam=1; in_ham=11}
|> Map.add "stop" { in_spam=1; in_ham=4}
|> Map.add "storage" { in_spam=0; in_ham=7}
|> Map.add "stories" { in_spam=0; in_ham=29}
|> Map.add "strings" { in_spam=0; in_ham=3}
|> Map.add "strong" { in_spam=0; in_ham=3}
|> Map.add "stuff" { in_spam=1; in_ham=3}
|> Map.add "stupid" { in_spam=0; in_ham=7}
|> Map.add "subject" { in_spam=467; in_ham=2533}
|> Map.add "subsidizing" { in_spam=0; in_ham=4}
|> Map.add "suggestion" { in_spam=0; in_ham=4}
|> Map.add "sun" { in_spam=0; in_ham=10}
|> Map.add "support" { in_spam=3; in_ham=6}
|> Map.add "suse" { in_spam=0; in_ham=4}
|> Map.add "sussed" { in_spam=0; in_ham=5}
|> Map.add "swap" { in_spam=0; in_ham=3}
|> Map.add "switch" { in_spam=0; in_ham=3}
|> Map.add "symbol" { in_spam=0; in_ham=5}
|> Map.add "system" { in_spam=1; in_ham=17}
|> Map.add "systemworks" { in_spam=12; in_ham=0}
|> Map.add "tag" { in_spam=0; in_ham=3}
|> Map.add "take" { in_spam=3; in_ham=5}
|> Map.add "talks" { in_spam=0; in_ham=3}
|> Map.add "teach" { in_spam=2; in_ham=2}
|> Map.add "teeth" { in_spam=1; in_ham=2}
|> Map.add "tell" { in_spam=3; in_ham=3}
|> Map.add "test" { in_spam=0; in_ham=38}
|> Map.add "testing" { in_spam=1; in_ham=21}
|> Map.add "tests" { in_spam=0; in_ham=5}
|> Map.add "than" { in_spam=1; in_ham=2}
|> Map.add "that" { in_spam=0; in_ham=22}
|> Map.add "that's" { in_spam=0; in_ham=3}
|> Map.add "the" { in_spam=50; in_ham=350}
|> Map.add "their" { in_spam=0; in_ham=6}
|> Map.add "there" { in_spam=0; in_ham=10}
|> Map.add "they" { in_spam=0; in_ham=3}
|> Map.add "thing" { in_spam=0; in_ham=7}
|> Map.add "this" { in_spam=9; in_ham=21}
|> Map.add "thoughts" { in_spam=0; in_ham=3}
|> Map.add "through" { in_spam=0; in_ham=4}
|> Map.add "time" { in_spam=7; in_ham=7}
|> Map.add "times" { in_spam=0; in_ham=6}
|> Map.add "timtest" { in_spam=0; in_ham=3}
|> Map.add "tiny" { in_spam=0; in_ham=5}
|> Map.add "tip" { in_spam=0; in_ham=12}
|> Map.add "tmda-like" { in_spam=0; in_ham=6}
|> Map.add "today" { in_spam=3; in_ham=2}
|> Map.add "toddlers" { in_spam=0; in_ham=8}
|> Map.add "tonight" { in_spam=1; in_ham=3}
|> Map.add "tons" { in_spam=0; in_ham=3}
|> Map.add "too" { in_spam=3; in_ham=10}
|> Map.add "tough" { in_spam=0; in_ham=15}
|> Map.add "traceback" { in_spam=0; in_ham=19}
|> Map.add "tracking" { in_spam=0; in_ham=4}
|> Map.add "training" { in_spam=0; in_ham=8}
|> Map.add "tree" { in_spam=0; in_ham=3}
|> Map.add "trial" { in_spam=4; in_ham=3}
|> Map.add "tru" { in_spam=0; in_ham=3}
|> Map.add "trust" { in_spam=0; in_ham=3}
|> Map.add "trying" { in_spam=0; in_ham=5}
|> Map.add "tweak" { in_spam=0; in_ham=7}
|> Map.add "two" { in_spam=0; in_ham=6}
|> Map.add "ufos" { in_spam=0; in_ham=4}
|> Map.add "ultimate" { in_spam=0; in_ham=7}
|> Map.add "undeclared" { in_spam=0; in_ham=5}
|> Map.add "under" { in_spam=2; in_ham=3}
|> Map.add "uninstall" { in_spam=0; in_ham=4}
|> Map.add "united" { in_spam=0; in_ham=26}
|> Map.add "unlucky" { in_spam=0; in_ham=4}
|> Map.add "unpissup" { in_spam=0; in_ham=3}
|> Map.add "unseen" { in_spam=0; in_ham=3}
|> Map.add "untie" { in_spam=0; in_ham=8}
|> Map.add "update" { in_spam=0; in_ham=5}
|> Map.add "updates" { in_spam=0; in_ham=8}
|> Map.add "upgrade" { in_spam=0; in_ham=18}
|> Map.add "urgent" { in_spam=8; in_ham=1}
|> Map.add "usb" { in_spam=0; in_ham=5}
|> Map.add "use" { in_spam=2; in_ham=88}
|> Map.add "used" { in_spam=0; in_ham=4}
|> Map.add "user" { in_spam=1; in_ham=2}
|> Map.add "users" { in_spam=0; in_ham=18}
|> Map.add "uses" { in_spam=0; in_ham=3}
|> Map.add "using" { in_spam=0; in_ham=8}
|> Map.add "value" { in_spam=1; in_ham=3}
|> Map.add "version" { in_spam=1; in_ham=4}
|> Map.add "versus" { in_spam=0; in_ham=3}
|> Map.add "very" { in_spam=1; in_ham=4}
|> Map.add "via" { in_spam=0; in_ham=3}
|> Map.add "viagra" { in_spam=7; in_ham=0}
|> Map.add "video" { in_spam=1; in_ham=3}
|> Map.add "viewing" { in_spam=0; in_ham=14}
|> Map.add "viral" { in_spam=1; in_ham=2}
|> Map.add "virus" { in_spam=3; in_ham=4}
|> Map.add "viruses" { in_spam=2; in_ham=2}
|> Map.add "void" { in_spam=0; in_ham=11}
|> Map.add "vox" { in_spam=0; in_ham=3}
|> Map.add "wacky" { in_spam=0; in_ham=4}
|> Map.add "want" { in_spam=4; in_ham=1}
|> Map.add "wants" { in_spam=0; in_ham=4}
|> Map.add "war" { in_spam=0; in_ham=4}
|> Map.add "warming" { in_spam=0; in_ham=25}
|> Map.add "warning" { in_spam=1; in_ham=3}
|> Map.add "warranties" { in_spam=6; in_ham=0}
|> Map.add "was" { in_spam=1; in_ham=103}
|> Map.add "watch" { in_spam=2; in_ham=2}
|> Map.add "web" { in_spam=2; in_ham=11}
|> Map.add "webforms" { in_spam=0; in_ham=9}
|> Map.add "wed" { in_spam=0; in_ham=3}
|> Map.add "wedded" { in_spam=0; in_ham=54}
|> Map.add "wedding" { in_spam=0; in_ham=3}
|> Map.add "week" { in_spam=1; in_ham=4}
|> Map.add "weekly's" { in_spam=0; in_ham=7}
|> Map.add "weeks" { in_spam=3; in_ham=1}
|> Map.add "weren't" { in_spam=0; in_ham=4}
|> Map.add "west" { in_spam=0; in_ham=5}
|> Map.add "what" { in_spam=7; in_ham=4}
|> Map.add "when" { in_spam=0; in_ham=6}
|> Map.add "where" { in_spam=2; in_ham=6}
|> Map.add "which" { in_spam=0; in_ham=5}
|> Map.add "while" { in_spam=2; in_ham=2}
|> Map.add "whitelist" { in_spam=0; in_ham=4}
|> Map.add "who" { in_spam=0; in_ham=5}
|> Map.add "whoa" { in_spam=0; in_ham=11}
|> Map.add "why" { in_spam=2; in_ham=25}
|> Map.add "wifi" { in_spam=0; in_ham=9}
|> Map.add "will" { in_spam=9; in_ham=5}
|> Map.add "win" { in_spam=2; in_ham=7}
|> Map.add "window" { in_spam=0; in_ham=31}
|> Map.add "windows" { in_spam=0; in_ham=4}
|> Map.add "wins" { in_spam=0; in_ham=4}
|> Map.add "wireless" { in_spam=0; in_ham=6}
|> Map.add "with" { in_spam=17; in_ham=113}
|> Map.add "women" { in_spam=0; in_ham=13}
|> Map.add "word" { in_spam=0; in_ham=6}
|> Map.add "wordinfo" { in_spam=0; in_ham=7}
|> Map.add "work" { in_spam=6; in_ham=7}
|> Map.add "working" { in_spam=3; in_ham=22}
|> Map.add "world" { in_spam=1; in_ham=10}
|> Map.add "world's" { in_spam=0; in_ham=3}
|> Map.add "write" { in_spam=1; in_ham=5}
|> Map.add "wrold" { in_spam=0; in_ham=8}
|> Map.add "wrong" { in_spam=0; in_ham=7}
|> Map.add "www" { in_spam=2; in_ham=2}
|> Map.add "xdegress" { in_spam=0; in_ham=3}
|> Map.add "xine" { in_spam=0; in_ham=12}
|> Map.add "xmms" { in_spam=0; in_ham=3}
|> Map.add "xtreme" { in_spam=0; in_ham=3}
|> Map.add "yahoo" { in_spam=0; in_ham=12}
|> Map.add "year" { in_spam=11; in_ham=2}
|> Map.add "years" { in_spam=3; in_ham=4}
|> Map.add "yesterday" { in_spam=0; in_ham=3}
|> Map.add "you" { in_spam=44; in_ham=23}
|> Map.add "young" { in_spam=0; in_ham=4}
|> Map.add "your" { in_spam=68; in_ham=14}
|> Map.add "yourself" { in_spam=1; in_ham=4}
|> Map.add "zoot" { in_spam=0; in_ham=3}
|> Map.add "zzzz" { in_spam=13; in_ham=0}
|> Map.add "zzzzteana" { in_spam=0; in_ham=87}

