open Bayesian.Database
open BayesianBody_011
let db = db 
|> Map.add "trillion" { in_spam=3; in_ham=3}
|> Map.add "trim" { in_spam=12; in_ham=3}
|> Map.add "trinidad" { in_spam=3; in_ham=1}
|> Map.add "trip" { in_spam=8; in_ham=12}
|> Map.add "triplicate" { in_spam=0; in_ham=3}
|> Map.add "trips" { in_spam=1; in_ham=6}
|> Map.add "triumphs" { in_spam=0; in_ham=3}
|> Map.add "trivia" { in_spam=0; in_ham=3}
|> Map.add "trivial" { in_spam=0; in_ham=24}
|> Map.add "trojan" { in_spam=0; in_ham=7}
|> Map.add "trollbox" { in_spam=0; in_ham=3}
|> Map.add "troops" { in_spam=1; in_ham=4}
|> Map.add "trouble" { in_spam=3; in_ham=48}
|> Map.add "troubles" { in_spam=9; in_ham=4}
|> Map.add "troublesome" { in_spam=0; in_ham=5}
|> Map.add "troy" { in_spam=0; in_ham=8}
|> Map.add "tru" { in_spam=1; in_ham=2}
|> Map.add "truck" { in_spam=7; in_ham=8}
|> Map.add "trucks" { in_spam=0; in_ham=7}
|> Map.add "true" { in_spam=45; in_ham=115}
|> Map.add "truly" { in_spam=5; in_ham=24}
|> Map.add "trumpet" { in_spam=0; in_ham=3}
|> Map.add "truncated" { in_spam=0; in_ham=3}
|> Map.add "trunk" { in_spam=2; in_ham=2}
|> Map.add "trust" { in_spam=25; in_ham=29}
|> Map.add "trusted" { in_spam=4; in_ham=19}
|> Map.add "trustworthy" { in_spam=4; in_ham=3}
|> Map.add "truth" { in_spam=9; in_ham=31}
|> Map.add "try" { in_spam=37; in_ham=226}
|> Map.add "trying" { in_spam=12; in_ham=164}
|> Map.add "tty" { in_spam=0; in_ham=4}
|> Map.add "tue" { in_spam=1; in_ham=96}
|> Map.add "tuesday" { in_spam=3; in_ham=70}
|> Map.add "tufte" { in_spam=0; in_ham=3}
|> Map.add "tuition" { in_spam=5; in_ham=4}
|> Map.add "tulsa" { in_spam=0; in_ham=3}
|> Map.add "tune" { in_spam=1; in_ham=4}
|> Map.add "tuned" { in_spam=0; in_ham=3}
|> Map.add "tuner" { in_spam=0; in_ham=5}
|> Map.add "tuning" { in_spam=0; in_ham=10}
|> Map.add "tunnu" { in_spam=0; in_ham=4}
|> Map.add "tuo" { in_spam=0; in_ham=4}
|> Map.add "turf" { in_spam=0; in_ham=3}
|> Map.add "turing" { in_spam=0; in_ham=6}
|> Map.add "turkey" { in_spam=2; in_ham=5}
|> Map.add "turn" { in_spam=23; in_ham=57}
|> Map.add "turned" { in_spam=2; in_ham=51}
|> Map.add "turning" { in_spam=0; in_ham=17}
|> Map.add "turns" { in_spam=9; in_ham=32}
|> Map.add "turpin" { in_spam=0; in_ham=24}
|> Map.add "tutorial" { in_spam=3; in_ham=2}
|> Map.add "tutoring" { in_spam=3; in_ham=2}
|> Map.add "tuxfamily" { in_spam=0; in_ham=5}
|> Map.add "twain" { in_spam=0; in_ham=3}
|> Map.add "tweak" { in_spam=0; in_ham=6}
|> Map.add "tweaked" { in_spam=1; in_ham=4}
|> Map.add "tweaking" { in_spam=0; in_ham=11}
|> Map.add "twelve" { in_spam=3; in_ham=4}
|> Map.add "twenties" { in_spam=2; in_ham=5}
|> Map.add "twentieth" { in_spam=0; in_ham=4}
|> Map.add "twenty" { in_spam=8; in_ham=9}
|> Map.add "twenty-first" { in_spam=0; in_ham=4}
|> Map.add "twenty-five" { in_spam=3; in_ham=3}
|> Map.add "twice" { in_spam=1; in_ham=21}
|> Map.add "twin" { in_spam=0; in_ham=5}
|> Map.add "twm" { in_spam=1; in_ham=3}
|> Map.add "two" { in_spam=43; in_ham=255}
|> Map.add "two-gram" { in_spam=0; in_ham=3}
|> Map.add "two-way" { in_spam=0; in_ham=5}
|> Map.add "txt" { in_spam=2; in_ham=19}
|> Map.add "tyler" { in_spam=0; in_ham=8}
|> Map.add "type" { in_spam=85; in_ham=107}
|> Map.add "typed" { in_spam=0; in_ham=9}
|> Map.add "typedef" { in_spam=0; in_ham=5}
|> Map.add "types" { in_spam=7; in_ham=28}
|> Map.add "typical" { in_spam=3; in_ham=27}
|> Map.add "typically" { in_spam=1; in_ham=14}
|> Map.add "typing" { in_spam=2; in_ham=14}
|> Map.add "typo" { in_spam=0; in_ham=7}
|> Map.add "typos" { in_spam=0; in_ham=3}
|> Map.add "tyrants" { in_spam=0; in_ham=3}
|> Map.add "tyrrell" { in_spam=0; in_ham=6}
|> Map.add "u-high" { in_spam=0; in_ham=6}
|> Map.add "uah" { in_spam=0; in_ham=4}
|> Map.add "ubiquitous" { in_spam=0; in_ham=7}
|> Map.add "ubiquity" { in_spam=0; in_ham=4}
|> Map.add "ucd" { in_spam=1; in_ham=3}
|> Map.add "uci" { in_spam=0; in_ham=3}
|> Map.add "ucsc" { in_spam=0; in_ham=8}
|> Map.add "udhay" { in_spam=0; in_ham=6}
|> Map.add "uefas" { in_spam=5; in_ham=0}
|> Map.add "ugh" { in_spam=0; in_ham=5}
|> Map.add "ugly" { in_spam=3; in_ham=24}
|> Map.add "uid" { in_spam=2; in_ham=3}
|> Map.add "ukraine" { in_spam=2; in_ham=2}
|> Map.add "ulises" { in_spam=0; in_ham=9}
|> Map.add "ultimate" { in_spam=9; in_ham=8}
|> Map.add "ultimately" { in_spam=1; in_ham=17}
|> Map.add "ultra" { in_spam=0; in_ham=3}
|> Map.add "umbrella" { in_spam=1; in_ham=2}
|> Map.add "umm" { in_spam=0; in_ham=4}
|> Map.add "un's" { in_spam=0; in_ham=3}
|> Map.add "unable" { in_spam=1; in_ham=30}
|> Map.add "unacceptable" { in_spam=1; in_ham=4}
|> Map.add "uname" { in_spam=0; in_ham=7}
|> Map.add "unanswered" { in_spam=1; in_ham=2}
|> Map.add "unauthorized" { in_spam=0; in_ham=6}
|> Map.add "unavailable" { in_spam=0; in_ham=5}
|> Map.add "unaware" { in_spam=1; in_ham=4}
|> Map.add "unbeatable" { in_spam=6; in_ham=0}
|> Map.add "unbelievable" { in_spam=8; in_ham=2}
|> Map.add "unbiased" { in_spam=0; in_ham=3}
|> Map.add "unblessed" { in_spam=0; in_ham=14}
|> Map.add "unbreakable" { in_spam=0; in_ham=5}
|> Map.add "uncertain" { in_spam=0; in_ham=4}
|> Map.add "uncertainty" { in_spam=0; in_ham=4}
|> Map.add "uncivilized" { in_spam=0; in_ham=4}
|> Map.add "unclaimed" { in_spam=6; in_ham=1}
|> Map.add "unclassified" { in_spam=0; in_ham=4}
|> Map.add "uncle" { in_spam=0; in_ham=6}
|> Map.add "uncovered" { in_spam=0; in_ham=3}
|> Map.add "undeclared" { in_spam=0; in_ham=3}
|> Map.add "undefined" { in_spam=0; in_ham=7}
|> Map.add "under" { in_spam=32; in_ham=149}
|> Map.add "undergoing" { in_spam=0; in_ham=4}
|> Map.add "undergrad" { in_spam=0; in_ham=3}
|> Map.add "underground" { in_spam=2; in_ham=7}
|> Map.add "underline" { in_spam=10; in_ham=3}
|> Map.add "underlying" { in_spam=0; in_ham=4}
|> Map.add "underneath" { in_spam=0; in_ham=4}
|> Map.add "underpin" { in_spam=0; in_ham=3}
|> Map.add "underrated" { in_spam=0; in_ham=3}
|> Map.add "underscore" { in_spam=0; in_ham=3}
|> Map.add "understand" { in_spam=26; in_ham=85}
|> Map.add "understands" { in_spam=4; in_ham=8}
|> Map.add "understood" { in_spam=2; in_ham=18}
|> Map.add "undertaken" { in_spam=1; in_ham=2}
|> Map.add "underwriting" { in_spam=6; in_ham=41}
|> Map.add "undesirable" { in_spam=0; in_ham=3}
|> Map.add "undisclosed" { in_spam=1; in_ham=4}
|> Map.add "undo" { in_spam=0; in_ham=6}
|> Map.add "undoubtedly" { in_spam=3; in_ham=4}
|> Map.add "une" { in_spam=4; in_ham=2}
|> Map.add "unecessarily" { in_spam=0; in_ham=4}
|> Map.add "unemployed" { in_spam=4; in_ham=3}
|> Map.add "unemployment" { in_spam=0; in_ham=3}
|> Map.add "unencrypted" { in_spam=0; in_ham=3}
|> Map.add "unethical" { in_spam=1; in_ham=2}
|> Map.add "uneven" { in_spam=0; in_ham=3}
|> Map.add "unexpected" { in_spam=2; in_ham=5}
|> Map.add "unfailingly" { in_spam=0; in_ham=5}
|> Map.add "unfair" { in_spam=4; in_ham=5}
|> Map.add "unfairly" { in_spam=0; in_ham=4}
|> Map.add "unfettered" { in_spam=0; in_ham=5}
|> Map.add "unfortunate" { in_spam=0; in_ham=5}
|> Map.add "unfounded" { in_spam=0; in_ham=3}
|> Map.add "unhappy" { in_spam=5; in_ham=1}
|> Map.add "unheader" { in_spam=0; in_ham=5}
|> Map.add "unicode" { in_spam=6; in_ham=0}
|> Map.add "unified" { in_spam=0; in_ham=3}
|> Map.add "unify" { in_spam=0; in_ham=3}
|> Map.add "unilateral" { in_spam=1; in_ham=4}
|> Map.add "uninstall" { in_spam=0; in_ham=6}
|> Map.add "unintened" { in_spam=0; in_ham=3}
|> Map.add "union" { in_spam=2; in_ham=11}
|> Map.add "unions" { in_spam=0; in_ham=3}
|> Map.add "unique" { in_spam=10; in_ham=36}
|> Map.add "unisphere" { in_spam=0; in_ham=6}
|> Map.add "unit" { in_spam=4; in_ham=20}
|> Map.add "united" { in_spam=44; in_ham=53}
|> Map.add "units" { in_spam=1; in_ham=6}
|> Map.add "universal" { in_spam=4; in_ham=10}
|> Map.add "universe" { in_spam=1; in_ham=17}
|> Map.add "universities" { in_spam=0; in_ham=7}
|> Map.add "university" { in_spam=4; in_ham=54}
|> Map.add "unix" { in_spam=0; in_ham=41}
|> Map.add "unixes" { in_spam=0; in_ham=3}
|> Map.add "unknown" { in_spam=5; in_ham=26}
|> Map.add "unlawful" { in_spam=0; in_ham=3}
|> Map.add "unleash" { in_spam=1; in_ham=2}
|> Map.add "unleashed" { in_spam=0; in_ham=4}
|> Map.add "unless" { in_spam=7; in_ham=77}
|> Map.add "unlike" { in_spam=6; in_ham=26}
|> Map.add "unlikely" { in_spam=0; in_ham=10}
|> Map.add "unlimited" { in_spam=5; in_ham=2}
|> Map.add "unlocked" { in_spam=1; in_ham=2}
|> Map.add "unmet" { in_spam=0; in_ham=3}
|> Map.add "unmodified" { in_spam=0; in_ham=4}
|> Map.add "unnecessary" { in_spam=6; in_ham=4}
|> Map.add "unnoticed" { in_spam=0; in_ham=3}
|> Map.add "unpackaged" { in_spam=0; in_ham=4}
|> Map.add "unpacking" { in_spam=0; in_ham=4}
|> Map.add "unparalleled" { in_spam=0; in_ham=10}
|> Map.add "unpeaceably" { in_spam=0; in_ham=7}
|> Map.add "unread" { in_spam=0; in_ham=11}
|> Map.add "unrealistic" { in_spam=0; in_ham=4}
|> Map.add "unrelated" { in_spam=0; in_ham=12}
|> Map.add "unresponsive" { in_spam=0; in_ham=8}
|> Map.add "unruly" { in_spam=0; in_ham=3}
|> Map.add "unseen" { in_spam=0; in_ham=41}
|> Map.add "unseenwin" { in_spam=0; in_ham=4}
|> Map.add "unset" { in_spam=0; in_ham=3}
|> Map.add "unsigned" { in_spam=0; in_ham=6}
|> Map.add "unsolicited" { in_spam=33; in_ham=12}
|> Map.add "unsorted" { in_spam=0; in_ham=3}
|> Map.add "unspecified" { in_spam=0; in_ham=5}
|> Map.add "unstable" { in_spam=3; in_ham=8}
|> Map.add "unstall" { in_spam=0; in_ham=4}
|> Map.add "unsub" { in_spam=8; in_ham=0}
|> Map.add "unsubscribe" { in_spam=87; in_ham=101}
|> Map.add "unsubscribed" { in_spam=31; in_ham=2}
|> Map.add "unsuccessful" { in_spam=1; in_ham=4}
|> Map.add "unsuitable" { in_spam=0; in_ham=5}
|> Map.add "unsupported" { in_spam=0; in_ham=7}
|> Map.add "unsure" { in_spam=1; in_ham=3}
|> Map.add "untested" { in_spam=0; in_ham=6}
|> Map.add "unthinkable" { in_spam=2; in_ham=2}
|> Map.add "until" { in_spam=19; in_ham=119}
|> Map.add "untitled" { in_spam=11; in_ham=0}
|> Map.add "untypical" { in_spam=0; in_ham=3}
|> Map.add "unusual" { in_spam=1; in_ham=23}
|> Map.add "unusually" { in_spam=4; in_ham=2}
|> Map.add "unveiled" { in_spam=0; in_ham=11}
|> Map.add "unwanted" { in_spam=21; in_ham=1}
|> Map.add "unwilling" { in_spam=1; in_ham=2}
|> Map.add "up'ed" { in_spam=0; in_ham=5}
|> Map.add "upcoming" { in_spam=1; in_ham=5}
|> Map.add "update" { in_spam=2; in_ham=83}
|> Map.add "updated" { in_spam=6; in_ham=40}
|> Map.add "updates" { in_spam=8; in_ham=26}
|> Map.add "updating" { in_spam=0; in_ham=16}
|> Map.add "upgrade" { in_spam=2; in_ham=45}
|> Map.add "upgraded" { in_spam=0; in_ham=23}
|> Map.add "upgrades" { in_spam=1; in_ham=9}
|> Map.add "upgrading" { in_spam=0; in_ham=17}
|> Map.add "uplevel" { in_spam=0; in_ham=4}
|> Map.add "upload" { in_spam=0; in_ham=3}
|> Map.add "uploaded" { in_spam=0; in_ham=5}
|> Map.add "upon" { in_spam=19; in_ham=119}
|> Map.add "upper" { in_spam=1; in_ham=5}
|> Map.add "upset" { in_spam=0; in_ham=6}
|> Map.add "upside" { in_spam=1; in_ham=3}
|> Map.add "upstarts" { in_spam=0; in_ham=3}
|> Map.add "upstream" { in_spam=0; in_ham=8}
|> Map.add "upwards" { in_spam=0; in_ham=3}
|> Map.add "urban" { in_spam=1; in_ham=12}
|> Map.add "urge" { in_spam=1; in_ham=5}
|> Map.add "urged" { in_spam=1; in_ham=2}
|> Map.add "urgent" { in_spam=14; in_ham=12}
|> Map.add "urgently" { in_spam=3; in_ham=1}
|> Map.add "url" { in_spam=21; in_ham=672}
|> Map.add "urls" { in_spam=0; in_ham=9}
|> Map.add "us-ascii" { in_spam=0; in_ham=10}
|> Map.add "usa" { in_spam=18; in_ham=56}
|> Map.add "usability" { in_spam=0; in_ham=11}
|> Map.add "usable" { in_spam=0; in_ham=6}
|> Map.add "usaf" { in_spam=1; in_ham=2}
|> Map.add "usage" { in_spam=3; in_ham=17}
|> Map.add "usb" { in_spam=1; in_ham=11}
|> Map.add "usd" { in_spam=10; in_ham=2}
|> Map.add "use" { in_spam=88; in_ham=601}
|> Map.add "used" { in_spam=36; in_ham=274}
|> Map.add "useful" { in_spam=3; in_ham=72}
|> Map.add "useful'" { in_spam=0; in_ham=3}
|> Map.add "usefulness" { in_spam=0; in_ham=39}
|> Map.add "useless" { in_spam=0; in_ham=61}
|> Map.add "usemap" { in_spam=4; in_ham=1}
|> Map.add "usenet" { in_spam=0; in_ham=8}
|> Map.add "user" { in_spam=28; in_ham=178}
|> Map.add "user's" { in_spam=0; in_ham=15}
|> Map.add "user-agent" { in_spam=0; in_ham=7}
|> Map.add "userid" { in_spam=9; in_ham=2}
|> Map.add "userland" { in_spam=0; in_ham=60}
|> Map.add "username" { in_spam=0; in_ham=7}
|> Map.add "users" { in_spam=22; in_ham=96}
|> Map.add "users'" { in_spam=46; in_ham=92}
|> Map.add "uses" { in_spam=5; in_ham=57}
|> Map.add "usinf" { in_spam=0; in_ham=3}
|> Map.add "using" { in_spam=49; in_ham=367}
|> Map.add "uspto" { in_spam=0; in_ham=4}
|> Map.add "usr" { in_spam=0; in_ham=98}
|> Map.add "usual" { in_spam=0; in_ham=34}
|> Map.add "usually" { in_spam=5; in_ham=65}
|> Map.add "usw-pr-cvs" { in_spam=0; in_ham=16}
|> Map.add "utf-" { in_spam=0; in_ham=5}
|> Map.add "utilisation" { in_spam=2; in_ham=2}
|> Map.add "utilities" { in_spam=22; in_ham=5}
|> Map.add "utility" { in_spam=3; in_ham=10}
|> Map.add "utilize" { in_spam=1; in_ham=5}
|> Map.add "utilized" { in_spam=5; in_ham=1}
|> Map.add "utilizing" { in_spam=4; in_ham=1}
|> Map.add "utils" { in_spam=0; in_ham=6}
|> Map.add "utmost" { in_spam=8; in_ham=1}
|> Map.add "utopia" { in_spam=0; in_ham=3}
|> Map.add "utter" { in_spam=2; in_ham=8}
|> Map.add "utterances" { in_spam=0; in_ham=4}
|> Map.add "utterly" { in_spam=2; in_ham=7}
|> Map.add "uuencode" { in_spam=0; in_ham=3}
|> Map.add "uvh" { in_spam=0; in_ham=5}
|> Map.add "uwo" { in_spam=1; in_ham=2}
|> Map.add "vaan" { in_spam=0; in_ham=4}
|> Map.add "vacant" { in_spam=0; in_ham=3}
|> Map.add "vacation" { in_spam=5; in_ham=10}
|> Map.add "vague" { in_spam=0; in_ham=5}
|> Map.add "valdis" { in_spam=0; in_ham=5}
|> Map.add "valenti" { in_spam=0; in_ham=3}
|> Map.add "valhalla" { in_spam=0; in_ham=49}
|> Map.add "valid" { in_spam=20; in_ham=22}
|> Map.add "validate" { in_spam=1; in_ham=5}
|> Map.add "validated" { in_spam=1; in_ham=3}
|> Map.add "validation" { in_spam=3; in_ham=4}
|> Map.add "validator" { in_spam=2; in_ham=2}
|> Map.add "validity" { in_spam=2; in_ham=2}
|> Map.add "valign" { in_spam=92; in_ham=3}
|> Map.add "valley" { in_spam=2; in_ham=6}
|> Map.add "valuable" { in_spam=34; in_ham=13}
|> Map.add "valuation" { in_spam=3; in_ham=2}
|> Map.add "value" { in_spam=87; in_ham=57}
|> Map.add "value'" { in_spam=0; in_ham=3}
|> Map.add "values" { in_spam=4; in_ham=20}
|> Map.add "vampire" { in_spam=0; in_ham=3}
|> Map.add "van" { in_spam=0; in_ham=41}
|> Map.add "vancouver" { in_spam=0; in_ham=3}
|> Map.add "vandenburg" { in_spam=0; in_ham=4}
|> Map.add "vander" { in_spam=0; in_ham=6}
|> Map.add "vanilla" { in_spam=0; in_ham=9}
|> Map.add "vapor" { in_spam=0; in_ham=3}
|> Map.add "var" { in_spam=6; in_ham=25}
|> Map.add "variability" { in_spam=0; in_ham=4}
|> Map.add "variable" { in_spam=1; in_ham=21}
|> Map.add "variables" { in_spam=0; in_ham=6}
|> Map.add "variant" { in_spam=0; in_ham=5}
|> Map.add "variation" { in_spam=0; in_ham=3}
|> Map.add "variations" { in_spam=0; in_ham=6}
|> Map.add "varies" { in_spam=1; in_ham=6}
|> Map.add "variety" { in_spam=6; in_ham=24}
|> Map.add "various" { in_spam=5; in_ham=81}
|> Map.add "varsinainen" { in_spam=0; in_ham=4}
|> Map.add "vary" { in_spam=1; in_ham=11}
|> Map.add "vast" { in_spam=13; in_ham=29}
|> Map.add "vastly" { in_spam=0; in_ham=5}
|> Map.add "vastness" { in_spam=0; in_ham=3}
|> Map.add "vat" { in_spam=1; in_ham=2}
|> Map.add "vaults" { in_spam=5; in_ham=0}
|> Map.add "vcr" { in_spam=2; in_ham=2}
|> Map.add "ved" { in_spam=0; in_ham=8}
|> Map.add "veder" { in_spam=0; in_ham=6}
|> Map.add "vegetation" { in_spam=0; in_ham=3}
|> Map.add "vehicle" { in_spam=3; in_ham=10}
|> Map.add "vehicles" { in_spam=6; in_ham=5}
|> Map.add "veiled" { in_spam=0; in_ham=4}
|> Map.add "velocity" { in_spam=1; in_ham=5}
|> Map.add "vendor" { in_spam=0; in_ham=24}
|> Map.add "vendors" { in_spam=0; in_ham=12}
|> Map.add "venerated" { in_spam=0; in_ham=6}
|> Map.add "venrock" { in_spam=0; in_ham=6}
|> Map.add "venrock's" { in_spam=0; in_ham=6}
|> Map.add "vent" { in_spam=0; in_ham=5}
|> Map.add "venture" { in_spam=15; in_ham=10}
|> Map.add "ventures" { in_spam=0; in_ham=4}
|> Map.add "venue" { in_spam=1; in_ham=6}
|> Map.add "venues" { in_spam=0; in_ham=5}
|> Map.add "ver" { in_spam=4; in_ham=3}
|> Map.add "verbose" { in_spam=0; in_ham=5}
|> Map.add "verdana" { in_spam=91; in_ham=3}
|> Map.add "verifiable" { in_spam=3; in_ham=1}
|> Map.add "verification" { in_spam=5; in_ham=2}
|> Map.add "verified" { in_spam=6; in_ham=5}
|> Map.add "verify" { in_spam=8; in_ham=15}
|> Map.add "verizon" { in_spam=0; in_ham=5}
|> Map.add "vermont" { in_spam=3; in_ham=1}
|> Map.add "vernacular" { in_spam=1; in_ham=4}
|> Map.add "vernon" { in_spam=0; in_ham=6}
|> Map.add "versa" { in_spam=0; in_ham=4}
|> Map.add "version" { in_spam=15; in_ham=240}
|> Map.add "versions" { in_spam=1; in_ham=45}
|> Map.add "versus" { in_spam=1; in_ham=14}
|> Map.add "vertical" { in_spam=3; in_ham=7}
|> Map.add "very" { in_spam=63; in_ham=293}
|> Map.add "vessels" { in_spam=0; in_ham=7}
|> Map.add "veteran" { in_spam=0; in_ham=10}
|> Map.add "vhp" { in_spam=0; in_ham=3}
|> Map.add "vhs" { in_spam=1; in_ham=2}
|> Map.add "via" { in_spam=32; in_ham=100}
|> Map.add "viable" { in_spam=1; in_ham=7}
|> Map.add "viagra" { in_spam=7; in_ham=0}
|> Map.add "vic" { in_spam=4; in_ham=1}
|> Map.add "vice" { in_spam=0; in_ham=16}
|> Map.add "victim" { in_spam=1; in_ham=5}
|> Map.add "victims" { in_spam=0; in_ham=6}
|> Map.add "victims'" { in_spam=0; in_ham=4}
|> Map.add "victoria" { in_spam=2; in_ham=4}
|> Map.add "victors" { in_spam=0; in_ham=3}
|> Map.add "victory" { in_spam=0; in_ham=7}
|> Map.add "video" { in_spam=12; in_ham=24}
|> Map.add "videos" { in_spam=7; in_ham=7}
|> Map.add "vietnam" { in_spam=2; in_ham=3}
|> Map.add "view" { in_spam=18; in_ham=49}
|> Map.add "viewed" { in_spam=2; in_ham=9}
|> Map.add "viewer" { in_spam=0; in_ham=6}
|> Map.add "viewing" { in_spam=4; in_ham=9}
|> Map.add "viewitem" { in_spam=0; in_ham=4}
|> Map.add "viewpoint" { in_spam=0; in_ham=9}
|> Map.add "views" { in_spam=1; in_ham=16}
|> Map.add "vigorous" { in_spam=0; in_ham=5}
|> Map.add "viii" { in_spam=0; in_ham=3}
|> Map.add "village" { in_spam=2; in_ham=9}
|> Map.add "villagers" { in_spam=0; in_ham=3}
|> Map.add "villages" { in_spam=0; in_ham=4}
|> Map.add "ville" { in_spam=2; in_ham=24}
|> Map.add "vim" { in_spam=0; in_ham=4}
|> Map.add "vin" { in_spam=0; in_ham=3}
|> Map.add "vincent" { in_spam=2; in_ham=7}
|> Map.add "violate" { in_spam=0; in_ham=9}
|> Map.add "violation" { in_spam=1; in_ham=6}
|> Map.add "violations" { in_spam=1; in_ham=3}
|> Map.add "violators" { in_spam=0; in_ham=7}
|> Map.add "violence" { in_spam=1; in_ham=19}
|> Map.add "violent" { in_spam=1; in_ham=12}
|> Map.add "vipul" { in_spam=0; in_ham=9}
|> Map.add "vircio" { in_spam=0; in_ham=47}
|> Map.add "virden" { in_spam=0; in_ham=3}
|> Map.add "virgin" { in_spam=3; in_ham=7}
|> Map.add "virginia" { in_spam=7; in_ham=10}
|> Map.add "viridiana" { in_spam=0; in_ham=5}
|> Map.add "virii" { in_spam=0; in_ham=3}
|> Map.add "virtual" { in_spam=3; in_ham=20}
|> Map.add "virtually" { in_spam=8; in_ham=12}
|> Map.add "virtue" { in_spam=5; in_ham=1}
|> Map.add "virus" { in_spam=1; in_ham=22}
|> Map.add "viruses" { in_spam=15; in_ham=17}
|> Map.add "visa" { in_spam=8; in_ham=3}
|> Map.add "visibility" { in_spam=3; in_ham=4}
|> Map.add "visible" { in_spam=1; in_ham=18}
|> Map.add "vision" { in_spam=2; in_ham=14}
|> Map.add "visionary" { in_spam=2; in_ham=7}
|> Map.add "visions" { in_spam=0; in_ham=8}
|> Map.add "visit" { in_spam=72; in_ham=26}
|> Map.add "visited" { in_spam=13; in_ham=6}
|> Map.add "visiting" { in_spam=2; in_ham=16}
|> Map.add "visitors" { in_spam=5; in_ham=3}
|> Map.add "visual" { in_spam=4; in_ham=8}
|> Map.add "visualstudio" { in_spam=0; in_ham=4}
|> Map.add "vital" { in_spam=0; in_ham=7}
|> Map.add "vivid" { in_spam=0; in_ham=6}
|> Map.add "vladimir" { in_spam=0; in_ham=3}
|> Map.add "vlink" { in_spam=26; in_ham=0}
|> Map.add "vm's" { in_spam=0; in_ham=6}
|> Map.add "vms" { in_spam=0; in_ham=3}
|> Map.add "vmware" { in_spam=0; in_ham=7}
|> Map.add "vnc" { in_spam=1; in_ham=5}
|> Map.add "vncviewer" { in_spam=0; in_ham=3}
|> Map.add "vocal" { in_spam=0; in_ham=3}
|> Map.add "voice" { in_spam=3; in_ham=30}
|> Map.add "voices" { in_spam=0; in_ham=15}
|> Map.add "void" { in_spam=7; in_ham=2}
|> Map.add "voidstar" { in_spam=0; in_ham=4}
|> Map.add "voila" { in_spam=0; in_ham=3}
|> Map.add "voip" { in_spam=1; in_ham=2}
|> Map.add "vol" { in_spam=1; in_ham=2}
|> Map.add "volatile" { in_spam=0; in_ham=4}
|> Map.add "voltage" { in_spam=0; in_ham=3}
|> Map.add "volume" { in_spam=5; in_ham=19}
|> Map.add "voluntary" { in_spam=1; in_ham=4}
|> Map.add "vos" { in_spam=4; in_ham=2}
|> Map.add "vote" { in_spam=1; in_ham=19}
|> Map.add "voter" { in_spam=0; in_ham=3}
|> Map.add "voters" { in_spam=0; in_ham=8}
|> Map.add "votes" { in_spam=2; in_ham=5}
|> Map.add "voting" { in_spam=0; in_ham=4}
|> Map.add "votre" { in_spam=2; in_ham=2}
|> Map.add "vous" { in_spam=3; in_ham=6}
|> Map.add "voyage" { in_spam=0; in_ham=8}
|> Map.add "vsnl" { in_spam=1; in_ham=2}
|> Map.add "vspace" { in_spam=19; in_ham=1}
|> Map.add "vulnerable" { in_spam=0; in_ham=11}
|> Map.add "waay" { in_spam=0; in_ham=4}
|> Map.add "wacky" { in_spam=0; in_ham=4}
|> Map.add "wage" { in_spam=1; in_ham=5}
|> Map.add "waged" { in_spam=0; in_ham=4}
|> Map.add "wages" { in_spam=0; in_ham=5}
|> Map.add "waider" { in_spam=0; in_ham=9}
|> Map.add "wait" { in_spam=24; in_ham=54}
|> Map.add "waited" { in_spam=1; in_ham=4}
|> Map.add "waiting" { in_spam=25; in_ham=40}
|> Map.add "wake" { in_spam=1; in_ham=8}
|> Map.add "walaa" { in_spam=6; in_ham=0}
|> Map.add "wales" { in_spam=1; in_ham=4}
|> Map.add "walk" { in_spam=7; in_ham=25}
|> Map.add "walked" { in_spam=3; in_ham=4}
|> Map.add "walking" { in_spam=0; in_ham=11}
|> Map.add "walks" { in_spam=5; in_ham=4}
|> Map.add "wall" { in_spam=7; in_ham=21}
|> Map.add "wallet" { in_spam=2; in_ham=6}
|> Map.add "walls" { in_spam=0; in_ham=6}
|> Map.add "wan" { in_spam=0; in_ham=9}
|> Map.add "wan's" { in_spam=0; in_ham=3}
|> Map.add "wander" { in_spam=0; in_ham=7}
|> Map.add "wandering" { in_spam=0; in_ham=4}
|> Map.add "wang" { in_spam=0; in_ham=6}
|> Map.add "wanna" { in_spam=2; in_ham=2}
|> Map.add "want" { in_spam=114; in_ham=307}
|> Map.add "wanted" { in_spam=17; in_ham=68}
|> Map.add "wanting" { in_spam=6; in_ham=9}
|> Map.add "wanton" { in_spam=0; in_ham=3}
|> Map.add "wants" { in_spam=6; in_ham=67}
|> Map.add "war" { in_spam=9; in_ham=88}
|> Map.add "warchalking" { in_spam=0; in_ham=7}
|> Map.add "ward" { in_spam=0; in_ham=16}
|> Map.add "warehouse" { in_spam=7; in_ham=1}
|> Map.add "warfare" { in_spam=0; in_ham=4}
|> Map.add "warm" { in_spam=1; in_ham=7}
|> Map.add "warmer" { in_spam=0; in_ham=3}
|> Map.add "warming" { in_spam=0; in_ham=19}
|> Map.add "warmth" { in_spam=0; in_ham=3}
|> Map.add "warn" { in_spam=0; in_ham=5}
|> Map.add "warned" { in_spam=1; in_ham=12}
|> Map.add "warner" { in_spam=1; in_ham=3}
|> Map.add "warning" { in_spam=4; in_ham=27}
|> Map.add "warnings" { in_spam=1; in_ham=11}
|> Map.add "warns" { in_spam=0; in_ham=6}
|> Map.add "warrant" { in_spam=3; in_ham=9}
|> Map.add "warranty" { in_spam=7; in_ham=2}
|> Map.add "warren" { in_spam=1; in_ham=2}
|> Map.add "wars" { in_spam=1; in_ham=10}
|> Map.add "warthog" { in_spam=0; in_ham=4}
|> Map.add "was" { in_spam=100; in_ham=736}
|> Map.add "wash" { in_spam=1; in_ham=4}
|> Map.add "washes" { in_spam=0; in_ham=5}
|> Map.add "washington" { in_spam=17; in_ham=36}
|> Map.add "wasn't" { in_spam=0; in_ham=76}
|> Map.add "wasnt" { in_spam=0; in_ham=3}
|> Map.add "waste" { in_spam=10; in_ham=20}
|> Map.add "wasted" { in_spam=0; in_ham=6}
|> Map.add "wasting" { in_spam=6; in_ham=3}
|> Map.add "watch" { in_spam=24; in_ham=23}
|> Map.add "watched" { in_spam=0; in_ham=11}
|> Map.add "watching" { in_spam=10; in_ham=38}
|> Map.add "water" { in_spam=1; in_ham=26}
|> Map.add "watermelon" { in_spam=0; in_ham=3}
|> Map.add "watershed" { in_spam=0; in_ham=4}
|> Map.add "wave" { in_spam=1; in_ham=7}
|> Map.add "waves" { in_spam=0; in_ham=3}
|> Map.add "waving" { in_spam=0; in_ham=4}
|> Map.add "way" { in_spam=58; in_ham=400}
|> Map.add "waylan" { in_spam=0; in_ham=4}
|> Map.add "wayne" { in_spam=1; in_ham=5}
|> Map.add "ways" { in_spam=12; in_ham=62}
|> Map.add "wayside" { in_spam=0; in_ham=7}
|> Map.add "we'd" { in_spam=0; in_ham=12}
|> Map.add "we'll" { in_spam=10; in_ham=34}
|> Map.add "we're" { in_spam=8; in_ham=86}
|> Map.add "we've" { in_spam=9; in_ham=54}
|> Map.add "weak" { in_spam=1; in_ham=18}
|> Map.add "weakening" { in_spam=0; in_ham=3}
|> Map.add "weakness" { in_spam=3; in_ham=4}
|> Map.add "weaknesses" { in_spam=0; in_ham=4}
|> Map.add "wealth" { in_spam=9; in_ham=16}
|> Map.add "wealthnow" { in_spam=6; in_ham=0}
|> Map.add "wealthy" { in_spam=6; in_ham=4}
|> Map.add "weapon" { in_spam=3; in_ham=2}
|> Map.add "weapons" { in_spam=0; in_ham=16}
|> Map.add "wear" { in_spam=7; in_ham=8}
|> Map.add "wearing" { in_spam=2; in_ham=5}
|> Map.add "wears" { in_spam=1; in_ham=7}
|> Map.add "weather" { in_spam=0; in_ham=22}
|> Map.add "web" { in_spam=65; in_ham=149}
|> Map.add "web's" { in_spam=9; in_ham=3}
|> Map.add "web-based" { in_spam=0; in_ham=6}
|> Map.add "webappsec" { in_spam=0; in_ham=4}
|> Map.add "webcam" { in_spam=6; in_ham=0}
|> Map.add "webforms" { in_spam=0; in_ham=6}
|> Map.add "weblog" { in_spam=0; in_ham=45}
|> Map.add "weblogger" { in_spam=0; in_ham=3}
|> Map.add "weblogs" { in_spam=1; in_ham=20}
|> Map.add "webmail" { in_spam=4; in_ham=3}
|> Map.add "webmaster" { in_spam=9; in_ham=11}
|> Map.add "webpage" { in_spam=0; in_ham=3}
|> Map.add "website" { in_spam=43; in_ham=39}
|> Map.add "websites" { in_spam=17; in_ham=7}
|> Map.add "wed" { in_spam=2; in_ham=132}
|> Map.add "wedded" { in_spam=0; in_ham=10}
|> Map.add "wedding" { in_spam=1; in_ham=4}
|> Map.add "wednesday" { in_spam=1; in_ham=53}
|> Map.add "weed" { in_spam=1; in_ham=3}
|> Map.add "weeded" { in_spam=0; in_ham=3}
|> Map.add "week" { in_spam=40; in_ham=95}
|> Map.add "week's" { in_spam=0; in_ham=4}
|> Map.add "weekend" { in_spam=0; in_ham=24}
|> Map.add "weekends" { in_spam=0; in_ham=4}
|> Map.add "weekly" { in_spam=13; in_ham=6}
|> Map.add "weeks" { in_spam=27; in_ham=41}
|> Map.add "weigh" { in_spam=0; in_ham=6}
|> Map.add "weighing" { in_spam=0; in_ham=3}
|> Map.add "weighs" { in_spam=0; in_ham=5}
|> Map.add "weight" { in_spam=18; in_ham=7}
|> Map.add "weil" { in_spam=1; in_ham=3}
|> Map.add "weird" { in_spam=0; in_ham=33}
|> Map.add "weirdpage" { in_spam=0; in_ham=8}
|> Map.add "welch" { in_spam=0; in_ham=32}
|> Map.add "welcome" { in_spam=10; in_ham=130}
|> Map.add "welcomed" { in_spam=1; in_ham=2}
|> Map.add "welcomes" { in_spam=1; in_ham=2}
|> Map.add "welfare" { in_spam=5; in_ham=7}
|> Map.add "well" { in_spam=53; in_ham=321}
|> Map.add "well-being" { in_spam=7; in_ham=3}
|> Map.add "well-known" { in_spam=1; in_ham=3}
|> Map.add "wellfleet" { in_spam=0; in_ham=6}
|> Map.add "wells" { in_spam=0; in_ham=3}
|> Map.add "wendy" { in_spam=2; in_ham=2}
|> Map.add "went" { in_spam=7; in_ham=89}
|> Map.add "were" { in_spam=46; in_ham=339}
|> Map.add "weren't" { in_spam=3; in_ham=18}
|> Map.add "wesley" { in_spam=0; in_ham=3}
|> Map.add "west" { in_spam=10; in_ham=32}
|> Map.add "western" { in_spam=4; in_ham=18}
|> Map.add "westport" { in_spam=6; in_ham=0}
|> Map.add "westwood" { in_spam=0; in_ham=3}
|> Map.add "wet" { in_spam=3; in_ham=6}
|> Map.add "wget" { in_spam=0; in_ham=3}
|> Map.add "wgl" { in_spam=0; in_ham=3}
|> Map.add "what" { in_spam=80; in_ham=665}
|> Map.add "what's" { in_spam=7; in_ham=71}
|> Map.add "whatever" { in_spam=8; in_ham=74}
|> Map.add "whats" { in_spam=0; in_ham=4}
|> Map.add "whatsoever" { in_spam=5; in_ham=16}
|> Map.add "wheel" { in_spam=0; in_ham=9}
|> Map.add "wheeler" { in_spam=0; in_ham=4}
|> Map.add "wheels" { in_spam=1; in_ham=6}
|> Map.add "when" { in_spam=76; in_ham=622}
|> Map.add "whenever" { in_spam=0; in_ham=13}
|> Map.add "where" { in_spam=57; in_ham=320}
|> Map.add "where's" { in_spam=1; in_ham=2}
|> Map.add "whereas" { in_spam=1; in_ham=12}
|> Map.add "whereby" { in_spam=1; in_ham=2}
|> Map.add "wherever" { in_spam=1; in_ham=4}
|> Map.add "whether" { in_spam=23; in_ham=88}
|> Map.add "whi" { in_spam=0; in_ham=6}
|> Map.add "which" { in_spam=83; in_ham=614}
|> Map.add "whichever" { in_spam=0; in_ham=3}
|> Map.add "while" { in_spam=46; in_ham=225}
|> Map.add "whim" { in_spam=0; in_ham=5}
|> Map.add "whimsical" { in_spam=0; in_ham=3}
|> Map.add "whip" { in_spam=0; in_ham=3}
|> Map.add "white" { in_spam=27; in_ham=33}
|> Map.add "whitehead" { in_spam=0; in_ham=17}
|> Map.add "whitelist" { in_spam=0; in_ham=18}
|> Map.add "whitelisting" { in_spam=0; in_ham=3}
|> Map.add "whitepaper" { in_spam=0; in_ham=3}
|> Map.add "whitespace" { in_spam=0; in_ham=3}
|> Map.add "whitey" { in_spam=0; in_ham=3}
|> Map.add "who" { in_spam=127; in_ham=428}
|> Map.add "who'd" { in_spam=0; in_ham=3}
|> Map.add "who's" { in_spam=0; in_ham=17}
|> Map.add "whoever" { in_spam=0; in_ham=7}
|> Map.add "whole" { in_spam=22; in_ham=98}
|> Map.add "wholesale" { in_spam=8; in_ham=2}
|> Map.add "wholly" { in_spam=1; in_ham=5}
|> Map.add "whom" { in_spam=3; in_ham=22}
|> Map.add "whose" { in_spam=13; in_ham=38}
|> Map.add "whump" { in_spam=0; in_ham=9}
|> Map.add "why" { in_spam=48; in_ham=247}
|> Map.add "wide" { in_spam=9; in_ham=25}
|> Map.add "widely" { in_spam=2; in_ham=25}
|> Map.add "widening" { in_spam=0; in_ham=7}
|> Map.add "wider" { in_spam=0; in_ham=4}
|> Map.add "widespread" { in_spam=0; in_ham=13}
|> Map.add "widget" { in_spam=0; in_ham=7}
|> Map.add "widow" { in_spam=3; in_ham=4}
|> Map.add "widows" { in_spam=0; in_ham=3}
|> Map.add "width" { in_spam=171; in_ham=9}
|> Map.add "wife" { in_spam=10; in_ham=20}
|> Map.add "wifi" { in_spam=0; in_ham=11}
|> Map.add "wild" { in_spam=6; in_ham=8}
|> Map.add "wildlife" { in_spam=0; in_ham=3}
|> Map.add "wildly" { in_spam=0; in_ham=3}
|> Map.add "will" { in_spam=221; in_ham=559}
|> Map.add "william" { in_spam=1; in_ham=20}
|> Map.add "williams" { in_spam=6; in_ham=34}
|> Map.add "willing" { in_spam=18; in_ham=44}
|> Map.add "willingness" { in_spam=6; in_ham=3}
|> Map.add "willis" { in_spam=0; in_ham=6}
|> Map.add "wills" { in_spam=2; in_ham=2}
|> Map.add "wilt" { in_spam=0; in_ham=8}
|> Map.add "win" { in_spam=9; in_ham=47}
|> Map.add "wind" { in_spam=3; in_ham=17}
|> Map.add "window" { in_spam=17; in_ham=67}
|> Map.add "windows" { in_spam=13; in_ham=85}
|> Map.add "windows-" { in_spam=47; in_ham=2}
|> Map.add "windsor" { in_spam=1; in_ham=5}
|> Map.add "wine" { in_spam=1; in_ham=4}
|> Map.add "winer" { in_spam=0; in_ham=6}
|> Map.add "winfax" { in_spam=6; in_ham=0}
|> Map.add "wing" { in_spam=1; in_ham=5}
|> Map.add "wings" { in_spam=0; in_ham=3}
|> Map.add "wink" { in_spam=1; in_ham=40}
|> Map.add "winner" { in_spam=2; in_ham=10}
|> Map.add "winners" { in_spam=7; in_ham=3}
|> Map.add "winning" { in_spam=7; in_ham=5}
|> Map.add "wins" { in_spam=0; in_ham=7}
|> Map.add "winter" { in_spam=0; in_ham=11}
|> Map.add "winters" { in_spam=0; in_ham=3}
|> Map.add "winzip" { in_spam=0; in_ham=4}
|> Map.add "wipe" { in_spam=4; in_ham=6}
|> Map.add "wiped" { in_spam=0; in_ham=3}
|> Map.add "wire" { in_spam=0; in_ham=5}
|> Map.add "wire-speed" { in_spam=0; in_ham=6}
|> Map.add "wired" { in_spam=1; in_ham=17}
|> Map.add "wireless" { in_spam=3; in_ham=36}
|> Map.add "wirespeed" { in_spam=0; in_ham=6}
|> Map.add "wirex" { in_spam=0; in_ham=4}
|> Map.add "wisdom" { in_spam=0; in_ham=16}
|> Map.add "wise" { in_spam=0; in_ham=10}
|> Map.add "wisely" { in_spam=2; in_ham=4}
|> Map.add "wish" { in_spam=141; in_ham=43}
|> Map.add "wishes" { in_spam=2; in_ham=9}
|> Map.add "wishful" { in_spam=0; in_ham=5}
|> Map.add "wit" { in_spam=1; in_ham=2}
|> Map.add "with" { in_spam=280; in_ham=1207}
|> Map.add "with-cards" { in_spam=0; in_ham=5}
|> Map.add "withdraw" { in_spam=0; in_ham=5}
|> Map.add "withheld" { in_spam=0; in_ham=4}
|> Map.add "within" { in_spam=68; in_ham=84}
|> Map.add "without" { in_spam=54; in_ham=218}
|> Map.add "witness" { in_spam=0; in_ham=4}
|> Map.add "witnessed" { in_spam=0; in_ham=5}
|> Map.add "witnesses" { in_spam=0; in_ham=8}
|> Map.add "wives" { in_spam=3; in_ham=6}
|> Map.add "wizard" { in_spam=1; in_ham=4}
|> Map.add "wmf" { in_spam=1; in_ham=2}
|> Map.add "wolf" { in_spam=5; in_ham=4}
|> Map.add "wolves" { in_spam=0; in_ham=3}
|> Map.add "woman" { in_spam=4; in_ham=39}
|> Map.add "woman's" { in_spam=1; in_ham=4}
|> Map.add "women" { in_spam=10; in_ham=52}
|> Map.add "women's" { in_spam=2; in_ham=9}
|> Map.add "won" { in_spam=1; in_ham=23}
|> Map.add "won't" { in_spam=11; in_ham=91}
|> Map.add "wonder" { in_spam=5; in_ham=42}
|> Map.add "wondered" { in_spam=8; in_ham=13}
|> Map.add "wonderful" { in_spam=16; in_ham=27}
|> Map.add "wondering" { in_spam=2; in_ham=22}
|> Map.add "wontfix" { in_spam=0; in_ham=4}
|> Map.add "wood" { in_spam=1; in_ham=12}
|> Map.add "woody" { in_spam=0; in_ham=5}
|> Map.add "woohoo" { in_spam=0; in_ham=6}
|> Map.add "woozle" { in_spam=0; in_ham=3}
|> Map.add "word" { in_spam=25; in_ham=84}
|> Map.add "wordinfo" { in_spam=0; in_ham=6}
|> Map.add "words" { in_spam=4; in_ham=84}
|> Map.add "wore" { in_spam=1; in_ham=2}
|> Map.add "work" { in_spam=73; in_ham=328}
|> Map.add "workaround" { in_spam=0; in_ham=9}
|> Map.add "worked" { in_spam=9; in_ham=81}
|> Map.add "workers" { in_spam=1; in_ham=21}
|> Map.add "workflow" { in_spam=0; in_ham=3}
|> Map.add "working" { in_spam=33; in_ham=166}
|> Map.add "workplace" { in_spam=0; in_ham=3}
|> Map.add "works" { in_spam=27; in_ham=146}
|> Map.add "workshop" { in_spam=0; in_ham=4}
|> Map.add "workstations" { in_spam=0; in_ham=3}
|> Map.add "world" { in_spam=37; in_ham=284}
|> Map.add "world's" { in_spam=6; in_ham=107}
|> Map.add "world-class" { in_spam=0; in_ham=7}
|> Map.add "worldcom" { in_spam=0; in_ham=4}
|> Map.add "worlds" { in_spam=3; in_ham=1}
|> Map.add "worldwide" { in_spam=16; in_ham=22}
|> Map.add "worm" { in_spam=0; in_ham=3}
|> Map.add "worn" { in_spam=0; in_ham=3}
|> Map.add "worried" { in_spam=1; in_ham=16}
|> Map.add "worry" { in_spam=9; in_ham=25}
|> Map.add "worse" { in_spam=2; in_ham=46}
|> Map.add "worsened" { in_spam=0; in_ham=3}
|> Map.add "worst" { in_spam=18; in_ham=38}
|> Map.add "worth" { in_spam=19; in_ham=85}
|> Map.add "worthless" { in_spam=0; in_ham=7}
|> Map.add "worthwhile" { in_spam=5; in_ham=5}
|> Map.add "worthy" { in_spam=2; in_ham=7}
|> Map.add "would" { in_spam=92; in_ham=591}
|> Map.add "would-be" { in_spam=0; in_ham=3}
|> Map.add "wouldn" { in_spam=5; in_ham=2}
|> Map.add "wouldn't" { in_spam=11; in_ham=67}
|> Map.add "wouldnt" { in_spam=0; in_ham=4}
|> Map.add "wound" { in_spam=0; in_ham=8}
|> Map.add "wounded" { in_spam=0; in_ham=4}
|> Map.add "wounds" { in_spam=1; in_ham=2}
|> Map.add "wow" { in_spam=0; in_ham=22}
|> Map.add "wp-dyn" { in_spam=0; in_ham=11}
|> Map.add "wrap" { in_spam=0; in_ham=3}
|> Map.add "wrapped" { in_spam=2; in_ham=4}
|> Map.add "wrapping" { in_spam=6; in_ham=4}
|> Map.add "wreak" { in_spam=0; in_ham=3}
|> Map.add "wright" { in_spam=0; in_ham=3}
|> Map.add "wrinkle" { in_spam=6; in_ham=0}
|> Map.add "writable" { in_spam=0; in_ham=7}
|> Map.add "write" { in_spam=25; in_ham=91}
|> Map.add "writer" { in_spam=3; in_ham=19}
|> Map.add "writers" { in_spam=1; in_ham=7}
|> Map.add "writes" { in_spam=0; in_ham=163}
|> Map.add "writhing" { in_spam=0; in_ham=3}
|> Map.add "writing" { in_spam=11; in_ham=50}
|> Map.add "written" { in_spam=7; in_ham=61}
|> Map.add "wrong" { in_spam=10; in_ham=98}
|> Map.add "wrong-doers" { in_spam=0; in_ham=35}
|> Map.add "wrongly" { in_spam=0; in_ham=4}
|> Map.add "wrote" { in_spam=0; in_ham=782}
|> Map.add "wrt" { in_spam=0; in_ham=9}
|> Map.add "wsj" { in_spam=0; in_ham=3}
|> Map.add "wsmf" { in_spam=0; in_ham=5}
|> Map.add "wtf" { in_spam=0; in_ham=11}
|> Map.add "wto" { in_spam=0; in_ham=4}
|> Map.add "wwii" { in_spam=0; in_ham=3}
|> Map.add "www" { in_spam=272; in_ham=1403}
|> Map.add "wybe" { in_spam=0; in_ham=5}
|> Map.add "wyoming" { in_spam=3; in_ham=2}
|> Map.add "x-beenthere" { in_spam=0; in_ham=3}
|> Map.add "x-from" { in_spam=0; in_ham=7}
|> Map.add "x-mailer" { in_spam=1; in_ham=11}
|> Map.add "x-priority" { in_spam=1; in_ham=2}
|> Map.add "x-spam-" { in_spam=0; in_ham=3}
|> Map.add "x-uidl" { in_spam=0; in_ham=3}
|> Map.add "xaj" { in_spam=0; in_ham=3}
|> Map.add "xargs" { in_spam=0; in_ham=4}
|> Map.add "xay" { in_spam=8; in_ham=0}
|> Map.add "xdegrees" { in_spam=0; in_ham=5}
|> Map.add "xemacs" { in_spam=0; in_ham=4}
|> Map.add "xent" { in_spam=0; in_ham=149}
|> Map.add "xhtml" { in_spam=0; in_ham=5}
|> Map.add "xim" { in_spam=0; in_ham=42}
|> Map.add "ximian" { in_spam=0; in_ham=6}
|> Map.add "xine" { in_spam=0; in_ham=24}
|> Map.add "xine-libs" { in_spam=0; in_ham=4}
|> Map.add "xine-libs-" { in_spam=0; in_ham=3}
|> Map.add "xine-root" { in_spam=0; in_ham=7}
|> Map.add "xmhcache" { in_spam=0; in_ham=6}
|> Map.add "xml" { in_spam=3; in_ham=45}
|> Map.add "xml-aware" { in_spam=0; in_ham=6}
|> Map.add "xml-based" { in_spam=0; in_ham=6}
|> Map.add "xml-centric" { in_spam=0; in_ham=6}
|> Map.add "xmms" { in_spam=0; in_ham=16}
|> Map.add "xnck" { in_spam=0; in_ham=4}
|> Map.add "xpe" { in_spam=0; in_ham=6}
|> Map.add "xps" { in_spam=0; in_ham=4}
|> Map.add "xsl" { in_spam=0; in_ham=6}
|> Map.add "xterm" { in_spam=0; in_ham=7}
|> Map.add "xterms" { in_spam=0; in_ham=4}
|> Map.add "xx-xx'" { in_spam=0; in_ham=3}
|> Map.add "xxx" { in_spam=10; in_ham=4}
|> Map.add "xyz" { in_spam=4; in_ham=3}
|> Map.add "y'all" { in_spam=0; in_ham=4}
|> Map.add "y'know" { in_spam=0; in_ham=4}
|> Map.add "yah" { in_spam=1; in_ham=2}
|> Map.add "yahoo" { in_spam=18; in_ham=143}
|> Map.add "yahoogroups" { in_spam=0; in_ham=8}
|> Map.add "yahoonews" { in_spam=0; in_ham=3}
|> Map.add "yale" { in_spam=0; in_ham=4}
|> Map.add "yanks" { in_spam=0; in_ham=3}
|> Map.add "yannick" { in_spam=0; in_ham=13}
|> Map.add "yapc" { in_spam=0; in_ham=7}
|> Map.add "yarns" { in_spam=0; in_ham=3}
|> Map.add "yassir" { in_spam=0; in_ham=5}
|> Map.add "yay" { in_spam=0; in_ham=3}
|> Map.add "ybb" { in_spam=1; in_ham=51}
|> Map.add "yea" { in_spam=1; in_ham=8}
|> Map.add "yeah" { in_spam=4; in_ham=49}
|> Map.add "year" { in_spam=53; in_ham=122}
|> Map.add "year's" { in_spam=4; in_ham=13}
|> Map.add "year-old" { in_spam=4; in_ham=25}
|> Map.add "years" { in_spam=60; in_ham=223}
|> Map.add "yeasterday" { in_spam=0; in_ham=4}
|> Map.add "yellow" { in_spam=5; in_ham=4}
|> Map.add "yemen" { in_spam=2; in_ham=3}
|> Map.add "yep" { in_spam=2; in_ham=15}
|> Map.add "yer" { in_spam=1; in_ham=2}
|> Map.add "yes" { in_spam=50; in_ham=176}
|> Map.add "yesterday" { in_spam=0; in_ham=57}
|> Map.add "yesterday's" { in_spam=0; in_ham=6}
|> Map.add "yet" { in_spam=18; in_ham=151}
|> Map.add "yetanother" { in_spam=0; in_ham=3}
|> Map.add "yield" { in_spam=1; in_ham=6}
|> Map.add "yielding" { in_spam=0; in_ham=6}
|> Map.add "yields" { in_spam=1; in_ham=2}
|> Map.add "yikes" { in_spam=0; in_ham=3}
|> Map.add "yoga" { in_spam=0; in_ham=3}
|> Map.add "york" { in_spam=18; in_ham=43}
|> Map.add "york's" { in_spam=0; in_ham=3}
|> Map.add "yorker" { in_spam=0; in_ham=4}
|> Map.add "yorkshire" { in_spam=0; in_ham=3}
|> Map.add "you" { in_spam=379; in_ham=1190}
|> Map.add "you'd" { in_spam=7; in_ham=47}
|> Map.add "you'll" { in_spam=51; in_ham=72}
|> Map.add "you're" { in_spam=31; in_ham=204}
|> Map.add "you've" { in_spam=21; in_ham=52}
|> Map.add "young" { in_spam=4; in_ham=31}
|> Map.add "younger" { in_spam=3; in_ham=3}
|> Map.add "your" { in_spam=347; in_ham=644}
|> Map.add "your's" { in_spam=1; in_ham=2}
|> Map.add "your-name" { in_spam=0; in_ham=3}
|> Map.add "yours" { in_spam=48; in_ham=8}
|> Map.add "yourself" { in_spam=48; in_ham=40}
|> Map.add "youth" { in_spam=3; in_ham=3}
|> Map.add "ytyv" { in_spam=0; in_ham=4}
|> Map.add "yuck" { in_spam=0; in_ham=4}
|> Map.add "yukon" { in_spam=1; in_ham=2}
|> Map.add "yup" { in_spam=0; in_ham=11}
|> Map.add "yyboc" { in_spam=0; in_ham=3}
|> Map.add "yyyy" { in_spam=0; in_ham=4}
|> Map.add "zaire" { in_spam=5; in_ham=0}
|> Map.add "zambia" { in_spam=2; in_ham=3}
|> Map.add "zawodny" { in_spam=0; in_ham=37}
|> Map.add "zdnet" { in_spam=0; in_ham=3}
|> Map.add "zealand" { in_spam=11; in_ham=3}
|> Map.add "zealot" { in_spam=0; in_ham=8}
|> Map.add "zealous" { in_spam=0; in_ham=3}
|> Map.add "zen" { in_spam=0; in_ham=6}
|> Map.add "zero" { in_spam=5; in_ham=23}
|> Map.add "zero-sum" { in_spam=0; in_ham=4}
|> Map.add "ziggy" { in_spam=0; in_ham=15}
|> Map.add "zimbabwe" { in_spam=6; in_ham=3}
|> Map.add "zip" { in_spam=12; in_ham=14}
|> Map.add "zipped" { in_spam=0; in_ham=3}
|> Map.add "znion" { in_spam=0; in_ham=4}
|> Map.add "zone" { in_spam=2; in_ham=8}
|> Map.add "zones" { in_spam=0; in_ham=6}
|> Map.add "zoo" { in_spam=1; in_ham=2}
|> Map.add "zope" { in_spam=2; in_ham=7}
|> Map.add "ztvn" { in_spam=0; in_ham=4}
|> Map.add "zzzz" { in_spam=40; in_ham=1}

