open Bayesian.Database
open BayesianBody_003
let db = db 
|> Map.add "damn" { in_spam=0; in_ham=17}
|> Map.add "damned" { in_spam=0; in_ham=4}
|> Map.add "dan" { in_spam=7; in_ham=42}
|> Map.add "dance" { in_spam=2; in_ham=3}
|> Map.add "dandy" { in_spam=0; in_ham=4}
|> Map.add "dang" { in_spam=0; in_ham=4}
|> Map.add "danger" { in_spam=2; in_ham=10}
|> Map.add "dangerous" { in_spam=0; in_ham=23}
|> Map.add "dangers" { in_spam=0; in_ham=5}
|> Map.add "daniel" { in_spam=5; in_ham=24}
|> Map.add "dankohn" { in_spam=0; in_ham=5}
|> Map.add "danny" { in_spam=0; in_ham=5}
|> Map.add "dare" { in_spam=10; in_ham=1}
|> Map.add "dared" { in_spam=1; in_ham=2}
|> Map.add "daring" { in_spam=0; in_ham=3}
|> Map.add "dark" { in_spam=1; in_ham=27}
|> Map.add "darker" { in_spam=0; in_ham=3}
|> Map.add "darkness" { in_spam=0; in_ham=3}
|> Map.add "darn" { in_spam=1; in_ham=7}
|> Map.add "darwin" { in_spam=0; in_ham=6}
|> Map.add "dash" { in_spam=0; in_ham=6}
|> Map.add "dashes" { in_spam=0; in_ham=5}
|> Map.add "dashing" { in_spam=0; in_ham=3}
|> Map.add "data" { in_spam=35; in_ham=169}
|> Map.add "database" { in_spam=31; in_ham=61}
|> Map.add "databases" { in_spam=6; in_ham=6}
|> Map.add "datapower" { in_spam=0; in_ham=12}
|> Map.add "datapower's" { in_spam=0; in_ham=10}
|> Map.add "datapowers" { in_spam=0; in_ham=6}
|> Map.add "date" { in_spam=20; in_ham=810}
|> Map.add "dated" { in_spam=2; in_ham=13}
|> Map.add "dates" { in_spam=1; in_ham=11}
|> Map.add "dating" { in_spam=2; in_ham=9}
|> Map.add "daughter" { in_spam=0; in_ham=11}
|> Map.add "dave" { in_spam=0; in_ham=74}
|> Map.add "dave's" { in_spam=0; in_ham=4}
|> Map.add "davedina" { in_spam=0; in_ham=8}
|> Map.add "david" { in_spam=3; in_ham=55}
|> Map.add "davis" { in_spam=1; in_ham=6}
|> Map.add "davorg" { in_spam=0; in_ham=3}
|> Map.add "dawn" { in_spam=0; in_ham=3}
|> Map.add "day" { in_spam=73; in_ham=163}
|> Map.add "daypop" { in_spam=0; in_ham=3}
|> Map.add "days" { in_spam=64; in_ham=88}
|> Map.add "dbm" { in_spam=1; in_ham=2}
|> Map.add "dbqe" { in_spam=0; in_ham=80}
|> Map.add "dbs" { in_spam=1; in_ham=7}
|> Map.add "dbsinfo" { in_spam=0; in_ham=3}
|> Map.add "dcc" { in_spam=0; in_ham=12}
|> Map.add "de-feminized" { in_spam=0; in_ham=10}
|> Map.add "de-select" { in_spam=0; in_ham=3}
|> Map.add "dead" { in_spam=5; in_ham=47}
|> Map.add "deadline" { in_spam=2; in_ham=5}
|> Map.add "deadly" { in_spam=0; in_ham=5}
|> Map.add "deaf" { in_spam=1; in_ham=3}
|> Map.add "deafbox" { in_spam=0; in_ham=3}
|> Map.add "deal" { in_spam=51; in_ham=62}
|> Map.add "dealer" { in_spam=8; in_ham=1}
|> Map.add "dealing" { in_spam=0; in_ham=16}
|> Map.add "deals" { in_spam=5; in_ham=16}
|> Map.add "dealt" { in_spam=5; in_ham=6}
|> Map.add "dean" { in_spam=0; in_ham=3}
|> Map.add "dear" { in_spam=64; in_ham=16}
|> Map.add "death" { in_spam=19; in_ham=41}
|> Map.add "death-taxes" { in_spam=0; in_ham=3}
|> Map.add "deaths" { in_spam=0; in_ham=5}
|> Map.add "debate" { in_spam=0; in_ham=18}
|> Map.add "debating" { in_spam=0; in_ham=3}
|> Map.add "debian" { in_spam=0; in_ham=10}
|> Map.add "debt" { in_spam=16; in_ham=6}
|> Map.add "debts" { in_spam=4; in_ham=1}
|> Map.add "debug" { in_spam=0; in_ham=26}
|> Map.add "dec" { in_spam=0; in_ham=7}
|> Map.add "decade" { in_spam=4; in_ham=21}
|> Map.add "decades" { in_spam=1; in_ham=20}
|> Map.add "decay" { in_spam=0; in_ham=3}
|> Map.add "decaying" { in_spam=0; in_ham=4}
|> Map.add "december" { in_spam=4; in_ham=12}
|> Map.add "decent" { in_spam=6; in_ham=16}
|> Map.add "decide" { in_spam=19; in_ham=29}
|> Map.add "decided" { in_spam=21; in_ham=39}
|> Map.add "decidedly" { in_spam=1; in_ham=4}
|> Map.add "decides" { in_spam=5; in_ham=3}
|> Map.add "deciding" { in_spam=0; in_ham=3}
|> Map.add "decision" { in_spam=12; in_ham=23}
|> Map.add "decisions" { in_spam=4; in_ham=20}
|> Map.add "decisions-" { in_spam=0; in_ham=4}
|> Map.add "decisive" { in_spam=0; in_ham=3}
|> Map.add "deck" { in_spam=0; in_ham=9}
|> Map.add "declan" { in_spam=0; in_ham=3}
|> Map.add "declaration" { in_spam=1; in_ham=16}
|> Map.add "declare" { in_spam=2; in_ham=2}
|> Map.add "declared" { in_spam=1; in_ham=9}
|> Map.add "declaring" { in_spam=0; in_ham=3}
|> Map.add "decline" { in_spam=0; in_ham=54}
|> Map.add "declined" { in_spam=2; in_ham=6}
|> Map.add "decode" { in_spam=0; in_ham=6}
|> Map.add "decorations" { in_spam=0; in_ham=4}
|> Map.add "decorative" { in_spam=0; in_ham=3}
|> Map.add "decore" { in_spam=0; in_ham=3}
|> Map.add "decrease" { in_spam=0; in_ham=5}
|> Map.add "decreased" { in_spam=0; in_ham=3}
|> Map.add "decrypt" { in_spam=0; in_ham=8}
|> Map.add "decrypted" { in_spam=0; in_ham=3}
|> Map.add "decrypting" { in_spam=0; in_ham=3}
|> Map.add "decryption" { in_spam=0; in_ham=4}
|> Map.add "decss" { in_spam=0; in_ham=3}
|> Map.add "dedicated" { in_spam=4; in_ham=5}
|> Map.add "deed" { in_spam=0; in_ham=3}
|> Map.add "deemed" { in_spam=0; in_ham=10}
|> Map.add "deep" { in_spam=1; in_ham=22}
|> Map.add "deepeddy" { in_spam=0; in_ham=49}
|> Map.add "deepening" { in_spam=0; in_ham=7}
|> Map.add "deeper" { in_spam=0; in_ham=11}
|> Map.add "deeply" { in_spam=0; in_ham=7}
|> Map.add "deersoft" { in_spam=0; in_ham=3}
|> Map.add "def" { in_spam=0; in_ham=4}
|> Map.add "default" { in_spam=9; in_ham=75}
|> Map.add "defaults" { in_spam=0; in_ham=12}
|> Map.add "defeat" { in_spam=0; in_ham=8}
|> Map.add "defeated" { in_spam=1; in_ham=4}
|> Map.add "defence" { in_spam=3; in_ham=2}
|> Map.add "defend" { in_spam=0; in_ham=28}
|> Map.add "defended" { in_spam=0; in_ham=3}
|> Map.add "defense" { in_spam=2; in_ham=10}
|> Map.add "defenses" { in_spam=0; in_ham=7}
|> Map.add "defensive" { in_spam=1; in_ham=3}
|> Map.add "definately" { in_spam=0; in_ham=11}
|> Map.add "define" { in_spam=1; in_ham=19}
|> Map.add "defined" { in_spam=3; in_ham=21}
|> Map.add "defines" { in_spam=1; in_ham=3}
|> Map.add "defining" { in_spam=0; in_ham=6}
|> Map.add "definitely" { in_spam=2; in_ham=35}
|> Map.add "definition" { in_spam=2; in_ham=17}
|> Map.add "definitions" { in_spam=1; in_ham=2}
|> Map.add "definitive" { in_spam=1; in_ham=2}
|> Map.add "definiton" { in_spam=0; in_ham=4}
|> Map.add "defnitions" { in_spam=0; in_ham=3}
|> Map.add "defuse" { in_spam=0; in_ham=3}
|> Map.add "degree" { in_spam=1; in_ham=11}
|> Map.add "degrees" { in_spam=1; in_ham=11}
|> Map.add "deja" { in_spam=0; in_ham=8}
|> Map.add "del" { in_spam=0; in_ham=6}
|> Map.add "delay" { in_spam=13; in_ham=12}
|> Map.add "delays" { in_spam=2; in_ham=3}
|> Map.add "delegate" { in_spam=1; in_ham=2}
|> Map.add "delendam" { in_spam=0; in_ham=4}
|> Map.add "delete" { in_spam=21; in_ham=34}
|> Map.add "deleted" { in_spam=13; in_ham=7}
|> Map.add "deleted-ham" { in_spam=0; in_ham=3}
|> Map.add "deleting" { in_spam=0; in_ham=8}
|> Map.add "deliberate" { in_spam=1; in_ham=4}
|> Map.add "deliberately" { in_spam=3; in_ham=6}
|> Map.add "deliberation" { in_spam=1; in_ham=2}
|> Map.add "delight" { in_spam=2; in_ham=2}
|> Map.add "delimited" { in_spam=0; in_ham=3}
|> Map.add "deliver" { in_spam=3; in_ham=26}
|> Map.add "delivered" { in_spam=8; in_ham=21}
|> Map.add "delivered-to" { in_spam=0; in_ham=7}
|> Map.add "delivering" { in_spam=3; in_ham=12}
|> Map.add "delivers" { in_spam=4; in_ham=13}
|> Map.add "delivery" { in_spam=13; in_ham=19}
|> Map.add "dell" { in_spam=1; in_ham=17}
|> Map.add "dellaca" { in_spam=6; in_ham=0}
|> Map.add "delta" { in_spam=2; in_ham=14}
|> Map.add "demand" { in_spam=8; in_ham=21}
|> Map.add "demanded" { in_spam=1; in_ham=5}
|> Map.add "demanding" { in_spam=4; in_ham=5}
|> Map.add "demands" { in_spam=5; in_ham=8}
|> Map.add "dementia" { in_spam=0; in_ham=4}
|> Map.add "demipublican" { in_spam=0; in_ham=3}
|> Map.add "demo" { in_spam=5; in_ham=2}
|> Map.add "democracies" { in_spam=0; in_ham=3}
|> Map.add "democracy" { in_spam=1; in_ham=13}
|> Map.add "democratic" { in_spam=13; in_ham=8}
|> Map.add "democrats" { in_spam=0; in_ham=5}
|> Map.add "demographics" { in_spam=0; in_ham=8}
|> Map.add "demonstrate" { in_spam=3; in_ham=4}
|> Map.add "demonstrated" { in_spam=0; in_ham=6}
|> Map.add "demonstrates" { in_spam=1; in_ham=2}
|> Map.add "deniability" { in_spam=0; in_ham=3}
|> Map.add "denied" { in_spam=4; in_ham=8}
|> Map.add "denies" { in_spam=0; in_ham=4}
|> Map.add "denmtrasote" { in_spam=0; in_ham=3}
|> Map.add "dense" { in_spam=0; in_ham=7}
|> Map.add "density" { in_spam=0; in_ham=9}
|> Map.add "dental" { in_spam=3; in_ham=1}
|> Map.add "dentist" { in_spam=1; in_ham=4}
|> Map.add "denver" { in_spam=0; in_ham=4}
|> Map.add "deny" { in_spam=0; in_ham=8}
|> Map.add "denying" { in_spam=0; in_ham=4}
|> Map.add "depart" { in_spam=1; in_ham=3}
|> Map.add "department" { in_spam=12; in_ham=31}
|> Map.add "depend" { in_spam=2; in_ham=11}
|> Map.add "dependence" { in_spam=0; in_ham=3}
|> Map.add "dependencies" { in_spam=0; in_ham=27}
|> Map.add "dependency" { in_spam=0; in_ham=25}
|> Map.add "dependent" { in_spam=2; in_ham=2}
|> Map.add "depending" { in_spam=3; in_ham=20}
|> Map.add "depends" { in_spam=0; in_ham=31}
|> Map.add "deployed" { in_spam=0; in_ham=10}
|> Map.add "deploying" { in_spam=0; in_ham=6}
|> Map.add "deployment" { in_spam=0; in_ham=19}
|> Map.add "deployments" { in_spam=0; in_ham=3}
|> Map.add "depmod" { in_spam=0; in_ham=4}
|> Map.add "deposit" { in_spam=18; in_ham=0}
|> Map.add "deposited" { in_spam=16; in_ham=7}
|> Map.add "deposits" { in_spam=5; in_ham=0}
|> Map.add "deprecated" { in_spam=0; in_ham=3}
|> Map.add "depressed" { in_spam=0; in_ham=3}
|> Map.add "depressing" { in_spam=1; in_ham=3}
|> Map.add "depression" { in_spam=1; in_ham=7}
|> Map.add "dept" { in_spam=2; in_ham=4}
|> Map.add "depth" { in_spam=0; in_ham=3}
|> Map.add "deputy" { in_spam=0; in_ham=5}
|> Map.add "der" { in_spam=0; in_ham=4}
|> Map.add "deregulation" { in_spam=0; in_ham=3}
|> Map.add "derived" { in_spam=1; in_ham=5}
|> Map.add "derricutt" { in_spam=0; in_ham=6}
|> Map.add "des" { in_spam=4; in_ham=1}
|> Map.add "descendants" { in_spam=0; in_ham=7}
|> Map.add "descendents" { in_spam=0; in_ham=5}
|> Map.add "describe" { in_spam=1; in_ham=12}
|> Map.add "described" { in_spam=10; in_ham=28}
|> Map.add "describes" { in_spam=0; in_ham=7}
|> Map.add "describing" { in_spam=0; in_ham=6}
|> Map.add "description" { in_spam=0; in_ham=24}
|> Map.add "descriptions" { in_spam=1; in_ham=6}
|> Map.add "descriptor" { in_spam=0; in_ham=5}
|> Map.add "desert" { in_spam=0; in_ham=4}
|> Map.add "deserve" { in_spam=11; in_ham=52}
|> Map.add "deserved" { in_spam=0; in_ham=5}
|> Map.add "design" { in_spam=5; in_ham=45}
|> Map.add "designated" { in_spam=5; in_ham=6}
|> Map.add "designed" { in_spam=6; in_ham=49}
|> Map.add "designer" { in_spam=5; in_ham=7}
|> Map.add "designers" { in_spam=1; in_ham=9}
|> Map.add "designing" { in_spam=0; in_ham=4}
|> Map.add "designs" { in_spam=1; in_ham=10}
|> Map.add "desirable" { in_spam=0; in_ham=3}
|> Map.add "desire" { in_spam=10; in_ham=4}
|> Map.add "desired" { in_spam=0; in_ham=11}
|> Map.add "desires" { in_spam=0; in_ham=3}
|> Map.add "desk" { in_spam=10; in_ham=5}
|> Map.add "desktop" { in_spam=0; in_ham=23}
|> Map.add "desktops" { in_spam=0; in_ham=11}
|> Map.add "desperate" { in_spam=2; in_ham=3}
|> Map.add "desperation" { in_spam=0; in_ham=5}
|> Map.add "despite" { in_spam=5; in_ham=34}
|> Map.add "destination" { in_spam=2; in_ham=9}
|> Map.add "destined" { in_spam=1; in_ham=2}
|> Map.add "destitution" { in_spam=0; in_ham=4}
|> Map.add "destroy" { in_spam=0; in_ham=7}
|> Map.add "destroyed" { in_spam=0; in_ham=11}
|> Map.add "destroyer" { in_spam=0; in_ham=3}
|> Map.add "destroying" { in_spam=0; in_ham=3}
|> Map.add "destruction" { in_spam=0; in_ham=9}
|> Map.add "destructive" { in_spam=16; in_ham=3}
|> Map.add "detached" { in_spam=0; in_ham=3}
|> Map.add "detail" { in_spam=2; in_ham=29}
|> Map.add "detailed" { in_spam=9; in_ham=13}
|> Map.add "details" { in_spam=24; in_ham=49}
|> Map.add "detect" { in_spam=2; in_ham=8}
|> Map.add "detected" { in_spam=0; in_ham=11}
|> Map.add "detection" { in_spam=1; in_ham=4}
|> Map.add "determine" { in_spam=6; in_ham=8}
|> Map.add "determined" { in_spam=4; in_ham=16}
|> Map.add "deterred" { in_spam=0; in_ham=4}
|> Map.add "dethroned" { in_spam=0; in_ham=4}
|> Map.add "detractors" { in_spam=0; in_ham=3}
|> Map.add "detroit" { in_spam=0; in_ham=3}
|> Map.add "dev" { in_spam=1; in_ham=39}
|> Map.add "devastated" { in_spam=0; in_ham=5}
|> Map.add "devastating" { in_spam=0; in_ham=3}
|> Map.add "devel" { in_spam=0; in_ham=5}
|> Map.add "develop" { in_spam=7; in_ham=19}
|> Map.add "developed" { in_spam=1; in_ham=38}
|> Map.add "developer" { in_spam=0; in_ham=25}
|> Map.add "developer's" { in_spam=0; in_ham=6}
|> Map.add "developers" { in_spam=0; in_ham=21}
|> Map.add "developing" { in_spam=6; in_ham=35}
|> Map.add "development" { in_spam=16; in_ham=56}
|> Map.add "developments" { in_spam=0; in_ham=8}
|> Map.add "develops" { in_spam=0; in_ham=3}
|> Map.add "device" { in_spam=0; in_ham=59}
|> Map.add "devices" { in_spam=1; in_ham=28}
|> Map.add "devil" { in_spam=0; in_ham=5}
|> Map.add "devore" { in_spam=0; in_ham=11}
|> Map.add "devote" { in_spam=0; in_ham=6}
|> Map.add "devoted" { in_spam=7; in_ham=3}
|> Map.add "devteam" { in_spam=0; in_ham=6}
|> Map.add "dewdney" { in_spam=0; in_ham=3}
|> Map.add "dexport" { in_spam=0; in_ham=3}
|> Map.add "dexter" { in_spam=0; in_ham=3}
|> Map.add "dga" { in_spam=0; in_ham=3}
|> Map.add "dgxt" { in_spam=0; in_ham=6}
|> Map.add "diabetes" { in_spam=4; in_ham=1}
|> Map.add "diagnose" { in_spam=5; in_ham=0}
|> Map.add "diagnostics" { in_spam=15; in_ham=0}
|> Map.add "dial" { in_spam=2; in_ham=5}
|> Map.add "dialog" { in_spam=0; in_ham=9}
|> Map.add "dialup" { in_spam=0; in_ham=4}
|> Map.add "diamond" { in_spam=6; in_ham=6}
|> Map.add "diamonds" { in_spam=3; in_ham=3}
|> Map.add "diary" { in_spam=0; in_ham=4}
|> Map.add "dick" { in_spam=0; in_ham=4}
|> Map.add "dickens" { in_spam=0; in_ham=3}
|> Map.add "dickheads" { in_spam=0; in_ham=9}
|> Map.add "dictated" { in_spam=1; in_ham=3}
|> Map.add "dictatorship" { in_spam=1; in_ham=2}
|> Map.add "dictionary" { in_spam=1; in_ham=11}
|> Map.add "did" { in_spam=30; in_ham=220}
|> Map.add "didn" { in_spam=0; in_ham=3}
|> Map.add "didn't" { in_spam=15; in_ham=188}
|> Map.add "didnt" { in_spam=0; in_ham=7}
|> Map.add "die" { in_spam=3; in_ham=21}
|> Map.add "died" { in_spam=15; in_ham=25}
|> Map.add "dies" { in_spam=0; in_ham=7}
|> Map.add "diet" { in_spam=4; in_ham=2}
|> Map.add "dieting" { in_spam=5; in_ham=0}
|> Map.add "diferent" { in_spam=0; in_ham=5}
|> Map.add "diff" { in_spam=2; in_ham=20}
|> Map.add "differ" { in_spam=0; in_ham=3}
|> Map.add "difference" { in_spam=11; in_ham=56}
|> Map.add "differences" { in_spam=1; in_ham=18}
|> Map.add "different" { in_spam=31; in_ham=194}
|> Map.add "differently" { in_spam=0; in_ham=13}
|> Map.add "difficult" { in_spam=4; in_ham=58}
|> Map.add "difficulties" { in_spam=0; in_ham=6}
|> Map.add "difficulty" { in_spam=0; in_ham=12}
|> Map.add "dig" { in_spam=1; in_ham=15}
|> Map.add "digeratus" { in_spam=0; in_ham=5}
|> Map.add "digest" { in_spam=0; in_ham=9}
|> Map.add "digging" { in_spam=0; in_ham=7}
|> Map.add "digid" { in_spam=0; in_ham=3}
|> Map.add "digit" { in_spam=2; in_ham=6}
|> Map.add "digital" { in_spam=10; in_ham=65}
|> Map.add "digits" { in_spam=1; in_ham=3}
|> Map.add "dignified" { in_spam=0; in_ham=4}
|> Map.add "dignity" { in_spam=1; in_ham=3}
|> Map.add "dijkstra" { in_spam=0; in_ham=5}
|> Map.add "dilemma" { in_spam=0; in_ham=3}
|> Map.add "dime" { in_spam=0; in_ham=4}
|> Map.add "dimebox" { in_spam=0; in_ham=5}
|> Map.add "dimension" { in_spam=0; in_ham=7}
|> Map.add "dimensions" { in_spam=0; in_ham=8}
|> Map.add "diminish" { in_spam=1; in_ham=4}
|> Map.add "diminishing" { in_spam=0; in_ham=3}
|> Map.add "dina" { in_spam=0; in_ham=8}
|> Map.add "dining" { in_spam=1; in_ham=2}
|> Map.add "dinner" { in_spam=0; in_ham=7}
|> Map.add "dinter" { in_spam=0; in_ham=11}
|> Map.add "diplomacy" { in_spam=0; in_ham=5}
|> Map.add "diplomatic" { in_spam=9; in_ham=3}
|> Map.add "diplomats" { in_spam=0; in_ham=4}
|> Map.add "dir" { in_spam=3; in_ham=19}
|> Map.add "dire" { in_spam=0; in_ham=4}
|> Map.add "direct" { in_spam=38; in_ham=31}
|> Map.add "directed" { in_spam=20; in_ham=2}
|> Map.add "directing" { in_spam=0; in_ham=6}
|> Map.add "direction" { in_spam=1; in_ham=21}
|> Map.add "directional" { in_spam=0; in_ham=4}
|> Map.add "directions" { in_spam=4; in_ham=6}
|> Map.add "directly" { in_spam=11; in_ham=58}
|> Map.add "director" { in_spam=15; in_ham=44}
|> Map.add "directories" { in_spam=5; in_ham=22}
|> Map.add "directors" { in_spam=0; in_ham=8}
|> Map.add "directory" { in_spam=7; in_ham=105}
|> Map.add "dirty" { in_spam=4; in_ham=10}
|> Map.add "disability" { in_spam=2; in_ham=2}
|> Map.add "disable" { in_spam=0; in_ham=12}
|> Map.add "disabled" { in_spam=0; in_ham=12}
|> Map.add "disables" { in_spam=0; in_ham=6}
|> Map.add "disabling" { in_spam=0; in_ham=11}
|> Map.add "disagree" { in_spam=0; in_ham=21}
|> Map.add "disagreeable" { in_spam=0; in_ham=4}
|> Map.add "disagreement" { in_spam=0; in_ham=3}
|> Map.add "disappear" { in_spam=0; in_ham=5}
|> Map.add "disappeared" { in_spam=0; in_ham=4}
|> Map.add "disappearing" { in_spam=0; in_ham=4}
|> Map.add "disappears" { in_spam=0; in_ham=3}
|> Map.add "disappointed" { in_spam=1; in_ham=2}
|> Map.add "disaster" { in_spam=0; in_ham=8}
|> Map.add "disbanding" { in_spam=0; in_ham=3}
|> Map.add "disc" { in_spam=1; in_ham=4}
|> Map.add "discard" { in_spam=0; in_ham=3}
|> Map.add "discarded" { in_spam=0; in_ham=4}
|> Map.add "discipline" { in_spam=0; in_ham=7}
|> Map.add "disciplines" { in_spam=0; in_ham=3}
|> Map.add "disclaimer" { in_spam=6; in_ham=9}
|> Map.add "disclose" { in_spam=3; in_ham=4}
|> Map.add "disclosed" { in_spam=4; in_ham=1}
|> Map.add "disclosure" { in_spam=0; in_ham=6}
|> Map.add "disclosures" { in_spam=1; in_ham=2}
|> Map.add "disconnected" { in_spam=2; in_ham=2}
|> Map.add "discotheques" { in_spam=0; in_ham=3}
|> Map.add "discount" { in_spam=14; in_ham=5}
|> Map.add "discourage" { in_spam=1; in_ham=4}
|> Map.add "discourse" { in_spam=1; in_ham=2}
|> Map.add "discover" { in_spam=21; in_ham=27}
|> Map.add "discovered" { in_spam=15; in_ham=28}
|> Map.add "discoveries" { in_spam=3; in_ham=2}
|> Map.add "discovering" { in_spam=5; in_ham=10}
|> Map.add "discovers" { in_spam=0; in_ham=4}
|> Map.add "discovery" { in_spam=11; in_ham=17}
|> Map.add "discreet" { in_spam=4; in_ham=1}
|> Map.add "discriminate" { in_spam=0; in_ham=3}
|> Map.add "discuss" { in_spam=9; in_ham=161}
|> Map.add "discussed" { in_spam=0; in_ham=13}
|> Map.add "discusses" { in_spam=0; in_ham=3}
|> Map.add "discussing" { in_spam=1; in_ham=15}
|> Map.add "discussion" { in_spam=3; in_ham=36}
|> Map.add "discussions" { in_spam=2; in_ham=11}
|> Map.add "disease" { in_spam=6; in_ham=9}
|> Map.add "diseases" { in_spam=0; in_ham=5}
|> Map.add "disgust" { in_spam=0; in_ham=3}
|> Map.add "dish" { in_spam=1; in_ham=6}
|> Map.add "disk" { in_spam=12; in_ham=36}
|> Map.add "disks" { in_spam=0; in_ham=5}
|> Map.add "dislike" { in_spam=0; in_ham=3}
|> Map.add "dismissed" { in_spam=0; in_ham=3}
|> Map.add "disney" { in_spam=0; in_ham=8}
|> Map.add "disobey" { in_spam=0; in_ham=5}
|> Map.add "disorder" { in_spam=0; in_ham=3}
|> Map.add "disorderly" { in_spam=0; in_ham=3}
|> Map.add "disparaging" { in_spam=0; in_ham=5}
|> Map.add "disparity" { in_spam=0; in_ham=3}
|> Map.add "dispatch" { in_spam=0; in_ham=8}
|> Map.add "display" { in_spam=8; in_ham=51}
|> Map.add "displayed" { in_spam=1; in_ham=8}
|> Map.add "displaying" { in_spam=1; in_ham=3}
|> Map.add "displays" { in_spam=0; in_ham=9}
|> Map.add "displaystory" { in_spam=0; in_ham=3}
|> Map.add "disposal" { in_spam=3; in_ham=1}
|> Map.add "disposition" { in_spam=4; in_ham=3}
|> Map.add "dispute" { in_spam=0; in_ham=7}
|> Map.add "disputes" { in_spam=0; in_ham=4}
|> Map.add "disrupt" { in_spam=0; in_ham=3}
|> Map.add "disrupting" { in_spam=0; in_ham=10}
|> Map.add "disruption" { in_spam=0; in_ham=3}
|> Map.add "dissatisfied" { in_spam=0; in_ham=5}
|> Map.add "dissertation" { in_spam=0; in_ham=6}
|> Map.add "dissident" { in_spam=0; in_ham=6}
|> Map.add "dist" { in_spam=2; in_ham=3}
|> Map.add "dist-upgrade" { in_spam=0; in_ham=4}
|> Map.add "distance" { in_spam=5; in_ham=15}
|> Map.add "distant" { in_spam=2; in_ham=8}
|> Map.add "distinct" { in_spam=0; in_ham=5}
|> Map.add "distinction" { in_spam=2; in_ham=15}
|> Map.add "distraction" { in_spam=0; in_ham=5}
|> Map.add "distribute" { in_spam=6; in_ham=11}
|> Map.add "distributed" { in_spam=0; in_ham=31}
|> Map.add "distributing" { in_spam=3; in_ham=4}
|> Map.add "distribution" { in_spam=9; in_ham=40}
|> Map.add "distributor" { in_spam=1; in_ham=3}
|> Map.add "distributors" { in_spam=7; in_ham=1}
|> Map.add "district" { in_spam=2; in_ham=11}
|> Map.add "districts" { in_spam=0; in_ham=4}
|> Map.add "distro" { in_spam=0; in_ham=12}
|> Map.add "distros" { in_spam=0; in_ham=3}
|> Map.add "disturbing" { in_spam=0; in_ham=9}
|> Map.add "dit" { in_spam=2; in_ham=3}
|> Map.add "ditch" { in_spam=0; in_ham=5}
|> Map.add "ditto" { in_spam=0; in_ham=8}
|> Map.add "div" { in_spam=83; in_ham=8}
|> Map.add "dive" { in_spam=0; in_ham=5}
|> Map.add "diveintomark" { in_spam=0; in_ham=47}
|> Map.add "diverse" { in_spam=0; in_ham=5}
|> Map.add "diversity" { in_spam=1; in_ham=9}
|> Map.add "divide" { in_spam=0; in_ham=7}
|> Map.add "divided" { in_spam=1; in_ham=6}
|> Map.add "dividends" { in_spam=0; in_ham=4}
|> Map.add "divine" { in_spam=0; in_ham=3}
|> Map.add "division" { in_spam=2; in_ham=4}
|> Map.add "divorce" { in_spam=0; in_ham=5}
|> Map.add "divx" { in_spam=2; in_ham=6}
|> Map.add "dl'd" { in_spam=0; in_ham=4}
|> Map.add "dlinux" { in_spam=0; in_ham=3}
|> Map.add "dll" { in_spam=0; in_ham=7}
|> Map.add "dma" { in_spam=0; in_ham=16}
|> Map.add "dmca" { in_spam=0; in_ham=9}
|> Map.add "dmodule" { in_spam=0; in_ham=3}
|> Map.add "dna" { in_spam=0; in_ham=4}
|> Map.add "dnfo" { in_spam=0; in_ham=3}
|> Map.add "dns" { in_spam=1; in_ham=28}
|> Map.add "dnsbl" { in_spam=0; in_ham=3}
|> Map.add "doc" { in_spam=1; in_ham=17}
|> Map.add "dock" { in_spam=0; in_ham=3}
|> Map.add "docs" { in_spam=0; in_ham=108}
|> Map.add "doctor" { in_spam=8; in_ham=10}
|> Map.add "doctors" { in_spam=2; in_ham=5}
|> Map.add "doctrine" { in_spam=0; in_ham=7}
|> Map.add "doctype" { in_spam=36; in_ham=6}
|> Map.add "document" { in_spam=47; in_ham=21}
|> Map.add "documentary" { in_spam=1; in_ham=3}
|> Map.add "documented" { in_spam=1; in_ham=13}
|> Map.add "documents" { in_spam=11; in_ham=15}
|> Map.add "dod" { in_spam=0; in_ham=3}
|> Map.add "does" { in_spam=77; in_ham=343}
|> Map.add "doesn't" { in_spam=11; in_ham=272}
|> Map.add "doesnt" { in_spam=0; in_ham=10}
|> Map.add "dog" { in_spam=3; in_ham=20}
|> Map.add "dog'" { in_spam=0; in_ham=3}
|> Map.add "dogs" { in_spam=0; in_ham=4}
|> Map.add "doing" { in_spam=32; in_ham=168}
|> Map.add "doit" { in_spam=0; in_ham=3}
|> Map.add "dollar" { in_spam=12; in_ham=7}
|> Map.add "dollars" { in_spam=57; in_ham=23}
|> Map.add "dom" { in_spam=2; in_ham=5}
|> Map.add "domain" { in_spam=13; in_ham=24}
|> Map.add "domains" { in_spam=10; in_ham=4}
|> Map.add "domestic" { in_spam=1; in_ham=9}
|> Map.add "dominant" { in_spam=0; in_ham=14}
|> Map.add "dominate" { in_spam=1; in_ham=7}
|> Map.add "dominated" { in_spam=0; in_ham=6}
|> Map.add "dominating" { in_spam=0; in_ham=3}
|> Map.add "don" { in_spam=11; in_ham=7}
|> Map.add "don't" { in_spam=108; in_ham=580}
|> Map.add "donald" { in_spam=2; in_ham=3}
|> Map.add "done" { in_spam=24; in_ham=166}
|> Map.add "done'" { in_spam=0; in_ham=5}
|> Map.add "donor" { in_spam=0; in_ham=3}
|> Map.add "donors" { in_spam=0; in_ham=4}
|> Map.add "dont" { in_spam=3; in_ham=27}
|> Map.add "dont'" { in_spam=0; in_ham=3}
|> Map.add "dooce" { in_spam=0; in_ham=5}
|> Map.add "doom" { in_spam=0; in_ham=6}
|> Map.add "doomed" { in_spam=0; in_ham=6}
|> Map.add "door" { in_spam=9; in_ham=17}
|> Map.add "doors" { in_spam=0; in_ham=6}
|> Map.add "dormant" { in_spam=0; in_ham=3}
|> Map.add "dos" { in_spam=2; in_ham=4}
|> Map.add "dose" { in_spam=3; in_ham=2}
|> Map.add "doses" { in_spam=1; in_ham=4}
|> Map.add "dot" { in_spam=9; in_ham=5}
|> Map.add "dot-com" { in_spam=1; in_ham=3}
|> Map.add "dotcom" { in_spam=0; in_ham=3}
|> Map.add "dotcomscoop" { in_spam=0; in_ham=3}
|> Map.add "dots" { in_spam=0; in_ham=4}
|> Map.add "dotted" { in_spam=3; in_ham=1}
|> Map.add "double" { in_spam=10; in_ham=15}
|> Map.add "doubleclick" { in_spam=0; in_ham=6}
|> Map.add "doubt" { in_spam=8; in_ham=43}
|> Map.add "doubts" { in_spam=0; in_ham=3}
|> Map.add "doug" { in_spam=0; in_ham=3}
|> Map.add "doughnuts" { in_spam=0; in_ham=3}
|> Map.add "dougy" { in_spam=0; in_ham=3}
|> Map.add "dover" { in_spam=0; in_ham=6}
|> Map.add "dow" { in_spam=0; in_ham=4}
|> Map.add "down" { in_spam=40; in_ham=205}
|> Map.add "downgrade" { in_spam=0; in_ham=3}
|> Map.add "downgrading" { in_spam=0; in_ham=4}
|> Map.add "downhill" { in_spam=0; in_ham=3}
|> Map.add "download" { in_spam=20; in_ham=41}
|> Map.add "downloadable" { in_spam=3; in_ham=1}
|> Map.add "downloaded" { in_spam=0; in_ham=24}
|> Map.add "downloading" { in_spam=0; in_ham=15}
|> Map.add "downloads" { in_spam=0; in_ham=9}
|> Map.add "downright" { in_spam=1; in_ham=5}
|> Map.add "downsized" { in_spam=0; in_ham=3}
|> Map.add "downstream" { in_spam=0; in_ham=3}
|> Map.add "downtime" { in_spam=0; in_ham=4}
|> Map.add "downtown" { in_spam=1; in_ham=5}
|> Map.add "dozen" { in_spam=0; in_ham=21}
|> Map.add "dozens" { in_spam=4; in_ham=5}
|> Map.add "draft" { in_spam=8; in_ham=4}
|> Map.add "drag" { in_spam=0; in_ham=8}
|> Map.add "dragged" { in_spam=0; in_ham=7}
|> Map.add "dragster" { in_spam=0; in_ham=4}
|> Map.add "draig" { in_spam=0; in_ham=4}
|> Map.add "dramatic" { in_spam=2; in_ham=14}
|> Map.add "dramatically" { in_spam=2; in_ham=7}
|> Map.add "draw" { in_spam=6; in_ham=4}
|> Map.add "drawback" { in_spam=0; in_ham=3}
|> Map.add "drawing" { in_spam=1; in_ham=11}
|> Map.add "drawn" { in_spam=5; in_ham=11}
|> Map.add "dreaded" { in_spam=0; in_ham=4}
|> Map.add "dream" { in_spam=8; in_ham=24}
|> Map.add "dreamed" { in_spam=5; in_ham=1}
|> Map.add "dreaming" { in_spam=5; in_ham=1}
|> Map.add "dreams" { in_spam=10; in_ham=15}
|> Map.add "dress" { in_spam=3; in_ham=2}
|> Map.add "dressed" { in_spam=1; in_ham=3}
|> Map.add "drew" { in_spam=1; in_ham=8}
|> Map.add "dri" { in_spam=1; in_ham=3}
|> Map.add "drink" { in_spam=0; in_ham=7}
|> Map.add "drinking" { in_spam=1; in_ham=6}
|> Map.add "drinks" { in_spam=0; in_ham=7}
|> Map.add "drive" { in_spam=22; in_ham=48}
|> Map.add "driven" { in_spam=4; in_ham=2}
|> Map.add "driver" { in_spam=1; in_ham=36}
|> Map.add "driver's" { in_spam=0; in_ham=4}
|> Map.add "drivers" { in_spam=0; in_ham=28}
|> Map.add "drives" { in_spam=2; in_ham=17}
|> Map.add "driving" { in_spam=5; in_ham=20}
|> Map.add "drm" { in_spam=1; in_ham=3}
|> Map.add "droit" { in_spam=2; in_ham=2}
|> Map.add "drop" { in_spam=6; in_ham=34}
|> Map.add "dropouts" { in_spam=0; in_ham=6}
|> Map.add "dropped" { in_spam=2; in_ham=17}
|> Map.add "dropping" { in_spam=0; in_ham=5}
|> Map.add "dropprivs" { in_spam=0; in_ham=5}
|> Map.add "drops" { in_spam=1; in_ham=4}
|> Map.add "drought" { in_spam=0; in_ham=3}
|> Map.add "drove" { in_spam=2; in_ham=9}
|> Map.add "drs" { in_spam=0; in_ham=4}
|> Map.add "drug" { in_spam=10; in_ham=11}
|> Map.add "drugs" { in_spam=9; in_ham=14}
|> Map.add "drumming" { in_spam=0; in_ham=4}
|> Map.add "drumroll" { in_spam=0; in_ham=4}
|> Map.add "drunk" { in_spam=0; in_ham=6}
|> Map.add "dry" { in_spam=0; in_ham=5}
|> Map.add "dryer" { in_spam=0; in_ham=4}
|> Map.add "dsa" { in_spam=0; in_ham=13}
|> Map.add "dsl" { in_spam=0; in_ham=8}
|> Map.add "dtd" { in_spam=36; in_ham=10}
|> Map.add "dtl" { in_spam=1; in_ham=2}
|> Map.add "dual" { in_spam=0; in_ham=3}
|> Map.add "duane" { in_spam=0; in_ham=3}
|> Map.add "dubbed" { in_spam=0; in_ham=11}
|> Map.add "dubious" { in_spam=1; in_ham=4}
|> Map.add "dublin" { in_spam=0; in_ham=9}
|> Map.add "dubya" { in_spam=0; in_ham=9}
|> Map.add "duck" { in_spam=0; in_ham=4}
|> Map.add "ducks" { in_spam=0; in_ham=3}
|> Map.add "dude" { in_spam=0; in_ham=14}
|> Map.add "dudex" { in_spam=0; in_ham=7}
|> Map.add "due" { in_spam=32; in_ham=64}
|> Map.add "dues" { in_spam=0; in_ham=5}
|> Map.add "dug" { in_spam=0; in_ham=6}
|> Map.add "duh" { in_spam=0; in_ham=6}
|> Map.add "duke" { in_spam=0; in_ham=4}
|> Map.add "dull" { in_spam=0; in_ham=7}
|> Map.add "duly" { in_spam=3; in_ham=2}
|> Map.add "dumb" { in_spam=0; in_ham=18}
|> Map.add "dummy" { in_spam=0; in_ham=4}
|> Map.add "dump" { in_spam=0; in_ham=24}
|> Map.add "dumping" { in_spam=0; in_ham=4}
|> Map.add "duncan" { in_spam=0; in_ham=42}
|> Map.add "dunno" { in_spam=0; in_ham=11}
|> Map.add "duplicate" { in_spam=0; in_ham=3}
|> Map.add "duplicated" { in_spam=0; in_ham=3}
|> Map.add "duplicates" { in_spam=0; in_ham=3}
|> Map.add "duplication" { in_spam=2; in_ham=4}
|> Map.add "duration" { in_spam=3; in_ham=4}
|> Map.add "during" { in_spam=25; in_ham=91}
|> Map.add "dust" { in_spam=0; in_ham=4}
|> Map.add "dutch" { in_spam=1; in_ham=3}
|> Map.add "duty" { in_spam=1; in_ham=8}
|> Map.add "dvd" { in_spam=7; in_ham=28}
|> Map.add "dvd's" { in_spam=5; in_ham=1}
|> Map.add "dvd-rom" { in_spam=2; in_ham=8}
|> Map.add "dvds" { in_spam=1; in_ham=70}
|> Map.add "dwarfs" { in_spam=0; in_ham=3}
|> Map.add "dwf" { in_spam=0; in_ham=9}
|> Map.add "dying" { in_spam=0; in_ham=7}
|> Map.add "dynamic" { in_spam=4; in_ham=11}
|> Map.add "dynamically" { in_spam=0; in_ham=5}
|> Map.add "dynamics" { in_spam=0; in_ham=4}
|> Map.add "dyndns" { in_spam=0; in_ham=4}
|> Map.add "e'print" { in_spam=0; in_ham=9}
|> Map.add "e-book" { in_spam=6; in_ham=0}
|> Map.add "e-business" { in_spam=0; in_ham=7}
|> Map.add "e-commerce" { in_spam=2; in_ham=6}
|> Map.add "e-mail" { in_spam=111; in_ham=56}
|> Map.add "e-mailed" { in_spam=7; in_ham=0}
|> Map.add "e-mails" { in_spam=27; in_ham=5}
|> Map.add "each" { in_spam=49; in_ham=172}
|> Map.add "eager" { in_spam=0; in_ham=11}
|> Map.add "eagerly" { in_spam=0; in_ham=4}
|> Map.add "ear" { in_spam=1; in_ham=3}
|> Map.add "earlier" { in_spam=1; in_ham=50}
|> Map.add "earliest" { in_spam=0; in_ham=9}
|> Map.add "early" { in_spam=4; in_ham=56}
|> Map.add "early-stage" { in_spam=0; in_ham=6}
|> Map.add "earn" { in_spam=24; in_ham=3}
|> Map.add "earned" { in_spam=2; in_ham=4}
|> Map.add "earning" { in_spam=4; in_ham=2}
|> Map.add "earnings" { in_spam=18; in_ham=2}
|> Map.add "earns" { in_spam=2; in_ham=3}
|> Map.add "ears" { in_spam=1; in_ham=8}
|> Map.add "earth" { in_spam=4; in_ham=25}
|> Map.add "earth's" { in_spam=0; in_ham=5}
|> Map.add "earthquake" { in_spam=0; in_ham=4}
|> Map.add "ease" { in_spam=1; in_ham=16}
|> Map.add "easier" { in_spam=8; in_ham=43}
|> Map.add "easiest" { in_spam=4; in_ham=13}
|> Map.add "easily" { in_spam=55; in_ham=58}
|> Map.add "east" { in_spam=7; in_ham=19}
|> Map.add "eastern" { in_spam=1; in_ham=7}
|> Map.add "easy" { in_spam=60; in_ham=127}
|> Map.add "easy-to-use" { in_spam=10; in_ham=3}
|> Map.add "eat" { in_spam=3; in_ham=23}
|> Map.add "eaten" { in_spam=0; in_ham=3}
|> Map.add "eating" { in_spam=2; in_ham=4}
|> Map.add "ebay" { in_spam=7; in_ham=10}
|> Map.add "ebayisapi" { in_spam=0; in_ham=4}
|> Map.add "ebedcb" { in_spam=5; in_ham=0}
|> Map.add "ebooks" { in_spam=6; in_ham=0}
|> Map.add "ebuilt" { in_spam=0; in_ham=9}
|> Map.add "ecademy" { in_spam=0; in_ham=3}
|> Map.add "eccentric" { in_spam=0; in_ham=3}
|> Map.add "echo" { in_spam=0; in_ham=16}
|> Map.add "echoes" { in_spam=0; in_ham=3}
|> Map.add "economic" { in_spam=12; in_ham=34}
|> Map.add "economically" { in_spam=0; in_ham=5}
|> Map.add "economics" { in_spam=3; in_ham=28}
|> Map.add "economies" { in_spam=1; in_ham=5}
|> Map.add "economist" { in_spam=0; in_ham=11}
|> Map.add "economy" { in_spam=6; in_ham=40}
|> Map.add "eddie" { in_spam=0; in_ham=3}
|> Map.add "edge" { in_spam=4; in_ham=27}
|> Map.add "edgesuite" { in_spam=0; in_ham=6}
|> Map.add "edificio" { in_spam=0; in_ham=42}
|> Map.add "edinburgh" { in_spam=0; in_ham=11}
|> Map.add "edit" { in_spam=3; in_ham=18}
|> Map.add "edited" { in_spam=0; in_ham=10}
|> Map.add "editing" { in_spam=1; in_ham=18}
|> Map.add "edition" { in_spam=18; in_ham=22}
|> Map.add "editor" { in_spam=31; in_ham=24}
|> Map.add "editorial" { in_spam=0; in_ham=12}
|> Map.add "editors" { in_spam=0; in_ham=9}
|> Map.add "edsger" { in_spam=0; in_ham=5}
|> Map.add "edt" { in_spam=0; in_ham=19}
|> Map.add "edu" { in_spam=6; in_ham=84}
|> Map.add "educate" { in_spam=1; in_ham=2}
|> Map.add "educated" { in_spam=0; in_ham=11}
|> Map.add "education" { in_spam=7; in_ham=18}
|> Map.add "educational" { in_spam=2; in_ham=7}
|> Map.add "educations" { in_spam=0; in_ham=6}
|> Map.add "educator" { in_spam=1; in_ham=2}
|> Map.add "edward" { in_spam=4; in_ham=43}
|> Map.add "eecs" { in_spam=0; in_ham=3}
|> Map.add "eeeeee" { in_spam=4; in_ham=1}
|> Map.add "eegads" { in_spam=0; in_ham=4}
|> Map.add "eek" { in_spam=0; in_ham=3}
|> Map.add "eff" { in_spam=0; in_ham=6}
|> Map.add "effect" { in_spam=10; in_ham=38}
|> Map.add "effective" { in_spam=13; in_ham=24}
|> Map.add "effectively" { in_spam=5; in_ham=20}
|> Map.add "effects" { in_spam=7; in_ham=28}
|> Map.add "efficiency" { in_spam=0; in_ham=23}
|> Map.add "efficient" { in_spam=2; in_ham=22}
|> Map.add "efficiently" { in_spam=0; in_ham=4}
|> Map.add "effort" { in_spam=22; in_ham=38}
|> Map.add "efforts" { in_spam=8; in_ham=32}
|> Map.add "efi" { in_spam=5; in_ham=0}
|> Map.add "egg" { in_spam=0; in_ham=8}
|> Map.add "eggs" { in_spam=0; in_ham=5}
|> Map.add "egh" { in_spam=0; in_ham=6}
|> Map.add "egroups" { in_spam=0; in_ham=88}
|> Map.add "egwn" { in_spam=0; in_ham=16}
|> Map.add "egypt" { in_spam=2; in_ham=7}
|> Map.add "eid" { in_spam=10; in_ham=0}
|> Map.add "eide" { in_spam=0; in_ham=3}
|> Map.add "eight" { in_spam=5; in_ham=7}
|> Map.add "eighth" { in_spam=3; in_ham=2}
|> Map.add "eine" { in_spam=1; in_ham=3}
|> Map.add "eircom" { in_spam=0; in_ham=6}
|> Map.add "eirikur" { in_spam=0; in_ham=23}
|> Map.add "either" { in_spam=24; in_ham=137}
|> Map.add "ejw" { in_spam=0; in_ham=6}
|> Map.add "elaborate" { in_spam=0; in_ham=4}
|> Map.add "eldred" { in_spam=0; in_ham=6}
|> Map.add "elected" { in_spam=0; in_ham=4}
|> Map.add "election" { in_spam=2; in_ham=17}
|> Map.add "elections" { in_spam=1; in_ham=8}
|> Map.add "electoral" { in_spam=0; in_ham=4}
|> Map.add "electric" { in_spam=3; in_ham=7}
|> Map.add "electrical" { in_spam=2; in_ham=9}
|> Map.add "electricity" { in_spam=1; in_ham=2}
|> Map.add "electronic" { in_spam=12; in_ham=62}
|> Map.add "electronics" { in_spam=4; in_ham=8}
|> Map.add "electrons" { in_spam=0; in_ham=3}
|> Map.add "elegant" { in_spam=1; in_ham=2}
|> Map.add "element" { in_spam=3; in_ham=15}
|> Map.add "elementary" { in_spam=1; in_ham=2}
|> Map.add "elements" { in_spam=0; in_ham=8}
|> Map.add "elevator" { in_spam=0; in_ham=6}
|> Map.add "eleventh" { in_spam=0; in_ham=3}
|> Map.add "eli" { in_spam=0; in_ham=5}
|> Map.add "elias" { in_spam=0; in_ham=19}
|> Map.add "eligible" { in_spam=12; in_ham=2}
|> Map.add "eliminate" { in_spam=3; in_ham=10}
|> Map.add "eliminated" { in_spam=5; in_ham=3}
|> Map.add "eliminates" { in_spam=3; in_ham=2}
|> Map.add "eliminating" { in_spam=1; in_ham=4}
|> Map.add "elite" { in_spam=1; in_ham=6}
|> Map.add "eliza" { in_spam=0; in_ham=3}
|> Map.add "ellen" { in_spam=0; in_ham=3}
|> Map.add "else" { in_spam=16; in_ham=162}
|> Map.add "else's" { in_spam=0; in_ham=5}
|> Map.add "elses" { in_spam=0; in_ham=4}
|> Map.add "elsewhere" { in_spam=3; in_ham=24}
|> Map.add "elswhere" { in_spam=0; in_ham=3}
|> Map.add "elusive" { in_spam=0; in_ham=5}
|> Map.add "elz" { in_spam=0; in_ham=23}
|> Map.add "emacs" { in_spam=0; in_ham=9}
|> Map.add "email" { in_spam=259; in_ham=475}
|> Map.add "emailed" { in_spam=4; in_ham=3}
|> Map.add "emailing" { in_spam=3; in_ham=1}
|> Map.add "emails" { in_spam=57; in_ham=14}
|> Map.add "embarrassed" { in_spam=1; in_ham=2}
|> Map.add "embassies" { in_spam=1; in_ham=2}
|> Map.add "embed" { in_spam=6; in_ham=0}
|> Map.add "embedded" { in_spam=0; in_ham=16}
|> Map.add "embedding" { in_spam=0; in_ham=5}
|> Map.add "emblematic" { in_spam=0; in_ham=3}
|> Map.add "embodying" { in_spam=0; in_ham=3}
|> Map.add "embrace" { in_spam=0; in_ham=11}
|> Map.add "emerge" { in_spam=0; in_ham=6}
|> Map.add "emerged" { in_spam=1; in_ham=13}
|> Map.add "emergence" { in_spam=0; in_ham=5}
|> Map.add "emergency" { in_spam=2; in_ham=7}
|> Map.add "emergent" { in_spam=0; in_ham=3}
|> Map.add "emerging" { in_spam=1; in_ham=17}
|> Map.add "emissions" { in_spam=0; in_ham=7}
|> Map.add "emit" { in_spam=1; in_ham=3}
|> Map.add "emitted" { in_spam=0; in_ham=3}
|> Map.add "emotional" { in_spam=4; in_ham=9}
|> Map.add "emotions" { in_spam=0; in_ham=4}
|> Map.add "emphasis" { in_spam=0; in_ham=5}
|> Map.add "emphasize" { in_spam=2; in_ham=4}
|> Map.add "empire" { in_spam=1; in_ham=16}
|> Map.add "empire'" { in_spam=0; in_ham=39}
|> Map.add "empires" { in_spam=2; in_ham=4}
|> Map.add "empirical" { in_spam=0; in_ham=3}
|> Map.add "employ" { in_spam=1; in_ham=6}
|> Map.add "employed" { in_spam=11; in_ham=8}
|> Map.add "employee" { in_spam=0; in_ham=4}
|> Map.add "employees" { in_spam=2; in_ham=6}
|> Map.add "employement" { in_spam=6; in_ham=0}
|> Map.add "employer" { in_spam=0; in_ham=5}
|> Map.add "employers" { in_spam=2; in_ham=3}
|> Map.add "employing" { in_spam=0; in_ham=3}
|> Map.add "employment" { in_spam=10; in_ham=8}
|> Map.add "empty" { in_spam=3; in_ham=28}
|> Map.add "emu" { in_spam=1; in_ham=4}
|> Map.add "emu-config" { in_spam=0; in_ham=3}
|> Map.add "en-us" { in_spam=33; in_ham=3}
|> Map.add "enable" { in_spam=10; in_ham=35}
|> Map.add "enabled" { in_spam=0; in_ham=26}
|> Map.add "enablement" { in_spam=0; in_ham=4}
|> Map.add "enables" { in_spam=3; in_ham=6}
|> Map.add "enabling" { in_spam=1; in_ham=18}
|> Map.add "enacting" { in_spam=0; in_ham=4}
|> Map.add "enc" { in_spam=0; in_ham=3}
|> Map.add "enclosed" { in_spam=2; in_ham=2}
|> Map.add "enclosing" { in_spam=0; in_ham=3}
|> Map.add "encoded" { in_spam=0; in_ham=7}
|> Map.add "encoder" { in_spam=0; in_ham=3}
|> Map.add "encoding" { in_spam=0; in_ham=5}
|> Map.add "encounter" { in_spam=2; in_ham=4}
|> Map.add "encountered" { in_spam=1; in_ham=5}
|> Map.add "encountering" { in_spam=0; in_ham=9}
|> Map.add "encounters" { in_spam=0; in_ham=3}
|> Map.add "encourage" { in_spam=3; in_ham=15}
|> Map.add "encouraged" { in_spam=2; in_ham=8}
|> Map.add "encourages" { in_spam=0; in_ham=5}
|> Map.add "encouraging" { in_spam=0; in_ham=6}
|> Map.add "encrypt" { in_spam=0; in_ham=7}
|> Map.add "encrypted" { in_spam=1; in_ham=11}
|> Map.add "encryption" { in_spam=0; in_ham=11}
|> Map.add "enctype" { in_spam=7; in_ham=0}
|> Map.add "end" { in_spam=32; in_ham=251}
|> Map.add "end-user" { in_spam=0; in_ham=3}
|> Map.add "endanger" { in_spam=2; in_ham=2}
|> Map.add "endangered" { in_spam=0; in_ham=4}
|> Map.add "endeavor" { in_spam=3; in_ham=2}
|> Map.add "endeavors" { in_spam=0; in_ham=11}
|> Map.add "ended" { in_spam=0; in_ham=20}
|> Map.add "endif" { in_spam=2; in_ham=8}
|> Map.add "ending" { in_spam=0; in_ham=9}
|> Map.add "endless" { in_spam=3; in_ham=4}
|> Map.add "endlessly" { in_spam=0; in_ham=5}
|> Map.add "endorsed" { in_spam=0; in_ham=6}
|> Map.add "endowed" { in_spam=2; in_ham=2}
|> Map.add "ends" { in_spam=5; in_ham=13}
|> Map.add "enduring" { in_spam=0; in_ham=11}
|> Map.add "enemies" { in_spam=3; in_ham=5}
|> Map.add "enemy" { in_spam=4; in_ham=9}
|> Map.add "energetic" { in_spam=10; in_ham=0}
|> Map.add "energies" { in_spam=0; in_ham=3}
|> Map.add "energized" { in_spam=0; in_ham=3}
|> Map.add "energy" { in_spam=4; in_ham=28}
|> Map.add "enforce" { in_spam=0; in_ham=6}
|> Map.add "enforcement" { in_spam=1; in_ham=14}
|> Map.add "enforcing" { in_spam=0; in_ham=3}
|> Map.add "eng" { in_spam=0; in_ham=3}
|> Map.add "engage" { in_spam=4; in_ham=8}
|> Map.add "engaged" { in_spam=2; in_ham=10}
|> Map.add "engagement" { in_spam=0; in_ham=4}
|> Map.add "engagements" { in_spam=0; in_ham=6}
|> Map.add "engel" { in_spam=0; in_ham=5}
|> Map.add "engine" { in_spam=5; in_ham=22}
|> Map.add "engineer" { in_spam=1; in_ham=75}
|> Map.add "engineered" { in_spam=0; in_ham=3}
|> Map.add "engineering" { in_spam=4; in_ham=21}
|> Map.add "engineers" { in_spam=1; in_ham=15}
|> Map.add "engines" { in_spam=11; in_ham=26}
|> Map.add "england" { in_spam=7; in_ham=24}
|> Map.add "english" { in_spam=0; in_ham=37}
|> Map.add "enhance" { in_spam=5; in_ham=5}
|> Map.add "enhanced" { in_spam=3; in_ham=11}
|> Map.add "enhancement" { in_spam=1; in_ham=3}
|> Map.add "enhances" { in_spam=1; in_ham=3}
|> Map.add "enigma" { in_spam=0; in_ham=6}
|> Map.add "enjoy" { in_spam=12; in_ham=23}
|> Map.add "enjoyed" { in_spam=1; in_ham=5}
|> Map.add "enjoys" { in_spam=0; in_ham=3}
|> Map.add "enlarge" { in_spam=6; in_ham=0}
|> Map.add "enlighten" { in_spam=1; in_ham=2}
|> Map.add "enormous" { in_spam=1; in_ham=15}
|> Map.add "enough" { in_spam=24; in_ham=161}
|> Map.add "enron" { in_spam=0; in_ham=7}
|> Map.add "ensin" { in_spam=0; in_ham=4}
|> Map.add "ensure" { in_spam=10; in_ham=32}
|> Map.add "ensuring" { in_spam=6; in_ham=4}
|> Map.add "enter" { in_spam=20; in_ham=20}
|> Map.add "entered" { in_spam=5; in_ham=7}
|> Map.add "entering" { in_spam=4; in_ham=5}
|> Map.add "enterprise" { in_spam=3; in_ham=20}
|> Map.add "enterprises" { in_spam=2; in_ham=13}
|> Map.add "enters" { in_spam=0; in_ham=4}
|> Map.add "entertained" { in_spam=6; in_ham=2}
|> Map.add "entire" { in_spam=29; in_ham=52}
|> Map.add "entirely" { in_spam=9; in_ham=42}
|> Map.add "entities" { in_spam=6; in_ham=6}
|> Map.add "entitled" { in_spam=7; in_ham=2}
|> Map.add "entity" { in_spam=1; in_ham=7}
|> Map.add "entrance" { in_spam=0; in_ham=3}
|> Map.add "entrepreneur" { in_spam=2; in_ham=15}
|> Map.add "entries" { in_spam=0; in_ham=21}
|> Map.add "entry" { in_spam=2; in_ham=26}
|> Map.add "env" { in_spam=2; in_ham=8}
|> Map.add "envelope" { in_spam=8; in_ham=3}
|> Map.add "environment" { in_spam=3; in_ham=41}
|> Map.add "environments" { in_spam=0; in_ham=7}
|> Map.add "envision" { in_spam=1; in_ham=2}
|> Map.add "envy" { in_spam=0; in_ham=4}
|> Map.add "epic" { in_spam=0; in_ham=3}
|> Map.add "epicycles" { in_spam=0; in_ham=5}
|> Map.add "episode" { in_spam=0; in_ham=4}
|> Map.add "equal" { in_spam=7; in_ham=20}
|> Map.add "equally" { in_spam=2; in_ham=9}
|> Map.add "equifax" { in_spam=1; in_ham=2}
|> Map.add "equipment" { in_spam=9; in_ham=26}
|> Map.add "equipped" { in_spam=1; in_ham=4}
|> Map.add "equipping" { in_spam=0; in_ham=3}
|> Map.add "equity" { in_spam=13; in_ham=7}
|> Map.add "equiv" { in_spam=5; in_ham=0}
|> Map.add "equivalent" { in_spam=1; in_ham=24}
|> Map.add "era" { in_spam=0; in_ham=11}
|> Map.add "erased" { in_spam=0; in_ham=3}
|> Map.add "erection" { in_spam=4; in_ham=1}
|> Map.add "eric" { in_spam=0; in_ham=7}
|> Map.add "erik" { in_spam=8; in_ham=2}
|> Map.add "eriksson" { in_spam=0; in_ham=15}
|> Map.add "erm" { in_spam=0; in_ham=3}
|> Map.add "ernest" { in_spam=0; in_ham=7}
|> Map.add "err" { in_spam=0; in_ham=7}
|> Map.add "errata" { in_spam=0; in_ham=8}
|> Map.add "error" { in_spam=63; in_ham=125}
|> Map.add "errors" { in_spam=6; in_ham=36}
|> Map.add "errr" { in_spam=0; in_ham=4}
|> Map.add "erudite" { in_spam=0; in_ham=3}
|> Map.add "erupts" { in_spam=0; in_ham=4}
|> Map.add "es-ss" { in_spam=0; in_ham=4}
|> Map.add "es-ssr" { in_spam=0; in_ham=4}
|> Map.add "escalation" { in_spam=1; in_ham=5}
|> Map.add "escape" { in_spam=1; in_ham=9}
|> Map.add "escaped" { in_spam=4; in_ham=4}
|> Map.add "escort" { in_spam=0; in_ham=3}
|> Map.add "escorted" { in_spam=0; in_ham=4}
|> Map.add "esmtp" { in_spam=0; in_ham=3}
|> Map.add "esnet" { in_spam=0; in_ham=3}
|> Map.add "esp" { in_spam=0; in_ham=3}
|> Map.add "especially" { in_spam=5; in_ham=77}
|> Map.add "espouses" { in_spam=0; in_ham=3}
|> Map.add "esr's" { in_spam=0; in_ham=3}
|> Map.add "essay" { in_spam=0; in_ham=9}
|> Map.add "esse" { in_spam=0; in_ham=4}
|> Map.add "essence" { in_spam=2; in_ham=7}
|> Map.add "essential" { in_spam=1; in_ham=14}
|> Map.add "essentially" { in_spam=0; in_ham=23}
|> Map.add "est" { in_spam=6; in_ham=3}
|> Map.add "establish" { in_spam=2; in_ham=18}
|> Map.add "established" { in_spam=3; in_ham=27}
|> Map.add "establishing" { in_spam=1; in_ham=3}
|> Map.add "estate" { in_spam=12; in_ham=10}
|> Map.add "estimate" { in_spam=1; in_ham=6}
|> Map.add "estimated" { in_spam=2; in_ham=4}
|> Map.add "estimates" { in_spam=5; in_ham=5}
|> Map.add "estimation" { in_spam=0; in_ham=4}
|> Map.add "etc" { in_spam=24; in_ham=170}
|> Map.add "eternally" { in_spam=0; in_ham=5}
|> Map.add "ethernet" { in_spam=0; in_ham=11}
|> Map.add "ethical" { in_spam=3; in_ham=7}
|> Map.add "ethics" { in_spam=3; in_ham=3}
|> Map.add "ethiopia" { in_spam=2; in_ham=2}

